#!/usr/bin/env python3
"""Thread X (EXOT), level (ii) -- the even native group and the four-defect cone K4 = (Q3 n X^*) + cone(X).

Run (cwd pt/X/): python3 -I -B x3_g16_k4.py > x3_g16_k4.out 2> x3_g16_k4.err

X = {e_s = E00/2 - T_s/4 : s in {+-1}^2}, T_s the pure table of psi_s = (1, s1 s2, s1, -s2)/2, the joint eigenvector
of X(x)Z (eigenvalue s1) and Y(x)Y (eigenvalue s2). Checked exactly:
  A  the native gates actC D o cnot o actC D' o actT R0 (D, D', R0 signed diagonal with z-entry +1; the landed frame
     family as transcribed by S2 s2_1_native.py:259-277, re-implemented here) with orientation pair (even, even)
     generate a group G16 of order 16 containing cnot; the larger group Gbig generated by cnot and all 32
     orientation-even signed-diagonal locals is computed too (both readings of "the even native class").
  B  every element of Gbig is L or cnot o L with L an even local; even locals are Pauli conjugations, or the full
     transpose composed with Pauli conjugations (symbolic identities), so Gbig <= Aut(Q3); all are signed
     permutations (ipW-orthogonal).
  C  psi_s orthonormal; T_s = E00 + s1 E13 + s2 E22 + s1 s2 E31; pauliW(e_s) = (1/8)(I - 2 psi_s psi_s^T) (the SD1
     hypothesis with beta = 1/8); ipW(e_s, e_t) = (1/4) [s = t]; every element of Gbig permutes {T_s}, hence X.
  D  H1 over the continuous family: ipW(e_s, prodState x y) = (1 - x^T M_s y)/4 with M_s a signed permutation, and
     2(1 - x^T M_s y) = |x - M_s y|^2 + (1 - |x|^2) + (1 - |y|^2), symbolic.
  (E  the multi-defect decomposition, lemma SD2, is tested in x4_k4_selfdual.py, not here.)
  F  the witness pair: e_s is not PSD, ipW(e_s, T_s) = -1/2 < 0 (T_s = P_v, v = 2 psi_s integer).
  G  E0 is not Gbig-invariant: some g in G16 has ipW(E0, g E0) = -1, so no G16-invariant subdual cone contains E0.
Countercontrols: (Bc) the matching test rejects an odd local (actC reflY alone) as an element of Gbig;
(Cc) the permutation test rejects the odd local actC reflY (it maps some T_s outside {T_t});
(Dc) the H1 test rejects the scaled defects e'_s = (1/8)(I - 3 psi_s psi_s^T), which violate the SD1 hypothesis
(negative product value).

DECISION RULES (fixed before the first run; rules, not expected numbers):
  R1. One PASS/FAIL line per check, tagged (identity, enumerate, witness, countercontrol); counts as INFO lines.
  R2. A countercontrol PASSES iff the test REJECTS the control object.
  R3. VERDICT only if all checks pass; else 'X3-G16-K4: FAILED -- <ids>' and exit 1.
  R4. Exact arithmetic only (integers, Fractions, sympy rationals); no floating point, randomness or timing.
"""
import sys
from fractions import Fraction as Fr
from itertools import combinations, product

import sympy as sp

R4 = range(4)
CHECKS = []


def chk(cid, name, ok, kind):
    ok = bool(ok)
    CHECKS.append((cid, kind, ok))
    print(f"{'PASS' if ok else 'FAIL'} {cid}  [{kind}] {name}", flush=True)


def section(t):
    print()
    print(f"== {t}", flush=True)


# ---------------- table maps as signed permutations of the 16 entries: out[i] = sign[i] * w[src[i]], i = 4m + n
SGN_NEG = {(1, 3), (2, 2)}
PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]


def sp_from_fun(f):
    """signed permutation (tuple of (src, sign)) of a linear table map f; asserts f is a signed permutation."""
    out = [None] * 16
    for k in range(16):
        w = [[0] * 4 for _ in R4]
        w[k // 4][k % 4] = 1
        img = [x for row in f(w) for x in row]
        nz = [(i, x) for i, x in enumerate(img) if x != 0]
        assert len(nz) == 1 and nz[0][1] in (1, -1)
        i, x = nz[0]
        assert out[i] is None
        out[i] = (k, x)
    return tuple(out)


def cnot_f(w):
    return [[(-1 if (m, n) in SGN_NEG else 1) * w[PC[m][n]][PT[m][n]] for n in R4] for m in R4]


def actC_f(d):          # signed diagonal d = (d1, d2, d3) on the control index: row m scaled by (1, d)[m]
    h = (1,) + tuple(d)
    return lambda w: [[h[m] * w[m][n] for n in R4] for m in R4]


def actT_f(d):
    h = (1,) + tuple(d)
    return lambda w: [[h[n] * w[m][n] for n in R4] for m in R4]


def mul(A, B):          # A o B
    return tuple((B[A[i][0]][0], A[i][1] * B[A[i][0]][1]) for i in range(16))


def apply(A, w):
    v = [x for row in w for x in row]
    out = [A[i][1] * v[A[i][0]] for i in range(16)]
    return [out[4 * m:4 * m + 4] for m in R4]


ID16 = tuple((i, 1) for i in range(16))


def closure(gens):
    seen, frontier = {ID16}, [ID16]
    while frontier:
        nxt = []
        for g in frontier:
            for h in gens:
                p = mul(h, g)
                if p not in seen:
                    seen.add(p)
                    nxt.append(p)
        frontier = nxt
    return seen


def det3(d):
    return d[0] * d[1] * d[2]


CN = sp_from_fun(cnot_f)
SDz = [(a, b, 1) for a in (1, -1) for b in (1, -1)]
SD = [(a, b, c) for a in (1, -1) for b in (1, -1) for c in (1, -1)]
AC = {d: sp_from_fun(actC_f(d)) for d in SD}
AT = {d: sp_from_fun(actT_f(d)) for d in SD}
ONE = (1, 1, 1)

# =====================================================================================================
section('A  the even native class: G16 and Gbig')
F64 = {}
for D, Dp, R0 in product(SDz, SDz, SDz):
    G = mul(AC[D], mul(AT[ONE], mul(CN, mul(AC[Dp], AT[R0]))))
    F64.setdefault(G, []).append((D, Dp, R0))
ORI = {}
for D, E, Dp, Ep in product(SD, SD, SD, SD):
    G = mul(AC[D], mul(AT[E], mul(CN, mul(AC[Dp], AT[Ep]))))
    if G in F64:
        ORI.setdefault(G, set()).add((det3(Dp) * det3(Ep) == -1, det3(D) * det3(E) == -1))   # (pre_odd, post_odd)
chk('A1', 'each of the distinct native gates (actC D o cnot o actC D\' o actT R0) has exactly one orientation pair '
    'over all 4096 signed-diagonal dressings', len(F64) == 32 and all(len(ORI[G]) == 1 for G in F64), 'enumerate')
EE = [G for G in F64 if ORI[G] == {(False, False)}]
G16 = closure(EE)
chk('A2', '8 native gates are (even, even), cnot among them; they generate a group G16 of order 16 containing cnot',
    len(EE) == 8 and CN in EE and len(G16) == 16 and CN in G16, 'enumerate')
EVEN = {mul(AC[D], AT[E]) for D in SD for E in SD if det3(D) * det3(E) == 1}
GBIG = closure([CN] + sorted(EVEN))
print(f"INFO |even locals| = {len(EVEN)}, |Gbig| = |<cnot, even locals>| = {len(GBIG)}; G16 <= Gbig: "
      f"{G16 <= GBIG}")
chk('A3', '32 distinct orientation-even signed-diagonal locals; G16 is a subgroup of Gbig = <cnot, even locals>',
    len(EVEN) == 32 and G16 <= GBIG, 'enumerate')

# =====================================================================================================
section('B  Gbig <= Aut(Q3): every element is L or cnot o L with L an even local; even locals are Pauli '
        'conjugations or the full transpose composed with them')
chk('B1', 'every element of Gbig equals L or cnot o L with L one of the 32 even locals',
    all(g in EVEN or mul(CN, g) in EVEN for g in GBIG), 'enumerate')
iu = sp.I
SIG = [sp.eye(2), sp.Matrix([[0, 1], [1, 0]]), sp.Matrix([[0, -iu], [iu, 0]]), sp.Matrix([[1, 0], [0, -1]])]
SS = [[sp.kronecker_product(SIG[m], SIG[n]) for n in R4] for m in R4]
wsym = [[sp.Symbol(f'w{m}{n}', real=True) for n in R4] for m in R4]


def pauliW(w):
    return sum((w[m][n] * SS[m][n] for m in R4 for n in R4), sp.zeros(4, 4)) / 4


def same(A, B):
    return all(sp.expand(x) == 0 for x in (A - B))


PW = pauliW(wsym)
ok = True
for d, P in [((1, -1, -1), SIG[1]), ((-1, 1, -1), SIG[2]), ((-1, -1, 1), SIG[3])]:
    U_c, U_t = sp.kronecker_product(P, SIG[0]), sp.kronecker_product(SIG[0], P)
    ok = ok and same(pauliW(apply(AC[d], wsym)), U_c * PW * U_c) and same(pauliW(apply(AT[d], wsym)), U_t * PW * U_t)
chk('B2', 'actC/actT of diag(1,-1,-1), diag(-1,1,-1), diag(-1,-1,1) = conjugation by X, Y, Z on that qubit, symbolic',
    ok, 'identity')
TT = mul(AC[(1, -1, 1)], AT[(1, -1, 1)])
chk('B3', 'actC reflY o actT reflY = full transpose: pauliW(T w) = pauliW(w)^T, symbolic; and every even local with '
    'det D = det E = -1 equals (actC reflY o actT reflY) o (a det +1 local)',
    same(pauliW(apply(TT, wsym)), PW.T)
    and all(mul(TT, mul(AC[tuple(x * y for x, y in zip(D, (1, -1, 1)))], AT[tuple(x * y for x, y in zip(E, (1, -1, 1)))]))
            == mul(AC[D], AT[E]) for D in SD for E in SD if det3(D) == -1 and det3(E) == -1), 'identity')
odd = AC[(1, -1, 1)]
phiW = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]
singlet = sp.Matrix([0, 1, -1, 0])
img = pauliW(apply(odd, phiW))
chk('Bc', 'countercontrol: the odd local actC reflY is rejected: not in Gbig, not of the form L or cnot o L, and it '
    'maps the Bell table phiW to a non-PSD table (<s|.|s> = -1 on the singlet s = |01> - |10>)',
    odd not in GBIG and odd not in EVEN and mul(CN, odd) not in EVEN
    and (singlet.T * img * singlet)[0, 0] == -1, 'countercontrol')

# =====================================================================================================
section('C  the four defects: stabilizer basis, tables, spectra, Gram matrix, permutation by Gbig')
S4 = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
XZm, YYm = SS[1][3], SS[2][2]
PSI = {s: sp.Matrix([1, s[0] * s[1], s[0], -s[1]]) / 2 for s in S4}


def table_of(rho):
    return [[sp.expand((SS[m][n] * rho).trace()) for n in R4] for m in R4]


def tab(*entries):
    w = [[sp.Integer(0)] * 4 for _ in R4]
    for (m, n, c) in entries:
        w[m][n] += c
    return w


T = {s: table_of(PSI[s] * PSI[s].T) for s in S4}
ES = {s: [[sp.Rational(int(m == 0 and n == 0), 2) - T[s][m][n] / 4 for n in R4] for m in R4] for s in S4}


def ipw(a, b):
    return sum(a[m][n] * b[m][n] for m in R4 for n in R4)


chk('C1', 'psi_s orthonormal, X(x)Z psi_s = s1 psi_s, Y(x)Y psi_s = s2 psi_s',
    all((PSI[s].T * PSI[t])[0, 0] == (1 if s == t else 0) for s in S4 for t in S4)
    and all(XZm * PSI[s] == s[0] * PSI[s] and YYm * PSI[s] == s[1] * PSI[s] for s in S4), 'identity')
chk('C2', 'T_s = E00 + s1 E13 + s2 E22 + s1 s2 E31 (pure tables of psi_s)',
    all(T[s] == tab((0, 0, 1), (1, 3, s[0]), (2, 2, s[1]), (3, 1, s[0] * s[1])) for s in S4), 'identity')
chk('C3', 'pauliW(e_s) = (1/8)(I - 2 psi_s psi_s^T) for all four s (SD1 hypothesis, beta = 1/8, g = psi_s)',
    all(same(pauliW(ES[s]), (sp.eye(4) - 2 * PSI[s] * PSI[s].T) / 8) for s in S4), 'identity')
chk('C4', 'ipW(e_s, e_t) = 1/4 if s = t, else 0 (pairwise orthogonal defects; subdual set)',
    all(ipw(ES[s], ES[t]) == (sp.Rational(1, 4) if s == t else 0) for s in S4 for t in S4), 'identity')
TS = [tuple(tuple(r) for r in T[s]) for s in S4]


def permutes(g):
    imgs = [tuple(tuple(r) for r in apply(g, T[s])) for s in S4]
    return sorted(imgs) == sorted(TS)


chk('C5', 'every element of Gbig (hence of G16) permutes {T_s}, hence permutes the defect set X',
    all(permutes(g) for g in GBIG), 'enumerate')
chk('Cc', 'countercontrol: the permutation test rejects the odd local actC reflY (some T_s is mapped outside {T_t})',
    not permutes(odd), 'countercontrol')

# =====================================================================================================
section('D  H1 for K4 over the continuous product family (symbolic)')
xs = [sp.Symbol(f'x{i}', real=True) for i in range(3)]
ys = [sp.Symbol(f'y{i}', real=True) for i in range(3)]
hx, hy = [1] + xs, [1] + ys
prod_xy = [[hx[m] * hy[n] for n in R4] for m in R4]
ok1 = ok2 = True
for s in S4:
    My = [s[0] * ys[2], s[1] * ys[1], s[0] * s[1] * ys[0]]
    xMy = sum(xs[i] * My[i] for i in range(3))
    ok1 = ok1 and sp.expand(ipw(ES[s], prod_xy) - (1 - xMy) / 4) == 0
    sos = (sum((xs[i] - My[i]) ** 2 for i in range(3)) + (1 - sum(t ** 2 for t in xs)) + (1 - sum(t ** 2 for t in ys)))
    ok2 = ok2 and sp.expand(2 * (1 - xMy) - sos) == 0
chk('D1', 'ipW(e_s, prodState x y) = (1 - x^T M_s y)/4 with M_s y = (s1 y3, s2 y2, s1 s2 y1), symbolic', ok1, 'identity')
chk('D2', '2(1 - x^T M_s y) = |x - M_s y|^2 + (1 - |x|^2) + (1 - |y|^2), symbolic (|M_s y| = |y|): every e_s is in '
    'maxCone, so SEP <= Q3 n X^*; cnot X = X (C5) gives cnot SEP <= Q3 n X^* too', ok2, 'identity')
EP = {s: [[sp.Rational(int(m == 0 and n == 0), 2) - 3 * T[s][m][n] / 8 for n in R4] for m in R4] for s in S4}
s0 = (1, 1)
pbad = [[a * b for b in [1, 0, 0, 1]] for a in [1, s0[0], 0, 0]]
chk('Dc', "countercontrol: the H1 test rejects e'_s = (1/8)(I - 3 psi_s psi_s^T) (table E00/2 - 3 T_s/8): "
    "ipW(e'_s, prodState((s1,0,0), (0,0,1))) = -1/4 < 0",
    same(pauliW(EP[s0]), (sp.eye(4) - 3 * PSI[s0] * PSI[s0].T) / 8) and ipw(EP[s0], pbad) == sp.Rational(-1, 4),
    'countercontrol')

# =====================================================================================================
section('F  the witness pair for K4 != Q3; G  E0 is not G16-invariant and not in K4')
chk('F1', 'each e_s is not PSD (psi_s^T pauliW(e_s) psi_s = -1/8) and ipW(e_s, T_s) = -1/2 with T_s = P_v, '
    'v = 2 psi_s an integer vector, pauliW(T_s) = psi_s psi_s^T',
    all((PSI[s].T * pauliW(ES[s]) * PSI[s])[0, 0] == sp.Rational(-1, 8) and ipw(ES[s], T[s]) == sp.Rational(-1, 2)
        and same(pauliW(T[s]), PSI[s] * PSI[s].T) for s in S4), 'witness')
chk('F2', 'each T_s is not a product table and cnot T_s is not a product table (ranks > 1)',
    all(sp.Matrix(T[s]).rank() > 1 and sp.Matrix(apply(CN, T[s])).rank() > 1 for s in S4), 'witness')
E0 = tab((0, 0, 1), (1, 3, 1), (2, 2, -1))
negs = [g for g in G16 if ipw(E0, apply(g, E0)) == -1]
chk('G1', 'some g in G16 has ipW(E0, g E0) = -1: no G16-invariant subdual cone contains E0 (K1 is a level-(i) '
    'model only)', len(negs) > 0, 'witness')
chk('G2', 'ipW(E0, e_(1,-1)) = -1/4 < 0: E0 is not in the self-dual K4 (K1 and K4 are different cones)',
    ipw(E0, ES[(1, -1)]) == sp.Rational(-1, 4), 'witness')

# =====================================================================================================
print()
failed = [c[0] for c in CHECKS if not c[2]]
print('kinds: ' + ', '.join(f"{k} {sum(1 for c in CHECKS if c[1] == k)}"
                            for k in ('identity', 'enumerate', 'witness', 'countercontrol')), flush=True)
if failed:
    print(f"X3-G16-K4: FAILED -- {len(failed)} of {len(CHECKS)}: {', '.join(failed)}", flush=True)
    sys.exit(1)
print(f'VERDICT X3-G16-K4-EXACT -- {len(CHECKS)} checks', flush=True)
