"""Split the green dev module into the stage-1 and stage-2 module texts, with the frozen header.
usage: python3 stage34.py <dev module .lean>   -> writes stage1.lean, stage2.lean beside it, prints
controls.module_label for both, and the per-theorem audit of landed helpers off the provenance list."""
import re, sys, importlib.util, subprocess, json
S = '/tmp/claude-0/-home-user-incompleteness/727ddb71-72ba-5388-a9a1-1413a0433ac0/scratchpad/a34/'
spec = importlib.util.spec_from_file_location('c34', S + 'controls.py'); C = importlib.util.module_from_spec(spec); spec.loader.exec_module(C)
P = json.load(open(S + 'props34.json'))
DOC = '''/-!
# Act 34 — the product-embedded stratum

At act 29's product configuration (`V = Fin 4 × Fin 4`, the ancilla `Fin 1 × Fin 1`, `Γ ≡ 1/16`, the
ordered decomposition `Equiv.refl`), this module studies the product-embedded stratum, the feature
vectors of the products `X ⊠ Y` of two realizable single-carrier tuples.

The feature map of a product tuple is the coordinatewise product of the factors' feature maps under
the index pairing, so inner products multiply; the stratum is the union of the eighty-one tori, the
products of pairs of act 26's nine relabelled Fourier circles, with the incidence generated by the two
`K₃,₃` incidences; act 33's group acts on it factorwise together with the factor exchange; the stratum
is a proper subset of the product normalized set, by an exhibited realizable class with entries in the
fourth roots of unity; and every surjective isometry of the stratum that factorizes through two
single-carrier maps has both factors in act 33's group. The finite parts are decided by the kernel.

The module carries no definition. Every theorem prints its axioms.
-/
'''
src = open(sys.argv[1], encoding='utf-8').read()
head_end = src.index('namespace OIBridge\n')
head = src[:head_end]
assert head.startswith(C.IMPORT)
body = src[head_end:]
new_head = C.IMPORT + '\n' + DOC + '\n'

def cut(text, name):
    m = re.search(r'(?m)^theorem %s :\n' % re.escape(name), text)
    assert m, name
    e = re.search(r'(?m)^#print axioms %s\n\n' % re.escape(name), text[m.start():])
    assert e, name
    piece = text[m.start():m.start() + e.end()]
    return text[:m.start()] + text[m.start() + e.end():], piece

body1, verdict = cut(body, 'a34_stratified')
body1, coroll = cut(body1, 'a34_c_exclusive')
tail = 'end ProductStratum\nend OIBridge\n'
assert body1.endswith(tail)
stage1 = new_head + body1
stage2 = new_head + body1[:-len(tail)] + verdict + coroll + tail
open(S + 'stage1.lean', 'w', encoding='utf-8').write(stage1)
open(S + 'stage2.lean', 'w', encoding='utf-8').write(stage2)
for nm, txt in (('stage1', stage1), ('stage2', stage2)):
    lab, f = C.module_label(txt)
    print(nm, 'label', lab, 'findings', f, 'theorems', len(C.theorems(C.strip_comments(txt))))
    print(nm, 'blob', subprocess.run(['git', 'hash-object', S + nm + '.lean'], capture_output=True, text=True).stdout.strip())

# ---- audit of landed helpers off the provenance list, per theorem
F = 'f307515877a19ad137920824b7d19e74026fb738'
files = subprocess.run(['git', 'ls-tree', '-r', '--name-only', F, 'verification/lean-mathlib/OIBridge/'], capture_output=True, text=True, cwd='/home/user/incompleteness').stdout.split()
names = {}
for p in files:
    s = subprocess.run(['git', 'show', F + ':' + p], capture_output=True, text=True, cwd='/home/user/incompleteness').stdout
    for m in re.finditer(r'(?m)^[ \t]*(?:@\[[^\]\n]*\][ \t]*)?(?:private[ \t]+|protected[ \t]+|noncomputable[ \t]+)*(?:theorem|lemma|def|abbrev)[ \t]+(\S+)', s):
        names.setdefault(m.group(1), p.split('/')[-1][:-5])
PROV = set("""FibreGram GramPhaseEquiv RealizableGram AdmissibleDilationAt sh1_necessity sh1_sufficiency posSemidef_factor_of_rank_le gramPhaseEquiv_refl gramPhaseEquiv_symm gramPhaseEquiv_trans prod_mem_unitaryGroup prod_admissible Reversible FactorizesOnProduct realizable_of_gramPhaseEquiv witness_supply product_cross relabel_product relabel_one vpart_unitary product_realizable product_separations hadamard_z_admissible mixedTriple mixedTriple_gauge mixedTriple_star coord_le_dist geo1_separation_star realizable_entry_ne_zero geo1_separation_single dist_eq_norm_toLp mixedTriple_relabel2 fibreGram_unique relabel2_realizable relabel2_isometry conj_isometry featureVec normalizedSet IsSurjIsometryOn featureVec_ofLp dist_featureVec featureVec_gauge gramPhaseEquiv_of_featureVec_eq featureVec_mem_normalizedSet relabelled_fourier_mem_normalizedSet normalizedSet_eq_iUnion eqOn_affineSpan_of_agree exists_affineIsometryEquiv_of_isSurjIsometryOn a26_0_affine_extension a26_1_circle_count""".split())
ORBIT = {'OrbitGeometryRigidity', 'OrbitGeometryIsometries', 'OrbitGeometrySelector', 'OrbitIsometryClassification', 'OrbitLawGaps', 'OrbitLawRigidityTwisted', 'GramTrajectorySelection', 'TwoSidedGauge', 'DilationChoice', 'IntermediateCrossTimeStructure', 'OrbitIsometryGroup'}
code = C.strip_comments(stage2)
by_helper = {}
for b in re.split(r'(?m)^(?=theorem )', code):
    m = re.match(r'theorem (\S+)', b)
    if not m:
        continue
    proof = b[b.index(':= by') + 5:] if ':= by' in b else b
    for ident in set(re.findall(r"(?<![A-Za-z0-9_'.])[A-Za-z_][A-Za-z0-9_']*", proof)):
        if ident in names and names[ident] in ORBIT and ident not in PROV and not ident.startswith('a34_') and not ident.startswith('a33_'):
            by_helper.setdefault((ident, names[ident]), []).append(m.group(1))
print('\nOFF-LIST HELPERS (module, consumers):')
for (h, f), ts in sorted(by_helper.items()):
    print(' ', h, f, len(ts), ts if len(ts) <= 6 else ts[:6] + ['...'])
