"""P2 — the dense-countable interval [K_d, Q3]: an explicit missing pure state, the rational word for the
closedness-free upper bound, and the interior of K_d.

Usage: python3 -I p2_interval.py <CompositeDimension.lean>

Objects.  D = rotations R(q), q in Q^4 \\ 0 (rational quaternions).  G_D = <cnot, actT R, actC R : R in D>.
K_d = convex cone generated by G_D . {prodState x y : x, y in ball}.  Q3 = image of the PSD cone.

Decision rule (fixed before the first run): verdict INTERVAL-INGREDIENTS-EXACT iff all checks pass:
  2.1 parsed kernel cnot = transfer matrix of Ad(CNOT)                                   [X]+[M]
  2.2 for sample rational q: U~_q has Gaussian-integer entries and Ad(I(x)U~_q)/|q|^2,
      Ad(U~_q(x)I)/|q|^2 equal actT R(q), actC R(q); R(q) rational                     [X]+[M]
  2.3 every word (length <= 3, 9 letters incl. inverses) is a 4x4 matrix over Q(i), its pulled-back
      Segre form is a rank-4 quadratic form, and its dehomogenisation Q_V(1,X,Y,Z) is a nonzero
      polynomial, and so is Q_V(1,a,b,c) for symbolic a,b,c                            [X]
  2.4 psi* = (1, e^sqrt2, e^sqrt3, e^sqrt5) is not a product: Segre(psi*) = e^sqrt5 - e^(sqrt2+sqrt3),
      and sqrt5 != sqrt2+sqrt3 exactly; [Q(sqrt2,sqrt3,sqrt5):Q] = 8 (Q-linear independence, the
      Lindemann-Weierstrass hypothesis)                                                [X]; LW is [L]
  2.5 controls: the Schmidt family (1,0,0,t) is sent to products by CNOT for every t (one transcendental
      parameter is not enough); the twisted cubic (1,t,t^2,t^3) is a product; phiW = cnot(prodState
      xplus z3) is an entangled pure state lying in K_d                                 [X]+[M]
  2.6 int K_d nonempty: 16 rational product states span W 3 (exact rank 16)              [X]
  2.7 the closedness-free upper bound with a RATIONAL word: omega = (16/25)Id - P_psi, psi=(4|00>+3|11>)/5,
      is not PSD (eigenvalue -9/25), and g = actC(R_y rational) o cnot gives the product-effect value
      -9/25 on g omega (so g omega is outside maxCone); countercontrol: same word on P_psi gives 1   [X]+[M]
  2.8 an entangled full-rank state in K_d by explicit G_D decomposition (Werner p = 1/2), with a
      field-neutral witness: F <= 1/2 on all products (symbolic), F = 5/8 on it          [X]
Otherwise INTERVAL-INGREDIENT-FAILED.
"""
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sympy as sp  # noqa: E402
from dlib import (Checks, parse_tables, cnot_mat, cnot_fun, ptm, CNOT, I2, kron, quat_U, quat_R,  # noqa: E402
                  actT_mat, actC_mat, is_gauss_rational, segre, prod_W, vec, unvec, q_of, rho_of,
                  pairval, sharpVec)

C = Checks('P2 interval')
tabs = parse_tables(sys.argv[1])

# 2.1
C.check('2.1 cnot = Ad(CNOT)', cnot_mat(tabs) == ptm(CNOT))

# 2.2
QS = [(1, 1, 0, 0), (2, 1, 2, 0), (1, 2, 3, 4)]
for q in QS:
    U = quat_U(q)
    n = sum(x * x for x in q)
    R = quat_R(q)
    gi = all(is_gauss_rational(z) for z in U)
    rat = all(sp.nsimplify(z).is_rational for z in R)
    okT = ptm(kron(I2, U), n) == actT_mat(R)
    okC = ptm(kron(U, I2), n) == actC_mat(R)
    C.check('2.2 q=%s' % (q,), gi and rat and okT and okC,
            'U~ in Z[i]: %s; R rational: %s; actT: %s; actC: %s' % (gi, rat, okT, okC))

# 2.3 words over Q(i)
letters = [('CNOT', CNOT)]
for q in QS[:2]:
    U = quat_U(q)
    Uh = U.H
    letters += [('A%s' % (q,), kron(U, I2)), ('A%s^-1' % (q,), kron(Uh, I2)),
                ('B%s' % (q,), kron(I2, U)), ('B%s^-1' % (q,), kron(I2, Uh))]
X = sp.symbols('X0:4')
a, b, c = sp.symbols('a b c')
J = sp.Matrix([[0, 0, 0, 1], [0, 0, -1, 0], [0, -1, 0, 0], [1, 0, 0, 0]]) / 2  # psi^T J psi = segre(psi)
C.check('2.3a Segre form matrix', sp.expand((sp.Matrix(X).T * J * sp.Matrix(X))[0, 0]) == segre(X)
        and J.rank() == 4)
nw = 0
bad = []
for L in range(1, 4):
    for w in itertools.product(range(len(letters)), repeat=L):
        V = sp.eye(4)
        for k in w:
            V = letters[k][1] * V
        V = V.applyfunc(sp.expand)
        nw += 1
        if not all(is_gauss_rational(z) for z in V):
            bad.append(('entries', w))
            continue
        QV = (V.T * J * V).applyfunc(sp.expand)
        if QV.rank() != 4:
            bad.append(('rank', w))
        p1 = sp.expand(segre(V * sp.Matrix([1, X[1], X[2], X[3]])))
        p2 = sp.expand(segre(V * sp.Matrix([1, a, b, c])))
        if p1 == 0 or p2 == 0:
            bad.append(('zero', w))
C.check('2.3b words over Q(i), rank-4 pulled-back Segre form, nonzero dehomogenisation', not bad,
        '%d words, %d bad %s' % (nw, len(bad), bad[:2]))

# 2.4 explicit missing state
s2, s3, s5 = sp.sqrt(2), sp.sqrt(3), sp.sqrt(5)
psi_star = [1, sp.exp(s2), sp.exp(s3), sp.exp(s5)]
seg = sp.simplify(segre(psi_star))
C.check('2.4a Segre(psi*) = e^sqrt5 - e^(sqrt2+sqrt3)', sp.simplify(seg - (sp.exp(s5) - sp.exp(s2 + s3))) == 0,
        str(seg))
x = sp.symbols('x')
mp = sp.minimal_polynomial(s2 + s3 - s5, x)
C.check('2.4b sqrt5 != sqrt2+sqrt3 (minimal polynomial of the difference is not x)', mp != x, str(mp))
mp8 = sp.minimal_polynomial(s2 + s3 + s5, x)
C.check('2.4c [Q(sqrt2,sqrt3,sqrt5):Q] = 8', sp.degree(mp8, x) == 8, str(mp8))
C.note('[L] Lindemann-Weierstrass: e^sqrt2, e^sqrt3, e^sqrt5 algebraically independent over Qbar.')
C.note('[W] hence Q_V(psi*) != 0 for every word V (Q_V(1,X,Y,Z) is a nonzero polynomial over Q(i)),')
C.note('    so psi* is no G_D-image of a pure product, so P_psi* (pure, extreme in Q3) is not in K_d.')

# 2.5 controls
t = sp.symbols('t')
C.check('2.5a Schmidt family -> product under CNOT', segre(CNOT * sp.Matrix([1, 0, 0, t])) == 0
        and segre([1, 0, 0, t]) == t)
C.check('2.5b twisted cubic is a product', segre([1, t, t ** 2, t ** 3]) == 0)
xplus, z3 = [1, 0, 0], [0, 0, 1]
phiW = cnot_fun(tabs, prod_W(xplus, z3))
rho = rho_of(phiW)
evs = rho.eigenvals()
ket = CNOT * kron(sp.Matrix([1, 1]) / sp.sqrt(2), sp.Matrix([1, 0]))
C.check('2.5c phiW in K_d is an entangled pure state', rho.rank() == 1 and segre(list(ket)) != 0
        and q_of(ket * ket.H) == phiW, 'eigenvalues %s, segre %s' % (evs, segre(list(ket))))

# 2.6 interior of K_d
pts = [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, -1]]
Mspan = sp.Matrix.hstack(*[vec(prod_W(p, r)) for p in pts for r in pts])
C.check('2.6 16 rational products span W 3', Mspan.rank() == 16)
C.note('[L] Rockafellar Thm 6.3: a convex set with nonempty interior in R^n has int C = int cl C;')
C.note('    with cl K_d = Q3 this gives int K_d = int Q3: every full-rank state is in K_d.')

# 2.7 rational word for the upper bound
psi = sp.Matrix([4, 0, 0, 3]) / 5
P = psi * psi.H
om = q_of(sp.Rational(16, 25) * sp.eye(4) - P)
C.check('2.7a omega not PSD', min(rho_of(om).eigenvals().keys()) == sp.Rational(-9, 25),
        str(rho_of(om).eigenvals()))
Ry = sp.Matrix([[sp.Rational(7, 25), 0, -sp.Rational(24, 25)], [0, 1, 0], [sp.Rational(24, 25), 0, sp.Rational(7, 25)]])
bloch = sp.Matrix([sp.Rational(24, 25), 0, sp.Rational(7, 25)])
C.check('2.7b R_y rational rotation sending (24/25,0,7/25) to e_z', Ry * Ry.T == sp.eye(3) and Ry.det() == 1
        and Ry * bloch == sp.Matrix([0, 0, 1]))
g = actC_mat(Ry) * cnot_mat(tabs)
gom = unvec(g * vec(om))
val = pairval(sharpVec(z3), sharpVec(z3), gom)
C.check('2.7c value on g omega = -9/25 (outside maxCone)', val == sp.Rational(-9, 25), str(val))
gP = unvec(g * vec(q_of(P)))
C.check('2.7d countercontrol: same word on P_psi gives 1', pairval(sharpVec(z3), sharpVec(z3), gP) == 1)

# 2.8 explicit interior entangled point of K_d
werner = (q_of(ket * ket.H) + prod_W([0, 0, 0], [0, 0, 0])) / 2
x1, x2, x3, y1, y2, y3 = sp.symbols('x1:4 y1:4')
F = lambda w: (w[0, 0] + w[1, 1] - w[2, 2] + w[3, 3]) / 4  # noqa: E731
Fprod = sp.expand(F(prod_W([x1, x2, x3], [y1, y2, y3])))
C.check('2.8a F on products = (1 + x1y1 - x2y2 + x3y3)/4 (<= 1/2 by Cauchy-Schwarz on balls)',
        sp.expand(Fprod - (1 + x1 * y1 - x2 * y2 + x3 * y3) / 4) == 0)
C.check('2.8b Werner(1/2) = (cnot(prodState xplus z3) + prodState 0 0)/2 in K_d, F = 5/8, full rank',
        F(werner) == sp.Rational(5, 8) and rho_of(werner).rank() == 4,
        'eigenvalues %s' % rho_of(werner).eigenvals())

C.summary('INTERVAL-INGREDIENTS-EXACT', 'INTERVAL-INGREDIENT-FAILED')
