#!/usr/bin/env python3
"""Thread C (FOUR-COMP) -- c1: cone-level exact checks for the four-copy interface FCC.

Research only. Exact arithmetic (sympy Rationals and Gaussian rationals); no floating point, no randomness, no time in
stdout. Reads three landed Lean sources and two design sources read-only, to check the transcription of the tables and
of the statements the checks rest on. Usage:
    python3 -I -B c1_cone_level.py <base>/verification/lean-mathlib/OIBridge <inputs>/fourcopy

Conventions (transcribed; S0 checks them): tables W 3 = 4x4, index 0 the unit; hom x = (1, x); prodState x y =
hom x hom y^T; homMap R = diag(1, R); actC R w = homMap R . w; actT R w = w . homMap R^T; reflY = diag(1, -1, 1), so
D := homMap reflY = diag(1, 1, -1, 1); cnot w (m, n) = sgn(m, n) w(pc(m, n), pt(m, n)); ipW E X = sum E_mn X_mn;
fourVal X Y E F = sum X_ab Y_cd E_ac F_bd (X on tokens 01, Y on 23, E on 02, F on 13); the famII value
g2 e f L L' = sum e_ab f_cd L_ac L'_bd (L on 02, L' on 13, e on 01, f on 23); pauliW w = (1/4) sum w_mn s_m (x) s_n,
opW E = sum E_mn s_m (x) s_n with s = (I, X, Y, Z); Q3 = {w : pauliW w >= 0}; dualW Q3 = {E : opW E >= 0} (landed
probe note D.W); twin = actT reflY '' Q3.

FCC(K01, K23, K02, K13) (FourCopyDefs.lean): famI: fourVal X Y E F >= 0 for X in K01, Y in K23, E in dualW K02,
F in dualW K13; famII: g2 e f L L' >= 0 for L in K02, L' in K13, e in dualW K01, f in dualW K23.

DECISION RULE (fixed before the first run). Each check prints PASS or FAIL. A check of kind [countercontrol] PASSES
exactly when the mutated object gives the opposite verdict (it must fail the property the paired check certifies).
The script prints 'VERDICT C1-CONE-LEVEL-EXACT' if and only if every check passes; otherwise it prints
'VERDICT NOT RENDERED' with the failed ids and exits 1. Membership claims that rest on a standard fact (the Kronecker
product of PSD matrices is PSD; a dual cone is unchanged by an ipW-isometry applied to both sides; a cone generated by
a compact base not containing 0 is closed) are printed as NOTE [written] lines and are not checks.

Sections:
  S0  transcription of the landed tables and of the design statements used.
  S1  identities: the two contraction forms, the sign charts, the partial transposes, cnot as an ipW-isometric
      involution, and the reflection conjugates of cnot.
  S2  the mixed assignment (Q3, Q3, Q3, twin): famI and famII both fail, with memberships.
  S3  the sixteen twist patterns of {Q3, twin}^4: the per-token transport identity, the coboundary enumeration, an
      exact negative witness for every odd pattern.
  S4  the tree (sub-plaquette) obstruction: on every proper subset of the four pairs the mixed assignment is a chart
      transform of uniform Q3 with cnot gates.
  S5  the entangled core: famI and famII with any separable argument reduce to pairings of Lorentz vectors.
  S6  the uniform foil K_c = cone(SEP u cnot SEP): a cnot-invariant effect E0 outside dualW Q3, and FCC failures for
      uniform K_c, for (Q3, Q3, K_c, K_c) (famI) and for (K_c, K_c, Q3, Q3) (famII).
"""
import re
import sys
from itertools import product
from pathlib import Path

import sympy as sp

Q = sp.Rational
iu = sp.I
R4 = range(4)
CHECKS = []


def chk(cid, name, ok, kind, detail=''):
    ok = bool(ok)
    CHECKS.append((cid, kind, ok))
    print(f"{'PASS' if ok else 'FAIL'} {cid}  [{kind}] {name}" + (f" -- {detail}" if detail else ''), flush=True)


def note(cid, text):
    print(f"NOTE [written] {cid}  -- {text}", flush=True)


def section(title):
    print()
    print(f"== {title}", flush=True)


def ex(v):
    return sp.expand(v)


def zero(v):
    return ex(v) == 0


def mzero(M):
    return all(ex(v) == 0 for v in M)


if len(sys.argv) != 3:
    print('usage: c1_cone_level.py <OIBridge dir> <inputs/fourcopy dir>')
    sys.exit(2)
OIB = Path(sys.argv[1])
FCP = Path(sys.argv[2])

# ---------------------------------------------------------------------------------------------------------------
PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]
NEG = {(1, 3), (2, 2)}


def sgn(m, n):
    return -1 if (m, n) in NEG else 1


def cnot(w):
    return sp.Matrix(4, 4, lambda m, n: sgn(m, n) * w[PC[m][n], PT[m][n]])


Dg = sp.diag(1, 1, -1, 1)          # homMap reflY
I4 = sp.eye(4)
phiW = sp.diag(1, 1, -1, 1)
idW = sp.eye(4)
sing4 = sp.diag(1, -1, -1, -1)
chainW = sp.Matrix([[1, 0, 0, 1], [1, 0, 0, -1], [0, 0, 0, 0], [0, 0, 0, 0]])
E00 = sp.zeros(4, 4)
E00[0, 0] = 1


def hom(x):
    return sp.Matrix([1] + list(x))


def prodState(x, y):
    return hom(x) * hom(y).T


def actC_refl(w):
    return Dg * w


def actT_refl(w):
    return w * Dg


def cnotTw(w):
    return actT_refl(cnot(actT_refl(w)))


def ipW(E, X):
    return sum(E[m, n] * X[m, n] for m in R4 for n in R4)


def fourVal(X, Y, E, F):
    return sum(X[a, b] * Y[c, d] * E[a, c] * F[b, d] for a, b, c, d in product(R4, repeat=4))


def g2(e, f, L, Lp):
    return sum(e[a, b] * f[c, d] * L[a, c] * Lp[b, d] for a, b, c, d in product(R4, repeat=4))


S = [sp.eye(2), sp.Matrix([[0, 1], [1, 0]]), sp.Matrix([[0, -iu], [iu, 0]]), sp.Matrix([[1, 0], [0, -1]])]


def kron(A, B):
    return sp.kronecker_product(A, B)


SS = [[kron(S[m], S[n]) for n in R4] for m in R4]


def pauliW(w):
    out = sp.zeros(4, 4)
    for m in R4:
        for n in R4:
            if w[m, n] != 0:
                out += w[m, n] * SS[m][n]
    return out / 4


def opW(E):
    return 4 * pauliW(E)


def dag(M):
    return M.conjugate().T


def trace_prod(A, B):
    n = A.shape[0]
    return sum(A[i, j] * B[j, i] for i in range(n) for j in range(n))


def coords(M):
    """the table w with pauliW(w) = M, for a Hermitian 4x4 M: w_mn = tr(M s_m (x) s_n)"""
    return sp.Matrix(4, 4, lambda m, n: ex(trace_prod(M, SS[m][n])))


def pt2(M):
    out = sp.zeros(4, 4)
    for i1, j1, i2, j2 in product(range(2), repeat=4):
        out[2 * i1 + i2, 2 * j1 + j2] = M[2 * i1 + j2, 2 * j1 + i2]
    return out


def pt1(M):
    out = sp.zeros(4, 4)
    for i1, j1, i2, j2 in product(range(2), repeat=4):
        out[2 * i1 + i2, 2 * j1 + j2] = M[2 * j1 + i2, 2 * i1 + j2]
    return out


def is_rank1_projector(P):
    return mzero(P - dag(P)) and mzero(P * P - P) and P.rank() == 1


def symtab(name):
    return sp.Matrix(4, 4, lambda m, n: sp.Symbol(f'{name}{m}{n}', real=True))


def symvec(name, k, start=0):
    return [sp.Symbol(f'{name}{i}', real=True) for i in range(start, start + k)]


def Dpow(k):
    return Dg if k else I4


# ===============================================================================================================
section('S0  transcription')

CD = (OIB / 'CompositeDimension.lean').read_text(encoding='utf-8')
KG = (OIB / 'K2Guard.lean').read_text(encoding='utf-8')
FDEF = (FCP / 'FourCopyDefs.lean').read_text(encoding='utf-8')
FCORE = (FCP / 'FourCopyCore.lean').read_text(encoding='utf-8')
FHEAD = (FCP / 'FourCopyHeadline.lean').read_text(encoding='utf-8')

msg = re.search(r'^def sgn \(μ ν : Fin 4\) : ℝ := if \(μ = (\d) ∧ ν = (\d)\) ∨ \(μ = (\d) ∧ ν = (\d)\) '
                r'then -1 else 1$', CD, re.M)
neg_src = {(int(msg.group(1)), int(msg.group(2))), (int(msg.group(3)), int(msg.group(4)))} if msg else None
chk('S0.sgn', 'landed sgn is -1 exactly at (1, 3) and (2, 2)', neg_src == NEG, 'source')


def lean_table(nm):
    mm = re.search(rf'^def {nm} : Fin 4 → Fin 4 → Fin 4\n((?:  \|.*\n){{4}})', CD, re.M)
    if not mm:
        return None
    T = [[None] * 4 for _ in R4]
    for a, b, v in re.findall(r'\|\s*(\d),\s*(\d)\s*=>\s*(\d)', mm.group(1)):
        T[int(a)][int(b)] = int(v)
    return T


chk('S0.pcpt', 'landed pc and pt tables', lean_table('pc') == PC and lean_table('pt') == PT, 'source')
chk('S0.phiW', 'landed phiW = diag(1, 1, -1, 1)',
    'def phiW : W 3 := fun μ ν => if μ = ν then (if μ = 2 then -1 else 1) else 0' in CD, 'source')
chk('S0.reflY', 'landed reflY = diag(1, -1, 1)', 'toFun x := fun i => (![1, -1, 1] : Fin 3 → ℝ) i * x i' in KG,
    'source')
chk('S0.fourVal', 'design fourVal = sum X a b * Y c d * E a c * F b d (FourCopyCore)',
    'def fourVal (X Y E F : W 3) : ℝ := ∑ a, ∑ b, ∑ c, ∑ d, X a b * Y c d * E a c * F b d' in FCORE, 'source')
chk('S0.fcc', 'design FCC: famI 0 <= ipW X (tabMul (tabMul E Y) (tabT F)), famII 0 <= ipW e (tabMul (tabMul L f) '
    '(tabT L\'))', '0 ≤ ipW X (tabMul (tabMul E Y) (tabT F))' in FDEF
    and "0 ≤ ipW e (tabMul (tabMul L f) (tabT L'))" in FDEF
    and 'famI : ∀ X ∈ K01, ∀ Y ∈ K23, ∀ E ∈ dualW K02, ∀ F ∈ dualW K13,' in FDEF
    and 'famII : ∀ L ∈ K02, ∀ L\' ∈ K13, ∀ e ∈ dualW K01, ∀ f ∈ dualW K23,' in FDEF, 'source')
chk('S0.head', 'design headline kt4_forward_ie1 takes H : KT4Core (K .p01) (K .p23) (K .p02) (K .p13) V',
    '(H : KT4Core (K .p01) (K .p23) (K .p02) (K .p13) V) :' in FHEAD
    and 'theorem kt4_forward_ie1' in FHEAD, 'source')

# ===============================================================================================================
section('S1  identities')

Xg, Yg, Eg, Fg, Wg = symtab('X'), symtab('Y'), symtab('E'), symtab('F'), symtab('W')
chk('I1', 'fourVal X Y E F = ipW X (E Y F^T) = ipW E (X F Y^T), symbolic',
    zero(fourVal(Xg, Yg, Eg, Fg) - ipW(Xg, Eg * Yg * Fg.T)) and zero(fourVal(Xg, Yg, Eg, Fg) - ipW(Eg, Xg * Fg * Yg.T)),
    'identity')
chk('I2', 'g2 e f L L\' = ipW e (L f L\'^T), symbolic', zero(g2(Eg, Fg, Xg, Yg) - ipW(Eg, Xg * Fg * Yg.T)), 'identity')
ok_i3 = all(zero(ipW(Eg, Dpow(a) * Wg * Dpow(b)) - ipW(Dpow(a) * Eg * Dpow(b), Wg)) for a in (0, 1) for b in (0, 1))
chk('I3', 'ipW E (D^a W D^b) = ipW (D^a E D^b) W for a, b in {0, 1} (the sign charts are ipW-isometric involutions)',
    ok_i3 and Dg * Dg == I4, 'identity')
rhoS = pauliW(Wg)
chk('I4', 'pauliW (W D) = (pauliW W)^{T_2}, pauliW (D W) = (pauliW W)^{T_1}, pauliW (D W D) = (pauliW W)^T, symbolic',
    mzero(pauliW(actT_refl(Wg)) - pt2(rhoS)) and mzero(pauliW(actC_refl(Wg)) - pt1(rhoS))
    and mzero(pauliW(Dg * Wg * Dg) - rhoS.T), 'identity')
note('I4W', 'by I4 the twin actT reflY Q3 is the partial-transpose image (token 2 of the pair) of Q3, actC reflY Q3 is '
     'the partial-transpose image on token 1, and since rho^{T_1} = (rho^{T_2})^T and transposition preserves PSD, '
     'actC reflY Q3 = twin; D Q3 D = Q3; by I3 dualW (D^a K D^b) = D^a (dualW K) D^b, so dualW twin = actT reflY '
     '(dualW Q3).')
chk('I5', 'cnot is an involution and ipW-isometric: cnot (cnot W) = W and ipW E (cnot W) = ipW (cnot E) W, symbolic',
    mzero(cnot(cnot(Wg)) - Wg) and zero(ipW(Eg, cnot(Wg)) - ipW(cnot(Eg), Wg)), 'identity')
chk('I6', 'reflection conjugates of cnot: D cnot(D W D) D = cnot W, and D cnot(D W) = cnot(W D) D = cnotTw W, '
    'symbolic', mzero(Dg * cnot(Dg * Wg * Dg) * Dg - cnot(Wg)) and mzero(Dg * cnot(Dg * Wg) - cnotTw(Wg)), 'identity')
chk('I6c', 'countercontrol: D cnot(W) is not cnot(D W) (a one-sided reflection does not commute with cnot)',
    not mzero(Dg * cnot(Wg) - cnot(Dg * Wg)), 'countercontrol')

# ===============================================================================================================
section('S2  the mixed assignment (Q3, Q3, Q3, twin)')

Lp = sp.diag(1, -1, 1, -1)                    # = actT reflY sing4
F_tw = Lp / 4
ok_m = is_rank1_projector(pauliW(phiW)) and is_rank1_projector(opW(phiW / 4))
ok_m = ok_m and actT_refl(sing4) == Lp and is_rank1_projector(pauliW(sing4))
ok_m = ok_m and actT_refl(F_tw) == sing4 / 4 and is_rank1_projector(opW(sing4 / 4))
chk('W1', 'memberships: phiW in Q3; phiW/4 in dualW Q3; L\' = diag(1,-1,1,-1) = actT reflY sing4 in twin; '
    'L\'/4 = actT reflY (sing4/4) in dualW twin (rank-one projectors)', ok_m, 'witness')
v1 = fourVal(phiW, phiW, phiW / 4, F_tw)
chk('W2', 'famI fails: fourVal phiW phiW (phiW/4) (L\'/4) = -1/8 (X in K01 = Q3, Y in K23 = Q3, E in dualW K02, '
    'F in dualW K13 = dualW twin)', v1 == Q(-1, 8), 'witness', f'value {v1}')
v2 = g2(phiW / 4, phiW / 4, phiW, Lp)
chk('W3', 'famII fails: g2 (phiW/4) (phiW/4) phiW L\' = -1/8 (L in K02 = Q3, L\' in K13 = twin, e, f in dualW Q3)',
    v2 == Q(-1, 8), 'witness', f'value {v2}')
chk('W2c', 'countercontrol: famI at the same states with F = phiW/4 (in dualW Q3) is >= 0',
    fourVal(phiW, phiW, phiW / 4, phiW / 4) >= 0, 'countercontrol', f'value {fourVal(phiW, phiW, phiW / 4, phiW / 4)}')
chk('W3c', 'countercontrol: famII with L\' = phiW (in Q3) is >= 0', g2(phiW / 4, phiW / 4, phiW, phiW) >= 0,
    'countercontrol', f'value {g2(phiW / 4, phiW / 4, phiW, phiW)}')
note('W.R', 'both families of FCC fail on the mixed assignment at -1/8, so any premise that yields famI alone, or '
     'famII alone, already excludes it.')

# ===============================================================================================================
section('S3  the sixteen twist patterns of {Q3, twin}^4 (pairs in the order 01, 23, 02, 13)')

ok_t = True
for s in product((0, 1), repeat=4):
    s0, s1, s2, s3 = s
    lhs1 = fourVal(Dpow(s0) * Xg * Dpow(s1), Dpow(s2) * Yg * Dpow(s3), Dpow(s0) * Eg * Dpow(s2),
                   Dpow(s1) * Fg * Dpow(s3))
    lhs2 = g2(Dpow(s0) * Eg * Dpow(s1), Dpow(s2) * Fg * Dpow(s3), Dpow(s0) * Xg * Dpow(s2), Dpow(s1) * Yg * Dpow(s3))
    ok_t = ok_t and zero(lhs1 - fourVal(Xg, Yg, Eg, Fg)) and zero(lhs2 - g2(Eg, Fg, Xg, Yg))
chk('T1', 'per-token transport: for all 16 s, fourVal and g2 are unchanged when the table of pair (i, j) is replaced by '
    'D^{s_i} . D^{s_j} (symbolic)', ok_t, 'identity')
chk('T1c', 'countercontrol: a sign chart applied to X alone changes fourVal', not zero(
    fourVal(Dg * Xg, Yg, Eg, Fg) - fourVal(Xg, Yg, Eg, Fg)), 'countercontrol')
EDGES = {'01': (0, 1), '23': (2, 3), '02': (0, 2), '13': (1, 3)}
ORDER = ['01', '23', '02', '13']


def cob(s):
    return tuple(s[EDGES[e][0]] ^ s[EDGES[e][1]] for e in ORDER)


cobs = {cob(s) for s in product((0, 1), repeat=4)}
pats = list(product((0, 1), repeat=4))
even = [t for t in pats if sum(t) % 2 == 0]
chk('T2', 'the coboundaries are exactly the 8 even patterns (enumeration over the 16 s)',
    cobs == set(even) and len(even) == 8, 'enumerate')
ok_odd = True
vals_odd = set()
for t in pats:
    if sum(t) % 2 == 0:
        continue
    # t = (0, 0, 0, 1) + cob(s): find s
    base = (0, 0, 0, 1)
    s = next(s for s in product((0, 1), repeat=4) if tuple(base[i] ^ cob(s)[i] for i in range(4)) == t)
    s0, s1, s2, s3 = s
    X_ = Dpow(s0) * phiW * Dpow(s1)
    Y_ = Dpow(s2) * phiW * Dpow(s3)
    E_ = Dpow(s0) * (phiW / 4) * Dpow(s2)
    F_ = Dpow(s1) * F_tw * Dpow(s3)
    w1 = fourVal(X_, Y_, E_, F_)
    e_ = Dpow(s0) * (phiW / 4) * Dpow(s1)
    f_ = Dpow(s2) * (phiW / 4) * Dpow(s3)
    L_ = Dpow(s0) * phiW * Dpow(s2)
    Lp_ = Dpow(s1) * Lp * Dpow(s3)
    w2 = g2(e_, f_, L_, Lp_)
    vals_odd.add((w1, w2))
    ok_odd = ok_odd and w1 < 0 and w2 < 0
chk('T3', 'every odd pattern has transported witnesses at which famI and famII are negative', ok_odd and len(vals_odd)
    == 1, 'enumerate', f'values {sorted(vals_odd)}')
note('T.W', 'membership of the transported witnesses: D^a Q3 D^b is Q3 for a = b and twin for a != b (I4W), and the '
     'transported witnesses sit in the cones of the transported pattern t = (0,0,0,1) + cob(s). Even patterns: FCC '
     'holds by T1 and FCC for uniform Q3 (landed F2, F3 with the Kronecker product of PSD matrices, note F.Q3). So on '
     '{Q3, twin}^4, FCC holds exactly for the 8 coboundary patterns: there are per-token reflection charts in which '
     'all four cones are Q3 (this is the design package\'s open fourCopyCoherent_chart, here by T1).')

# ===============================================================================================================
section('S4  the tree obstruction (proper subsets of the 4-cycle)')

tau_tok = (0, 0, 0, 1)
ok_tree = True
for k in range(4):
    sub = [i for i in range(4) if i != k]
    ok_tree = ok_tree and any(all(cob(s)[i] == tau_tok[i] for i in sub) for s in product((0, 1), repeat=4))
chk('R1', 'on each of the four 3-pair subsets, the twist pattern of (Q3, Q3, Q3, twin) agrees with a coboundary',
    ok_tree, 'enumerate')
chk('R1c', 'countercontrol: on all four pairs no coboundary agrees with it', not any(
    cob(s) == tau_tok for s in product((0, 1), repeat=4)), 'countercontrol')


def chart(a, b, w):
    return Dpow(a) * w * Dpow(b)


ok_g = True
for a, b in product((0, 1), repeat=2):
    conj = chart(a, b, cnot(chart(a, b, Wg)))
    target = cnot(Wg) if a == b else cnotTw(Wg)
    ok_g = ok_g and mzero(conj - target)
chk('R2', 'gate transport: chart(a,b) . cnot . chart(a,b) is cnot for a = b and cnotTw for a != b, symbolic',
    ok_g, 'identity')
note('R.W', 'the obstruction (written). Let Pi be a conjunction of predicates Pi_k, each reading only the data (cones, '
     'gates, locals) of a proper subset S_k of the four pairs and each invariant under per-token reflection charts. '
     'If Pi holds at the quantum data (uniform Q3, cnot gates, identity locals), it holds at the data of M_tok '
     '(cones Q3, Q3, Q3, twin; gates cnot, cnot, cnot, cnotTw; B_13 = B\'_13 = reflY): by R1 there is s with '
     'cob(s) = tau on S_k, and by I4W and R2 the chart (reflY^{s_t}) maps the quantum data on S_k onto the M_tok data '
     'on S_k. FCC fails for M_tok (S2). So no such Pi implies FCC: a principle that excludes the mixed assignment '
     'must couple all four pairs or depend on the charts.')

# ===============================================================================================================
section('S5  the entangled core: one separable argument makes famI and famII automatic')

p, q, u, wv = [sp.Matrix(symvec(nm, 4)) for nm in ('p', 'q', 'u', 'v')]
ok_e = zero(fourVal(p * q.T, Yg, Eg, Fg) - (p.T * Eg * (Yg * Fg.T * q))[0, 0])
ok_e = ok_e and zero(fourVal(Xg, p * q.T, Eg, Fg) - ((Eg * p).T * Xg * (Fg * q))[0, 0])
ok_e = ok_e and zero(fourVal(Xg, Yg, u * wv.T, Fg) - ((Xg.T * u).T * Fg * (Yg.T * wv))[0, 0])
ok_e = ok_e and zero(fourVal(Xg, Yg, Eg, u * wv.T) - ((Xg * u).T * Eg * (Yg * wv))[0, 0])
chk('E1', 'famI with one rank-one argument: fourVal (p q^T) Y E F = p^T E (Y F^T q), fourVal X (p q^T) E F = '
    '(E p)^T X (F q), fourVal X Y (u v^T) F = (X^T u)^T F (Y^T v), fourVal X Y E (u v^T) = (X u)^T E (Y v), symbolic',
    ok_e, 'identity')
ok_e2 = zero(g2(p * q.T, Fg, Xg, Yg) - (p.T * Xg * (Fg * Yg.T * q))[0, 0])
ok_e2 = ok_e2 and zero(g2(Eg, p * q.T, Xg, Yg) - ((Xg * p).T * Eg * (Yg * q))[0, 0])
ok_e2 = ok_e2 and zero(g2(Eg, Fg, u * wv.T, Yg) - ((Eg.T * u).T * Yg * (Fg.T * wv))[0, 0])
ok_e2 = ok_e2 and zero(g2(Eg, Fg, Xg, u * wv.T) - ((Eg * u).T * Xg * (Fg * wv))[0, 0])
chk('E2', 'famII with one rank-one argument: the four analogous reductions of g2, symbolic', ok_e2, 'identity')
chk('E1c', 'countercontrol: without the transpose, fourVal (p q^T) Y E F is not p^T E (Y F q)', not zero(
    fourVal(p * q.T, Yg, Eg, Fg) - (p.T * Eg * (Yg * Fg * q))[0, 0]), 'countercontrol')
note('E.W', 'with every cone admissible (products in K, K in maxCone) every state table and every dual table lies in '
     'maxCone = {M : a^T M b >= 0 for a, b in L}, and a maxCone table maps L into L (b^T M a >= 0 for all b in L means '
     'M a in L* = L). So each reduced expression is a^T M b with a, b in L and M in maxCone, hence >= 0; SEP is the '
     'cone generated by such p q^T. FCC can fail only at configurations in which all four arguments are '
     'non-separable (S2 is one). A principle that constrains only configurations with a product state or a product '
     'effect is implied by hadm and does not imply FCC.')

# ===============================================================================================================
section('S6  the uniform foil K_c = cone(SEP u cnot SEP)')

E0 = sp.zeros(4, 4)
E0[0, 0], E0[1, 3], E0[2, 2] = 1, 1, -1
x3, y3 = symvec('x', 3, 1), symvec('y', 3, 1)
x1_, x2_, _x3 = x3
y1_, y2_, y3_ = y3
chk('K1', 'hom x^T E0 hom y = 1 + x1 y3 - x2 y2, symbolic', zero((hom(x3).T * E0 * hom(y3))[0, 0]
                                                                    - (1 + x1_ * y3_ - x2_ * y2_)), 'identity')
chk('K2', 'Lagrange: (x1^2 + x2^2)(y3^2 + y2^2) - (x1 y3 - x2 y2)^2 = (x1 y2 + x2 y3)^2, symbolic',
    zero((x1_ ** 2 + x2_ ** 2) * (y3_ ** 2 + y2_ ** 2) - (x1_ * y3_ - x2_ * y2_) ** 2 - (x1_ * y2_ + x2_ * y3_) ** 2),
    'identity')
chk('K3', 'cnot E0 = E0', cnot(E0) == E0, 'witness')
note('K.W', 'by K1, K2: |x1 y3 - x2 y2| <= |x||y| <= 1 on the ball, so E0 is >= 0 on every product (E0 in dualW SEP = '
     'maxCone); by I5 and K3, ipW E0 (cnot P) = ipW E0 P >= 0, so E0 in dualW (cnot SEP); hence E0 in dualW K_c. K_c is '
     'a convex cone generated by a compact base, so closed; it contains the products, lies in Q3 (products are PSD, '
     'cnot preserves Q3, landed D1, D5) hence in maxCone, and is cnot-invariant (I5).')
psi = sp.Matrix([1, -1, -1, -1]) / 2
chk('K4', 'opW E0 psi = -psi for psi = (1,-1,-1,-1)/2, |psi| = 1: E0 is not in dualW Q3',
    mzero(opW(E0) * psi + psi) and (psi.T * psi)[0, 0] == 1, 'witness')
G = coords(psi * psi.T)
chk('K5', 'G = coords(psi psi^T): pauliW G = psi psi^T (G in Q3, so G in dualW K_c), and D G D = G',
    mzero(pauliW(G) - psi * psi.T) and Dg * G * Dg == G, 'witness', f'G = {G.tolist()}')
chk('K6', 'phiW = cnot (prodState xplus z3): phiW lies in cnot SEP, so in K_c', cnot(prodState([1, 0, 0], [0, 0, 1]))
    == phiW, 'witness')
vk = fourVal(phiW, phiW, E0, G)
chk('K7', 'fourVal phiW phiW E0 G = -1: famI fails for uniform K_c and for (Q3, Q3, K_c, K_c)', vk == -1, 'witness',
    f'value {vk}')
vk2 = g2(E0, G, phiW, phiW)
chk('K8', 'g2 E0 G phiW phiW = -1: famII fails for (K_c, K_c, Q3, Q3)', vk2 == -1, 'witness', f'value {vk2}')
chk('K9', 'ipW E0 G = -1 with E0 in dualW K_c: G in Q3 is not in K_c (K_c != Q3)', ipW(E0, G) == -1, 'witness')
chk('K7c', 'countercontrol: with the unit effect E00 (opW = I) in place of E0 the value is > 0',
    fourVal(phiW, phiW, E00, G) > 0, 'countercontrol', f'value {fourVal(phiW, phiW, E00, G)}')
SH = [Q(1, 2), Q(-1, 2), 0, 0]
SZ = [Q(1, 2), 0, 0, Q(-1, 2)]
chk('K1c', 'countercontrol: the product test of K1 detects a table outside maxCone (chainW at the sharp pair -e1, -e3 '
    'is -1/2)', (sp.Matrix(SH).T * chainW * sp.Matrix(SZ))[0, 0] == Q(-1, 2), 'countercontrol')
note('K.R', 'uniform K_c with cnot gates and identity locals satisfies hcls, hadm, hcl and hgate and violates FCC '
     '(K7). (Q3, Q3, K_c, K_c) with cnot gates satisfies the same four and violates famI (K7) while famII holds there '
     '(L, L\' in K_c lie in Q3 and e, f in dualW Q3: the uniform-Q3 argument); (K_c, K_c, Q3, Q3) violates famII (K8) '
     'while famI holds by the same argument.')

# ===============================================================================================================
print()
print('kinds: ' + ', '.join(f"{k} {sum(1 for c in CHECKS if c[1] == k)}"
                            for k in ('identity', 'witness', 'enumerate', 'source', 'countercontrol')), flush=True)
failed = [c[0] for c in CHECKS if not c[2]]
if failed:
    print(f"{len(CHECKS) - len(failed)}/{len(CHECKS)} checks; failed: {', '.join(failed)}", flush=True)
    print('VERDICT NOT RENDERED', flush=True)
    sys.exit(1)
print(f'{len(CHECKS)}/{len(CHECKS)} checks', flush=True)
print('VERDICT C1-CONE-LEVEL-EXACT', flush=True)
