"""QUOTIENT investigation (read-only, off-repo), d = 2 target: is there a 4-dimensional effect space E,
containing the unit, generated by an observer seed effect under the available non-selective operations
(idle = time step W, flip F, swap S), invariant under them, and compatible across horizons?

Exact arithmetic throughout (integer counts, Fractions).  Midpoint seeding: the uniform product measure is
invariant under the leap and under the local bijections, so the configuration at the middle leap step of a
protocol is uniform on the cone; the prefix is run backward with inverse steps.  Validated against the
start-seeded enumeration (control V0).

Effect functionals: e_w(x) = p(w . o=1 | x) for words w over {i, f, s}; the seed is r = "observe 1 now".
Preparations: protocols over {o, i, f, s} of length <= Lp with positive-probability records.
"""
import sys
from fractions import Fraction as Fr
from itertools import product
import numpy as np

sys.path.insert(0, '../rank')
from lattice_rank import F, rank_Q, rank_mod, P1   # noqa: E402
from protocol_rank import run_all                   # noqa: E402


def leap_fwd(u, v, m, rule):
    return v, (F(v, m, rule) ^ u) & m


def leap_bwd(u, v, m, rule):
    return (v ^ F(u, m, rule)) & m, u


def run_mid(protocol, rule):
    """Integer record counts of a protocol; denominator 2^(2W) returned alongside."""
    leaps = [k for k, s in enumerate(protocol) if s in 'oi']
    T = len(leaps)
    half = T // 2
    split = leaps[half] if T > 0 else len(protocol)      # prefix = steps before the (half)-th leap step
    # steps strictly before `split` are run backward; the prefix contains `half` leap steps, suffix T-half
    R = max(half, T - half, 1)
    W = 2 * R + 1
    m = np.uint32((1 << W) - 1)
    c = np.uint32(R)
    one = np.uint32(1) << c
    idx = np.arange(1 << (2 * W), dtype=np.uint64)
    u0 = (idx & np.uint64((1 << W) - 1)).astype(np.uint32)
    v0 = (idx >> np.uint64(W)).astype(np.uint32)
    del idx
    # forward over the suffix
    u, v = u0, v0
    fwd = []
    for st in protocol[split:]:
        if st == 'o':
            fwd.append(((v >> c) & np.uint32(1)).astype(np.int64))
            u, v = leap_fwd(u, v, m, rule)
        elif st == 'i':
            u, v = leap_fwd(u, v, m, rule)
        elif st == 'f':
            v = v ^ one
        elif st == 's':
            bu, bv = (u >> c) & np.uint32(1), (v >> c) & np.uint32(1)
            u = (u & ~one) | (bv << c)
            v = (v & ~one) | (bu << c)
    # backward over the prefix
    u, v = u0, v0
    bwd = []
    for st in reversed(protocol[:split]):
        if st == 'o':
            u, v = leap_bwd(u, v, m, rule)
            bwd.append(((v >> c) & np.uint32(1)).astype(np.int64))
        elif st == 'i':
            u, v = leap_bwd(u, v, m, rule)
        elif st == 'f':
            v = v ^ one
        elif st == 's':
            bu, bv = (u >> c) & np.uint32(1), (v >> c) & np.uint32(1)
            u = (u & ~one) | (bv << c)
            v = (v & ~one) | (bu << c)
    bits = list(reversed(bwd)) + fwd
    rec = np.zeros(1 << (2 * W), dtype=np.int64)
    for b in bits:
        rec = (rec << 1) | b
    cnt = np.bincount(rec, minlength=1 << len(bits))
    return cnt, 1 << (2 * W)


def joint(protocol, rule):
    cnt, den = run_mid(protocol, rule)
    return [Fr(int(x), den) for x in cnt]


def preparations(Lp, rule, alphabet='oifs'):
    preps = []
    for l in range(Lp + 1):
        for pp in product(alphabet, repeat=l):
            pr = ''.join(pp)
            j = joint(pr, rule)
            k = pr.count('o')
            for r in range(1 << k):
                if j[r] > 0:
                    preps.append((pr, r, j[r]))
    return preps


def effect_value(prep, word, rule):
    """p(word . observe=1 | prep) : conditional probability."""
    pr, r, w = prep
    full = pr + word + 'o'
    j = joint(full, rule)
    k1 = pr.count('o')
    k2 = word.count('o') + 1
    # record bits: prep bits (k1) then effect bits (k2); effect record = (anything for word's o's, last = 1)
    tot = Fr(0)
    for rr in range(1 << k2):
        if rr & 1 == 1:
            tot += j[(r << k2) | rr]
    return tot / w


if __name__ == '__main__':
    rule = sys.argv[1]
    Lp = int(sys.argv[2]) if len(sys.argv) > 2 else 2
    M = int(sys.argv[3]) if len(sys.argv) > 3 else 3
    alph = sys.argv[4] if len(sys.argv) > 4 else 'oifs'
    # V0: midpoint seeding agrees with start seeding
    ok = True
    for pr in ('o', 'oo', 'oio', 'ofo', 'oso', 'sofo', 'oifso', 'oosoo'):
        a, da = run_mid(pr, rule)
        b = run_all(pr, max(1, sum(1 for s in pr if s in 'oi')), rule)
        db = 1 << (2 * (2 * max(1, sum(1 for s in pr if s in 'oi')) + 1))
        ok = ok and all(Fr(int(x), da) == Fr(int(y), db) for x, y in zip(a, b))
    print(f'V0 {rule}: midpoint seeding == start seeding on 8 protocols: {ok}')
    preps = preparations(Lp, rule, alph)
    print(f'PREPS {rule} Lp={Lp} alphabet={alph}: {len(preps)} preparations', flush=True)
    words = [''.join(w) for l in range(M + 1) for w in product('ifs', repeat=l)]
    cols = {w: [effect_value(x, w, rule) for x in preps] for w in words}
    unit = [Fr(1)] * len(preps)
    # Q1: the delay family W^k r alone
    for kmax in range(0, M + 1):
        fam = [unit] + [cols['i' * k] for k in range(kmax + 1)]
        print(f'DELAY {rule}: span(unit, W^k r, k<={kmax}) dim = {rank_Q([list(c) for c in zip(*fam)])}')
    # Q2: the full orbit of the seed under <W, F, S>, words of length <= m
    for mm in range(0, M + 1):
        fam = [unit] + [cols[w] for w in words if len(w) <= mm]
        print(f'ORBIT {rule}: span(unit, w.r, |w|<={mm}) dim = {rank_Q([list(c) for c in zip(*fam)])}')
    # Q3: swap-free orbit <W, F> and flip-free orbit <W, S>
    for gens, name in (('if', 'W,F'), ('is', 'W,S'), ('fs', 'F,S')):
        fam = [unit] + [cols[w] for w in words if len(w) <= M and all(ch in gens for ch in w)]
        print(f'ORBIT {rule}: generators <{name}>, |w|<={M}: dim = {rank_Q([list(c) for c in zip(*fam)])}')
    # total effect span available on these preparations (for reference)
    allc = [unit] + [cols[w] for w in words]
    print(f'TOTAL {rule}: rank of [unit | all w.r, |w|<={M}] on {len(preps)} preps = {rank_Q([list(c) for c in zip(*allc)])}')
