"""EQ2-A probe A4 -- coupling at three and four copies: exact countermodels and the kinematic parity test.
Research only; base bcbc516f.  Usage: python3 -I -B a4_coupling.py <CompositeDimension.lean> <K2Guard.lean>

MODELS (three copies 0, 1, 2; tables T[i0, i1, i2]; Q = Q3 = PSD Pauli tables of two qubits, Tw = actT reflY '' Q):
  K_tau, tau = (t01, t02, t12) in {0,1}^3: the closed convex cone generated by
     sigma placed on the pair (i, j) (i < j), sigma in R^{t_ij} Q (twist on the second copy j), times hom(z) on the
     remaining copy, for every pair, every such sigma and every z in the ball.
  M_odd = K_(0,1,0)  (pairs 01, 12 untwisted, pair 02 twisted: an odd cycle of twist bits)
  M_tw  = K_(1,1,1)  (all three pairs twisted; S_3-symmetric)        M_odd = R_1 M_tw (reflect copy 1)
  M_bs  = K_(0,0,0)  (the untwisted biseparable hull)

WRITTEN CLAIMS whose algebraic steps are checked here (all exact; spot checks are labelled as such):
  C1  products: prodState3 x y z = (prodState x y) (x) hom z, and prodState x y lies in Q and in Tw
  C2  K_tau within max_3: the value of a triple product effect on each generator factorizes as
      (pair value) x (single value)  [symbolic identity]  (+ spot checks)
  C3  H0 marginals: the (i,j) marginal of a generator is the pair state (matching pair) or a product table
      (mismatched pair) [symbolic]; so the pair marginal cones of K_tau are exactly R^{t_ij} Q
  C4  conditional cones: conditioning the third copy on any effect f gives a multiple of the pair state or a
      product of Lor vectors [symbolic]
  C5  COMP-1 on every (pair | single) bipartition: (E (x) f)(sigma' (x) y) = <E hom y, sigma' f> on mismatched
      generators [symbolic], both factors in Lor; spot checks with random exact E in the dual pair cone
  C6  pair interactions: cnot preserves Q (Ad CNOT, A1.5), cnot' = R_B cnot R_B preserves Tw; both fix the unit
      entry; cnot (prodState xplus z3) = phiW, cnot' (prodState xplus z3) = idW (non-products)
  C7  EX for M_tw: swapW preserves Tw [A1.13 identities]; the copy transpositions permute the generator families
  C8  NO PER-TOKEN CHART for M_odd / M_tw: for each eps in {I, R}^3 some pair cone is sent off Q, exhibited by
      the image of that pair's Bell table being idW (not in Q)  [8 assignments, exact]
  C9  IE2 FAILS in M_odd: omega = |+><+|_0 (x) Phi+_12 is a generator; (cnot on (0,1)) (x) id_2 sends it to
      GHZ' = (|000>+|011>+|101>+|110>)/2; the functional W = (1/2) u - GHZ' satisfies tr(W g) >= 0 on every
      generator of every K_tau (written: <psi| sigma (x) rho |psi> <= lambda_max(sigma)/2 <= 1/2 since every
      single-copy marginal of GHZ' is 1/2 and lambda_max <= 1 on Q and on Tw) and tr(W GHZ') = -1/2.
      Spot checks of tr(W g) >= 0 on random exact generators of all 8 K_tau.
  C10 M_bs has no chart for the triple: GHZ is in PSD_8 but tr(W_GHZ GHZ) = -1/2 with W_GHZ >= 0 on every K_tau,
      so no per-token image K_{delta eps} of M_bs contains GHZ
  C11 pair-CX for M_bs: U_t = ((1-t^2) I - 2 i t SWAP)/(1+t^2) is unitary for every rational t, U_0 = 1,
      U_1 = -i SWAP (EQ-C T5 path), so SWAP is in the identity component of Aut(Q)
KINEMATIC TEST (four copies; COMP-1 on 2|2 bipartitions with all effects of the pair cones):
  D1  for each of the 16 twist assignments on the 4-cycle 0-1-2-3-0, search the Bell-type candidates:
      a negative value of <E_12 (x) F_03, sigma_01 (x) sigma_23> exists IFF the cycle parity is odd
  D2  exhaustive: on K_4 and K_5, the assignments with every 4-cycle even are exactly {delta eps + c}: 16 of 64 and
      32 of 1024
  D3  even parity: spot checks of nonnegativity on random exact states and effects (all-twisted assignment
      included, c = 1)
  D4  six copies, untwisted pairwise hull: E = W_GHZ (in B_3*), F = GHZ (PSD, in B_3*), state = Phi+_03 Phi+_14
      Phi+_25 (in B_6): the value is negative, so B_6 violates COMP-1 on the 012|345 bipartition

DECISION RULE (fixed before the first run): verdict `A4-COUNTERMODELS-EXACT` iff every check passes, including the
controls (C1 products in both cones; C6 interaction facts reproduce A1; D1 the even-parity cases give no negative
value among the candidates; D3 the QM assignment tau = 0 is nonnegative) and the countercontrols (C8: the all-zero
assignment on M_bs pairs is presentable; D1 odd cases negative).  Exact arithmetic only.
"""
import itertools
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sympy as sp  # noqa: E402
from sympy import I, Matrix, Rational as R, eye, zeros  # noqa: E402

import eq2a_lib as L  # noqa: E402

cd_path, k2_path = sys.argv[1], sys.argv[2]
check = L.check
rng = random.Random(4)
tabs = L.parse_cnot_tables(cd_path)
cnot = L.cnot_fun(tabs)
idW, chainW, _ = L.parse_k2guard_tables(k2_path)
phiW = L.parse_phiW(cd_path)
RY = L.REFLY
PAIRS = [(0, 1), (0, 2), (1, 2)]


def zero(M):
    return M.applyfunc(sp.expand).is_zero_matrix


def twist(sig, t):
    return L.actT(RY, sig) if t else sig


def gen3(sig, pair, z):
    """sigma on `pair` (first index = pair[0]) times hom(z) on the remaining copy."""
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    hz = L.hom(z)
    T = {}
    for idx in itertools.product(range(4), repeat=3):
        T[idx] = sig[idx[i], idx[j]] * hz[idx[k]]
    return T


def prod3(x, y, z):
    hx, hy, hz = L.hom(x), L.hom(y), L.hom(z)
    return {idx: hx[idx[0]] * hy[idx[1]] * hz[idx[2]] for idx in itertools.product(range(4), repeat=3)}


def tab_eq(A, B):
    return all(sp.expand(A[k] - B[k]) == 0 for k in A)


def marg(T, pair):
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    def ent(m, n):
        idx = [0, 0, 0]
        idx[i], idx[j], idx[k] = m, n, 0
        return T[tuple(idx)]
    return Matrix(4, 4, ent)


def cond(T, pair, f):
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    def ent(m, n):
        s = 0
        for c in range(4):
            idx = [0, 0, 0]
            idx[i], idx[j], idx[k] = m, n, c
            s += T[tuple(idx)] * f[c]
        return sp.expand(s)
    return Matrix(4, 4, ent)


def pair3(Tab, a, b, c):
    return sp.expand(sum(Tab[idx] * a[idx[0]] * b[idx[1]] * c[idx[2]] for idx in Tab))


def rand_rat_ball():
    while True:
        v = [R(rng.randint(-9, 9), 10) for _ in range(3)]
        if sum(t * t for t in v) <= 1:
            return v


def rand_lor():
    v = rand_rat_ball()
    a0 = R(rng.randint(1, 5), 2)
    return [a0] + [a0 * t for t in v]


def rand_density(d):
    A = Matrix(d, d, lambda i, j: R(rng.randint(-3, 3), rng.randint(1, 3)) + I * R(rng.randint(-3, 3), rng.randint(1, 3)))
    M = A * A.H
    return (M / M.trace()).applyfunc(sp.expand)


def rand_pair_table(t):
    return twist(L.coordsW(rand_density(4)), t)


# ---------------------------------------------------------------- C1 products
x, y, z = (sp.symbols("x0:3", real=True), sp.symbols("y0:3", real=True), sp.symbols("z0:3", real=True))
check("C1 prodState3 x y z = (prodState x y) placed on (0,1) times hom z on copy 2 (symbolic)",
      tab_eq(prod3(x, y, z), gen3(L.prod_state(x, y), (0, 1), z)))
check("C1 actT reflY (prodState x y) = prodState x (reflY y): products lie in Tw as well as in Q (symbolic)",
      zero(L.actT(RY, L.prod_state(x, y)) - L.prod_state(x, list(RY * Matrix(y)))))

# ---------------------------------------------------------------- C2 factorization of triple product effects
Ssym = Matrix(4, 4, lambda m, n: sp.Symbol(f"s{m}{n}", real=True))
a = sp.symbols("a0:4", real=True)
b = sp.symbols("b0:4", real=True)
c = sp.symbols("c0:4", real=True)
ok = True
for pair in PAIRS:
    G = gen3(Ssym, pair, z)
    eff = [a, b, c]
    i, j = pair
    k = [t for t in range(3) if t not in pair][0]
    lhs = pair3(G, a, b, c)
    rhs = L.pair_val(eff[i], eff[j], Ssym) * sum(eff[k][t] * L.hom(z)[t] for t in range(4))
    ok = ok and sp.expand(lhs - rhs) == 0
check("C2 triple product effect on a generator = (pair value) x (single value), all three pair types (symbolic)", ok)

# ---------------------------------------------------------------- C3 / C4 marginals and conditionals
ok_m = True
ok_c = True
f = sp.symbols("f0:4", real=True)
for gp in PAIRS:
    G = gen3(Ssym, gp, z)
    for mp in PAIRS:
        M = marg(G, mp)
        if mp == gp:
            ok_m = ok_m and zero(M - Ssym)
        else:
            # mismatched: a product of the shared-copy marginal of sigma and hom z (up to the pair order)
            ok_m = ok_m and Matrix(M).rank() <= 1
        C = cond(G, mp, f)
        if mp == gp:
            ok_c = ok_c and zero(C - Ssym * sum(f[t] * L.hom(z)[t] for t in range(4)))
        else:
            ok_c = ok_c and Matrix(C).rank() <= 1
check("C3 marginals: matching pair returns sigma; mismatched pairs return rank-one (product) tables (symbolic)", ok_m)
check("C4 conditionals on any f: matching pair gives sigma * <f, hom z>; mismatched gives rank-one tables (symbolic)", ok_c)
# the rank-one tables are products of Lor vectors: spot check that their factors are in Lor for normalized sigma in Q/Tw
ok_l = True
for _ in range(6):
    for t in (0, 1):
        sig = rand_pair_table(t)
        G = gen3(sig, (0, 2), rand_rat_ball())
        M = marg(G, (0, 1))
        u_ = [M[m, 0] for m in range(4)]
        v_ = [M[0, n] for n in range(4)]
        ok_l = ok_l and zero(M - Matrix(u_) * Matrix(v_).T) and u_[0] >= 0 and \
            sum(q * q for q in u_[1:]) <= u_[0] ** 2 and sum(q * q for q in v_[1:]) <= v_[0] ** 2
check("C3 spot check (12 random exact generators, both twists): mismatched marginals are products of Lor vectors", ok_l)

# ---------------------------------------------------------------- C5 COMP-1 on pair|single bipartitions
Esym = Matrix(4, 4, lambda m, n: sp.Symbol(f"e{m}{n}", real=True))
ok5 = True
for ep in PAIRS:              # the pair carrying the pair effect E; the single effect f is on the remaining copy
    k = [t for t in range(3) if t not in ep][0]
    for gp in PAIRS:
        if gp == ep:
            continue
        G = gen3(Ssym, gp, y)
        val = sp.expand(sum(G[idx] * Esym[idx[ep[0]], idx[ep[1]]] * f[idx[k]] for idx in G))
        shared = [q for q in gp if q in ep][0]       # copy shared by the generator pair and the effect pair
        single_in_g = [q for q in range(3) if q not in gp][0]
        # E contracted with hom y on the copy of ep that carries the single state of the generator
        Ey = [sum((Esym[m, n] if ep[0] == shared else Esym[n, m]) * L.hom(y)[n] for n in range(4)) for m in range(4)]
        # sigma contracted with f on its copy that is the f-copy k
        if gp[0] == shared:
            Sf = [sum(Ssym[m, n] * f[n] for n in range(4)) for m in range(4)]
        else:
            Sf = [sum(Ssym[n, m] * f[n] for n in range(4)) for m in range(4)]
        ok5 = ok5 and sp.expand(val - sum(Ey[m] * Sf[m] for m in range(4))) == 0
check("C5 on mismatched generators (E (x) f)(g) = <E hom y, sigma f> (Euclidean pairing of two Lor vectors) (symbolic)",
      ok5)
ok5s = True
for _ in range(5):
    for tau in itertools.product((0, 1), repeat=3):
        for ep_i, ep in enumerate(PAIRS):
            k = [t for t in range(3) if t not in ep][0]
            E = rand_pair_table(tau[ep_i])     # an element of the dual pair cone (self-dual cones)
            fv = rand_lor()
            gp_i = rng.randrange(3)
            G = gen3(rand_pair_table(tau[gp_i]), PAIRS[gp_i], rand_rat_ball())
            val = sum(G[idx] * E[idx[ep[0]], idx[ep[1]]] * fv[idx[k]] for idx in G)
            ok5s = ok5s and sp.expand(val) >= 0
check("C5 spot check: 120 random exact (pair effect (x) single effect, generator) values are >= 0 across all 8 K_tau",
      ok5s)

# ---------------------------------------------------------------- C6 interactions
Wsym = Matrix(4, 4, lambda m, n: sp.Symbol(f"w{m}{n}", real=True))
cnotp = lambda w: L.actT(RY, cnot(L.actT(RY, w)))  # noqa: E731
check("C6 cnot and cnot' fix the unit entry (normalization) (symbolic)",
      sp.expand(cnot(Wsym)[0, 0] - Wsym[0, 0]) == 0 and sp.expand(cnotp(Wsym)[0, 0] - Wsym[0, 0]) == 0)
check("C6 cnot (prodState xplus z3) = phiW and cnot' (prodState xplus z3) = idW (non-products)",
      cnot(L.prod_state(L.XPLUS, L.Z3)) == phiW and cnotp(L.prod_state(L.XPLUS, L.Z3)) == idW)
CNOT = Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
check("C6 pauliW (cnot w) = CNOT pauliW(w) CNOT, so cnot maps Q onto Q (symbolic)",
      zero(L.pauliW(cnot(Wsym)) - CNOT * L.pauliW(Wsym) * CNOT))

# ---------------------------------------------------------------- C7 EX for M_tw
check("C7 swapW (actT reflY w) = transposeW (actT reflY (swapW w)) (symbolic): Tw is swap-invariant since transposeW "
      "fixes Q and commutes with actT reflY",
      zero(L.swapW(L.actT(RY, Wsym)) - L.transposeW(L.actT(RY, L.swapW(Wsym)))) and
      zero(L.transposeW(L.actT(RY, Wsym)) - L.actT(RY, L.transposeW(Wsym))))

# ---------------------------------------------------------------- C8 no per-token chart for M_odd and M_tw
def chart_pair(ei, ej, w):
    return L.chart2(RY if ei else L.ID3, RY if ej else L.ID3, w)


def bell_of(t):
    return twist(phiW, t)


def in_Q_witnessed_out(w):
    """True when w is witnessed outside Q: its Pauli matrix has v^H M v < 0 for the singlet v."""
    v = Matrix([0, 1, -1, 0])
    return (v.H * L.pauliW(w) * v)[0, 0] < 0


for name, tau in (("M_odd", (0, 1, 0)), ("M_tw", (1, 1, 1))):
    okc = True
    for eps in itertools.product((0, 1), repeat=3):
        witnessed = False
        for p_i, (i, j) in enumerate(PAIRS):
            img = chart_pair(eps[i], eps[j], bell_of(tau[p_i]))
            if img == idW and in_Q_witnessed_out(img):
                witnessed = True
        okc = okc and witnessed
    check(f"C8 {name}: for all 8 eps in {{I,R}}^3 some pair Bell table is sent to idW (singlet value < 0): no per-token "
          "chart presents the three pair composites", okc)
okcc = all(chart_pair(0, 0, bell_of(0)) == phiW for _ in [0])
check("C8 countercontrol: for M_bs (all untwisted) eps = (I,I,I) sends every pair Bell table to phiW (in Q)", okcc)

# ---------------------------------------------------------------- C9 IE2 fails: the GHZ' witness
e = lambda bits: Matrix([1 if i == int(bits, 2) else 0 for i in range(8)])  # noqa: E731
plus = Matrix([1, 1])
psi0 = L.kron(plus, Matrix([1, 0, 0, 1]))            # |+>_0 (x) Phi+_12, unnormalized (norm^2 = 4)
rho0 = psi0 * psi0.H / 4
om0 = L.coordsN(rho0, 3)
check("C9 omega0 = |+><+|_0 (x) Phi+_12 is the generator gen3(phiW on (1,2), xplus on 0) of M_odd",
      tab_eq(om0, gen3(phiW, (1, 2), L.XPLUS)))
img = L.idle_ext(cnot, om0, (0, 1))
ghzp = (e("000") + e("011") + e("101") + e("110")) / 2
check("C9 (cnot on (0,1)) (x) id_2 sends omega0 to GHZ' = (|000>+|011>+|101>+|110>)/2",
      zero(L.pauliN(img, 3) - ghzp * ghzp.H))
Wop = eye(8) / 2 - ghzp * ghzp.H
check("C9 tr(W GHZ') = -1/2 for W = 1/2 - |GHZ'><GHZ'|", sp.expand((Wop * ghzp * ghzp.H).trace()) == R(-1, 2))
marg_ok = True
for q in range(3):
    keep = [q]
    rq = zeros(2, 2)
    for a_ in range(2):
        for b_ in range(2):
            s = 0
            for rest in itertools.product(range(2), repeat=2):
                ia, ib = [0, 0, 0], [0, 0, 0]
                ia[q], ib[q] = a_, b_
                others = [t for t in range(3) if t != q]
                for t_, val in zip(others, rest):
                    ia[t_] = val
                    ib[t_] = val
                s += ghzp[int("".join(map(str, ia)), 2)] * sp.conjugate(ghzp[int("".join(map(str, ib)), 2)])
            rq[a_, b_] = s
    marg_ok = marg_ok and zero(rq - eye(2) / 2)
check("C9 every single-copy marginal of GHZ' is 1/2 (the input of the written bound <= 1/2)", marg_ok)


def gen_op(tau_bit, pair, rho2, zvec):
    """Operator of a generator: pauliN of gen3(R^tau coords(rho2), pair, z)."""
    return L.pauliN(gen3(twist(L.coordsW(rho2), tau_bit), pair, zvec), 3)


okw = True
nspots = 0
for tau in itertools.product((0, 1), repeat=3):
    for p_i, pair in enumerate(PAIRS):
        for _ in range(2):
            G = gen_op(tau[p_i], pair, rand_density(4), rand_rat_ball())
            okw = okw and sp.expand((Wop * G).trace()) >= 0
            nspots += 1
check(f"C9 spot check: tr(W g) >= 0 on {nspots} random exact generators of all eight K_tau (written proof covers all)",
      okw)

# ---------------------------------------------------------------- C10 M_bs: GHZ is not in any K_tau
ghz = (e("000") + e("111"))
Wg = eye(8) / 2 - ghz * ghz.H / 2
check("C10 tr(W_GHZ GHZ) = -1/2 for W_GHZ = 1/2 - |GHZ><GHZ|", sp.expand((Wg * ghz * ghz.H / 2).trace()) == R(-1, 2))
okg = True
for tau in itertools.product((0, 1), repeat=3):
    for p_i, pair in enumerate(PAIRS):
        G = gen_op(tau[p_i], pair, rand_density(4), rand_rat_ball())
        okg = okg and sp.expand((Wg * G).trace()) >= 0
check("C10 spot check: tr(W_GHZ g) >= 0 on 24 random exact generators of all eight K_tau", okg)

# ---------------------------------------------------------------- C11 pair-CX path for Q
t = sp.Symbol("t", real=True)
SWAP = L.swap_matrix([2, 2], [1, 0])
Ut = ((1 - t ** 2) * eye(4) - 2 * I * t * SWAP) / (1 + t ** 2)
check("C11 U_t is unitary for symbolic real t; U_0 = 1; U_1 = -i SWAP",
      zero((Ut.H * Ut - eye(4)).applyfunc(sp.simplify)) and Ut.subs(t, 0) == eye(4) and
      zero(Ut.subs(t, 1) + I * SWAP))


# ---------------------------------------------------------------- D1 four-copy 2|2 test on the 4-cycle
def bell_tables():
    return [sp.diag(1, 1, -1, 1), sp.diag(1, -1, 1, 1), sp.diag(1, 1, 1, -1), sp.diag(1, -1, -1, -1)]


def val4(s01, s23, E12, F03):
    tot = 0
    for i0, i1, i2, i3 in itertools.product(range(4), repeat=4):
        sv = s01[i0, i1] * s23[i2, i3]
        if sv == 0:
            continue
        ev = E12[i1, i2] * F03[i0, i3]
        if ev != 0:
            tot += sv * ev
    return tot


okD1 = True
details = []
for tau4 in itertools.product((0, 1), repeat=4):   # (t01, t12, t23, t03)
    t01, t12, t23, t03 = tau4
    states01 = [twist(B, t01) for B in bell_tables()]
    states23 = [twist(B, t23) for B in bell_tables()]
    eff12 = [twist(B, t12) for B in bell_tables()]
    eff03 = [twist(B, t03) for B in bell_tables()]
    neg = min(val4(s, s2, E, F) for s in states01 for s2 in states23 for E in eff12 for F in eff03)
    odd = (sum(tau4) % 2 == 1)
    okD1 = okD1 and ((neg < 0) == odd)
    details.append((tau4, neg))
check("D1 over Bell-type candidates: a negative 2|2 value exists IFF the 4-cycle twist parity is odd (16 assignments)",
      okD1)
print("     D1 minima: " + ", ".join(f"{''.join(map(str, k))}:{v}" for k, v in details))


def even4(n, tau):
    for a_, b_, c_, d_ in itertools.permutations(range(n), 4):
        cyc = [(a_, b_), (b_, c_), (c_, d_), (d_, a_)]
        if sum(tau[tuple(sorted(p))] for p in cyc) % 2:
            return False
    return True


for n in (4, 5):
    edges_ = list(itertools.combinations(range(n), 2))
    good = set()
    for bits in itertools.product((0, 1), repeat=len(edges_)):
        tau = dict(zip(edges_, bits))
        if even4(n, tau):
            good.add(bits)
    cob = set()
    for eps in itertools.product((0, 1), repeat=n):
        for c0 in (0, 1):
            cob.add(tuple((eps[i] + eps[j] + c0) % 2 for (i, j) in edges_))
    check(f"D2 K_{n}: assignments with every 4-cycle even = {{delta eps + c}} exactly ({len(good)} of {2 ** len(edges_)})",
          good == cob and len(good) == 2 ** n)

okD3 = True
cnt = 0
for tau4 in ((0, 0, 0, 0), (1, 1, 1, 1), (1, 1, 0, 0), (0, 1, 1, 0)):
    for _ in range(3):
        s01, s23 = rand_pair_table(tau4[0]), rand_pair_table(tau4[2])
        E12, F03 = rand_pair_table(tau4[1]), rand_pair_table(tau4[3])
        okD3 = okD3 and sp.expand(val4(s01, s23, E12, F03)) >= 0
        cnt += 1
check(f"D3 even parity (incl. all-twisted c = 1 and QM tau = 0): {cnt} random exact 2|2 values >= 0", okD3)


# ---------------------------------------------------------------- D4 six copies, untwisted pairwise hull
def eff_table3(Eop):
    return {idx: sp.expand((Eop * L.kron(*[L.PAULI[i] for i in idx])).trace() / 8) for idx in itertools.product(range(4), repeat=3)}


Etab = eff_table3(Wg)
Ftab = eff_table3(ghz * ghz.H / 2)
s = [1, 1, -1, 1]   # phiW diagonal: the three Bell pairs (0,3), (1,4), (2,5) contract index i_k with i_{k+3}
val6 = sp.expand(sum(Etab[idx] * Ftab[idx] * s[idx[0]] * s[idx[1]] * s[idx[2]] for idx in Etab))
check(f"D4 <W_GHZ (x) GHZ, Phi+_03 Phi+_14 Phi+_25> = {val6} < 0: the six-copy pairwise hull violates COMP-1 on 012|345",
      val6 < 0)
okd4 = True
for _ in range(4):
    p_i = rng.randrange(3)
    G = gen_op(0, PAIRS[p_i], rand_density(4), rand_rat_ball())
    okd4 = okd4 and sp.expand((ghz * ghz.H * G).trace()) >= 0
check("D4 control: GHZ is nonnegative on random untwisted generators (it is PSD, hence in B_3*)", okd4)

ok = L.summary("a4_coupling")
print("VERDICT " + ("A4-COUNTERMODELS-EXACT" if ok else "A4-NOT-RENDERED"))
sys.exit(0 if ok else 1)
