"""EQ2-A probe A4c -- the all-twisted pairwise hull B_tw is not self-dual, exact.  Research only; base bcbc516f.
Usage: python3 -I -B a4c_twisted_selfduality.py

Objects (operator form, three qubits, basis index 4*x0 + 2*x1 + x2; PT_j = partial transpose on copy j):
  B_tw  = the closed convex cone generated by PT_j(sigma_ij) (x) rho_k for (i, j) in {(0,1), (0,2), (1,2)}, k the third
          copy, sigma a two-qubit state, rho a one-qubit state (a4b_twisted_hull.py; = M_tw = K_(1,1,1) of a4_coupling).
  B_tw* = { X : tr(X g) >= 0 for every generator g }  (trace pairing).
  F = (1/2)(1 - |000><000| - |111><111|) + |000><111| + |111><000|,   G = Ad_{S (x) S (x) 1}(F),  S = diag(1, i).
Written reduction (NOTES A4.5): COMP-1 on the 012|345 bipartition of a six-copy composite whose pair composites are all
twins forces K_3 = K_3* (trace pairing).  CLAIM checked here: F and G lie in B_tw* and tr(F G) = -1/2.  Hence G is in
B_tw* but not in B_tw (B_tw is not self-dual), and no cone K with K inside K* that is invariant under local unitaries
contains F or G.

DECISION RULE (fixed before the first run): verdict `A4c-TWISTED-HULL-NOT-SELF-DUAL` iff all pass:
  L0  conventions: pt() on three qubits transposes exactly the named factor (random rational product operators), and
      tr(X PT_j(Y)) = tr(PT_j(X) Y) (random Gaussian-rational X, Y)
  L1  for each pair (i, j) and a symbolic state vector phi = (alpha, beta) on copy k, the conditional
      M = <phi|_k PT_j(F) |phi>_k, computed from the operator, equals the explicit sum of squares
      (1/2)|beta|^2 |00><00| + (1/2)|alpha|^2 |11><11| + (1/2)(u u^H + w w^H),  u = conj(alpha)|01> + conj(beta)|10>,
      w = beta|01> + alpha|10>  (pair basis |x_i x_j>); for G the same with u = conj(alpha)|01> - conj(beta)|10>,
      w = beta|01> - alpha|10>.  Control identity: tr(F (PT_j(sigma) (x) |phi><phi|)) = tr(M sigma) on random
      rational sigma and phi.  Hence F and G are in B_tw*.
  L2  G = Ad_{S (x) S (x) 1}(F) exactly; F and G commute with the GHZ stabilizer group (they lie in the twirled sector)
  L3  tr(F G) = -1/2
  L4  controls: W = 1/2 - |GHZ><GHZ| equals PT_1(rho') for an explicit rho' that is a positive sum of products across
      01|2 (a one-family certificate that W is in B_tw); tr(W F) = 1/2 and tr(W G) = 5/2 (consistency: W in B_tw, F and
      G in B_tw*); 40 random exact generators pair nonnegatively with F and with G.  Countercontrols: F_2 = (1/2)(1 -
      |000><000| - |111><111|) + 2(|000><111| + h.c.) pairs negatively with the generator PT_1(Psi-) (x) |+><+|, and
      |GHZ><GHZ| pairs negatively with W
  L5  six-copy identities behind the written reduction (random Gaussian-rational Hermitian E on copies 012 and F on
      345, the links built as products of the pair operators): <E (x) F, (x)_i PT_{i+3}(Phi+_{i,i+3})> = tr(E F)/8
      (twin links) and <E (x) F, (x)_i Phi+_{i,i+3}> = tr(E F^T)/8 (untwisted links); countercontrol: the two values
      differ for the sample
all pass.  Exact Gaussian-rational and symbolic arithmetic only.
"""
import itertools
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sympy as sp  # noqa: E402
from sympy import I, Matrix, Rational as R, eye, zeros  # noqa: E402

import eq2a_lib as L  # noqa: E402

check = L.check
X, Y, Z, I2 = L.SX, L.SY, L.SZ, L.S0
PAIRS = [(0, 1), (0, 2), (1, 2)]
rng = random.Random(20261008)


def zero(M):
    return M.applyfunc(sp.expand).is_zero_matrix


def ket(bits):
    return Matrix([1 if i == int(bits, 2) else 0 for i in range(2 ** len(bits))])


def proj(v):
    return (v * v.H / (v.H * v)[0, 0]).applyfunc(sp.expand)


def rq():
    return R(rng.randint(-5, 5), rng.randint(1, 4))


def rgauss(n, m):
    return Matrix(n, m, lambda i, j: rq() + I * rq())


def place(sig4, pair, rho2):
    """sigma on `pair` (sigma's tensor order = pair order) times rho on the remaining copy, as an 8x8 matrix."""
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    M = zeros(8, 8)
    for a in itertools.product(range(2), repeat=3):
        for b in itertools.product(range(2), repeat=3):
            v = sig4[2 * a[i] + a[j], 2 * b[i] + b[j]] * rho2[a[k], b[k]]
            if v != 0:
                M[4 * a[0] + 2 * a[1] + a[2], 4 * b[0] + 2 * b[1] + b[2]] = v
    return M


def conditional(Op, pair, phi):
    """<phi|_k Op |phi>_k as a 4x4 matrix on `pair` (basis 2*x_i + x_j)."""
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    M = zeros(4, 4)
    for xi, xj, yi, yj in itertools.product(range(2), repeat=4):
        s = 0
        for c in range(2):
            for d in range(2):
                a, b = [0, 0, 0], [0, 0, 0]
                a[i], a[j], a[k] = xi, xj, c
                b[i], b[j], b[k] = yi, yj, d
                s += sp.conjugate(phi[c]) * phi[d] * Op[4 * a[0] + 2 * a[1] + a[2], 4 * b[0] + 2 * b[1] + b[2]]
        M[2 * xi + xj, 2 * yi + yj] = s
    return M.applyfunc(sp.expand)


# ---------------------------------------------------------------- L0 conventions
okL0a = True
for j in range(3):
    A, B, C = (Matrix(2, 2, lambda r, c: rq()) for _ in range(3))
    fac = [A, B, C]
    fac_t = [f.T if t == j else f for t, f in enumerate(fac)]
    okL0a = okL0a and zero(L.pt(L.kron(*fac), j, [2, 2, 2]) - L.kron(*fac_t))
check("L0 pt() on three qubits transposes exactly the named factor (random rational products, j = 0, 1, 2)", okL0a)
Xr, Yr = rgauss(8, 8), rgauss(8, 8)
check("L0 tr(X PT_j(Y)) = tr(PT_j(X) Y) for j = 0, 1, 2 (random Gaussian-rational X, Y)",
      all(sp.expand((Xr * L.pt(Yr, j, [2, 2, 2])).trace() - (L.pt(Xr, j, [2, 2, 2]) * Yr).trace()) == 0
          for j in range(3)))

# ---------------------------------------------------------------- the operators
P6 = eye(8) - ket("000") * ket("000").T - ket("111") * ket("111").T
Xc = ket("000") * ket("111").T + ket("111") * ket("000").T
F = P6 / 2 + Xc
G_expected = P6 / 2 - Xc
Sg = sp.diag(1, I)
U = L.kron(Sg, Sg, I2)
G = L.ad(U, F).applyfunc(sp.expand)
ghz = ket("000") + ket("111")
GHZ = ghz * ghz.T / 2
W = eye(8) / 2 - GHZ

# ---------------------------------------------------------------- L1 sums of squares for the conditionals
a0, a1, b0, b1 = sp.symbols("a0 a1 b0 b1", real=True)
al, be = a0 + I * a1, b0 + I * b1
phi_sym = [al, be]
n2a, n2b = sp.expand(al * sp.conjugate(al)), sp.expand(be * sp.conjugate(be))


def sos(sign):
    u = Matrix([0, sp.conjugate(al), sign * sp.conjugate(be), 0])
    w = Matrix([0, be, sign * al, 0])
    D = zeros(4, 4)
    D[0, 0], D[3, 3] = n2b / 2, n2a / 2
    return (D + (u * u.H + w * w.H) / 2).applyfunc(sp.expand)


okL1 = True
for p in PAIRS:
    for Op, sign in ((F, 1), (G, -1)):
        M = conditional(L.pt(Op, p[1], [2, 2, 2]), p, phi_sym)
        okL1 = okL1 and zero(M - sos(sign))
check("L1 every conditional <phi|_k PT_j(F)|phi>_k and <phi|_k PT_j(G)|phi>_k equals the explicit sum of squares "
      "(three pairs, symbolic phi)  =>  F, G in B_tw*", okL1)
okL1c = True
for t in range(6):
    p = PAIRS[t % 3]
    sig = rgauss(4, 4)
    sig = sig + sig.H
    ph = [rq() + I * rq(), rq() + I * rq()]
    rho = Matrix(2, 1, ph) * Matrix(2, 1, ph).H
    lhs = sp.expand((F * L.pt(place(sig, p, rho), p[1], [2, 2, 2])).trace())
    rhs = sp.expand((conditional(L.pt(F, p[1], [2, 2, 2]), p, ph) * sig).trace())
    okL1c = okL1c and sp.expand(lhs - rhs) == 0
check("L1 control: tr(F (PT_j(sigma) (x) |phi><phi|)) = tr(M_phi sigma) (6 random rational instances)", okL1c)

# ---------------------------------------------------------------- L2 local-unitary relation, twirled sector
check("L2 G = Ad_{S (x) S (x) 1}(F) = (1/2)(1 - |000><000| - |111><111|) - (|000><111| + h.c.) exactly",
      zero(G - G_expected))
stab_lbls = [(1, "ZZI"), (1, "IZZ"), (1, "ZIZ"), (1, "XXX"), (-1, "YYX"), (-1, "XYY"), (-1, "YXY")]
PM = {"I": I2, "X": X, "Y": Y, "Z": Z}
stab = [sg * L.kron(PM[l[0]], PM[l[1]], PM[l[2]]) for sg, l in stab_lbls]
check("L2 F and G commute with the GHZ stabilizer group (GHZ-diagonal: the twirled sector)",
      all(zero(s * F - F * s) and zero(s * G - G * s) for s in stab))

# ---------------------------------------------------------------- L3 the negative pairing
trFG = sp.expand((F * G).trace())
print(f"     tr(F G) = {trFG}")
check("L3 tr(F G) = -1/2  =>  G in B_tw* but not in B_tw; B_tw is not self-dual", trFG == R(-1, 2))

# ---------------------------------------------------------------- L4 controls and countercontrols
e01, e10 = ket("01"), ket("10")
v2 = {"+": Matrix([1, 1]), "-": Matrix([1, -1]), "+i": Matrix([1, I]), "-i": Matrix([1, -I])}
pairs_eff = [(e01 + e10, v2["-"]), (e01 - e10, v2["+"]), (e01 + I * e10, v2["+i"]), (e01 - I * e10, v2["-i"])]
rho_p = sum((L.kron(proj(a), proj(b)) for a, b in pairs_eff), zeros(8, 8)) / 2 \
    + L.kron(proj(ket("00")), proj(ket("1"))) / 2 + L.kron(proj(ket("11")), proj(ket("0"))) / 2
check("L4 control: W = PT_1(rho') with rho' = (1/2) sum of four products across 01|2 + (1/2)(|00><00| (x) |1><1| + "
      "|11><11| (x) |0><0|)  (one-family certificate: W in B_tw)", zero(L.pt(rho_p, 1, [2, 2, 2]) - W))
trWF, trWG = sp.expand((W * F).trace()), sp.expand((W * G).trace())
check("L4 control: tr(W F) = 1/2 and tr(W G) = 5/2 (W in B_tw pairs nonnegatively with F, G in B_tw*)",
      trWF == R(1, 2) and trWG == R(5, 2))
okL4r = True
for t in range(40):
    p = PAIRS[t % 3]
    A4 = rgauss(4, 4)
    sig = A4 * A4.H
    sig = sig / sig.trace()
    B2 = rgauss(2, 2)
    rho = B2 * B2.H
    rho = rho / rho.trace()
    g = L.pt(place(sig, p, rho), p[1], [2, 2, 2])
    for Op in (F, G):
        v = sp.expand((Op * g).trace())
        okL4r = okL4r and v.is_Rational is True and v >= 0
check("L4 control: 40 random exact generators PT_j(sigma) (x) rho pair nonnegatively with F and with G", okL4r)
F2 = P6 / 2 + 2 * Xc
psim = e01 - e10
gneg = L.pt(place(psim * psim.H / 2, (0, 1), v2["+"] * v2["+"].H / 2), 1, [2, 2, 2])
vneg = sp.expand((F2 * gneg).trace())
print(f"     countercontrol value tr(F_2 (PT_1(Psi-) (x) |+><+|)) = {vneg}")
check("L4 countercontrol: F_2 (coherence 2) pairs negatively with the generator PT_1(Psi-) (x) |+><+|", vneg < 0)
check("L4 countercontrol: tr(GHZ W) = -1/2 < 0 (GHZ is not in B_tw*)", sp.expand((GHZ * W).trace()) == R(-1, 2))

# ---------------------------------------------------------------- L5 six-copy identities
Ar, Br = rgauss(8, 8), rgauss(8, 8)
E6, F6 = Ar + Ar.H, Br + Br.H
phip = (ket("00") + ket("11")) * (ket("00") + ket("11")).T / 2
links = {"twin": L.pt(phip, 1, [2, 2]), "untwisted": phip}


def six_copy_value(link):
    """<E (x) F, (x)_{i=0..2} link_{i, i+3}> with the six-copy operator built entrywise as a product of pair entries."""
    tot = 0
    for x in itertools.product(range(2), repeat=6):
        for y in itertools.product(range(2), repeat=6):
            m = 1
            for i in range(3):
                m *= link[2 * x[i] + x[i + 3], 2 * y[i] + y[i + 3]]
                if m == 0:
                    break
            if m == 0:
                continue
            xa, xb = 4 * x[0] + 2 * x[1] + x[2], 4 * x[3] + 2 * x[4] + x[5]
            ya, yb = 4 * y[0] + 2 * y[1] + y[2], 4 * y[3] + 2 * y[4] + y[5]
            tot += E6[ya, xa] * F6[yb, xb] * m
    return sp.expand(tot)


v_tw, v_un = six_copy_value(links["twin"]), six_copy_value(links["untwisted"])
check("L5 twin links: <E (x) F, (x)_i PT_{i+3}(Phi+)> = tr(E F)/8", sp.expand(v_tw - (E6 * F6).trace() / 8) == 0)
check("L5 untwisted links: <E (x) F, (x)_i Phi+> = tr(E F^T)/8", sp.expand(v_un - (E6 * F6.T).trace() / 8) == 0)
check("L5 countercontrol: the two six-copy values differ for the sample", sp.expand(v_tw - v_un) != 0)

ok = L.summary("a4c_twisted_selfduality")
print("VERDICT " + ("A4c-TWISTED-HULL-NOT-SELF-DUAL" if ok else "A4c-NOT-RENDERED"))
sys.exit(0 if ok else 1)
