"""EQ4-P probe p11 -- the GHZ-diagonal sector: exact ingredients of the reduction "sector problem SP => wall", the
single-token filter structure, an admissible non-extreme addition for the W3 branch, and the kappa / W3 Bell-network
values cited in N3.4.  Research only.

Usage:  python3 -I -B p11_sector_reduction.py <base>/verification/lean-mathlib/OIBridge
Imports only the own library eq4_lib.py.

Written reduction (NOTES N3.7).  P_j (j = 2b + t) are the GHZ-basis projectors, P_{2b+t} = |g><g| with
g = (|0 b1 b2> + (-1)^t |1 ~b1 ~b2>)/sqrt2, b = 2 b1 + b2.  For an admissible K3 (closed, LU-invariant from five
tokens, S3-symmetric, co-self-dual from six tokens, BS <= K3): its twirl over the GHZ stabilizer group H equals its
section with the GHZ-diagonal sector GD (H acts by local unitaries); T fixes GD pointwise, so the section is self-dual
for the trace pairing inside GD; it is invariant under the group G generated by LU and token permutations normalizing
H; and S = twirl(BS) <= section <= S*.  If the orthant were the only such cone, GHZ+ = P_0 would lie in K3 and E3
((ii) => (i)) would give K3 = PSD8.

DECISION RULE (fixed before the first run; rules, not expected numbers).  VERDICT `P11-SECTOR-REDUCTION-EXACT` iff all:
  K  transcription control.
  H  (H1) the twirl (1/8) sum_h Ad(h) over the group generated by XXX, ZZ1, 1ZZ equals the pinching
     X -> sum_j tr(X P_j) P_j on all 64 units; (H2) each of Z_1, X_1, X_2, X_3, S_1 S_2 (S = diag(1, i)), SWAP_12,
     SWAP_23 maps every P_j to some P_k (a permutation); the group generated by these permutations has order 192 and
     equals G = {S_4 on fibres x even numbers of within-fibre swaps} as a set of permutations of the 8 positions; it
     is transitive on positions and has exactly two orbits on unordered pairs (same fibre, different fibres);
     (H3) T(P_j) = P_j for all j.
  S  (S1) twirl(|0 b1 b2><0 b1 b2|) = (P_{2b} + P_{2b+1})/2 for all b (a product operator); P_0 + P_2 =
     Phi+_12 (x) |+><+|_3 + Phi-_12 (x) |-><-|_3 (biseparable across 12|3).  With H2 (G acts by maps preserving BS,
     transitively on both pair orbits) S = cone{e_j + e_k} <= twirl(BS); with p1 P1 (tr(b P_0) <= tr(b)/2 on BS) and H2,
     twirl(BS) <= S; so twirl(BS) = S and BS* n GD = S*.
  F  single-token filters: for each token and 3 random exact complex A, the 8 x 8 matrix M_ik = tr(P_i Ad(A)(P_k))
     equals c_1 I + c_s Sig + c_p Pi + c_ps Pi Sig, with Sig the global within-fibre swap and Pi the fibre map of
     X on that token (both in G), and c_1 = |a00 + a11|^2/4, c_s = |a00 - a11|^2/4, c_p = |a01 + a10|^2/4,
     c_ps = |a01 - a10|^2/4 (all >= 0): single-token filters add nothing to G-invariance and convexity.
  Y  W3 branch: with mu = (-1, 1^7) (= 2 W3 in the P_j basis), nu = (-1, 5, 1^6) (p8's nu) and y = (21, -3, 5^6):
     nu and y pair nonnegatively with every generator of K_mu = cone(S u G.mu) (both lie in K_mu*), <y, nu> < 0
     (so y is not in K_mu), the G-orbit of y is self-positive (all 192 images), and <nu, Sig nu> < 0 (nu's orbit is
     not).  Tie-in control: the operator pairing tr(Y N) of Y = sum y_j P_j, N = sum nu_j P_j equals <y, nu>.
  N  Bell-link network values (exact), re-certifying numbers first computed in an unrecorded inline exploration in
     this session: theta(kappa, W3), the four K4 placements kWWW, WWkk, kkWW, kWkW, the 3x3 Latin square with kappa
     rows / W3 columns, W3 rows / kappa columns, mixed, and with W3 / GHZ in all four combinations: all real and >= 0;
     countercontrol: theta with GHZ states and W3 effects is < 0.
"""
import random
import sys
from fractions import Fraction as Fr
from itertools import permutations, product

sys.path.insert(0, __file__.rsplit("/", 1)[0] if "/" in __file__ else ".")
import eq4_lib as L  # noqa: E402

BASE = sys.argv[1]
rep = L.Report("p11_sector_reduction")
rng = random.Random(20261009 + 11)
rep.check("K0 transcription control", L.transcription_control(BASE)[0])
X3 = (0, 1, 2)


def idx(x, y, z):
    return 4 * x + 2 * y + z


PJ = []
for b in range(4):
    b1, b2 = b >> 1, b & 1
    for t in range(2):
        v = [0] * 8
        v[idx(0, b1, b2)] = 1
        v[idx(1, 1 - b1, 1 - b2)] = 1 if t == 0 else -1
        PJ.append(L.ket_op(v, X3).scale(Fr(1, 2)))


def pin(X):
    out = L.Op(X3, {})
    for P in PJ:
        out = out + P.scale(L.pair(X, P))
    return out


def mat1(M, q):
    return L.op(M, (q,))


def mm2(A, B):
    return [[sum((L.G.of(A[i][k]) * L.G.of(B[k][j]) for k in range(2)), L.ZERO) for j in range(2)] for i in range(2)]


def powm(M, e):
    return M if e else L.S0


# ------------------------------------------------------------------------------------------------ H1 twirl = pinching
Hgrp = []
for a in (0, 1):
    for bb in (0, 1):
        for c in (0, 1):
            m1 = mm2(powm(L.SX, a), powm(L.SZ, bb))
            m2 = mm2(mm2(powm(L.SX, a), powm(L.SZ, bb)), powm(L.SZ, c))
            m3 = mm2(powm(L.SX, a), powm(L.SZ, c))
            Hgrp.append(L.tensor(mat1(m1, 0), mat1(m2, 1), mat1(m3, 2)))


def twirl(X):
    out = L.Op(X3, {})
    for h in Hgrp:
        out = out + L.ad(h, X)
    return out.scale(Fr(1, 8))


rep.check("H1 the twirl over <XXX, ZZ1, 1ZZ> equals the GHZ-basis pinching on all 64 units",
          all(twirl(U) == pin(U) for _, U in L.units(X3)))


# ------------------------------------------------------------------------------------------------ H2 the group G
def perm_of(f):
    out = []
    for P in PJ:
        Q = f(P)
        k = next((k for k, R in enumerate(PJ) if R == Q), None)
        if k is None:
            return None
        out.append(k)
    return tuple(out) if sorted(out) == list(range(8)) else None


Sd = [[1, 0], [0, L.I_]]
gens_ops = {
    "Z_1": lambda X: L.ad(mat1(L.SZ, 0), X),
    "X_1": lambda X: L.ad(mat1(L.SX, 0), X),
    "X_2": lambda X: L.ad(mat1(L.SX, 1), X),
    "X_3": lambda X: L.ad(mat1(L.SX, 2), X),
    "S_1 S_2": lambda X: L.ad(L.tensor(mat1(Sd, 0), mat1(Sd, 1)), X),
    "SWAP_12": lambda X: L.reorder(L.relabel(X, {0: 1, 1: 0}), X3),
    "SWAP_23": lambda X: L.reorder(L.relabel(X, {1: 2, 2: 1}), X3),
}
gperms = {k: perm_of(f) for k, f in gens_ops.items()}
ok_h2 = all(p is not None for p in gperms.values())
grp = set()
if ok_h2:
    grp = {tuple(range(8))}
    frontier = [tuple(range(8))]
    while frontier:
        nxt = []
        for g in frontier:
            for p in gperms.values():
                h = tuple(p[g[i]] for i in range(8))
                if h not in grp:
                    grp.add(h)
                    nxt.append(h)
        frontier = nxt
GA = set()
for perm in permutations(range(4)):
    for eps in product((0, 1), repeat=4):
        if sum(eps) % 2 == 0:
            GA.add(tuple(2 * perm[b] + (t ^ eps[b]) for b in range(4) for t in range(2)))
pair_orbits = set()
for j in range(8):
    for k in range(j + 1, 8):
        pair_orbits.add(frozenset(frozenset((g[j], g[k])) for g in grp))
transitive = len({g[0] for g in grp}) == 8
rep.check("H2 the seven generators permute the P_j (%s); generated group of order %d equal to G (order %d); transitive "
          "%s; orbits on unordered pairs: %d" % (", ".join("%s %s" % (k, v) for k, v in gperms.items()), len(grp), len(GA),
                                                 transitive, len(pair_orbits)),
          ok_h2 and len(grp) == 192 and grp == GA and transitive and len(pair_orbits) == 2)
rep.check("H3 T(P_j) = P_j for all j", all(L.transpose(P) == P for P in PJ))

# ------------------------------------------------------------------------------------------------ S twirl(BS) = S
ok_s1 = True
for b in range(4):
    b1, b2 = b >> 1, b & 1
    prod_ = L.ket_op(L.basis_vec([0, b1, b2]), X3)
    ok_s1 &= twirl(prod_) == (PJ[2 * b] + PJ[2 * b + 1]).scale(Fr(1, 2))
phim = L.ket_op([1, 0, 0, -1], (0, 1)).scale(Fr(1, 2))
plus = L.ket_op([1, 1], (2,)).scale(Fr(1, 2))
minus = L.ket_op([1, -1], (2,)).scale(Fr(1, 2))
bisep = L.tensor(L.phi_plus(0, 1), plus) + L.tensor(phim, minus)
ok_s1 &= (PJ[0] + PJ[2]) == bisep
rep.check("S1 twirl(|0 b1 b2><0 b1 b2|) = (P_2b + P_2b+1)/2 for all b; P_0 + P_2 = Phi+_12 (x) |+><+| + Phi-_12 (x) |-><-| "
          "(biseparable): with H2, S <= twirl(BS)", ok_s1)

# ------------------------------------------------------------------------------------------------ F single-token filters
SIGP = tuple(j ^ 1 for j in range(8))
ok_f = True
coef_txt = []
for q, xname in ((0, "X_1"), (1, "X_2"), (2, "X_3")):
    PIP = gperms[xname]
    PISIG = tuple(PIP[SIGP[j]] for j in range(8))
    for _ in range(3):
        A = [[L.rand_gauss(rng) for _ in range(2)] for _ in range(2)]
        Aop = mat1(A, q)
        M = [[L.pair(PJ[i], L.ad(Aop, PJ[k])) for k in range(8)] for i in range(8)]
        c1 = (A[0][0] + A[1][1]).abs2() / 4
        cs = (A[0][0] - A[1][1]).abs2() / 4
        cp = (A[0][1] + A[1][0]).abs2() / 4
        cps = (A[0][1] - A[1][0]).abs2() / 4
        for i in range(8):
            for k in range(8):
                exp = L.ZERO
                if i == k:
                    exp = exp + c1
                if i == SIGP[k]:
                    exp = exp + cs
                if i == PIP[k]:
                    exp = exp + cp
                if i == PISIG[k]:
                    exp = exp + cps
                ok_f &= M[i][k] == exp
        coef_txt.append("(%s, %s, %s, %s)" % (c1, cs, cp, cps))
rep.check("F single-token filters on each token (3 random exact complex A each): M = c_1 I + c_s Sig + c_p Pi + c_ps Pi Sig "
          "with the stated nonnegative coefficients; first instances %s" % ", ".join(coef_txt[:3]), ok_f)

# ------------------------------------------------------------------------------------------------ Y the W3 branch
def e(j):
    return tuple(int(k == j) for k in range(8))


def act(g, v):
    w = [0] * 8
    for i in range(8):
        w[g[i]] = v[i]
    return tuple(w)


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


mu = (-1, 1, 1, 1, 1, 1, 1, 1)
nu = (-1, 5, 1, 1, 1, 1, 1, 1)
yv = (21, -3, 5, 5, 5, 5, 5, 5)
Sgen = sorted(set(tuple(a + b for a, b in zip(e(j), e(k))) for j in range(8) for k in range(8) if j != k))
Kmu = Sgen + sorted(set(act(g, mu) for g in GA))
W3op = L.w3(X3)
mu_ok = [L.pair(W3op, P) * 2 for P in PJ] == [L.G(x) for x in mu]
nu_in = all(dot(nu, w) >= 0 for w in Kmu)
y_in = all(dot(yv, w) >= 0 for w in Kmu)
y_out = dot(yv, nu) < 0
y_orbit = all(dot(yv, act(g, yv)) >= 0 for g in GA)
nu_bad = dot(nu, act(SIGP, nu))
Yop = L.Op(X3, {})
Nop = L.Op(X3, {})
for j in range(8):
    Yop = Yop + PJ[j].scale(yv[j])
    Nop = Nop + PJ[j].scale(nu[j])
tie = L.pair(Yop, Nop) == L.G(dot(yv, nu))
rep.check("Y W3 branch: mu is 2 W3 in the P_j basis %s; nu in K_mu* %s; y in K_mu* %s; <y, nu> = %d < 0 (y outside K_mu); "
          "G-orbit of y self-positive %s; <nu, Sig nu> = %d < 0; tie-in tr(Y N) = <y, nu> %s"
          % (mu_ok, nu_in, y_in, dot(yv, nu), y_orbit, nu_bad, tie),
          mu_ok and nu_in and y_in and y_out and y_orbit and nu_bad < 0 and tie)

# ------------------------------------------------------------------------------------------------ N Bell-link networks
W = L.w3(X3)
kap = L.identity(X3).scale(Fr(1, 2)) + L.Op(X3, {(0, 7): L.ONE, (7, 0): L.ONE})
GH = L.ghz(X3)


def rel(A, m, qs):
    return L.reorder(L.relabel(A, m), qs)


vals = []
lk = L.tensor(L.phi_plus(0, 3), L.phi_plus(1, 4), L.phi_plus(2, 5))
vals.append(("theta(kappa, W3)", L.pair(lk, L.tensor(kap, rel(W, {0: 3, 1: 4, 2: 5}, (3, 4, 5))))))
a_, b_, ap, bp = 10, 11, 12, 13
for nm, (s1, s2, e1, e2) in (("K4 kWWW", (kap, W, W, W)), ("K4 WWkk", (W, W, kap, kap)),
                             ("K4 kkWW", (kap, kap, W, W)), ("K4 kWkW", (kap, W, kap, W))):
    x = rel(s1, {0: a_, 1: 1, 2: 2}, (a_, 1, 2))
    y = rel(s2, {0: b_, 1: 3, 2: 4}, (b_, 3, 4))
    xq = rel(e1, {0: ap, 1: 1, 2: 3}, (ap, 1, 3))
    yq = rel(e2, {0: bp, 1: 2, 2: 4}, (bp, 2, 4))
    vals.append((nm, L.pair(L.tensor(L.phi_plus(a_, b_), xq, yq), L.tensor(x, y, L.phi_plus(ap, bp)))))


def tok(i, j):
    return 3 * i + j


rows = [tuple(tok(i, j) for j in range(3)) for i in range(3)]
cols = [tuple(tok(i, j) for i in range(3)) for j in range(3)]


def place(A, qs):
    return rel(A, {0: qs[0], 1: qs[1], 2: qs[2]}, qs)


def latin(Rw, Cl):
    return L.pair(L.tensor(*[place(c, q) for c, q in zip(Cl, cols)]), L.tensor(*[place(r, q) for r, q in zip(Rw, rows)]))


vals.append(("Latin rows kappa, cols W3", latin([kap] * 3, [W] * 3)))
vals.append(("Latin rows W3, cols kappa", latin([W] * 3, [kap] * 3)))
vals.append(("Latin mixed", latin([kap, W, W], [W, kap, W])))
for nS, S_ in (("W3", W), ("GHZ", GH)):
    for nE, E_ in (("W3", W), ("GHZ", GH)):
        vals.append(("Latin rows %s, cols %s" % (nS, nE), latin([S_] * 3, [E_] * 3)))
cc = L.pair(lk, L.tensor(GH, rel(W, {0: 3, 1: 4, 2: 5}, (3, 4, 5))))
rep.check("N Bell-link values: %s; countercontrol theta(GHZ, W3) = %s < 0"
          % ("; ".join("%s = %s" % (k, v) for k, v in vals), cc),
          all(v.im == 0 and v.re >= 0 for _, v in vals) and cc.im == 0 and cc.re < 0)

rep.verdict("P11-SECTOR-REDUCTION-EXACT")
