"""EQ4-P probe p6 -- an exact countermodel at five tokens: the pair-network hierarchy.  Research only.

Usage:  python3 -I -B p6_five_token_model.py <base>/verification/lean-mathlib/OIBridge
Imports only the own library eq4_lib.py.

Model (aligned c = 0).  K_F = PN_F for every token set F with |F| <= 5: the closed convex cone generated by tensor
products of PSD operators over partitions of F into blocks of size <= 2 (so K_1 = PSD_2, K_2 = PSD_4 = Q3,
K_3 = BS != PSD_8, K_4 = PN_4, K_5 = PN_5); effect sets are the full duals.  Written claim (NOTES N3.2): every KT
constraint among families of at most five tokens holds -- for every family F and every two bipartitions X|Y, Z|W of F,
every product state of K_Z (x) K_W pairs nonnegatively with every product effect of K_X* (x) K_Y* (full duals) --
because in such a pairing every conditional reaching a block of at most two tokens is a CP image (Choi PSD), and every
conditional reaching three tokens is a local CP image of a BS element.  At six tokens the model fails (BS is not
co-self-dual).

DECISION RULE (fixed before the first run; rules, not expected numbers).  VERDICT `P6-FIVE-TOKEN-MODEL-EXACT` iff all:
  K  transcription control; the pair cone PSD_4 contains the gate's Bell link and is invariant under Ad(CNOT) (gate
     premise; Ad of a unitary preserves PSD -- checked on 3 random exact PSD instances).
  W  non-PN effects used below are in the full duals: W3 = 1/2 - GHZ and its images Ad(k) W3 under 3 random rational
     product filters k are in BS* (for every pure product across every cut the value is a nonnegative sum of squares:
     checked as the exact identity <a chi| Ad(k)W3 |a chi> = <a' chi'| W3 |a' chi'> with a' chi' = k^dag (a chi), a
     product across the same cut; with P1 of p1 for W3 itself), and the four-token witness w = 1/16 - C/32 is in PN_4*
     (largest Schmidt weight of c/2 across every cut <= 1/2, as in p4 D2).
  F  five tokens, crossing type (|P|,|Q|,|R|,|U|) = (1,1,1,2) (the only crossing type with all parts <= 3 at five
     tokens): (F1) for random PSD pair states x (on C) and pair effects e (on A), the conditional on B is
     (1/c)(Psi (x) id)(y renamed) with Psi the one-token map whose Choi matrix is computed exactly and is PSD (Psi CP),
     on all 64 units y; (F2) the values tr[(e (x) f)(x (x) y)] are >= 0 for y in BS (random products over all three
     cuts) and f in {W3, Ad(k) W3, GHZ} (12 instances each).
  N  non-crossing pairings at four and five tokens with full duals: tr[p (e (x) f)] >= 0 for p in PN_4 / PN_5 (random
     products over random partitions), e a single-token PSD effect and f in {W3 (x) PSD on the rest} or the PN_4*
     witness w (for 1|4); and for 2|2 / 2|3 effect splits with pair PSD effects and f in {W3, Ad(k) W3} (10 each).
  S  six-token control: PN_6 contains Phi+ (x) Phi+ (x) Phi+ and GHZ (x) W3 is a product of BS* effects; the value is
     negative (the model fails at six tokens; matches p1 P5).
"""
import random
import sys
from fractions import Fraction as Fr

sys.path.insert(0, __file__.rsplit("/", 1)[0] if "/" in __file__ else ".")
import eq4_lib as L  # noqa: E402

BASE = sys.argv[1]
rep = L.Report("p6_five_token_model")
rng = random.Random(20261009 + 6)
rep.check("K0 transcription control", L.transcription_control(BASE)[0])
CN = L.op(L.CNOT, (0, 1))
ok_g = L.psd(L.phi_plus(0, 1))[0]
for _ in range(3):
    ok_g &= L.psd(L.ad(CN, L.rand_psd(rng, (0, 1), rank=2)))[0]
rep.check("K1 gate premise: Phi+ in PSD_4; Ad(CNOT) maps PSD_4 into PSD_4 (3 random exact instances)", ok_g)


# ------------------------------------------------------------------------------------------------ W dual elements
def rand_mat2(rng_, invertible=True):
    while True:
        M = [[L.rand_gauss(rng_) for _ in range(2)] for _ in range(2)]
        det = M[0][0] * M[1][1] - M[0][1] * M[1][0]
        if not invertible or not det.is_zero():
            return M


def kprod(qs):
    return L.tensor(*[L.op(rand_mat2(rng), (q,)) for q in qs])


def apply_vec(K, vec):
    N = len(vec)
    out = [L.ZERO] * N
    for (r, c), v in K.d.items():
        out[r] = out[r] + v * L.G.of(vec[c])
    return out


T3 = (2, 3, 4)
W3 = L.w3(T3)
filters = [kprod(T3) for _ in range(3)]
W3k = [L.ad(k, W3) for k in filters]
ok_w = True
for k, Wk in zip(filters, W3k):
    kd = L.dag(k)
    for cut in range(3):
        for _ in range(3):
            a = [L.rand_gauss(rng) for _ in range(2)]
            chi = [L.rand_gauss(rng) for _ in range(4)]
            # product across cut: token T3[cut] carries a, the other two carry chi
            vec = [L.ZERO] * 8
            others = [i for i in range(3) if i != cut]
            for b0 in range(2):
                for b1 in range(2):
                    for b2 in range(2):
                        bits = (b0, b1, b2)
                        vec[4 * b0 + 2 * b1 + b2] = a[bits[cut]] * chi[2 * bits[others[0]] + bits[others[1]]]
            lhs = L.pair(Wk, L.ket_op(vec, T3))
            v2 = apply_vec(kd, vec)
            # k^dag maps a product across the cut to a product across the same cut (k is a product of one-token maps)
            rhs = L.pair(W3, L.ket_op(v2, T3))
            ok_w &= lhs == rhs and rhs.im == 0 and rhs.re >= 0
cvec = [0] * 16
for aa in range(2):
    for bb in range(2):
        cvec[L.bits_index((bb, (aa + bb) % 2, aa, aa))] = 1
Q4 = (0, 1, 2, 3)
C4 = L.ket_op(cvec, Q4)
wq = L.identity(Q4).scale(Fr(1, 16)) - C4.scale(Fr(1, 32))
cn = [Fr(x, 2) for x in cvec]
ok_wq = True
for part in [(0, 1), (0, 2), (0, 3), (0,), (1,), (2,), (3,)]:
    red = L.ptrace(L.ket_op(cn, Q4), part)
    ok_wq &= L.psd(L.identity(part).scale(Fr(1, 2)) - red)[0]
rep.check("W Ad(k) W3 (3 random rational product filters) is >= 0 on random pure products across every cut, by the "
          "exact identity with W3 on the pulled-back product (W3 in BS*: p1 P1); w = 1/16 - C/32 is in PN_4* (largest "
          "Schmidt weight of c/2 <= 1/2 across every cut)", ok_w and ok_wq)


# ------------------------------------------------------------------------------------------------ F five-token crossings
def rand_bs(qs):
    """random element of BS on three tokens: a positive sum of products over random cuts."""
    out = L.Op(qs, {})
    for _ in range(2):
        cut = rng.randrange(3)
        single = (qs[cut],)
        pair_ = tuple(q for q in qs if q != qs[cut])
        out = out + L.reorder(L.tensor(L.rand_psd(rng, single, rank=1), L.rand_psd(rng, pair_, rank=2)), qs)
    return out


z, p, q = 0, 1, 5        # A = (z, p) effects pair, C = (z, q) state pair; B = (q, s, t), D = (p, s, t)
s, t = 3, 4
ok_f1 = True
for _ in range(3):
    x = L.rand_psd(rng, (z, q), rank=2)
    e = L.rand_psd(rng, (z, p), rank=2)
    # one-token map Psi: p -> q with cond = Psi(y) on (q,s,t); Choi computed from units on token p
    J = L.choi(lambda u: L.reorder(L.cond(e, L.tensor(x, u)), (q,)), (p,), (q,))
    ok_f1 &= L.psd(J)[0]
    for _, y in L.units((p, s, t)):
        lhs = L.reorder(L.cond(e, L.tensor(x, y)), (q, s, t))
        # (Psi (x) id)(y): apply via the Choi matrix on token p, identity on s, t
        Jfull = L.reorder(L.tensor(J, L.Op((s, s + 10), {(a_ * 2 + a_, b_ * 2 + b_): L.ONE for a_ in range(2)
                                                         for b_ in range(2)}),
                                   L.Op((t, t + 10), {(a_ * 2 + a_, b_ * 2 + b_): L.ONE for a_ in range(2)
                                                      for b_ in range(2)})), (p, s, t, q, s + 10, t + 10))
        rhs = L.apply_choi(Jfull, (p, s, t), (q, s + 10, t + 10), y)
        rhs = L.reorder(L.relabel(rhs, {s + 10: s, t + 10: t}), (q, s, t))
        ok_f1 &= lhs == rhs
rep.check("F1 five-token crossing: the conditional on B is (Psi (x) id)(y) with Psi: p -> q a CP map (its Choi matrix "
          "is PSD, computed exactly), on all 64 units y, 3 random (x, e)", ok_f1)
ok_f2 = True
cnt = 0
Bq = (q, s, t)
fs = [L.reorder(L.relabel(W3, {2: q, 3: s, 4: t}), Bq)] + \
     [L.reorder(L.relabel(Wk, {2: q, 3: s, 4: t}), Bq) for Wk in W3k] + [L.ghz(Bq)]
for f in fs:
    for _ in range(12):
        x = L.rand_psd(rng, (z, q), rank=rng.choice([1, 2]))
        e = L.rand_psd(rng, (z, p), rank=rng.choice([1, 2]))
        y = rand_bs((p, s, t))
        v = L.pair(L.tensor(e, f), L.tensor(x, y))
        ok_f2 &= v.im == 0 and v.re >= 0
        cnt += 1
rep.check("F2 five-token values tr[(e (x) f)(x (x) y)] >= 0 for y in BS, f in {W3, Ad(k)W3 (3), GHZ}: %d exact "
          "instances" % cnt, ok_f2)


# ------------------------------------------------------------------------------------------------ N non-crossing
def rand_pn(tokens):
    toks = list(tokens)
    rng.shuffle(toks)
    blocks = []
    while toks:
        k = 2 if (len(toks) >= 2 and rng.random() < 0.6) else 1
        blocks.append(tuple(toks[:k]))
        toks = toks[k:]
    return L.reorder(L.tensor(*[L.rand_psd(rng, b, rank=rng.choice([1, 2])) for b in blocks]), tuple(tokens))


ok_n = True
cntn = 0
for _ in range(10):
    # four tokens, 1|3 effects: single PSD on 0, f in BS* on (1,2,3)
    pp = rand_pn((0, 1, 2, 3))
    f = L.ad(kprod((1, 2, 3)), L.w3((1, 2, 3)))
    v = L.pair(L.tensor(L.rand_psd(rng, (0,), rank=1), f), pp)
    ok_n &= v.im == 0 and v.re >= 0
    # five tokens, 1|4 effects with the PN_4* witness w on (1,2,3,4)
    p5 = rand_pn((0, 1, 2, 3, 4))
    wr = L.reorder(L.relabel(wq, {0: 1, 1: 2, 2: 3, 3: 4}), (1, 2, 3, 4))
    v = L.pair(L.tensor(L.rand_psd(rng, (0,), rank=1), wr), p5)
    ok_n &= v.im == 0 and v.re >= 0
    # five tokens, 2|3 effects: pair PSD on (0,1), f in BS* on (2,3,4)
    f3 = L.ad(kprod((2, 3, 4)), L.w3((2, 3, 4)))
    v = L.pair(L.tensor(L.rand_psd(rng, (0, 1), rank=2), f3), p5)
    ok_n &= v.im == 0 and v.re >= 0
    cntn += 3
rep.check("N non-crossing and 1|4, 2|3 pairings with full duals (W3 images, the PN_4* witness w): %d exact instances "
          ">= 0" % cntn, ok_n)

# ------------------------------------------------------------------------------------------------ S six-token control
links = L.tensor(L.phi_plus(0, 3), L.phi_plus(1, 4), L.phi_plus(2, 5))
v6 = L.pair(L.tensor(L.ghz((0, 1, 2)), L.w3((3, 4, 5))), links)
rep.check("S six-token control: PN_6 contains the Bell-link product and GHZ (x) W3 is a product of BS* effects; value "
          "%s < 0: the pair-network hierarchy violates KT at six tokens" % v6, v6.im == 0 and v6.re < 0)

rep.verdict("P6-FIVE-TOKEN-MODEL-EXACT")
