"""P2 -- the elementary-scope field: what the landed Stage fields do and do not bound.  Exact arithmetic only.

(a) BinaryVisible is satisfiable on a one-point body (zero/unit pair): it carries no non-triviality.
(b) A protocol tower over landed classical data (Z3 cycle, binary vis) satisfies SCInf, BinaryVisible, FiniteRank
    and has THREE perfectly distinguishable states by stage effects: capacity 3 (a triangle).
(c) The "face generated by a perfectly distinguishable extreme pair" construction does not bound capacity:
    triangular bipyramid.
(d) Qutrit with diagonal states: capacity 3 and P = diag(1,1,0) certain on two states (census replay).
(e) Square: every 3-vertex interpolation fails nonnegativity (capacity 2 under full effects, cf. kernel Lemma D),
    while the square is not relatively strictly convex (kernel not_relStrictConvex_square): the scope predicate
    is not the geometric conclusion in disguise.
"""
from fractions import Fraction as F
from itertools import product, combinations
import sympy as sp

res = []
def check(name, cond, det=''):
    res.append((name, bool(cond), det))

# (a) one preparation, effects {unit, zero}
p_tab = {('unit', 'x'): F(1), ('zero', 'x'): F(0)}
check('(a) one-point stage: zero+unit is a BinaryVisible test (sum 1), body is one point, rank 0',
      p_tab[('zero', 'x')] + p_tab[('unit', 'x')] == 1, 'v0 = zero, v1 = unit; SCInf trivially (constant tower)')
check('(a2) constant-1/2 effect paired with itself is also a BinaryVisible test', F(1, 2) + F(1, 2) == 1,
      'v0 = v1 = e with p(e,x) = 1/2: no sharpness, no distinctness required by the structure')

# (b) Z3 cycle protocol tower
OM = [0, 1, 2]
phi = lambda w: (w + 1) % 3
vis = lambda w: 1 if w == 0 else 0
MU = [F(1, 3)] * 3
def run(s, w):
    rec = []
    for a in s:
        if a == 'o':
            rec.append(vis(w))
        w = phi(w)
    return tuple(rec), w
def preps(n):
    P = {}
    for L in range(n + 1):
        for s in product('oi', repeat=L):
            b = {}
            for w in OM:
                r, w2 = run(s, w)
                b.setdefault(r, [F(0)] * 3)
                b[r][w2] += MU[w]
            for r, v in b.items():
                z = sum(v)
                if z:
                    P[(s, r)] = tuple(x / z for x in v)
    return P
P = preps(3)
def p(e, nu):
    s, r = e
    return sum(nu[w] * (1 if run(s, w)[0] == r else 0) for w in OM)
itin = {w: run(('o', 'o', 'o'), w)[0] for w in OM}
effs = [(('o', 'o', 'o'), itin[w]) for w in OM]          # three stage effects, same protocol
dets = {w: next(x for x, nu in P.items() if nu == tuple(F(1) if v == w else F(0) for v in OM)) for w in OM}
pd = all(p(effs[i], P[dets[OM[j]]]) == (1 if i == j else 0) for i in range(3) for j in range(3))
sums = all(sum(p(e, nu) for e in effs) == 1 for nu in P.values())
bv = all(p((('o',), (0,)), nu) + p((('o',), (1,)), nu) == 1 for nu in P.values())
rank = sp.Matrix([[p(((s), r), nu) for nu in set(P.values())]
                  for L in range(4) for s in product('o', repeat=L) for r in product((0, 1), repeat=L)]).rank()
check('(b) Z3 tower: three preps perfectly distinguishable by three stage effects summing to the unit',
      pd and sums, f'itineraries {itin}; preps {[dets[w] for w in OM]}')
check('(b2) Z3 tower: BinaryVisible holds; FiniteRank holds (affine dim = rank - 1)', bv and rank - 1 == 2,
      f'rank of the protocol matrix {rank}, affine dim {rank - 1}')

# (c) triangular bipyramid
Nn, Ss = (0, 0, 1), (0, 0, -1)
A = [(1, 0, 0), (0, 1, 0), (-1, -1, 0)]
V = [Nn, Ss] + A
def aff_eval(coef, v):
    return coef[0] + sum(c * x for c, x in zip(coef[1:], v))
eNS = (F(1, 2), 0, 0, F(1, 2))                          # (1+z)/2
ok_ns = [aff_eval(eNS, v) for v in V]
check('(c) bipyramid: N,S perfectly distinguishable by (1+z)/2 and 1-(1+z)/2 (values on vertices in [0,1])',
      all(0 <= t <= 1 for t in ok_ns) and aff_eval(eNS, Nn) == 1 and aff_eval(eNS, Ss) == 0, f'values {ok_ns}')
# barycentric coordinates of the equator triangle, independent of z
xs, ys = sp.symbols('x y')
lam = []
Mt = sp.Matrix([[1, 1, 1], [A[0][0], A[1][0], A[2][0]], [A[0][1], A[1][1], A[2][1]]])
Minv = Mt.inv()
for k in range(3):
    lam.append((Minv[k, 0], Minv[k, 1], Minv[k, 2], 0))
vals = [[aff_eval(l, v) for v in V] for l in lam]
check('(c2) bipyramid: equator triple perfectly distinguishable (barycentric effects, >=0 on all 5 vertices, sum 1)',
      all(0 <= t <= 1 for row in vals for t in row) and all(sum(vals[k][j] for k in range(3)) == 1 for j in range(5))
      and all(vals[k][2 + j] == (1 if k == j else 0) for k in range(3) for j in range(3)), f'values {vals}')
# midpoint of N,S is the origin: strictly positive combination of all 5 vertices, which affinely span R^3
w = [F(1, 4), F(1, 4), F(1, 6), F(1, 6), F(1, 6)]
mid = tuple(sum(wi * v[c] for wi, v in zip(w, V)) for c in range(3))
span = sp.Matrix([[v[c] - V[0][c] for c in range(3)] for v in V[1:]]).rank()
check('(c3) bipyramid: midpoint of N,S is interior, so the face generated by the sharp pair is the whole body',
      mid == (0, 0, 0) and sum(w) == 1 and min(w) > 0 and span == 3, f'weights {w}')

# (d) qutrit diagonal
D3 = [[F(1) if i == j else F(0) for i in range(3)] for j in range(3)]  # diagonal states e_j
P2 = [F(1), F(1), F(0)]
certain = [j for j in range(3) if sum(P2[i] * D3[j][i] for i in range(3)) == 1]
check('(d) qutrit: P=diag(1,1,0) proper and certain on two distinct states; diagonal projectors give capacity 3',
      certain == [0, 1] and sum(P2[i] * D3[2][i] for i in range(3)) == 0, f'certain on {certain}')

# (e) square [-1,1]^2: for every 3-subset of vertices, the unique affine interpolation e_i(v_j) = delta_ij
sq = [(1, 1), (1, -1), (-1, -1), (-1, 1)]
allfail = True
detail = []
for tri in combinations(range(4), 3):
    rest = [k for k in range(4) if k not in tri][0]
    M = sp.Matrix([[1, sq[k][0], sq[k][1]] for k in tri])
    Minv = M.inv()
    fourth = [sum(Minv[r, i] * c for r, c in enumerate((1, sq[rest][0], sq[rest][1]))) for i in range(3)]
    neg = min(fourth) < 0
    allfail &= neg
    detail.append((tri, [str(t) for t in fourth]))
check('(e) square: every 3-vertex interpolation is negative at the fourth vertex (no 3 vertices distinguishable)',
      allfail, str(detail))

allok = all(c for _, c, _ in res)
for n, c, d in res:
    print(('PASS ' if c else 'FAIL ') + n + (' -- ' + d if d else ''))
print('ALL-PASS' if allok else 'SOME-FAIL')
