"""A45 Q2 exact probe: composition/intervention stability of the visible relation R0 (research, not frozen).

Realizations R0..R4 from q1_probe (all admissible dilations of the same visible slice J/16). An intervention M acting
before the visible readout sends H to the slice |M H N|^2 (N acting on the input side). Measured:
  S1  monomial interventions (permutation x diagonal unit, and a scaled partial permutation -- the stated access
      `permClass` = IsScaledPartialPerm) preserve R0: the slices of M H N agree across all five realizations;
  S2  a non-monomial intervention K (one Fourier factor K = F4(i) (x) I4, and K = SIG^H) separates realizations sharing
      the slice, including the two-sided-equivalent pair R0/R1, and the Dita / non-Dita pair R3/R4;
  S3  the relation generated by all left unitary interventions contains right-diagonal equivalence (|K H D|^2 = |K H|^2)
      and separates left-diagonal moves (R0 vs D1.R0) -- strictly finer than the two-sided class;
  S4  the named Q_fb embedding composed with monomial interventions stays realization-independent.
"""
import itertools, json, random, sys, importlib.util, io, contextlib
spec = importlib.util.spec_from_file_location('q1', __file__.replace('q2_probe.py', 'q1_probe.py'))
q1 = importlib.util.module_from_spec(spec)
with contextlib.redirect_stdout(io.StringIO()):
    sys.argv = [sys.argv[0], '/dev/null']; spec.loader.exec_module(q1)
G, ZERO, ONE, I_, Fr = q1.G, q1.ZERO, q1.ONE, q1.I_, q1.Fr
REAL, names = q1.REAL, list(q1.REAL)
def mm(A, B): return [[sum((A[i][k] * B[k][j] for k in range(16)), ZERO) for j in range(16)] for i in range(16)]
def slice_(H): return tuple(tuple(x.n2() for x in r) for r in H)
rng = random.Random(4502)
units = [G(Fr(3, 5), Fr(4, 5)), G(Fr(5, 13), Fr(12, 13)), I_, G(-1), ONE]
def perm_diag():
    p = list(range(16)); rng.shuffle(p); d = [rng.choice(units) for _ in range(16)]
    return [[d[i] if p[i] == j else ZERO for j in range(16)] for i in range(16)]
def scaled_partial_perm():
    p = list(range(16)); rng.shuffle(p); keep = set(rng.sample(range(16), 11))
    return [[G(2) * rng.choice(units) if (p[i] == j and i in keep) else ZERO for j in range(16)] for i in range(16)]
def is_monomial(M): return all(sum(1 for x in r if x != ZERO) <= 1 for r in M) and all(sum(1 for r in M if r[j] != ZERO) <= 1 for j in range(16))
out = {}
# S1
S1 = []
for kind, maker in (('perm x diag', perm_diag), ('scaled partial perm', scaled_partial_perm)):
    for _ in range(3):
        M, N = maker(), maker()
        sl = {nm: slice_(mm(mm(M, H), N)) for nm, H in REAL.items()}
        S1.append({'kind': kind, 'monomial': is_monomial(M) and is_monomial(N), 'all_equal': len(set(sl.values())) == 1})
out['S1_monomial_preserves_R0'] = S1
print('S1 monomial interventions preserve the visible relation:', all(x['all_equal'] and x['monomial'] for x in S1), flush=True)
# S2
F4i = q1.F4(I_)
KF = [[F4i[i // 4][j // 4] if i % 4 == j % 4 else ZERO for j in range(16)] for i in range(16)]      # F4(i) (x) I4, scaled by 2
KS = [[q1.SIG[j][i].conj() for j in range(16)] for i in range(16)]                                   # SIG^H, scaled by 4
S2 = {}
for kn, K in (('F4(i) (x) I4', KF), ('SIG^H', KS)):
    sl = {nm: slice_(mm(K, H)) for nm, H in REAL.items()}
    pairs = {'%s | %s' % (a, b): sl[a] != sl[b] for a, b in itertools.combinations(names, 2)}
    S2[kn] = {'non_monomial': not is_monomial(K), 'separated_pairs': [p for p, s in pairs.items() if s], 'n_separated': sum(pairs.values()), 'n_pairs': len(pairs)}
    print('S2 %-14s non-monomial %s: separates %d of %d pairs; R0|R1 (two-sided equivalent) %s; R3|R4 (Dita|non-Dita) %s' % (
        kn, S2[kn]['non_monomial'], S2[kn]['n_separated'], len(pairs), pairs['%s | %s' % (names[0], names[1])], pairs['%s | %s' % (names[3], names[4])]), flush=True)
out['S2_nonmonomial_separates'] = S2
# S3
H = REAL[names[0]]
Dr = [rng.choice(units) for _ in range(16)]; Dl = [rng.choice(units) for _ in range(16)]
HDr = [[H[i][j] * Dr[j] for j in range(16)] for i in range(16)]; DlH = [[Dl[i] * H[i][j] for j in range(16)] for i in range(16)]
right_inv = all(slice_(mm(K, HDr)) == slice_(mm(K, H)) for K in (KF, KS))
left_sep = any(slice_(mm(K, DlH)) != slice_(mm(K, H)) for K in (KF, KS))
out['S3'] = {'right_diagonal_invisible_under_left_interventions': right_inv, 'left_diagonal_separated': left_sep}
print('S3 right-diagonal moves invisible: %s; left-diagonal moves separated: %s' % (right_inv, left_sep), flush=True)
# S4
def rooted_of(H):
    M = [[H[b2][b].n2() / 16 for b2 in range(16)] for b in range(16)]
    return tuple(tuple(r) for r in M)
M, N = perm_diag(), perm_diag()
out['S4_qfb_under_monomial'] = len(set(rooted_of(mm(mm(M, H_), N)) for H_ in REAL.values())) == 1
print('S4 named Q_fb embedding under monomial interventions realization-independent:', out['S4_qfb_under_monomial'])
ok = all(x['all_equal'] and x['monomial'] for x in S1) and all(v['non_monomial'] and v['n_separated'] > 0 for v in S2.values()) and right_inv and left_sep and out['S4_qfb_under_monomial']
print('Q2 PROBE: ALL EXPECTED' if ok else 'Q2 PROBE: UNEXPECTED RESULT')
json.dump(out, open('q2_probe.json', 'w'), indent=1, sort_keys=True)
