#!/usr/bin/env python3
"""S2 / node S2.5 (decisive) + S2.4: the fixed-frame native-gate family, its consistent subsets, and the cones
they generate from the product states.  Exact integer / rational / Gaussian-rational arithmetic only.

Run:  cd pt/S2 && python3 -I -B s2_1_native.py ../base/verification/lean-mathlib/OIBridge

Objects (landed definitions, transcribed and checked in R0):
  W 3 = 4x4 real tables (index 0 = unit, 1..3 = ball coordinates x0,x1,x2); prodState x y = hom x hom y^T;
  actC N w = homMap(N) w ; actT N w = w homMap(N)^T ; homMap N = blockdiag(1, N);
  cnot = the signed permutation sgn/pc/pt of CompositeDimension.lean; nflip = diag(1,-1,-1); reflY = diag(1,-1,1);
  z3 = (0,0,1); xplus = (1,0,0); phiW; idW; chainW (K2Guard).
  The native family F64 (Thread D, D1.4, frame (z3, nflip)):  G(D, D', R0) = actC D o cnot o actC D' o actT R0,
  D, D', R0 in {diag(s1, s2, 1)}.  The superset S4096: actC D o actT E o cnot o actC D' o actT E',
  D, E, D', E' in {diag(+-1,+-1,+-1)}.
  Orientation (design NClass/orient): post-locals (A,B) applied last, pre-locals (A',B') applied first;
  orient_post = [det A det B = -1], orient_pre = [det A' det B' = -1].
  sigma = actT reflY.  K_gen = cone(SEP u cnot SEP).

DECISION RULES (fixed before the first run; rules, not expected numbers):
 R0 Transcription.  pc, pt and sgn parsed from the landed source equal the hard-coded tables; the landed identities
    cnotFun_cnotFun, cnot_frame, cnot_relT, cnot_relC, cnot_prodState_xplus_z3 (= phiW), cnot_idW (= chainW) and
    chain_value (= -1/2) hold exactly.  Any failure: ABORT, no verdict.
 R1 Dictionary (Pauli coordinates w_mn = Tr(rho s_m (x) s_n), s = I,X,Y,Z).  cnot = Ad(CNOT) on all 16 basis tables;
    each proper signed-diagonal Bloch map = Ad(Pauli); reflY = the one-copy transpose; actC reflY o actT reflY = the
    global transpose; the global transpose commutes with cnot.  Countercontrol: cnot != Ad(reversed CNOT) (must hold).
 R2 Native family.  Every member of F64 satisfies NativeGate's frame, relT and relC exactly.  The distinct maps of F64
    are counted.  The members of S4096 satisfying frame, relT and relC are computed; their distinct set must EQUAL the
    distinct set of F64 (an exact cross-check of D1.4 within signed-diagonal dressings).  Countercontrol:
    actC diag(1,1,-1) o cnot must FAIL the frame clause.
 R3 Orientation.  For every distinct native gate, all its decompositions inside S4096 give one (orient_pre,
    orient_post) pair (exact cross-check of D's T2 on this family).
 R4 Absorption.  For each of the 64 signed-diagonal locals L = actC D o actT E: cnot o L o cnot is a signed-diagonal
    local iff det D det E = +1.  For every odd L an exact product state with a non-product image (table rank > 1) is
    exhibited.  Countercontrol: the identity local is absorbed (cnot o id o cnot = id).
 R5 Consistency.  For every ordered pair (Gi, Gj) of distinct native gates with odd residue
    (orient_pre(Gi) != orient_post(Gj)) an exact witness is found: axis states x, y in {+-e_k} and axis sharp effects
    e, f along {+-e_k} with prodEffVal e f (Gi(Gj(prodState x y))) < 0.  A pair without a witness makes the
    classification INCOMPLETE (reported, no class verdict).  Even-residue pairs are covered by R4 (written argument).
 R6 Classes.  The group generated by the native gates with (orient_pre, orient_post) = (even, even) is closed exactly
    (finite); every element equals L or L o cnot o L' with signed-diagonal locals L, L'; for every even local L,
    L o cnot = cnot o L'' with L'' a signed-diagonal local.  The (odd, odd) class equals sigma o (even class) o sigma.
 R7 Positivity spot check (supports the written posFwd argument): for every native gate and axis product state, the
    image lies in Q3 or in twin = sigma(Q3) (exact principal-minor PSD test).
 VERDICT lines print only if R0-R7 pass and every countercontrol behaves as required.
"""
import sys, os, re, itertools
from fractions import Fraction as Fr

OK = True
NPASS = 0
def check(name, cond, detail=""):
    global OK, NPASS
    if cond:
        NPASS += 1
        print(f"PASS {name}" + (f"  [{detail}]" if detail else ""))
    else:
        OK = False
        print(f"FAIL {name}" + (f"  [{detail}]" if detail else ""))

def control(name, should_fail_cond, detail=""):
    """A countercontrol: the stated condition must be FALSE (the control must fail)."""
    global OK, NPASS
    if not should_fail_cond:
        NPASS += 1
        print(f"PASS countercontrol {name} fails as required" + (f"  [{detail}]" if detail else ""))
    else:
        OK = False
        print(f"FAIL countercontrol {name} did not fail" + (f"  [{detail}]" if detail else ""))

# ---------------------------------------------------------------- linear algebra on W 3 (16-vectors, 16x16 maps)
IDX = [(m, n) for m in range(4) for n in range(4)]
def k(m, n): return 4 * m + n

def mat_mul(A, B):
    n = len(A); p = len(B[0]); q = len(B)
    return tuple(tuple(sum(A[i][r] * B[r][j] for r in range(q) if A[i][r]) for j in range(p)) for i in range(n))

def mat_vec(A, v):
    return tuple(sum(A[i][r] * v[r] for r in range(len(v)) if A[i][r]) for i in range(len(A)))

def ident(n=16):
    return tuple(tuple(1 if i == j else 0 for j in range(n)) for i in range(n))

I16 = ident()

def homMap(N):  # N: 3x3
    H = [[0] * 4 for _ in range(4)]
    H[0][0] = 1
    for i in range(3):
        for j in range(3):
            H[i + 1][j + 1] = N[i][j]
    return H

def actC_map(N):
    H = homMap(N)
    M = [[0] * 16 for _ in range(16)]
    for m in range(4):
        for n in range(4):
            for kk in range(4):
                if H[m][kk]:
                    M[k(m, n)][k(kk, n)] += H[m][kk]
    return tuple(tuple(r) for r in M)

def actT_map(N):
    H = homMap(N)
    M = [[0] * 16 for _ in range(16)]
    for m in range(4):
        for n in range(4):
            for l in range(4):
                if H[n][l]:
                    M[k(m, n)][k(m, l)] += H[n][l]
    return tuple(tuple(r) for r in M)

def diag3(a, b, c): return [[a, 0, 0], [0, b, 0], [0, 0, c]]
def det3(N):
    return (N[0][0] * (N[1][1] * N[2][2] - N[1][2] * N[2][1]) - N[0][1] * (N[1][0] * N[2][2] - N[1][2] * N[2][0])
            + N[0][2] * (N[1][0] * N[2][1] - N[1][1] * N[2][0]))

def hom(x): return (1, x[0], x[1], x[2])
def prodState(x, y):
    hx, hy = hom(x), hom(y)
    return tuple(hx[m] * hy[n] for (m, n) in IDX)
def pairVal(a, b, w):
    return sum(a[m] * w[k(m, n)] * b[n] for (m, n) in IDX)

def table_rank(w):
    M = [[Fr(w[k(m, n)]) for n in range(4)] for m in range(4)]
    r = 0
    for c in range(4):
        piv = None
        for i in range(r, 4):
            if M[i][c] != 0:
                piv = i; break
        if piv is None: continue
        M[r], M[piv] = M[piv], M[r]
        for i in range(4):
            if i != r and M[i][c] != 0:
                f = M[i][c] / M[r][c]
                M[i] = [M[i][j] - f * M[r][j] for j in range(4)]
        r += 1
    return r

# ---------------------------------------------------------------- R0: transcription of the landed cnot
oib = sys.argv[1] if len(sys.argv) > 1 else "../base/verification/lean-mathlib/OIBridge"
src = open(os.path.join(oib, "CompositeDimension.lean"), encoding="utf-8").read()

PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]
def SGN(m, n): return -1 if ((m == 1 and n == 3) or (m == 2 and n == 2)) else 1

def parse_table(name):
    mm = re.search(r"def " + name + r" : Fin 4 → Fin 4 → Fin 4\n(.*?)\n\n", src, re.S)
    body = mm.group(1)
    arms = re.findall(r"\|\s*(\d),\s*(\d)\s*=>\s*(\d)", body)
    T = [[None] * 4 for _ in range(4)]
    for a, b, c in arms:
        T[int(a)][int(b)] = int(c)
    return T

check("R0.pc parsed = hard-coded", parse_table("pc") == PC)
check("R0.pt parsed = hard-coded", parse_table("pt") == PT)
sgn_line = re.search(r"def sgn \(μ ν : Fin 4\) : ℝ := (.*)\n", src).group(1).strip()
check("R0.sgn source text", sgn_line == "if (μ = 1 ∧ ν = 3) ∨ (μ = 2 ∧ ν = 2) then -1 else 1", sgn_line)

CNOT = [[0] * 16 for _ in range(16)]
for (m, n) in IDX:
    CNOT[k(m, n)][k(PC[m][n], PT[m][n])] = SGN(m, n)
CNOT = tuple(tuple(r) for r in CNOT)
check("R0.cnotFun_cnotFun", mat_mul(CNOT, CNOT) == I16)

z3 = (0, 0, 1); xplus = (1, 0, 0)
def neg(x): return tuple(-t for t in x)
corner = {0: z3, 1: neg(z3)}
NFLIP = diag3(1, -1, -1); REFLY = diag3(1, -1, 1); I3 = diag3(1, 1, 1)
phiW = tuple((1 if m != 2 else -1) if m == n else 0 for (m, n) in IDX)
idW = tuple(1 if m == n else 0 for (m, n) in IDX)
chainW = (1, 0, 0, 1, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0)

def frame_ok(G):
    return all(mat_vec(G, prodState(corner[a], corner[b])) == prodState(corner[a], corner[(a + b) % 2])
               for a in (0, 1) for b in (0, 1))
ACn, ATn = actC_map(NFLIP), actT_map(NFLIP)
def relT_ok(G): return mat_mul(ATn, mat_mul(G, ATn)) == G
def relC_ok(G): return mat_mul(ACn, mat_mul(G, ACn)) == mat_mul(ATn, G)

check("R0.cnot_frame", frame_ok(CNOT))
check("R0.cnot_relT", relT_ok(CNOT))
check("R0.cnot_relC", relC_ok(CNOT))
pxz = prodState(xplus, z3)
check("R0.cnot_prodState_xplus_z3 = phiW", mat_vec(CNOT, pxz) == phiW)
check("R0.cnot_idW = chainW", mat_vec(CNOT, idW) == chainW)
SIGMA = actT_map(REFLY)
check("R0.actT_reflY_phiW = idW", mat_vec(SIGMA, phiW) == idW)
sharp2 = lambda b: (1, b[0], b[1], b[2])          # 2 * sharpVec b (integer scaling; sign-exact)
cv = Fr(pairVal(sharp2((-1, 0, 0)), sharp2((0, 0, -1)), chainW), 4)
check("R0.chain_value = -1/2", cv == Fr(-1, 2), str(cv))

if not OK:
    print("ABORT: transcription failed; no verdict"); sys.exit(1)

# ---------------------------------------------------------------- R1: Pauli dictionary (sympy, Gaussian rationals)
import sympy as sp
I2 = sp.eye(2); X = sp.Matrix([[0, 1], [1, 0]]); Y = sp.Matrix([[0, -sp.I], [sp.I, 0]]); Z = sp.Matrix([[1, 0], [0, -1]])
PAULI = [I2, X, Y, Z]
def kron(A, B): return sp.kronecker_product(A, B)
SS = [[kron(PAULI[m], PAULI[n]) for n in range(4)] for m in range(4)]
def rho_of(w):
    R = sp.zeros(4, 4)
    for (m, n) in IDX:
        if w[k(m, n)] != 0:
            R += sp.Rational(w[k(m, n)]) * SS[m][n]
    return R / 4
def w_of(R):
    return tuple(sp.nsimplify(sp.simplify((R * SS[m][n]).trace())) for (m, n) in IDX)
def Ad_map(U):
    Ud = U.H
    cols = []
    for (m, n) in IDX:
        img = U * SS[m][n] * Ud
        cols.append(w_of(img / 1))
    # column (m,n) is the image of the basis table e_mn scaled: basis table e_mn <-> rho = SS[m][n]/4
    M = [[0] * 16 for _ in range(16)]
    for c, (m, n) in enumerate(IDX):
        col = cols[c]
        for r in range(16):
            M[r][c] = sp.Rational(col[r]) / 4 if col[r] != 0 else 0
    return tuple(tuple(int(x) if (x == int(x)) else x for x in row) for row in M)

P0 = sp.Matrix([[1, 0], [0, 0]]); P1 = sp.Matrix([[0, 0], [0, 1]])
UCNOT = kron(P0, I2) + kron(P1, X)
URCNOT = kron(I2, P0) + kron(X, P1)          # reversed: control on the second token
check("R1.cnot = Ad(CNOT) on all 16 basis tables", Ad_map(UCNOT) == CNOT)
control("R1.cnot = Ad(reversed CNOT)", Ad_map(URCNOT) == CNOT)
BLOCH_OF_PAULI = {"X": (diag3(1, -1, -1), X), "Y": (diag3(-1, 1, -1), Y), "Z": (diag3(-1, -1, 1), Z)}
for nm, (D, U) in BLOCH_OF_PAULI.items():
    check(f"R1.actC {D} = Ad({nm} (x) I)", actC_map(D) == Ad_map(kron(U, I2)))
    check(f"R1.actT {D} = Ad(I (x) {nm})", actT_map(D) == Ad_map(kron(I2, U)))
def transpose_map(which):
    M = [[0] * 16 for _ in range(16)]
    for (m, n) in IDX:
        img = SS[m][n]
        if which == "B":
            img = kron(PAULI[m], PAULI[n].T)
        elif which == "A":
            img = kron(PAULI[m].T, PAULI[n])
        else:
            img = img.T
        w = w_of(img)
        for r in range(16):
            M[r][k(m, n)] = sp.Rational(w[r]) / 4 if w[r] != 0 else 0
    return tuple(tuple(int(x) if x == int(x) else x for x in row) for row in M)
check("R1.sigma = actT reflY = one-copy transpose on token 2", SIGMA == transpose_map("B"))
check("R1.actC reflY = one-copy transpose on token 1", actC_map(REFLY) == transpose_map("A"))
TT = mat_mul(actC_map(REFLY), SIGMA)
check("R1.actC reflY o actT reflY = global transpose", TT == transpose_map("G"))
check("R1.global transpose commutes with cnot", mat_mul(TT, CNOT) == mat_mul(CNOT, TT))

# ---------------------------------------------------------------- R2: the native family
SD = [diag3(a, b, c) for a in (1, -1) for b in (1, -1) for c in (1, -1)]        # 8 signed diagonals
SDz = [diag3(a, b, 1) for a in (1, -1) for b in (1, -1)]                           # z-entry +1
ACm = {tuple(map(tuple, D)): actC_map(D) for D in SD}
ATm = {tuple(map(tuple, D)): actT_map(D) for D in SD}
def T3(D): return tuple(map(tuple, D))
def G_of(D, E, Dp, Ep):
    return mat_mul(ACm[T3(D)], mat_mul(ATm[T3(E)], mat_mul(CNOT, mat_mul(ACm[T3(Dp)], ATm[T3(Ep)]))))

F64 = []
for D in SDz:
    for Dp in SDz:
        for R0 in SDz:
            G = G_of(D, I3, Dp, R0)
            F64.append((G, (T3(D), T3(I3), T3(Dp), T3(R0))))
check("R2.F64 all frame", all(frame_ok(G) for G, _ in F64))
check("R2.F64 all relT", all(relT_ok(G) for G, _ in F64))
check("R2.F64 all relC", all(relC_ok(G) for G, _ in F64))
F64set = {G for G, _ in F64}
print(f"INFO F64 combos=64 distinct maps={len(F64set)}")
control("R2.actC diag(1,1,-1) o cnot satisfies frame", frame_ok(mat_mul(actC_map(diag3(1, 1, -1)), CNOT)))

S4096 = {}
for D in SD:
    for E in SD:
        for Dp in SD:
            for Ep in SD:
                G = G_of(D, E, Dp, Ep)
                S4096.setdefault(G, []).append((T3(D), T3(E), T3(Dp), T3(Ep)))
native_super = {G for G in S4096 if frame_ok(G) and relT_ok(G) and relC_ok(G)}
print(f"INFO S4096 distinct maps={len(S4096)} satisfying frame+relT+relC={len(native_super)}")
check("R2.native subset of S4096 equals F64 distinct set", native_super == F64set,
      f"{len(native_super)} vs {len(F64set)}")

# ---------------------------------------------------------------- R3: orientation bits
def orient_pair(dec):
    D, E, Dp, Ep = dec
    post = det3(D) * det3(E) == -1
    pre = det3(Dp) * det3(Ep) == -1
    return (pre, post)
NATIVE = sorted(F64set)
ORI = {}
single = True
for G in NATIVE:
    pairs = {orient_pair(d) for d in S4096[G]}
    if len(pairs) != 1:
        single = False
    ORI[G] = pairs.pop()
check("R3.each native gate has one (orient_pre, orient_post)", single)
from collections import Counter
cnt = Counter(ORI[G] for G in NATIVE)
print("INFO orientation classes (pre_odd, post_odd): " +
      ", ".join(f"{key}:{cnt[key]}" for key in sorted(cnt)))
check("R3.cnot is (even, even)", ORI[CNOT] == (False, False))

# ---------------------------------------------------------------- R4: absorption
LOCALS = {}
for D in SD:
    for E in SD:
        LOCALS[mat_mul(ACm[T3(D)], ATm[T3(E)])] = (T3(D), T3(E))
check("R4.64 distinct signed-diagonal locals", len(LOCALS) == 64)
axis = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]
absorb_ok = True
odd_witness_ok = True
for L, (D, E) in LOCALS.items():
    M = mat_mul(CNOT, mat_mul(L, CNOT))
    even = det3(D) * det3(E) == 1
    is_local = M in LOCALS
    if even != is_local:
        absorb_ok = False
    if not even:
        found = False
        for x in axis:
            for y in axis:
                if table_rank(mat_vec(M, prodState(x, y))) > 1:
                    found = True; break
            if found: break
        if not found:
            odd_witness_ok = False
check("R4.cnot L cnot is local iff L is orientation-even (all 64)", absorb_ok)
check("R4.every odd L has an axis product with non-product image", odd_witness_ok)
control("R4.identity local not absorbed", mat_mul(CNOT, mat_mul(I16, CNOT)) not in LOCALS)

# ---------------------------------------------------------------- R5: consistency witnesses
STATES = [prodState(x, y) for x in axis for y in axis]
EFFS = [(sharp2(e), sharp2(f)) for e in axis for f in axis]
n_odd = 0; n_wit = 0; n_even = 0
for Gi in NATIVE:
    for Gj in NATIVE:
        odd = ORI[Gi][0] != ORI[Gj][1]
        if not odd:
            n_even += 1
            continue
        n_odd += 1
        W = mat_mul(Gi, Gj)
        found = False
        for s in STATES:
            img = mat_vec(W, s)
            for (a, b) in EFFS:
                if pairVal(a, b, img) < 0:
                    found = True; break
            if found: break
        if found:
            n_wit += 1
print(f"INFO ordered pairs: odd residue={n_odd}, with exact negative witness={n_wit}; even residue={n_even}")
check("R5.every odd-residue pair has an exact invalidity witness", n_wit == n_odd and n_odd > 0)
# countercontrol: the even pair (cnot, cnot) must have NO negative value on axis data (cnot o cnot = id)
neg_cc = any(pairVal(a, b, mat_vec(mat_mul(CNOT, CNOT), s)) < 0 for s in STATES for (a, b) in EFFS)
control("R5.(cnot,cnot) shows a negative axis value", neg_cc)

# ---------------------------------------------------------------- R6: the classes and their groups
EE = [G for G in NATIVE if ORI[G] == (False, False)]
OO = [G for G in NATIVE if ORI[G] == (True, True)]
def closure(gens):
    seen = {I16}
    frontier = [I16]
    while frontier:
        nxt = []
        for g in frontier:
            for h in gens:
                p = mat_mul(h, g)
                if p not in seen:
                    seen.add(p); nxt.append(p)
        frontier = nxt
    return seen
GEE = closure(EE)
print(f"INFO even-even native gates={len(EE)}, generated group order={len(GEE)}")
LOCSET = set(LOCALS)
dec_ok = True
for g in GEE:
    if g in LOCSET:
        continue
    found = False
    for L in LOCSET:
        Ag = mat_mul(L, g)            # L^-1 = L for signed diagonals; test L o g = cnot o L'
        Mg = mat_mul(CNOT, Ag)        # cnot o L o g should be a local L'
        if Mg in LOCSET:
            found = True; break
    if not found:
        dec_ok = False
check("R6.every element of <even-even natives> is L or L o cnot o L'", dec_ok)
even_locals = [L for L, (D, E) in LOCALS.items() if det3(D) * det3(E) == 1]
lc_ok = all(mat_mul(CNOT, mat_mul(L, CNOT)) in LOCSET for L in even_locals)
check("R6.for every even local L: L o cnot = cnot o L'' with L'' local", lc_ok)
# post-locals that occur: for g = L o cnot o L', L is even
post_even = True
for g in GEE:
    if g in LOCSET:
        continue
    for L in LOCSET:
        if mat_mul(CNOT, mat_mul(L, g)) in LOCSET:
            D, E = LOCALS[L]
            if det3(D) * det3(E) != 1:
                post_even = False
check("R6.every decomposition g = L o cnot o L' in the even class has L even", post_even)
conj_ok = {mat_mul(SIGMA, mat_mul(G, SIGMA)) for G in OO} == set(EE)
check("R6.odd-odd class = sigma o (even-even class) o sigma", conj_ok)
GOO = closure(OO)
print(f"INFO odd-odd native gates={len(OO)}, generated group order={len(GOO)}")
mixed = closure(EE + OO[:1])
bad_mixed = any(any(pairVal(a, b, mat_vec(g, s)) < 0 for s in STATES for (a, b) in EFFS) for g in mixed)
control("R6.the group of the even class plus one odd-odd gate stays valid on axis data", not bad_mixed)

# ---------------------------------------------------------------- R7: positivity spot check
def psd_exact(R):
    n = R.shape[0]
    for r in range(1, n + 1):
        for S in itertools.combinations(range(n), r):
            d = sp.nsimplify(sp.simplify(R.extract(list(S), list(S)).det()))
            if sp.re(d) < 0:
                return False
    return True
q3_or_twin = True
for G in NATIVE:
    for x in axis:
        for y in axis:
            w = mat_vec(G, prodState(x, y))
            if not (psd_exact(rho_of(w)) or psd_exact(rho_of(mat_vec(SIGMA, w)))):
                q3_or_twin = False
check("R7.native images of axis products lie in Q3 or twin", q3_or_twin)

# ---------------------------------------------------------------- verdict
print(f"SUMMARY checks passed={NPASS} all_ok={OK}")
if OK:
    print("VERDICT FIXED-FRAME-NATIVE-FAMILY: frame+relT+relC within signed-diagonal dressings = the D1.4 family "
          f"({len(F64set)} distinct gates); one orientation pair per gate")
    print("VERDICT CONSISTENCY: a set of fixed-frame native gates generates valid tables only if every residue is "
          "even (exact witnesses for every odd ordered pair); even residues are absorbed (cnot L cnot local)")
    print("VERDICT CONES: every consistent fixed-frame native construction is generated by L o cnot^e o L' with "
          "even post-locals absorbed: generated cone = K_gen (even class) or sigma K_gen (odd class)")
else:
    print("NO VERDICT")
