#!/usr/bin/env python3
"""S2 / node S2.1 (+ S2.4 generativity): the pair tower generated from data at finite stages, table rule.
Exact arithmetic only (Fractions).

Run:  cd pt/S2 && python3 -I -B s2_5_tower.py ../base/verification/lean-mathlib/OIBridge

Construction P(O) (choices C1-C11 are listed in RESULT.md section 1, S2.1):
  stage n: ball points Q_n (rational, nested), effects F_n (sharp effects along unit points of Q_n, their halves, the
  unit), preparations {w (x (x) y) : x, y in Q_n, w a word in O}, labels {(w', e, f) : w' a word in O, e, f in F_n},
  table p((w', e, f), w (x (x) y)) = prodEffVal e f (w'(w(prodState x y))), stage maps = inclusions.
  With O = {cnot} the words reduce to {id, cnot} (cnotFun_cnotFun).

DECISION RULES (fixed before the first run):
 T0 Transcription: pc/pt parsed; cnot involution; cnot pxz = phiW.  Failure: ABORT.
 T1 Validity: every table value of stages n = 1, 2, 3 lies in [0, 1]; the unit label is 1 on every preparation.
 T2 SC-infinity: the preparations and labels of stage n are preparations and labels of stage n + 1 (inclusion maps);
    every stage table is the restriction of the one function `value`, so the stage maps carry the table (written).
 T3 Table rule: every label value equals ipW(M_l, table(prep)) with M_l = w'^T (ehom e (x) ehom f) (exact, stage 2),
    and the preparation-vector matrix of stage 2 has rank 16 (read-out through 16 product labels).
 T4 Generativity: for every preparation s of a stage, cnot(s) is a preparation of the same stage, and
    prepVec(cnot s)(w', e, f) = prepVec(s)(w' o cnot, e, f) (Heisenberg reading of the gate on tests).
 T5 Affine respect of the gate datum tau(s) = prepVec(cnot s) on stage 2: every affine relation among the
    preparation vectors annihilates the image vectors, tested exactly as rank([prepVec | 1 | image]) =
    rank([prepVec | 1]).
 T6 hgate/hinv of the read-out set: the set of read-out tables of stage 3 is closed under cnot (and cnot^-1 = cnot).
 T7 Countercontrol: the tower generated by g_D = actT reflY o cnot (words of length <= 2) must FAIL validity
    (some value < 0).
 T8 Generation is load-bearing (S2.3): N_h = [[cnot, Delta], [0, 1]], Delta = e_03 - e_33 with cnot Delta = -Delta,
    is an involution with the certified product action; adding the ungenerated preparations (E00, +-1/4) keeps every
    value in [0, 1] and breaks LT: (E00, 1/4) and (E00, 0) have equal product tables and different N-test tables.
 VERDICT lines print only if T0-T8 pass and the countercontrol fails as required.
"""
import sys, os, re
from fractions import Fraction as Fr

OK = True
NPASS = 0
def check(name, cond, detail=""):
    global OK, NPASS
    if cond:
        NPASS += 1; print(f"PASS {name}" + (f"  [{detail}]" if detail else ""))
    else:
        OK = False; print(f"FAIL {name}" + (f"  [{detail}]" if detail else ""))
def control(name, should_fail_cond, detail=""):
    global OK, NPASS
    if not should_fail_cond:
        NPASS += 1; print(f"PASS countercontrol {name} fails as required" + (f"  [{detail}]" if detail else ""))
    else:
        OK = False; print(f"FAIL countercontrol {name} did not fail" + (f"  [{detail}]" if detail else ""))

IDX = [(m, n) for m in range(4) for n in range(4)]
def k(m, n): return 4 * m + n
def mmul(A, B):
    return [[sum(A[i][r] * B[r][j] for r in range(len(B)) if A[i][r] != 0) for j in range(len(B[0]))] for i in range(len(A))]
def mvec(A, v):
    return [sum(A[i][r] * v[r] for r in range(len(v)) if A[i][r] != 0) for i in range(len(A))]
def eye(n): return [[1 if i == j else 0 for j in range(n)] for i in range(n)]
def transpose(A): return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]
def hom(x): return (1, x[0], x[1], x[2])
def prodState(x, y):
    hx, hy = hom(x), hom(y); return [hx[m] * hy[n] for (m, n) in IDX]
def pairVal(a, b, w): return sum(a[m] * w[k(m, n)] * b[n] for (m, n) in IDX)
def outer(a, b): return [a[m] * b[n] for (m, n) in IDX]
def ipW(E, X): return sum(E[i] * X[i] for i in range(16))
def frank(rows):
    M = [[Fr(x) for x in r] for r in rows]
    if not M: return 0
    rk = 0; ncol = len(M[0])
    for c in range(ncol):
        piv = next((i for i in range(rk, len(M)) if M[i][c] != 0), None)
        if piv is None: continue
        M[rk], M[piv] = M[piv], M[rk]
        pr = M[rk]
        for i in range(len(M)):
            if i != rk and M[i][c] != 0:
                f = M[i][c] / pr[c]
                M[i] = [M[i][j] - f * pr[j] for j in range(ncol)]
        rk += 1
    return rk
def nullspace(rows):
    """Exact left-null basis: vectors c with sum_i c_i rows[i] = 0."""
    m = len(rows); n = len(rows[0])
    A = [[Fr(rows[i][j]) for i in range(m)] for j in range(n)]   # n x m, solve A c = 0
    piv_cols = []; r = 0
    for c in range(m):
        piv = next((i for i in range(r, n) if A[i][c] != 0), None)
        if piv is None: continue
        A[r], A[piv] = A[piv], A[r]
        pv = A[r][c]
        A[r] = [x / pv for x in A[r]]
        for i in range(n):
            if i != r and A[i][c] != 0:
                f = A[i][c]
                A[i] = [A[i][j] - f * A[r][j] for j in range(m)]
        piv_cols.append(c); r += 1
    free = [c for c in range(m) if c not in piv_cols]
    basis = []
    for fcol in free:
        vec = [Fr(0)] * m; vec[fcol] = Fr(1)
        for i, pc in enumerate(piv_cols):
            vec[pc] = -A[i][fcol]
        basis.append(vec)
    return basis

# ---------------------------------------------------------------- T0
oib = sys.argv[1] if len(sys.argv) > 1 else "../base/verification/lean-mathlib/OIBridge"
src = open(os.path.join(oib, "CompositeDimension.lean"), encoding="utf-8").read()
PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]
def SGN(m, n): return -1 if ((m == 1 and n == 3) or (m == 2 and n == 2)) else 1
def parse_table(name):
    body = re.search(r"def " + name + r" : Fin 4 → Fin 4 → Fin 4\n(.*?)\n\n", src, re.S).group(1)
    T = [[None] * 4 for _ in range(4)]
    for a, b, c in re.findall(r"\|\s*(\d),\s*(\d)\s*=>\s*(\d)", body):
        T[int(a)][int(b)] = int(c)
    return T
check("T0.pc/pt transcription", parse_table("pc") == PC and parse_table("pt") == PT)
CNOT = [[0] * 16 for _ in range(16)]
for (m, n) in IDX:
    CNOT[k(m, n)][k(PC[m][n], PT[m][n])] = SGN(m, n)
check("T0.cnot involution", mmul(CNOT, CNOT) == eye(16))
xplus, z3 = (1, 0, 0), (0, 0, 1)
phiW = [(1 if m != 2 else -1) if m == n else 0 for (m, n) in IDX]
check("T0.cnot pxz = phiW", mvec(CNOT, prodState(xplus, z3)) == phiW)
if not OK:
    print("ABORT"); sys.exit(1)

# ---------------------------------------------------------------- the stages
AXIS = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]
PYTH = [(Fr(3, 5), Fr(4, 5), 0), (0, Fr(3, 5), Fr(4, 5)), (Fr(4, 5), 0, Fr(3, 5)),
        (Fr(1, 3), Fr(2, 3), Fr(2, 3)), (Fr(-2, 3), Fr(1, 3), Fr(2, 3)), (Fr(2, 3), Fr(-2, 3), Fr(1, 3))]
INTER = [(0, 0, 0), (Fr(1, 2), 0, 0), (0, Fr(-1, 3), Fr(1, 4))]
Q = {1: AXIS[:4] + [(0, 0, 0)], 2: AXIS + PYTH[:3] + INTER[:2], 3: AXIS + PYTH + INTER}
def sharpv(b): return (Fr(1, 2), Fr(b[0], 2), Fr(b[1], 2), Fr(b[2], 2))
def is_unit(b): return sum(Fr(t) ** 2 for t in b) == 1
def effects(n):
    out = [(1, 0, 0, 0)]
    for b in Q[n]:
        if is_unit(b):
            out.append(sharpv(b)); out.append(tuple(t / 2 for t in sharpv(b)))
    return out
WORDS = {"id": eye(16), "cnot": CNOT}
def preps(n):
    return [(w, x, y) for x in Q[n] for y in Q[n] for w in ("id", "cnot")]
def table(prep):
    w, x, y = prep
    return mvec(WORDS[w], prodState(x, y))
def labels(n):
    return [(w, e, f) for w in ("id", "cnot") for e in effects(n) for f in effects(n)]
TABC = {}
def tabs(prep):
    if prep not in TABC:
        tp = table(prep)
        TABC[prep] = {"id": tp, "cnot": mvec(CNOT, tp)}
    return TABC[prep]
def value(label, prep):
    w, e, f = label
    return pairVal(e, f, tabs(prep)[w])

# ---------------------------------------------------------------- T1 validity, T2 SC
valid = True; unit_ok = True
for n in (1, 2, 3):
    P, L = preps(n), labels(n)
    for p in P:
        tw = tabs(p)
        if pairVal((1, 0, 0, 0), (1, 0, 0, 0), tw["id"]) != 1: unit_ok = False
        for (w, e, f) in L:
            v = pairVal(e, f, tw[w])
            if not (0 <= v <= 1): valid = False
check("T1.all values of stages 1-3 in [0,1]", valid)
check("T1.unit label = 1 on every preparation", unit_ok)
sc = True
for n in (1, 2):
    P_next, L_next = set(preps(n + 1)), set(labels(n + 1))
    for p in preps(n):
        if p not in P_next: sc = False
    for l in labels(n):
        if l not in L_next: sc = False
check("T2.stage preparations and labels are included in the next stage (inclusion maps)", sc)

# ---------------------------------------------------------------- T3 table rule, rank
def ehom_outer(e, f): return outer(e, f)
rule = True
for p in preps(2):
    tp = table(p)
    for (w, e, f) in labels(2):
        Ml = mvec(transpose(WORDS[w]), ehom_outer(e, f))
        if ipW(Ml, tp) != pairVal(e, f, mvec(WORDS[w], tp)): rule = False
check("T3.every label value = ipW(w'^T(ehom e (x) ehom f), table) (stage 2)", rule)
P2r, L2r = preps(2), labels(2)
PV2r = [[value(l, p) for l in L2r] for p in P2r]
r2 = frank(PV2r)
check("T3.stage-2 preparation-vector matrix has rank 16", r2 == 16, f"rank {r2}")

# ---------------------------------------------------------------- T4 generativity
gen = True
for n in (1, 2):
    Pset = set(preps(n))
    for p in preps(n):
        w, x, y = p
        q = ("cnot" if w == "id" else "id", x, y)
        if q not in Pset: gen = False
        for (w2, e, f) in labels(n):
            w2c = "cnot" if w2 == "id" else "id"           # w' o cnot reduces to the other word
            if value((w2, e, f), q) != value((w2c, e, f), p): gen = False
check("T4.cnot maps preparations to preparations; prepVec(cnot s) = label-shifted prepVec(s)", gen)

# ---------------------------------------------------------------- T5 affine respect (stage 2)
P2, L2 = preps(2), labels(2)
PV2 = [[value(l, p) for l in L2] + [1] for p in P2]
IMG2 = [[value(l, ("cnot" if p[0] == "id" else "id", p[1], p[2])) for l in L2] + [1] for p in P2]
rA = frank(PV2)
rAB = frank([PV2[i] + IMG2[i] for i in range(len(P2))])
check("T5.every affine relation among stage-2 preparation vectors holds among the cnot images", rA == rAB,
      f"rank [prepVec|1] = {rA}, with images = {rAB}")

# ---------------------------------------------------------------- T6 hgate/hinv of the read-out set
RO = {tuple(table(p)) for p in preps(3)}
check("T6.read-out tables of stage 3 closed under cnot", all(tuple(mvec(CNOT, list(t))) in RO for t in RO))

# ---------------------------------------------------------------- T7 countercontrol g_D
REFLY_T = [[0] * 16 for _ in range(16)]
H = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]
for m in range(4):
    for n in range(4):
        for l in range(4):
            if H[n][l]: REFLY_T[k(m, n)][k(m, l)] += H[n][l]
GD = mmul(REFLY_T, CNOT)
neg_found = False
for x in Q[2]:
    for y in Q[2]:
        s0 = prodState(x, y)
        for word in (GD, mmul(GD, GD)):
            img = mvec(word, s0)
            for e in effects(2):
                for f in effects(2):
                    if pairVal(e, f, img) < 0: neg_found = True
control("T7.g_D-generated tower is valid", not neg_found)

# ---------------------------------------------------------------- T8 generation is load-bearing
Delta = [0] * 16; Delta[k(0, 3)] = 1; Delta[k(3, 3)] = -1
check("T8.cnot Delta = -Delta", mvec(CNOT, Delta) == [-d for d in Delta])
def Nh(s): u, h = s[:16], s[16]; return [a + h * d for a, d in zip(mvec(CNOT, u), Delta)] + [h]
E00 = prodState((0, 0, 0), (0, 0, 0))
t = Fr(1, 4)
test_states = [prodState(x, y) + [0] for x in Q[2] for y in Q[2]] + [E00 + [t], E00 + [-t]]
inv_ok = all(Nh(Nh(s)) == s for s in test_states)
check("T8.N_h o N_h = id on the test states", inv_ok)
check("T8.product action of N_h is cnot", all(Nh(prodState(x, y) + [0])[:16] == mvec(CNOT, prodState(x, y))
                                             for x in Q[2] for y in Q[2]))
vals8 = [pairVal(e, f, (s if j == 0 else Nh(s))[:16]) for s in test_states for j in (0, 1)
         for e in effects(2) for f in effects(2)]
check("T8.all values in [0,1] with the ungenerated preparations (E00, +-1/4)", all(0 <= v <= 1 for v in vals8))
a1, a0 = E00 + [t], E00 + [0]
eq_tab = a1[:16] == a0[:16]
dif = [(e, f) for e in effects(2) for f in effects(2) if pairVal(e, f, Nh(a1)[:16]) != pairVal(e, f, Nh(a0)[:16])]
check("T8.(E00, 1/4) and (E00, 0): equal product tables, different N-test values (LT fails)", eq_tab and len(dif) > 0,
      f"{len(dif)} separating product effects")

print(f"SUMMARY checks passed={NPASS} all_ok={OK}")
if OK:
    print("VERDICT TOWER: the pair tower generated from products by cnot, with tests generated by cnot, is a valid "
          "system of finite stages with SC-infinity; under the table rule every label reads the W 3 table (LT built in "
          "by the rule) and the read-out rank is 16; the gate is generative (OpDatum with AffineRespect, its own "
          "inverse) and the read-out set is cnot-closed (hgate and hinv for the generated cone)")
    print("VERDICT GENERATION: an involutive gate with the certified product action does not give LT once an "
          "ungenerated hidden-parameter preparation is admitted: the 'from data' generation is load-bearing")
else:
    print("NO VERDICT")
