# Exact checks (rational arithmetic) for EFF-1 restart, base bd5de8f5.
# ehom(e) = (c, a): e(x) = c + a.x on eball d.  Sharp effect s_b = (1/2, b/2), |b| = 1.  Unit u = (1, 0).
# pairVal(A, B, w) = sum_{mu,nu} A_mu w_{mu nu} B_nu.
from fractions import Fraction as F
import itertools, random
random.seed(1)

def pair(A, B, w): return sum(A[m]*w[m][n]*B[n] for m in range(len(A)) for n in range(len(B)))
def tens(X, Y): return [[x*y for y in Y] for x in X]
def sharp(b): return [F(1,2)] + [F(bi)/2 for bi in b]
def is_effect(c, a):
    # effect on eball d iff |a| <= c and |a| <= 1 - c  (exact via squares)
    s2 = sum(x*x for x in a); return 0 <= c <= 1 and s2 <= c*c and s2 <= (1-c)*(1-c)

# 1. Conic decomposition with RATIONAL directions: effects whose |a| is rational (Pythagorean a).
pyth = [(F(3,5),F(4,5),F(0)), (F(2,3),F(1,3),F(2,3)), (F(0),F(0),F(1))]
ok = 0
for (u1,u2,u3) in pyth:
    for s in [F(0), F(1,10), F(1,4), F(3,8)]:
        for c in [F(1,2), F(3,5), F(2,5), F(3,4)]:
            a = [s*u1, s*u2, s*u3]
            if not is_effect(c, a): continue
            # e = (c - s) * unit + 2s * sharp(uhat): both coefficients >= 0
            alpha, beta = c - s, 2*s
            assert alpha >= 0 and beta >= 0
            rec = [alpha*1 + beta*F(1,2)] + [beta*x/2 for x in (u1,u2,u3)]
            assert rec == [c] + a
            # and unit = sharp(b) + sharp(-b)
            assert [x+y for x,y in zip(sharp([u1,u2,u3]), sharp([-u1,-u2,-u3]))] == [1,0,0,0]
            ok += 1
print("decomposition cases (exact):", ok)

# 2. Countercontrol: a family missing directions (bit family: z-sharp effects, unit, zero, mixtures) has a
#    strictly larger dual cone than the full effect set at d = 3.
X = [F(1), F(2), F(0), F(0)]          # outside the Lorentz cone
w = tens(X, X)
bit = [sharp([0,0,1]), sharp([0,0,-1]), [F(1),0,0,0], [F(0)]*4]
assert all(pair(A,B,w) >= 0 for A in bit for B in bit)
sx_m, sx_p = sharp([-1,0,0]), sharp([1,0,0])
v = pair(sx_m, sx_p, w)
print("bit-family dual-cone member, full-effect product value:", v)
assert v < 0

# 3. Control: the non-mix-closed family {unit, 0} + sharp (C2a) has the SAME dual cone as the full set on
#    product test vectors: check on random rational joint vectors in the cone generated by tens(Lor, Lor).
def lor_rand(d):
    while True:
        a = [F(random.randint(-6,6),7) for _ in range(d)]
        s2 = sum(x*x for x in a)
        c = F(random.randint(0,14),7)
        if s2 <= c*c: return [c]+a
mism = 0
for d in [3, 5]:
    for _ in range(200):
        w = tens(lor_rand(d), lor_rand(d))
        # every Lorentz-cone pair pairs nonnegatively (full-effect cone member)
        for _ in range(5):
            A, B = lor_rand(d), lor_rand(d)
            if pair(A,B,w) < 0: mism += 1
print("product-in-cone countercheck mismatches:", mism)
