"""EQ4-P probe p12 -- the sector problem SP has a non-orthant solution: the cone K_A, exact.  Research only.

Usage:  python3 -I -B p12_sector_selfdual.py <base>/verification/lean-mathlib/OIBridge
Imports only the own library eq4_lib.py.

Sector problem SP (NOTES N3.7; reduction ingredients certified in p11): in GHZ-basis eigenvalue coordinates x in R^8
(x_j = tr(X P_j)), is the orthant the only closed convex cone K with G-invariance, K = K* and S <= K <= S*,
S = cone{e_j + e_k}?  Candidate (found by the exploration x8):
    K_A = cone( e_j + e_k (j != k),   m_j = 1 - 2 e_j,   n_jp = 1 - 2 e_j + 2 e_p (p != j) ),
invariant under all permutations of the 8 positions.  As operators: m_0 = 2 W3, n_01 = I - 2 P_0 + 2 P_1 = 2 kappa'
(kappa' = 1/2 + P_1 - P_0, the G-image of kappa), n_02 = I - 2 P_0 + 2 P_2.

Written proof that K_A = K_A* (NOTES N3.7).  (a) Generators pairwise >= 0: <1-2e_j+2e_p, 1-2e_j'+2e_p'> = 8 + 4(d_jj' -
d_jp' - d_pj' + d_pp') >= 0, the other pairs are positive by inspection.  (b) x in K_A*: if x >= 0 the m-constraints
give 2 max x <= sum x, i.e. x in S (pair-sum cone).  Otherwise x has exactly one negative entry, scaled to x_q = -1;
the constraint from n_jq gives z_j <= sum_{k != j} z_k + 2 for z = x - m_q (supported off q, z >= 0); if no entry
of z dominates, x = m_q + z with z in S; else the dominant entry m has excess d = z_m - sum_{k != m} z_k in (0, 2] and
x = (1 - d/2) m_q + (d/2) n_qm + (z - d e_m) with z - d e_m in S.  So K_A* <= K_A.

DECISION RULE (fixed before the first run; rules, not expected numbers).  VERDICT `P12-SECTOR-SELFDUAL-EXACT` iff all:
  K  transcription control.
  A1 the 92 generators form a set invariant under all 8! position permutations (checked on the generators S_8 is
     generated by) and are pairwise >= 0 (exact): K_A <= K_A*.
  A2 exact double description of K_A* (constraints = generators) in two different constraint orders returns the same
     ray set; every returned ray lies in K_A* and has a tight set of rank 7; the ray set equals the generator set
     (so K_A* = cone(generators) = K_A, given A1).  Control: the same code on the orthant returns the 8 unit vectors;
     countercontrol: on S it returns rays that are not pairwise >= 0 (S* is not self-dual).
  A3 cross-check of the written proof: on 300 random exact points of K_A* (half nonnegative, half with a negative
     entry, rejection-sampled against all 92 constraints), the explicit decomposition (written case analysis, then a
     greedy pair-sum decomposition) returns nonnegative coefficients reproducing the point exactly.
  A4 structure: the nonnegative rays of K_A* are exactly the 28 pair sums (K_A n R^8_+ = S); e_0 is not in K_A
     (<e_0, m_0> < 0 with m_0 in K_A = K_A*); m_0 and n_01 are the eigenvalue vectors of 2 W3 and 2 kappa' (exact
     operator tie-in with the P_j of p11).
"""
import random
import sys
from fractions import Fraction as Fr
from itertools import combinations
from math import gcd

sys.path.insert(0, __file__.rsplit("/", 1)[0] if "/" in __file__ else ".")
import eq4_lib as L  # noqa: E402

BASE = sys.argv[1]
rep = L.Report("p12_sector_selfdual")
rng = random.Random(20261009 + 12)
rep.check("K0 transcription control", L.transcription_control(BASE)[0])


def prim(v):
    g = 0
    for x in v:
        g = gcd(g, abs(x))
    return tuple(x // g for x in v) if g else tuple(v)


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def rank(rows):
    if not rows:
        return 0
    M = [[Fr(x) for x in r] for r in rows]
    rk = 0
    ncol = len(M[0])
    for c in range(ncol):
        piv = next((i for i in range(rk, len(M)) if M[i][c] != 0), None)
        if piv is None:
            continue
        M[rk], M[piv] = M[piv], M[rk]
        for i in range(len(M)):
            if i != rk and M[i][c] != 0:
                f = M[i][c] / M[rk][c]
                M[i] = [M[i][j] - f * M[rk][j] for j in range(ncol)]
        rk += 1
    return rk


def inverse_cols(B):
    n = len(B)
    M = [[Fr(x) for x in B[i]] + [Fr(int(i == j)) for j in range(n)] for i in range(n)]
    for c in range(n):
        piv = next(i for i in range(c, n) if M[i][c] != 0)
        M[c], M[piv] = M[piv], M[c]
        pv = M[c][c]
        M[c] = [x / pv for x in M[c]]
        for i in range(n):
            if i != c and M[i][c] != 0:
                f = M[i][c]
                M[i] = [M[i][j] - f * M[c][j] for j in range(2 * n)]
    inv = [row[n:] for row in M]
    cols = []
    for j in range(n):
        col = [inv[i][j] for i in range(n)]
        den = 1
        for x in col:
            den = den * x.denominator // gcd(den, x.denominator)
        cols.append(prim(tuple(int(x * den) for x in col)))
    return cols


def extreme_rays(A, n=8):
    """exact double description of {x : <a, x> >= 0 for a in A} (pointed, full-dimensional dual assumed)."""
    rows = [tuple(a) for a in A]
    basis = []
    for i, a in enumerate(rows):
        if rank([rows[k] for k in basis] + [a]) > len(basis):
            basis.append(i)
        if len(basis) == n:
            break
    assert len(basis) == n
    rays = list(inverse_cols([rows[k] for k in basis]))
    Z = []
    for j in range(n):
        mask = 0
        for k in range(n):
            if k != j:
                mask |= 1 << basis[k]
        Z.append(mask)
    bset = set(basis)
    for i, a in enumerate(rows):
        if i in bset:
            continue
        vals = [dot(a, r) for r in rays]
        pos = [k for k in range(len(rays)) if vals[k] > 0]
        neg = [k for k in range(len(rays)) if vals[k] < 0]
        zer = [k for k in range(len(rays)) if vals[k] == 0]
        nr = [rays[k] for k in pos] + [rays[k] for k in zer]
        nz = [Z[k] for k in pos] + [Z[k] | (1 << i) for k in zer]
        for p in pos:
            for q in neg:
                common = Z[p] & Z[q]
                if common.bit_count() < n - 2:
                    continue
                if all(not (r != p and r != q and (Z[r] & common) == common) for r in range(len(rays))):
                    nr.append(prim(tuple(vals[p] * rays[q][t] - vals[q] * rays[p][t] for t in range(n))))
                    nz.append(common | (1 << i))
        rays, Z = nr, nz
    return sorted(set(rays))


def e(j):
    return tuple(int(k == j) for k in range(8))


ONE8 = (1,) * 8
PAIRS = sorted(set(tuple(a + b for a, b in zip(e(j), e(k))) for j, k in combinations(range(8), 2)))
MS = [tuple(1 - 2 * int(k == j) for k in range(8)) for j in range(8)]
NS = [tuple(1 - 2 * int(k == j) + 2 * int(k == p) for k in range(8)) for j in range(8) for p in range(8) if p != j]
GEN = sorted(set(PAIRS + MS + NS))

# ------------------------------------------------------------------------------------------------ A1
def permute(v, s):
    w = [0] * 8
    for i in range(8):
        w[s[i]] = v[i]
    return tuple(w)


transp = [tuple(list(range(i)) + [i + 1, i] + list(range(i + 2, 8))) for i in range(7)]
gset = set(GEN)
inv_ok = all(permute(v, s) in gset for v in GEN for s in transp)
sp_ok = all(dot(GEN[i], GEN[j]) >= 0 for i in range(len(GEN)) for j in range(i, len(GEN)))
rep.check("A1 %d generators (28 pair sums, 8 m_j, 56 n_jp); invariant under the adjacent transpositions (hence S_8); "
          "pairwise >= 0: %s" % (len(GEN), sp_ok), len(GEN) == 92 and inv_ok and sp_ok)

# ------------------------------------------------------------------------------------------------ A2
ext1 = extreme_rays(GEN)
order2 = list(GEN)
rng.shuffle(order2)
ext2 = extreme_rays(order2)
in_dual = all(all(dot(z, w) >= 0 for w in GEN) for z in ext1)
extreme = all(rank([w for w in GEN if dot(z, w) == 0]) == 7 for z in ext1)
ctrl_orth = extreme_rays([e(j) for j in range(8)]) == sorted(e(j) for j in range(8))
extS = extreme_rays(PAIRS)
cc_S = not all(dot(a, b) >= 0 for a in extS for b in extS)
rep.check("A2 exact double description: %d rays (two orders agree: %s); all in K_A* %s, all extreme (tight rank 7) %s; "
          "ray set = generator set %s; control orthant %s; countercontrol S* not self-positive %s"
          % (len(ext1), ext1 == ext2, in_dual, extreme, set(ext1) == gset, ctrl_orth, cc_S),
          ext1 == ext2 and in_dual and extreme and set(ext1) == gset and ctrl_orth and cc_S)


# ------------------------------------------------------------------------------------------------ A3
def in_KAstar(x):
    return all(dot(x, w) >= 0 for w in GEN)


def pair_decomp(x):
    """x >= 0 with 2 max <= sum: greedy pair-sum decomposition; returns list of (coef, (i, j)) or None."""
    x = list(x)
    out = []
    for _ in range(200):
        if all(v == 0 for v in x):
            return out
        order = sorted(range(len(x)), key=lambda k: (-x[k], k))
        i, j = order[0], order[1]
        third = x[order[2]] if len(x) > 2 else Fr(0)
        s = sum(x)
        d = min(x[j], (s - 2 * third) / 2)
        if d <= 0:
            return None
        x[i] -= d
        x[j] -= d
        out.append((d, (i, j)))
    return None


def decompose(x):
    """returns a list of (coef >= 0, generator) summing to x, or None."""
    x = [Fr(v) for v in x]
    neg = [k for k in range(8) if x[k] < 0]
    if not neg:
        pd = pair_decomp(x)
        return None if pd is None else [(c, tuple(int(k in ij) for k in range(8))) for c, ij in pd]
    q = neg[0]
    a = -x[q]
    y = [v / a for v in x]
    z = [y[k] - (1 - 2 * int(k == q)) for k in range(8)]
    zz = [z[k] for k in range(8) if k != q]
    idxs = [k for k in range(8) if k != q]
    Zs = sum(zz)
    mpos = max(range(7), key=lambda t: (zz[t], -t))
    d = zz[mpos] - (Zs - zz[mpos])
    terms = []
    if d <= 0:
        terms.append((a, MS[q]))
        rest = zz
    else:
        if d > 2:
            return None
        m = idxs[mpos]
        terms.append((a * (1 - d / 2), MS[q]))
        terms.append((a * d / 2, tuple(1 - 2 * int(k == q) + 2 * int(k == m) for k in range(8))))
        rest = [zz[t] - (d if t == mpos else 0) for t in range(7)]
    pd = pair_decomp(rest)
    if pd is None:
        return None
    for c, (i, j) in pd:
        terms.append((a * c, tuple(int(k == idxs[i] or k == idxs[j]) for k in range(8))))
    return terms


def rand_point(negative):
    while True:
        if negative:
            q = rng.randrange(8)
            x = [Fr(1) + Fr(rng.randint(0, 12), rng.choice((1, 2, 3, 4))) for _ in range(8)]
            x[q] = Fr(-1)
            if rng.random() < 0.5:                    # push one entry towards the boundary z_m ~ sum + 2
                m = rng.choice([k for k in range(8) if k != q])
                others = sum(x[k] - 1 for k in range(8) if k not in (q, m))
                x[m] = 1 + others + Fr(rng.randint(0, 8), 4)
        else:
            x = [Fr(rng.randint(0, 9), rng.choice((1, 2, 3))) for _ in range(8)]
        den = 1
        for v in x:
            den = den * v.denominator // gcd(den, v.denominator)
        xi = tuple(int(v * den) for v in x)
        if any(xi) and in_KAstar(xi):
            return xi


ok_a3 = True
nneg = 0
for t in range(300):
    x = rand_point(t % 2 == 1)
    nneg += int(min(x) < 0)
    terms = decompose(x)
    if terms is None or any(c < 0 for c, _ in terms) or any(g not in gset for _, g in terms):
        ok_a3 = False
        break
    recon = [sum((c * g[k] for c, g in terms), Fr(0)) for k in range(8)]
    ok_a3 &= recon == [Fr(v) for v in x]
rep.check("A3 decomposition cross-check on 300 random exact points of K_A* (%d with a negative entry): nonnegative "
          "coefficients on generators reproduce every point exactly" % nneg, ok_a3 and nneg >= 100)

# ------------------------------------------------------------------------------------------------ A4
X3 = (0, 1, 2)


def idx(x, y, z):
    return 4 * x + 2 * y + z


PJ = []
for b in range(4):
    b1, b2 = b >> 1, b & 1
    for t in range(2):
        v = [0] * 8
        v[idx(0, b1, b2)] = 1
        v[idx(1, 1 - b1, 1 - b2)] = 1 if t == 0 else -1
        PJ.append(L.ket_op(v, X3).scale(Fr(1, 2)))
nonneg_rays = sorted(z for z in ext1 if min(z) >= 0)
W3op = L.w3(X3)
kap_p = L.identity(X3).scale(Fr(1, 2)) + PJ[1] - PJ[0]
tie = ([L.pair(W3op, P) * 2 for P in PJ] == [L.G(v) for v in MS[0]]
       and [L.pair(kap_p, P) * 2 for P in PJ] == [L.G(v) for v in NS[0]])
kap = L.identity(X3).scale(Fr(1, 2)) + L.Op(X3, {(0, 7): L.ONE, (7, 0): L.ONE})
kap_is = kap == L.identity(X3).scale(Fr(1, 2)) + PJ[0] - PJ[1]
rep.check("A4 nonnegative rays of K_A* = the 28 pair sums %s (K_A n R^8_+ = S); <e_0, m_0> = %d < 0 (e_0 = GHZ+ not in K_A); "
          "m_0 = eigenvalues of 2 W3 and n_01 = eigenvalues of 2 kappa', kappa' = 1/2 + P_1 - P_0 (kappa = 1/2 + P_0 - P_1 "
          "%s): %s" % (nonneg_rays == PAIRS, dot(e(0), MS[0]), kap_is, tie),
          nonneg_rays == PAIRS and dot(e(0), MS[0]) < 0 and tie and kap_is)

rep.verdict("P12-SECTOR-SELFDUAL-EXACT")
