"""EQ4-P exploration x12 -- the c = 1 GHZ-diagonal sector problem.  EXPLORATION (exact arithmetic; a search; leads
only).  Research only.

For c = 1, K3 = K3* (Euclidean), B_tw = cone{PT_j(sigma_ij) (x) rho_k} <= K3, and K3 is LU-invariant and S3-symmetric
(twin-link teleportation and filter links, as for c = 0).  The twirl over the GHZ stabilizer group commutes with every
PT_j (the group consists of real local Paulis), so twirl(K3) = K3 n GD is a G-invariant Euclidean self-dual cone that
contains S_tw = twirl(B_tw) and hence lies in S_tw*.  Here S' <= S_tw is generated by the G-orbits of PT_1 and PT_2
applied to the twirls of two 12|3-separable operators: |000><000| (twirl (P_0 + P_1)/2) and
Phi+ (x) |+><+| + Phi- (x) |-><-| (= P_0 + P_2).  PT_j acts on GD linearly (computed from the operator library on
the GHZ projectors P_m).  Questions: (i) is S' self-positive (it must be: B_tw is); (ii) depth-first extreme-ray
completion (as x4) from S', and from S' plus seeds; FOUND = a G-invariant self-dual cone containing S'.  A FOUND cone
is a model of the sector conditions only if it also contains all of S_tw (checked separately).
Output: progress lines.  No VERDICT line (exploration).
"""
import sys
from fractions import Fraction as Fr
from itertools import permutations, product
from math import gcd

sys.path.insert(0, __file__.rsplit("/", 1)[0] if "/" in __file__ else ".")
import eq4_lib as L  # noqa: E402

X3 = (0, 1, 2)


def idx(x, y, z):
    return 4 * x + 2 * y + z


PJ = []
for b in range(4):
    b1, b2 = b >> 1, b & 1
    for t in range(2):
        v = [0] * 8
        v[idx(0, b1, b2)] = 1
        v[idx(1, 1 - b1, 1 - b2)] = 1 if t == 0 else -1
        PJ.append(L.ket_op(v, X3).scale(Fr(1, 2)))


def coords(Xop):
    return [L.pair(Xop, P) for P in PJ]


def from_coords(lam):
    out = L.Op(X3, {})
    for m in range(8):
        out = out + PJ[m].scale(lam[m])
    return out


PTM = {}
ok_gd = True
for j in X3:
    cols = []
    for m in range(8):
        Y = L.ptranspose(PJ[m], [j])
        c = coords(Y)
        ok_gd &= from_coords(c) == Y            # PT_j maps GD into GD
        cols.append(c)
    PTM[j] = cols                                # PTM[j][m] = coordinates of PT_j(P_m)
print("PT_j maps GD into GD:", ok_gd)
for j in X3:
    print("PT_%d on P_0:" % (j + 1), [str(x) for x in PTM[j][0]])


def pt_vec(j, lam):
    out = [Fr(0)] * 8
    for m in range(8):
        for n in range(8):
            out[n] += Fr(lam[m]) * PTM[j][m][n].re
    return out


def prim(v):
    den = 1
    for x in v:
        den = den * Fr(x).denominator // gcd(den, Fr(x).denominator)
    w = [int(Fr(x) * den) for x in v]
    g = 0
    for x in w:
        g = gcd(g, abs(x))
    return tuple(x // g for x in w) if g else tuple(w)


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


GR = []
for perm in permutations(range(4)):
    for eps in product((0, 1), repeat=4):
        if sum(eps) % 2 == 0:
            GR.append(tuple(2 * perm[b] + (t ^ eps[b]) for b in range(4) for t in range(2)))


def act(g, v):
    w = [0] * 8
    for i in range(8):
        w[g[i]] = v[i]
    return tuple(w)


def orbit(v):
    return sorted(set(act(g, v) for g in GR))


def canon(v):
    return min(orbit(v))


base = [(1, 1, 0, 0, 0, 0, 0, 0), (1, 0, 1, 0, 0, 0, 0, 0)]
seedgens = set()
for g0 in base:
    for j in (0, 1):
        seedgens.add(prim(pt_vec(j, g0)))
print("PT images of the two twirls (tokens 1, 2):", sorted(seedgens))
SP_ = sorted(set(w for v in seedgens for w in orbit(v)))
selfpos = all(dot(a, b) >= 0 for a in SP_ for b in SP_)
print("S' has %d generators; self-positive: %s" % (len(SP_), selfpos))
# W3 control: W3 = 1/2 - P_0 is in B_tw (p1 T5), so its twirl (itself) should be in cone(S_tw); report pairing data
w3 = (-1, 1, 1, 1, 1, 1, 1, 1)
print("min <W3-type, S' generator> =", min(dot(w3, a) for a in SP_))

def rank(rows):
    M = [[Fr(x) for x in r] for r in rows]
    rk = 0
    ncol = len(M[0]) if M else 0
    for c in range(ncol):
        piv = next((i for i in range(rk, len(M)) if M[i][c] != 0), None)
        if piv is None:
            continue
        M[rk], M[piv] = M[piv], M[rk]
        for i in range(len(M)):
            if i != rk and M[i][c] != 0:
                f = M[i][c] / M[rk][c]
                M[i] = [M[i][j] - f * M[rk][j] for j in range(ncol)]
        rk += 1
    return rk


def inverse_cols(B):
    n = len(B)
    M = [[Fr(x) for x in B[i]] + [Fr(int(i == j)) for j in range(n)] for i in range(n)]
    for c in range(n):
        piv = next(i for i in range(c, n) if M[i][c] != 0)
        M[c], M[piv] = M[piv], M[c]
        pv = M[c][c]
        M[c] = [x / pv for x in M[c]]
        for i in range(n):
            if i != c and M[i][c] != 0:
                f = M[i][c]
                M[i] = [M[i][j] - f * M[c][j] for j in range(2 * n)]
    inv = [row[n:] for row in M]
    cols = []
    for j in range(n):
        col = [inv[i][j] for i in range(n)]
        den = 1
        for x in col:
            den = den * x.denominator // gcd(den, x.denominator)
        cols.append(prim(tuple(int(x * den) for x in col)))
    return cols


def extreme_rays(A, n=8):
    rows = [tuple(a) for a in A]
    basis = []
    for i, a in enumerate(rows):
        if rank([rows[k] for k in basis] + [a]) > len(basis):
            basis.append(i)
        if len(basis) == n:
            break
    assert len(basis) == n
    rays = list(inverse_cols([rows[k] for k in basis]))
    Z = []
    for j in range(n):
        mask = 0
        for k in range(n):
            if k != j:
                mask |= 1 << basis[k]
        Z.append(mask)
    bset = set(basis)
    for i, a in enumerate(rows):
        if i in bset:
            continue
        vals = [dot(a, r) for r in rays]
        pos = [k for k in range(len(rays)) if vals[k] > 0]
        neg = [k for k in range(len(rays)) if vals[k] < 0]
        zer = [k for k in range(len(rays)) if vals[k] == 0]
        nr = [rays[k] for k in pos] + [rays[k] for k in zer]
        nz = [Z[k] for k in pos] + [Z[k] | (1 << i) for k in zer]
        for p in pos:
            for q in neg:
                common = Z[p] & Z[q]
                if common.bit_count() < n - 2:
                    continue
                if all(not (r != p and r != q and (Z[r] & common) == common) for r in range(len(rays))):
                    nr.append(prim(tuple(vals[p] * rays[q][t] - vals[q] * rays[p][t] for t in range(n))))
                    nz.append(common | (1 << i))
        rays, Z = nr, nz
    return sorted(set(rays))



def self_positive(vs):
    return all(dot(vs[i], vs[j]) >= 0 for i in range(len(vs)) for j in range(i, len(vs)))


extS = extreme_rays(SP_)
print("ext(S'*): %d rays; S'* self-positive: %s; W3-type in cone(S'): %s"
      % (len(extS), self_positive(extS), all(dot(w3, z) >= 0 for z in extS)), flush=True)
print("ext(S'*) orbit reps:", sorted(set(canon(z) for z in extS)), flush=True)
visited = {}
found = []


def node(reps, depth, maxn=150):
    key = tuple(sorted(reps))
    if key in visited or len(visited) >= maxn:
        return
    gens = sorted(set(SP_ + [w for v in key for w in orbit(v)]))
    if not self_positive(gens):
        visited[key] = "NOT-SELF-POSITIVE"
        print("%sNOT-SELF-POSITIVE reps=%s" % ("  " * depth, list(key)), flush=True)
        return
    ext = extreme_rays(gens)
    if self_positive(ext):
        visited[key] = "FOUND"
        found.append(key)
        print("%sFOUND  reps=%s  ext(K*)=%d, ext orbit reps=%s"
              % ("  " * depth, list(key), len(ext), sorted(set(canon(v) for v in ext))), flush=True)
        return
    outside = [z for z in ext if any(dot(z, w) < 0 for w in ext)]
    reps_out = sorted(set(canon(z) for z in outside))
    good = [z for z in reps_out if all(dot(z, w) >= 0 for w in orbit(z))]
    if not good:
        visited[key] = "STUCK"
        print("%sSTUCK  reps=%s  ext(K*)=%d; outside reps %s" % ("  " * depth, list(key), len(ext), reps_out[:6]),
              flush=True)
        return
    visited[key] = "OPEN"
    print("%snode   reps=%s  ext(K*)=%d; children %s" % ("  " * depth, list(key), len(ext), good[:8]), flush=True)
    for z in good:
        node(list(key) + [z], depth + 1)


print("=== root: S' alone", flush=True)
node([], 0)
print("visited %d nodes; FOUND %d: %s" % (len(visited), len(found), found), flush=True)
