#!/usr/bin/env python3
"""Coordinator's independent check of the research/bridge thread's load-bearing numbers (branch head 5f4089a4).
Own table-level code (conventions of the stage-6 audits: tables 4x4, index 0 the unit, states w00 = 1, ipW the
entrywise sum, defects z_s = (E00 + s1 E13 + s2 E22 - s1 s2 E31)/4, P_s = table of the (-1/8)-eigenstate of pauliW(z_s)).
Reads nothing.  Run: python3 -I -B indep_checkB.py
DECISION RULE (fixed before the first run): CONFIRMED/MISMATCH per line; INDEP-B-FIXED iff all CONFIRMED.
 X1 tr(cnot . actC R1) on W 3 = 10/9 (R1 the order-3 rotation about (5,1,1)); the trace of an element of a finite
    group acting linearly is an algebraic integer, and 10/9 is a non-integral rational, so no finite group acting on
    W 3 contains both cnot and actC R1 (the thread's B3-2 obstruction).  Control: tr(cnot . actC cyc3) is an integer.
 X2 the group generated by cnot and the octahedral rotations acting on either token (actC O, actT O) has order 11520.
 X3 K(Z_F) is moved out by actC S (S = R_z(pi/2)), actC cyc3, actC R_z(theta) with cos theta = 3/5, and actC R1, with
    exact negative witnesses in K(Z_F) (pure states in Q3 n Z_F* or defects); the same probes keep Q3 (PSD) valid.
    In the thread's normalization (effects y/4, state w0 = 4 z_s) the thresholds are -1/2, -1/2, -2/5 and the Q3
    controls 1/2, 1/2, 9/20.
 X4 CHSH: phiW = cnot(prodState(xplus, z3)) = diag(1, 1, -1, 1); with settings a in {x, z}, b in {(3,0,4)/5, (-3,0,4)/5}
    S_CHSH = 14/5 for phiW, and each defect 4 z_s also reaches 14/5 with some settings from the same pool.
 X5 the measure-and-prepare realization reproduces the K(Z_F) law exactly: for w0 = 4 z_(1,1), local sharp
    measurements along the pool axes with conditional-state update give joint probabilities equal to the GPT law
    <e_a^o (x) e_b^o', w0>, every probability is in [0, 1], the marginals are setting-independent (no-signalling),
    and 20 q is an integer for every local threshold q in the pool (the seed grid G = 20 realizes the law exactly).
"""
import itertools
import sympy as sp
from sympy import Matrix, Rational as Q, I, eye, zeros, sqrt, simplify, expand, kronecker_product as kron
R = []
def rec(cid, ok, text, detail=""):
    ok = bool(ok); R.append(ok)
    print(f"{'CONFIRMED' if ok else 'MISMATCH'} {cid} {text}" + (f" -- {detail}" if detail else ""))
I2 = eye(2); SX = Matrix([[0, 1], [1, 0]]); SY = Matrix([[0, -I], [I, 0]]); SZ = Matrix([[1, 0], [0, -1]])
SG = [I2, SX, SY, SZ]; KR = {(m, n): kron(SG[m], SG[n]) for m in range(4) for n in range(4)}
def pauliW(w): return sum((w[m, n] * KR[(m, n)] for m in range(4) for n in range(4) if w[m, n] != 0), zeros(4, 4)) / 4
def tab(M): return Matrix(4, 4, lambda m, n: sp.nsimplify(simplify(expand((KR[(m, n)] * M).trace()))))
def ipW(a, b): return expand(sum(a[i, j] * b[i, j] for i in range(4) for j in range(4)))
def E(m, n): B = zeros(4, 4); B[m, n] = 1; return B
def homMap(Rm):
    M = eye(4)
    for i in range(3):
        for j in range(3): M[i + 1, j + 1] = Rm[i, j]
    return M
def actC(Rm, w): return homMap(Rm) * w
def actT(Rm, w): return w * homMap(Rm).T
def prodState(x, y): return Matrix([1] + list(x)) * Matrix([1] + list(y)).T
CNOT = Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
def cnotW(w): return tab(CNOT * pauliW(w) * CNOT.H)
def zdef(s1, s2): return (E(0, 0) + s1 * E(1, 3) + s2 * E(2, 2) - s1 * s2 * E(3, 1)) / 4
SS = [(1, 1), (1, -1), (-1, 1), (-1, -1)]; ZF = {s: zdef(*s) for s in SS}
def negstate(w):
    v = (pauliW(w) + eye(4) / 8).nullspace()[0]; v = v / sqrt((v.H * v)[0]); return tab(v * v.H)
PS = {s: negstate(ZF[s]) for s in SS}
def in_KZF_pure(p): return all(simplify(ipW(p, PS[t])) <= 2 for t in SS)
def minEig(M): return min(M.eigenvals().keys(), key=lambda e: float(e))
# linear map matrices on the 16-dim table space (basis E(m,n) in row-major order)
def linmat(f):
    cols = []
    for m in range(4):
        for n in range(4):
            img = f(E(m, n)); cols.append([img[i, j] for i in range(4) for j in range(4)])
    return Matrix(cols).T
v511 = Matrix([5, 1, 1]); K511 = Matrix([[0, -1, 1], [1, 0, -5], [-1, 5, 0]])
R1 = Q(-1, 2) * eye(3) + K511 / 6 + v511 * v511.T / 18
cyc3 = Matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
Sz90 = Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 1]])              # R_z(pi/2): x -> y, y -> -x
Rz35 = Matrix([[Q(3, 5), Q(-4, 5), 0], [Q(4, 5), Q(3, 5), 0], [0, 0, 1]])   # R_z(theta), cos = 3/5
NF = Matrix.diag(1, -1, -1)
print("== X1 trace obstruction")
Mcnot = linmat(cnotW); MR1 = linmat(lambda w: actC(R1, w)); Mcyc = linmat(lambda w: actC(cyc3, w))
t1 = simplify((Mcnot * MR1).trace()); t1c = simplify((Mcnot * Mcyc).trace())
rec('X1', t1 == Q(10, 9) and t1c.is_integer and (Mcnot * Mcnot == eye(16)) and (MR1 ** 3 == eye(16)),
    'tr(cnot . actC R1) = 10/9, not an algebraic integer, so no finite group on W 3 contains both; control tr(cnot . actC cyc3) integral', 'tr = %s, control %s' % (t1, t1c))
print("== X2 order of <cnot, actC O, actT O>")
# octahedral rotations: signed permutation matrices of det +1
octa = []
for perm in itertools.permutations(range(3)):
    for signs in itertools.product([1, -1], repeat=3):
        M = zeros(3, 3)
        for i in range(3): M[i, perm[i]] = signs[i]
        if M.det() == 1: octa.append(M)
gens = [Mcnot] + [linmat(lambda w, M=M: actC(M, w)) for M in octa] + [linmat(lambda w, M=M: actT(M, w)) for M in octa]
def key(M): return tuple(int(x) for x in M)
seen = {key(eye(16))}; frontier = [eye(16)]
while frontier:
    nxt = []
    for A in frontier:
        for g in gens:
            B = g * A; k = key(B)
            if k not in seen: seen.add(k); nxt.append(B)
    frontier = nxt
rec('X2', len(seen) == 11520 and len(octa) == 24, 'the native pair group <cnot, actC O, actT O> on W 3 has order 11520 (24 octahedral rotations)', 'order %d' % len(seen))
print("== X3 witnesses and thresholds")
bell = Matrix([1, 0, 0, 1]) / sqrt(2); PHI = tab(bell * bell.H)
def best_witness(g):
    # candidate y in K(Z_F): defects and pure states (eigenstate images under a pool of maps) certified by in_KZF_pure
    pool = [actC(M, PS[s]) for s in SS for M in (Sz90, cyc3, cyc3.T, Rz35, R1, R1 * R1, eye(3))] + [actT(M, PS[s]) for s in SS for M in (Sz90, cyc3, Rz35)]
    pool = [p for p in pool if in_KZF_pure(p)]
    best = None
    for s in SS:
        img = actC(g, ZF[s])
        for y in pool + list(ZF.values()):
            v = simplify(ipW(img, y))
            if best is None or v < best[0]: best = (v, s)
    return best
w = {}
for name, g in (('S', Sz90), ('cyc3', cyc3), ('Rz35', Rz35), ('R1', R1)):
    w[name] = best_witness(g)
# thread's normalization: effect y/4 against state 4 z_s equals my ipW(img, y) exactly (factor 4 * 1/4)
ctrl = {}
# run 1 paired the R_z(theta) row with the eigenstate image y = actC(R_z(theta)) P_s (threshold -1/2, control 1/2); the
# thread's row uses the rotated Bell projector y = actC(R_z(pi/2)) P_s of the flow law (threshold -sin(theta)/2 = -2/5,
# control 9/20).  Run 2 uses the flow-law witness for that row; run 1 is kept as indep_checkB.run1.*.
for name, g, ywit in (('S', Sz90, Sz90), ('cyc3', cyc3, cyc3), ('Rz35', Rz35, Sz90)):
    s = (1, 1); y = actC(ywit, PS[s])
    ctrl[name] = (simplify(ipW(actC(g, 4 * ZF[s]), y) / 4), simplify(ipW(actC(g, PHI), y) / 4), in_KZF_pure(y), minEig(pauliW(actC(g, PHI))) >= 0)
rec('X3', all(v[0] < 0 for v in w.values()) and ctrl['S'][0] == Q(-1, 2) and ctrl['cyc3'][0] == Q(-1, 2) and ctrl['Rz35'][0] == Q(-2, 5)
    and ctrl['S'][1] == Q(1, 2) and ctrl['cyc3'][1] == Q(1, 2) and ctrl['Rz35'][1] == Q(9, 20) and all(c[2] and c[3] for c in ctrl.values()),
    'S, cyc3, R_z(theta), R1 each move a defect out of K(Z_F) (negative witnesses); thresholds -1/2, -1/2, -2/5 with Q3 controls 1/2, 1/2, 9/20', 'best witnesses %s; thresholds %s' % ({k: str(v[0]) for k, v in w.items()}, {k: (str(v[0]), str(v[1])) for k, v in ctrl.items()}))
print("== X4 CHSH")
phiW = cnotW(prodState([1, 0, 0], [0, 0, 1]))
def corr(w0, a, b): return expand((Matrix([[0] + list(a)]) * w0 * Matrix([0] + list(b)))[0])
def chsh(w0, a1, a2, b1, b2): return simplify(corr(w0, a1, b1) - corr(w0, a1, b2) + corr(w0, a2, b1) + corr(w0, a2, b2))
b0 = [Q(-3, 5), 0, Q(4, 5)]; b1v = [Q(3, 5), 0, Q(4, 5)]
axes = {'x': [1, 0, 0], 'y': [0, 1, 0], 'z': [0, 0, 1]}
S_phi = chsh(phiW, axes['x'], axes['z'], b1v, b0)
pool_b = list(axes.values()) + [b0, b1v]
def max_chsh(w0):
    best = 0
    for a1, a2 in itertools.permutations(list(axes.values()), 2):
        for bb1, bb2 in itertools.permutations(pool_b, 2):
            for sg in (1, -1):
                v = simplify(sg * chsh(w0, a1, a2, bb1, bb2))
                if v > best: best = v
    return best
mx = {s: max_chsh(4 * ZF[s]) for s in SS}
rec('X4', phiW == Matrix.diag(1, 1, -1, 1) and S_phi == Q(14, 5) and all(v == Q(14, 5) for v in mx.values()),
    'phiW = diag(1,1,-1,1); S_CHSH(phiW) = 14/5 at the stated settings; every defect reaches 14/5 within the pool', 'phiW %s, defects %s' % (S_phi, {str(k): str(v) for k, v in mx.items()}))
print("== X5 the measure-and-prepare realization reproduces the K(Z_F) law exactly")
w0 = 4 * ZF[(1, 1)]
def sharp(a, o): return Matrix([Q(1, 2)] + [o * Q(x, 2) if not isinstance(x, sp.Basic) else o * x / 2 for x in a])
def gpt(w0, a, o, b, op): return simplify((sharp(a, o).T * w0 * sharp(b, op))[0])
def realized(w0, a, o, b, op):
    # A measures first: P(o) = <e_a^o (x) unit, w0>; conditional state of B; then B measures
    e = sharp(a, o); unit = Matrix([1, 0, 0, 0])
    p_o = simplify((e.T * w0 * unit)[0])
    if p_o == 0: return 0, p_o
    condB = (e.T * w0).T / p_o          # B's conditional state (table column), unit entry 1
    p_op = simplify((sharp(b, op).T * condB)[0])
    return simplify(p_o * p_op), p_o
ok5 = True; thresholds = set(); details = []
settings_A = list(axes.values()); settings_B = pool_b
for a in settings_A:
    for b in settings_B:
        for o in (1, -1):
            for op in (1, -1):
                g = gpt(w0, a, o, b, op); r, p_o = realized(w0, a, o, b, op)
                ok5 = ok5 and r == g and 0 <= g <= 1
                thresholds.add(p_o)
        # no-signalling: A's marginal independent of b, B's marginal independent of a
        mA = simplify(sum(gpt(w0, a, 1, b, op) for op in (1, -1))); mB = {}
        for bb in settings_B: mB[tuple(bb)] = simplify(sum(gpt(w0, a, o, bb, 1) for o in (1, -1)))
        ok5 = ok5 and mA == simplify((sharp(a, 1).T * w0 * Matrix([1, 0, 0, 0]))[0])
# conditional thresholds for B after A's outcome
for a in settings_A:
    for o in (1, -1):
        e = sharp(a, o); p_o = simplify((e.T * w0 * Matrix([1, 0, 0, 0]))[0]); condB = (e.T * w0).T / p_o
        for b in settings_B: thresholds.add(simplify((sharp(b, 1).T * condB)[0]))
grid_ok = all((20 * t).is_integer for t in thresholds)
rec('X5', ok5 and grid_ok, 'measure-and-prepare dynamics = the GPT law exactly on the pool, all probabilities in [0,1], no-signalling marginals, every threshold on the 20-grid', 'thresholds %s' % sorted(str(t) for t in thresholds))
print('SUMMARY %d/%d CONFIRMED' % (sum(R), len(R)))
print('INDEP-B-FIXED' if all(R) else 'INDEP-B-MISMATCH')
