#!/usr/bin/env python3
# induced_source_probes.py — b436 (2026-08-27)
#
# b405's LATTICE source witness, evaluated on the OI construction's own configuration space.
#
# THE CLAIM UNDER TEST. b405 §3 deforms the matter action by
#
#   dS_kappa = sum_x |phi_x|^2 [ kappa_E sum_i (1 - Re P_0i(x)) + kappa_B sum_{i<j} (1 - Re P_ij(x)) ]
#
# and observes that it vanishes at U_mu = I with vanishing first source derivative but independently
# tunable second derivative. Hence: zero-source law + gauge covariance + linear current vertex do
# not determine the vacuum polarization. That argument treats U as an INDEPENDENT field, free to be
# set to I or not, which is the right setting for a general lattice gauge theory.
#
# OI's LINK IS NOT INDEPENDENT. [SM §6], the induced-measure passage, fixes
#
#   M(n, e_j) = exp( (2 pi i / q) Lie[ phi(n + e_j) - phi(n) ] ),
#
# a function of the NEAREST-NEIGHBOUR MATTER DIFFERENCE. Around a plaquette the four exponents
# telescope to zero identically, whatever the configuration. Consequently, with eps = 2 pi / q:
#
#   - ABELIAN: the induced plaquette is EXACTLY the identity on every configuration (IS1), so
#     dS_kappa is IDENTICALLY THE ZERO FUNCTIONAL there -- not merely zero at a chosen background.
#     [SM §6] already states this ("its classical field strength is identically zero (the gradient
#     connection is pure gauge)"); what is new here is the consequence for b405's witness.
#   - NON-ABELIAN: the exponents still sum to zero (IS2), so log P is a pure commutator, O(eps^2),
#     and the plaquette ACTION 1 - Re Tr P / N starts at eps^4 (IS3) -- against a hopping term that
#     deviates from the identity at eps^1.
#
# So b405's kappa direction is not a leading-order direction in OI's own theory space; it is a
# direction in the ambient independent-link theory that OI sits inside. This does NOT dissolve
# b405's question -- see SCOPE.
#
# WHAT THE FRAMEWORK SUPPLIES THAT b405 §6 ASKED FOR. b405 §2 proves the source lift is unique,
# B(U) = U, CONDITIONAL on a strict nearest-edge bilinear operator basis (IS5 checks that lemma's
# two halves and its reducible countercontrol), and §6 flags that condition as a model choice
# "unless a source naturality/minimality statement is derived for the coherent lift". The OI
# construction supplies one structurally: the substratum dynamics is the strict nearest-neighbour
# wave equation ([SM §4.1] Lemma; [Substratum] A4/A5), the staggered operator factorizes it
# ([SM §4.2] Theorem 2, D_st^2 = -(1/4) Box_lat), and the link enters the action in the hopping term
# and NOWHERE ELSE (IS6). On a compact lattice link the n-photon vertices are then Taylor
# coefficients of ONE exponential, so the seagull is determined by the single-photon vertex rather
# than being an independent parameter (IS4) -- which is exactly what a kappa term would add, and
# exactly what the induced plaquette does not supply at leading order.
#
# ARITHMETIC. Everything here is exact rational or Gaussian-rational; the objects are small enough
# (2x2 and 3x3, and truncated series in eps) that no finite-field detour is needed. The eps-order
# statements are EXACT SERIES COEFFICIENTS, not float scaling fits: b434's hazard was a float rank
# test reporting full rank on an identically zero matrix, and a float log-log slope for an eps^4 law
# is the same mistake wearing a different hat. A first exploratory pass here did fit slopes, and
# read 7.2, 10.5, 15.9, 22.5 for a ratio whose exact value is 16 -- because the random field was
# redrawn at each eps. The series below cannot drift that way.
#
# SCOPE, and it is the whole difficulty of reading this round.
#   - This does NOT compute Z_E/Z_B, and b404's E/B gate remains unevaluated. What narrows is the
#     SPACE OF LIFTS, not the value of any observable.
#   - It does NOT prove the EFFECTIVE action has no plaquette terms. Those are generated by the
#     fermion determinant from a microscopically minimal action.
#   - AND IT DOES NOT REDUCE THE LATTICE HALF TO THAT COMPUTATION. For U(1) the vanishing proved
#     here cuts the other way: b437 (gauge_support_probes.py) shows the induced abelian link is
#     EXACTLY pure gauge, so D[U[phi]] = G^dag D[I] G, S_eff is CONSTANT on the induced manifold,
#     and the minimal and kappa-dressed extensions agree on the WHOLE physical image rather than
#     only at U = I. That is a stronger ambiguity than b405 exhibited, and it makes the prior
#     question one of SUPPORT: H-transverse-link, named there.
#   - The eps^4 suppression is a statement at kappa = O(1) in cutoff units. Nothing here bounds
#     kappa, so a kappa growing like eps^-4 is not excluded by this argument.
#   - IS6 reads manuscript prose. That is weaker than the rest of the file and is labelled so.
#   - Nothing here touches the OPERATIONAL half (b405 §5, settled at b434/b435 in
#     source_lift_probes.py). b426 recorded that the two settings have no bridge; none is supplied
#     here either, and this file is separate from that one for exactly that reason.
import sys
import time
from fractions import Fraction as F

CHECKS = []
DEG = 6                                    # truncate eps-series at eps^DEG

def check(label, ok, msg):
    CHECKS.append(bool(ok))
    print(f"  {'PASS' if ok else 'FAIL'}  {label}: {msg}", flush=True)

# ---------------------------------------------------------------- Gaussian rationals
def gadd(x, y): return (x[0] + y[0], x[1] + y[1])
def gsub(x, y): return (x[0] - y[0], x[1] - y[1])
def gmul(x, y): return (x[0]*y[0] - x[1]*y[1], x[0]*y[1] + x[1]*y[0])
def gscale(c, x): return (c * x[0], c * x[1])
GZ, GO = (F(0), F(0)), (F(1), F(0))

# ---------------------------------------------------------------- truncated eps-polynomials
def padd(a, b): return [gadd(x, y) for x, y in zip(a, b)]
def pmul(a, b):
    out = [GZ] * DEG
    for i, x in enumerate(a):
        if x == GZ:
            continue
        for j, y in enumerate(b):
            if i + j < DEG and y != GZ:
                out[i + j] = gadd(out[i + j], gmul(x, y))
    return out
def pscale(c, a): return [gscale(c, x) for x in a]
def pconst(g): return [g] + [GZ] * (DEG - 1)
PZ, PO = pconst(GZ), pconst(GO)
def pzero(a): return all(x == GZ for x in a)

def meye(n): return [[PO if r == c else PZ for c in range(n)] for r in range(n)]
def madd(A, B): return [[padd(x, y) for x, y in zip(ra, rb)] for ra, rb in zip(A, B)]
def mscale(c, A): return [[pscale(c, x) for x in row] for row in A]
def mzero(A): return all(pzero(p) for row in A for p in row)
def mmul(A, B):
    n = len(A)
    out = [[PZ] * n for _ in range(n)]
    for r in range(n):
        for c in range(n):
            tot = PZ
            for k in range(n):
                tot = padd(tot, pmul(A[r][k], B[k][c]))
            out[r][c] = tot
    return out
def mexp(A):
    """exp(A) truncated at eps^DEG. A must have zero constant term."""
    assert all(p[0] == GZ for row in A for p in row), 'A must be O(eps)'
    n = len(A)
    out, term = meye(n), meye(n)
    for k in range(1, DEG + 1):
        term = mscale(F(1, k), mmul(term, A))
        out = madd(out, term)
    return out

# su(2): the anti-Hermitian generators i*sigma_a, with Gaussian-INTEGER entries
ISIG = ([[GZ, (F(0), F(1))], [(F(0), F(1)), GZ]],
        [[GZ, (F(1), F(0))], [(F(-1), F(0)), GZ]],
        [[(F(0), F(1)), GZ], [GZ, (F(0), F(-1))]])

def lie_eps(vec):
    """eps * sum_a vec[a] (i sigma_a): the induced link exponent, linear in the matter difference."""
    M = [[PZ] * 2 for _ in range(2)]
    for a, v in enumerate(vec):
        for r in range(2):
            for c in range(2):
                p = [GZ] * DEG
                p[1] = gscale(F(v), ISIG[a][r][c])      # the eps^1 slot
                M[r][c] = padd(M[r][c], p)
    return M

sub3 = lambda a, b: tuple(x - y for x, y in zip(a, b))

# ---------------------------------------------------------------- IS1  abelian, exactly trivial
print("IS1  the induced ABELIAN plaquette is exactly the identity, on every configuration")
ok1, tested = True, 0
# exhaustive over every Z/qZ field on a 2x2 torus for small q, then a large-q spot check
for q in (2, 3, 5):
    L = 2
    for code in range(q ** (L * L)):
        f, phi = code, {}
        for x in range(L):
            for y in range(L):
                phi[(x, y)] = f % q; f //= q
        for x in range(L):
            for y in range(L):
                # the plaquette exponent is the alternating sum of nearest-neighbour differences
                e = ((phi[((x+1) % L, y)] - phi[(x, y)])
                     + (phi[((x+1) % L, (y+1) % L)] - phi[((x+1) % L, y)])
                     - (phi[((x+1) % L, (y+1) % L)] - phi[(x, (y+1) % L)])
                     - (phi[(x, (y+1) % L)] - phi[(x, y)])) % q
                ok1 &= (e == 0); tested += 1
# a deterministic large-q, larger-torus sweep (no RNG: the statement is configuration-independent)
for q in (251, 4096):
    L = 5
    phi = {(x, y): (7 * x * x + 13 * y * y * y + 5 * x * y + 1) % q for x in range(L) for y in range(L)}
    for x in range(L):
        for y in range(L):
            e = ((phi[((x+1) % L, y)] - phi[(x, y)])
                 + (phi[((x+1) % L, (y+1) % L)] - phi[((x+1) % L, y)])
                 - (phi[((x+1) % L, (y+1) % L)] - phi[(x, (y+1) % L)])
                 - (phi[(x, (y+1) % L)] - phi[(x, y)])) % q
            ok1 &= (e == 0); tested += 1
check("IS1", ok1,
      f"every one of {tested} plaquette exponents vanishes exactly mod q — exhaustively over ALL "
      "Z/qZ fields on a 2x2 torus at q = 2, 3, 5, and on a 5x5 torus at q = 251 and 4096. The "
      "induced abelian connection is a lattice gradient, so the four link exponents telescope. "
      "b405's kappa deformation is therefore the ZERO FUNCTIONAL on the abelian sector of OI's "
      "configuration space, not merely zero at the trivial background it is evaluated at")

# ---------------------------------------------------------------- IS2  non-abelian telescoping
print("IS2  the non-abelian exponents telescope too, so the plaquette is I + O(eps^2)")
CONFIGS = (((1, 0, 0), (0, 2, 1), (3, 1, 0), (1, 1, 2)),
           ((2, 1, 3), (1, 1, 1), (0, 4, 2), (3, 0, 1)),
           ((0, 0, 1), (5, 2, 0), (1, 3, 4), (2, 2, 2)))
ok2 = True
for L00, L10, L01, L11 in CONFIGS:
    X1, X2 = lie_eps(sub3(L10, L00)), lie_eps(sub3(L11, L10))
    X3, X4 = lie_eps(sub3(L11, L01)), lie_eps(sub3(L01, L00))
    ok2 &= mzero(madd(madd(X1, X2), madd(mscale(F(-1), X3), mscale(F(-1), X4))))
    Pl = mmul(mmul(mexp(X1), mexp(X2)), mmul(mexp(mscale(F(-1), X3)), mexp(mscale(F(-1), X4))))
    ok2 &= all(Pl[r][c][1] == GZ for r in range(2) for c in range(2))     # eps^1 term vanishes
    ok2 &= all(Pl[r][c][0] == (GO if r == c else GZ) for r in range(2) for c in range(2))
check("IS2", ok2,
      f"at {len(CONFIGS)} site-field configurations the four exponents sum to EXACTLY zero — the "
      "telescoping is algebra-blind, since Lie[.] is linear and the differences cancel around the "
      "loop — and the plaquette's eps^1 coefficient vanishes identically, leaving P = I + O(eps^2) "
      "with the eps^2 term a pure commutator. Non-abelian field strength survives only because the "
      "exponentials do not commute")

# ---------------------------------------------------------------- IS3  the action starts at eps^4
print("IS3  so the induced plaquette ACTION starts at eps^4, against an eps^1 hopping term")
ok3, leads = True, []
for L00, L10, L01, L11 in CONFIGS:
    X1, X2 = lie_eps(sub3(L10, L00)), lie_eps(sub3(L11, L10))
    X3, X4 = lie_eps(sub3(L11, L01)), lie_eps(sub3(L01, L00))
    Pl = mmul(mmul(mexp(X1), mexp(X2)), mmul(mexp(mscale(F(-1), X3)), mexp(mscale(F(-1), X4))))
    tr = padd(Pl[0][0], Pl[1][1])
    act = pscale(F(-1, 2), tr)
    act[0] = gadd(act[0], GO)                                   # 1 - Re Tr(P)/2
    lead = next((k for k in range(DEG) if act[k][0] != 0), None)
    leads.append(lead)
    ok3 &= (lead == 4)
    # and the link itself moves at first order, which is the comparison that gives eps^4 its meaning
    ok3 &= (mexp(X1)[0][1][1] != GZ or mexp(X1)[0][0][1] != GZ)
check("IS3", ok3 and leads == [4] * len(CONFIGS),
      f"the exact series coefficients of 1 - Re Tr(P)/2 vanish at eps^0..eps^3 and are nonzero at "
      f"eps^4, at every configuration tested (leading orders {leads}), while the link itself "
      "departs from the identity at eps^1. These are EXACT rational series coefficients, not a "
      "fitted log-log slope. So on induced configurations b405's kappa term is suppressed by four "
      "powers of 2 pi / q relative to the hopping term it would have to compete with — at "
      "kappa = O(1) in cutoff units, which is the one thing this does not itself establish")

# ---------------------------------------------------------------- IS4  contact terms are not free
print("IS4  on a compact link the seagull is a Taylor coefficient, not a parameter")
# U(1) hopping exp(i a A): the n-photon vertices are the derivatives of ONE exponential, so
# V_2 = V_1^2 identically. An independent contact term kappa A^2 breaks exactly that tie while
# leaving V_1 alone -- which is b405's AR4 restated as a statement about the vertex tower.
a = F(3, 7)
V1 = (F(0), a)                                   # d/dA exp(i a A) at 0  = i a
V2 = gmul(V1, V1)                                # d^2/dA^2 of the same exponential = (i a)^2
tie_holds = (V2 == (-a * a, F(0)))
broken = []
for kappa in (F(1, 5), F(-2, 3)):
    V2k = gadd(V2, (2 * kappa, F(0)))            # add an independent A^2 contact term
    broken.append(V2k != V2 and True)
    # the LINEAR vertex is untouched by it, which is why the zero-source law cannot see it
    broken.append(V1 == (F(0), a))
check("IS4", tie_holds and all(broken),
      "for a compact lattice link the single-photon and two-photon vertices are the first and "
      "second Taylor coefficients of the same exponential, so V_2 = V_1^2 identically and the "
      "seagull carries no free coefficient. An independent A^2 contact term shifts V_2 while "
      "leaving V_1 untouched — precisely b405's AR4 — so the freedom it exhibits is the freedom "
      "to add such a term. IS1-IS3 say the plaquette operator that would carry it is zero "
      "(abelian) or eps^4-suppressed (non-abelian) on OI's own configurations")

# ---------------------------------------------------------------- IS5  b405 §2's lemma
print("IS5  b405 §2's uniqueness lemma, both halves and the reducible countercontrol")
def commutant_dim(gens, n):
    """dim_C { X : X g = g X for all g }, by exact rank over Q(i) treated as 2n^2 real unknowns."""
    rows = []
    for g in gens:
        for r in range(n):
            for c in range(n):
                # (Xg - gX)[r][c] = sum_k X[r][k] g[k][c] - g[r][k] X[k][c]
                re_row = [F(0)] * (2 * n * n); im_row = [F(0)] * (2 * n * n)
                def bump(i, j, coef):
                    idx = 2 * (i * n + j)
                    re_row[idx] += coef[0]; re_row[idx + 1] -= coef[1]
                    im_row[idx] += coef[1]; im_row[idx + 1] += coef[0]
                for k in range(n):
                    bump(r, k, g[k][c])
                    bump(k, c, (-g[r][k][0], -g[r][k][1]))
                rows.append(re_row); rows.append(im_row)
    # exact rank over Q
    m = [r[:] for r in rows]; rank = 0
    for col in range(2 * n * n):
        piv = next((i for i in range(rank, len(m)) if m[i][col] != 0), None)
        if piv is None:
            continue
        m[rank], m[piv] = m[piv], m[rank]
        pv = m[rank][col]
        m[rank] = [x / pv for x in m[rank]]
        for i in range(len(m)):
            if i != rank and m[i][col] != 0:
                f = m[i][col]
                m[i] = [x - f * y for x, y in zip(m[i], m[rank])]
        rank += 1
    return (2 * n * n - rank) // 2                     # complex dimension

# the defining SU(2) rep is irreducible: two Pythagorean generators suffice to pin the commutant
g1 = [[(F(3, 5), F(0)), (F(4, 5), F(0))], [(F(-4, 5), F(0)), (F(3, 5), F(0))]]
g2 = [[(F(0), F(5, 13)), (F(12, 13), F(0))], [(F(-12, 13), F(0)), (F(0), F(-5, 13))]]
d_irr = commutant_dim([g1, g2], 2)
# a reducible carrier: the same block plus a trivial one. Schur then gives one scalar per block.
emb = lambda g: [[g[0][0], g[0][1], GZ], [g[1][0], g[1][1], GZ], [GZ, GZ, GO]]
d_red = commutant_dim([emb(g1), emb(g2)], 3)
# and the covariance step: with G_x = U, G_y = I, B(U) = B(I) U = c U. Verified as an identity on
# explicit elements rather than asserted: c U satisfies covariance, U^2 does not. The two gauge
# arguments must DIFFER for that countercontrol to bite — at G_x = G_y conjugation is an algebra
# homomorphism and U -> U^2 is covariant too, which makes G_x = G_y a vacuous test.
def mm2(A, C):
    return [[gadd(gmul(A[r][0], C[0][c]), gmul(A[r][1], C[1][c])) for c in range(2)]
            for r in range(2)]
minv = lambda G: [[G[1][1], gscale(F(-1), G[0][1])],
                  [gscale(F(-1), G[1][0]), G[0][0]]]           # det = 1 for our generators
def cov_ok(B, U, Gx, Gy):
    return B(mm2(mm2(Gx, U), minv(Gy))) == mm2(mm2(Gx, B(U)), minv(Gy))
g3 = mm2(g1, g2)
det1 = all(gsub(gmul(g[0][0], g[1][1]), gmul(g[0][1], g[1][0])) == GO for g in (g1, g2, g3))
lin_ok = cov_ok(lambda U: U, g3, g1, g2)
sq_bad = not cov_ok(lambda U: mm2(U, U), g3, g1, g2)
# the vacuous-test guard, recorded so the countercontrol cannot silently rot back to G_x = G_y
sq_vacuous_at_equal = cov_ok(lambda U: mm2(U, U), g3, g1, g1)
check("IS5", d_irr == 1 and d_red == 2 and lin_ok and sq_bad and det1 and sq_vacuous_at_equal,
      f"the commutant of the defining (irreducible) carrier has complex dimension {d_irr} — Schur, "
      f"so B(I) = cI — while the reducible 2+1 carrier gives {d_red}, one coefficient per block, "
      "which is the qualification b405 §2 states. Covariance then forces B(U) = B(I)U = cU, "
      "verified as an identity at DISTINCT gauge arguments: B(U) = U satisfies it and B(U) = U^2 "
      "does not. The distinctness matters and is asserted here — at G_x = G_y the square is "
      "covariant too, so a countercontrol run there tests nothing. The lemma is sound; §6's point "
      "is that its EDGE-BILINEAR HYPOTHESIS was the open part")

# ---------------------------------------------------------------- IS6  the hypothesis is supplied
print("IS6  the OI construction meets that hypothesis structurally (prose anchors — weakest check)")
import os
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    '..', '..', '..'))
rd = lambda *p: open(os.path.join(ROOT, *p), encoding='utf-8').read()
sm, sub_ = rd('papers', 'SM.md'), rd('papers', 'Substratum.md')
anchors = {
    'wave equation is strictly nearest-neighbour':
        'second-order reversible nearest-neighbor rule' in sm,
    'the induced link is a nearest-neighbour matter difference':
        'phi(\\mathbf{n}+\\hat e_j) - \\phi(\\mathbf{n})' in sm.replace('$', '')
        or '\\phi(\\mathbf{n}+\\hat e_j) - \\phi(\\mathbf{n})' in sm,
    # matched by CONTENT, not by one phrasing: b437's manuscript edit rewrote this sentence and
    # broke a literal anchor here, which is the failure mode b431/b432 already paid for on notes
    'the abelian induced connection is stated to be pure gauge':
        any(f in sm for f in ('classical field strength is identically zero',
                              'lattice gradient, so it is pure gauge',
                              'the gradient connection is pure gauge')),
    'the staggered operator factorizes the wave operator':
        'D_{\\text{st}}^2 = -\\frac{1}{4}\\Box_{\\text{lat}}' in sm,
    'no tree-level gauge self-interaction in the induced theory':
        'no tree-level gauge self-interactions exist in the induced theory' in sm,
    'the wave equation governs the local lattice sector':
        'wave equation' in sub_,
}
check("IS6", all(anchors.values()),
      "the manuscript's own statements supply b405 §2's missing hypothesis: "
      + '; '.join(k for k, v in anchors.items() if v)
      + ". The link enters through the hopping term of a strict nearest-neighbour operator and "
      "nowhere else, so the strict edge-bilinear basis is the framework's structure rather than a "
      "modelling choice. THIS CHECK READS PROSE and is the weakest in the file: it confirms the "
      "statements are present, not that they are true")

# ---------------------------------------------------------------- IS7  what this settles
print("IS7  what the round settles, and what it leaves untouched")
check("IS7", True,
      "b405's lattice witness is a direction in the ambient independent-link theory, not a "
      "leading-order direction in OI's own theory space; and §2's uniqueness lemma, which §6 left "
      "conditional on a modelling choice, is met by the construction's own nearest-neighbour "
      "structure. What that does NOT license is the reading that the lattice half reduces to "
      "computing the determinant's contact terms: for U(1) the same vanishing makes b405's "
      "counterexample STRONGER, since two extensions then agree on the entire induced manifold "
      "while differing transversally. See gauge_support_probes.py (GS1-GS7), which proves the "
      "induced U(1) link exactly pure gauge and S_eff constant there, and names the condition "
      "H-transverse-link that the ambient computation needs")

print()
print("     [scope] Settled: on OI's induced configurations b405's kappa deformation is the ZERO")
print("     functional in the abelian sector and eps^4-suppressed in the non-abelian one, against")
print("     an eps^1 hopping term; and the strict edge-bilinear hypothesis of b405 §2's uniqueness")
print("     lemma is supplied by the construction rather than chosen, so the lift B(U) = U is")
print("     forced. What this does NOT settle is the lattice half as a whole: for U(1) the same")
print("     vanishing SHARPENS b405's counterexample rather than dissolving it, because two")
print("     extensions then agree on the entire induced manifold and not merely at U = I. See")
print("     gauge_support_probes.py, which proves the induced U(1) link exactly pure gauge, S_eff")
print("     constant on that manifold, and names the condition H-transverse-link.")
print("     NOT settled: Z_E/Z_B is not computed and b404's E/B gate is not evaluated; the")
print("     EFFECTIVE action's plaquette terms are generated by the determinant and are not")
print("     computed here; nothing bounds kappa, so a kappa growing like eps^-4 is untouched; IS6")
print("     reads prose rather than proving it. And nothing here bridges to the operational half")
print("     of b405 (§5, settled at b434/b435) — b426 recorded there is no bridge, and this file")
print("     is deliberately separate from source_lift_probes.py for that reason.")
print()
print("induced_source_probes:", "ALL CHECKS PASS" if all(CHECKS) else "FAILURE")
sys.exit(0 if all(CHECKS) else 1)
