#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The minimal-repertoire audit: which drive graphs generate su(D)?

The elementary repertoire of LieRankSource.lean is every pair continuously driven, every exchange,
and a quarter phase on every state. The drive on a pair (a, b) is the flow of the real transition
X_ab = E_ab + E_ba, i.e. the skew-Hermitian direction -i X_ab. Conjugating one driven pair by the
available permutations gives drives on the edges of a graph G on the D states (the orbit graph), so
the question "how little control selects quantum mechanics" is, at the Lie-algebraic level,

    for which graphs G does { -i X_e : e an edge of G } generate su(D)?

WHAT IS CHECKED HERE, exactly over Q. Every generator has Gaussian-integer entries and every
iterated bracket stays Gaussian, so the real dimension of the generated Lie algebra is the rank
over Q of the (real part, imaginary part) coordinate vectors, computed by exact fraction-free
elimination. No floating point anywhere.

  L1. ODD CYCLES generate su(D):        D = 3, 5, 7   ->  D^2 - 1.
  L2. EVEN CYCLES do not:               D = 4, 6, 8   ->  D(D-1)/2, the dimension of so(D).
  L3. PATHS do not:                     D = 3..6      ->  D(D-1)/2.
  L4. COMPLETE GRAPHS generate su(D):   D = 3, 4, 5   ->  D^2 - 1  (one drive + all exchanges).
  L5. A CYCLE PLUS ONE CHORD generates: D = 4, 6      ->  D^2 - 1.
  L6. D = 2, drive + swap:              dimension 1, and no diagonal direction.
  L7. THE BIPARTITE INVARIANT: for every even cycle and every path, every element of the generated
      algebra has zero diagonal, so the population difference i(E_pp - E_qq) is never reached.

THE MECHANISM (proved in MinimalRepertoire.lean). For a bipartite G with colouring c, the diagonal
phase Lambda = diag(i on c = true, 1 on c = false) carries each drive on a bichromatic edge to a
real antisymmetric matrix; the real antisymmetric matrices form a Lie algebra with zero diagonal;
so the generated algebra is a conjugate of a subalgebra of so(D) and contains no population
difference. For a connected non-bipartite G, two drives sharing a state bracket to the imaginary
transition on the third pair (the direction the quarter phase used to supply), the real and
imaginary transitions on a pair bracket to the population difference, and the round-59
decomposition of a traceless skew-Hermitian matrix finishes.

CONSEQUENCE FOR THE PRIMITIVE. "One drive + one cyclic permutation" generates full control exactly
at odd D; every doubled level is even, so the theory-level primitive is one driven pair plus the
exchanges (orbit graph the complete graph, which has a triangle). The exchanges are generated by one
full cycle and one adjacent exchange; L2 says the adjacent exchange cannot be dropped.

SCOPE TOKENS, machine-checked by the R7-MIN guard in edge_rigidity_probe.py.

    SCOPE-TOKEN: ODD-CYCLE-FULL        one drive + one D-cycle generates su(D) iff D is odd
    SCOPE-TOKEN: BIPARTITE-NO-DIAGONAL bipartite drive graphs reach no population difference
    SCOPE-TOKEN: EXCHANGES-NOT-DROPPED one cycle alone is not the exchange clause
"""
from fractions import Fraction
import sys

# A Gaussian-rational matrix is a dict {(i, j): (re, im)} of Fractions over D x D, zeros omitted.


def X(D, a, b):
    """-i (E_ab + E_ba): the drive direction on the pair (a, b)."""
    m = {}
    m[(a, b)] = (Fraction(0), Fraction(-1))
    m[(b, a)] = (Fraction(0), Fraction(-1))
    return m


def mul(D, P, Q):
    out = {}
    rows = {}
    for (i, k), v in P.items():
        rows.setdefault(i, []).append((k, v))
    cols = {}
    for (k, j), v in Q.items():
        cols.setdefault(k, []).append((j, v))
    for i, lst in rows.items():
        for k, (pr, pi) in lst:
            for j, (qr, qi) in cols.get(k, []):
                r, im = out.get((i, j), (Fraction(0), Fraction(0)))
                out[(i, j)] = (r + pr * qr - pi * qi, im + pr * qi + pi * qr)
    return {k: v for k, v in out.items() if v != (0, 0)}


def sub(P, Q):
    out = dict(P)
    for k, (qr, qi) in Q.items():
        r, im = out.get(k, (Fraction(0), Fraction(0)))
        out[k] = (r - qr, im - qi)
    return {k: v for k, v in out.items() if v != (0, 0)}


def bracket(D, P, Q):
    return sub(mul(D, P, Q), mul(D, Q, P))


def vec(D, M):
    v = [Fraction(0)] * (2 * D * D)
    for (i, j), (r, im) in M.items():
        v[i * D + j] = r
        v[D * D + i * D + j] = im
    return v


class Basis:
    """Exact row-echelon basis over Q, with the pivot of each stored row."""

    def __init__(self, n):
        self.n = n
        self.rows = []      # reduced rows
        self.pivots = []    # pivot column of each row

    def reduce(self, v):
        v = list(v)
        for row, p in zip(self.rows, self.pivots):
            if v[p] != 0:
                f = v[p] / row[p]
                v = [a - f * b for a, b in zip(v, row)]
        return v

    def add(self, v):
        v = self.reduce(v)
        for p, a in enumerate(v):
            if a != 0:
                self.rows.append(v)
                self.pivots.append(p)
                return True
        return False

    def dim(self):
        return len(self.rows)


def generated_algebra(D, gens):
    """The real Lie algebra generated by gens: returns (dimension, list of basis matrices)."""
    B = Basis(2 * D * D)
    mats = []
    for g in gens:
        if B.add(vec(D, g)):
            mats.append(g)
    frontier = list(mats)
    while frontier:
        new = []
        for P in frontier:
            for Q in mats:
                C = bracket(D, P, Q)
                if C and B.add(vec(D, C)):
                    new.append(C)
        mats.extend(new)
        frontier = new
    return B.dim(), mats


def diagonal_free(mats):
    return all(all(M.get((i, i), (0, 0)) == (0, 0) for i in range(64)) for M in mats)


def cycle(D):
    return [X(D, k, (k + 1) % D) for k in range(D)]


def path(D):
    return [X(D, k, k + 1) for k in range(D - 1)]


def complete(D):
    return [X(D, a, b) for a in range(D) for b in range(a + 1, D)]


checks = []


def check(tag, ok, msg):
    checks.append(ok)
    print(f"  {'PASS' if ok else 'FAIL'}  {tag}: {msg}")


def su(D):
    return D * D - 1


def so(D):
    return D * (D - 1) // 2


print("repertoire_lie_probe: the generated Lie algebra of drive graphs, exact over Q")

for D in (3, 5, 7):
    d, _ = generated_algebra(D, cycle(D))
    check(f"L1 D={D}", d == su(D), f"odd cycle generates dimension {d} = su({D}) = {su(D)}")

for D in (4, 6, 8):
    d, mats = generated_algebra(D, cycle(D))
    check(f"L2 D={D}", d == so(D), f"even cycle generates dimension {d} = so({D}) = {so(D)}, "
          f"not su({D}) = {su(D)}")
    check(f"L7 cycle D={D}", diagonal_free(mats), "every element of the even-cycle algebra "
          "has zero diagonal: no population difference")

for D in (3, 4, 5, 6):
    d, mats = generated_algebra(D, path(D))
    check(f"L3 D={D}", d == so(D), f"path generates dimension {d} = so({D}) = {so(D)}")
    check(f"L7 path D={D}", diagonal_free(mats), "every element of the path algebra has zero "
          "diagonal")

for D in (3, 4, 5):
    d, _ = generated_algebra(D, complete(D))
    check(f"L4 D={D}", d == su(D), f"complete graph (one drive + all exchanges) generates "
          f"dimension {d} = su({D}) = {su(D)}")

for D in (4, 6):
    d, _ = generated_algebra(D, cycle(D) + [X(D, 0, 2)])
    check(f"L5 D={D}", d == su(D), f"even cycle plus the chord (0,2) generates dimension {d} "
          f"= su({D}) = {su(D)}")

d, mats = generated_algebra(2, [X(2, 0, 1)])
check("L6", d == 1 and diagonal_free(mats), "D = 2: the drive and the swap commute; the algebra is "
      "one-dimensional with zero diagonal, so the Z-rotation direction is unreachable")

print()
print("     [scope] One drive + one D-cycle generates su(D) exactly when D is odd; even cycles and")
print("     paths are bipartite and generate a conjugate of so(D) with no diagonal direction. The")
print("     theory-level primitive is therefore one driven pair plus the exchanges (a complete orbit")
print("     graph); the exchanges are generated by one full cycle and one adjacent exchange, and the")
print("     adjacent exchange cannot be dropped. Nothing here is a theory-level statement; the kernel")
print("     (MinimalRepertoire.lean) carries those.")
print()
print("repertoire_lie_probe:", "ALL CHECKS PASS" if all(checks) else "FAILURE")
sys.exit(0 if all(checks) else 1)
