"""K/R discrimination probes -- read-only, exact arithmetic (sympy / Fractions). Nothing here touches the repository.

P1  local-tomography parameter counting: K(N) for classical, real, complex, quaternionic state spaces, and the product
    rule K(NM) = K(N) K(M) for N, M <= 8.
P2  real QM fails local tomography: sigma_y (x) sigma_y is a real symmetric 2-qubit matrix orthogonal (Hilbert-Schmidt)
    to every product of real symmetric local observables, so rho_pm = (I (x) I +- s_y (x) s_y)/4 are distinct real
    states with identical local statistics; both are PSD.
P3  the flat three-state law J/3: the Fourier matrix is an exact complex unitary lift; no real orthogonal lift exists
    (exhaustive over sign patterns of +-1/sqrt3 rows).
P4  the law (J - I)/2 on three states: realized by a bijection of V x H with |H| = 2 (so it is an OI visible law), and
    admits no unitary lift over R, C or H (zero pattern forces a nonzero inner product of two rows).
P5  pair flows and control: the Lie closure (real span, commutators) of the conjugates by all permutations of one pair
    generator, for D = 3, 4, 5:
      real rotation generator  R01 = E01 - E10            -> expect so(D), dimension D(D-1)/2
      complex drive generator  -i X01, X01 = E01 + E10    -> expect su(D), dimension D^2 - 1
    and the bipartite control: D = 2, drive + swap only.
P6  the no-control census cell's kinematic content: diagonal-preserving unitary conjugations; the Lie algebra generated by
    diagonal skew-Hermitian generators is abelian of dimension D, and no element moves a basis state to a superposition.
"""
import itertools
from fractions import Fraction
import sympy as sp

OUT = []


def rep(name, ok, detail=''):
    OUT.append(('PASS' if ok else 'FAIL', name, detail))
    print(('PASS ' if ok else 'FAIL ') + name + ('  ' + detail if detail else ''))


# ---- P1 --------------------------------------------------------------------------------------------------------
K = {'classical': lambda n: n, 'real': lambda n: n * (n + 1) // 2, 'complex': lambda n: n * n,
     'quaternionic': lambda n: n * (2 * n - 1)}
res = {}
for name, f in K.items():
    res[name] = all(f(n * m) == f(n) * f(m) for n in range(2, 9) for m in range(2, 9))
rep('P1 product rule K(NM)=K(N)K(M), N,M in 2..8', res == {'classical': True, 'real': False, 'complex': True,
                                                          'quaternionic': False}, str(res))
rep('P1 real deficit at 2x2: K(4)=10 vs K(2)^2=9 (real has MORE global params than local products)',
    K['real'](4) == 10 and K['real'](2) ** 2 == 9)
rep('P1 quaternionic mismatch at 2x2: K(4)=28 vs K(2)^2=36', K['quaternionic'](4) == 28 and K['quaternionic'](2) ** 2 == 36)

# ---- P2 --------------------------------------------------------------------------------------------------------
I2 = sp.eye(2)
sx = sp.Matrix([[0, 1], [1, 0]]); sz = sp.Matrix([[1, 0], [0, -1]]); sy = sp.Matrix([[0, -sp.I], [sp.I, 0]])
YY = sp.kronecker_product(sy, sy)
real_sym_basis = [I2, sx, sz]          # basis of real symmetric 2x2
orth = all(sp.simplify((sp.kronecker_product(a, b) * YY).trace()) == 0 for a in real_sym_basis for b in real_sym_basis)
rep('P2 s_y(x)s_y is real symmetric', YY == YY.T and all(sp.im(x) == 0 for x in YY))
rep('P2 s_y(x)s_y orthogonal to all 9 real-symmetric product observables', orth)
rhos = [(sp.kronecker_product(I2, I2) + s * YY) / 4 for s in (1, -1)]
psd = all(all(ev >= 0 for ev in r.eigenvals()) for r in rhos)
rep('P2 rho_+ != rho_- , both PSD real states, identical local statistics', rhos[0] != rhos[1] and psd and orth)
# control: over C the same pair is locally distinguishable (s_y is a complex local observable)
rep('P2 control: over C, tr((s_y(x)s_y) rho_+-) = +-1 distinguishes them',
    [sp.simplify((YY * r).trace()) for r in rhos] == [1, -1])

# ---- P3 --------------------------------------------------------------------------------------------------------
w = (-1 + sp.I * sp.sqrt(3)) / 2   # exp(2 pi i/3) in algebraic form: sympy does not simplify the exponential form
F = sp.Matrix(3, 3, lambda i, j: sp.expand(w ** (i * j))) / sp.sqrt(3)
unit = (F * F.H - sp.eye(3)).applyfunc(lambda x: sp.nsimplify(sp.expand(x))) == sp.zeros(3)
flat = all(sp.nsimplify(sp.expand(F[i, j] * sp.conjugate(F[i, j]))) == sp.Rational(1, 3) for i in range(3) for j in range(3))
rep('P3 Fourier F3 is unitary with |F|^2 = J/3 (complex lift)', unit and flat)
# real: rows are s/sqrt3 with s in {+-1}^3; two rows orthogonal iff their +-1 dot product is 0 -- impossible (odd)
signs = list(itertools.product((1, -1), repeat=3))
any_orth_pair = any(sum(a * b for a, b in zip(u, v)) == 0 for u in signs for v in signs)
rep('P3 no two {+-1}^3 vectors are orthogonal => no real orthogonal lift of J/3', not any_orth_pair)

# ---- P4 --------------------------------------------------------------------------------------------------------
# bijection on V x H, V = {0,1,2}, H = {0,1}: (j, h) -> (P_h(j), h) with P_0 = (0 1 2) cycle, P_1 = (0 2 1) cycle
P = {0: [1, 2, 0], 1: [2, 0, 1]}
step = {(j, h): (P[h][j], h) for j in range(3) for h in range(2)}
bij = len(set(step.values())) == 6
T = [[Fraction(sum(1 for h in range(2) if step[(j, h)][0] == i), 2) for j in range(3)] for i in range(3)]
target = [[Fraction(0) if i == j else Fraction(1, 2) for j in range(3)] for i in range(3)]
rep('P4 (J-I)/2 is the visible law of a bijection of V x H with uniform |H|=2', bij and T == target)
# zero pattern: U with |U_ij|^2 = T_ij has U_ii = 0; rows 0 and 1 have supports {1,2} and {0,2}, overlapping only at
# column 2, so <row0,row1> = U_02 conj(U_12) with |U_02| = |U_12| = 1/sqrt2 != 0  -- over any normed division algebra.
supp = [{j for j in range(3) if target[i][j] != 0} for i in range(3)]
single_overlap = all(len(supp[a] & supp[b]) == 1 for a in range(3) for b in range(3) if a < b)
rep('P4 every pair of rows overlaps in exactly one column => no unitary lift over R, C or H', single_overlap)

# ---- P5 --------------------------------------------------------------------------------------------------------
def E(D, a, b):
    M = sp.zeros(D); M[a, b] = 1; return M


def perm_matrix(D, p):
    M = sp.zeros(D)
    for j in range(D): M[p[j], j] = 1
    return M


def vec_real(M):
    """real coordinates of a complex matrix (re, im parts) -- for real-span rank"""
    out = []
    for x in M:
        x = sp.nsimplify(sp.expand(x))
        out += [sp.re(x), sp.im(x)]
    return out


def lie_closure_dim(gens, cap=200):
    basis, vecs = [], []

    def add(M):
        M = sp.expand(M)
        v = vec_real(M)
        test = sp.Matrix(vecs + [v]) if vecs else sp.Matrix([v])
        if test.rank() > len(vecs):
            vecs.append(v); basis.append(M); return True
        return False
    for g in gens: add(g)
    changed = True
    while changed and len(basis) < cap:
        changed = False
        cur = list(basis)
        for A in cur:
            for B in cur:
                if add(A * B - B * A): changed = True
    return len(basis)


for D in (3, 4, 5):
    perms = list(itertools.permutations(range(D)))
    R = E(D, 0, 1) - E(D, 1, 0)
    X = E(D, 0, 1) + E(D, 1, 0)
    gR = [perm_matrix(D, p) * R * perm_matrix(D, p).T for p in perms]
    gC = [perm_matrix(D, p) * (-sp.I * X) * perm_matrix(D, p).T for p in perms]
    dR, dC = lie_closure_dim(gR), lie_closure_dim(gC)
    rep('P5 D=%d real rotation + permutations: dim %d = so(D) %d' % (D, dR, D * (D - 1) // 2), dR == D * (D - 1) // 2)
    rep('P5 D=%d complex drive -iX + permutations: dim %d = su(D) %d' % (D, dC, D * D - 1), dC == D * D - 1)
# bipartite control D = 2: drive -iX and swap-conjugates only
X2 = sp.Matrix([[0, 1], [1, 0]]); S2 = sp.Matrix([[0, 1], [1, 0]])
d2 = lie_closure_dim([-sp.I * X2, S2 * (-sp.I * X2) * S2.T])
rep('P5 D=2 drive + swap: dim %d < su(2) 3 (the bipartite obstruction)' % d2, d2 < 3)

# ---- P6 --------------------------------------------------------------------------------------------------------
for D in (3, 4):
    gens = [sp.I * E(D, a, a) for a in range(D)]
    dD = lie_closure_dim(gens)
    rep('P6 D=%d diagonal skew-Hermitian generators: abelian, dim %d = D' % (D, dD), dD == D)

print('\nSUMMARY: %d PASS, %d FAIL' % (sum(o[0] == 'PASS' for o in OUT), sum(o[0] == 'FAIL' for o in OUT)))
