/-
  EQ-A candidate text — UNBUILT.  Never compiled (no local toolchain; Lean runs only in CI).  Not part of any round,
  not frozen, not governed.  Written against the vocabulary at bcbc516f:
    KInfFoundations (KF): IsEffectOn, certainFace, IsProperOn, IsBoundaryState (KF:130), SingletonFaces (KF:139),
      RelStrictConvex (KF:144), CentrallySymmetric (KF:160), eq_one_of_certain_of_not_boundary (KF:210),
      singletonFaces_of_relStrictConvex (KF:590)
    OrbitGeneration (OG): SharpSeed (OG:65), PreservesBody (OG:69), SeedOrbitAvailable (OG:74),
      BoundaryTransitive (OG:79), seedTransport (OG:49)
    TransitiveBody (TB): IsBodyGroup (TB:223), extreme_image (TB:246), isBoundaryState_of_extreme (TB:284),
      extreme_of_isBoundaryState_of_transitive (TB:290)
    DenseOrbit (DO): DenseBoundaryOrbit (DO:53)
    StageCompletion / CompletionAction: DirectedStages, Label, Prep, val, coord, OpDatum (CA:46), AffineRespect (CA:58),
      CompletionChart (CA:144), chartBody (CA:166), gen (CA:169), affineSpan_gen (CA:218), induced (CA:277),
      induced_gen (CA:281); OrbitNormalization: effR (ON:400)
  `Set.extremePoints` is used in the single-conclusion form the base uses (TB:246, TB:258): membership plus
  `∀ ⦃x₁⦄, x₁ ∈ A → ∀ ⦃x₂⦄, x₂ ∈ A → x ∈ openSegment ℝ x₁ x₂ → x₁ = x`.
-/
import OIBridge.KInfFoundations
import OIBridge.OrbitGeneration
import OIBridge.TransitiveBody
import OIBridge.DenseOrbit

namespace OIBridge
namespace ElementaryScope

open Set KInfFoundations OrbitGeneration TransitiveBody

variable {V : Type} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-! ### §A — the face generated by a state; the elementary scope; the localized principle -/

/-- The face of `Ω` generated by `m`: the states `z` beyond which `m` extends inside `Ω`. -/
def genFace (Ω : Set V) (m : V) : Set V :=
  {z ∈ Ω | ∃ ε : ℝ, 0 < ε ∧ m + ε • (m - z) ∈ Ω}

/-- **ELEM₂.** The body is generated, as a face, by two of its pure states: two distinct extreme points whose
midpoint is a state and not a boundary state. -/
def Elem2 (Ω : Set V) : Prop :=
  ∃ x ∈ Ω.extremePoints ℝ, ∃ y ∈ Ω.extremePoints ℝ, x ≠ y ∧
    midpoint ℝ x y ∈ Ω ∧ ¬ IsBoundaryState Ω (midpoint ℝ x y)

/-- **GEOM₂** (body form of the localized K∞-Geom). The face generated by any two distinct pure states is
relatively strictly convex. -/
def PairFaceStrictConvex (Ω : Set V) : Prop :=
  ∀ x ∈ Ω.extremePoints ℝ, ∀ y ∈ Ω.extremePoints ℝ, x ≠ y →
    RelStrictConvex (genFace Ω (midpoint ℝ x y))

/-- **SF₂** (effect form). Inside the face generated by two distinct pure states, every available effect that is
proper on that face is certain on at most one state. -/
def PairFaceSingleton (Ω : Set V) (avail : Set (V →ᵃ[ℝ] ℝ)) : Prop :=
  ∀ x ∈ Ω.extremePoints ℝ, ∀ y ∈ Ω.extremePoints ℝ, x ≠ y →
    SingletonFaces (genFace Ω (midpoint ℝ x y)) avail

/-- Transitivity on pure states (Masanes–Müller's "symmetry"). -/
def ExtremeTransitive (Ω : Set V) (G : Set (V ≃ᵃ[ℝ] V)) : Prop :=
  ∀ x ∈ Ω.extremePoints ℝ, ∀ y ∈ Ω.extremePoints ℝ, ∃ g ∈ G, g x = y

/-- Dense orbits on pure states. -/
def ExtremeDense (Ω : Set V) (G : Set (V ≃ᵃ[ℝ] V)) : Prop :=
  ∀ x ∈ Ω.extremePoints ℝ, ∀ y ∈ Ω.extremePoints ℝ, y ∈ closure ((fun g : V ≃ᵃ[ℝ] V => g x) '' G)

/-! ### §B — the elementary body is relatively strictly convex (Theorem B) -/

theorem genFace_subset (Ω : Set V) (m : V) : genFace Ω m ⊆ Ω := fun _ hz => hz.1

/-- When `m` is a state and not a boundary state, the face it generates is the whole body. -/
theorem genFace_eq_of_not_boundary {Ω : Set V} {m : V} (hm : m ∈ Ω) (h : ¬ IsBoundaryState Ω m) :
    genFace Ω m = Ω := by
  refine Set.Subset.antisymm (genFace_subset Ω m) (fun z hz => ⟨hz, ?_⟩)
  by_contra hno
  push_neg at hno
  exact h ⟨hm, z, hz, fun ε hε hmem => hno ε hε hmem⟩

/-- **Theorem B.** ELEM₂ and GEOM₂ make the body relatively strictly convex. -/
theorem relStrictConvex_of_elem2 {Ω : Set V} (hE : Elem2 Ω) (hG : PairFaceStrictConvex Ω) :
    RelStrictConvex Ω := by
  obtain ⟨x, hx, y, hy, hxy, hm, hnb⟩ := hE
  have h := hG x hx y hy hxy
  rwa [genFace_eq_of_not_boundary hm hnb] at h

/-- The effect form, with supporting-effect completeness on the body, gives the same conclusion
(Lemma C, KF:575, applied to the body, which is its own pair face). -/
theorem relStrictConvex_of_elem2_singleton {Ω : Set V} {avail : Set (V →ᵃ[ℝ] ℝ)} (hconv : Convex ℝ Ω)
    (hE : Elem2 Ω) (hSF : PairFaceSingleton Ω avail) (hSEC : SupportingEffectComplete Ω avail) :
    RelStrictConvex Ω := by
  obtain ⟨x, hx, y, hy, hxy, hm, hnb⟩ := hE
  have h := hSF x hx y hy hxy
  rw [genFace_eq_of_not_boundary hm hnb] at h
  exact relStrictConvex_of_supporting_singleton hconv hSEC h

/-! ### §C — K∞-Trans = RelStrictConvex + transitivity on pure states (Theorem A and its converse) -/

/-- A boundary state of a relatively strictly convex body is extreme. -/
theorem extreme_of_isBoundaryState_of_relStrictConvex {Ω : Set V} (h : RelStrictConvex Ω) {x : V}
    (hx : IsBoundaryState Ω x) : x ∈ Ω.extremePoints ℝ := by
  refine ⟨hx.1, fun x₁ hx₁ x₂ hx₂ hseg => ?_⟩
  by_cases h12 : x₁ = x₂
  · subst h12
    rw [openSegment_same] at hseg
    exact (Set.mem_singleton_iff.mp hseg).symm
  · obtain ⟨a, b, ha, hb, hab, hab'⟩ := hseg
    exact absurd (hab' ▸ hx) (h x₁ hx₁ x₂ hx₂ h12 a b ha hb hab).2

/-- **Theorem A (←).** Relative strict convexity and transitivity on pure states give boundary transitivity. -/
theorem boundaryTransitive_of_relStrictConvex {Ω : Set V} {G : Set (V ≃ᵃ[ℝ] V)} (h : RelStrictConvex Ω)
    (hT : ExtremeTransitive Ω G) : BoundaryTransitive Ω G :=
  fun x y hx hy => hT x (extreme_of_isBoundaryState_of_relStrictConvex h hx) y
    (extreme_of_isBoundaryState_of_relStrictConvex h hy)

/-- **Theorem A, dense form (←).** -/
theorem denseBoundaryOrbit_of_relStrictConvex {Ω : Set V} {G : Set (V ≃ᵃ[ℝ] V)} (h : RelStrictConvex Ω)
    (hT : ExtremeDense Ω G) : DenseOrbit.DenseBoundaryOrbit Ω G :=
  fun x y hx hy => hT x (extreme_of_isBoundaryState_of_relStrictConvex h hx) y
    (extreme_of_isBoundaryState_of_relStrictConvex h hy)

/-- **Theorem A (→), first half.** Under TRB-1's hypotheses boundary transitivity gives relative strict
convexity (boundary purity, TB:290). -/
theorem relStrictConvex_of_boundaryTransitive [Nontrivial V] {Ω : Set V} (hc : IsCompact Ω)
    (hconv : Convex ℝ Ω) (hi : (interior Ω).Nonempty) {G : Set (V ≃ᵃ[ℝ] V)} (hG : PreservesBody Ω G)
    (hT : BoundaryTransitive Ω G) : RelStrictConvex Ω := by
  intro x hx y hy hxy a b ha hb hab
  refine ⟨hconv hx hy ha.le hb.le hab, fun hbd => ?_⟩
  have hext := extreme_of_isBoundaryState_of_transitive hc hconv hi hG hT hbd
  have h1 : x = a • x + b • y := hext.2 hx hy ⟨a, b, ha, hb, hab, rfl⟩
  have h2 : y = a • x + b • y := hext.2 hy hx (by rw [openSegment_symm]; exact ⟨a, b, ha, hb, hab, rfl⟩)
  exact hxy (h1.trans h2.symm)

/-- **Theorem A (→), second half.** -/
theorem extremeTransitive_of_boundaryTransitive [Nontrivial V] {Ω : Set V} (hconv : Convex ℝ Ω)
    (hi : (interior Ω).Nonempty) {G : Set (V ≃ᵃ[ℝ] V)} (hT : BoundaryTransitive Ω G) :
    ExtremeTransitive Ω G :=
  fun x hx y hy => hT x y (isBoundaryState_of_extreme hconv hi hx) (isBoundaryState_of_extreme hconv hi hy)

/-! ### §D — ELEM₂ on centrally symmetric bodies -/

/-- Every centrally symmetric body with a pure state other than its centre satisfies ELEM₂. -/
theorem elem2_of_centrallySymmetric {Ω : Set V} {c : V} (hc : c ∈ Ω) (hcs : CentrallySymmetric Ω c)
    {x : V} (hx : x ∈ Ω.extremePoints ℝ) (hxc : x ≠ c) : Elem2 Ω := by
  -- y = c + (c - x) is the image of x under the point reflection, an affine automorphism of Ω (its own inverse);
  -- extreme_image (TB:246) carries extremality; midpoint ℝ x y = c; and c + 1 • (c - z) ∈ Ω for every z ∈ Ω.
  sorry -- UNBUILT: routine (point reflection as an AffineEquiv, `extreme_image`, `midpoint` algebra)

/-! ### §E — QA2: label duals give seed-orbit availability on the chart -/

section LabelDual

open StageCompletion CompletionAction OrbitNormalization

variable {D : DirectedStages} (C : CompletionChart D)

/-- SA-LEDGER P-A (not landed): the operation pulls every stage effect back to a stage effect. -/
def LabelDual (T : OpDatum D) (σ : Label D → Label D) : Prop :=
  ∀ a x, T.τ x a = val D (σ a) x

/-- The stage effects read in the chart. -/
def chartEffects : Set ((Fin C.d → ℝ) →ᵃ[ℝ] (ℝ)) :=
  Set.range fun a : Label D => effR C.L C.p0 (coord D a)

/-- **Pullback of a stage effect along a label-dual datum is a stage effect** (as affine maps of the chart:
they agree on the generators `gen C x`, which affinely span the chart, CA:218). -/
theorem pullback_eq_of_labelDual {T : OpDatum D} (hT : AffineRespect T) {σ : Label D → Label D}
    (hσ : LabelDual T σ) (a : Label D) :
    (effR C.L C.p0 (coord D a)).comp (induced C T hT) = effR C.L C.p0 (coord D (σ a)) := by
  sorry -- UNBUILT: ext on `Set.range (gen C)` via `induced_gen` (CA:281), `hσ`, chart/coordsOf inverse on the body,
        -- then equality of affine maps agreeing on an affinely spanning set (`affineSpan_gen`, CA:218)

/-- **V4 from label duals.** If the inverse of every member of `G` is induced by a label-dual datum, every transport
of a stage-effect seed is a stage effect. -/
theorem seedOrbitAvailable_of_labelDual {G : Set ((Fin C.d → ℝ) ≃ᵃ[ℝ] (Fin C.d → ℝ))}
    (hG : ∀ g ∈ G, ∃ (T : OpDatum D) (hT : AffineRespect T) (σ : Label D → Label D),
      LabelDual T σ ∧ (g.symm : (Fin C.d → ℝ) →ᵃ[ℝ] (Fin C.d → ℝ)) = induced C T hT)
    (a : Label D) :
    SeedOrbitAvailable G (effR C.L C.p0 (coord D a)) (chartEffects C) := by
  intro g hg
  obtain ⟨T, hT, σ, hσ, hg'⟩ := hG g hg
  refine ⟨σ a, ?_⟩
  show effR C.L C.p0 (coord D (σ a)) = (effR C.L C.p0 (coord D a)).comp g.symm.toAffineMap
  rw [← pullback_eq_of_labelDual C hT hσ a]
  congr 1
  exact hg'.symm

end LabelDual

/-! ### §F — QA3: operational compactness gives finite rank under the package (Theorem R) -/

/-- **Theorem R.** On a compact convex body that is relatively strictly convex and has two points, a body group with
a dense boundary orbit and a sharp seed whose transports are available among 1-Lipschitz effects force a
finite-dimensional affine span.  Written proof in RESULT.md §4 (Kakutani's fixed-point theorem for equicontinuous
affine groups, Arzelà–Ascoli, Riesz). -/
theorem finiteRank_of_isCompact {Ω : Set V} (hconv : Convex ℝ Ω) (hc : IsCompact Ω) (hRSC : RelStrictConvex Ω)
    (h2 : ∃ x ∈ Ω, ∃ y ∈ Ω, x ≠ y) {G : Set (V ≃ᵃ[ℝ] V)} (hG : IsBodyGroup Ω G)
    (hD : DenseOrbit.DenseBoundaryOrbit Ω G) {r : V →ᵃ[ℝ] ℝ} (hr : SharpSeed Ω r)
    {avail : Set (V →ᵃ[ℝ] ℝ)} (hV4 : SeedOrbitAvailable G r avail)
    (hLip : ∀ e ∈ avail, LipschitzWith 1 e) :
    StageCompletion.FiniteRank Ω := by
  sorry -- UNBUILT: Kakutani's fixed-point theorem for equicontinuous affine groups is not known to be in Mathlib at
        -- the pinned tag; the other two ingredients are (`FiniteDimensional.of_isCompact_closedBall₀`, Arzelà–Ascoli)

end ElementaryScope
end OIBridge
