#!/usr/bin/env python3
"""EQ-A, QA1 -- exact controls for the elementary-system predicate ELEM2 and the localized geometric principle GEOM2.

Definitions checked here (field-neutral; stated on a convex body Omega, read in Omega alone):
  boundary state   x in Om and some y in Om with x + eps (x - y) not in Om for every eps > 0      (KF:130)
  genFace(Om, m)   {z in Om : exists eps > 0, m + eps (m - z) in Om}   (the face of Om generated by m)
  ELEM2(Om)        two distinct extreme points x, y of Om whose midpoint is in Om and not a boundary state
  GEOM2(Om)        for all distinct extreme x, y: genFace(Om, (x+y)/2) is relatively strictly convex (KF:144)
  SF2 (effect form) for all distinct extreme x, y and every available effect e proper on F = genFace(Om,(x+y)/2),
                   the certain face of e inside F has at most one state

Exact arithmetic only: fractions.Fraction, Gaussian rationals GQ, Q(sqrt5).  Written arguments are printed as NOTE
lines and are not counted as checks.  Every check is tagged witness / identity / enumerate / sample.
Run:  PYTHONDONTWRITEBYTECODE=1 python3 -I qa1_controls.py
"""
from fractions import Fraction as Fr
from itertools import permutations, product
import sys

N_CHECKS = {'witness': 0, 'identity': 0, 'enumerate': 0, 'sample': 0}
FAILED = []


def chk(name, ok, kind, detail=''):
    assert kind in N_CHECKS
    N_CHECKS[kind] += 1
    tag = 'PASS' if ok else 'FAIL'
    if not ok:
        FAILED.append(name)
    print('%s [%s] %s%s' % (tag, kind, name, ('  -- ' + detail) if detail else ''))


def note(name, detail):
    print('NOTE [written] %s  -- %s' % (name, detail))


def section(title):
    print('\n=== %s ===' % title)


# ------------------------------------------------------------------------------------------------ exact fields ---
class GQ:
    """Gaussian rational a + b i, a, b in Q."""
    __slots__ = ('re', 'im')

    def __init__(self, re, im=0):
        if isinstance(re, GQ):
            self.re, self.im = re.re, re.im
        else:
            self.re, self.im = Fr(re), Fr(im)

    def _c(self, o):
        return o if isinstance(o, GQ) else GQ(o)

    def __add__(self, o):
        o = self._c(o); return GQ(self.re + o.re, self.im + o.im)
    __radd__ = __add__

    def __sub__(self, o):
        o = self._c(o); return GQ(self.re - o.re, self.im - o.im)

    def __rsub__(self, o):
        return self._c(o) - self

    def __neg__(self):
        return GQ(-self.re, -self.im)

    def __mul__(self, o):
        o = self._c(o); return GQ(self.re * o.re - self.im * o.im, self.re * o.im + self.im * o.re)
    __rmul__ = __mul__

    def conj(self):
        return GQ(self.re, -self.im)

    def __truediv__(self, o):
        o = self._c(o)
        n = o.re * o.re + o.im * o.im
        if n == 0:
            raise ZeroDivisionError
        q = self * o.conj()
        return GQ(q.re / n, q.im / n)

    def __eq__(self, o):
        o = self._c(o); return self.re == o.re and self.im == o.im

    def __hash__(self):
        return hash((self.re, self.im))

    def is_zero(self):
        return self.re == 0 and self.im == 0

    def __repr__(self):
        return '%s%+si' % (self.re, self.im) if self.im else '%s' % self.re


class Q5:
    """a + b sqrt5 with a, b rational; exact sign."""
    __slots__ = ('a', 'b')

    def __init__(s, a, b=0):
        if isinstance(a, Q5):
            s.a, s.b = a.a, a.b
        else:
            s.a, s.b = Fr(a), Fr(b)

    def _c(s, o):
        return o if isinstance(o, Q5) else Q5(o)

    def __add__(s, o):
        o = s._c(o); return Q5(s.a + o.a, s.b + o.b)
    __radd__ = __add__

    def __neg__(s):
        return Q5(-s.a, -s.b)

    def __sub__(s, o):
        return s + (-s._c(o))

    def __rsub__(s, o):
        return s._c(o) - s

    def __mul__(s, o):
        o = s._c(o); return Q5(s.a * o.a + 5 * s.b * o.b, s.a * o.b + s.b * o.a)
    __rmul__ = __mul__

    def inv(s):
        n = s.a * s.a - 5 * s.b * s.b
        return Q5(s.a / n, -s.b / n)

    def __truediv__(s, o):
        return s * s._c(o).inv()

    def sign(s):
        # sign of a + b sqrt5 exactly
        if s.b == 0:
            return (s.a > 0) - (s.a < 0)
        if s.a == 0:
            return (s.b > 0) - (s.b < 0)
        if (s.a > 0) == (s.b > 0):
            return 1 if s.a > 0 else -1
        # opposite signs: compare a^2 with 5 b^2
        d = s.a * s.a - 5 * s.b * s.b
        if d == 0:
            return 0
        return ((1 if s.a > 0 else -1) if d > 0 else (1 if s.b > 0 else -1))

    def __eq__(s, o):
        o = s._c(o); return s.a == o.a and s.b == o.b

    def __hash__(s):
        return hash((s.a, s.b))

    def is_zero(s):
        return s.a == 0 and s.b == 0

    def __repr__(s):
        return '(%s%+s*sqrt5)' % (s.a, s.b)


def iszero(x):
    return x.is_zero() if hasattr(x, 'is_zero') else x == 0


# ----------------------------------------------------------------------------------- generic exact linear algebra ---
def mat_copy(M):
    return [list(r) for r in M]


def det(M):
    A = mat_copy(M); n = len(A); d = 1; one = 1
    for c in range(n):
        p = next((r for r in range(c, n) if not iszero(A[r][c])), None)
        if p is None:
            return A[0][0] * 0 if n else one
        if p != c:
            A[c], A[p] = A[p], A[c]; d = -d
        d = d * A[c][c]
        for r in range(c + 1, n):
            f = A[r][c] / A[c][c]
            A[r] = [A[r][k] - f * A[c][k] for k in range(n)]
    return d


def rref(M):
    A = mat_copy(M); rows = len(A); cols = len(A[0]) if rows else 0; piv = []; r = 0
    for c in range(cols):
        p = next((i for i in range(r, rows) if not iszero(A[i][c])), None)
        if p is None:
            continue
        A[r], A[p] = A[p], A[r]
        pv = A[r][c]
        A[r] = [v / pv for v in A[r]]
        for i in range(rows):
            if i != r and not iszero(A[i][c]):
                f = A[i][c]
                A[i] = [A[i][k] - f * A[r][k] for k in range(cols)]
        piv.append(c); r += 1
        if r == rows:
            break
    return A, piv


def rank(M):
    return len(rref(M)[1]) if M and M[0] else 0


def nullspace(M, zero, one):
    A, piv = rref(M); cols = len(M[0]); free = [c for c in range(cols) if c not in piv]; basis = []
    for f in free:
        v = [zero] * cols; v[f] = one
        for i, pc in enumerate(piv):
            v[pc] = -A[i][f]
        basis.append(v)
    return basis


def matmul(A, B):
    return [[sum((A[i][k] * B[k][j] for k in range(len(B))), A[0][0] * 0) for j in range(len(B[0]))]
            for i in range(len(A))]


def ctrans(A):
    return [[A[j][i].conj() for j in range(len(A))] for i in range(len(A[0]))]


def madd(A, B, a=1, b=1):
    return [[A[i][j] * a + B[i][j] * b for j in range(len(A[0]))] for i in range(len(A))]


def eye(n, one):
    return [[one if i == j else one * 0 for j in range(n)] for i in range(n)]


def principal_minors_nonneg(H):
    """Hermitian H (GQ entries) is PSD iff every principal minor is >= 0 (each is real)."""
    n = len(H)
    for mask in range(1, 1 << n):
        idx = [i for i in range(n) if mask >> i & 1]
        d = det([[H[i][j] for j in idx] for i in idx])
        d = GQ(d)
        if d.im != 0 or d.re < 0:
            return False
    return True


def proj(v):
    """Rank-one projector v v^dag / (v^dag v) over Q(i)."""
    n = sum((x.conj() * x for x in v), GQ(0))
    return [[v[i] * v[j].conj() / n for j in range(len(v))] for i in range(len(v))]


def span_projector(vs):
    """Orthogonal projector onto span(vs): B (B^dag B)^-1 B^dag, exact over Q(i)."""
    B = [[vs[j][i] for j in range(len(vs))] for i in range(len(vs[0]))]   # columns = vs
    G = matmul(ctrans(B), B)
    k = len(G)
    aug = [G[i] + eye(k, GQ(1))[i] for i in range(k)]
    R, piv = rref(aug)
    Ginv = [row[k:] for row in R]
    return matmul(matmul(B, Ginv), ctrans(B))


def hdot(u, v):
    return sum((u[i].conj() * v[i] for i in range(len(u))), GQ(0))


def interior_certificate(m, PK):
    """Find a rational lam > 0 with m - lam*PK PSD (exact).  Then m is not a boundary state of the face of states
    supported on range(PK): every state z of that face has z <= PK, and m + eps (m - z) >= ((1+eps) lam - eps) PK >= 0
    for 0 < eps <= lam/(1-lam).  Returns lam or None."""
    lam = Fr(1, 2)
    for _ in range(40):
        if principal_minors_nonneg(madd(m, PK, 1, -GQ(lam))):
            return lam
        lam /= 2
    return None


# =================================================================================================================
section('A. Complex quantum theory: ELEM2 selects n <= 2; GEOM2 / SF2 hold at every n (the converse test)')

note('A.ELEM2_fails_n_ge_3',
     'for pure x = |v><v|, y = |w><w| in M_n(C), m = (x+y)/2 has rank <= 2 < n; a kernel vector chi of m gives the '
     'state z = |chi><chi|/<chi|chi> with <chi|(m + eps(m - z))|chi> = -eps<chi|chi> < 0 for every eps > 0, so m is a '
     'boundary state.  Hence ELEM2 fails for every n >= 3 and every pair; checked exactly on the instances below.')
note('A.GEOM2_holds_all_n',
     'genFace(D_n, m) = {states supported on K = span(v, w)}, dim K = 2; for an effect 0 <= E <= I and rho supported '
     'on K: tr(E rho) = 1 iff supp rho is in K cap ker(I - E).  dim(K cap ker(I-E)) is 0 or 1 (certain face empty or '
     'one pure state) or 2 (E identically 1 on the face, i.e. not proper on it).  So SF2 holds for every effect, every '
     'pair face, every n; and since a midpoint of two distinct states on a 2-dim space has rank 2 (full on K), every '
     'pair face is relatively strictly convex (GEOM2).  Checked exactly on the instances below.')

I = GQ(0, 1)
z0, o1 = GQ(0), GQ(1)


def vec(*xs):
    return [GQ(x) if not isinstance(x, GQ) else x for x in xs]


# --- the qubit: ELEM2 holds
x, y = proj(vec(1, 0)), proj(vec(0, 1))
m = madd(x, y, Fr(1, 2), Fr(1, 2))
lam = interior_certificate(m, eye(2, o1))
chk('qubit.ELEM2', lam is not None and lam > 0 and x != y, 'witness',
    'm = (|0><0| + |1><1|)/2 >= %s I: not a boundary state of the Bloch ball; |0>,|1> are pure' % lam)
# qubit SF2 on its only pair face (the whole ball): every effect: dim(K cap ker(I-E)) <= 1 unless E = I
qubit_effects = [proj(vec(1, 0)), proj(vec(1, 1)), proj(vec(1, I)), proj(vec(3, 4)),
                 [[GQ(Fr(3, 4)), GQ(Fr(1, 4))], [GQ(Fr(1, 4)), GQ(Fr(1, 2))]], eye(2, o1)]
ok = True
for E in qubit_effects:
    IE = madd(eye(2, o1), E, 1, -1)
    kd = len(nullspace(IE, z0, o1))
    proper = not all(iszero(IE[i][j]) for i in range(2) for j in range(2))
    ok = ok and ((kd <= 1) if proper else (kd == 2))
chk('qubit.SF2', ok, 'sample', 'certain face of every sampled proper qubit effect is at most one pure state')

# --- qutrit / ququart: ELEM2 fails at every sampled pure pair; GEOM2 holds on every sampled pair face
pairs3 = [((1, 0, 0), (0, 1, 0)), ((1, 0, 0), (1, 1, 1)), ((1, I, 0), (0, 1, -I)), ((1, 2, 0), (2, -1, 1)),
          ((3, 0, 4), (0, 5, 0)), ((1, 1 + I, 2), (2 - I, 0, 1))]
pairs4 = [((1, 0, 0, 0), (0, 1, 0, 0)), ((1, 1, 1, 1), (1, -1, I, -I)), ((1, 2, 0, I), (0, 1, 1, -1))]


def check_pair(n, v, w, tag):
    v, w = vec(*v), vec(*w)
    xv, yw = proj(v), proj(w)
    m = madd(xv, yw, Fr(1, 2), Fr(1, 2))
    r = rank(m)
    ker = nullspace(m, z0, o1)
    chi = ker[0]
    mchi = hdot(chi, [sum((m[i][j] * chi[j] for j in range(n)), z0) for i in range(n)])
    cc = hdot(chi, chi)
    # <chi|(m + eps(m - z))|chi> = (1+eps)<chi|m|chi> - eps <chi|chi>  with z = |chi><chi|/<chi|chi>
    chk('%s.ELEM2_fails' % tag, r == 2 and mchi.is_zero() and cc.re > 0 and cc.im == 0 and xv != yw, 'witness',
        'rank m = 2 < %d; <chi|m|chi> = 0, <chi|chi> = %s > 0: <chi|(m + eps(m - z))|chi> = -eps*%s < 0' % (n, cc, cc))
    PK = span_projector([v, w])
    lam = interior_certificate(m, PK)
    chk('%s.pairface_relint' % tag, lam is not None, 'witness',
        'm >= %s P_K: the midpoint is not a boundary state of its pair face (the face is the Bloch ball of K)' % lam)
    # strict convexity of the pair face on sampled pairs of distinct states inside it (pure and mixed)
    samples = [xv, yw, proj([v[i] + w[i] for i in range(n)]), proj([v[i] + I * w[i] for i in range(n)]),
               madd(xv, yw, Fr(2, 3), Fr(1, 3)), madd(proj([v[i] - w[i] for i in range(n)]), xv, Fr(1, 2), Fr(1, 2))]
    good = True
    for a in range(len(samples)):
        for b in range(a + 1, len(samples)):
            if samples[a] == samples[b]:
                continue
            mid = madd(samples[a], samples[b], Fr(1, 2), Fr(1, 2))
            good = good and interior_certificate(mid, PK) is not None
    chk('%s.GEOM2_sampled' % tag, good, 'sample',
        'every midpoint of two distinct sampled states of the pair face dominates lam P_K, lam > 0: relatively interior')


for k, (v, w) in enumerate(pairs3):
    check_pair(3, v, w, 'qutrit%d' % k)
for k, (v, w) in enumerate(pairs4):
    check_pair(4, v, w, 'ququart%d' % k)

# --- the census counterexample P = diag(1,1,0): global SF fails; SF2 holds on every pair face
P = [[o1, z0, z0], [z0, o1, z0], [z0, z0, z0]]
e0, e1, e2 = vec(1, 0, 0), vec(0, 1, 0), vec(0, 0, 1)


def tr(A, B):
    return sum((A[i][j] * B[j][i] for i in range(len(A)) for j in range(len(A))), z0)


chk('census.global_SF_fails', tr(P, proj(e0)) == 1 and tr(P, proj(e1)) == 1 and tr(P, proj(e2)) == 0, 'witness',
    'P certain on |0>,|1> and 0 at |2>: proper with a two-state certain face (kn-elementary-carrier-census section 4)')
mid01 = madd(proj(e0), proj(e1), Fr(1, 2), Fr(1, 2))
chk('census.midpoint_boundary', tr(mid01, proj(e2)) == 0, 'witness',
    '<2|m|2> = 0, so with z = |2><2| the extension m + eps(m - z) has <2|.|2> = -eps < 0: m is a boundary state')
IP = madd(eye(3, o1), P, 1, -1)


def certain_dim_in_face(E, K):
    """dim(K cap ker(I - E)): intersect span(K) with the kernel of I - E."""
    IE = madd(eye(len(E), o1), E, 1, -1)
    # vectors a*k1 + b*k2 with (I-E)(a k1 + b k2) = 0: solve for (a, b)
    cols = [[sum((IE[i][j] * kv[j] for j in range(len(E))), z0) for i in range(len(E))] for kv in K]
    Mab = [[cols[c][i] for c in range(len(K))] for i in range(len(E))]
    return len(K) - rank(Mab)


for nm, K in (('F(0,1)', [e0, e1]), ('F(0,2)', [e0, e2]), ('F(0,psi)', [e0, vec(1, 1, 1)]),
              ('F(1,0+2i)', [e1, vec(1, 0, 2 * I)])):
    d_ = certain_dim_in_face(P, K)
    verdict = 'not proper on the face (identically 1)' if d_ == 2 else 'certain face = %d pure state(s)' % d_
    chk('census.SF2.%s' % nm, d_ in (0, 1, 2), 'witness', 'dim(K cap ker(I-P)) = %d: %s' % (d_, verdict))
chk('census.SF2.F01_not_proper', certain_dim_in_face(P, [e0, e1]) == 2, 'witness',
    'on the pair face of |0>,|1> the census effect is the unit: no SF2 obligation, the census counterexample is defused')
chk('census.SF2.F02_singleton', certain_dim_in_face(P, [e0, e2]) == 1, 'witness',
    'on the pair face of |0>,|2> the census effect is proper and certain on |0><0| only')

# --- the real qutrit: same rank argument; pair faces are real disks
rpairs = [((1, 0, 0), (0, 1, 0)), ((1, 2, 2), (2, -2, 1)), ((3, 4, 0), (0, 0, 1))]
for k, (v, w) in enumerate(rpairs):
    v_, w_ = vec(*v), vec(*w)
    m = madd(proj(v_), proj(w_), Fr(1, 2), Fr(1, 2))
    ker = nullspace(m, z0, o1)
    chi = ker[0]
    real = all(c.im == 0 for c in chi)
    mchi = hdot(chi, [sum((m[i][j] * chi[j] for j in range(3)), z0) for i in range(3)])
    chk('rqutrit%d.ELEM2_fails' % k, rank(m) == 2 and real and mchi.is_zero(), 'witness',
        'a real kernel vector of the rank-2 midpoint exists: boundary state of the real qutrit')
note('rqutrit.GEOM2', 'pair faces are the real 2x2 density matrices on span(v, w): a disk, strictly convex')

# =================================================================================================================
section('B. Foils: which bodies does ELEM2 & GEOM2 exclude?')

note('B.CS_lemma', 'if Om is centrally symmetric about c in Om and x is an extreme point, x != c, then y = 2c - x is '
     'extreme and c = midpoint(x, y) is not a boundary state: for z in Om, c + 1*(c - z) = 2c - z is in Om by symmetry. '
     'So ELEM2 holds on every centrally symmetric body with two points (bit, square, hexagon, torus, Stiefel, disk, '
     'balls, the l2 ball).')
note('B.polytope_lemma', 'a polytope of dimension >= 2 is not relatively strictly convex (an edge midpoint is a '
     'boundary state), so it violates GEOM2 as soon as it satisfies ELEM2; a segment satisfies both.')


def in_H(H, p, strict=False):
    for (a, b) in H:
        s = sum((ai * pi for ai, pi in zip(a, p)), type(b)(0) if not isinstance(b, int) else 0) - b
        sg = s.sign() if hasattr(s, 'sign') else ((s > 0) - (s < 0))
        if sg > 0 or (strict and sg == 0):
            return False
    return True


def H_of_polygon(V, F=Fr):
    """facets a.x <= b of a convex polygon given in counterclockwise order"""
    H = []
    n = len(V)
    for i in range(n):
        p, q = V[i], V[(i + 1) % n]
        a = (q[1] - p[1], p[0] - q[0])            # outward normal for ccw order
        b = a[0] * p[0] + a[1] * p[1]
        H.append((a, b))
    return H


def boundary_witness_H(H, mpt, ypt):
    """m + eps(m - y) leaves Om for all eps > 0 iff some facet is tight at m and strictly separates y (a.y < b)."""
    for (a, b) in H:
        am = sum((ai * mi for ai, mi in zip(a, mpt)), a[0] * 0) - b
        ay = sum((ai * yi for ai, yi in zip(a, ypt)), a[0] * 0) - b
        sm = am.sign() if hasattr(am, 'sign') else ((am > 0) - (am < 0))
        sy = ay.sign() if hasattr(ay, 'sign') else ((ay > 0) - (ay < 0))
        if sm == 0 and sy < 0:
            return True
    return False


def half(p, q):
    return tuple((a + b) / 2 for a, b in zip(p, q))


# --- square gbit
SQ = [(Fr(1), Fr(1)), (Fr(-1), Fr(1)), (Fr(-1), Fr(-1)), (Fr(1), Fr(-1))]
HSQ = H_of_polygon(SQ)
chk('square.ELEM2', in_H(HSQ, half(SQ[0], SQ[2]), strict=True), 'witness',
    'opposite vertices (1,1), (-1,-1): midpoint 0 strictly inside every facet, so not a boundary state')
chk('square.GEOM2_fails', boundary_witness_H(HSQ, half(SQ[0], SQ[3]), (Fr(0), Fr(0))), 'witness',
    'the pair face of (1,1), (-1,-1) is the square; (1,1), (1,-1) are distinct and their midpoint (1,0) is a boundary '
    'state (facet x <= 1 tight at it, strict at 0): not relatively strictly convex')

# --- affine-regular hexagon (rational)
HEX = [(Fr(1), Fr(0)), (Fr(1), Fr(1)), (Fr(0), Fr(1)), (Fr(-1), Fr(0)), (Fr(-1), Fr(-1)), (Fr(0), Fr(-1))]
HHX = H_of_polygon(HEX)
chk('hexagon.ELEM2', in_H(HHX, half(HEX[0], HEX[3]), strict=True), 'witness', 'opposite vertices: midpoint interior')
chk('hexagon.GEOM2_fails', boundary_witness_H(HHX, half(HEX[0], HEX[1]), (Fr(0), Fr(0))), 'witness',
    'edge midpoint is a boundary state of the (whole-body) pair face')

# --- regular pentagon (affine-regular, Q(sqrt5)); not centrally symmetric
c1 = Q5(Fr(-1, 4), Fr(1, 4)); c2 = Q5(Fr(-1, 4), Fr(-1, 4)); s2r = Q5(Fr(-1, 2), Fr(1, 2))
PEN = [(Q5(1), Q5(0)), (c1, Q5(1)), (c2, s2r), (c2, -s2r), (c1, Q5(-1))]
rec = all(PEN[(k + 1) % 5][j] + PEN[(k - 1) % 5][j] == 2 * c1 * PEN[k][j] for k in range(5) for j in range(2))
chk('pentagon.affine_regular', rec, 'identity', 'P_{k+1} + P_{k-1} = 2cos72 P_k: a linear image of the regular pentagon')
HPE = H_of_polygon(PEN)
chk('pentagon.ccw_convex', all(in_H(HPE, p) for p in PEN) and
    all(not in_H(HPE, PEN[i], strict=True) for i in range(5)), 'enumerate', 'every vertex on the boundary, none outside')
chk('pentagon.ELEM2', in_H(HPE, half(PEN[0], PEN[2]), strict=True), 'witness',
    'vertices 0 and 2 (non-adjacent): the midpoint of the diagonal is strictly inside every facet')
cen = (sum((p[0] for p in PEN), Q5(0)) / 5, sum((p[1] for p in PEN), Q5(0)) / 5)
chk('pentagon.GEOM2_fails', boundary_witness_H(HPE, half(PEN[0], PEN[1]), cen), 'witness',
    'edge midpoint of [v0, v1] is a boundary state (facet tight there, strict at the centroid)')

# --- classical bit [-1, 1]
chk('bit.ELEM2', all(-1 <= -e * t <= 1 for e in (Fr(1, 10), Fr(1, 2), Fr(1)) for t in (Fr(-1), Fr(0), Fr(1))),
    'sample', 'm = 0: 0 + eps(0 - z) = -eps z stays in [-1,1] for eps <= 1 (CS lemma); endpoints are extreme')
note('bit.GEOM2', 'the segment is strictly convex (kernel: relStrictConvex_of_strictConvex KF:617 with strictConvex_Icc)'
     ': ELEM2 and GEOM2 hold.  Exclusion needs a further premise: HasTwoSharpTests (SharpTests.lean:41; '
     'hasTwoSharpTests_iff :155 gives 2 <= d) or ElementaryDrivability (not_drivable_Icc KF:529).')

# --- classical trit (triangle): ELEM2 fails; GEOM2 holds
TR = [(Fr(1), Fr(0), Fr(0)), (Fr(0), Fr(1), Fr(0)), (Fr(0), Fr(0), Fr(1))]
ok = True
for i in range(3):
    for j in range(i + 1, 3):
        k = 3 - i - j
        mm = half(TR[i], TR[j])
        # m + eps(m - e_k) has coordinate k equal to -eps < 0: leaves the simplex
        ok = ok and mm[k] == 0 and (mm[k] + Fr(1, 10 ** 6) * (mm[k] - TR[k][k])) < 0
chk('trit.ELEM2_fails', ok, 'enumerate', 'every vertex pair is an edge; its midpoint has a zero coordinate and is '
    'a boundary state (witness the third vertex)')
note('trit.GEOM2', 'the pair face of two vertices is their edge, a segment: GEOM2 holds; the trit is not elementary')

# --- triangular bipyramid: ELEM2 holds (apexes), GEOM2 fails, capacity 3
Nn, Ss = (Fr(0), Fr(0), Fr(1)), (Fr(0), Fr(0), Fr(-1))
A_, B_, C_ = (Fr(2), Fr(0), Fr(0)), (Fr(-1), Fr(1), Fr(0)), (Fr(-1), Fr(-1), Fr(0))


def plane(p, q, r, inside):
    u = tuple(q[i] - p[i] for i in range(3)); v = tuple(r[i] - p[i] for i in range(3))
    nrm = (u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0])
    b = sum(nrm[i] * p[i] for i in range(3))
    if sum(nrm[i] * inside[i] for i in range(3)) > b:
        nrm = tuple(-c for c in nrm); b = -b
    return (nrm, b)


ORG = (Fr(0), Fr(0), Fr(0))
HBP = [plane(Nn, X, Y, ORG) for X, Y in ((A_, B_), (B_, C_), (C_, A_))] + \
      [plane(Ss, X, Y, ORG) for X, Y in ((A_, B_), (B_, C_), (C_, A_))]
chk('bipyramid.vertices_in', all(in_H(HBP, p) for p in (Nn, Ss, A_, B_, C_)), 'enumerate')
chk('bipyramid.ELEM2', in_H(HBP, half(Nn, Ss), strict=True), 'witness', 'midpoint of the apexes is the interior point 0')
chk('bipyramid.GEOM2_fails', boundary_witness_H(HBP, half(Nn, A_), ORG), 'witness',
    'midpoint of the edge [N, A] is a boundary state of the (whole-body) pair face of N, S')


def bary(p):
    # barycentric coordinates of the projection (x, y) in the equator triangle A, B, C (affine in (x, y, z))
    M = [[A_[0], B_[0], C_[0]], [A_[1], B_[1], C_[1]], [Fr(1), Fr(1), Fr(1)]]
    rhs = [p[0], p[1], Fr(1)]
    aug = [M[i] + [rhs[i]] for i in range(3)]
    R, _ = rref(aug)
    return [R[i][3] for i in range(3)]


cap3 = all(all(c >= 0 for c in bary(p)) for p in (Nn, Ss, A_, B_, C_)) and \
    [bary(A_), bary(B_), bary(C_)] == [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
chk('bipyramid.capacity3', cap3, 'witness', 'the three equator barycentric effects are >= 0 on every vertex, sum to '
    'one and perfectly distinguish A, B, C: ELEM2 alone does not bound capacity; GEOM2 does (note B.capacity)')
note('B.capacity', 'ELEM2 & GEOM2 => RelStrictConvex => capacity <= 2: if x1, x2, x3 were perfectly '
     'distinguishable by e1 + e2 + e3 = 1, then 1 - e1 is proper (0 at x1) and certain at x2 != x3, contradicting '
     'singleton faces (KF:590 from RelStrictConvex)')

# --- torus orbitope D x D (= conv S^1 x S^1)
def in_DxD(p):
    return p[0] ** 2 + p[1] ** 2 <= 1 and p[2] ** 2 + p[3] ** 2 <= 1


t1, t2 = (Fr(1), Fr(0), Fr(1), Fr(0)), (Fr(1), Fr(0), Fr(-1), Fr(0))
mt = half(t1, t2)
chk('torus.ELEM2', in_DxD(t1) and in_DxD(tuple(-c for c in t1)), 'witness',
    'x = (1,0,1,0) on S^1 x S^1 (extreme) and -x: the centre 0 is not a boundary state by the CS lemma')
chk('torus.GEOM2_fails', mt == (1, 0, 0, 0) and all(not in_DxD(tuple((1 + e) * c for c in mt))
                                                     for e in (Fr(1, 10 ** k) for k in range(1, 8))), 'witness',
    'two extreme points with midpoint (1,0,0,0); with y = 0 the extension (1+eps)(1,0,0,0) has first-circle norm '
    '(1+eps)^2 > 1 for EVERY eps > 0 (exact sample shown; the inequality is linear in eps): flat face, not RSC')

# --- Stiefel orbitope (spectral-norm unit ball of 3x2 real matrices)
def spec_le_one(M):
    MtM = [[sum(M[i][a] * M[i][b] for i in range(3)) for b in range(2)] for a in range(2)]
    A = [[(1 if a == b else 0) - MtM[a][b] for b in range(2)] for a in range(2)]
    return A[0][0] >= 0 and A[1][1] >= 0 and A[0][0] * A[1][1] - A[0][1] * A[1][0] >= 0


S1 = [[Fr(1), Fr(0)], [Fr(0), Fr(1)], [Fr(0), Fr(0)]]
S2 = [[Fr(1), Fr(0)], [Fr(0), Fr(0)], [Fr(0), Fr(1)]]
mS = [[(S1[i][j] + S2[i][j]) / 2 for j in range(2)] for i in range(3)]
chk('stiefel.ELEM2', spec_le_one(S1) and spec_le_one([[-v for v in r] for r in S1]), 'witness',
    'S1 (a 2-frame, extreme) and -S1: the centre 0 is not a boundary state by the CS lemma')
chk('stiefel.GEOM2_fails', spec_le_one(mS) and all(not spec_le_one([[(1 + e) * v for v in r] for r in mS])
                                                   for e in (Fr(1, 10 ** k) for k in range(1, 8))), 'witness',
    'midpoint of the frames S1, S2 has first column e1 (norm 1); (1+eps) times it has spectral norm 1+eps > 1: flat '
    'face, not RSC')

# --- cone over a disk: ELEM2 fails (sampled pairs + written), GEOM2 holds (written)
def in_cone(p):   # apex (0,0,1), base disk x^2 + y^2 <= 1 at z = 0:  0 <= z <= 1, x^2 + y^2 <= (1 - z)^2
    return 0 <= p[2] <= 1 and p[0] ** 2 + p[1] ** 2 <= (1 - p[2]) ** 2


apex = (Fr(0), Fr(0), Fr(1))
rim = [(Fr(1), Fr(0), Fr(0)), (Fr(-1), Fr(0), Fr(0)), (Fr(3, 5), Fr(4, 5), Fr(0)), (Fr(-4, 5), Fr(3, 5), Fr(0))]
ok = True
for p in rim:
    mm = half(apex, p)                         # on the lateral surface: |xy| = 1 - z exactly
    ok = ok and (mm[0] ** 2 + mm[1] ** 2 == (1 - mm[2]) ** 2)
for p in rim:
    for q in rim:
        if p != q:
            mm = half(p, q)
            ok = ok and mm[2] == 0                  # in the base plane: z + eps(z - apex_z) = -eps < 0 leaves the cone
chk('cone.ELEM2_fails_sampled', ok, 'sample', 'apex-rim midpoints lie on the lateral surface, rim-rim midpoints in the '
    'base: boundary states (written: every pair of extreme points lies in a proper face)')
note('cone.GEOM2', 'pair faces are generating segments [apex, w] or the base disk: GEOM2 holds; the cone has '
     'capacity 3 (apex and two antipodal rim points) and is not elementary')

note('disk.ELEM2_GEOM2', 'the rebit disk is centrally symmetric and strictly convex: ELEM2 and GEOM2 hold.  Exclusion '
     'needs a further premise: corrected ElementaryDrivability (J must normalize SO(2) = the only flow; written, thread '
     'A / KINF-2 record) or the native-gate selector dim_of_nativeGate / dim_of_nativeGateOf (d in {1,3}).  The same '
     'holds for every ball of dimension >= 4 (spin factors): they need the DIM-1 selector.')

# =================================================================================================================
section('C. Countercontrols (each must come out the other way)')

# C1: drop "pure" from ELEM2 (perfectly distinguishable pair instead): the qutrit then qualifies
xq = proj(e0)
yq = [[z0, z0, z0], [z0, GQ(Fr(1, 2)), z0], [z0, z0, GQ(Fr(1, 2))]]
P0 = proj(e0)
mq = madd(xq, yq, Fr(1, 2), Fr(1, 2))
lamq = interior_certificate(mq, eye(3, o1))
chk('C1.ELEMprime_admits_qutrit', tr(P0, xq) == 1 and tr(P0, yq) == 0 and lamq is not None, 'witness',
    'x = |0><0| and the mixed y = (|1><1|+|2><2|)/2 are perfectly distinguishable (P0, 1-P0) and their midpoint '
    'dominates %s I (interior): a non-pure ELEM would put the qutrit in scope, where SF fails (census): "pure" is '
    'load-bearing' % lamq)

# C2: the unlocalized SF on the full qutrit fails (reproduced in census.global_SF_fails); as a countercontrol for
# the SF2 code path, the same code applied to the whole body (K = C^3) must report a two-dimensional certain space.
IEP = madd(eye(3, o1), P, 1, -1)
chk('C2.unlocalized_SF_code_path', len(nullspace(IEP, z0, o1)) == 2, 'witness',
    'ker(I - P) on C^3 has dimension 2: the same computation on the whole qutrit reports a non-singleton certain face')

# C3: Theorem A's hypotheses are each load-bearing
sq_auts = []
for perm in permutations(range(4)):
    # an affine map of the plane is fixed by the images of three affinely independent vertices
    src = [SQ[0], SQ[1], SQ[3]]; dst = [SQ[perm[0]], SQ[perm[1]], SQ[perm[3]]]
    # solve L, t with L src_k + t = dst_k
    M = [[s[0], s[1], Fr(1)] for s in src]
    def solve(col):
        aug = [M[i] + [dst[i][col]] for i in range(3)]
        R, _ = rref(aug)
        return [R[i][3] for i in range(3)]
    ax, ay = solve(0), solve(1)
    # bind the coefficients now (a bare closure would late-bind ax, ay and make every stored map the last one)
    f = (lambda p, ax=tuple(ax), ay=tuple(ay): (ax[0] * p[0] + ax[1] * p[1] + ax[2], ay[0] * p[0] + ay[1] * p[1] + ay[2]))
    if sorted(f(p) for p in SQ) == sorted(SQ):
        sq_auts.append(f)
chk('C3.square_aut_count', len(sq_auts) == 8, 'enumerate', 'exactly 8 of the 24 vertex permutations are affine: D4')
chk('C3.square_auts_distinct', len({tuple(f(p) for p in SQ) for f in sq_auts}) == 8, 'enumerate',
    'the 8 stored maps act as 8 distinct vertex permutations (guards against late binding of the coefficients)')
chk('C3.square_extreme_transitive', {f(SQ[0]) for f in sq_auts} == set(SQ), 'enumerate',
    'ExtremeTransitive holds for the full automorphism group of the square')
edge_mid = (Fr(1), Fr(0))
chk('C3.square_not_boundary_transitive', all(f(edge_mid) != SQ[0] for f in sq_auts), 'enumerate',
    'no automorphism carries the boundary state (1,0) to the vertex (1,1): BoundaryTransitive fails, so '
    'RelStrictConvex is load-bearing in Theorem A (kernel: not_boundaryTransitive_square2)')
note('C3.flow', 'the one-axis rotation flow of ball3 is RelStrictConvex but not ExtremeTransitive (the poles are '
     'fixed); kernel not_boundaryTransitive_flow (OrbitGeneration.lean:620): ExtremeTransitive is load-bearing')

# C4: restricted-preparation sub-theory of the qubit (assumption-watch: state completeness)
def bloch(r):
    # rho = (I + r.sigma)/2 over Q(i)
    return [[GQ((1 + r[2]) / 2), GQ(r[0] / 2, -r[1] / 2)], [GQ(r[0] / 2, r[1] / 2), GQ((1 - r[2]) / 2)]]


REC = [(Fr(3, 5), Fr(4, 5)), (Fr(-3, 5), Fr(4, 5)), (Fr(-3, 5), Fr(-4, 5)), (Fr(3, 5), Fr(-4, 5))]
HRC = H_of_polygon(REC)
pure_vertices = all(rank(bloch((a, b, Fr(0)))) == 1 for a, b in REC)
chk('C4.rectangle_vertices_pure', pure_vertices, 'witness', 'the four vertices (+-3/5, +-4/5, 0) are pure qubit states')
chk('C4.rectangle_ELEM2', in_H(HRC, half(REC[0], REC[2]), strict=True), 'witness', 'opposite vertices: centre interior')
chk('C4.rectangle_GEOM2_fails', boundary_witness_H(HRC, half(REC[0], REC[3]), (Fr(0), Fr(0))), 'witness',
    'edge midpoint (3/5, 0) is a boundary state of the rectangle body: the geometric GEOM2 fails on this sub-body')
rho_mid = bloch((Fr(3, 5), Fr(0), Fr(0)))
lam_mid = interior_certificate(rho_mid, eye(2, o1))
chk('C4.SF2_quantum_effects_hold', lam_mid is not None, 'witness',
    'the edge midpoint is a full-rank qubit state (>= %s I); a qubit effect certain there has tr((I-E) rho) = 0 with '
    'rho > 0, so E = I, not proper: the effect form SF2 with quantum effects holds, and SEC with quantum effects fails '
    'at this boundary state' % lam_mid)
note('C4.reading', 'the geometric principle (GEOM2, like SF with full effects, RelStrictConvex, K-inf-Trans) is not '
     'inherited by restricted-preparation sub-bodies of a quantum system; the effect form with quantum effects is.  '
     'Every geometric seam therefore presupposes that the completed body is the full state space of the system '
     '(state completeness), an unnamed reading of K-inf-Stage.')

# C5: an operational-capacity scope (capacity measured with the AVAILABLE effects) is falsified by a quantum model
# with restricted effects; the geometric ELEM2 is not (the qutrit body fails ELEM2 whatever the effects).
Pc = P                                                    # diag(1,1,0)
avail_r = {'unit': eye(3, o1), 'P': Pc, '1-P': madd(eye(3, o1), Pc, 1, -1)}
pure_states = [proj(v) for v in (e0, e1, e2, vec(1, 1, 0), vec(1, 0, 1), vec(0, 1, I), vec(1, 1, 1))]


def certain_on(E, rho):
    return tr(E, rho) == 1


# perfectly distinguishable pairs from avail_r: (P, 1-P) on (|0>, |2>)
pair_ok = certain_on(avail_r['P'], proj(e0)) and certain_on(avail_r['1-P'], proj(e2))
# a perfectly distinguishing triple needs three available effects summing to the unit, each certain on a state:
names = list(avail_r)
triples = []
for a in names:
    for b in names:
        for c in names:
            S = madd(madd(avail_r[a], avail_r[b]), avail_r[c])
            if S == eye(3, o1):
                triples.append((a, b, c))
# the only sums equal to the unit use the unit itself plus two copies of ... none: list them
triple_certain = [t for t in triples if all(any(certain_on(avail_r[e], s) for s in pure_states) for e in t)]
chk('C5.operational_capacity_is_2', pair_ok and triple_certain == [], 'enumerate',
    'with avail = {unit, P, 1-P} the qutrit has a perfectly distinguishable pair and no perfectly distinguishing triple '
    '(no three available effects sum to the unit)')
chk('C5.SF_avail_fails', certain_on(Pc, proj(e0)) and certain_on(Pc, proj(e1)) and tr(Pc, proj(e2)) == 0, 'witness',
    'yet the available P is proper and certain on two states: "operational capacity 2 => SF(avail)" fails on a quantum '
    'model; the geometric ELEM2 excludes the qutrit body for every effect family (qutrit*.ELEM2_fails)')

# =================================================================================================================
total = sum(N_CHECKS.values())
print()
print('summary: ' + ', '.join('%s %d' % (k, v) for k, v in N_CHECKS.items()))
if FAILED:
    print('qa1_controls: FAIL -- %d of %d checks failed: %s' % (len(FAILED), total, ', '.join(FAILED)))
    sys.exit(1)
print('qa1_controls: OK -- %d exact checks' % total)
