#!/usr/bin/env python3
"""Coordinator's independent check of the research/origin thread's round-3 exact claims (branch head de9285d6;
NOTES-O8, NOTES-O10, NOTES-O9).  Own code; reads nothing.  Run: python3 -I -B indep_checkO3.py
DECISION RULE (fixed before the first run): CONFIRMED/MISMATCH per line; INDEP-O3-FIXED iff all CONFIRMED.
Run 2 (run 1 kept as indep_checkO3.run1.*): run 1 crashed in X6 inside my own harness -- sympy could not integrate the
sign-weighted vector integrand as a Matrix over the sphere (a Piecewise/Matrix TypeError); run 2 integrates each component
with the sign split at theta = pi/2.  X1-X5 were CONFIRMED in run 1; no thread claim was involved.
Conventions: the kernel's level-n carrier is Fin 2 x Fin n with index 2*site + ancilla (site first); mixImage n theta
= rot(theta) on the site factor, identity on the ancilla; phaseGate p = diag(i at p, 1 elsewhere); exchanges =
permutation matrices.  Numbers of Q(zeta_8) are 4-tuples of Fractions in the basis 1, sqrt2, i, i*sqrt2 (own class).
 X1 (O9-L2R) the group generated on the four states of level two by mixImage 2 (pi/4) and the exchanges (a
    transposition and a 4-cycle generate S4) is finite of order 2304, contains -1, and each generator normalizes the
    real Pauli group {+-1}{I, X, Z, XZ}^{x2} (so the whole group does).
 X2 (O9-L2C) with phaseGate (1,1) = diag(1,1,1,i): the word M2.SWAP.M2.SWAP.phaseGate has trace (3+i)/2, not an
    algebraic integer (minimal polynomial 2x^2 - 6x + 5), hence infinite order; the commutant of the conjugation action
    of the four generators (transposition, 4-cycle, M2, phaseGate) on M_4 has dimension 2 modulo a prime p = 1 (mod 8)
    of my own choosing (not the thread's two primes), and 3 for the real generators alone (countercontrol).
 X3 (O9-L1) level one: the group generated by rot(pi/4), the exchange and the two quarter phases has 192 elements and
    exactly 24 conjugation channels (unitaries modulo a scalar); independently, the unit columns with entries in
    B = Z[i][1/2] (denominators up to 2^3) number 24, those with entries in sqrt2.B number 24, the 2x2 unitaries with
    both columns in one class number 192, and they give the same 24 channels.
 X4 (O9-L1a) representations of 4^k and 2*4^k (k <= 3) as ordered sums of four integer squares: 8 for 1, 24 otherwise.
 X5 (O9-E scope) at alpha = pi/8 the level-one word rot(pi/8) S rot(pi/8) S^dag (S = diag(1, i)) has trace 1 + sqrt2/2,
    not an algebraic integer (2x^2 - 4x + 1), so infinite order; at pi/4 the same word has trace 1 and order 6.
 X6 (O10) phiW = cnot(prodState xplus z3) = diag(1,1,-1,1) in the table convention and S_CHSH = 14/5 at the settings
    a0 = e_x, a1 = e_z, b0 = (4/5, 0, 3/5), b1 = (4/5, 0, -3/5); the controlled-rotation table (1, 0; 0, C/2),
    C = diag(1,-1,1), has partial-transpose eigenvalue -1/8 and S = 7/5; E[sgn(u.lambda) lambda] = u/2 for lambda uniform
    on S^2 (exact integral); the 16 deterministic sign patterns give S in {-2, 2}; the lune {x > 0, z > 0} has measure 1/4.
 X7 (O8-T4) on N = 2, 3, 4 configurations with every permutation and the readout of one nontrivial cell (read, correct
    by an outcome-dependent permutation, forget), the closure of the uniform state has exactly C(2N-1, N) = 3, 10, 35
    members (all distributions with masses in (1/N) Z), containing every point mass; for every nontrivial cell at N = 3;
    the trivial cells reach only the uniform state.
"""
import itertools, math
from fractions import Fraction as Fr
import sympy as sp
from sympy import Matrix, Rational as Q, I, eye, zeros, sqrt, pi, cos, sin, simplify, expand, kronecker_product as kron
R = []
def rec(cid, ok, text, detail=""):
    ok = bool(ok); R.append(ok)
    print(f"{'CONFIRMED' if ok else 'MISMATCH'} {cid} {text}" + (f" -- {detail}" if detail else ""), flush=True)

# ---------- own exact arithmetic in Q(zeta_8) = Q(sqrt2, i): (a, b, c, d) = a + b sqrt2 + c i + d i sqrt2 ----------
def nz(x): return (Fr(x[0]), Fr(x[1]), Fr(x[2]), Fr(x[3]))
ZERO = nz((0, 0, 0, 0)); ONE = nz((1, 0, 0, 0)); S2 = nz((0, 1, 0, 0)); IM = nz((0, 0, 1, 0)); IS2 = nz((0, 0, 0, 1))
def add(x, y): return (x[0] + y[0], x[1] + y[1], x[2] + y[2], x[3] + y[3])
def neg(x): return (-x[0], -x[1], -x[2], -x[3])
def mul(x, y):
    a, b, c, d = x; e, f, g, h = y
    # (a + b s + c i + d i s)(e + f s + g i + h i s), s^2 = 2, i^2 = -1
    return (a*e + 2*b*f - c*g - 2*d*h, a*f + b*e - c*h - d*g, a*g + c*e + 2*b*h + 2*d*f, a*h + d*e + b*g + c*f)
def conj(x): return (x[0], x[1], -x[2], -x[3])
def scal(x, r): return (x[0]*r, x[1]*r, x[2]*r, x[3]*r)
def inv(x):
    # 1/x = conj over norm: x * conj(x) = real part in Q(sqrt2); then multiply by its Q(sqrt2)-conjugate
    xc = conj(x); n = mul(x, xc)           # n = (n0, n1, 0, 0)
    n0, n1 = n[0], n[1]; m = n0*n0 - 2*n1*n1   # (n0 + n1 s)(n0 - n1 s) = m rational
    assert m != 0
    t = mul(xc, (n0, -n1, Fr(0), Fr(0)))
    return scal(t, Fr(1) / m)
def iszero(x): return all(v == 0 for v in x)
def mat_mul(A, B, n):
    out = []
    for i in range(n):
        row = []
        for j in range(n):
            s = ZERO
            for k in range(n):
                a = A[i*n + k]
                if a == ZERO: continue
                b = B[k*n + j]
                if b == ZERO: continue
                s = add(s, mul(a, b))
            row.append(s)
        out.extend(row)
    return tuple(out)
def mat_adj(A, n): return tuple(conj(A[j*n + i]) for i in range(n) for j in range(n))
def mat_id(n): return tuple(ONE if i == j else ZERO for i in range(n) for j in range(n))
def mat_neg(A): return tuple(neg(a) for a in A)
def perm_mat(p, n): return tuple(ONE if i == p[j] else ZERO for i in range(n) for j in range(n))   # e_j -> e_{p(j)}
half_s2 = scal(S2, Fr(1, 2))
ROT8 = (half_s2, neg(half_s2), half_s2, half_s2)        # rot(pi/4) = [[c, -s], [s, c]], c = s = sqrt2/2
def kron2(A, B):   # 2x2 (x) 2x2 -> 4x4, index 2*i + j
    out = [None] * 16
    for i in range(2):
        for j in range(2):
            for k in range(2):
                for l in range(2):
                    out[(2*i + k) * 4 + (2*j + l)] = mul(A[i*2 + j], B[k*2 + l])
    return tuple(out)
def closure(gens, n, cap=100000):
    e = mat_id(n); seen = {e}; frontier = [e]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = mat_mul(g, a, n)
                if b not in seen:
                    seen.add(b); nxt.append(b)
                    if len(seen) > cap: return seen, False
        frontier = nxt
    return seen, True

print("== X1 level two, real: order 2304, -1, normalizes the real Pauli group")
I2m = mat_id(2); X2m = (ZERO, ONE, ONE, ZERO); Z2m = (ONE, ZERO, ZERO, neg(ONE)); XZ2m = mat_mul(X2m, Z2m, 2)
M2 = kron2(ROT8, I2m)                                     # rot on the site factor (first), identity on the ancilla
t_perm = perm_mat([1, 0, 2, 3], 4); c_perm = perm_mat([1, 2, 3, 0], 4)
G2, fin = closure([M2, t_perm, c_perm], 4)
minus1 = mat_neg(mat_id(4)) in G2
paulis = [kron2(P, Qm) for P in (I2m, X2m, Z2m, XZ2m) for Qm in (I2m, X2m, Z2m, XZ2m)]
pauli_set = set(paulis) | set(mat_neg(P) for P in paulis)
def normalizes(g):
    gi = mat_adj(g, 4)
    return all(mat_mul(mat_mul(g, P, 4), gi, 4) in pauli_set for P in paulis)
norm_ok = all(normalizes(g) for g in (M2, t_perm, c_perm))
unit_ok = all(mat_mul(g, mat_adj(g, 4), 4) == mat_id(4) for g in (M2, t_perm, c_perm))
rec('X1', fin and len(G2) == 2304 and minus1 and norm_ok and unit_ok,
    '|<mixImage 2 (pi/4), transposition, 4-cycle>| = 2304, contains -1, generators unitary and normalizing the real Pauli group (32 elements)',
    'order %d' % len(G2))

print("== X2 level two with the quarter phase: infinite order; commutant 2 (real: 3)")
def to_sympy(x): return x[0] + x[1] * sqrt(2) + x[2] * I + x[3] * I * sqrt(2)
def mat_to_sympy(A, n): return Matrix(n, n, lambda i, j: to_sympy(A[i*n + j]))
PH = tuple(IM if (i == j == 3) else (ONE if i == j else ZERO) for i in range(4) for j in range(4))   # phaseGate (1,1): index 3
SWAP = perm_mat([0, 2, 1, 3], 4)                                   # (site, anc) -> (anc, site)
word = mat_mul(mat_mul(mat_mul(mat_mul(M2, SWAP, 4), M2, 4), SWAP, 4), PH, 4)
tr = ZERO
for i in range(4): tr = add(tr, word[i*4 + i])
tr_s = sp.nsimplify(to_sympy(tr))
mp = sp.minimal_polynomial(tr_s, sp.Symbol('x'))
not_alg_int = sp.Poly(mp, sp.Symbol('x')).LC() != 1 or sp.Poly(mp, sp.Symbol('x')).LC() == 1 and any(not c.is_integer for c in sp.Poly(mp, sp.Symbol('x')).all_coeffs())
# modular commutant dimension
p = sp.nextprime(2 * 10**9)
while p % 8 != 1: p = sp.nextprime(p)
from sympy.ntheory import sqrt_mod
r2 = sqrt_mod(2, p); im = sqrt_mod(p - 1, p); inv2 = pow(2, -1, p)
def to_modp(x):
    a, b, c, d = x
    def fr(q): return (q.numerator * pow(q.denominator, -1, p)) % p
    return (fr(a) + fr(b) * r2 + fr(c) * im + fr(d) * im * r2) % p
def mat_modp(A, n): return [[to_modp(A[i*n + j]) for j in range(n)] for i in range(n)]
def rank_modp(rows, ncols):
    rows = [r[:] for r in rows]; rank = 0; col = 0; nrows = len(rows)
    for col in range(ncols):
        piv = None
        for r in range(rank, nrows):
            if rows[r][col] % p: piv = r; break
        if piv is None: continue
        rows[rank], rows[piv] = rows[piv], rows[rank]
        invp = pow(rows[rank][col], -1, p)
        rows[rank] = [(v * invp) % p for v in rows[rank]]
        for r in range(nrows):
            if r != rank and rows[r][col] % p:
                f = rows[r][col]
                rows[r] = [(a - f * b) % p for a, b in zip(rows[r], rows[rank])]
        rank += 1
        if rank == nrows: break
    return rank
def commutant_dim(gens_modp):
    """dimension of {Phi in End(M_4) : Phi(g X g^-1) = g Phi(X) g^-1 for all g} over F_p: unknowns Phi (256),
    equations [Phi, Ad(g)] = 0 (256 per generator), Ad(g) as a 16x16 matrix X -> g X g^-1 on vec(X)"""
    def ad_matrix(g, gi):
        # Ad(g)(E_kl) = g E_kl g^-1 ; column index (k,l) -> entry (i,j) = g[i][k] * gi[l][j]
        M = [[0]*16 for _ in range(16)]
        for k in range(4):
            for l in range(4):
                for i in range(4):
                    for j in range(4):
                        M[i*4 + j][k*4 + l] = (g[i][k] * gi[l][j]) % p
        return M
    rows = []
    for g, gi in gens_modp:
        A = ad_matrix(g, gi)
        # [Phi, A] = 0: Phi A - A Phi = 0; unknown Phi (16x16) indexed phi[r][c] -> variable 16 r + c
        for r in range(16):
            for c in range(16):
                row = [0] * 256
                # (Phi A)[r][c] = sum_m Phi[r][m] A[m][c] ; (A Phi)[r][c] = sum_m A[r][m] Phi[m][c]
                for m in range(16):
                    row[16*r + m] = (row[16*r + m] + A[m][c]) % p
                    row[16*m + c] = (row[16*m + c] - A[r][m]) % p
                rows.append(row)
    return 256 - rank_modp(rows, 256)
def inv_modp(g):
    # g unitary with entries in Q(zeta8): inverse = conjugate transpose; compute from the exact matrix
    return None
gens_exact = [(t_perm, mat_adj(t_perm, 4)), (c_perm, mat_adj(c_perm, 4)), (M2, mat_adj(M2, 4)), (PH, mat_adj(PH, 4))]
gens_modp = [(mat_modp(g, 4), mat_modp(gi, 4)) for g, gi in gens_exact]
dim_phase = commutant_dim(gens_modp)
dim_real = commutant_dim(gens_modp[:3])
dets = [mat_to_sympy(g, 4).det() for g, _ in gens_exact]
rec('X2', simplify(tr_s - (3 + I) / 2) == 0 and not_alg_int and dim_phase == 2 and dim_real == 3 and [simplify(d) for d in dets] == [-1, -1, 1, I],
    'trace of M2.SWAP.M2.SWAP.phaseGate(1,1) is (3+i)/2, not an algebraic integer; commutant of Ad on M_4 has dimension 2 (real generators: 3); determinants -1, -1, 1, i',
    'trace %s, minpoly %s, p = %d, dims %d / %d' % (tr_s, mp, p, dim_phase, dim_real))

print("== X3 level one: 192 elements, 24 channels; unit columns 24 + 24")
Xm = X2m; S1 = (IM, ZERO, ZERO, ONE); S0 = (ONE, ZERO, ZERO, IM)
G1, fin1 = closure([ROT8, Xm, S0, S1], 2)
def ray_key(A):
    for a in A:
        if not iszero(a):
            ai = inv(a); return tuple(mul(ai, b) for b in A)
    return A
chan1 = set(ray_key(A) for A in G1)
# unit columns with entries in B = Z[i][1/2]: x / 2^k, x in Z[i]^2, |x|^2 = 4^k; in sqrt2 B: x / (2^k sqrt2), |x|^2 = 2 * 4^k
cols_plus = set(); cols_minus = set()
for k in range(0, 4):
    N = 4 ** k; rng = range(-2 ** k, 2 ** k + 1)
    for a, b, c, d in itertools.product(rng, repeat=4):
        s = a*a + b*b + c*c + d*d
        if s == N:
            v = (scal(add(nz((a, 0, 0, 0)), nz((0, 0, b, 0))), Fr(1, 2 ** k)), scal(add(nz((c, 0, 0, 0)), nz((0, 0, d, 0))), Fr(1, 2 ** k)))
            cols_plus.add(v)
        if s == 2 * N:
            f = scal(inv(S2), Fr(1, 2 ** k))        # 1/(2^k sqrt2)
            v = (mul(add(nz((a, 0, 0, 0)), nz((0, 0, b, 0))), f), mul(add(nz((c, 0, 0, 0)), nz((0, 0, d, 0))), f))
            cols_minus.add(v)
def inner(u, v): return add(mul(conj(u[0]), v[0]), mul(conj(u[1]), v[1]))
unitaries = set()
for cls in (cols_plus, cols_minus):
    for u in cls:
        for v in cls:
            if iszero(inner(u, v)):
                unitaries.add((u[0], v[0], u[1], v[1]))     # columns u, v
chan_cols = set(ray_key(A) for A in unitaries)
rec('X3', fin1 and len(G1) == 192 and len(chan1) == 24 and len(cols_plus) == 24 and len(cols_minus) == 24 and len(unitaries) == 192 and chan_cols == chan1,
    'level-one group 192 elements, 24 channels; unit columns in B: 24, in sqrt2 B: 24; unitaries from same-class orthonormal pairs: 192, with the same 24 channels',
    'group %d, channels %d, columns %d + %d, unitaries %d' % (len(G1), len(chan1), len(cols_plus), len(cols_minus), len(unitaries)))

print("== X4 four squares equal to 4^k and 2*4^k")
def reps(N):
    r = int(math.isqrt(N)); return sum(1 for a, b, c, d in itertools.product(range(-r, r + 1), repeat=4) if a*a + b*b + c*c + d*d == N)
counts = {N: reps(N) for N in (1, 4, 16, 64, 2, 8, 32, 128)}
rec('X4', counts == {1: 8, 4: 24, 16: 24, 64: 24, 2: 24, 8: 24, 32: 24, 128: 24}, 'ordered four-square representations: 8 for 1, 24 for 4, 16, 64, 2, 8, 32, 128', str(counts))

print("== X5 scope: pi/8 infinite order, pi/4 order 6")
th = sp.Symbol('th')
def rot_s(t): return Matrix([[cos(t), -sin(t)], [sin(t), cos(t)]])
Sg = Matrix.diag(1, I)
w8 = rot_s(pi / 8) * Sg * rot_s(pi / 8) * Sg.H
tr8 = sp.nsimplify(simplify(w8.trace()))
mp8 = sp.minimal_polynomial(tr8, sp.Symbol('x'))
w4 = rot_s(pi / 4) * Sg * rot_s(pi / 4) * Sg.H
tr4 = simplify(w4.trace())
ord4 = next((n for n in range(1, 13) if simplify(w4 ** n - eye(2)) == zeros(2, 2)), None)
rec('X5', simplify(tr8 - (1 + sqrt(2) / 2)) == 0 and sp.Poly(mp8, sp.Symbol('x')).LC() != 1 and tr4 == 1 and ord4 == 6,
    'trace at pi/8 is 1 + sqrt2/2 (minimal polynomial 2x^2 - 4x + 1, not monic: infinite order); at pi/4 trace 1, order 6',
    'minpoly %s, order at pi/4 %s' % (mp8, ord4))

print("== X6 O10 pair numbers")
I2 = eye(2); SX = Matrix([[0, 1], [1, 0]]); SY = Matrix([[0, -I], [I, 0]]); SZ = Matrix([[1, 0], [0, -1]])
SG = [I2, SX, SY, SZ]; KR = {(m, n): kron(SG[m], SG[n]) for m in range(4) for n in range(4)}
def pauliW(w): return sum((w[m, n] * KR[(m, n)] for m in range(4) for n in range(4) if w[m, n] != 0), zeros(4, 4)) / 4
def tab(M): return Matrix(4, 4, lambda m, n: sp.nsimplify(simplify((KR[(m, n)] * M).trace())))
CNOT = Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
def prodState(x, y):
    hx = Matrix([1, x[0], x[1], x[2]]); hy = Matrix([1, y[0], y[1], y[2]]); return hx * hy.T
xplus = (1, 0, 0); z3 = (0, 0, 1)
phiW = tab(CNOT * pauliW(prodState(xplus, z3)) * CNOT.H)
def E(w, u, v): return sum(u[i] * v[j] * w[i + 1, j + 1] for i in range(3) for j in range(3))
a0, a1 = (1, 0, 0), (0, 0, 1); b0, b1 = (Q(4, 5), 0, Q(3, 5)), (Q(4, 5), 0, Q(-3, 5))
def chsh(w): return E(w, a0, b0) + E(w, a0, b1) + E(w, a1, b0) - E(w, a1, b1)
S_phi = chsh(phiW)
wC = zeros(4, 4); wC[0, 0] = 1; wC[1, 1] = Q(1, 2); wC[2, 2] = Q(-1, 2); wC[3, 3] = Q(1, 2)
rhoC = pauliW(wC)
def ptrans(rho):   # partial transpose on the second factor
    out = zeros(4, 4)
    for i in range(2):
        for j in range(2):
            for k in range(2):
                for l in range(2):
                    out[2*i + k, 2*j + l] = rho[2*i + l, 2*j + k]
    return out
evs = ptrans(rhoC).eigenvals()
S_C = chsh(wC)
theta, phi = sp.symbols('theta phi', real=True)
lam = Matrix([sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta)])
def sphere_avg_signed(f):
    inner = sp.integrate(f * sin(theta), (phi, 0, 2 * pi))
    a = sp.integrate(inner, (theta, 0, pi / 2)); b = sp.integrate(inner, (theta, pi / 2, pi))
    return simplify((a - b) / (4 * pi))
Ez = Matrix([sphere_avg_signed(lam[i]) for i in range(3)])
lune = sp.integrate(sp.integrate(sin(theta), (phi, 0, pi / 2)), (theta, 0, pi)) / (4 * pi)   # x > 0 (phi in (-pi/2, pi/2)) and z > 0 (theta < pi/2): use symmetric region
lune = sp.integrate(sp.integrate(sin(theta), (phi, -pi / 2, pi / 2)), (theta, 0, pi / 2)) / (4 * pi)
patterns = set()
for sa0, sa1, sb0, sb1 in itertools.product([1, -1], repeat=4):
    patterns.add(sa0 * sb0 + sa0 * sb1 + sa1 * sb0 - sa1 * sb1)
rec('X6', phiW == Matrix.diag(1, 1, -1, 1) and S_phi == Q(14, 5) and set(evs.keys()) == {Q(3, 8), Q(-1, 8)} and evs[Q(-1, 8)] == 1 and S_C == Q(7, 5)
    and Ez == Matrix([0, 0, Q(1, 2)]) and simplify(lune - Q(1, 4)) == 0 and patterns == {2, -2},
    'phiW = diag(1,1,-1,1), S = 14/5; the controlled-rotation table has partial-transpose eigenvalue -1/8 and S = 7/5; E[sgn(u.lambda) lambda] = u/2; lune 1/4; deterministic patterns give +-2',
    'S(phiW) = %s, PT eigenvalues %s, S(C) = %s, E = %s, lune %s' % (S_phi, {str(k): v for k, v in evs.items()}, S_C, list(Ez), lune))

print("== X7 O8: one nontrivial cell with every permutation reaches every point mass; closure sizes C(2N-1, N)")
def reach_closure(N, cell):
    unif = tuple([Fr(1, N)] * N); seen = {unif}; frontier = [unif]
    perms = list(itertools.permutations(range(N)))
    while frontier:
        nxt = []
        for w in frontier:
            inc = [w[x] if x in cell else Fr(0) for x in range(N)]; outc = [Fr(0) if x in cell else w[x] for x in range(N)]
            for s in perms:
                pin = [Fr(0)] * N
                for x in range(N): pin[s[x]] += inc[x]
                for t in perms:
                    new = pin[:]
                    for x in range(N): new[t[x]] += outc[x]
                    new = tuple(new)
                    if new not in seen: seen.add(new); nxt.append(new)
        frontier = nxt
    return seen
ok7 = True; sizes = {}
for N in (2, 3, 4):
    cl = reach_closure(N, {0}); sizes[N] = len(cl)
    pm = all(tuple(Fr(1) if x == x0 else Fr(0) for x in range(N)) in cl for x0 in range(N))
    grid = all(all((v * N).denominator == 1 for v in w) and sum(w) == 1 for w in cl)
    ok7 = ok7 and len(cl) == math.comb(2 * N - 1, N) and pm and grid
for cell in ({0}, {1}, {2}, {0, 1}, {0, 2}, {1, 2}):
    ok7 = ok7 and len(reach_closure(3, cell)) == 10
triv = len(reach_closure(3, set())) == 1 and len(reach_closure(3, {0, 1, 2})) == 1
rec('X7', ok7 and triv, 'closures 3, 10, 35 = C(2N-1, N) for N = 2, 3, 4 with every point mass; every nontrivial cell at N = 3 gives 10; trivial cells give 1', str(sizes))

print("SUMMARY %d/%d CONFIRMED" % (sum(R), len(R)))
print("INDEP-O3-FIXED" if all(R) else "INDEP-O3-MISMATCH")
