import OIBridge.LiftSource
import OIBridge.FlowEndpoint

/-!
# The C5 discovery audit — the kill battery, the two candidate families, the polarization map

The preregistered pass of `C5-DISCOVERY-AUDIT.md`. Nothing here is named "C5"; every object is a
candidate or a test. The kernel content:

* T0, the obligations and their independence: the substratum theory has the relative-phase
  resource and executes no layer flow; the ones-fixing theory executes every layer flow and has
  no quarter phase (`obligations_independent`).
* T1, the kill battery: the predicate listing the three named non-quantum theories a candidate's
  sourced theory must differ from (`KillBattery`, `killBattery_substratum`, `killBattery_ones`,
  `killBattery_perm`), none of them quantum (`killBattery_not_qm`), and any theory with both
  obligations lying outside it (`obligations_outside_battery`).
* T2, candidate 1 as the negative control: the theory generated by any bijection-level class,
  the read-write family's included, fails both obligations (`bijectionLevel_fails_obligations`).
* T3, candidate 2 at update level: a configuration-level class, label-invariant, fails phase-free
  richness and executes no layer flow (`updateLevel_symplectic_inert`).
* T4, candidate 2 as the polarization map on the two-valued alphabet: the Hadamard matrix
  (`hadamard`), not monomial and not diagonal-preserving (`hadamard_not_monomial`,
  `hadamard_not_preservesDiag`); the images of the two layers at every level with the ancilla a
  spectator (`siteShearImage`, `siteSwapImage`), the swap image not monomial at any level
  (`siteSwapImage_not_monomial`); the polarized class, the stated access closed with the two
  images under the architecture operations (`PolGen`, `polGen_arch`), not configuration-level
  (`polGen_not_configurationLevel`), and its theory (`polarizedTheory`); at level one the shear
  image is the quarter phase (`siteShearImage_one_eq_phaseGate`) and is available
  (`polarizedTheory_phase_level_one`); the swap-layer flow at time one half is exactly the
  Hadamard-conjugated quarter phase (`gateFlow_half_eq_hsh`) and is available at level one
  (`polarizedTheory_swap_half_level_one`).

Not proved here, and undecided for the full generated theory: whether the polarized theory has the
quarter phase on a single configuration at level two, and whether it executes the swap-layer flow at
a non-Clifford time. The finiteness of the bare Weil subgroup identifies the candidate obstruction
to both and proves nothing about what the closure operations, the scalars, projections, blocks and
the instrument closure, synthesize from it; the missing kernel step is a conjugation invariant
stable under that closure.

Not claimed: that any candidate is a C5; that the polarization map is available to the observer;
anything about a manuscript.
-/

namespace OIBridge
namespace C5Discovery

open Complex Matrix CoherentLift SpectatorBridge OperationalAssembly AncillaClosure
open MonoidalCompletion InterventionLocality MicroReversibility PrimitiveSource LieRankSource
open DiagonalTheory SubstratumInterface StructuralClosure MinimalRepertoire LevelOneSeam
open PhysicalCharacterization RouteB ManuscriptAxioms LiftAudit SubstratumInterfaceAudit
open InstrumentRealization SecondOrderCircuit ExecSource FlowEndpoint DerivedQ3

/-! ### Section A — T0 and T1: the obligations, their independence, the kill battery -/

section Battery

/-- **T0 — THE TWO OBLIGATIONS ARE INDEPENDENT**: the phase without the flow in the substratum
theory, the flow without the phase in the ones-fixing theory. -/
theorem obligations_independent :
    (PhasesAvailable (substratumTheory (Fin 2))
        ∧ ¬ LayerFlowExecutable (substratumTheory (Fin 2)) (Equiv.swap 0 1))
      ∧ (LayerFlowExecutable (onesTheory (Fin 2)) (Equiv.swap 0 1)
        ∧ ¬ PhasesAvailable (onesTheory (Fin 2))) :=
  ⟨⟨substratumTheory_derivedOI.2.2.2.1,
    substratumTheory_not_layerFlowExecutable (x := (0 : Fin 2)) (by simp)⟩,
   ⟨onesTheory_layerFlowExecutable (fun x => Equiv.swap_apply_self _ _ x),
    onesTheory_not_phasesAvailable (by simp)⟩⟩

/-- **T1 — THE KILL BATTERY**: the named non-quantum theories a candidate's sourced theory must
differ from. -/
def KillBattery (T : FiniteOperationalTheory (Fin 2)) : Prop :=
  T = substratumTheory (Fin 2) ∨ T = onesTheory (Fin 2) ∨ T = permTheory (Fin 2)

theorem killBattery_substratum : KillBattery (substratumTheory (Fin 2)) := Or.inl rfl

theorem killBattery_ones : KillBattery (onesTheory (Fin 2)) := Or.inr (Or.inl rfl)

theorem killBattery_perm : KillBattery (permTheory (Fin 2)) := Or.inr (Or.inr rfl)

/-- **T1 — NOTHING IN THE BATTERY IS QUANTUM.** -/
theorem killBattery_not_qm {T : FiniteOperationalTheory (Fin 2)} (h : KillBattery T) :
    ¬ ExactAllFiniteEndomorphicQuantumOps T := by
  rcases h with rfl | rfl | rfl
  · exact fun hq =>
      substratumTheory_not_phaseFree ((derivedOI_qm_iff_phaseFree substratumTheory_derivedOI).mp hq)
  · exact onesTheory_not_qm
  · exact permTheory_not_qm

/-- **T1 — BOTH OBLIGATIONS PLACE A THEORY OUTSIDE THE BATTERY.** -/
theorem obligations_outside_battery {T : FiniteOperationalTheory (Fin 2)}
    (hph : PhasesAvailable T) {σ : Equiv.Perm (Fin 2)} {x : Fin 2} (hx : σ x ≠ x)
    (hex : LayerFlowExecutable T σ) : ¬ KillBattery T := by
  rintro (rfl | rfl | rfl)
  · exact substratumTheory_not_layerFlowExecutable hx hex
  · exact onesTheory_not_phasesAvailable (by simp) hph
  · exact permTheory_not_phasesAvailable hph

end Battery

/-! ### Section B — T2 and T3: candidate 1 as the negative control; candidate 2 at update level -/

section Candidates

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T2 — A BIJECTION-LEVEL CLASS FAILS BOTH OBLIGATIONS**: no quarter phase, no layer flow of an
involution with a moved configuration. The read-write family, permutation-valued at every
parameter, generates such a class. -/
theorem bijectionLevel_fails_obligations [Nonempty S] {𝓘 : ImplementationClass}
    (arch : Architecture 𝓘) (hb : BijectionLevel 𝓘) :
    ¬ PhasesAvailable (genTheory 𝓘 arch S)
      ∧ ∀ (σ : Equiv.Perm S) (x : S), σ x ≠ x → ¬ LayerFlowExecutable (genTheory 𝓘 arch S) σ :=
  ⟨bijectionLevel_not_phasesAvailable arch hb,
    fun _ _ hx => bijectionLevel_not_layerFlowExecutable arch hb hx⟩

/-- **T3 — THE UPDATE-LEVEL CANONICAL STRUCTURE IS INERT**: whatever a property of the update
alone reaches through the stipulated sourcing is configuration-level, and a configuration-level
label-invariant class fails phase-free richness and executes no layer flow. -/
theorem updateLevel_symplectic_inert {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
    (h : ConfigurationLevel 𝓘) (hl : LabelInvariant 𝓘) :
    ¬ PhaseFreeRichness (genTheory 𝓘 arch (Fin 2))
      ∧ ∀ (T : Type) [Fintype T] [DecidableEq T] (σ : Equiv.Perm T) (x : T), σ x ≠ x →
          ¬ LayerFlowExecutable (genTheory 𝓘 arch T) σ :=
  ⟨configurationLevel_not_phaseFree arch h hl,
    fun _ _ _ _ _ hx => configurationLevel_not_layerFlowExecutable arch h hx⟩

end Candidates

/-! ### Section C — T4: the polarization map on the two-valued alphabet -/

section Polarization

/-- The Hadamard coefficient `1/√2`, as a complex number. -/
noncomputable def hc : ℂ := ((Real.sqrt 2)⁻¹ : ℝ)

theorem hc_mul_hc : hc * hc = 1 / 2 := by
  unfold hc
  rw [← Complex.ofReal_mul, ← mul_inv, Real.mul_self_sqrt (by norm_num : (0 : ℝ) ≤ 2)]
  push_cast
  ring

theorem hc_ne_zero : hc ≠ 0 := by
  unfold hc
  exact Complex.ofReal_ne_zero.mpr (inv_ne_zero (Real.sqrt_ne_zero'.mpr (by norm_num)))

theorem conj_hc : (starRingEnd ℂ) hc = hc := by
  unfold hc
  exact Complex.conj_ofReal _

theorem star_hc : star hc = hc := by
  rw [Complex.star_def]
  exact conj_hc

/-- **THE SWAP IMAGE ON ONE SITE**: the Hadamard matrix, the finite Fourier transform of the
two-valued alphabet. -/
noncomputable def hadamard : Matrix (Fin 2) (Fin 2) ℂ :=
  Matrix.of fun i j => if i = 1 ∧ j = 1 then -hc else hc

theorem hadamard_apply (i j : Fin 2) : hadamard i j = if i = 1 ∧ j = 1 then -hc else hc := rfl

/-- **T4 — THE HADAMARD MATRIX IS NOT MONOMIAL**: its first row has two nonzero entries. -/
theorem hadamard_not_monomial : ¬ IsMonomial hadamard := by
  rintro ⟨τ, d, h⟩
  have h00 := congrFun (congrFun h 0) 0
  have h01 := congrFun (congrFun h 0) 1
  rw [monomial_entry] at h00 h01
  rw [hadamard_apply] at h00 h01
  simp only [Fin.zero_eq_one_iff, OfNat.ofNat_ne_one, false_and, if_false] at h00 h01
  by_cases hτ0 : τ 0 = 0
  · by_cases hτ1 : τ 1 = 0
    · exact absurd (τ.injective (hτ0.trans hτ1.symm)) (by decide)
    · rw [if_neg hτ1] at h01
      exact hc_ne_zero h01
  · rw [if_neg hτ0] at h00
    exact hc_ne_zero h00

/-- **T4 — THE HADAMARD MATRIX DOES NOT PRESERVE DIAGONAL STATES**: it sends the first basis
state to the uniform superposition. -/
theorem hadamard_not_preservesDiag : ¬ PreservesDiag (conjChannel hadamard) := by
  intro h
  obtain ⟨w', hw'⟩ := h (fun p => if p = 0 then 1 else 0)
  have h01 := congrFun (congrFun hw' 0) 1
  rw [Matrix.diagonal_apply_ne _ (by decide), conjChannel_apply] at h01
  simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.diagonal_apply, Matrix.conjTranspose_apply,
    hadamard_apply] at h01
  simp only [Fin.isValue, Fin.zero_eq_one_iff, OfNat.ofNat_ne_one, false_and, if_false, and_self,
    if_true, and_false, one_ne_zero, mul_one, mul_zero, add_zero, zero_mul, star_hc] at h01
  exact hc_ne_zero (mul_self_eq_zero.mp h01)

/-- **THE SHEAR IMAGE AT LEVEL `n`**, the ancilla a spectator: the quarter phase on the site's
position one. -/
noncomputable def siteShearImage (n : ℕ) : Matrix (Fin 2 × Fin n) (Fin 2 × Fin n) ℂ :=
  Matrix.diagonal fun p => if p.1 = 1 then Complex.I else 1

/-- **THE SWAP IMAGE AT LEVEL `n`**, the ancilla a spectator: the Hadamard matrix on the site. -/
noncomputable def siteSwapImage (n : ℕ) : Matrix (Fin 2 × Fin n) (Fin 2 × Fin n) ℂ :=
  Matrix.of fun p q => if p.2 = q.2 then hadamard p.1 q.1 else 0

theorem siteSwapImage_apply (n : ℕ) (p q : Fin 2 × Fin n) :
    siteSwapImage n p q = if p.2 = q.2 then hadamard p.1 q.1 else 0 := rfl

/-- **T4 — THE SWAP IMAGE IS NOT MONOMIAL AT ANY LEVEL.** -/
theorem siteSwapImage_not_monomial (n : ℕ) (k : Fin n) : ¬ IsMonomial (siteSwapImage n) := by
  rintro ⟨τ, d, h⟩
  have h00 := congrFun (congrFun h (0, k)) (0, k)
  have h01 := congrFun (congrFun h (0, k)) (1, k)
  rw [monomial_entry] at h00 h01
  rw [siteSwapImage_apply, if_pos rfl, hadamard_apply] at h00 h01
  simp only [Fin.isValue, Fin.zero_eq_one_iff, OfNat.ofNat_ne_one, false_and, if_false] at h00 h01
  by_cases hτ0 : τ (0, k) = (0, k)
  · by_cases hτ1 : τ (1, k) = (0, k)
    · have := τ.injective (hτ0.trans hτ1.symm)
      exact absurd (Prod.mk.inj this).1 (by decide)
    · rw [if_neg hτ1] at h01
      exact hc_ne_zero h01
  · rw [if_neg hτ0] at h00
    exact hc_ne_zero h00

/-- **THE POLARIZED CLASS**: the stated access, the scaled partial permutations, together with the
two images at every level, closed under the operations of an architecture. -/
inductive PolGen : ∀ (T : Type) [Fintype T] [DecidableEq T], Matrix T T ℂ → Prop
  | perm {T : Type} [Fintype T] [DecidableEq T] (K : Matrix T T ℂ) (h : permClass T K) : PolGen T K
  | shear (n : ℕ) : PolGen (Fin 2 × Fin n) (siteShearImage n)
  | swap (n : ℕ) : PolGen (Fin 2 × Fin n) (siteSwapImage n)
  | mul {T : Type} [Fintype T] [DecidableEq T] (K L : Matrix T T ℂ) :
      PolGen T K → PolGen T L → PolGen T (K * L)
  | smul {T : Type} [Fintype T] [DecidableEq T] (a : ℂ) (K : Matrix T T ℂ) (ha : ‖a‖ ≤ 1) :
      PolGen T K → PolGen T (a • K)
  | proj {T : Type} [Fintype T] [DecidableEq T] (m : ℕ) (k : Fin m) :
      PolGen (T × Fin m) (Matrix.diagonal fun r => if r.2 = k then 1 else 0)
  | block {T : Type} [Fintype T] [DecidableEq T] (m : ℕ) (K : Matrix (T × Fin m) (T × Fin m) ℂ)
      (f e : Fin m) : PolGen (T × Fin m) K → PolGen T (ancBlock K f e)

theorem polGen_arch : Architecture PolGen where
  one := fun T _ _ => PolGen.perm 1 (permClass_arch.one T)
  mul := fun _ _ _ K L hK hL => PolGen.mul K L hK hL
  smul := fun _ _ _ a K ha hK => PolGen.smul a K ha hK
  proj := fun _ _ _ m k => PolGen.proj m k
  block := fun _ _ _ m K f e hK => PolGen.block m K f e hK

/-- **T4 — THE POLARIZED CLASS IS NOT CONFIGURATION-LEVEL**: test 2 passes. -/
theorem polGen_not_configurationLevel : ¬ ConfigurationLevel PolGen :=
  fun h => siteSwapImage_not_monomial 1 0 (h _ _ (PolGen.swap 1))

/-- **THE POLARIZED THEORY**: what the stated access and the two images generate through the
observer architecture. -/
noncomputable def polarizedTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S :=
  genTheory PolGen polGen_arch S

/-- At level one the shear image is the quarter phase on the site's position one. -/
theorem siteShearImage_one_eq_phaseGate :
    siteShearImage 1 = phaseGate ((1 : Fin 2), (0 : Fin 1)) := by
  ext p q
  rw [siteShearImage, phaseGate, Matrix.diagonal_apply, Matrix.diagonal_apply]
  rcases p with ⟨a, k⟩
  rcases q with ⟨b, l⟩
  have hk : k = 0 := Subsingleton.elim _ _
  have hl : l = 0 := Subsingleton.elim _ _
  subst hk hl
  by_cases hab : a = b
  · subst hab
    simp only [if_true]
    by_cases ha : a = 1
    · subst ha; simp
    · rw [if_neg ha, if_neg (fun h => ha (Prod.mk.inj h).1.symm)]
  · rw [if_neg (fun h => hab (Prod.mk.inj h).1), if_neg (fun h => hab (Prod.mk.inj h).1)]

theorem siteShearImage_unitary (n : ℕ) : (siteShearImage n)ᴴ * siteShearImage n = 1 := by
  rw [siteShearImage, Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
    ← Matrix.diagonal_one]
  congr 1
  funext p
  simp only [Pi.star_apply]
  split_ifs <;> simp [Complex.I_mul_I]

/-- **T4 — O1 AT LEVEL ONE**: the quarter phase on the site is available in the polarized
theory. -/
theorem polarizedTheory_phase_level_one :
    (polarizedTheory (Fin 2)).availExt 1 Unit
      (fun _ => conjChannel (phaseGate ((1 : Fin 2), (0 : Fin 1)))) := by
  rw [← siteShearImage_one_eq_phaseGate]
  exact SubstratumSource.genTheory_avail_conj polGen_arch (PolGen.shear 1) (siteShearImage_unitary 1)

/-- **THE SWAP-LAYER FLOW AT TIME ONE HALF IS THE HADAMARD-CONJUGATED QUARTER PHASE** at level
one: `H · S · H` entry by entry. -/
theorem gateFlow_half_eq_hsh :
    gateFlow (levelPerm (Equiv.swap (0 : Fin 2) 1) 1) (1 / 2 : ℝ)
      = siteSwapImage 1 * siteShearImage 1 * siteSwapImage 1 := by
  have hmoved : ∀ p : Fin 2 × Fin 1, levelPerm (Equiv.swap (0 : Fin 2) 1) 1 p ≠ p := by
    rintro ⟨a, k⟩ h
    rw [levelPerm_apply] at h
    have := (Prod.mk.inj h).1
    fin_cases a <;> simp at this
  have hrhs : ∀ a b : Fin 2, (siteSwapImage 1 * siteShearImage 1 * siteSwapImage 1) (a, 0) (b, 0)
      = if a = b then (1 + Complex.I) / 2 else (1 - Complex.I) / 2 := by
    intro a b
    simp only [Matrix.mul_apply, Fintype.sum_prod_type, Fin.sum_univ_two, Fin.sum_univ_one,
      siteSwapImage_apply, siteShearImage, Matrix.diagonal_apply, hadamard_apply]
    fin_cases a <;> fin_cases b <;> simp <;>
      first
      | linear_combination (1 + Complex.I) * hc_mul_hc
      | linear_combination (1 - Complex.I) * hc_mul_hc
  ext p q
  rcases p with ⟨a, k⟩
  rcases q with ⟨b, l⟩
  have hk : k = 0 := Subsingleton.elim _ _
  have hl : l = 0 := Subsingleton.elim _ _
  subst hk hl
  rw [hrhs]
  by_cases hab : a = b
  · subst hab
    rw [if_pos rfl]
    exact (gateFlow_half_entries (hmoved (a, 0))).1
  · rw [if_neg hab]
    have hσ : levelPerm (Equiv.swap (0 : Fin 2) 1) 1 (b, 0) = (a, 0) := by
      rw [levelPerm_apply]
      fin_cases a <;> fin_cases b <;> simp_all
    have := (gateFlow_half_entries (hmoved (b, 0))).2
    rw [hσ] at this
    exact this

/-- **T4 — THE HALF-TIME POINT OF THE SWAP FLOW IS AVAILABLE AT LEVEL ONE** in the polarized
theory: one point of O2, at the one time where the flow is a product of the images. -/
theorem polarizedTheory_swap_half_level_one :
    (polarizedTheory (Fin 2)).availExt 1 Unit
      (fun _ => conjChannel (gateFlow (levelPerm (Equiv.swap (0 : Fin 2) 1) 1) (1 / 2 : ℝ))) := by
  have hσ : ∀ x : Fin 2, Equiv.swap (0 : Fin 2) 1 (Equiv.swap 0 1 x) = x :=
    fun x => Equiv.swap_apply_self _ _ _
  have hiso := gateFlow_unitary (LiftAudit.levelPerm_involutive hσ 1) (1 / 2 : ℝ)
  rw [gateFlow_half_eq_hsh] at hiso ⊢
  exact SubstratumSource.genTheory_avail_conj polGen_arch
    (PolGen.mul _ _ (PolGen.mul _ _ (PolGen.swap 1) (PolGen.shear 1)) (PolGen.swap 1)) hiso

end Polarization

/-! ### Axiom check -/

#print axioms obligations_independent
#print axioms killBattery_substratum
#print axioms killBattery_ones
#print axioms killBattery_perm
#print axioms killBattery_not_qm
#print axioms obligations_outside_battery
#print axioms bijectionLevel_fails_obligations
#print axioms updateLevel_symplectic_inert
#print axioms hadamard_not_monomial
#print axioms hadamard_not_preservesDiag
#print axioms siteSwapImage_not_monomial
#print axioms polGen_arch
#print axioms polGen_not_configurationLevel
#print axioms siteShearImage_one_eq_phaseGate
#print axioms polarizedTheory_phase_level_one
#print axioms gateFlow_half_eq_hsh
#print axioms polarizedTheory_swap_half_level_one

end C5Discovery
end OIBridge
