/-
  OIBridge/ControlLie.lean — the dynamical control Lie algebra of an H-functor
  completion: projective well-definedness, gauge covariance, the conjugated-flow
  identity, the skew-Hermitian bound, and the no-controls collapse.

  PHASE THREE, ROUND NINETEEN. Round eighteen selected the quantum branch by the named
  bridge H-functor: a chosen completion carries projective monomial unitary controls
  U_g over the classical action, alongside the reconstructed passive flow e^{-itH}.
  This round is a unitary-controllability CLASSIFICATION, not a claim that the
  existing hypotheses generate U(D): H-functor says how the available reversible
  controls lift; it does not guarantee the classical menu contains enough controls.
  The central object is the dynamical Lie algebra

      𝔏(H,U) = Lie_ℝ⟨ -i·U_g·H·U_g† : g ∈ G ⟩ ⊆ u(D)     (`controlLie`),

  formalized as `LieSubalgebra.lieSpan` over ℝ inside the matrix algebra with the
  commutator bracket. Kernel results:

  · PROJECTIVE WELL-DEFINEDNESS (`phase_conj_invariant`,
    `controlLie_phase_invariant`): replacing U_g by λ_g·U_g with |λ_g| = 1 leaves
    every conjugated Hamiltonian, hence 𝔏, literally unchanged — the 2-cocycle
    freedom of round eighteen never touches the control algebra.
  · GAUGE COVARIANCE (`controlLie_gauge_mem`, `controlLie_gauge_mem_iff`): a common
    unitary gauge H ↦ WHW†, U_g ↦ WU_gW† conjugates 𝔏 elementwise, so membership,
    dimension and fullness are representation-gauge invariant.
  · THE CONJUGATED-FLOW IDENTITY (`unitary_exp_conj`, `conjugated_flow`):
    U·e^{-itH}·U† = e^{-it·UHU†} — the group generated by the passive flow and the
    controls contains every conjugated flow, so 𝔏's generators are all reachable
    directions.
  · THE SKEW-HERMITIAN BOUND (`controlLie_le_skewHerm`): for Hermitian H and unitary
    controls, 𝔏 ⊆ u(D) — the classification lives inside the unitary Lie algebra.
  · THE NO-CONTROLS COLLAPSE (`controlLie_trivial`): when every control fixes H by
    conjugation, 𝔏 = ℝ·(-iH), one-dimensional — the MANDATORY SEPARATION from the
    accessible-algebra theorem: `AccessibleAlgebra.native_menu_generates` can deliver
    the full *-algebra M_D(ℂ) from Heisenberg-evolved readouts on the SAME carrier
    whose dynamical Lie algebra is a line. Algebra generation and dynamical
    controllability are different notions, and probe F32 exhibits the exact 2×2
    instance: accessible algebra full, 𝔏 = ℝ(-iH); adding one classical swap control
    jumps 𝔏 to all of u(2), with traceless part su(2).

  WHAT REMAINS ANALYTIC, recorded not claimed: the Lie-closure equality
  Lie(K⁰) = 𝔏(H,U) for the closure K of the generated subgroup (the
  closed-subgroup/analytic-subgroup step), and the criterion "𝔏₀ = su(D) ⟹
  universal unitary control up to phase". Probe F32 carries both at the exact finite
  level (bracket-closure ranks over ℚ(i)). The chain is now:

      bare OI          ⟹  classical core + correlation extensions;
      + H-functor      ⟹  projective monomial quantum controls;
      + 𝔏₀ = su(D)     ⟹  universal unitary control up to phase —

  and only then the remaining purification/composite/instrument bridge. The theorem
  is conditional on the selected H-functor completion with gauge-equivalent lifts
  identified; the classical permutation action alone does not determine 𝔏.

  Kernel check:  cd verification/lean-mathlib && lake exe cache get && lake build
-/
import OIBridge.ProjectiveAction
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Algebra.Lie.Subalgebra
import Mathlib.Algebra.Lie.OfAssociative

namespace OIBridge
namespace ControlLie

open Complex Matrix
open scoped ComplexOrder

local notation "conj'" => (starRingEnd ℂ)

attribute [local instance 100] LieRing.ofAssociativeRing

variable {S G : Type*} [Fintype S] [DecidableEq S]

/-- The control generators of a completion: the conjugated Hamiltonians
`-i·U_g·H·U_g†`. -/
def controlGenerators (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    Set (Matrix S S ℂ) :=
  {A | ∃ g : G, A = (-Complex.I) • (U g * H * (U g)ᴴ)}

/-- **The dynamical control Lie algebra** `𝔏(H,U)`: the real Lie algebra generated by
the conjugated Hamiltonians inside the matrix algebra with the commutator bracket. -/
noncomputable def controlLie (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    LieSubalgebra ℝ (Matrix S S ℂ) :=
  LieSubalgebra.lieSpan ℝ (Matrix S S ℂ) (controlGenerators H U)

/-- The skew-Hermitian matrices `u(D)` as a real Lie subalgebra. -/
def skewHerm (S : Type*) [Fintype S] [DecidableEq S] :
    LieSubalgebra ℝ (Matrix S S ℂ) where
  carrier := {A | Aᴴ = -A}
  add_mem' := fun {A B} hA hB => by
    show (A + B)ᴴ = -(A + B)
    rw [Matrix.conjTranspose_add, hA, hB, neg_add]
  zero_mem' := by
    show (0 : Matrix S S ℂ)ᴴ = -0
    rw [Matrix.conjTranspose_zero, neg_zero]
  smul_mem' := fun r A hA => by
    show (r • A)ᴴ = -(r • A)
    rw [Matrix.conjTranspose_smul, star_trivial, hA, smul_neg]
  lie_mem' := fun {A B} hA hB => by
    show (A * B - B * A)ᴴ = -(A * B - B * A)
    rw [Matrix.conjTranspose_sub, Matrix.conjTranspose_mul,
      Matrix.conjTranspose_mul, hA, hB, Matrix.neg_mul, Matrix.mul_neg, neg_neg,
      Matrix.neg_mul, Matrix.mul_neg, neg_neg, neg_sub]

omit [DecidableEq S] in
/-- **Projective well-definedness, pointwise**: a global phase on a control leaves the
conjugated Hamiltonian unchanged. -/
theorem phase_conj_invariant (U H : Matrix S S ℂ) (lam : ℂ)
    (hlam : lam * conj' lam = 1) :
    (lam • U) * H * (lam • U)ᴴ = U * H * Uᴴ := by
  rw [Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.smul_mul,
    Matrix.mul_smul, smul_smul]
  rw [show star lam = conj' lam from rfl, hlam, one_smul]

omit [DecidableEq S] in
/-- Phase changes leave the generator set unchanged. -/
theorem controlGenerators_phase_invariant (H : Matrix S S ℂ)
    (U : G → Matrix S S ℂ) (lam : G → ℂ)
    (hlam : ∀ g, lam g * conj' (lam g) = 1) :
    controlGenerators H (fun g => lam g • U g) = controlGenerators H U := by
  ext A
  exact exists_congr fun g => by
    rw [phase_conj_invariant (U g) H (lam g) (hlam g)]

/-- **Projective well-definedness of 𝔏**: the 2-cocycle freedom of the H-functor
completion never moves the control Lie algebra. -/
theorem controlLie_phase_invariant (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (lam : G → ℂ) (hlam : ∀ g, lam g * conj' (lam g) = 1) :
    controlLie H (fun g => lam g • U g) = controlLie H U := by
  unfold controlLie
  rw [controlGenerators_phase_invariant H U lam hlam]

/-- Conjugation by a unitary is a real Lie algebra homomorphism of the matrix
algebra. -/
def conjLieHom (W : Matrix S S ℂ) (hW : W * Wᴴ = 1) :
    Matrix S S ℂ →ₗ⁅ℝ⁆ Matrix S S ℂ where
  toFun A := W * A * Wᴴ
  map_add' A B := by rw [Matrix.mul_add, Matrix.add_mul]
  map_smul' r A := by
    rw [Matrix.mul_smul, Matrix.smul_mul]
    rfl
  map_lie' := fun {A B} => by
    have hWW : Wᴴ * W = 1 := mul_eq_one_comm.mp hW
    have key : ∀ X Y : Matrix S S ℂ,
        (W * X * Wᴴ) * (W * Y * Wᴴ) = W * (X * Y) * Wᴴ := by
      intro X Y
      simp only [Matrix.mul_assoc]
      rw [show Wᴴ * (W * (Y * Wᴴ)) = Y * Wᴴ from by
        rw [← Matrix.mul_assoc, hWW, Matrix.one_mul]]
    show W * ⁅A, B⁆ * Wᴴ = ⁅W * A * Wᴴ, W * B * Wᴴ⁆
    rw [Ring.lie_def, Ring.lie_def, Matrix.mul_sub, Matrix.sub_mul, key, key]

/-- Conjugating back collapses: `W†(WAW†)W = A`. -/
theorem conj_conj_collapse (W A : Matrix S S ℂ) (hW : W * Wᴴ = 1) :
    Wᴴ * (W * A * Wᴴ) * W = A := by
  have hWW : Wᴴ * W = 1 := mul_eq_one_comm.mp hW
  calc Wᴴ * (W * A * Wᴴ) * W = (Wᴴ * W) * A * (Wᴴ * W) := by
        simp only [Matrix.mul_assoc]
    _ = A := by rw [hWW, Matrix.one_mul, Matrix.mul_one]

/-- **Gauge covariance, forward**: a common unitary gauge transports membership of the
control Lie algebra. -/
theorem controlLie_gauge_mem (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (W : Matrix S S ℂ) (hW : W * Wᴴ = 1) {x : Matrix S S ℂ}
    (hx : x ∈ controlLie H U) :
    W * x * Wᴴ ∈ controlLie (W * H * Wᴴ) (fun g => W * U g * Wᴴ) := by
  have hWW : Wᴴ * W = 1 := mul_eq_one_comm.mp hW
  have hle : controlLie H U ≤ LieSubalgebra.comap (conjLieHom W hW)
      (controlLie (W * H * Wᴴ) (fun g => W * U g * Wᴴ)) := by
    refine LieSubalgebra.lieSpan_le.mpr ?_
    rintro A ⟨g, rfl⟩
    show conjLieHom W hW ((-Complex.I) • (U g * H * (U g)ᴴ))
      ∈ controlLie (W * H * Wᴴ) (fun g => W * U g * Wᴴ)
    refine LieSubalgebra.subset_lieSpan ⟨g, ?_⟩
    show W * ((-Complex.I) • (U g * H * (U g)ᴴ)) * Wᴴ
      = (-Complex.I) • ((W * U g * Wᴴ) * (W * H * Wᴴ) * (W * U g * Wᴴ)ᴴ)
    rw [Matrix.mul_smul, Matrix.smul_mul]
    congr 1
    rw [Matrix.conjTranspose_mul, Matrix.conjTranspose_mul,
      Matrix.conjTranspose_conjTranspose]
    simp only [Matrix.mul_assoc]
    rw [show Wᴴ * (W * (H * (Wᴴ * (W * ((U g)ᴴ * Wᴴ))))) = H * ((U g)ᴴ * Wᴴ) from by
      rw [← Matrix.mul_assoc Wᴴ W, hWW, Matrix.one_mul,
        ← Matrix.mul_assoc Wᴴ W, hWW, Matrix.one_mul]]
  exact hle hx

/-- **Gauge covariance, both ways**: membership of the gauged algebra is equivalent to
membership of the original — dimension and fullness of `𝔏` are gauge invariants. -/
theorem controlLie_gauge_mem_iff (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (W : Matrix S S ℂ) (hW : W * Wᴴ = 1) (x : Matrix S S ℂ) :
    W * x * Wᴴ ∈ controlLie (W * H * Wᴴ) (fun g => W * U g * Wᴴ)
      ↔ x ∈ controlLie H U := by
  have hWW : Wᴴ * W = 1 := mul_eq_one_comm.mp hW
  have hWH : Wᴴ * Wᴴᴴ = 1 := by rw [Matrix.conjTranspose_conjTranspose]; exact hWW
  constructor
  · intro hx
    have h1 := controlLie_gauge_mem (W * H * Wᴴ) (fun g => W * U g * Wᴴ) Wᴴ hWH
      (x := W * x * Wᴴ) hx
    rw [Matrix.conjTranspose_conjTranspose] at h1
    rw [conj_conj_collapse W x hW] at h1
    rw [conj_conj_collapse W H hW] at h1
    rw [show (fun g => Wᴴ * (W * U g * Wᴴ) * W) = U from
      funext fun g => conj_conj_collapse W (U g) hW] at h1
    exact h1
  · exact controlLie_gauge_mem H U W hW

/-- **The skew-Hermitian bound**: for a Hermitian passive Hamiltonian and unitary
controls, the control Lie algebra lies inside `u(D)`. -/
theorem controlLie_le_skewHerm (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (hH : Hᴴ = H) :
    controlLie H U ≤ skewHerm S := by
  refine LieSubalgebra.lieSpan_le.mpr ?_
  rintro A ⟨g, rfl⟩
  show ((-Complex.I) • (U g * H * (U g)ᴴ))ᴴ = -((-Complex.I) • (U g * H * (U g)ᴴ))
  rw [Matrix.conjTranspose_smul, Matrix.conjTranspose_mul,
    Matrix.conjTranspose_mul, Matrix.conjTranspose_conjTranspose, hH,
    Matrix.mul_assoc]
  rw [show star (-Complex.I) = Complex.I from by
    rw [star_neg, Complex.star_def, Complex.conj_I, neg_neg]]
  rw [← neg_smul, neg_neg]

/-- A unitary's inverse is its conjugate transpose. -/
theorem unitary_inv_eq_conjTranspose {W : Matrix S S ℂ} (hW : W * Wᴴ = 1) :
    W⁻¹ = Wᴴ :=
  Matrix.inv_eq_right_inv hW

/-- The exponential intertwines with unitary conjugation. -/
theorem unitary_exp_conj (W A : Matrix S S ℂ) (hW : W * Wᴴ = 1) :
    NormedSpace.exp (W * A * Wᴴ) = W * NormedSpace.exp A * Wᴴ := by
  have hunit : IsUnit W := ⟨⟨W, Wᴴ, hW, mul_eq_one_comm.mp hW⟩, rfl⟩
  have hinv := unitary_inv_eq_conjTranspose hW
  rw [← hinv]
  exact Matrix.exp_conj W A hunit

/-- **THE CONJUGATED-FLOW IDENTITY**: `U·e^{-itH}·U† = e^{-it·UHU†}` — the group
generated by the passive flow and the controls contains the flow of every conjugated
Hamiltonian, so the control generators are reachable directions. -/
theorem conjugated_flow (U H : Matrix S S ℂ) (hU : U * Uᴴ = 1) (t : ℝ) :
    U * NormedSpace.exp ((-(t : ℂ) * Complex.I) • H) * Uᴴ
      = NormedSpace.exp ((-(t : ℂ) * Complex.I) • (U * H * Uᴴ)) := by
  rw [show (-(t : ℂ) * Complex.I) • (U * H * Uᴴ)
      = U * ((-(t : ℂ) * Complex.I) • H) * Uᴴ from by
    rw [Matrix.mul_smul, Matrix.smul_mul]]
  exact (unitary_exp_conj U _ hU).symm

/-- The real line through one generator, as a Lie subalgebra. -/
def lineOf (x₀ : Matrix S S ℂ) : LieSubalgebra ℝ (Matrix S S ℂ) where
  carrier := {y | ∃ r : ℝ, y = r • x₀}
  add_mem' := fun {A B} hA hB => by
    obtain ⟨r, rfl⟩ := hA
    obtain ⟨r', rfl⟩ := hB
    exact ⟨r + r', (add_smul r r' x₀).symm⟩
  zero_mem' := ⟨0, (zero_smul ℝ x₀).symm⟩
  smul_mem' := fun c A hA => by
    obtain ⟨r, rfl⟩ := hA
    exact ⟨c * r, (mul_smul c r x₀).symm⟩
  lie_mem' := fun {A B} hA hB => by
    obtain ⟨r, rfl⟩ := hA
    obtain ⟨r', rfl⟩ := hB
    refine ⟨0, ?_⟩
    rw [smul_lie, lie_smul, lie_self, smul_zero, smul_zero, zero_smul]

/-- **THE NO-CONTROLS COLLAPSE**: when every control fixes the Hamiltonian by
conjugation, the dynamical Lie algebra is the real line through `-iH` — while on the
same carrier the accessible *-algebra of Heisenberg-evolved readouts can already be
all of `M_D(ℂ)` (`AccessibleAlgebra.native_menu_generates`). Algebra generation and
dynamical controllability are distinct notions. -/
theorem controlLie_trivial [Nonempty G] (H : Matrix S S ℂ)
    (U : G → Matrix S S ℂ) (hU : ∀ g, U g * H * (U g)ᴴ = H) (y : Matrix S S ℂ) :
    y ∈ controlLie H U ↔ ∃ r : ℝ, y = r • ((-Complex.I) • H) := by
  have hgen : controlGenerators H U = {(-Complex.I) • H} := by
    ext A
    constructor
    · rintro ⟨g, rfl⟩
      rw [hU g]
      rfl
    · intro hA
      exact ⟨Classical.arbitrary G, by rw [hU, hA]⟩
  constructor
  · intro hy
    have hle : controlLie H U ≤ lineOf ((-Complex.I) • H) := by
      refine LieSubalgebra.lieSpan_le.mpr ?_
      rw [hgen]
      rintro A hA
      exact ⟨1, by rw [hA, one_smul]⟩
    exact hle hy
  · rintro ⟨r, rfl⟩
    refine (controlLie H U).smul_mem r ?_
    refine LieSubalgebra.subset_lieSpan ?_
    rw [hgen]
    rfl

#print axioms phase_conj_invariant
#print axioms controlGenerators_phase_invariant
#print axioms controlLie_phase_invariant
#print axioms conj_conj_collapse
#print axioms controlLie_gauge_mem
#print axioms controlLie_gauge_mem_iff
#print axioms controlLie_le_skewHerm
#print axioms unitary_inv_eq_conjTranspose
#print axioms unitary_exp_conj
#print axioms conjugated_flow
#print axioms controlLie_trivial

end ControlLie
end OIBridge
