import OIBridge.DerivedQ3

/-!
# The executability-source audit — does the substratum's dynamics with the stated access make
one layer flow executable?

The preregistered pass of `EXEC-SOURCE-AUDIT.md`. The kernel content is four groups of theorems;
the census of the corpus is in the note.

* T1, the necessary condition: a theory generated by an architecture that executes the layer flow
  of an involution with a moved configuration has a non-monomial admissible operator at level one,
  and the architecture is not configuration-level (`exists_nonMonomial_of_layerFlowExecutable`,
  `not_configurationLevel_of_layerFlowExecutable`).
* T2, the actual layers: the observer theory of every substratum executes no layer flow of an
  involution with a moved configuration, its own shear and swap layers included; the swap layer of
  the wave substratum moves a configuration for every nontrivial alphabet, so the wave substratum's
  observer theory does not execute its own swap-layer flow (`obs_not_layerFlowExecutable`,
  `obs_not_layerFlowExecutable_shear`, `obs_not_layerFlowExecutable_swap`,
  `waveSubstratum_swap_moves`, `waveSubstratum_not_layerFlowExecutable_swap`).
* T3, the write access with a continuous parameter: no bijection-level class, the classes the
  read-write families generate included, derives executability (`bijectionLevel_not_layerFlowExecutable`).
* T4, the path is not an operation: in the theory of every configuration-level class the gate flow
  is unavailable at level one and time one half, the substratum theory included
  (`configurationLevel_not_avail_gateFlow_half`, `substratumTheory_not_avail_gateFlow_half`).
* T6, the countercontrols: the gate flow at time one half is not monomial, so the ones-fixing
  class, which contains it, is not configuration-level and the necessary condition of T1 is not
  vacuous (`gateFlow_half_not_monomial`, `onesClass_not_configurationLevel`).

Not claimed: that the observer-level lift is or is not derivable; that a non-monomial admissible
operator suffices for the gate flow of a layer; anything about the phase; anything about a
richer observer architecture than the stated one; anything about a manuscript.
-/

namespace OIBridge
namespace ExecSource

open Complex Matrix CoherentLift SpectatorBridge OperationalAssembly AncillaClosure
open MonoidalCompletion InterventionLocality MicroReversibility PrimitiveSource LieRankSource
open DiagonalTheory SubstratumInterface StructuralClosure MinimalRepertoire LevelOneSeam
open PhysicalCharacterization RouteB ManuscriptAxioms LiftAudit SubstratumInterfaceAudit
open InstrumentRealization SecondOrderCircuit

/-! ### Section A — T1: the necessary condition -/

section Necessity

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T1 — EXECUTABILITY NEEDS A NON-MONOMIAL ADMISSIBLE OPERATOR AT LEVEL ONE**: the flow at
time one half does not preserve diagonal states, and it is a finite sum of admissible
conjugations, so one of them is by a non-monomial operator. -/
theorem exists_nonMonomial_of_layerFlowExecutable {𝓘 : ImplementationClass}
    (arch : Architecture 𝓘) {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x)
    (hex : LayerFlowExecutable (genTheory 𝓘 arch S) σ) :
    ∃ K : Matrix (S × Fin 1) (S × Fin 1) ℂ, 𝓘 (S × Fin 1) K ∧ ¬ IsMonomial K := by
  by_contra hno
  have hall : ∀ K : Matrix (S × Fin 1) (S × Fin 1) ℂ, 𝓘 (S × Fin 1) K → IsMonomial K :=
    fun K hK => by
      by_contra hm
      exact hno ⟨K, hK, hm⟩
  have hav := hex 1 (1 / 2 : ℝ)
  obtain ⟨ι, _, K, hK, hadm⟩ := realized_of_instAvail arch hav ()
  have hK' : conjChannel (gateFlow (levelPerm σ 1) (1 / 2 : ℝ)) = ∑ i, conjChannel (K i) := hK
  have hx' : levelPerm σ 1 (x, 0) ≠ (x, 0) := by
    rw [levelPerm_apply]
    intro hc
    exact hx (Prod.mk.inj hc).1
  apply gateFlow_half_not_preservesDiag hx'
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_monomial (hall _ (hadm i))

/-- **T1 — THE GENERATING CLASS IS NOT CONFIGURATION-LEVEL.** -/
theorem not_configurationLevel_of_layerFlowExecutable {𝓘 : ImplementationClass}
    (arch : Architecture 𝓘) {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x)
    (hex : LayerFlowExecutable (genTheory 𝓘 arch S) σ) : ¬ ConfigurationLevel 𝓘 :=
  fun h => configurationLevel_not_layerFlowExecutable arch h hx hex

end Necessity

/-! ### Section B — T3 and T4: the write access, and the path -/

section Access

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T3 — NO BIJECTION-LEVEL CLASS DERIVES EXECUTABILITY**: the read-write operators are
permutation matrices at every parameter value, and every class of scaled partial permutations is
configuration-level. -/
theorem bijectionLevel_not_layerFlowExecutable {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
    (hb : BijectionLevel 𝓘) {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) :
    ¬ LayerFlowExecutable (genTheory 𝓘 arch S) σ :=
  configurationLevel_not_layerFlowExecutable arch (bijectionLevel_configurationLevel hb) hx

/-- **T4 — THE PATH IS NOT AN OPERATION**: in the theory of a configuration-level class the gate
flow of an involution with a moved configuration is unavailable at level one and time one half,
the one time at which the lift audit tests it. -/
theorem configurationLevel_not_avail_gateFlow_half {𝓘 : ImplementationClass}
    (arch : Architecture 𝓘) (h : ConfigurationLevel 𝓘) {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) :
    ¬ (genTheory 𝓘 arch S).availExt 1 Unit
        (fun _ => conjChannel (gateFlow (levelPerm σ 1) (1 / 2 : ℝ))) := by
  intro hav
  obtain ⟨ι, _, K, hK, hadm⟩ := realized_of_instAvail arch hav ()
  have hK' : conjChannel (gateFlow (levelPerm σ 1) (1 / 2 : ℝ)) = ∑ i, conjChannel (K i) := hK
  have hx' : levelPerm σ 1 (x, 0) ≠ (x, 0) := by
    rw [levelPerm_apply]
    intro hc
    exact hx (Prod.mk.inj hc).1
  apply gateFlow_half_not_preservesDiag hx'
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_monomial (h _ _ (hadm i))

/-- **T4 — IN THE SUBSTRATUM THEORY** the gate flow at time one half is unavailable. -/
theorem substratumTheory_not_avail_gateFlow_half {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) :
    ¬ (substratumTheory S).availExt 1 Unit
        (fun _ => conjChannel (gateFlow (levelPerm σ 1) (1 / 2 : ℝ))) :=
  configurationLevel_not_avail_gateFlow_half substratumClass_arch
    substratumClass_configurationLevel hx

end Access

/-! ### Section C — T2: the actual substratum and its layers -/

section Observer

variable (𝒮 : Substratum) [Fintype 𝒮.ι] [Fintype 𝒮.V] [DecidableEq 𝒮.V]

/-- **T2 — THE OBSERVER THEORY EXECUTES NO LAYER FLOW** of an involution with a moved
configuration: it lies inside the substratum theory, which executes none. -/
theorem obs_not_layerFlowExecutable {g : Equiv.Perm 𝒮.Conf} {x : 𝒮.Conf} (hx : g x ≠ x) :
    ¬ LayerFlowExecutable (obsTheory 𝒮) g := by
  intro hex
  apply substratumTheory_not_layerFlowExecutable hx
  intro n t
  exact obs_availExt_le_substratum 𝒮 _ (hex n t)

/-- **T2 — NOT ITS OWN SHEAR LAYER'S FLOW**, when the shear layer moves a configuration. -/
theorem obs_not_layerFlowExecutable_shear {x : 𝒮.Conf} (hx : shearEquiv 𝒮.R.F x ≠ x) :
    ¬ LayerFlowExecutable (obsTheory 𝒮) (shearEquiv 𝒮.R.F) :=
  obs_not_layerFlowExecutable 𝒮 hx

/-- **T2 — NOT ITS OWN SWAP LAYER'S FLOW**, when the swap layer moves a configuration. -/
theorem obs_not_layerFlowExecutable_swap {x : 𝒮.Conf} (hx : (swapEquiv : 𝒮.Conf ≃ 𝒮.Conf) x ≠ x) :
    ¬ LayerFlowExecutable (obsTheory 𝒮) (swapEquiv : 𝒮.Conf ≃ 𝒮.Conf) :=
  obs_not_layerFlowExecutable 𝒮 hx

end Observer

section Wave

variable (d L q : ℕ)

/-- **THE SWAP LAYER OF THE WAVE SUBSTRATUM MOVES A CONFIGURATION** for a nontrivial alphabet:
the configuration with `(0, 1)` at every site. -/
theorem waveSubstratum_swap_moves [Fact (1 < q)] (α : ZMod q) :
    ∃ x : (waveSubstratum d L q α).Conf,
      (swapEquiv : (waveSubstratum d L q α).Conf ≃ (waveSubstratum d L q α).Conf) x ≠ x := by
  refine ⟨fun _ => ((0 : ZMod q), (1 : ZMod q)), fun h => ?_⟩
  have h' : ((1 : ZMod q), (0 : ZMod q)) = ((0 : ZMod q), (1 : ZMod q)) := congrFun h (fun _ => 0)
  exact one_ne_zero (Prod.mk.inj h').1

instance [NeZero L] : Fintype (waveSubstratum d L q α).ι := inferInstanceAs (Fintype (Fin d → ZMod L))
instance [NeZero q] : Fintype (waveSubstratum d L q α).V := inferInstanceAs (Fintype (ZMod q))
instance : DecidableEq (waveSubstratum d L q α).V := inferInstanceAs (DecidableEq (ZMod q))

/-- **T2 — THE WAVE SUBSTRATUM'S OBSERVER THEORY DOES NOT EXECUTE ITS OWN SWAP-LAYER FLOW.** -/
theorem waveSubstratum_not_layerFlowExecutable_swap [NeZero L] [NeZero q] [Fact (1 < q)]
    (α : ZMod q) :
    ¬ LayerFlowExecutable (obsTheory (waveSubstratum d L q α))
      (swapEquiv : (waveSubstratum d L q α).Conf ≃ (waveSubstratum d L q α).Conf) := by
  obtain ⟨x, hx⟩ := waveSubstratum_swap_moves d L q α
  exact obs_not_layerFlowExecutable_swap _ hx

end Wave

/-! ### Section D — T6: the countercontrols -/

section Countercontrol

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **THE GATE FLOW AT TIME ONE HALF IS NOT MONOMIAL**: its column at a moved configuration has
two nonzero entries. -/
theorem gateFlow_half_not_monomial {σ : Equiv.Perm S} {a : S} (ha : σ a ≠ a) :
    ¬ IsMonomial (gateFlow σ (1 / 2 : ℝ)) := by
  rintro ⟨τ, d, hK⟩
  obtain ⟨h1, h2⟩ := gateFlow_half_entries ha
  rw [hK, monomial_entry] at h1 h2
  by_cases hτ : τ a = a
  · rw [if_neg (by rw [hτ]; exact Ne.symm ha)] at h2
    have := congrArg Complex.re h2
    norm_num at this
  · rw [if_neg hτ] at h1
    have := congrArg Complex.re h1
    norm_num at this

/-- **C — THE ONES-FIXING CLASS IS NOT CONFIGURATION-LEVEL**: it contains the gate flow of the
exchange on two states at time one half, which is not monomial; the necessary condition of T1 is
not vacuous. -/
theorem onesClass_not_configurationLevel : ¬ ConfigurationLevel onesClass := by
  intro h
  have hσ : ∀ x : Fin 2, Equiv.swap (0 : Fin 2) 1 (Equiv.swap 0 1 x) = x :=
    fun x => Equiv.swap_apply_self _ _ _
  have ha : Equiv.swap (0 : Fin 2) 1 0 ≠ 0 := by simp
  exact gateFlow_half_not_monomial ha (h _ _ (onesClass_gateFlow hσ (1 / 2 : ℝ)))

end Countercontrol

#print axioms exists_nonMonomial_of_layerFlowExecutable
#print axioms not_configurationLevel_of_layerFlowExecutable
#print axioms bijectionLevel_not_layerFlowExecutable
#print axioms configurationLevel_not_avail_gateFlow_half
#print axioms substratumTheory_not_avail_gateFlow_half
#print axioms obs_not_layerFlowExecutable
#print axioms obs_not_layerFlowExecutable_shear
#print axioms obs_not_layerFlowExecutable_swap
#print axioms waveSubstratum_swap_moves
#print axioms waveSubstratum_not_layerFlowExecutable_swap
#print axioms gateFlow_half_not_monomial
#print axioms onesClass_not_configurationLevel

end ExecSource
end OIBridge
