import OIBridge.InstrumentRealization

/-!
# The flow-endpoint audit — the executable layer flow on the sourced baseline

The preregistered pass of `FLOW-ENDPOINT-AUDIT.md`, on the migrated semantics: availability in an
implementation-generated theory is instrument realization by the class. The test theory is
`onesTheory A := genTheory onesClass onesClass_arch A`, the theory the closed-form ones-fixing
class generates.

* F1, the sourced closure: `onesTheory` satisfies `SourcedOI` on every carrier
  (`onesTheory_sourcedOI`), every conjunct being a single admissible step.
* F2, executability: the gate flow of every layer involution is available at every level and
  time (`onesTheory_layerFlowExecutable`).
* F3, the endpoint, negative at level two: on every carrier with a third point no pair's
  quarter-turn transition flow is available (`onesTheory_no_quarter_flow`), so `onesTheory (Fin 2)`
  fails `PhaseFreeRichness` at level two, where the carrier has four states
  (`onesTheory_not_phaseFree`).
* F4, the endpoint theorem: `SourcedOI ∧ LayerFlowExecutable ⇏ PhaseFreeRichness`
  (`flow_endpoint_refuted`, and `flow_endpoint_refuted_general` on every carrier with at least two
  states).
* F5, the absence of phases: the countermodel carries no quarter phase, so it fails
  `PhasesAvailable` and `DerivedOI`, and that absence witnesses its failure of `SubstratumAvail`,
  with the full gap to the substratum's availability not characterized; consistent with the lift
  audit's Q3′, whose hypothesis it does not meet; and it is not quantum mechanics (`onesTheory_not_phasesAvailable`, `onesTheory_not_derivedOI`,
  `onesTheory_not_substratumAvail`, `onesTheory_not_qm`).

Not claimed: anything about the lift audit's preregistered Q3, from `DerivedOI`; the least class of
one layer involution, which is not defined; the minimality of `onesTheory` among countermodels;
that relative phase is the unique or minimal resource the witness lacks.
-/

namespace OIBridge
namespace FlowEndpoint

open Complex Matrix OperationalAssembly MonoidalCompletion SpectatorBridge InterventionLocality
open MicroReversibility LieRankSource
open SubstratumInterfaceAudit RouteB LiftAudit MinimalRepertoire ReadWriteControl LevelOneSeam
open PhysicalCharacterization InstrumentRealization

open scoped ComplexOrder

/-! ### Section A — the test theory -/

section Theory

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **THE ONES-FIXING THEORY**: the theory generated by the closed-form class of contractive
compressions of all-ones-fixing unitaries. -/
noncomputable abbrev onesTheory (A : Type) [Fintype A] [DecidableEq A] :
    FiniteOperationalTheory A :=
  genTheory onesClass onesClass_arch A

/-- An admissible isometry's conjugation is available in the ones-fixing theory as one step. -/
theorem onesTheory_avail_conj {n : ℕ} {V : Matrix (A × Fin n) (A × Fin n) ℂ}
    (hV : onesClass (A × Fin n) V) (hiso : Vᴴ * V = 1) :
    (onesTheory A).availExt n Unit (fun _ => conjChannel V) :=
  InstAvail.op V hV hiso

/-- **F1 — THE ONES-FIXING THEORY SATISFIES THE SOURCED CLOSURE** on every carrier. -/
theorem onesTheory_sourcedOI : SourcedOI (onesTheory A) :=
  ⟨genTheory_reversibleImplementationLocality onesClass onesClass_arch onesClass_contextStable
      onesClass_labelInvariant onesClass_daggerStable,
    genTheory_embeddedObservation onesClass onesClass_arch onesClass_labelInvariant,
    fun _ a b => onesTheory_avail_conj (onesClass_permMatrix (Equiv.swap a b)) (permMatrix_isometry _),
    fun _ _ _ F l => by
      rw [readWriteOperator_eq_perm]
      exact onesTheory_avail_conj (onesClass_permMatrix _) (permMatrix_isometry _)⟩

end Theory

/-! ### Section B — executability -/

section Executable

variable {S : Type} [Fintype S] [DecidableEq S]

omit [Fintype S] [DecidableEq S] in
/-- The layer involution read at any level is an involution. -/
theorem levelPerm_involutive {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) (n : ℕ)
    (p : S × Fin n) : levelPerm σ n (levelPerm σ n p) = p := by
  simp [levelPerm_apply, hσ]

/-- **F2 — THE ONES-FIXING THEORY EXECUTES EVERY LAYER FLOW**: the gate flow of an involution
fixes the all-ones vector, so it is one admissible step at every level and time. -/
theorem onesTheory_layerFlowExecutable {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) :
    LayerFlowExecutable (onesTheory S) σ :=
  fun n t => onesTheory_avail_conj (onesClass_gateFlow (levelPerm_involutive hσ n) t)
    (gateFlow_unitary (levelPerm_involutive hσ n) t)

end Executable

/-! ### Section C — the endpoint, negative at level two -/

section Endpoint

/-- A carrier with at least three points has a point distinct from any two. -/
theorem exists_third {α : Type} [Fintype α] [DecidableEq α] (h : 3 ≤ Fintype.card α) (a b : α) :
    ∃ c, c ≠ a ∧ c ≠ b := by
  by_contra hne
  have hall : ∀ c : α, c ≠ a → c = b := fun c hc => by
    by_contra hcb
    exact hne ⟨c, hc, hcb⟩
  have hsub : (Finset.univ : Finset α) ⊆ {a, b} := fun c _ => by
    by_cases hc : c = a
    · simp [hc]
    · simp [hall c hc]
  have h1 := Finset.card_le_card hsub
  have h2 : ({a, b} : Finset α).card ≤ 2 := Finset.card_le_two
  rw [Finset.card_univ] at h1
  omega

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **F3 — NO PAIR IS DRIVEN THROUGH A QUARTER TURN** on a carrier with a third point: every
available unitary conjugation of the ones-fixing theory fixes the all-ones vector up to a scalar
and the transition flow at a quarter turn moves it. -/
theorem onesTheory_no_quarter_flow {n : ℕ} {a b c : A × Fin n} (hab : a ≠ b) (hca : c ≠ a)
    (hcb : c ≠ b) :
    ¬ (onesTheory A).availExt n Unit
      (fun _ => conjChannel (ReachabilitySeam.flow (transition a b) (Real.pi / 2))) :=
  fun h => (flow_realized_not_instrumentRealized hab hca hcb).2 h

/-- **F3 — THE ONES-FIXING THEORY FAILS PHASE-FREE RICHNESS AT LEVEL TWO** on every carrier
with at least two states: the level-two carrier has at least four states, so every pair has a
third point. -/
theorem onesTheory_not_phaseFree_general (h2 : 2 ≤ Fintype.card A) :
    ¬ PhaseFreeRichness (onesTheory A) := by
  intro h
  have hcard : 2 ≤ Fintype.card (A × Fin 2) := by
    rw [Fintype.card_prod, Fintype.card_fin]
    omega
  obtain ⟨⟨a, b, hab, hflow⟩, -⟩ := h 2 hcard
  have h3 : 3 ≤ Fintype.card (A × Fin 2) := by
    rw [Fintype.card_prod, Fintype.card_fin]
    omega
  obtain ⟨c, hca, hcb⟩ := exists_third h3 a b
  exact onesTheory_no_quarter_flow hab hca hcb (hflow (Real.pi / 2))

/-- **F3 — ON THE TWO-STATE CARRIER**, at level two. -/
theorem onesTheory_not_phaseFree : ¬ PhaseFreeRichness (onesTheory (Fin 2)) :=
  onesTheory_not_phaseFree_general (by simp)

/-- **F4 — THE ENDPOINT IS REFUTED**: on the two-state carrier, a theory with the sourced
closure and the executable layer flow of the exchange and without phase-free richness. -/
theorem flow_endpoint_refuted :
    ∃ T : FiniteOperationalTheory (Fin 2),
      SourcedOI T ∧ LayerFlowExecutable T (Equiv.swap 0 1) ∧ ¬ PhaseFreeRichness T :=
  ⟨onesTheory (Fin 2), onesTheory_sourcedOI,
    onesTheory_layerFlowExecutable (fun x => Equiv.swap_apply_self _ _ x), onesTheory_not_phaseFree⟩

/-- **F4 — THE GENERAL FORM**: on every carrier with at least two states and for every layer
involution. -/
theorem flow_endpoint_refuted_general (h2 : 2 ≤ Fintype.card A) {σ : Equiv.Perm A}
    (hσ : ∀ x, σ (σ x) = x) :
    SourcedOI (onesTheory A) ∧ LayerFlowExecutable (onesTheory A) σ
      ∧ ¬ PhaseFreeRichness (onesTheory A) :=
  ⟨onesTheory_sourcedOI, onesTheory_layerFlowExecutable hσ, onesTheory_not_phaseFree_general h2⟩

end Endpoint

/-! ### Section D — the absence of phases -/

section Location

variable {A : Type} [Fintype A] [DecidableEq A]

/-- The quarter phase carries the all-ones vector to the vector with `i` at its state and `1`
elsewhere. -/
theorem phaseGate_mulVec_ones {S : Type} [Fintype S] [DecidableEq S] (a : S) (p : S) :
    (phaseGate a *ᵥ ones S) p = if a = p then Complex.I else 1 := by
  rw [phaseGate, Matrix.mulVec_diagonal, ones_apply, mul_one]

/-- **F5 — THE ONES-FIXING THEORY CARRIES NO QUARTER PHASE** on a carrier with at least two
states: the phase moves the all-ones vector off its ray. -/
theorem onesTheory_not_phasesAvailable (h2 : 2 ≤ Fintype.card A) :
    ¬ PhasesAvailable (onesTheory A) := by
  intro hp
  obtain ⟨a₀, b₀, hab⟩ := Fintype.exists_pair_of_one_lt_card (by omega : 1 < Fintype.card A)
  set a : A × Fin 1 := (a₀, 0) with ha
  set b : A × Fin 1 := (b₀, 0) with hb
  have hne : a ≠ b := fun h => hab (Prod.mk.inj h).1
  obtain ⟨z, hz⟩ := instAvail_unitary_fixes_ones isometry_fixes_ones (phaseGate_unitary a) (hp 1 a)
  have h1 := congrFun hz a
  have h2' := congrFun hz b
  rw [phaseGate_mulVec_ones, Pi.smul_apply, ones_apply, smul_eq_mul, mul_one] at h1 h2'
  simp only [if_true] at h1
  rw [if_neg hne] at h2'
  have := congrArg Complex.im (h1.trans h2'.symm)
  simp at this

/-- **F5 — THE ONES-FIXING THEORY FAILS THE CONSEQUENCE CLOSURE**, the phases witnessing it. -/
theorem onesTheory_not_derivedOI (h2 : 2 ≤ Fintype.card A) : ¬ DerivedOI (onesTheory A) :=
  fun h => onesTheory_not_phasesAvailable h2 h.2.2.2.1

/-- **F5 — THE ONES-FIXING THEORY FAILS THE SUBSTRATUM'S AVAILABILITY**, the absence of phases
witnessing it and the full gap not characterized: the countermodel is consistent with the lift
audit's Q3′, whose hypothesis it does not meet. -/
theorem onesTheory_not_substratumAvail (h2 : 2 ≤ Fintype.card A) :
    ¬ SubstratumAvail (onesTheory A) :=
  fun h => onesTheory_not_phasesAvailable h2 (substratumAvail_phasesAvailable h)

/-- **F5 — THE ONES-FIXING THEORY IS NOT QUANTUM MECHANICS** on the two-state carrier. -/
theorem onesTheory_not_qm : ¬ ExactAllFiniteEndomorphicQuantumOps (onesTheory (Fin 2)) :=
  fun h => onesTheory_not_phaseFree ((sourcedOI_qm_iff_phaseFree onesTheory_sourcedOI).mp h)

end Location

#print axioms onesTheory_avail_conj
#print axioms onesTheory_sourcedOI
#print axioms levelPerm_involutive
#print axioms onesTheory_layerFlowExecutable
#print axioms exists_third
#print axioms onesTheory_no_quarter_flow
#print axioms onesTheory_not_phaseFree_general
#print axioms onesTheory_not_phaseFree
#print axioms flow_endpoint_refuted
#print axioms flow_endpoint_refuted_general
#print axioms phaseGate_mulVec_ones
#print axioms onesTheory_not_phasesAvailable
#print axioms onesTheory_not_derivedOI
#print axioms onesTheory_not_substratumAvail
#print axioms onesTheory_not_qm

end FlowEndpoint
end OIBridge
