/-
  OIBridge/ImplementationLocality.lean — the primitive-source audit, second target: the
  source of observational independence.

  ROUND FIFTY-SEVEN. After round fifty-six the carrier-general quantum-complete package is
  composite operational validity, observational independence, reversible richness and
  embedded observation. This file asks where observational independence comes from, in the
  order the audit demands: first whether it is already forced by the other three; then, since
  it is not, what deeper principle supplies it.

  A. THE REDUNDANCY TEST FAILS. The round-34 countermodel (`countermodel`: Kraus families on
  the qubit, 2-positive trace-preserving instruments on every composite) carries the OI
  core, composite operational validity and reversible richness, and it carries EMBEDDED
  OBSERVATION: the 2-positive-instrument theory on every finite carrier (`twoPosTheory`,
  `twoPosFamily`) is a regrouping- and relabelling-invariant family whose qubit member is
  the countermodel on the composites and, by `twoPositive_qubit_cp`, on the system. And it
  has no observational independence (`countermodel_not_inert`). So
  `redundancy_fails`: validity + reversible richness + embedded observation do not imply
  observational independence, and the four-part package does not compress to three.

  B/C. FORM WITHOUT EXISTENCE. Round thirty-seven proved that locality fixes the form of a
  spectator extension uniquely (`isSpectatorExtension_iff`: any extension of `Φ` along `e`
  is `withSpectator R e Φ`), and the countermodel shows that the form being fixed does not
  make the extension available: `form_fixed_existence_fails` records, for the available
  two-qubit reduction map, that its qutrit spectator extension is uniquely determined and
  not available. The missing physics is existence, not form.

  D. THE PRIMITIVE, BELOW AVAILABILITY. An IMPLEMENTATION CLASS `𝓘` says, at every finite
  carrier, which single operators are admissible physical implementations
  (`ImplementationClass`). A family of operations with outcomes is INSTRUMENT-REALIZED by the
  class (`InstAvail`) when it is built from one admissible isometric step, the native readout
  of a register with admissible projectors, classical coarse-graining, sequential composition
  with outcome-dependent continuation, and the discard of a uniformly attached ancilla, by
  exactly those five constructors and no sum: the branches of a realized family arise together
  as the outcomes of one protocol. The aggregate trace is a theorem of the predicate
  (`instAvail_trace`), not a clause. Then

      (G) IMPLEMENTATION GENERATION — at every positive level, a family is available exactly
          when it is instrument-realized by the class (`ImplementationGenerated`);
      (C) CONTEXT STABILITY — adjoining dynamically uncoupled degrees of freedom leaves an
          admissible implementation admissible and unchanged on its original support:
          `𝓘 S K → 𝓘 (R × S) (1_R ⊗ K)` (`ContextStable`);
      (L) LABEL INVARIANCE — admissibility is transported along carrier bijections
          (`LabelInvariant`).

  `ImplementationLocality T` is the existence of such a class. Neither (C) nor (L) mentions
  availability, `withSpectator`, `HasParallelReferenceExtension` or
  `InertSpectatorCompositionality`; (G) mentions availability only to say that it is
  generated by implementations. The BRANCH-WISE notion, an operation as a finite sum of
  conjugations by admissible operators (`Realized`), is kept as the comparison object: for an
  ARCHITECTURE, a class closed under identity, product, contractive scalar, ancilla projector
  and ancilla block (`Architecture`), every branch of an instrument-realized family is
  branch-realized (`realized_of_instAvail`), and every branch is completely positive for every
  class (`cp_of_instAvail`). An architecture GENERATES a finite operational theory on every
  carrier (`genTheory`), with embedded observation when the class is label-invariant
  (`genTheory_embeddedObservation`).

  E. THE DERIVATION. The predicate is transported along carrier bijections for a
  label-invariant class (`instAvail_transport`) and closed under an uncoupled spectator for a
  context-stable, label-invariant class (`instAvail_spectator`): the step becomes the step by
  `1 ⊗ K`, the readout the readout of the same register beside the spectator, the discard
  regroups the fresh ancilla past the spectator. So the spectator extension of an available
  family is available (`instAvail_withSpectator`) and
  `observationalIndependence_of_implementationLocality` follows. Validity is derived as well
  (`validity_of_implementationLocality`): every branch is completely positive and the trace is
  preserved in aggregate.

  F. NECESSITY. Exact finite operational QM is implementation-local with every operator
  admissible (`implementationLocality_of_qm`): every finite Kraus family is the Stinespring
  circuit of the theory of the full class (`instAvail_fullClass_of_krausFamily`).

  THE DIAGNOSIS. The countermodel is not implementation-generated by ANY class
  (`countermodel_not_implementationGenerated`): its available reduction map is not
  completely positive, so no finite physical implementation realizes it. Its failure is
  implementability, not context stability. `implementationLocality_independent` records that
  the core, validity, reversible richness and embedded observation do not supply
  implementation locality.

  THE COMPRESSED SET. `OIPlusLocal` is implementation locality, reversible richness and
  embedded observation; `carrier_general_oiPlusLocal` proves it equivalent to exact finite
  endomorphic operational QM on every nonempty finite carrier. Validity is absent because it
  is derived; the normalization half of validity is a theorem of instrument realization
  (`instAvail_trace`), and that is said plainly rather than hidden.

  WHAT IS NOT CLAIMED. Whether context stability is redundant given implementation
  generation (a theory generated by a class not closed under `1 ⊗ ·` and failing
  observational independence) is not settled here. The converse from observational
  independence to implementation locality is not claimed outside the OI⁺ context. Nothing
  here bears on the sources of either clause of reversible richness.
-/

import OIBridge.EmbeddedObservation

namespace OIBridge
namespace InterventionLocality

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource IsometryExtension

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — the redundancy test fails: the 2-positive family -/

section TwoPos

/-- **THE 2-POSITIVE-INSTRUMENT THEORY** on an arbitrary finite carrier: 2-positive branches
with the trace preserved in aggregate, on the system and on every composite. -/
noncomputable def twoPosTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S where
  avail := fun _ _ _ F => IsTwoPositiveInstrument F
  availExt := fun _ _ _ _ F => IsTwoPositiveInstrument F
  avail_id := ⟨fun _ => by rw [← conjChannel_one]; exact conjChannel_twoPositive _, fun X => by
    rw [Fintype.sum_unique, LinearMap.id_apply]⟩
  avail_coarse := by
    rintro O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => isTwoPositive_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_coarse := by
    rintro n O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => isTwoPositive_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_bind := by
    rintro n O O' _ _ _ _ F G ⟨hF2, hFtr⟩ hG
    refine ⟨fun c => isTwoPositive_comp ((hG c.1).1 c.2) (hF2 c.1), fun X => ?_⟩
    rw [Fintype.sum_prod_type]
    show ∑ a, ∑ b, ((G a b) ((F a) X)).trace = X.trace
    rw [Finset.sum_congr rfl fun a _ => (hG a).2 ((F a) X)]
    exact hFtr X
  prepAvail := fun n P => 0 < n ∧ ∃ Φ, IsTwoPositiveInstrument (fun _ : Unit => Φ)
    ∧ P = Φ.comp (uniformAttach n)
  prepAvail_uniform := fun n =>
    ⟨n.succ_pos, LinearMap.id,
      ⟨fun _ => by rw [← conjChannel_one]; exact conjChannel_twoPositive _, fun X => by
        rw [Fintype.sum_unique, LinearMap.id_apply]⟩, by rw [LinearMap.id_comp]⟩
  prepAvail_post := by
    rintro n P Φ ⟨hn, Ψ, ⟨hΨ2, hΨtr⟩, rfl⟩ ⟨hΦ2, hΦtr⟩
    refine ⟨hn, Φ.comp Ψ, ⟨fun _ => isTwoPositive_comp (hΦ2 ()) (hΨ2 ()), fun X => ?_⟩,
      by rw [LinearMap.comp_assoc]⟩
    rw [Fintype.sum_unique]
    have h1 := hΦtr (Ψ X)
    rw [Fintype.sum_unique] at h1
    have h2 := hΨtr X
    rw [Fintype.sum_unique] at h2
    exact h1.trans h2
  readout := fun _ k => localLuders k
  readout_avail := fun _ => ⟨fun k => localLuders_twoPositive k, localLuders_trace_sum⟩
  readout_local := fun _ k => localLuders_mapSpectatorIndependent k
  prepAvail_discard := by
    rintro n P O _ _ F ⟨hn, Φ, ⟨hΦ2, hΦtr⟩, rfl⟩ ⟨hF2, hFtr⟩
    refine ⟨fun a => ?_, fun X => ?_⟩
    · show IsTwoPositive (discardWith n (Φ.comp (uniformAttach n)) (F a))
      have h : discardWith n (Φ.comp (uniformAttach n)) (F a)
          = discardWith n (uniformAttach n) ((F a).comp Φ) := by
        simp only [discardWith, LinearMap.comp_assoc]
      rw [h]
      exact discardWith_uniform_twoPositive (isTwoPositive_comp (hF2 a) (hΦ2 ()))
    · show ∑ a, ((discardWith n (Φ.comp (uniformAttach n)) (F a)) X).trace = X.trace
      rw [Finset.sum_congr rfl fun a _ => discardWith_trace n _ (F a) X, hFtr]
      have h := hΦtr (uniformAttach n X)
      rw [Fintype.sum_unique] at h
      exact h.trans (uniformAttach_trace n hn.ne' X)

/-- The 2-positive family. -/
noncomputable def twoPosFamily : TheoryFamily := fun S _ _ => twoPosTheory S

theorem twoPosFamily_regrouping : RegroupingInvariant twoPosFamily := by
  intro S _ _ m _ O _ _ F
  exact Iff.rfl

theorem twoPosFamily_relabelling : RelabellingInvariant twoPosFamily := by
  intro S S' _ _ _ _ e O _ _ F ⟨h2, htr⟩
  refine ⟨fun a => twoPositive_transport e (h2 a), fun X => ?_⟩
  simp only [trace_transport]
  rw [htr, trace_reindex]

/-- The round-34 countermodel is the qubit member of the 2-positive family: definitionally
on every composite, and on the system because a 2-positive map of a qubit is completely
positive (`twoPositive_qubit_cp`). -/
theorem countermodel_ambient : IsAmbientMember countermodel twoPosFamily := by
  refine ⟨fun O _ _ F => ⟨fun hF => ?_, fun hF => ?_⟩, fun N _ O _ _ F => Iff.rfl⟩
  · obtain ⟨hcp, htr⟩ := krausFamily_cp_tr hF
    exact ⟨fun a => cp_referencePositive (Fin 2) _ (hcp a), htr⟩
  · obtain ⟨h2, htr⟩ := hF
    exact isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
      (fun a => twoPositive_qubit_cp _ (h2 a)) htr

theorem countermodel_embeddedObservation : EmbeddedObservation countermodel :=
  ⟨twoPosFamily, twoPosFamily_regrouping, twoPosFamily_relabelling, countermodel_ambient⟩

theorem countermodel_reversibleRichness : ReversibleRichness countermodel :=
  reversibleRichness_of_control _ ⟨countermodel_validity, countermodel_systemToLevelOne⟩
    countermodel_control

/-- **THE REDUNDANCY TEST FAILS**: validity, reversible richness and embedded observation
(with the OI core) do not imply observational independence. -/
theorem redundancy_fails :
    ∃ T : FiniteOperationalTheory (Fin 2), OICore T ∧ CompositeOperationalValidity T
      ∧ ReversibleRichness T ∧ EmbeddedObservation T ∧ ¬ ObservationalIndependence T :=
  ⟨countermodel, countermodel_realizesSealedOICore, countermodel_validity,
    countermodel_reversibleRichness, countermodel_embeddedObservation,
    fun h => countermodel_not_inert ((observationalIndependence_iff_inert _).mp h)⟩

end TwoPos

/-! ### Section B — form without existence -/

section Form

/-- **THE FORM IS FIXED AND THE EXTENSION IS NOT AVAILABLE**: the two-qubit reduction map is
available in the countermodel, every spectator extension of it along the qutrit index is
`withSpectator`, and that extension is not available. -/
theorem form_fixed_existence_fails :
    countermodel.availExt 2 Unit (fun _ => reduction2 (Fin 2 × Fin 2))
    ∧ (∀ G, IsSpectatorExtension qutritIdx (reduction2 (Fin 2 × Fin 2)) G
        ↔ G = withSpectator (Fin 3) qutritIdx (reduction2 (Fin 2 × Fin 2)))
    ∧ ¬ countermodel.availExt 6 Unit
        (fun _ => withSpectator (Fin 3) qutritIdx (reduction2 (Fin 2 × Fin 2))) := by
  refine ⟨countermodel_reduction2_available, fun G => isSpectatorExtension_iff _ _ _, ?_⟩
  rintro ⟨h2, -⟩
  have hpos := positive_of_twoPositive (h2 ())
    (posSemidef_reindex qutritIdx (Matrix.posSemidef_vecMulVec_self_star maxEnt3))
  rw [withSpectator_reindex] at hpos
  exact amplRef_reduction2_maxEnt3_not_posSemidef (posSemidef_of_reindex qutritIdx hpos)

end Form

/-! ### Section C — the primitive: implementation classes and instrument realization -/

section Primitive

/-- An implementation class: at every finite carrier, which single operators are admissible
physical implementations. -/
abbrev ImplementationClass :=
  ∀ (S : Type) [Fintype S] [DecidableEq S], Matrix S S ℂ → Prop

/-- An operation is BRANCH-REALIZED by a class when it is a finite sum of conjugations by
admissible operators. This is the comparison notion; the availability of a theory is generated
by `InstAvail` below. -/
def Realized (𝓘 : ImplementationClass) (S : Type) [Fintype S] [DecidableEq S]
    (Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) : Prop :=
  ∃ (ι : Type) (_ : Fintype ι) (K : ι → Matrix S S ℂ),
    Φ = ∑ i, conjChannel (K i) ∧ ∀ i, 𝓘 S (K i)

/-- The readout projector onto the register value `k` of the carrier `T × Fin m`. -/
def readProj (T : Type) [DecidableEq T] (m : ℕ) (k : Fin m) :
    Matrix (T × Fin m) (T × Fin m) ℂ :=
  Matrix.diagonal fun r => if r.2 = k then 1 else 0

/-- **INSTRUMENT REALIZATION.** A family of operations on the carrier `T` with outcomes `O` is
instrument-realized by the class `𝓘` when it is built from: one admissible isometric step;
the native Lüders readout of a register `T' × Fin m ≃ T` of the carrier, its projectors
admissible; classical coarse-graining of the outcome; sequential composition with
outcome-dependent continuation; and the discard of a uniformly attached ancilla of positive
size. There is no constructor taking a sum of admissible operators: the branches of a realized
family arise together as the outcomes of one protocol, and the uniformly weighted preparation
label is summed inside the discard and is never an outcome. -/
inductive InstAvail (𝓘 : ImplementationClass) :
    ∀ (T : Type) [Fintype T] [DecidableEq T] (O : Type) [Fintype O] [DecidableEq O],
      (O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ) → Prop
  | op {T : Type} [Fintype T] [DecidableEq T] (K : Matrix T T ℂ) (hK : 𝓘 T K)
      (hiso : Kᴴ * K = 1) : InstAvail 𝓘 T Unit (fun _ => conjChannel K)
  | readout {T T' : Type} [Fintype T] [DecidableEq T] [Fintype T'] [DecidableEq T'] {m : ℕ}
      (e : T' × Fin m ≃ T) (hP : ∀ k, 𝓘 T (Matrix.reindex e e (readProj T' m k))) :
      InstAvail 𝓘 T (Fin m) (fun k => conjChannel (Matrix.reindex e e (readProj T' m k)))
  | coarse {T : Type} [Fintype T] [DecidableEq T] {O O' : Type} [Fintype O] [DecidableEq O]
      [Fintype O'] [DecidableEq O'] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (f : O → O')
      (h : InstAvail 𝓘 T O F) :
      InstAvail 𝓘 T O' (fun a => ∑ j ∈ Finset.univ.filter (fun j => f j = a), F j)
  | bind {T : Type} [Fintype T] [DecidableEq T] {O O' : Type} [Fintype O] [DecidableEq O]
      [Fintype O'] [DecidableEq O'] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ}
      {G : O → O' → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (hF : InstAvail 𝓘 T O F)
      (hG : ∀ a, InstAvail 𝓘 T O' (G a)) :
      InstAvail 𝓘 T (O × O') (fun c => (G c.1 c.2).comp (F c.1))
  | discard {T : Type} [Fintype T] [DecidableEq T] {m : ℕ} (hm : 0 < m) {O : Type} [Fintype O]
      [DecidableEq O]
      {F : O → Matrix (T × Fin m) (T × Fin m) ℂ →ₗ[ℂ] Matrix (T × Fin m) (T × Fin m) ℂ}
      (h : InstAvail 𝓘 (T × Fin m) O F) :
      InstAvail 𝓘 T O (fun a => discardWith (A := T) m (uniformAttach m) (F a))

variable {𝓘 : ImplementationClass}

/-- A one-outcome conjugation preserves the trace exactly when its operator is an isometry: the
contractive-plus-normalized reading of a step is the isometric one. -/
theorem conjChannel_trace_iff {T : Type} [Fintype T] [DecidableEq T] (K : Matrix T T ℂ) :
    (∀ X : Matrix T T ℂ, (conjChannel K X).trace = X.trace) ↔ Kᴴ * K = 1 := by
  constructor
  · intro h
    have := sum_conjTranspose_mul_eq_one_of_trace (fun _ : Unit => K) fun X => by
      rw [Fintype.sum_unique]; exact h X
    rwa [Fintype.sum_unique] at this
  · intro h X
    exact conjChannel_trace K h X

theorem instAvail_mono {𝓙 : ImplementationClass}
    (hle : ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → 𝓙 S K)
    {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O] [DecidableEq O]
    {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (h : InstAvail 𝓘 T O F) : InstAvail 𝓙 T O F := by
  induction h with
  | op K hK hiso => exact InstAvail.op K (hle _ _ hK) hiso
  | readout e hP => exact InstAvail.readout e fun k => hle _ _ (hP k)
  | coarse f _ ih => exact InstAvail.coarse f ih
  | bind _ _ ihF ihG => exact InstAvail.bind ihF ihG
  | discard hm _ ih => exact InstAvail.discard hm ih

/-- **T1, THE TRACE**: an instrument-realized family preserves the trace in aggregate. -/
theorem instAvail_trace {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O]
    [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (h : InstAvail 𝓘 T O F) :
    ∀ X, ∑ a, ((F a) X).trace = X.trace := by
  induction h with
  | op K hK hiso =>
    intro X
    rw [Fintype.sum_unique]
    exact conjChannel_trace K hiso X
  | readout e hP =>
    intro X
    have h1 : ∀ k, conjChannel (Matrix.reindex e e (readProj _ _ k)) = transport e (localLuders k) :=
      fun k => by rw [localLuders_eq_conjChannel, transport_conjChannel]; rfl
    simp only [h1, trace_transport]
    rw [localLuders_trace_sum, trace_reindex]
  | coarse f _ ih =>
    intro X
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))]
    exact ih X
  | bind _ hG ihF ihG =>
    intro X
    rw [Fintype.sum_prod_type]
    simp only [LinearMap.comp_apply]
    rw [Finset.sum_congr rfl fun a _ => ihG a _]
    exact ihF X
  | discard hm _ ih =>
    intro X
    simp only [discardWith_trace]
    rw [ih, uniformAttach_trace _ hm.ne']

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **(G) IMPLEMENTATION GENERATION**: at every positive level, availability is instrument
realization by the class. The normalization half of validity is a theorem of the predicate
(`instAvail_trace`), not a clause. -/
def ImplementationGenerated (T : FiniteOperationalTheory A) (𝓘 : ImplementationClass) : Prop :=
  ∀ (N : ℕ), 0 < N → ∀ (O : Type) [Fintype O] [DecidableEq O]
    (F : O → Matrix (A × Fin N) (A × Fin N) ℂ →ₗ[ℂ] Matrix (A × Fin N) (A × Fin N) ℂ),
    T.availExt N O F ↔ InstAvail 𝓘 (A × Fin N) O F

/-- **(C) CONTEXT STABILITY**: adjoining uncoupled degrees of freedom leaves an admissible
implementation admissible, unchanged on its original support. -/
def ContextStable (𝓘 : ImplementationClass) : Prop :=
  ∀ (R S : Type) [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S] (K : Matrix S S ℂ),
    𝓘 S K → 𝓘 (R × S) (tensorOf (1 : Matrix R R ℂ) K)

/-- **(L) LABEL INVARIANCE**: admissibility is transported along carrier bijections. -/
def LabelInvariant (𝓘 : ImplementationClass) : Prop :=
  ∀ (S S' : Type) [Fintype S] [DecidableEq S] [Fintype S'] [DecidableEq S'] (e : S ≃ S')
    (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S' (Matrix.reindex e e K)

/-- **IMPLEMENTATION LOCALITY**: availability is generated by a context-stable,
label-invariant implementation class. -/
def ImplementationLocality (T : FiniteOperationalTheory A) : Prop :=
  ∃ 𝓘 : ImplementationClass, ImplementationGenerated T 𝓘 ∧ ContextStable 𝓘 ∧ LabelInvariant 𝓘

/-- The full class: every operator admissible at every carrier. -/
def fullClass : ImplementationClass := fun _ _ _ _ => True

theorem fullClass_contextStable : ContextStable fullClass := fun _ _ _ _ _ _ _ _ => trivial

theorem fullClass_labelInvariant : LabelInvariant fullClass := fun _ _ _ _ _ _ _ _ _ => trivial

end Primitive

/-! ### Section D — branch realization is closed under the operations a theory performs -/

section Closure

variable {𝓘 : ImplementationClass} {S : Type} [Fintype S] [DecidableEq S]

/-- A branch-realized operation is completely positive. -/
theorem cp_of_realized {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (h : Realized 𝓘 S Φ) :
    IsCompletelyPositive Φ := by
  obtain ⟨ι, _, K, rfl, -⟩ := h
  exact cp_sum _ _ fun i _ => conjChannel_cp _

omit [DecidableEq S] in
theorem conjChannel_smul (a : ℂ) (V : Matrix S S ℂ) :
    conjChannel (a • V) = (a * star a) • conjChannel V := by
  refine LinearMap.ext fun X => ?_
  show a • V * X * (a • V)ᴴ = (a * star a) • (V * X * Vᴴ)
  rw [Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.mul_smul, Matrix.smul_mul, smul_smul,
    mul_comm (star a) a]

theorem realized_conj {K : Matrix S S ℂ} (h : 𝓘 S K) : Realized 𝓘 S (conjChannel K) :=
  ⟨Unit, inferInstance, fun _ => K, by rw [Fintype.sum_unique], fun _ => h⟩

theorem realized_zero : Realized 𝓘 S 0 :=
  ⟨Empty, inferInstance, fun x => x.elim, by simp, fun x => x.elim⟩

theorem realized_add {Φ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (hΦ : Realized 𝓘 S Φ)
    (hΨ : Realized 𝓘 S Ψ) : Realized 𝓘 S (Φ + Ψ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := hΦ
  obtain ⟨κ, _, L, rfl, hL⟩ := hΨ
  refine ⟨ι ⊕ κ, inferInstance, Sum.elim K L, ?_, ?_⟩
  · simp [Fintype.sum_sum_type]
  · rintro (i | j)
    · exact hK i
    · exact hL j

theorem realized_sum {ι' : Type*} (s : Finset ι') (Φ : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (h : ∀ i ∈ s, Realized 𝓘 S (Φ i)) : Realized 𝓘 S (∑ i ∈ s, Φ i) :=
  Finset.sum_induction _ (Realized 𝓘 S) (fun _ _ => realized_add) realized_zero h

omit [Fintype S] [DecidableEq S] in
theorem sum_comp' {ι' : Type*} (s : Finset ι') (f : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (g : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    (∑ i ∈ s, f i).comp g = ∑ i ∈ s, (f i).comp g := by
  refine LinearMap.ext fun X => ?_
  simp only [LinearMap.comp_apply, LinearMap.sum_apply]

omit [Fintype S] [DecidableEq S] in
theorem comp_sum' {ι' : Type*} (s : Finset ι') (f : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (g : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    f.comp (∑ i ∈ s, g i) = ∑ i ∈ s, f.comp (g i) := by
  refine LinearMap.ext fun X => ?_
  simp only [LinearMap.comp_apply, LinearMap.sum_apply, map_sum]

theorem realized_comp (hmul : ∀ K L : Matrix S S ℂ, 𝓘 S K → 𝓘 S L → 𝓘 S (K * L))
    {Φ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (hΦ : Realized 𝓘 S Φ) (hΨ : Realized 𝓘 S Ψ) :
    Realized 𝓘 S (Φ.comp Ψ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := hΦ
  obtain ⟨κ, _, L, rfl, hL⟩ := hΨ
  refine ⟨ι × κ, inferInstance, fun p => K p.1 * L p.2, ?_,
    fun p => hmul _ _ (hK p.1) (hL p.2)⟩
  rw [sum_comp', Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [comp_sum']
  exact Finset.sum_congr rfl fun j _ => OIHierarchyGeneral.conjChannel_mul_general (K i) (L j)

theorem realized_smul_nonneg
    (hsmul : ∀ (a : ℂ) (K : Matrix S S ℂ), ‖a‖ ≤ 1 → 𝓘 S K → 𝓘 S (a • K))
    {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (c : ℝ) (hc : 0 ≤ c) (hc1 : c ≤ 1)
    (h : Realized 𝓘 S Φ) : Realized 𝓘 S ((c : ℂ) • Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  have hs : ‖((Real.sqrt c : ℝ) : ℂ)‖ ≤ 1 := by
    rw [Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (Real.sqrt_nonneg c)]
    exact (Real.sqrt_le_sqrt hc1).trans_eq Real.sqrt_one
  refine ⟨ι, inferInstance, fun i => ((Real.sqrt c : ℝ) : ℂ) • K i, ?_,
    fun i => hsmul _ _ hs (hK i)⟩
  rw [Finset.smul_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  show (c : ℂ) • conjChannel (K i) = conjChannel (((Real.sqrt c : ℝ) : ℂ) • K i)
  rw [conjChannel_smul, Complex.star_def, Complex.conj_ofReal,
    ← Complex.ofReal_mul, Real.mul_self_sqrt hc]

theorem realized_transport (hl : LabelInvariant 𝓘) {S' : Type} [Fintype S'] [DecidableEq S']
    (e : S ≃ S') {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (h : Realized 𝓘 S Φ) :
    Realized 𝓘 S' (transport e Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  refine ⟨ι, inferInstance, fun i => Matrix.reindex e e (K i), ?_, fun i => hl _ _ e _ (hK i)⟩
  rw [transport_sum]
  exact Finset.sum_congr rfl fun i _ => transport_conjChannel e (K i)

theorem realized_id (hone : 𝓘 S 1) : Realized 𝓘 S LinearMap.id := by
  rw [← conjChannel_one]
  exact realized_conj hone

theorem realized_localLuders {m : ℕ}
    (hproj : ∀ k : Fin m, 𝓘 (S × Fin m) (Matrix.diagonal fun r => if r.2 = k then 1 else 0))
    (k : Fin m) : Realized 𝓘 (S × Fin m) (localLuders (A := S) k) := by
  rw [localLuders_eq_conjChannel]
  exact realized_conj (hproj k)

theorem realized_discard {m : ℕ}
    (hblock : ∀ (K : Matrix (S × Fin m) (S × Fin m) ℂ) (f e : Fin m),
      𝓘 (S × Fin m) K → 𝓘 S (ancBlock K f e))
    (hsmul : ∀ (a : ℂ) (K : Matrix S S ℂ), ‖a‖ ≤ 1 → 𝓘 S K → 𝓘 S (a • K))
    {Φ : Matrix (S × Fin m) (S × Fin m) ℂ →ₗ[ℂ] Matrix (S × Fin m) (S × Fin m) ℂ}
    (h : Realized 𝓘 (S × Fin m) Φ) :
    Realized 𝓘 S (discardWith (A := S) m (uniformAttach m) Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  rw [discardWith_sum]
  refine realized_sum _ _ fun i _ => ?_
  rw [discardWith_uniform_conjChannel]
  have hcast : ((m : ℂ))⁻¹ = (((m : ℝ)⁻¹ : ℝ) : ℂ) := by push_cast; rfl
  rw [hcast]
  refine realized_smul_nonneg hsmul _ (inv_nonneg.mpr (Nat.cast_nonneg m)) (Nat.cast_inv_le_one m) ?_
  exact realized_sum _ _ fun c _ => realized_conj (hblock _ _ _ (hK i))

end Closure

/-! ### Section E — architectures: soundness, relabelling and spectators -/

section Architecture

/-- **AN ARCHITECTURE**: an implementation class closed under the operations every finite
operational theory performs on implementations. -/
structure Architecture (𝓘 : ImplementationClass) : Prop where
  one : ∀ (S : Type) [Fintype S] [DecidableEq S], 𝓘 S 1
  mul : ∀ (S : Type) [Fintype S] [DecidableEq S] (K L : Matrix S S ℂ),
    𝓘 S K → 𝓘 S L → 𝓘 S (K * L)
  smul : ∀ (S : Type) [Fintype S] [DecidableEq S] (a : ℂ) (K : Matrix S S ℂ),
    ‖a‖ ≤ 1 → 𝓘 S K → 𝓘 S (a • K)
  proj : ∀ (S : Type) [Fintype S] [DecidableEq S] (m : ℕ) (k : Fin m),
    𝓘 (S × Fin m) (Matrix.diagonal fun r => if r.2 = k then 1 else 0)
  block : ∀ (S : Type) [Fintype S] [DecidableEq S] (m : ℕ)
    (K : Matrix (S × Fin m) (S × Fin m) ℂ) (f e : Fin m),
    𝓘 (S × Fin m) K → 𝓘 S (ancBlock K f e)

theorem fullClass_arch : Architecture fullClass where
  one := fun _ _ _ => trivial
  mul := fun _ _ _ _ _ _ _ => trivial
  smul := fun _ _ _ _ _ _ _ => trivial
  proj := fun _ _ _ _ _ => trivial
  block := fun _ _ _ _ _ _ _ _ => trivial

variable {𝓘 : ImplementationClass}

/-- **T1, SOUNDNESS**: for an architecture, every branch of an instrument-realized family is
branch-realized: the step and the readout are conjugations by admissible operators, the
continuation multiplies admissible operators, and the discard takes contractive blocks. -/
theorem realized_of_instAvail (arch : Architecture 𝓘) {T : Type} [Fintype T] [DecidableEq T]
    {O : Type} [Fintype O] [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ}
    (h : InstAvail 𝓘 T O F) : ∀ a, Realized 𝓘 T (F a) := by
  induction h with
  | op K hK hiso => exact fun _ => realized_conj hK
  | readout e hP => exact fun k => realized_conj (hP k)
  | coarse f _ ih => exact fun a => realized_sum _ _ fun j _ => ih j
  | bind _ _ ihF ihG => exact fun c => realized_comp (arch.mul _) (ihG c.1 c.2) (ihF c.1)
  | discard hm _ ih => exact fun a => realized_discard (arch.block _ _) (arch.smul _) (ih a)

/-- Every branch of an instrument-realized family is completely positive, for every class. -/
theorem cp_of_instAvail {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O]
    [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (h : InstAvail 𝓘 T O F) (a : O) :
    IsCompletelyPositive (F a) :=
  cp_of_realized (realized_of_instAvail fullClass_arch
    (instAvail_mono (fun _ _ _ _ _ => trivial) h) a)

/-- Post-composition of every branch by an available one-outcome operation: the continuation
with a constant choice, coarse-grained along the outcome. -/
theorem instAvail_comp_one {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O]
    [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ}
    {Φ : Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (hF : InstAvail 𝓘 T O F)
    (hΦ : InstAvail 𝓘 T Unit (fun _ => Φ)) : InstAvail 𝓘 T O (fun a => (F a).comp Φ) := by
  have h := InstAvail.coarse (fun c : Unit × O => c.2) (InstAvail.bind hΦ (fun _ => hF))
  have e : (fun a => (F a).comp Φ)
      = fun a => ∑ j ∈ Finset.univ.filter (fun j : Unit × O => j.2 = a), (F j.2).comp Φ := by
    funext a
    rw [Finset.sum_filter, Fintype.sum_prod_type, Fintype.sum_unique]
    simp
  rw [e]
  exact h

theorem instAvail_one_comp {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O]
    [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ}
    {Φ : Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (hΦ : InstAvail 𝓘 T Unit (fun _ => Φ))
    (hF : InstAvail 𝓘 T O F) : InstAvail 𝓘 T O (fun a => Φ.comp (F a)) := by
  have h := InstAvail.coarse (fun c : O × Unit => c.1) (InstAvail.bind hF (fun _ => hΦ))
  have e : (fun a => Φ.comp (F a))
      = fun a => ∑ j ∈ Finset.univ.filter (fun j : O × Unit => j.1 = a), Φ.comp (F j.1) := by
    funext a
    rw [Finset.sum_filter, Fintype.sum_prod_type]
    simp
  rw [e]
  exact h

/-- The identity is instrument-realized in every class containing the identity operator. -/
theorem instAvail_id {T : Type} [Fintype T] [DecidableEq T] (hone : 𝓘 T 1) :
    InstAvail 𝓘 T Unit (fun _ => LinearMap.id) := by
  have h := InstAvail.op (𝓘 := 𝓘) (1 : Matrix T T ℂ) hone (by simp)
  rwa [conjChannel_one] at h

end Architecture

section Transport

variable {𝓘 : ImplementationClass}

theorem transport_refl {T : Type} [Fintype T] [DecidableEq T]
    (Φ : Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ) : transport (Equiv.refl T) Φ = Φ := by
  refine LinearMap.ext fun X => ?_
  simp [transport_apply]

theorem transport_trans {T T' T'' : Type} [Fintype T] [DecidableEq T] [Fintype T'] [DecidableEq T']
    [Fintype T''] [DecidableEq T''] (e : T ≃ T') (e' : T' ≃ T'')
    (Φ : Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ) :
    transport e' (transport e Φ) = transport (e.trans e') Φ := by
  refine LinearMap.ext fun X => ?_
  simp only [transport_apply, Matrix.reindex_apply, Matrix.submatrix_submatrix]
  rfl

theorem transport_comp {T T' : Type} [Fintype T] [DecidableEq T] [Fintype T'] [DecidableEq T']
    (e : T ≃ T') (Φ Ψ : Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ) :
    transport e (Φ.comp Ψ) = (transport e Φ).comp (transport e Ψ) := by
  refine LinearMap.ext fun X => ?_
  simp only [transport_apply, LinearMap.comp_apply]
  rw [← Matrix.reindex_symm, Equiv.symm_apply_apply]

theorem reindex_reindex {l m n : Type} (e₀ : l ≃ m) (e : m ≃ n) (M : Matrix l l ℂ) :
    Matrix.reindex e e (Matrix.reindex e₀ e₀ M) = Matrix.reindex (e₀.trans e) (e₀.trans e) M := by
  rw [← Matrix.reindex_trans]
  rfl

theorem reindex_isometry' {T T' : Type} [Fintype T] [DecidableEq T] [Fintype T'] [DecidableEq T']
    (e : T ≃ T') {K : Matrix T T ℂ} (hK : Kᴴ * K = 1) :
    (Matrix.reindex e e K)ᴴ * Matrix.reindex e e K = 1 := by
  rw [Matrix.reindex_apply, Matrix.conjTranspose_submatrix, Matrix.submatrix_mul_equiv, hK,
    Matrix.submatrix_one_equiv]

theorem uniformAttach_reindex {T T' : Type} [Fintype T] [DecidableEq T] [Fintype T']
    [DecidableEq T'] (e : T ≃ T') (m : ℕ) (X : Matrix T' T' ℂ) :
    uniformAttach m (Matrix.reindex e.symm e.symm X)
      = Matrix.reindex (e.prodCongr (Equiv.refl (Fin m))).symm
          (e.prodCongr (Equiv.refl (Fin m))).symm (uniformAttach m X) := by
  ext ⟨s, f⟩ ⟨t, f'⟩
  simp [Matrix.reindex_apply, Matrix.submatrix_apply]

/-- Relabelling the carrier commutes with the discard of a fresh ancilla. -/
theorem transport_discard {T T' : Type} [Fintype T] [DecidableEq T] [Fintype T'] [DecidableEq T']
    (e : T ≃ T') {m : ℕ}
    (Φ : Matrix (T × Fin m) (T × Fin m) ℂ →ₗ[ℂ] Matrix (T × Fin m) (T × Fin m) ℂ) :
    transport e (discardWith (A := T) m (uniformAttach m) Φ)
      = discardWith (A := T') m (uniformAttach m)
          (transport (e.prodCongr (Equiv.refl (Fin m))) Φ) := by
  refine LinearMap.ext fun X => ?_
  ext s t
  simp only [transport_apply, discardWith, LinearMap.comp_apply, Matrix.reindex_apply,
    Matrix.submatrix_apply]
  show ptraceAnc m (Φ (uniformAttach m (Matrix.reindex e.symm e.symm X))) (e.symm s) (e.symm t)
    = ptraceAnc m (Matrix.reindex _ _ (Φ (Matrix.reindex _ _ (uniformAttach m X)))) s t
  rw [uniformAttach_reindex]
  simp [Matrix.reindex_apply, Matrix.submatrix_apply]

/-- **RELABELLING**: for a label-invariant class the predicate is transported along every
carrier bijection. -/
theorem instAvail_transport (hl : LabelInvariant 𝓘) {T : Type} [Fintype T] [DecidableEq T]
    {O : Type} [Fintype O] [DecidableEq O] {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ}
    (h : InstAvail 𝓘 T O F) :
    ∀ (T' : Type) [Fintype T'] [DecidableEq T'] (e : T ≃ T'),
      InstAvail 𝓘 T' O (fun a => transport e (F a)) := by
  induction h with
  | op K hK hiso =>
    intro T' _ _ e
    have := InstAvail.op (𝓘 := 𝓘) (Matrix.reindex e e K) (hl _ _ e _ hK) (reindex_isometry' e hiso)
    simpa only [transport_conjChannel] using this
  | readout e₀ hP =>
    intro T' _ _ e
    have := InstAvail.readout (𝓘 := 𝓘) (e₀.trans e) fun k => by
      rw [← reindex_reindex]; exact hl _ _ e _ (hP k)
    simpa only [transport_conjChannel, reindex_reindex] using this
  | coarse f _ ih =>
    intro T' _ _ e
    have := InstAvail.coarse f (ih T' e)
    simpa only [transport_sum] using this
  | bind _ _ ihF ihG =>
    intro T' _ _ e
    have := InstAvail.bind (ihF T' e) (fun a => ihG a T' e)
    simpa only [transport_comp] using this
  | discard hm _ ih =>
    intro T' _ _ e
    have := InstAvail.discard (𝓘 := 𝓘) hm (ih _ (e.prodCongr (Equiv.refl _)))
    simpa only [transport_discard] using this

end Transport

section Spectator

variable {𝓘 : ImplementationClass}

theorem tensorOf_conjTranspose {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    (A : Matrix R R ℂ) (B : Matrix S S ℂ) : (tensorOf A B)ᴴ = tensorOf Aᴴ Bᴴ := by
  ext p q
  simp [Matrix.conjTranspose_apply, tensorOf_apply]

theorem tensorOf_mul' {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    (A C : Matrix R R ℂ) (B D : Matrix S S ℂ) :
    tensorOf A B * tensorOf C D = tensorOf (A * C) (B * D) := by
  ext p q
  simp only [Matrix.mul_apply, tensorOf_apply, Fintype.sum_prod_type, Finset.sum_mul_sum]
  refine Finset.sum_congr rfl fun u _ => Finset.sum_congr rfl fun v _ => ?_
  ring

theorem tensorOf_one_isometry' {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    {K : Matrix S S ℂ} (hK : Kᴴ * K = 1) :
    (tensorOf (1 : Matrix R R ℂ) K)ᴴ * tensorOf (1 : Matrix R R ℂ) K = 1 := by
  rw [tensorOf_conjTranspose, tensorOf_mul', Matrix.conjTranspose_one, Matrix.one_mul, hK,
    tensorOf_one_one]

theorem amplRefL_conjChannel (R : Type) [Fintype R] [DecidableEq R] {S : Type} [Fintype S]
    [DecidableEq S] (K : Matrix S S ℂ) :
    amplRefL R (conjChannel K) = conjChannel (tensorOf (1 : Matrix R R ℂ) K) :=
  LinearMap.ext fun M => amplRef_conjChannel K M

theorem amplRefL_sum (R : Type) [Fintype R] [DecidableEq R] {S : Type} [Fintype S] [DecidableEq S]
    {ι : Type*} (s : Finset ι) (Φ : ι → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    amplRefL R (∑ i ∈ s, Φ i) = ∑ i ∈ s, amplRefL R (Φ i) := by
  refine LinearMap.ext fun M => ?_
  rw [LinearMap.sum_apply]
  exact amplRef_sum_map s Φ M

theorem amplRef_apply' {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    (Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) (M : Matrix (R × S) (R × S) ℂ) (p q : R × S) :
    amplRef R Φ M p q = Φ (refBlockR M p.1 q.1) p.2 q.2 := rfl

theorem refBlockR_amplRef {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    (Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) (M : Matrix (R × S) (R × S) ℂ) (r r' : R) :
    refBlockR (amplRef R Ψ M) r r' = Ψ (refBlockR M r r') := by
  ext k l
  rfl

theorem amplRefL_comp (R : Type) [Fintype R] [DecidableEq R] {S : Type} [Fintype S] [DecidableEq S]
    (Φ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    amplRefL R (Φ.comp Ψ) = (amplRefL R Φ).comp (amplRefL R Ψ) := by
  refine LinearMap.ext fun M => ?_
  ext ⟨r, k⟩ ⟨r', l⟩
  show amplRef R (Φ.comp Ψ) M (r, k) (r', l) = amplRef R Φ (amplRef R Ψ M) (r, k) (r', l)
  rw [amplRef_apply', amplRef_apply', refBlockR_amplRef]
  rfl

theorem tensorOf_one_reindex {R S S' : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    [Fintype S'] [DecidableEq S'] (e : S ≃ S') (K : Matrix S S ℂ) :
    tensorOf (1 : Matrix R R ℂ) (Matrix.reindex e e K)
      = Matrix.reindex ((Equiv.refl R).prodCongr e) ((Equiv.refl R).prodCongr e)
          (tensorOf (1 : Matrix R R ℂ) K) := by
  ext ⟨r, x⟩ ⟨r', y⟩
  simp [Matrix.reindex_apply, Matrix.submatrix_apply]

theorem tensorOf_one_readProj {R S : Type} [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S]
    (m : ℕ) (k : Fin m) :
    tensorOf (1 : Matrix R R ℂ) (readProj S m k)
      = Matrix.reindex (Equiv.prodAssoc R S (Fin m)) (Equiv.prodAssoc R S (Fin m))
          (readProj (R × S) m k) := by
  ext ⟨r, x, f⟩ ⟨r', y, f'⟩
  simp only [tensorOf_apply, readProj, Matrix.diagonal_apply, Matrix.one_apply, Matrix.reindex_apply,
    Matrix.submatrix_apply, Equiv.prodAssoc_symm_apply, Prod.mk.injEq]
  by_cases hr : r = r' <;> by_cases hx : x = y <;> by_cases hf : f = f' <;> simp [hr, hx, hf]

/-- Amplification by a spectator commutes with relabelling of the carrier. -/
theorem amplRefL_transport (R : Type) [Fintype R] [DecidableEq R] {S S' : Type} [Fintype S]
    [DecidableEq S] [Fintype S'] [DecidableEq S'] (e : S ≃ S')
    (Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    amplRefL R (transport e Φ)
      = transport ((Equiv.refl R).prodCongr e) (amplRefL R Φ) := by
  refine LinearMap.ext fun M => ?_
  ext ⟨r, x⟩ ⟨r', y⟩
  simp only [amplRefL_apply, amplRef, Matrix.of_apply, transport_apply, Matrix.reindex_apply,
    Matrix.submatrix_apply, Equiv.prodCongr_symm, Equiv.prodCongr_apply, Equiv.refl_symm,
    Equiv.coe_refl, Prod.map_apply, id_eq]
  congr 2

theorem refBlockR_reindex_uniformAttach {R S : Type} [Fintype R] [DecidableEq R] [Fintype S]
    [DecidableEq S] (m : ℕ) (M : Matrix (R × S) (R × S) ℂ) (r r' : R) :
    refBlockR (Matrix.reindex (Equiv.prodAssoc R S (Fin m)) (Equiv.prodAssoc R S (Fin m))
        (uniformAttach m M)) r r'
      = uniformAttach m (refBlockR M r r') := by
  ext ⟨x, f⟩ ⟨y, f'⟩
  simp [refBlockR, Matrix.reindex_apply, Matrix.submatrix_apply]

/-- Amplification by a spectator commutes with the discard of a fresh ancilla, the ancilla
being regrouped past the spectator. -/
theorem amplRefL_discard (R : Type) [Fintype R] [DecidableEq R] {S : Type} [Fintype S]
    [DecidableEq S] {m : ℕ}
    (Φ : Matrix (S × Fin m) (S × Fin m) ℂ →ₗ[ℂ] Matrix (S × Fin m) (S × Fin m) ℂ) :
    amplRefL R (discardWith (A := S) m (uniformAttach m) Φ)
      = discardWith (A := R × S) m (uniformAttach m)
          (transport (Equiv.prodAssoc R S (Fin m)).symm (amplRefL R Φ)) := by
  refine LinearMap.ext fun M => ?_
  ext ⟨r, x⟩ ⟨r', y⟩
  simp only [amplRefL_apply, amplRef, Matrix.of_apply, discardWith, LinearMap.comp_apply,
    transport_apply, Equiv.symm_symm]
  show ∑ f, (Φ (uniformAttach m (refBlockR M r r'))) (x, f) (y, f)
    = ∑ f, (Matrix.reindex (Equiv.prodAssoc R S (Fin m)).symm (Equiv.prodAssoc R S (Fin m)).symm
        (amplRef R Φ (Matrix.reindex (Equiv.prodAssoc R S (Fin m)) (Equiv.prodAssoc R S (Fin m))
          (uniformAttach m M)))) ((r, x), f) ((r', y), f)
  refine Finset.sum_congr rfl fun f _ => ?_
  rw [Matrix.reindex_apply, Matrix.submatrix_apply, Equiv.symm_symm, Equiv.prodAssoc_apply,
    Equiv.prodAssoc_apply, amplRef_apply', refBlockR_reindex_uniformAttach]

/-- **SPECTATORS**: for a context-stable, label-invariant class the predicate is closed under
an uncoupled spectator. -/
theorem instAvail_spectator (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘) (R : Type) [Fintype R]
    [DecidableEq R] {T : Type} [Fintype T] [DecidableEq T] {O : Type} [Fintype O] [DecidableEq O]
    {F : O → Matrix T T ℂ →ₗ[ℂ] Matrix T T ℂ} (h : InstAvail 𝓘 T O F) :
    InstAvail 𝓘 (R × T) O (fun a => amplRefL R (F a)) := by
  induction h with
  | op K hK hiso =>
    have := InstAvail.op (𝓘 := 𝓘) (tensorOf (1 : Matrix R R ℂ) K) (hc R _ _ hK)
      (tensorOf_one_isometry' hiso)
    simpa only [amplRefL_conjChannel] using this
  | readout e hP =>
    have hre : ∀ k, tensorOf (1 : Matrix R R ℂ) (Matrix.reindex e e (readProj _ _ k))
        = Matrix.reindex ((Equiv.prodAssoc R _ _).trans ((Equiv.refl R).prodCongr e))
            ((Equiv.prodAssoc R _ _).trans ((Equiv.refl R).prodCongr e)) (readProj (R × _) _ k) :=
      fun k => by rw [tensorOf_one_reindex, tensorOf_one_readProj, reindex_reindex]
    have := InstAvail.readout (𝓘 := 𝓘)
      ((Equiv.prodAssoc R _ _).trans ((Equiv.refl R).prodCongr e))
      fun k => by rw [← hre]; exact hc R _ _ (hP k)
    simpa only [amplRefL_conjChannel, hre] using this
  | coarse f _ ih =>
    have := InstAvail.coarse f ih
    simpa only [amplRefL_sum] using this
  | bind _ _ ihF ihG =>
    have := InstAvail.bind ihF ihG
    simpa only [amplRefL_comp] using this
  | discard hm _ ih =>
    have := InstAvail.discard (𝓘 := 𝓘) hm
      (instAvail_transport hl ih _ (Equiv.prodAssoc R _ _).symm)
    simpa only [amplRefL_discard] using this

/-- **THE LOCAL FORM KEEPS INSTRUMENT REALIZATION**: the spectator extension of an
instrument-realized family is instrument-realized. -/
theorem instAvail_withSpectator (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘) {A : Type}
    [Fintype A] [DecidableEq A] {R : Type} [Fintype R] [DecidableEq R] {n m : ℕ}
    (e : R × (A × Fin n) ≃ A × Fin m) {O : Type} [Fintype O] [DecidableEq O]
    {F : O → Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ}
    (h : InstAvail 𝓘 (A × Fin n) O F) :
    InstAvail 𝓘 (A × Fin m) O (fun a => withSpectator R e (F a)) :=
  instAvail_transport hl (instAvail_spectator hc hl R h) _ e

end Spectator

/-- **THE LOCAL FORM KEEPS BRANCH REALIZATION**: the spectator extension of a branch-realized
operation is branch-realized, because the extension of a conjugation is the conjugation by the
reindexed `1 ⊗ K`, and (C), (L) keep that operator admissible. -/
theorem realized_withSpectator {𝓘 : ImplementationClass} (hc : ContextStable 𝓘)
    (hl : LabelInvariant 𝓘) {A : Type} [Fintype A] [DecidableEq A] {R : Type} [Fintype R]
    [DecidableEq R] {n m : ℕ} (e : R × (A × Fin n) ≃ A × Fin m)
    {Φ : Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ}
    (h : Realized 𝓘 (A × Fin n) Φ) : Realized 𝓘 (A × Fin m) (withSpectator R e Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  refine ⟨ι, inferInstance, fun i => Matrix.reindex e e (tensorOf (1 : Matrix R R ℂ) (K i)), ?_,
    fun i => hl _ _ e _ (hc R _ _ (hK i))⟩
  rw [withSpectator_sum]
  exact Finset.sum_congr rfl fun i _ => withSpectator_conjChannel e (K i)

/-! ### Section F — the theory an architecture generates -/

section Generated

variable (𝓘 : ImplementationClass) (arch : Architecture 𝓘)

/-- **THE THEORY GENERATED BY AN ARCHITECTURE** on a carrier: availability is instrument
realization by the class, on the system and at every level. -/
noncomputable def genTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S where
  avail := fun _ _ _ F => InstAvail 𝓘 S _ F
  availExt := fun _ _ _ _ F => InstAvail 𝓘 _ _ F
  avail_id := instAvail_id (arch.one S)
  avail_coarse := fun _ _ _ _ _ _ _ f h => InstAvail.coarse f h
  availExt_coarse := fun _ _ _ _ _ _ _ _ f h => InstAvail.coarse f h
  availExt_bind := fun _ _ _ _ _ _ _ _ _ hF hG => InstAvail.bind hF hG
  prepAvail := fun n P => 0 < n ∧ ∃ Φ, InstAvail 𝓘 _ Unit (fun _ : Unit => Φ)
    ∧ P = Φ.comp (uniformAttach n)
  prepAvail_uniform := fun n =>
    ⟨n.succ_pos, LinearMap.id, instAvail_id (arch.one _), by rw [LinearMap.id_comp]⟩
  prepAvail_post := by
    rintro n P Φ ⟨hn, Ψ, hΨ, rfl⟩ hΦ
    exact ⟨hn, Φ.comp Ψ, instAvail_one_comp hΦ hΨ, by rw [LinearMap.comp_assoc]⟩
  readout := fun _ k => localLuders k
  readout_avail := fun n => by
    have h := InstAvail.readout (𝓘 := 𝓘) (Equiv.refl (S × Fin n))
      (fun k => by rw [Matrix.reindex_refl_refl]; exact arch.proj S n k)
    simp only [Matrix.reindex_refl_refl] at h
    have e : (fun k : Fin n => localLuders (A := S) k)
        = fun k => conjChannel (readProj S n k) := funext fun k => localLuders_eq_conjChannel k
    rw [e]
    exact h
  readout_local := fun _ k => localLuders_mapSpectatorIndependent k
  prepAvail_discard := by
    rintro n P O _ _ F ⟨hn, Φ, hΦ, rfl⟩ hF
    have e : (fun a => discardWith n (Φ.comp (uniformAttach n)) (F a))
        = fun a => discardWith (A := S) n (uniformAttach n) ((F a).comp Φ) := by
      funext a
      simp only [discardWith, LinearMap.comp_assoc]
    rw [e]
    exact InstAvail.discard hn (instAvail_comp_one hF hΦ)

/-- The generated family. -/
noncomputable def genFamily : TheoryFamily := fun S _ _ => genTheory 𝓘 arch S

theorem genFamily_regrouping : RegroupingInvariant (genFamily 𝓘 arch) := by
  intro S _ _ m _ O _ _ F
  exact Iff.rfl

theorem genFamily_relabelling (hl : LabelInvariant 𝓘) :
    RelabellingInvariant (genFamily 𝓘 arch) := by
  intro S S' _ _ _ _ e O _ _ F h
  exact instAvail_transport hl h S' e

variable {A : Type} [Fintype A] [DecidableEq A]

theorem genTheory_ambient : IsAmbientMember (genTheory 𝓘 arch A) (genFamily 𝓘 arch) :=
  ⟨fun _ _ _ _ => Iff.rfl, fun _ _ _ _ _ _ => Iff.rfl⟩

/-- **GENERATED THEORIES CARRY EMBEDDED OBSERVATION** when the class is label-invariant. -/
theorem genTheory_embeddedObservation (hl : LabelInvariant 𝓘) :
    EmbeddedObservation (genTheory 𝓘 arch A) :=
  ⟨genFamily 𝓘 arch, genFamily_regrouping 𝓘 arch, genFamily_relabelling 𝓘 arch hl,
    genTheory_ambient 𝓘 arch⟩

theorem genTheory_availExt_iff (n : ℕ) {O : Type} [Fintype O] [DecidableEq O]
    (F : O → Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ) :
    (genTheory 𝓘 arch A).availExt n O F ↔ InstAvail 𝓘 (A × Fin n) O F :=
  Iff.rfl

/-- **COMPOSITE UNITARY CONTROL IN THE THEORY OF THE FULL CLASS.** -/
theorem genTheory_fullClass_control : HasCompositeUnitaryControl (genTheory fullClass fullClass_arch A) :=
  fun _ U hU => InstAvail.op U trivial hU

/-- Class inclusion carries instrument availability at every level. -/
theorem genTheory_mono {𝓙 : ImplementationClass} (arch' : Architecture 𝓙)
    (hle : ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → 𝓙 S K) (n : ℕ)
    {O : Type} [Fintype O] [DecidableEq O]
    (F : O → Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ)
    (h : (genTheory 𝓘 arch A).availExt n O F) : (genTheory 𝓙 arch' A).availExt n O F :=
  instAvail_mono hle h

theorem genTheory_generated : ImplementationGenerated (genTheory 𝓘 arch A) 𝓘 :=
  fun _ _ _ _ _ _ => Iff.rfl

theorem genTheory_implementationLocality (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘) :
    ImplementationLocality (genTheory 𝓘 arch A) :=
  ⟨𝓘, genTheory_generated 𝓘 arch, hc, hl⟩

end Generated

/-! ### Section G — the derivation -/

section Derivation

variable {A : Type} [Fintype A] [DecidableEq A] {𝓘 : ImplementationClass}

/-- **OBSERVATIONAL INDEPENDENCE FROM IMPLEMENTATION LOCALITY**, in its parallel
reference-extension form. -/
theorem parallel_of_implementationLocal [Nonempty A] {T : FiniteOperationalTheory A}
    (hg : ImplementationGenerated T 𝓘) (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘) :
    HasParallelReferenceExtension T := by
  intro R _ _ n m e O _ _ F hF
  rcases m with _ | m'
  · exact availExt_zero T _
  rcases n with _ | k
  · exfalso
    have hc' := Fintype.card_congr e
    simp only [Fintype.card_prod, Fintype.card_fin, mul_zero] at hc'
    exact absurd hc'.symm (Nat.mul_pos Fintype.card_pos m'.succ_pos).ne'
  exact (hg (m' + 1) m'.succ_pos O _).mpr
    (instAvail_withSpectator hc hl e ((hg (k + 1) k.succ_pos O F).mp hF))

theorem observationalIndependence_of_implementationLocality [Nonempty A]
    {T : FiniteOperationalTheory A} (h : ImplementationLocality T) : OIHierarchyGeneral.ObservationalIndependence T := by
  obtain ⟨𝓘, hg, hc, hl⟩ := h
  exact parallel_of_implementationLocal hg hc hl

/-- Implementation-generated theories are composite Kraus-sound, for every class. -/
theorem krausSoundExt_of_implementationGenerated [Nonempty A] {T : FiniteOperationalTheory A}
    (hg : ImplementationGenerated T 𝓘) : KrausSoundExt T := by
  intro n O _ _ F hF
  have h := (hg (n + 1) n.succ_pos O F).mp hF
  exact isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
    (cp_of_instAvail h) (instAvail_trace h)

/-- **VALIDITY IS DERIVED** from implementation locality. -/
theorem validity_of_implementationLocality [Nonempty A] {T : FiniteOperationalTheory A}
    (h : ImplementationLocality T) : CompositeOperationalValidity T := by
  obtain ⟨𝓘, hg, -, -⟩ := h
  exact validity_of_krausSoundExt T (krausSoundExt_of_implementationGenerated hg)

end Derivation

/-! ### Section H — necessity and the diagnosis -/

section Necessity

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **EVERY FINITE KRAUS FAMILY IS INSTRUMENT-REALIZED BY THE FULL CLASS**: the Stinespring
circuit of the theory of the full class, a pure seed obtained from the uniform ancilla
by readout and feed-forward, a composite unitary extending the Stinespring isometry, the readout
and the discard, followed by the coarse-graining along the outcome labelling. -/
theorem instAvail_fullClass_of_krausFamily {S : Type} [Fintype S] [DecidableEq S] {O : Type}
    [Fintype O] [DecidableEq O] {F : O → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (hK : IsKrausFamily F) :
    InstAvail fullClass S O F := by
  obtain ⟨n, K, out, hnorm, hKF⟩ := hK
  have hfull := fullInstruments_of_control (genTheory fullClass fullClass_arch S)
    (finiteIsometryExtensionSF_discharged S) genTheory_fullClass_control
  have h := InstAvail.coarse out (hfull n (n + 1) K id hnorm)
  have e : F = fun a => ∑ j ∈ Finset.univ.filter (fun j => out j = a), instrumentBranch K id j := by
    funext a
    rw [hKF a]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp [instrumentBranch, Finset.filter_eq']
  rw [e]
  exact h

/-- **AN EXACT THEORY IS GENERATED BY THE FULL CLASS.** -/
theorem generated_of_qm [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ImplementationGenerated T fullClass := by
  intro N hN O _ _ F
  constructor
  · intro hF
    exact instAvail_fullClass_of_krausFamily (krausFamily_of_exactComposite T h.2 N hN F hF)
  · intro hI
    have : Nonempty (A × Fin N) := ⟨(Classical.arbitrary A, ⟨0, hN⟩)⟩
    exact availExt_of_krausFamily T h.2 N hN F
      (isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
        (cp_of_instAvail hI) (instAvail_trace hI))

/-- **EXACT FINITE OPERATIONAL QM IS IMPLEMENTATION-LOCAL.** -/
theorem implementationLocality_of_qm [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ImplementationLocality T :=
  ⟨fullClass, generated_of_qm T h, fullClass_contextStable, fullClass_labelInvariant⟩

/-- **THE DIAGNOSIS**: the countermodel is not generated by any implementation class — its
available reduction map has no finite physical implementation. -/
theorem countermodel_not_implementationGenerated :
    ¬ ∃ 𝓘 : ImplementationClass, ImplementationGenerated countermodel 𝓘 := by
  rintro ⟨𝓘, hg⟩
  have h := (hg 2 two_pos Unit (fun _ => reduction2 (Fin 2 × Fin 2))).mp
    countermodel_reduction2_available
  exact reduction2_not_cp (cp_of_instAvail h ())

theorem countermodel_not_implementationLocality : ¬ ImplementationLocality countermodel :=
  fun ⟨𝓘, hg, _⟩ => countermodel_not_implementationGenerated ⟨𝓘, hg⟩

/-- **IMPLEMENTATION LOCALITY IS NOT SUPPLIED** by the core, validity, reversible richness
and embedded observation. -/
theorem implementationLocality_independent :
    ∃ T : FiniteOperationalTheory (Fin 2), OICore T ∧ CompositeOperationalValidity T
      ∧ ReversibleRichness T ∧ EmbeddedObservation T ∧ ¬ ImplementationLocality T :=
  ⟨countermodel, countermodel_realizesSealedOICore, countermodel_validity,
    countermodel_reversibleRichness, countermodel_embeddedObservation,
    countermodel_not_implementationLocality⟩

end Necessity

/-! ### Section I — the compressed set -/

section Compressed

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **THE COMPRESSED SET**: implementation locality, reversible richness, embedded
observation. Validity is absent because it is derived; the normalization half of validity is
a theorem of instrument realization. -/
def OIPlusLocal : Prop :=
  ImplementationLocality T ∧ OIHierarchyGeneral.ReversibleRichness T ∧ EmbeddedObservation T

variable [Nonempty A]

theorem oiPlusEmbedded_of_oiPlusLocal (h : OIPlusLocal T) : OIPlusEmbedded T :=
  ⟨validity_of_implementationLocality h.1,
    observationalIndependence_of_implementationLocality h.1, h.2.1, h.2.2⟩

theorem qm_of_oiPlusLocal (h : OIPlusLocal T) : ExactAllFiniteEndomorphicQuantumOps T :=
  qm_of_oiPlusEmbedded T (oiPlusEmbedded_of_oiPlusLocal T h)

theorem oiPlusLocal_of_qm (h : ExactAllFiniteEndomorphicQuantumOps T) : OIPlusLocal T :=
  have hp := oiPlusEmbedded_of_qm T h
  ⟨implementationLocality_of_qm T h, hp.2.2.1, hp.2.2.2⟩

/-- **THE COMPRESSED SET ⟺ FINITE OPERATIONAL QM**, on any nonempty finite carrier. -/
theorem oiPlusLocal_iff_qm : OIPlusLocal T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  ⟨qm_of_oiPlusLocal T, oiPlusLocal_of_qm T⟩

theorem oiPlusLocal_iff_oiPlusEmbedded : OIPlusLocal T ↔ OIPlusEmbedded T := by
  rw [oiPlusLocal_iff_qm, oiPlusEmbedded_iff_qm]

end Compressed

/-- **THE CARRIER-GENERAL STATEMENT**, quantified over the carrier. -/
theorem carrier_general_oiPlusLocal :
    ∀ (A : Type) [Fintype A] [DecidableEq A] [Nonempty A] (T : FiniteOperationalTheory A),
      OIPlusLocal T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  fun _ _ _ _ T => oiPlusLocal_iff_qm T

#print axioms twoPosFamily_regrouping
#print axioms twoPosFamily_relabelling
#print axioms countermodel_ambient
#print axioms countermodel_embeddedObservation
#print axioms countermodel_reversibleRichness
#print axioms redundancy_fails
#print axioms form_fixed_existence_fails
#print axioms conjChannel_trace_iff
#print axioms instAvail_mono
#print axioms instAvail_trace
#print axioms fullClass_contextStable
#print axioms fullClass_labelInvariant
#print axioms cp_of_realized
#print axioms conjChannel_smul
#print axioms realized_conj
#print axioms realized_zero
#print axioms realized_add
#print axioms realized_sum
#print axioms sum_comp'
#print axioms comp_sum'
#print axioms realized_comp
#print axioms realized_smul_nonneg
#print axioms realized_transport
#print axioms realized_id
#print axioms realized_localLuders
#print axioms realized_discard
#print axioms fullClass_arch
#print axioms realized_of_instAvail
#print axioms cp_of_instAvail
#print axioms instAvail_comp_one
#print axioms instAvail_one_comp
#print axioms instAvail_id
#print axioms transport_refl
#print axioms transport_trans
#print axioms transport_comp
#print axioms reindex_reindex
#print axioms reindex_isometry'
#print axioms uniformAttach_reindex
#print axioms transport_discard
#print axioms instAvail_transport
#print axioms tensorOf_conjTranspose
#print axioms tensorOf_mul'
#print axioms tensorOf_one_isometry'
#print axioms amplRefL_conjChannel
#print axioms amplRefL_sum
#print axioms amplRef_apply'
#print axioms refBlockR_amplRef
#print axioms amplRefL_comp
#print axioms tensorOf_one_reindex
#print axioms tensorOf_one_readProj
#print axioms amplRefL_transport
#print axioms refBlockR_reindex_uniformAttach
#print axioms amplRefL_discard
#print axioms instAvail_spectator
#print axioms instAvail_withSpectator
#print axioms realized_withSpectator
#print axioms genFamily_regrouping
#print axioms genFamily_relabelling
#print axioms genTheory_ambient
#print axioms genTheory_embeddedObservation
#print axioms genTheory_availExt_iff
#print axioms genTheory_fullClass_control
#print axioms genTheory_mono
#print axioms genTheory_generated
#print axioms genTheory_implementationLocality
#print axioms parallel_of_implementationLocal
#print axioms observationalIndependence_of_implementationLocality
#print axioms krausSoundExt_of_implementationGenerated
#print axioms validity_of_implementationLocality
#print axioms instAvail_fullClass_of_krausFamily
#print axioms generated_of_qm
#print axioms implementationLocality_of_qm
#print axioms countermodel_not_implementationGenerated
#print axioms countermodel_not_implementationLocality
#print axioms implementationLocality_independent
#print axioms oiPlusEmbedded_of_oiPlusLocal
#print axioms qm_of_oiPlusLocal
#print axioms oiPlusLocal_of_qm
#print axioms oiPlusLocal_iff_qm
#print axioms oiPlusLocal_iff_oiPlusEmbedded
#print axioms carrier_general_oiPlusLocal

end InterventionLocality
end OIBridge
