/-
  OIBridge/ImplementationLocality.lean — the primitive-source audit, second target: the
  source of observational independence.

  ROUND FIFTY-SEVEN. After round fifty-six the carrier-general quantum-complete package is
  composite operational validity, observational independence, reversible richness and
  embedded observation. This file asks where observational independence comes from, in the
  order the audit demands: first whether it is already forced by the other three; then, since
  it is not, what deeper principle supplies it.

  A. THE REDUNDANCY TEST FAILS. The round-34 countermodel (`countermodel`: Kraus families on
  the qubit, 2-positive trace-preserving instruments on every composite) carries the OI
  core, composite operational validity and reversible richness, and it carries EMBEDDED
  OBSERVATION: the 2-positive-instrument theory on every finite carrier (`twoPosTheory`,
  `twoPosFamily`) is a regrouping- and relabelling-invariant family whose qubit member is
  the countermodel on the composites and, by `twoPositive_qubit_cp`, on the system. And it
  has no observational independence (`countermodel_not_inert`). So
  `redundancy_fails`: validity + reversible richness + embedded observation do not imply
  observational independence, and the four-part package does not compress to three.

  B/C. FORM WITHOUT EXISTENCE. Round thirty-seven proved that locality fixes the form of a
  spectator extension uniquely (`isSpectatorExtension_iff`: any extension of `Φ` along `e`
  is `withSpectator R e Φ`), and the countermodel shows that the form being fixed does not
  make the extension available: `form_fixed_existence_fails` records, for the available
  two-qubit reduction map, that its qutrit spectator extension is uniquely determined and
  not available. The missing physics is existence, not form.

  D. THE PRIMITIVE, BELOW AVAILABILITY. An IMPLEMENTATION CLASS `𝓘` says, at every finite
  carrier, which single operators are admissible physical implementations
  (`ImplementationClass`). An operation is REALIZED by the class when it is a finite sum of
  conjugations by admissible operators (`Realized`). Then

      (G) IMPLEMENTATION GENERATION — at every positive level, a family is available exactly
          when each branch is realized by the class and the aggregate trace is preserved
          (`ImplementationGenerated`);
      (C) CONTEXT STABILITY — adjoining dynamically uncoupled degrees of freedom leaves an
          admissible implementation admissible and unchanged on its original support:
          `𝓘 S K → 𝓘 (R × S) (1_R ⊗ K)` (`ContextStable`);
      (L) LABEL INVARIANCE — admissibility is transported along carrier bijections
          (`LabelInvariant`).

  `ImplementationLocality T` is the existence of such a class. Neither (C) nor (L) mentions
  availability, `withSpectator`, `HasParallelReferenceExtension` or
  `InertSpectatorCompositionality`; (G) mentions availability only to say that it is
  generated by implementations.

  E. THE DERIVATION. The spectator extension of a realized operation is realized
  (`realized_withSpectator`): the extension of a conjugation is the conjugation by the
  reindexed `1 ⊗ K` (round thirty-seven's `withSpectator_conjChannel`, the local form), and
  (C), (L) keep that operator admissible. The aggregate trace is preserved by the extension.
  Hence `observationalIndependence_of_implementationLocality`. Validity is derived as well
  (`validity_of_implementationLocality`): realized operations are completely positive.

  F. NECESSITY. Exact finite operational QM is implementation-local with every operator
  admissible (`implementationLocality_of_qm`).

  THE DIAGNOSIS. The countermodel is not implementation-generated by ANY class
  (`countermodel_not_implementationGenerated`): its available reduction map is not
  completely positive, so no finite physical implementation realizes it. Its failure is
  implementability, not context stability. `implementationLocality_independent` records that
  the core, validity, reversible richness and embedded observation do not supply
  implementation locality.

  THE COMPRESSED SET. `OIPlusLocal` is implementation locality, reversible richness and
  embedded observation; `carrier_general_oiPlusLocal` proves it equivalent to exact finite
  endomorphic operational QM on every nonempty finite carrier. Validity is absent because it
  is derived; the normalization half of validity is carried by the trace clause of (G), and
  that is said plainly rather than hidden.

  WHAT IS NOT CLAIMED. Whether context stability is redundant given implementation
  generation (a theory generated by a class not closed under `1 ⊗ ·` and failing
  observational independence) is not settled here. The converse from observational
  independence to implementation locality is not claimed outside the OI⁺ context. Nothing
  here bears on the sources of either clause of reversible richness.
-/

import OIBridge.EmbeddedObservation

namespace OIBridge
namespace InterventionLocality

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — the redundancy test fails: the 2-positive family -/

section TwoPos

/-- **THE 2-POSITIVE-INSTRUMENT THEORY** on an arbitrary finite carrier: 2-positive branches
with the trace preserved in aggregate, on the system and on every composite. -/
noncomputable def twoPosTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S where
  avail := fun _ _ _ F => IsTwoPositiveInstrument F
  availExt := fun _ _ _ _ F => IsTwoPositiveInstrument F
  avail_id := ⟨fun _ => by rw [← conjChannel_one]; exact conjChannel_twoPositive _, fun X => by
    rw [Fintype.sum_unique, LinearMap.id_apply]⟩
  avail_coarse := by
    rintro O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => isTwoPositive_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_coarse := by
    rintro n O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => isTwoPositive_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_bind := by
    rintro n O O' _ _ _ _ F G ⟨hF2, hFtr⟩ hG
    refine ⟨fun c => isTwoPositive_comp ((hG c.1).1 c.2) (hF2 c.1), fun X => ?_⟩
    rw [Fintype.sum_prod_type]
    show ∑ a, ∑ b, ((G a b) ((F a) X)).trace = X.trace
    rw [Finset.sum_congr rfl fun a _ => (hG a).2 ((F a) X)]
    exact hFtr X
  prepAvail := fun n P => 0 < n ∧ ∃ Φ, IsTwoPositiveInstrument (fun _ : Unit => Φ)
    ∧ P = Φ.comp (uniformAttach n)
  prepAvail_uniform := fun n =>
    ⟨n.succ_pos, LinearMap.id,
      ⟨fun _ => by rw [← conjChannel_one]; exact conjChannel_twoPositive _, fun X => by
        rw [Fintype.sum_unique, LinearMap.id_apply]⟩, by rw [LinearMap.id_comp]⟩
  prepAvail_post := by
    rintro n P Φ ⟨hn, Ψ, ⟨hΨ2, hΨtr⟩, rfl⟩ ⟨hΦ2, hΦtr⟩
    refine ⟨hn, Φ.comp Ψ, ⟨fun _ => isTwoPositive_comp (hΦ2 ()) (hΨ2 ()), fun X => ?_⟩,
      by rw [LinearMap.comp_assoc]⟩
    rw [Fintype.sum_unique]
    have h1 := hΦtr (Ψ X)
    rw [Fintype.sum_unique] at h1
    have h2 := hΨtr X
    rw [Fintype.sum_unique] at h2
    exact h1.trans h2
  readout := fun _ k => localLuders k
  readout_avail := fun _ => ⟨fun k => localLuders_twoPositive k, localLuders_trace_sum⟩
  readout_local := fun _ k => localLuders_mapSpectatorIndependent k
  prepAvail_discard := by
    rintro n P O _ _ F ⟨hn, Φ, ⟨hΦ2, hΦtr⟩, rfl⟩ ⟨hF2, hFtr⟩
    refine ⟨fun a => ?_, fun X => ?_⟩
    · show IsTwoPositive (discardWith n (Φ.comp (uniformAttach n)) (F a))
      have h : discardWith n (Φ.comp (uniformAttach n)) (F a)
          = discardWith n (uniformAttach n) ((F a).comp Φ) := by
        simp only [discardWith, LinearMap.comp_assoc]
      rw [h]
      exact discardWith_uniform_twoPositive (isTwoPositive_comp (hF2 a) (hΦ2 ()))
    · show ∑ a, ((discardWith n (Φ.comp (uniformAttach n)) (F a)) X).trace = X.trace
      rw [Finset.sum_congr rfl fun a _ => discardWith_trace n _ (F a) X, hFtr]
      have h := hΦtr (uniformAttach n X)
      rw [Fintype.sum_unique] at h
      exact h.trans (uniformAttach_trace n hn.ne' X)

/-- The 2-positive family. -/
noncomputable def twoPosFamily : TheoryFamily := fun S _ _ => twoPosTheory S

theorem twoPosFamily_regrouping : RegroupingInvariant twoPosFamily := by
  intro S _ _ m _ O _ _ F
  exact Iff.rfl

theorem twoPosFamily_relabelling : RelabellingInvariant twoPosFamily := by
  intro S S' _ _ _ _ e O _ _ F ⟨h2, htr⟩
  refine ⟨fun a => twoPositive_transport e (h2 a), fun X => ?_⟩
  simp only [trace_transport]
  rw [htr, trace_reindex]

/-- The round-34 countermodel is the qubit member of the 2-positive family: definitionally
on every composite, and on the system because a 2-positive map of a qubit is completely
positive (`twoPositive_qubit_cp`). -/
theorem countermodel_ambient : IsAmbientMember countermodel twoPosFamily := by
  refine ⟨fun O _ _ F => ⟨fun hF => ?_, fun hF => ?_⟩, fun N _ O _ _ F => Iff.rfl⟩
  · obtain ⟨hcp, htr⟩ := krausFamily_cp_tr hF
    exact ⟨fun a => cp_referencePositive (Fin 2) _ (hcp a), htr⟩
  · obtain ⟨h2, htr⟩ := hF
    exact isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
      (fun a => twoPositive_qubit_cp _ (h2 a)) htr

theorem countermodel_embeddedObservation : EmbeddedObservation countermodel :=
  ⟨twoPosFamily, twoPosFamily_regrouping, twoPosFamily_relabelling, countermodel_ambient⟩

theorem countermodel_reversibleRichness : ReversibleRichness countermodel :=
  reversibleRichness_of_control _ ⟨countermodel_validity, countermodel_systemToLevelOne⟩
    countermodel_control

/-- **THE REDUNDANCY TEST FAILS**: validity, reversible richness and embedded observation
(with the OI core) do not imply observational independence. -/
theorem redundancy_fails :
    ∃ T : FiniteOperationalTheory (Fin 2), OICore T ∧ CompositeOperationalValidity T
      ∧ ReversibleRichness T ∧ EmbeddedObservation T ∧ ¬ ObservationalIndependence T :=
  ⟨countermodel, countermodel_realizesSealedOICore, countermodel_validity,
    countermodel_reversibleRichness, countermodel_embeddedObservation,
    fun h => countermodel_not_inert ((observationalIndependence_iff_inert _).mp h)⟩

end TwoPos

/-! ### Section B — form without existence -/

section Form

/-- **THE FORM IS FIXED AND THE EXTENSION IS NOT AVAILABLE**: the two-qubit reduction map is
available in the countermodel, every spectator extension of it along the qutrit index is
`withSpectator`, and that extension is not available. -/
theorem form_fixed_existence_fails :
    countermodel.availExt 2 Unit (fun _ => reduction2 (Fin 2 × Fin 2))
    ∧ (∀ G, IsSpectatorExtension qutritIdx (reduction2 (Fin 2 × Fin 2)) G
        ↔ G = withSpectator (Fin 3) qutritIdx (reduction2 (Fin 2 × Fin 2)))
    ∧ ¬ countermodel.availExt 6 Unit
        (fun _ => withSpectator (Fin 3) qutritIdx (reduction2 (Fin 2 × Fin 2))) := by
  refine ⟨countermodel_reduction2_available, fun G => isSpectatorExtension_iff _ _ _, ?_⟩
  rintro ⟨h2, -⟩
  have hpos := positive_of_twoPositive (h2 ())
    (posSemidef_reindex qutritIdx (Matrix.posSemidef_vecMulVec_self_star maxEnt3))
  rw [withSpectator_reindex] at hpos
  exact amplRef_reduction2_maxEnt3_not_posSemidef (posSemidef_of_reindex qutritIdx hpos)

end Form

/-! ### Section C — the primitive: implementation classes -/

section Primitive

/-- An implementation class: at every finite carrier, which single operators are admissible
physical implementations. -/
abbrev ImplementationClass :=
  ∀ (S : Type) [Fintype S] [DecidableEq S], Matrix S S ℂ → Prop

/-- An operation is REALIZED by a class when it is a finite sum of conjugations by admissible
operators. -/
def Realized (𝓘 : ImplementationClass) (S : Type) [Fintype S] [DecidableEq S]
    (Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) : Prop :=
  ∃ (ι : Type) (_ : Fintype ι) (K : ι → Matrix S S ℂ),
    Φ = ∑ i, conjChannel (K i) ∧ ∀ i, 𝓘 S (K i)

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **(G) IMPLEMENTATION GENERATION**: at every positive level, availability is realization
by the class together with aggregate trace preservation. -/
def ImplementationGenerated (T : FiniteOperationalTheory A) (𝓘 : ImplementationClass) : Prop :=
  ∀ (N : ℕ), 0 < N → ∀ (O : Type) [Fintype O] [DecidableEq O]
    (F : O → Matrix (A × Fin N) (A × Fin N) ℂ →ₗ[ℂ] Matrix (A × Fin N) (A × Fin N) ℂ),
    T.availExt N O F ↔ (∀ a, Realized 𝓘 (A × Fin N) (F a)) ∧ ∀ X, ∑ a, ((F a) X).trace = X.trace

/-- **(C) CONTEXT STABILITY**: adjoining uncoupled degrees of freedom leaves an admissible
implementation admissible, unchanged on its original support. -/
def ContextStable (𝓘 : ImplementationClass) : Prop :=
  ∀ (R S : Type) [Fintype R] [DecidableEq R] [Fintype S] [DecidableEq S] (K : Matrix S S ℂ),
    𝓘 S K → 𝓘 (R × S) (tensorOf (1 : Matrix R R ℂ) K)

/-- **(L) LABEL INVARIANCE**: admissibility is transported along carrier bijections. -/
def LabelInvariant (𝓘 : ImplementationClass) : Prop :=
  ∀ (S S' : Type) [Fintype S] [DecidableEq S] [Fintype S'] [DecidableEq S'] (e : S ≃ S')
    (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S' (Matrix.reindex e e K)

/-- **IMPLEMENTATION LOCALITY**: availability is generated by a context-stable,
label-invariant implementation class. -/
def ImplementationLocality (T : FiniteOperationalTheory A) : Prop :=
  ∃ 𝓘 : ImplementationClass, ImplementationGenerated T 𝓘 ∧ ContextStable 𝓘 ∧ LabelInvariant 𝓘

end Primitive

/-! ### Section D — the derivation -/

section Derivation

variable {A : Type} [Fintype A] [DecidableEq A]

/-- A realized operation is completely positive. -/
theorem cp_of_realized {𝓘 : ImplementationClass} {S : Type} [Fintype S] [DecidableEq S]
    {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (h : Realized 𝓘 S Φ) : IsCompletelyPositive Φ := by
  obtain ⟨ι, _, K, rfl, -⟩ := h
  exact cp_sum _ _ fun i _ => conjChannel_cp _

/-- **THE LOCAL FORM KEEPS REALIZATION**: the spectator extension of a realized operation is
realized, because the extension of a conjugation is the conjugation by the reindexed
`1 ⊗ K`, and (C), (L) keep that operator admissible. -/
theorem realized_withSpectator {𝓘 : ImplementationClass} (hc : ContextStable 𝓘)
    (hl : LabelInvariant 𝓘) {R : Type} [Fintype R] [DecidableEq R] {n m : ℕ}
    (e : R × (A × Fin n) ≃ A × Fin m)
    {Φ : Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ}
    (h : Realized 𝓘 (A × Fin n) Φ) : Realized 𝓘 (A × Fin m) (withSpectator R e Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  refine ⟨ι, inferInstance, fun i => Matrix.reindex e e (tensorOf (1 : Matrix R R ℂ) (K i)), ?_,
    fun i => hl _ _ e _ (hc R _ _ (hK i))⟩
  rw [withSpectator_sum]
  exact Finset.sum_congr rfl fun i _ => withSpectator_conjChannel e (K i)

/-- **OBSERVATIONAL INDEPENDENCE FROM IMPLEMENTATION LOCALITY**, in its parallel
reference-extension form. -/
theorem parallel_of_implementationLocal [Nonempty A] {T : FiniteOperationalTheory A}
    {𝓘 : ImplementationClass} (hg : ImplementationGenerated T 𝓘) (hc : ContextStable 𝓘)
    (hl : LabelInvariant 𝓘) : HasParallelReferenceExtension T := by
  intro R _ _ n m e O _ _ F hF
  rcases m with _ | m'
  · exact availExt_zero T _
  rcases n with _ | k
  · exfalso
    have hc' := Fintype.card_congr e
    simp only [Fintype.card_prod, Fintype.card_fin, mul_zero] at hc'
    exact absurd hc'.symm (Nat.mul_pos Fintype.card_pos m'.succ_pos).ne'
  obtain ⟨hreal, htr⟩ := (hg (k + 1) k.succ_pos O F).mp hF
  refine (hg (m' + 1) m'.succ_pos O _).mpr
    ⟨fun a => realized_withSpectator hc hl e (hreal a), fun X => ?_⟩
  simp only [withSpectator_apply, trace_reindex, trace_amplRef]
  rw [Finset.sum_comm]
  rw [Finset.sum_congr rfl fun i _ => htr (refBlockR (Matrix.reindex e.symm e.symm X) i i),
    ← trace_eq_sum_refBlockR, trace_reindex]

theorem observationalIndependence_of_implementationLocality [Nonempty A]
    {T : FiniteOperationalTheory A} (h : ImplementationLocality T) : OIHierarchyGeneral.ObservationalIndependence T := by
  obtain ⟨𝓘, hg, hc, hl⟩ := h
  exact parallel_of_implementationLocal hg hc hl

/-- Implementation-generated theories are composite Kraus-sound. -/
theorem krausSoundExt_of_implementationGenerated [Nonempty A] {T : FiniteOperationalTheory A}
    {𝓘 : ImplementationClass} (hg : ImplementationGenerated T 𝓘) : KrausSoundExt T := by
  intro n O _ _ F hF
  obtain ⟨hreal, htr⟩ := (hg (n + 1) n.succ_pos O F).mp hF
  exact isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
    (fun a => cp_of_realized (hreal a)) htr

/-- **VALIDITY IS DERIVED** from implementation locality. -/
theorem validity_of_implementationLocality [Nonempty A] {T : FiniteOperationalTheory A}
    (h : ImplementationLocality T) : CompositeOperationalValidity T := by
  obtain ⟨𝓘, hg, -, -⟩ := h
  exact validity_of_krausSoundExt T (krausSoundExt_of_implementationGenerated hg)

end Derivation

/-! ### Section E — necessity and the diagnosis -/

section Necessity

variable {A : Type} [Fintype A] [DecidableEq A]

/-- The full class: every operator admissible at every carrier. -/
def fullClass : ImplementationClass := fun _ _ _ _ => True

theorem fullClass_contextStable : ContextStable fullClass := fun _ _ _ _ _ _ _ _ => trivial

theorem fullClass_labelInvariant : LabelInvariant fullClass := fun _ _ _ _ _ _ _ _ _ => trivial

/-- An exact theory is generated by the full class. -/
theorem generated_of_qm [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ImplementationGenerated T fullClass := by
  intro N hN O _ _ F
  constructor
  · intro hF
    obtain ⟨r, K, out, hnorm, hKF⟩ := krausFamily_of_exactComposite T h.2 N hN F hF
    refine ⟨fun a => ⟨{k : Fin (r + 1) // out k = a}, inferInstance, fun k => K k.1, ?_,
      fun _ => trivial⟩, ?_⟩
    · rw [hKF a]
      exact Finset.sum_subtype _ (fun k => by simp) (fun k => conjChannel (K k))
    exact (krausFamily_cp_tr ⟨r, K, out, hnorm, hKF⟩).2
  · rintro ⟨hreal, htr⟩
    have : Nonempty (A × Fin N) := ⟨(Classical.arbitrary A, ⟨0, hN⟩)⟩
    exact availExt_of_krausFamily T h.2 N hN F
      (isKrausFamily_of_cp_of_factorization (psdFactorization_discharged _) F
        (fun a => cp_of_realized (hreal a)) htr)

/-- **EXACT FINITE OPERATIONAL QM IS IMPLEMENTATION-LOCAL.** -/
theorem implementationLocality_of_qm [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ImplementationLocality T :=
  ⟨fullClass, generated_of_qm T h, fullClass_contextStable, fullClass_labelInvariant⟩

/-- **THE DIAGNOSIS**: the countermodel is not generated by any implementation class — its
available reduction map has no finite physical implementation. -/
theorem countermodel_not_implementationGenerated :
    ¬ ∃ 𝓘 : ImplementationClass, ImplementationGenerated countermodel 𝓘 := by
  rintro ⟨𝓘, hg⟩
  have h := (hg 2 two_pos Unit (fun _ => reduction2 (Fin 2 × Fin 2))).mp
    countermodel_reduction2_available
  exact reduction2_not_cp (cp_of_realized (h.1 ()))

theorem countermodel_not_implementationLocality : ¬ ImplementationLocality countermodel :=
  fun ⟨𝓘, hg, _⟩ => countermodel_not_implementationGenerated ⟨𝓘, hg⟩

/-- **IMPLEMENTATION LOCALITY IS NOT SUPPLIED** by the core, validity, reversible richness
and embedded observation. -/
theorem implementationLocality_independent :
    ∃ T : FiniteOperationalTheory (Fin 2), OICore T ∧ CompositeOperationalValidity T
      ∧ ReversibleRichness T ∧ EmbeddedObservation T ∧ ¬ ImplementationLocality T :=
  ⟨countermodel, countermodel_realizesSealedOICore, countermodel_validity,
    countermodel_reversibleRichness, countermodel_embeddedObservation,
    countermodel_not_implementationLocality⟩

end Necessity

/-! ### Section F — the compressed set -/

section Compressed

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **THE COMPRESSED SET**: implementation locality, reversible richness, embedded
observation. Validity is absent because it is derived; the normalization half of validity is
the trace clause of implementation generation. -/
def OIPlusLocal : Prop :=
  ImplementationLocality T ∧ OIHierarchyGeneral.ReversibleRichness T ∧ EmbeddedObservation T

variable [Nonempty A]

theorem oiPlusEmbedded_of_oiPlusLocal (h : OIPlusLocal T) : OIPlusEmbedded T :=
  ⟨validity_of_implementationLocality h.1,
    observationalIndependence_of_implementationLocality h.1, h.2.1, h.2.2⟩

theorem qm_of_oiPlusLocal (h : OIPlusLocal T) : ExactAllFiniteEndomorphicQuantumOps T :=
  qm_of_oiPlusEmbedded T (oiPlusEmbedded_of_oiPlusLocal T h)

theorem oiPlusLocal_of_qm (h : ExactAllFiniteEndomorphicQuantumOps T) : OIPlusLocal T :=
  have hp := oiPlusEmbedded_of_qm T h
  ⟨implementationLocality_of_qm T h, hp.2.2.1, hp.2.2.2⟩

/-- **THE COMPRESSED SET ⟺ FINITE OPERATIONAL QM**, on any nonempty finite carrier. -/
theorem oiPlusLocal_iff_qm : OIPlusLocal T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  ⟨qm_of_oiPlusLocal T, oiPlusLocal_of_qm T⟩

theorem oiPlusLocal_iff_oiPlusEmbedded : OIPlusLocal T ↔ OIPlusEmbedded T := by
  rw [oiPlusLocal_iff_qm, oiPlusEmbedded_iff_qm]

end Compressed

/-- **THE CARRIER-GENERAL STATEMENT**, quantified over the carrier. -/
theorem carrier_general_oiPlusLocal :
    ∀ (A : Type) [Fintype A] [DecidableEq A] [Nonempty A] (T : FiniteOperationalTheory A),
      OIPlusLocal T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  fun _ _ _ _ T => oiPlusLocal_iff_qm T

#print axioms twoPosFamily_regrouping
#print axioms twoPosFamily_relabelling
#print axioms countermodel_ambient
#print axioms countermodel_embeddedObservation
#print axioms countermodel_reversibleRichness
#print axioms redundancy_fails
#print axioms form_fixed_existence_fails
#print axioms cp_of_realized
#print axioms realized_withSpectator
#print axioms parallel_of_implementationLocal
#print axioms observationalIndependence_of_implementationLocality
#print axioms krausSoundExt_of_implementationGenerated
#print axioms validity_of_implementationLocality
#print axioms fullClass_contextStable
#print axioms fullClass_labelInvariant
#print axioms generated_of_qm
#print axioms implementationLocality_of_qm
#print axioms countermodel_not_implementationGenerated
#print axioms countermodel_not_implementationLocality
#print axioms implementationLocality_independent
#print axioms oiPlusEmbedded_of_oiPlusLocal
#print axioms qm_of_oiPlusLocal
#print axioms oiPlusLocal_of_qm
#print axioms oiPlusLocal_iff_qm
#print axioms oiPlusLocal_iff_oiPlusEmbedded
#print axioms carrier_general_oiPlusLocal

end InterventionLocality
end OIBridge
