/-
  OIBridge/IndependenceCensus.lean — the OI independence census: one shared C1–C4 core
  carrying three inequivalent coherent completions.

  PHASE THREE, ROUND TWENTY-THREE. Rounds fifteen through twenty-two ran the
  constructive direction: how far bare Observation Incompleteness reaches toward
  operational quantum mechanics, and which completion principles have to be named
  along the way. Round twenty-two closed the last derivable link. What remains is the
  converse question, and this file settles it by explicit countermodel:

      ┌────────────────────────────────────────────────────────────────────┐
      │  C1–C4 OI does NOT select the unrestricted operational completion.  │
      │  One and the same controlled-minimal, memory-bearing OI process     │
      │  admits three completions that agree on every classical comb and    │
      │  disagree on each of the three named bridges in turn.               │
      └────────────────────────────────────────────────────────────────────┘

  §A — THE SHARED SWAP-MEMORY CORE. Three bits `(v,h,b)`; the observer reads `(v,b)`
  and `h` is hidden. The passive step is `σ(v,h,b) = (h,v,b)` and the control is
  `τ(v,h,b) = (v,h,b⊕1)`. This core is finite, reversible, and commuting
  (`sigma_tau_commute`). C1 is literal: `v_{t+1} = h_t`, so the hidden bit drives the
  visible future (`core_hidden_drives_visible`). C2 is structural, not merely
  statistical: `v_{t+2} = v_t` (`core_visible_period_two`), so the visible stream
  carries a genuine one-bit memory. And the core is already observer-minimal — the two
  step visible itinerary separates all eight states (`core_observer_minimal`), so no
  quotient collapses it.

  §B — THE COMB IDENTITY. `threeCompletions_same_classical_comb`: for EVERY classical
  preparation and EVERY finite word of passive steps, `τ`-controls, and rank-one
  readouts, all three completions return exactly the same branch statistics as the
  common classical core. Round seventeen's comb blindness supplies the intervention
  steps and round twenty-two's Lüders branch supplies the readouts — the fold stays
  diagonal throughout, so the three completions are operationally indistinguishable
  to the whole OI data stream, not merely on unitary words.

  §C — THE THREE FAILURES, hierarchically. Each completion satisfies every bridge above
  it and fails the next:

    (1) `nonFunctorial_not_functorial` — CPTP, classically exact, but the `τ`-member
        dephases, so `Φ_τ ∘ Φ_τ ≠ Φ_e`.  ⇒ C1–C4 ⇏ H-functor.
    (2) `nonTensor_not_local` — a STRICT (not merely projective) unitary
        representation of `ℤ₂ × ℤ₂`, hence functorial, whose `τ`-lift is not
        `I_vh ⊗ M_b`: its b-flip amplitude is `1` on the `v = h` sector and `±i` on
        `v ≠ h`, and one matrix entry of a genuine local operator cannot be both.
        ⇒ C1–C4 + H-functor ⇏ H-tensor.
    (3) `restricted_controlLie_proper` — functorial AND tensor-local, with the passive
        swap generated by `H = π·P₋ ⊗ I_b`; every control commutes with `H`, so the
        dynamical control Lie algebra is the single real line `ℝ(-iH)`, a proper
        subalgebra of `su(D)`.  ⇒ C1–C4 + H-functor + H-tensor ⇏ `𝔏₀ = su(D)`.

  WORDING DISCIPLINE. Case (3) is not "non-quantum": it is ordinary quantum kinematics
  with a restricted reachable-control subgroup. The theorem says bare OI does not imply
  the UNRESTRICTED finite operational quantum package — not that C1–C4 fail to imply any
  quantum description. `S ⇔ D ⇔ Q_fb` is untouched. Cases (1) and (2) are OI-compatible
  coherent completions, not automatically new fundamental physical theories.

  RECORDED STANDARD FACT. Case (3) certifies `exp(-iH) = U_σ` algebraically, by
  `passiveProj_idempotent` together with `one_sub_two_passiveProj`: for an idempotent
  `P`, `exp(zP) = 1 + (e^z - 1)P`, so `exp(-iπP₋) = 1 - 2P₋ = S ⊗ I_b`. The projector
  exponential series itself is recorded, not re-derived, exactly as round nineteen
  recorded Lie integration.

  Kernel check:  cd verification/lean-mathlib && lake exe cache get && lake build
-/
import OIBridge.BranchSelector

namespace OIBridge
namespace IndependenceCensus

open Complex Matrix CoherentLift CoherentExtension ProjectiveAction ControlLie
open BranchSelector
open scoped ComplexOrder

local notation "conj'" => (starRingEnd ℂ)

/-! ### Section A — the shared swap-memory OI core -/

/-- The visible/hidden pair `(v,h)`. -/
abbrev VH := Bool × Bool

/-- The core state `((v,h),b)`: the carrier is `ℋ_vh ⊗ ℋ_b`. -/
abbrev Core := VH × Bool

/-- The observer reads `(v,b)`; the middle bit `h` is hidden. -/
def vis (p : Core) : Bool × Bool := (p.1.1, p.2)

/-- The passive step `σ(v,h,b) = (h,v,b)`. -/
def swapFn : Core → Core := fun p => ((p.1.2, p.1.1), p.2)

/-- The control `τ(v,h,b) = (v,h,b⊕1)`. -/
def flipFn : Core → Core := fun p => (p.1, !p.2)

theorem swapFn_involutive : Function.Involutive swapFn := fun _ => rfl

theorem flipFn_involutive : Function.Involutive flipFn := by
  intro p
  show (p.1, !!p.2) = p
  rw [Bool.not_not]

/-- The passive dynamics as a permutation of the core. -/
def sigmaPerm : Equiv.Perm Core := swapFn_involutive.toPerm

/-- The control as a permutation of the core. -/
def tauPerm : Equiv.Perm Core := flipFn_involutive.toPerm

@[simp] theorem sigmaPerm_apply (p : Core) : sigmaPerm p = swapFn p := rfl
@[simp] theorem tauPerm_apply (p : Core) : tauPerm p = flipFn p := rfl
@[simp] theorem sigmaPerm_symm_apply (p : Core) : sigmaPerm.symm p = swapFn p := rfl
@[simp] theorem tauPerm_symm_apply (p : Core) : tauPerm.symm p = flipFn p := rfl

/-- The core is reversible: the passive step is an involution. -/
theorem sigmaPerm_sq : sigmaPerm * sigmaPerm = 1 :=
  Equiv.ext fun p => swapFn_involutive p

/-- The control is an involution. -/
theorem tauPerm_sq : tauPerm * tauPerm = 1 :=
  Equiv.ext fun p => flipFn_involutive p

/-- **The core is commuting**: passive evolution and control do not interfere. -/
theorem sigma_tau_commute : sigmaPerm * tauPerm = tauPerm * sigmaPerm :=
  Equiv.ext fun _ => rfl

/-- **C1, literally.** The hidden bit drives the visible future: two states with the
same visible readout are separated after a single passive step. -/
theorem core_hidden_drives_visible :
    ∃ p q : Core, vis p = vis q ∧ p ≠ q ∧ vis (swapFn p) ≠ vis (swapFn q) := by
  decide

/-- **C2, structurally.** The visible stream carries a genuine one-bit memory:
`v_{t+2} = v_t`, while `v_{t+1}` is the hidden bit. -/
theorem core_visible_period_two (p : Core) : vis (swapFn (swapFn p)) = vis p := rfl

/-- The two-step visible itinerary. -/
def itin (p : Core) : List (Bool × Bool) := [vis p, vis (swapFn p)]

/-- **The core is already observer-minimal**: the two-step visible itinerary separates
all eight states, so no observational quotient collapses it. -/
theorem core_observer_minimal : ∀ p q : Core, itin p = itin q → p = q := by decide

/-! ### Section B — the three completions and the comb identity -/

/-- The rank-one phase correlation of a phase assignment. -/
def rankOneC (d : Core → ℂ) : Matrix Core Core ℂ :=
  Matrix.of fun s t => d s * conj' (d t)

/-- The all-ones correlation: the phase-free coherent member. -/
def allOnes : Matrix Core Core ℂ := rankOneC (fun _ => 1)

/-- Complete dephasing: the identity correlation. -/
def dephaseC : Matrix Core Core ℂ := Matrix.of fun s t => if s = t then 1 else 0

theorem rankOneC_apply (d : Core → ℂ) (s t : Core) :
    rankOneC d s t = d s * conj' (d t) := rfl

/-- Every rank-one phase correlation is positive semidefinite. -/
theorem rankOneC_posSemidef (d : Core → ℂ) : (rankOneC d).PosSemidef := by
  have hfac : rankOneC d = Matrix.vecMulVec d (star d) := by
    ext s t
    rw [Matrix.vecMulVec_apply, Pi.star_apply, Complex.star_def]
    rfl
  rw [hfac]
  exact Matrix.posSemidef_vecMulVec_self_star d

theorem rankOneC_diag (d : Core → ℂ) (hd : ∀ s, d s * conj' (d s) = 1) (s : Core) :
    rankOneC d s s = 1 := hd s

theorem allOnes_diag (s : Core) : allOnes s s = 1 := by
  show (1 : ℂ) * conj' 1 = 1
  rw [map_one, one_mul]

theorem allOnes_posSemidef : allOnes.PosSemidef := rankOneC_posSemidef _

theorem dephaseC_eq_one : dephaseC = (1 : Matrix Core Core ℂ) := by
  ext s t
  rw [Matrix.one_apply]
  rfl

theorem dephaseC_diag (s : Core) : dephaseC s s = 1 := if_pos rfl

theorem dephaseC_posSemidef : dephaseC.PosSemidef := by
  rw [dephaseC_eq_one]; exact Matrix.PosSemidef.one

/-- The two OI interventions: the passive step and the `τ`-control. -/
inductive Gen
  | pass
  | ctrl
  deriving DecidableEq

/-- The classical action of each intervention — shared by all three completions. -/
def genPerm : Gen → Equiv.Perm Core
  | .pass => sigmaPerm
  | .ctrl => tauPerm

/-- **The nonfactorizable phase.** Trivial on the `v = h` sector and `±i` on `v ≠ h`,
with the sign set by `b`. It depends on `v ⊕ h`, hence is invariant under the passive
swap — which is what lets the two lifts commute strictly. -/
def nlPhase : Core → ℂ := fun p =>
  if p.1.1 = p.1.2 then 1 else (if p.2 then -Complex.I else Complex.I)

theorem nlPhase_unimodular (p : Core) : nlPhase p * conj' (nlPhase p) = 1 := by
  obtain ⟨⟨v, h⟩, b⟩ := p
  cases v <;> cases h <;> cases b <;> simp [nlPhase]

/-- The phase is invariant under the passive swap: it depends only on `v ⊕ h` and `b`. -/
theorem nlPhase_swap_invariant (p : Core) : nlPhase (swapFn p) = nlPhase p := by
  obtain ⟨⟨v, h⟩, b⟩ := p
  cases v <;> cases h <;> cases b <;> rfl

/-- **Completion 1** — CPTP and classically exact, but the control member dephases. -/
def nonFunctorialC : Gen → Matrix Core Core ℂ
  | .pass => allOnes
  | .ctrl => dephaseC

/-- **Completion 2** — a strict unitary representation whose control lift is not
tensor-local. -/
def nonTensorC : Gen → Matrix Core Core ℂ
  | .pass => allOnes
  | .ctrl => rankOneC nlPhase

/-- **Completion 3** — the phase-free permutation lifts: functorial and tensor-local. -/
def restrictedC : Gen → Matrix Core Core ℂ
  | _ => allOnes

theorem nonFunctorialC_diag : ∀ g s, nonFunctorialC g s s = 1
  | .pass, s => allOnes_diag s
  | .ctrl, s => dephaseC_diag s

theorem nonTensorC_diag : ∀ g s, nonTensorC g s s = 1
  | .pass, s => allOnes_diag s
  | .ctrl, s => rankOneC_diag nlPhase nlPhase_unimodular s

theorem restrictedC_diag : ∀ g s, restrictedC g s s = 1
  | .pass, s => allOnes_diag s
  | .ctrl, s => allOnes_diag s

/-- One OI-operational step: an intervention, or a rank-one readout. -/
inductive Step
  | act (g : Gen)
  | read (k : Core)

/-- The coherent action of one step under a given completion. -/
def stateStep (Cof : Gen → Matrix Core Core ℂ) :
    Step → Matrix Core Core ℂ → Matrix Core Core ℂ
  | .act g, X => correlationExtension (genPerm g) (Cof g) X
  | .read k, X => ludersLift k X

/-- The coherent comb: a preparation pushed through a finite operational word. -/
def stateFold (Cof : Gen → Matrix Core Core ℂ) (steps : List Step)
    (X : Matrix Core Core ℂ) : Matrix Core Core ℂ :=
  steps.foldl (fun Y s => stateStep Cof s Y) X

/-- The classical action of one step on a weight vector. -/
def weightStep : Step → (Core → ℂ) → (Core → ℂ)
  | .act g, w => fun a => w ((genPerm g).symm a)
  | .read k, w => fun a => if a = k then w k else 0

/-- The classical comb of the bare OI core. -/
def weightFold (steps : List Step) (w : Core → ℂ) : Core → ℂ :=
  steps.foldl (fun v s => weightStep s v) w

/-- The Lüders branch of round twenty-two keeps a classical state classical. -/
theorem ludersLift_diagonal (k : Core) (w : Core → ℂ) :
    ludersLift k (Matrix.diagonal w)
      = Matrix.diagonal (fun a => if a = k then w k else 0) := by
  rw [ludersLift_apply, Matrix.diagonal_apply_eq]
  ext a b
  rw [Matrix.smul_apply, smul_eq_mul, single_entry]
  by_cases hab : a = b
  · subst hab
    rw [Matrix.diagonal_apply_eq]
    by_cases hak : a = k
    · rw [if_pos ⟨hak.symm, hak.symm⟩, if_pos hak, mul_one]
    · rw [if_neg (fun hh => hak hh.1.symm), if_neg hak, mul_zero]
  · rw [Matrix.diagonal_apply_ne _ hab,
      if_neg (fun hh => hab (hh.1.symm.trans hh.2)), mul_zero]

/-- **THE COMB STAYS CLASSICAL.** Under any completion with unit-diagonal correlations,
a classical preparation pushed through any operational word stays diagonal, and its
diagonal is exactly the bare classical comb — the correlations drop out entirely. -/
theorem stateFold_diagonal (Cof : Gen → Matrix Core Core ℂ)
    (hC : ∀ g s, Cof g s s = 1) (steps : List Step) (w : Core → ℂ) :
    stateFold Cof steps (Matrix.diagonal w)
      = Matrix.diagonal (weightFold steps w) := by
  induction steps generalizing w with
  | nil => rfl
  | cons s rest ih =>
      cases s with
      | act g =>
          show List.foldl (fun Y s => stateStep Cof s Y)
            (correlationExtension (genPerm g) (Cof g) (Matrix.diagonal w)) rest = _
          rw [correlationExtension_diagonal (genPerm g) (Cof g) (hC g) w]
          exact ih _
      | read k =>
          show List.foldl (fun Y s => stateStep Cof s Y)
            (ludersLift k (Matrix.diagonal w)) rest = _
          rw [ludersLift_diagonal k w]
          exact ih _

/-- **THE COMB IDENTITY — the central round-twenty-three theorem.** For every classical
preparation and every finite word of passive steps, `τ`-controls, and rank-one readouts,
all three completions return exactly the same branch statistics as the bare classical
core. The three theories below are therefore attached to one and the same OI process:
nothing in the C1–C4 operational data stream distinguishes them. -/
theorem threeCompletions_same_classical_comb (steps : List Step) (w : Core → ℂ) :
    stateFold nonFunctorialC steps (Matrix.diagonal w)
        = Matrix.diagonal (weightFold steps w)
      ∧ stateFold nonTensorC steps (Matrix.diagonal w)
        = Matrix.diagonal (weightFold steps w)
      ∧ stateFold restrictedC steps (Matrix.diagonal w)
        = Matrix.diagonal (weightFold steps w) :=
  ⟨stateFold_diagonal _ nonFunctorialC_diag steps w,
   stateFold_diagonal _ nonTensorC_diag steps w,
   stateFold_diagonal _ restrictedC_diag steps w⟩

/-! ### Section C — the monomial toolbox -/

/-- The monomial unitary of a phase assignment along a classical action:
`U|x⟩ = c(x)·|g x⟩`. -/
def monoU (c : Core → ℂ) (g : Equiv.Perm Core) : Matrix Core Core ℂ :=
  Matrix.of fun y x => if y = g x then c x else 0

theorem monoU_apply (c : Core → ℂ) (g : Equiv.Perm Core) (y x : Core) :
    monoU c g y x = if y = g x then c x else 0 := rfl

theorem perm_inv_apply (g : Equiv.Perm Core) (x : Core) : g⁻¹ x = g.symm x := rfl

/-- The round-thirteen monomial form `U = D·P_g`. -/
theorem monoU_eq_diagonal_permMatrix (c : Core → ℂ) (g : Equiv.Perm Core) :
    monoU c g = Matrix.diagonal (fun a => c (g.symm a)) * permMatrix g := by
  ext y x
  rw [monoU_apply, Matrix.diagonal_mul]
  show (if y = g x then c x else 0) = c (g.symm y) * (if g x = y then 1 else 0)
  by_cases h : y = g x
  · rw [if_pos h, if_pos h.symm, mul_one, h, Equiv.symm_apply_apply]
  · rw [if_neg h, if_neg (fun hh => h hh.symm), mul_zero]

/-- **Conjugation by a monomial unitary is the rank-one member of the round-seventeen
family.** So every monomial lift is CPTP and comb-blind for free. -/
theorem monoU_conj (c : Core → ℂ) (g : Equiv.Perm Core) (X : Matrix Core Core ℂ) :
    monoU c g * X * (monoU c g)ᴴ = correlationExtension g (rankOneC c) X := by
  rw [monoU_eq_diagonal_permMatrix]
  exact (rankOne_extension_monomial g c X).symm

/-- Monomial unitaries compose by composing actions and transporting phases. -/
theorem monoU_mul (c c' : Core → ℂ) (g g' : Equiv.Perm Core) :
    monoU c g * monoU c' g' = monoU (fun x => c (g' x) * c' x) (g * g') := by
  ext z x
  rw [Matrix.mul_apply, Finset.sum_eq_single (g' x)]
  · show (if z = g (g' x) then c (g' x) else 0) * (if g' x = g' x then c' x else 0)
      = if z = (g * g') x then c (g' x) * c' x else 0
    rw [if_pos rfl, Equiv.Perm.mul_apply]
    by_cases h : z = g (g' x)
    · rw [if_pos h, if_pos h]
    · rw [if_neg h, if_neg h, zero_mul]
  · intro y _ hy
    show monoU c g z y * (if y = g' x then c' x else 0) = 0
    rw [if_neg hy, mul_zero]
  · intro h
    exact absurd (Finset.mem_univ _) h

theorem monoU_one : monoU (fun _ => 1) (1 : Equiv.Perm Core) = 1 := by
  ext y x
  rw [Matrix.one_apply]
  rfl

theorem monoU_conjTranspose (c : Core → ℂ) (g : Equiv.Perm Core) :
    (monoU c g)ᴴ = monoU (fun x => conj' (c (g.symm x))) g⁻¹ := by
  ext y x
  rw [Matrix.conjTranspose_apply, monoU_apply, monoU_apply, perm_inv_apply]
  by_cases h : x = g y
  · rw [if_pos h, if_pos (show y = g.symm x from by rw [h, Equiv.symm_apply_apply]),
      show g.symm x = y from by rw [h, Equiv.symm_apply_apply]]
    rfl
  · rw [if_neg h, if_neg (show ¬y = g.symm x from fun hh => h (by
      rw [hh, Equiv.apply_symm_apply])), star_zero]

/-- A monomial matrix with unimodular phases is unitary. -/
theorem monoU_unitary (c : Core → ℂ) (hc : ∀ x, c x * conj' (c x) = 1)
    (g : Equiv.Perm Core) : monoU c g * (monoU c g)ᴴ = 1 := by
  rw [monoU_conjTranspose, monoU_mul, mul_inv_cancel,
    show (fun x => c (g⁻¹ x) * conj' (c (g.symm x))) = (fun _ : Core => (1 : ℂ)) from by
      funext x
      rw [perm_inv_apply]
      exact hc (g.symm x)]
  exact monoU_one

/-! ### Section D — countermodel 1: CPTP, classically exact, not functorial -/

/-- The coherent member of a completion at one intervention. -/
def member (Cof : Gen → Matrix Core Core ℂ) (g : Gen) :
    Matrix Core Core ℂ →ₗ[ℂ] Matrix Core Core ℂ :=
  correlationExtension (genPerm g) (Cof g)

/-- Two distinct core states, used to witness the failures. -/
def pt0 : Core := ((false, false), false)

def pt1 : Core := ((false, false), true)

theorem pt0_ne_pt1 : pt0 ≠ pt1 := by decide

theorem dephaseC_apply (s t : Core) : dephaseC s t = if s = t then 1 else 0 := rfl

/-- Completion 1 is a genuine channel at every intervention. -/
theorem nonFunctorial_cptp : ∀ g, IsCPTP (member nonFunctorialC g)
  | .pass => correlationExtension_cptp _ _ allOnes_posSemidef allOnes_diag
  | .ctrl => correlationExtension_cptp _ _ dephaseC_posSemidef dephaseC_diag

/-- Completion 1 reproduces the classical action exactly. -/
theorem nonFunctorial_classical :
    ∀ g, ClassicallyRealizes (member nonFunctorialC g) (genPerm g)
  | .pass => correlationExtension_classical _ _ allOnes_diag
  | .ctrl => correlationExtension_classical _ _ dephaseC_diag

/-- **COUNTERMODEL 1.** The control member dephases, so composing the `τ`-control with
itself is not the identity even though `τ² = 1` classically: coherent functoriality
fails while every channel axiom and every classical prediction holds.
⇒ C1–C4 OI does not imply H-functor. -/
theorem nonFunctorial_not_functorial :
    (member nonFunctorialC .ctrl).comp (member nonFunctorialC .ctrl) ≠ LinearMap.id := by
  intro hid
  rw [show member nonFunctorialC .ctrl = correlationExtension tauPerm dephaseC from rfl,
    correlationExtension_comp tauPerm tauPerm dephaseC dephaseC, tauPerm_sq] at hid
  have h := (correlationExtension_one_eq_id_iff _).mp hid pt0 pt1
  rw [Matrix.of_apply, dephaseC_apply, if_neg pt0_ne_pt1, zero_mul] at h
  exact zero_ne_one h

/-! ### Section E — countermodel 2: a strict unitary rep that is not tensor-local -/

/-- `U_σ = S ⊗ I_b`: the phase-free passive lift, shared by completions 2 and 3. -/
def Usigma : Matrix Core Core ℂ := monoU (fun _ => 1) sigmaPerm

/-- `U_τ = D (I_vh ⊗ X_b) D†`: the control lift carrying the nonfactorizable phase. -/
def Utau : Matrix Core Core ℂ := monoU nlPhase tauPerm

/-- `V_τ = I_vh ⊗ X_b`: the phase-free control lift of completion 3. -/
def Vtau : Matrix Core Core ℂ := monoU (fun _ => 1) tauPerm

theorem one_unimodular : ∀ _ : Core, (1 : ℂ) * conj' 1 = 1 :=
  fun _ => by rw [map_one, one_mul]

theorem Usigma_unitary : Usigma * Usigmaᴴ = 1 := monoU_unitary _ one_unimodular _

theorem Vtau_unitary : Vtau * Vtauᴴ = 1 := monoU_unitary _ one_unimodular _

theorem Utau_unitary : Utau * Utauᴴ = 1 := monoU_unitary _ nlPhase_unimodular _

theorem Usigma_involution : Usigma * Usigma = 1 := by
  rw [Usigma, monoU_mul, sigmaPerm_sq,
    show (fun x : Core => (1 : ℂ) * 1) = (fun _ : Core => (1 : ℂ)) from by
      funext _; rw [one_mul]]
  exact monoU_one

theorem Vtau_involution : Vtau * Vtau = 1 := by
  rw [Vtau, monoU_mul, tauPerm_sq,
    show (fun x : Core => (1 : ℂ) * 1) = (fun _ : Core => (1 : ℂ)) from by
      funext _; rw [one_mul]]
  exact monoU_one

/-- The phase pairs off across a `τ`-step: `α(τx)·α(x) = 1`. -/
theorem nlPhase_flip_prod (x : Core) : nlPhase (flipFn x) * nlPhase x = 1 := by
  obtain ⟨⟨v, h⟩, b⟩ := x
  cases v <;> cases h <;> cases b <;> simp [nlPhase, flipFn, Complex.I_mul_I]

/-- The phased control lift is a strict involution, not merely projective. -/
theorem Utau_involution : Utau * Utau = 1 := by
  rw [Utau, monoU_mul, tauPerm_sq,
    show (fun x : Core => nlPhase (tauPerm x) * nlPhase x) = (fun _ : Core => (1 : ℂ))
      from by
      funext x
      rw [tauPerm_apply]
      exact nlPhase_flip_prod x]
  exact monoU_one

/-- **The two lifts commute strictly** — the phase depends on `v ⊕ h`, which the swap
preserves. Completion 2 is therefore a genuine unitary representation of `ℤ₂ × ℤ₂`,
hence functorial: no projective cocycle is needed. -/
theorem Usigma_Utau_commute : Usigma * Utau = Utau * Usigma := by
  rw [Usigma, Utau, monoU_mul, monoU_mul, sigma_tau_commute,
    show (fun x : Core => (1 : ℂ) * nlPhase x)
      = (fun x : Core => nlPhase (sigmaPerm x) * 1) from by
      funext x
      rw [one_mul, mul_one, sigmaPerm_apply, nlPhase_swap_invariant]]

/-- A control lift is tensor-local on the `b` factor when it acts as `I_vh ⊗ M_b`. -/
def IsLocalOnB (U : Matrix Core Core ℂ) : Prop :=
  ∃ M : Matrix Bool Bool ℂ, ∀ y x : Core,
    U y x = (if y.1 = x.1 then 1 else 0) * M y.2 x.2

/-- A passive lift is tensor-local on the `vh` factor when it acts as `M_vh ⊗ I_b`. -/
def IsLocalOnVH (U : Matrix Core Core ℂ) : Prop :=
  ∃ M : Matrix VH VH ℂ, ∀ y x : Core,
    U y x = M y.1 x.1 * (if y.2 = x.2 then 1 else 0)

theorem Utau_flip (x : Core) : Utau (flipFn x) x = nlPhase x := by
  show (if flipFn x = tauPerm x then nlPhase x else 0) = nlPhase x
  rw [tauPerm_apply, if_pos rfl]

theorem local_flip_entry (M : Matrix Bool Bool ℂ) (x : Core) :
    (if (flipFn x).1 = x.1 then (1 : ℂ) else 0) * M (flipFn x).2 x.2 = M (!x.2) x.2 := by
  show (if x.1 = x.1 then (1 : ℂ) else 0) * M (!x.2) x.2 = M (!x.2) x.2
  rw [if_pos rfl, one_mul]

/-- **COUNTERMODEL 2.** The phased control lift is not `I_vh ⊗ M_b`: its `b`-flip
amplitude is `1` on the `v = h` sector and `i` on `v ≠ h`, and one and the same matrix
entry of a genuine local operator cannot be both.
⇒ C1–C4 OI + H-functor does not imply H-tensor. -/
theorem nonTensor_not_local : ¬IsLocalOnB Utau := by
  rintro ⟨M, hM⟩
  have e1 : nlPhase (((false, true) : VH), false) = M true false := by
    have h := hM (flipFn (((false, true) : VH), false)) (((false, true) : VH), false)
    rwa [Utau_flip, local_flip_entry] at h
  have e2 : nlPhase (((false, false) : VH), false) = M true false := by
    have h := hM (flipFn (((false, false) : VH), false)) (((false, false) : VH), false)
    rwa [Utau_flip, local_flip_entry] at h
  rw [show nlPhase (((false, true) : VH), false) = Complex.I from rfl] at e1
  rw [show nlPhase (((false, false) : VH), false) = 1 from rfl] at e2
  have hI : Complex.I = 1 := e1.trans e2.symm
  have hre := congrArg Complex.re hI
  simp at hre

/-! ### Section F — countermodel 3: functorial, tensor-local, proper control Lie rank -/

/-- The phase-free lift of each intervention. -/
def genLift : Gen → Matrix Core Core ℂ
  | .pass => Usigma
  | .ctrl => Vtau

/-- The reachable control group of completion 3: all finite words in the two lifts. -/
def restrictedU : List Gen → Matrix Core Core ℂ
  | [] => 1
  | g :: rest => genLift g * restrictedU rest

/-- Completion 3's passive lift is a genuine local operation on the `vh` factor. -/
theorem Usigma_local : IsLocalOnVH Usigma := by
  refine ⟨Matrix.of fun a a' => if a = (a'.2, a'.1) then 1 else 0, fun y x => ?_⟩
  show (if y = sigmaPerm x then (1 : ℂ) else 0)
    = (if y.1 = (x.1.2, x.1.1) then 1 else 0) * (if y.2 = x.2 then 1 else 0)
  rw [sigmaPerm_apply]
  by_cases h1 : y.1 = (x.1.2, x.1.1)
  · by_cases h2 : y.2 = x.2
    · rw [if_pos h1, if_pos h2, one_mul,
        if_pos (show y = swapFn x from Prod.ext h1 h2)]
    · rw [if_pos h1, if_neg h2, mul_zero,
        if_neg (show ¬y = swapFn x from fun hh => h2 ((congrArg Prod.snd hh : y.2 = (swapFn x).2)))]
  · rw [if_neg h1, zero_mul,
      if_neg (show ¬y = swapFn x from
        fun hh => h1 ((congrArg Prod.fst hh : y.1 = (swapFn x).1)))]

/-- Completion 3's control lift is a genuine local operation on the `b` factor. -/
theorem Vtau_local : IsLocalOnB Vtau := by
  refine ⟨Matrix.of fun b b' => if b = !b' then 1 else 0, fun y x => ?_⟩
  show (if y = tauPerm x then (1 : ℂ) else 0)
    = (if y.1 = x.1 then 1 else 0) * (if y.2 = !x.2 then 1 else 0)
  rw [tauPerm_apply]
  by_cases h1 : y.1 = x.1
  · by_cases h2 : y.2 = !x.2
    · rw [if_pos h1, if_pos h2, one_mul,
        if_pos (show y = flipFn x from Prod.ext h1 h2)]
    · rw [if_pos h1, if_neg h2, mul_zero,
        if_neg (show ¬y = flipFn x from fun hh => h2 ((congrArg Prod.snd hh : y.2 = (flipFn x).2)))]
  · rw [if_neg h1, zero_mul,
      if_neg (show ¬y = flipFn x from
        fun hh => h1 ((congrArg Prod.fst hh : y.1 = (flipFn x).1)))]

theorem Usigma_hermitian : Usigmaᴴ = Usigma := by
  rw [Usigma, monoU_conjTranspose]
  show monoU (fun x => conj' (1 : ℂ)) sigmaPerm⁻¹ = monoU (fun _ => 1) sigmaPerm
  rw [show (fun _ : Core => conj' (1 : ℂ)) = (fun _ : Core => (1 : ℂ)) from by
    funext _; rw [map_one]]
  congr 1

theorem Vtau_hermitian : Vtauᴴ = Vtau := by
  rw [Vtau, monoU_conjTranspose]
  show monoU (fun x => conj' (1 : ℂ)) tauPerm⁻¹ = monoU (fun _ => 1) tauPerm
  rw [show (fun _ : Core => conj' (1 : ℂ)) = (fun _ : Core => (1 : ℂ)) from by
    funext _; rw [map_one]]
  congr 1

theorem Usigma_Vtau_commute : Usigma * Vtau = Vtau * Usigma := by
  rw [Usigma, Vtau, monoU_mul, monoU_mul, sigma_tau_commute]

/-- The antisymmetric projector of the passive swap: `P₋ = (I - S⊗I_b)/2`. -/
noncomputable def passiveProj : Matrix Core Core ℂ :=
  (2 : ℂ)⁻¹ • ((1 : Matrix Core Core ℂ) - Usigma)

/-- The passive Hamiltonian `H = π·P₋ ⊗ I_b`. -/
noncomputable def coreH : Matrix Core Core ℂ := (Real.pi : ℂ) • passiveProj

/-- `P₋` is idempotent. -/
theorem passiveProj_idempotent : passiveProj * passiveProj = passiveProj := by
  have hexp : ((1 : Matrix Core Core ℂ) - Usigma) * (1 - Usigma)
      = (2 : ℂ) • (1 - Usigma) := by
    rw [two_smul, Matrix.sub_mul, Matrix.mul_sub, Matrix.mul_sub, Matrix.one_mul,
      Matrix.mul_one, Matrix.one_mul, Usigma_involution]
    abel
  rw [passiveProj, Matrix.smul_mul, Matrix.mul_smul, hexp, smul_smul, smul_smul]
  norm_num

/-- **THE INTERPOLATION CERTIFICATE.** `1 - 2P₋ = S ⊗ I_b`. Together with
`passiveProj_idempotent` and the standard projector-exponential identity
`exp(zP) = 1 + (e^z - 1)P`, this gives `exp(-iπP₋) = U_σ`: the passive swap really is
the time-`π` flow of `H`, so `H` is a legitimate Hamiltonian for this dynamics. -/
theorem one_sub_two_passiveProj :
    (1 : Matrix Core Core ℂ) - (2 : ℂ) • passiveProj = Usigma := by
  rw [passiveProj, smul_smul, show (2 : ℂ) * 2⁻¹ = 1 from by norm_num, one_smul]
  abel

/-- Any unitary commuting with the passive lift fixes the Hamiltonian by conjugation. -/
theorem conj_fixes_coreH {U : Matrix Core Core ℂ} (hU : U * Uᴴ = 1)
    (hcomm : U * Usigma = Usigma * U) : U * coreH * Uᴴ = coreH := by
  have hbase : U * ((1 : Matrix Core Core ℂ) - Usigma) * Uᴴ = 1 - Usigma := by
    rw [Matrix.mul_sub, Matrix.sub_mul, Matrix.mul_one, hU, hcomm, mul_assoc, hU,
      Matrix.mul_one]
  rw [coreH, passiveProj]
  simp only [Matrix.mul_smul, Matrix.smul_mul]
  rw [hbase]

theorem genLift_fixes_coreH : ∀ g : Gen, genLift g * coreH * (genLift g)ᴴ = coreH
  | .pass => conj_fixes_coreH Usigma_unitary rfl
  | .ctrl => conj_fixes_coreH Vtau_unitary Usigma_Vtau_commute.symm

/-- **Every reachable control fixes the Hamiltonian.** -/
theorem restrictedU_fixes_coreH (w : List Gen) :
    restrictedU w * coreH * (restrictedU w)ᴴ = coreH := by
  induction w with
  | nil =>
      show (1 : Matrix Core Core ℂ) * coreH * (1 : Matrix Core Core ℂ)ᴴ = coreH
      rw [Matrix.one_mul, Matrix.conjTranspose_one, Matrix.mul_one]
  | cons g rest ih =>
      show genLift g * restrictedU rest * coreH * (genLift g * restrictedU rest)ᴴ = coreH
      rw [Matrix.conjTranspose_mul,
        show genLift g * restrictedU rest * coreH
              * ((restrictedU rest)ᴴ * (genLift g)ᴴ)
            = genLift g * (restrictedU rest * coreH * (restrictedU rest)ᴴ)
              * (genLift g)ᴴ from by noncomm_ring,
        ih, genLift_fixes_coreH]

/-- **THE CONTROL LIE ALGEBRA COLLAPSES TO A LINE.** Every reachable control commutes
with `H`, so `𝔏(H,U)` is the single real line `ℝ(-iH)`. -/
theorem restricted_controlLie_line (y : Matrix Core Core ℂ) :
    y ∈ controlLie coreH restrictedU ↔ ∃ r : ℝ, y = r • ((-Complex.I) • coreH) :=
  controlLie_trivial coreH restrictedU restrictedU_fixes_coreH y

/-- A traceless skew-Hermitian direction, exhibited outside the control Lie algebra. -/
noncomputable def outsideGen : Matrix Core Core ℂ :=
  (-Complex.I) • (Matrix.single pt0 pt0 1 - Matrix.single pt1 pt1 1)

theorem single_diag_hermitian (k : Core) :
    (Matrix.single k k (1 : ℂ))ᴴ = Matrix.single k k 1 := by
  ext a b
  rw [Matrix.conjTranspose_apply, single_entry, single_entry]
  by_cases h : k = a ∧ k = b
  · rw [if_pos ⟨h.2, h.1⟩, if_pos h, star_one]
  · rw [if_neg (fun hh => h ⟨hh.2, hh.1⟩), if_neg h, star_zero]

theorem trace_single_diag (k : Core) : (Matrix.single k k (1 : ℂ)).trace = 1 := by
  rw [Matrix.trace, Finset.sum_eq_single k]
  · rw [Matrix.diag_apply, Matrix.single_apply_same]
  · intro a _ ha
    rw [Matrix.diag_apply, single_entry, if_neg (fun hh => ha hh.1.symm)]
  · intro h
    exact absurd (Finset.mem_univ _) h

theorem outsideGen_skewHermitian : outsideGenᴴ = -outsideGen := by
  rw [outsideGen, Matrix.conjTranspose_smul, Matrix.conjTranspose_sub,
    single_diag_hermitian, single_diag_hermitian,
    show star (-Complex.I) = Complex.I from by
      rw [star_neg, Complex.star_def, Complex.conj_I, neg_neg],
    ← neg_smul, neg_neg]

theorem outsideGen_traceless : outsideGen.trace = 0 := by
  rw [outsideGen, Matrix.trace_smul, Matrix.trace_sub, trace_single_diag,
    trace_single_diag, sub_self, smul_zero]

/-- The two off-diagonal probe points: `qy = σ(qx)` and `qy ≠ qx`. -/
def qx : Core := ((false, true), false)

def qy : Core := ((true, false), false)

theorem qy_eq_swap : qy = swapFn qx := rfl

theorem qy_ne_qx : qy ≠ qx := by decide

theorem pt0_ne_qy : pt0 ≠ qy := by decide

theorem pt1_ne_qy : pt1 ≠ qy := by decide

theorem outsideGen_apply_qy : outsideGen qy qx = 0 := by
  rw [outsideGen, Matrix.smul_apply, Matrix.sub_apply, single_entry, single_entry,
    if_neg (fun hh => pt0_ne_qy hh.1), if_neg (fun hh => pt1_ne_qy hh.1), sub_zero,
    smul_zero]

theorem Usigma_apply_qy : Usigma qy qx = 1 := by
  show (if qy = sigmaPerm qx then (1 : ℂ) else 0) = 1
  rw [sigmaPerm_apply, if_pos qy_eq_swap]

theorem coreH_apply_qy : coreH qy qx = -((Real.pi : ℂ) * 2⁻¹) := by
  rw [coreH, Matrix.smul_apply, passiveProj, Matrix.smul_apply, Matrix.sub_apply,
    Matrix.one_apply_ne qy_ne_qx, Usigma_apply_qy, smul_eq_mul, smul_eq_mul]
  ring

theorem outsideGen_apply_pt0 : outsideGen pt0 pt0 = -Complex.I := by
  rw [outsideGen, Matrix.smul_apply, Matrix.sub_apply, single_entry, single_entry,
    if_pos ⟨rfl, rfl⟩, if_neg (fun hh => pt0_ne_pt1 hh.1.symm), sub_zero, smul_eq_mul,
    mul_one]

/-- **COUNTERMODEL 3.** A traceless skew-Hermitian direction that the reachable
controls cannot generate: the control Lie algebra is a proper subalgebra of `su(D)`.
⇒ C1–C4 OI + H-functor + H-tensor does not imply `𝔏₀ = su(D)`. -/
theorem outsideGen_not_mem : outsideGen ∉ controlLie coreH restrictedU := by
  intro hmem
  obtain ⟨r, hr⟩ := (restricted_controlLie_line _).mp hmem
  have hentry := congrFun (congrFun hr qy) qx
  rw [outsideGen_apply_qy, Matrix.smul_apply, Matrix.smul_apply, coreH_apply_qy,
    smul_eq_mul, Complex.real_smul] at hentry
  have hpi : (Real.pi : ℂ) ≠ 0 := by
    exact_mod_cast Real.pi_ne_zero
  have hr0 : (r : ℂ) = 0 := by
    rcases mul_eq_zero.mp hentry.symm with h | h
    · exact h
    · exact absurd h (by
        intro hz
        rcases mul_eq_zero.mp hz with h' | h'
        · exact Complex.I_ne_zero (neg_eq_zero.mp h')
        · rcases mul_eq_zero.mp (neg_eq_zero.mp h') with h'' | h''
          · exact hpi h''
          · exact absurd h'' (by norm_num))
  have hzero := congrFun (congrFun hr pt0) pt0
  rw [outsideGen_apply_pt0, Matrix.smul_apply, Complex.real_smul, hr0, zero_mul] at hzero
  exact Complex.I_ne_zero (neg_eq_zero.mp hzero)

/-! ### Section G — the census -/

/-- **THE INDEPENDENCE CENSUS.** One and the same controlled-minimal, memory-bearing
C1–C4 OI core (Section A), on which every completion below reproduces the identical
classical comb (`threeCompletions_same_classical_comb`), carries:

  1. a CPTP, classically exact, NON-FUNCTORIAL coherent completion;
  2. a strict unitary — hence functorial — completion that is NOT tensor-local;
  3. a functorial AND tensor-local completion whose reachable control Lie algebra is a
     proper subalgebra of `su(D)`.

So C1–C4 do not select the unrestricted operational completion. Case 3 is ordinary
quantum kinematics with a restricted reachable-control subgroup, not a non-quantum
theory: `S ⇔ D ⇔ Q_fb` is untouched, and what fails is the UNRESTRICTED finite
operational package. -/
theorem oi_core_underdetermines_completion :
    ((∀ g, IsCPTP (member nonFunctorialC g))
        ∧ (∀ g, ClassicallyRealizes (member nonFunctorialC g) (genPerm g))
        ∧ (member nonFunctorialC .ctrl).comp (member nonFunctorialC .ctrl)
            ≠ LinearMap.id)
      ∧ (Usigma * Usigmaᴴ = 1 ∧ Utau * Utauᴴ = 1
        ∧ Usigma * Usigma = 1 ∧ Utau * Utau = 1
        ∧ Usigma * Utau = Utau * Usigma
        ∧ ¬IsLocalOnB Utau)
      ∧ (IsLocalOnVH Usigma ∧ IsLocalOnB Vtau
        ∧ (∀ w, restrictedU w * coreH * (restrictedU w)ᴴ = coreH)
        ∧ outsideGenᴴ = -outsideGen ∧ outsideGen.trace = 0
        ∧ outsideGen ∉ controlLie coreH restrictedU) :=
  ⟨⟨nonFunctorial_cptp, nonFunctorial_classical, nonFunctorial_not_functorial⟩,
   ⟨Usigma_unitary, Utau_unitary, Usigma_involution, Utau_involution,
    Usigma_Utau_commute, nonTensor_not_local⟩,
   ⟨Usigma_local, Vtau_local, restrictedU_fixes_coreH, outsideGen_skewHermitian,
    outsideGen_traceless, outsideGen_not_mem⟩⟩

#print axioms core_hidden_drives_visible
#print axioms core_visible_period_two
#print axioms core_observer_minimal
#print axioms sigma_tau_commute
#print axioms ludersLift_diagonal
#print axioms stateFold_diagonal
#print axioms threeCompletions_same_classical_comb
#print axioms monoU_conj
#print axioms monoU_mul
#print axioms monoU_unitary
#print axioms nonFunctorial_cptp
#print axioms nonFunctorial_classical
#print axioms nonFunctorial_not_functorial
#print axioms Utau_involution
#print axioms Usigma_Utau_commute
#print axioms nonTensor_not_local
#print axioms Usigma_local
#print axioms Vtau_local
#print axioms passiveProj_idempotent
#print axioms one_sub_two_passiveProj
#print axioms restrictedU_fixes_coreH
#print axioms restricted_controlLie_line
#print axioms outsideGen_skewHermitian
#print axioms outsideGen_traceless
#print axioms outsideGen_not_mem
#print axioms oi_core_underdetermines_completion

end IndependenceCensus
end OIBridge
