/-
  OIBridge/LieRankSource.lean — the primitive-source audit, fourth target: the Lie-rank clause
  of reversible richness, audited for redundancy and derived from elementary transitions.

  ROUND FIFTY-NINE. After round fifty-eight the carrier-general quantum-complete package is
  reversible implementation locality, Lie-rank richness and embedded observation, and the
  Lie-rank clause is the one substantive selector with no audited source. The round follows
  the audit's discipline: redundancy first, then the source.

  A. THE REDUNDANCY TEST FAILS. Implementation classes closed under the operations every
  finite operational theory performs — identity, product, scalar, ancilla projector, ancilla
  block — GENERATE a finite operational theory on every carrier (`Architecture`,
  `genTheory`): availability is realization by the class with the aggregate trace preserved.
  The generated theories form a regrouping-invariant family, relabelling-invariant when the
  class is (`genFamily`), so the generated theory carries embedded observation
  (`genTheory_embeddedObservation`); it is generated by its class definitionally, so with a
  context-stable, label-invariant, dagger-stable class it carries reversible implementation
  locality (`genTheory_reversibleImplementationLocality`). The DIAGONAL class — operators
  with no off-diagonal entry — is such an architecture (`diagClass`, `diagClass_arch`,
  and the three stability properties). Its generated theory on the qubit has no composite
  unitary control: every available conjugation is realized by diagonal operators, hence
  preserves diagonal matrices, and the round-42 rotation `rot` does not
  (`diagGen_not_control`). Since the inverse clause holds there (dagger stability) and
  inverse accessibility with Lie-rank richness gives control (`control_of_lieRank_inverse`),
  Lie-rank richness fails: `lieRank_not_redundant`. Reversible implementation locality and
  embedded observation do not supply the Lie-rank clause.

  B. THE PRIMITIVE, IN ELEMENTARY IMPLEMENTATIONS. At every level and for every two
  distinguishable states `a ≠ b`: the real transition generator `X_ab = E_ab + E_ba` is
  continuously drivable (its flow is available for every time); the exchange of `a` and `b`
  is available (the transposition, a permutation matrix); and a quarter phase on `a` is
  available (`ElementaryTransitionRichness`, with `transition`, `permMatrix`, `phaseGate`).
  Nothing in it mentions a Lie algebra, a drift/control certificate, or reachability.

  C. THE DERIVATION, FINITE LIE ALGEBRA. Fix a base state `i₀` and one partner `j₁`. Take the
  drift `X_{i₀j₁}` and as controls the words `P_σ · S_{i₀}^b` (a permutation matrix times an
  optional quarter phase), all available as words in exchanges and the phase. Conjugating
  the drift by a permutation carries `X_{i₀j₁}` to `X_{σi₀,σj₁}`, and by the quarter phase to
  `Y_{i₀j₁} = i(E_{i₀j₁} − E_{j₁i₀})`; since a permutation carries any ordered pair of
  distinct states to any other, the control Lie algebra contains `−iX_pq` and `−iY_pq` for
  every `p ≠ q` (`perm_conj_transition`, `phase_conj_transition`, `exists_perm_pair`).
  The bracket `[−iX_pq, −iY_pq] = 2i(E_pp − E_qq)` supplies the diagonal directions
  (`bracket_XY`). Every traceless skew-Hermitian matrix is a real combination of these
  (`pair_decomp`, `specialSkew_mem`), so `su(D)` lies in the control Lie algebra
  (`hControl_star`) and Lie-rank richness follows (`lieRank_of_elementary`). The
  derivation consumes one driven transition, one quarter phase and the exchanges; the
  primitive grants more, and its minimal form is not settled here.

  NECESSITY. Full composite unitary control supplies every elementary transition
  (`elementary_of_control`), so exact finite operational QM has the primitive.

  THE COMPRESSED SET. `OIPlusElem` is reversible implementation locality, elementary
  transition richness and embedded observation; `carrier_general_oiPlusElem` proves it
  equivalent to exact finite endomorphic operational QM on every nonempty finite carrier.
  Every principle in it is now stated at the level of implementations or of the observer
  architecture; none is a Lie-algebraic or reachability condition.

  WHAT IS NOT CLAIMED. The minimal elementary repertoire (whether the phase is dispensable
  on three or more states, whether one driven pair and one exchange orbit suffice) is not
  settled. The converse from Lie-rank richness to elementary transition richness is not
  claimed. Nothing here bears on the open redundancy of the inverse clause.
-/

import OIBridge.MicroscopicReversibility

namespace OIBridge
namespace LieRankSource

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource InterventionLocality
open MicroReversibility

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

attribute [local instance 100] LieRing.ofAssociativeRing

/-! ### Section A — realization is closed under the operations a theory performs -/

section Closure

variable {𝓘 : ImplementationClass} {S : Type} [Fintype S] [DecidableEq S]

theorem realized_conj {K : Matrix S S ℂ} (h : 𝓘 S K) : Realized 𝓘 S (conjChannel K) :=
  ⟨Unit, inferInstance, fun _ => K, by rw [Fintype.sum_unique], fun _ => h⟩

theorem realized_zero : Realized 𝓘 S 0 :=
  ⟨Empty, inferInstance, fun x => x.elim, by simp, fun x => x.elim⟩

theorem realized_add {Φ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (hΦ : Realized 𝓘 S Φ)
    (hΨ : Realized 𝓘 S Ψ) : Realized 𝓘 S (Φ + Ψ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := hΦ
  obtain ⟨κ, _, L, rfl, hL⟩ := hΨ
  refine ⟨ι ⊕ κ, inferInstance, Sum.elim K L, ?_, ?_⟩
  · simp [Fintype.sum_sum_type]
  · rintro (i | j)
    · exact hK i
    · exact hL j

theorem realized_sum {ι' : Type*} (s : Finset ι') (Φ : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (h : ∀ i ∈ s, Realized 𝓘 S (Φ i)) : Realized 𝓘 S (∑ i ∈ s, Φ i) :=
  Finset.sum_induction _ (Realized 𝓘 S) (fun _ _ => realized_add) realized_zero h

theorem sum_comp' {ι' : Type*} (s : Finset ι') (f : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (g : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    (∑ i ∈ s, f i).comp g = ∑ i ∈ s, (f i).comp g := by
  refine LinearMap.ext fun X => ?_
  simp only [LinearMap.comp_apply, LinearMap.sum_apply]

theorem comp_sum' {ι' : Type*} (s : Finset ι') (f : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ)
    (g : ι' → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) :
    f.comp (∑ i ∈ s, g i) = ∑ i ∈ s, f.comp (g i) := by
  refine LinearMap.ext fun X => ?_
  simp only [LinearMap.comp_apply, LinearMap.sum_apply, map_sum]

theorem realized_comp (hmul : ∀ K L : Matrix S S ℂ, 𝓘 S K → 𝓘 S L → 𝓘 S (K * L))
    {Φ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (hΦ : Realized 𝓘 S Φ) (hΨ : Realized 𝓘 S Ψ) :
    Realized 𝓘 S (Φ.comp Ψ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := hΦ
  obtain ⟨κ, _, L, rfl, hL⟩ := hΨ
  refine ⟨ι × κ, inferInstance, fun p => K p.1 * L p.2, ?_,
    fun p => hmul _ _ (hK p.1) (hL p.2)⟩
  rw [sum_comp', Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [comp_sum']
  exact Finset.sum_congr rfl fun j _ => OIHierarchyGeneral.conjChannel_mul_general (K i) (L j)

theorem realized_smul_nonneg (hsmul : ∀ (a : ℂ) (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S (a • K))
    {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (c : ℝ) (hc : 0 ≤ c) (h : Realized 𝓘 S Φ) :
    Realized 𝓘 S ((c : ℂ) • Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  refine ⟨ι, inferInstance, fun i => ((Real.sqrt c : ℝ) : ℂ) • K i, ?_,
    fun i => hsmul _ _ (hK i)⟩
  rw [Finset.smul_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  show (c : ℂ) • conjChannel (K i) = conjChannel (((Real.sqrt c : ℝ) : ℂ) • K i)
  rw [MicroReversibility.conjChannel_smul, Complex.star_def, Complex.conj_ofReal,
    ← Complex.ofReal_mul, Real.mul_self_sqrt hc]

theorem realized_transport (hl : LabelInvariant 𝓘) {S' : Type} [Fintype S'] [DecidableEq S']
    (e : S ≃ S') {Φ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ} (h : Realized 𝓘 S Φ) :
    Realized 𝓘 S' (transport e Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  refine ⟨ι, inferInstance, fun i => Matrix.reindex e e (K i), ?_, fun i => hl _ _ e _ (hK i)⟩
  rw [transport_sum]
  exact Finset.sum_congr rfl fun i _ => transport_conjChannel e (K i)

theorem realized_id (hone : 𝓘 S 1) : Realized 𝓘 S LinearMap.id := by
  rw [← conjChannel_one]
  exact realized_conj hone

theorem realized_localLuders {m : ℕ}
    (hproj : ∀ k : Fin m, 𝓘 (S × Fin m) (Matrix.diagonal fun r => if r.2 = k then 1 else 0))
    (k : Fin m) : Realized 𝓘 (S × Fin m) (localLuders (A := S) k) := by
  rw [localLuders_eq_conjChannel]
  exact realized_conj (hproj k)

theorem realized_discard {m : ℕ}
    (hblock : ∀ (K : Matrix (S × Fin m) (S × Fin m) ℂ) (f e : Fin m),
      𝓘 (S × Fin m) K → 𝓘 S (ancBlock K f e))
    (hsmul : ∀ (a : ℂ) (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S (a • K))
    {Φ : Matrix (S × Fin m) (S × Fin m) ℂ →ₗ[ℂ] Matrix (S × Fin m) (S × Fin m) ℂ}
    (h : Realized 𝓘 (S × Fin m) Φ) :
    Realized 𝓘 S (discardWith (A := S) m (uniformAttach m) Φ) := by
  obtain ⟨ι, _, K, rfl, hK⟩ := h
  rw [discardWith_sum]
  refine realized_sum _ _ fun i _ => ?_
  rw [discardWith_uniform_conjChannel]
  have hcast : ((m : ℂ))⁻¹ = (((m : ℝ)⁻¹ : ℝ) : ℂ) := by push_cast; rfl
  rw [hcast]
  refine realized_smul_nonneg hsmul _ (inv_nonneg.mpr (Nat.cast_nonneg m)) ?_
  exact realized_sum _ _ fun c _ => realized_conj (hblock _ _ _ (hK i))

end Closure

/-! ### Section B — architectures and the theories they generate -/

section Generated

/-- **AN ARCHITECTURE**: an implementation class closed under the operations every finite
operational theory performs on implementations. -/
structure Architecture (𝓘 : ImplementationClass) : Prop where
  one : ∀ (S : Type) [Fintype S] [DecidableEq S], 𝓘 S 1
  mul : ∀ (S : Type) [Fintype S] [DecidableEq S] (K L : Matrix S S ℂ),
    𝓘 S K → 𝓘 S L → 𝓘 S (K * L)
  smul : ∀ (S : Type) [Fintype S] [DecidableEq S] (a : ℂ) (K : Matrix S S ℂ),
    𝓘 S K → 𝓘 S (a • K)
  proj : ∀ (S : Type) [Fintype S] [DecidableEq S] (m : ℕ) (k : Fin m),
    𝓘 (S × Fin m) (Matrix.diagonal fun r => if r.2 = k then 1 else 0)
  block : ∀ (S : Type) [Fintype S] [DecidableEq S] (m : ℕ)
    (K : Matrix (S × Fin m) (S × Fin m) ℂ) (f e : Fin m),
    𝓘 (S × Fin m) K → 𝓘 S (ancBlock K f e)

/-- The generated instruments: realized branches, trace preserved in aggregate. -/
def IsGenInstrument (𝓘 : ImplementationClass) (S : Type) [Fintype S] [DecidableEq S]
    {O : Type} [Fintype O] [DecidableEq O] (F : O → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) : Prop :=
  (∀ a, Realized 𝓘 S (F a)) ∧ ∀ X, ∑ a, ((F a) X).trace = X.trace

variable (𝓘 : ImplementationClass) (arch : Architecture 𝓘)

/-- **THE THEORY GENERATED BY AN ARCHITECTURE** on a carrier. -/
noncomputable def genTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S where
  avail := fun _ _ _ F => IsGenInstrument 𝓘 S F
  availExt := fun _ _ _ _ F => IsGenInstrument 𝓘 _ F
  avail_id := ⟨fun _ => realized_id (arch.one S), fun X => by
    rw [Fintype.sum_unique, LinearMap.id_apply]⟩
  avail_coarse := by
    rintro O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => realized_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_coarse := by
    rintro n O O' _ _ _ _ F f ⟨h2, htr⟩
    refine ⟨fun a' => realized_sum _ _ fun j _ => h2 j, fun X => ?_⟩
    rw [Finset.sum_congr rfl fun a' _ => by rw [LinearMap.sum_apply, Matrix.trace_sum],
      Finset.sum_fiberwise_of_maps_to (fun x _ => Finset.mem_univ (f x))
        (fun j => ((F j) X).trace)]
    exact htr X
  availExt_bind := by
    rintro n O O' _ _ _ _ F G ⟨hF2, hFtr⟩ hG
    refine ⟨fun c => realized_comp (arch.mul _) ((hG c.1).1 c.2) (hF2 c.1), fun X => ?_⟩
    rw [Fintype.sum_prod_type]
    show ∑ a, ∑ b, ((G a b) ((F a) X)).trace = X.trace
    rw [Finset.sum_congr rfl fun a _ => (hG a).2 ((F a) X)]
    exact hFtr X
  prepAvail := fun n P => 0 < n ∧ ∃ Φ, IsGenInstrument 𝓘 _ (fun _ : Unit => Φ)
    ∧ P = Φ.comp (uniformAttach n)
  prepAvail_uniform := fun n =>
    ⟨n.succ_pos, LinearMap.id,
      ⟨fun _ => realized_id (arch.one _), fun X => by
        rw [Fintype.sum_unique, LinearMap.id_apply]⟩, by rw [LinearMap.id_comp]⟩
  prepAvail_post := by
    rintro n P Φ ⟨hn, Ψ, ⟨hΨ2, hΨtr⟩, rfl⟩ ⟨hΦ2, hΦtr⟩
    refine ⟨hn, Φ.comp Ψ, ⟨fun _ => realized_comp (arch.mul _) (hΦ2 ()) (hΨ2 ()), fun X => ?_⟩,
      by rw [LinearMap.comp_assoc]⟩
    rw [Fintype.sum_unique]
    have h1 := hΦtr (Ψ X)
    rw [Fintype.sum_unique] at h1
    have h2 := hΨtr X
    rw [Fintype.sum_unique] at h2
    exact h1.trans h2
  readout := fun _ k => localLuders k
  readout_avail := fun _ => ⟨fun k => realized_localLuders (arch.proj _ _) k, localLuders_trace_sum⟩
  readout_local := fun _ k => localLuders_mapSpectatorIndependent k
  prepAvail_discard := by
    rintro n P O _ _ F ⟨hn, Φ, ⟨hΦ2, hΦtr⟩, rfl⟩ ⟨hF2, hFtr⟩
    refine ⟨fun a => ?_, fun X => ?_⟩
    · show Realized 𝓘 S (discardWith n (Φ.comp (uniformAttach n)) (F a))
      have h : discardWith n (Φ.comp (uniformAttach n)) (F a)
          = discardWith n (uniformAttach n) ((F a).comp Φ) := by
        simp only [discardWith, LinearMap.comp_assoc]
      rw [h]
      exact realized_discard (arch.block _ _) (arch.smul _)
        (realized_comp (arch.mul _) (hF2 a) (hΦ2 ()))
    · show ∑ a, ((discardWith n (Φ.comp (uniformAttach n)) (F a)) X).trace = X.trace
      rw [Finset.sum_congr rfl fun a _ => discardWith_trace n _ (F a) X, hFtr]
      have h := hΦtr (uniformAttach n X)
      rw [Fintype.sum_unique] at h
      exact h.trans (uniformAttach_trace n hn.ne' X)

/-- The generated family. -/
noncomputable def genFamily : TheoryFamily := fun S _ _ => genTheory 𝓘 arch S

theorem genFamily_regrouping : RegroupingInvariant (genFamily 𝓘 arch) := by
  intro S _ _ m _ O _ _ F
  exact Iff.rfl

theorem genFamily_relabelling (hl : LabelInvariant 𝓘) : RelabellingInvariant (genFamily 𝓘 arch) := by
  intro S S' _ _ _ _ e O _ _ F ⟨h2, htr⟩
  refine ⟨fun a => realized_transport hl e (h2 a), fun X => ?_⟩
  simp only [trace_transport]
  rw [htr, trace_reindex]

variable {A : Type} [Fintype A] [DecidableEq A]

theorem genTheory_ambient : IsAmbientMember (genTheory 𝓘 arch A) (genFamily 𝓘 arch) :=
  ⟨fun _ _ _ _ => Iff.rfl, fun _ _ _ _ _ _ => Iff.rfl⟩

/-- **GENERATED THEORIES CARRY EMBEDDED OBSERVATION** when the class is label-invariant. -/
theorem genTheory_embeddedObservation (hl : LabelInvariant 𝓘) :
    EmbeddedObservation (genTheory 𝓘 arch A) :=
  ⟨genFamily 𝓘 arch, genFamily_regrouping 𝓘 arch, genFamily_relabelling 𝓘 arch hl,
    genTheory_ambient 𝓘 arch⟩

theorem genTheory_generated : ImplementationGenerated (genTheory 𝓘 arch A) 𝓘 :=
  fun _ _ _ _ _ _ => Iff.rfl

/-- **GENERATED THEORIES ARE REVERSIBLY IMPLEMENTATION-LOCAL** when the class is
context-stable, label-invariant and dagger-stable. -/
theorem genTheory_reversibleImplementationLocality (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘)
    (hd : DaggerStable 𝓘) : ReversibleImplementationLocality (genTheory 𝓘 arch A) :=
  ⟨𝓘, genTheory_generated 𝓘 arch, hc, hl, hd⟩

end Generated

/-! ### Section C — the diagonal architecture and the countermodel -/

section Diagonal

/-- **THE DIAGONAL CLASS**: operators with no off-diagonal entry. -/
def diagClass : ImplementationClass := fun S _ _ K => ∀ p q, p ≠ q → K p q = 0

theorem diagClass_arch : Architecture diagClass where
  one := fun S _ _ p q h => Matrix.one_apply_ne h
  mul := by
    intro S _ _ K L hK hL p q h
    rw [Matrix.mul_apply]
    refine Finset.sum_eq_zero fun k _ => ?_
    by_cases hk : p = k
    · rw [hL k q (hk ▸ h), mul_zero]
    · rw [hK p k hk, zero_mul]
  smul := fun S _ _ a K hK p q h => by rw [Matrix.smul_apply, hK p q h, smul_zero]
  proj := fun S _ _ m k p q h => Matrix.diagonal_apply_ne _ h
  block := fun S _ _ m K f e hK s t h =>
    hK (s, f) (t, e) fun h' => h (congrArg Prod.fst h')

theorem diagClass_contextStable : ContextStable diagClass := by
  intro R S _ _ _ _ K hK p q h
  rw [tensorOf_apply]
  by_cases h1 : p.1 = q.1
  · have h2 : p.2 ≠ q.2 := fun h2 => h (Prod.ext h1 h2)
    rw [hK _ _ h2, mul_zero]
  · rw [Matrix.one_apply_ne h1, zero_mul]

theorem diagClass_labelInvariant : LabelInvariant diagClass := by
  intro S S' _ _ _ _ e K hK p q h
  rw [Matrix.reindex_apply, Matrix.submatrix_apply]
  exact hK _ _ (e.symm.injective.ne h)

theorem diagClass_daggerStable : DaggerStable diagClass := by
  intro S _ _ K hK p q h
  rw [Matrix.conjTranspose_apply, hK q p (Ne.symm h), star_zero]

/-- A conjugation by a diagonal operator preserves diagonal matrices. -/
theorem preservesDiag_conj_of_diag {S : Type} [Fintype S] [DecidableEq S] {K : Matrix S S ℂ}
    (hK : ∀ p q, p ≠ q → K p q = 0) : PreservesDiag (conjChannel K) := by
  set d : S → ℂ := fun p => K p p with hd
  have hKd : K = Matrix.diagonal d := by
    ext p q
    by_cases h : p = q
    · subst h
      rw [Matrix.diagonal_apply_eq]
    · rw [Matrix.diagonal_apply_ne _ h]
      exact hK p q h
  intro w
  refine ⟨fun p => d p * w p * star (d p), ?_⟩
  rw [conjChannel_apply, hKd, Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
    Matrix.diagonal_mul_diagonal]
  rfl

/-- **THE DIAGONAL THEORY HAS NO COMPOSITE UNITARY CONTROL**: the round-42 rotation is not
available at level one on the qubit. -/
theorem diagGen_not_control : ¬ HasCompositeUnitaryControl (genTheory diagClass diagClass_arch (Fin 2)) := by
  intro h
  obtain ⟨ι, _, K, hK, hadm⟩ := (h 1 rot rot_isometry).1 ()
  have hK' : conjChannel rot = ∑ i, conjChannel (K i) := hK
  apply rot_not_preservesDiag
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_diag (hadm i)

/-- **THE REDUNDANCY TEST FAILS**: reversible implementation locality and embedded observation
do not supply Lie-rank richness. -/
theorem lieRank_not_redundant :
    ∃ T : FiniteOperationalTheory (Fin 2), ReversibleImplementationLocality T
      ∧ EmbeddedObservation T ∧ ¬ LieRankRichness T := by
  have hrev := genTheory_reversibleImplementationLocality diagClass diagClass_arch (A := Fin 2)
    diagClass_contextStable diagClass_labelInvariant diagClass_daggerStable
  refine ⟨genTheory diagClass diagClass_arch (Fin 2), hrev,
    genTheory_embeddedObservation diagClass diagClass_arch diagClass_labelInvariant, fun hlie => ?_⟩
  exact diagGen_not_control (control_of_lieRank_inverse _
    (inverseAccessibility_of_reversibleImplementationLocality hrev) hlie)

end Diagonal

/-! ### Section D — elementary transitions -/

section Elementary

variable {S : Type} [Fintype S] [DecidableEq S]

omit [Fintype S] in
theorem single_apply' (i j : S) (c : ℂ) (a b : S) :
    Matrix.single i j c a b = if i = a ∧ j = b then c else 0 := rfl

omit [Fintype S] in
theorem single_conjTranspose' (a b : S) :
    (Matrix.single a b (1 : ℂ))ᴴ = Matrix.single b a 1 := by
  ext p q
  rw [Matrix.conjTranspose_apply, single_apply', single_apply']
  by_cases h1 : a = q <;> by_cases h2 : b = p <;> simp [h1, h2]

omit [Fintype S] in
theorem real_smul_matrix (r : ℝ) (M : Matrix S S ℂ) : r • M = (r : ℂ) • M := by
  ext p q
  simp [Matrix.smul_apply, Complex.real_smul]

omit [Fintype S] in
theorem single_smul_one (a b : S) (c : ℂ) : c • Matrix.single a b (1 : ℂ) = Matrix.single a b c := by
  ext p q
  rw [Matrix.smul_apply, single_apply', single_apply']
  split_ifs <;> simp

/-- The real transition generator between two states, `E_ab + E_ba`. -/
def transition (a b : S) : Matrix S S ℂ := Matrix.single a b 1 + Matrix.single b a 1

/-- The imaginary transition generator, `i(E_ab − E_ba)`. -/
def transitionY (a b : S) : Matrix S S ℂ :=
  Complex.I • (Matrix.single a b 1 - Matrix.single b a 1)

/-- The population difference, `E_aa − E_bb`. -/
def popDiff (a b : S) : Matrix S S ℂ := Matrix.single a a 1 - Matrix.single b b 1

/-- The quarter phase on one state. -/
def phaseGate (a : S) : Matrix S S ℂ := Matrix.diagonal fun p => if a = p then Complex.I else 1

theorem transition_hermitian (a b : S) : (transition a b)ᴴ = transition a b := by
  rw [transition, Matrix.conjTranspose_add, single_conjTranspose', single_conjTranspose', add_comm]

theorem phaseGate_conjTranspose (a : S) :
    (phaseGate a)ᴴ = Matrix.diagonal fun p => if a = p then -Complex.I else 1 := by
  rw [phaseGate, Matrix.diagonal_conjTranspose]
  congr 1
  ext p
  simp only [Pi.star_apply]
  split_ifs <;> simp [Complex.star_def, Complex.conj_I]

theorem phaseGate_unitary (a : S) : (phaseGate a)ᴴ * phaseGate a = 1 := by
  rw [phaseGate_conjTranspose, phaseGate, Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
  congr 1
  ext p
  split_ifs <;> simp [Complex.I_mul_I]

theorem permMatrix_one' : permMatrix (1 : Equiv.Perm S) = 1 := by
  ext i j
  simp [permMatrix, Matrix.one_apply, eq_comm]

theorem permMatrix_mul' (g h : Equiv.Perm S) :
    permMatrix (g * h) = permMatrix g * permMatrix h := by
  ext i j
  rw [Matrix.mul_apply, Finset.sum_eq_single (h j)]
  · show (if (g * h) j = i then (1 : ℂ) else 0)
        = (if g (h j) = i then (1 : ℂ) else 0) * (if h j = h j then (1 : ℂ) else 0)
    rw [if_pos rfl, mul_one]
    rfl
  · intro k _ hk
    simp [permMatrix, Ne.symm hk]
  · simp

/-- Conjugating the real transition by a permutation relabels it. -/
theorem perm_conj_transition (σ : Equiv.Perm S) (a b : S) :
    permMatrix σ * transition a b * (permMatrix σ)ᴴ = transition (σ a) (σ b) := by
  ext p q
  rw [permMatrix_conj_apply]
  simp only [transition, Matrix.add_apply, single_apply', Equiv.eq_symm_apply]

theorem perm_conj_transitionY (σ : Equiv.Perm S) (a b : S) :
    permMatrix σ * transitionY a b * (permMatrix σ)ᴴ = transitionY (σ a) (σ b) := by
  ext p q
  rw [permMatrix_conj_apply]
  simp only [transitionY, Matrix.smul_apply, Matrix.sub_apply, single_apply', Equiv.eq_symm_apply]

/-- Conjugating the real transition by the quarter phase gives the imaginary transition. -/
theorem phase_conj_transition (a b : S) (hab : a ≠ b) :
    phaseGate a * transition a b * (phaseGate a)ᴴ = transitionY a b := by
  rw [phaseGate_conjTranspose, phaseGate]
  ext p q
  rw [Matrix.mul_diagonal, Matrix.diagonal_mul]
  simp only [transition, transitionY, Matrix.add_apply, Matrix.smul_apply, Matrix.sub_apply,
    single_apply', smul_eq_mul]
  split_ifs <;> simp_all [Complex.I_mul_I] <;> ring

/-- The bracket of the two transition directions is the population difference. -/
theorem bracket_XY (a b : S) (hab : a ≠ b) :
    ((-Complex.I) • transition a b) * ((-Complex.I) • transitionY a b)
      - ((-Complex.I) • transitionY a b) * ((-Complex.I) • transition a b)
      = (2 : ℝ) • (Complex.I • popDiff a b) := by
  rw [real_smul_matrix (2 : ℝ) (Complex.I • popDiff a b)]
  simp only [transition, transitionY, popDiff, Matrix.smul_mul, Matrix.mul_smul, Matrix.add_mul,
    Matrix.mul_add, Matrix.sub_mul, Matrix.mul_sub, Matrix.single_mul_single_same,
    Matrix.single_mul_single_of_ne (h := hab), Matrix.single_mul_single_of_ne (h := hab.symm)]
  ext p q
  simp only [Matrix.smul_apply, Matrix.sub_apply, Matrix.add_apply, Matrix.zero_apply, single_apply',
    smul_eq_mul, mul_one, mul_zero, smul_zero, add_zero, zero_add, sub_zero, zero_sub]
  split_ifs <;> ring_nf <;> simp [Complex.I_sq] <;> ring

end Elementary

/-! ### Section E — the control Lie algebra of one driven transition, one phase, all exchanges -/

section Derivation

variable {S : Type} [Fintype S] [DecidableEq S]

/-- The control words: a permutation, optionally followed by the quarter phase on `i₀`. -/
def ctrl (i₀ : S) (g : Equiv.Perm S × Bool) : Matrix S S ℂ :=
  permMatrix g.1 * (if g.2 then phaseGate i₀ else 1)

theorem ctrl_unitary (i₀ : S) (g : Equiv.Perm S × Bool) : (ctrl i₀ g)ᴴ * ctrl i₀ g = 1 := by
  obtain ⟨σ, b⟩ := g
  cases b
  · simp [ctrl, permMatrix_isometry]
  · simp only [ctrl, if_true, Matrix.conjTranspose_mul]
    rw [Matrix.mul_assoc, ← Matrix.mul_assoc (permMatrix σ)ᴴ, permMatrix_isometry, Matrix.one_mul,
      phaseGate_unitary]

theorem gen_X (i₀ j₁ : S) (σ : Equiv.Perm S) :
    (-Complex.I) • transition (σ i₀) (σ j₁) ∈ controlLie (transition i₀ j₁) (ctrl i₀) :=
  LieSubalgebra.subset_lieSpan ⟨(σ, false), by
    simp only [ctrl, Bool.false_eq_true, if_false, Matrix.mul_one, perm_conj_transition]⟩

theorem gen_Y (i₀ j₁ : S) (h : i₀ ≠ j₁) (σ : Equiv.Perm S) :
    (-Complex.I) • transitionY (σ i₀) (σ j₁) ∈ controlLie (transition i₀ j₁) (ctrl i₀) :=
  LieSubalgebra.subset_lieSpan ⟨(σ, true), by
    have hconj : ctrl i₀ (σ, true) * transition i₀ j₁ * (ctrl i₀ (σ, true))ᴴ
        = permMatrix σ * (phaseGate i₀ * transition i₀ j₁ * (phaseGate i₀)ᴴ) * (permMatrix σ)ᴴ := by
      simp only [ctrl, if_true, Matrix.conjTranspose_mul, Matrix.mul_assoc]
    rw [hconj, phase_conj_transition i₀ j₁ h, perm_conj_transitionY]⟩

/-- A permutation carrying one ordered pair of distinct states to another. -/
theorem exists_perm_pair (i₀ j₁ : S) (h : i₀ ≠ j₁) (p q : S) (hpq : p ≠ q) :
    ∃ σ : Equiv.Perm S, σ i₀ = p ∧ σ j₁ = q := by
  have hj'p : Equiv.swap i₀ p j₁ ≠ p := by
    by_cases h2 : j₁ = p
    · rw [h2, Equiv.swap_apply_right]
      exact fun h3 => h (h3.trans h2.symm)
    · rw [Equiv.swap_apply_of_ne_of_ne h.symm h2]
      exact h2
  refine ⟨Equiv.swap (Equiv.swap i₀ p j₁) q * Equiv.swap i₀ p, ?_, ?_⟩
  · rw [Equiv.Perm.mul_apply, Equiv.swap_apply_left, Equiv.swap_apply_of_ne_of_ne hj'p.symm hpq]
  · rw [Equiv.Perm.mul_apply, Equiv.swap_apply_left]

theorem re_diag_zero {A : Matrix S S ℂ} (hA : Aᴴ = -A) (p : S) : (A p p).re = 0 := by
  have h := congrFun (congrFun hA p) p
  rw [Matrix.conjTranspose_apply, Matrix.neg_apply] at h
  have h2 := congrArg Complex.re h
  rw [Complex.star_def, Complex.conj_re, Complex.neg_re] at h2
  linarith

theorem skew_offdiag {A : Matrix S S ℂ} (hA : Aᴴ = -A) (p q : S) : A q p = -star (A p q) := by
  have h := congrFun (congrFun hA q) p
  rw [Matrix.conjTranspose_apply, Matrix.neg_apply] at h
  rw [h, neg_neg]

/-- **THE PAIR DECOMPOSITION**: a skew pair of entries is a real combination of the two
transition directions. -/
theorem pair_decomp (p q : S) (z : ℂ) :
    Matrix.single p q z - Matrix.single q p (star z)
      = z.re • ((-Complex.I) • transitionY p q) + (-z.im) • ((-Complex.I) • transition p q) := by
  ext r s
  rw [real_smul_matrix, real_smul_matrix]
  simp only [transition, transitionY, Matrix.sub_apply, Matrix.add_apply, Matrix.smul_apply,
    single_apply', smul_eq_mul]
  split_ifs <;> simp [Complex.ext_iff] <;> ring_nf <;> simp [Complex.I_sq] <;> ring

/-- **`su(D)` LIES IN THE CONTROL LIE ALGEBRA** of one driven transition, one quarter phase and
the exchanges. -/
theorem hControl_star (i₀ j₁ : S) (h : i₀ ≠ j₁) : HControl (transition i₀ j₁) (ctrl i₀) := by
  intro A hA
  set L := controlLie (transition i₀ j₁) (ctrl i₀) with hL
  have hX : ∀ p q, p ≠ q → (-Complex.I) • transition p q ∈ L := fun p q hpq => by
    obtain ⟨σ, hp, hq⟩ := exists_perm_pair i₀ j₁ h p q hpq
    have := gen_X i₀ j₁ σ
    rwa [hp, hq] at this
  have hY : ∀ p q, p ≠ q → (-Complex.I) • transitionY p q ∈ L := fun p q hpq => by
    obtain ⟨σ, hp, hq⟩ := exists_perm_pair i₀ j₁ h p q hpq
    have := gen_Y i₀ j₁ h σ
    rwa [hp, hq] at this
  have hZ : ∀ p, Complex.I • popDiff p i₀ ∈ L := fun p => by
    by_cases hp : p = i₀
    · subst hp
      rw [popDiff, sub_self, smul_zero]
      exact L.zero_mem
    · have hb := LieSubalgebra.lie_mem L (hX p i₀ hp) (hY p i₀ hp)
      rw [LieRing.of_associative_ring_bracket, bracket_XY p i₀ hp] at hb
      have := L.smul_mem (1 / 2 : ℝ) hb
      rwa [smul_smul, show (1 / 2 : ℝ) * 2 = 1 by norm_num, one_smul] at this
  have hpair : ∀ p q, p ≠ q → Matrix.single p q (A p q) + Matrix.single q p (A q p) ∈ L := by
    intro p q hpq
    rw [skew_offdiag hA.1 p q, ← single_smul_one q p, neg_smul, single_smul_one, ← sub_eq_add_neg,
      pair_decomp]
    exact L.add_mem (L.smul_mem _ (hY p q hpq)) (L.smul_mem _ (hX p q hpq))
  have hdiag : ∀ p, A p p • popDiff p i₀ ∈ L := by
    intro p
    have hre := re_diag_zero hA.1 p
    have hApp : A p p = ((A p p).im : ℂ) * Complex.I := by
      apply Complex.ext <;> simp [hre]
    rw [hApp, ← smul_smul, ← real_smul_matrix]
    exact L.smul_mem _ (hZ p)
  -- the decomposition of `A`
  set D : Matrix S S ℂ := ∑ p, Matrix.single p p (A p p) with hD
  set Off : Matrix S S ℂ := ∑ p, ∑ q, (Matrix.single p q (A p q) + Matrix.single q p (A q p)
    - if p = q then (2 : ℝ) • Matrix.single p p (A p p) else 0) with hOff
  have hOffEq : Off = (2 : ℝ) • A - (2 : ℝ) • D := by
    have h1 : ∑ p, ∑ q, Matrix.single p q (A p q) = A := (Matrix.matrix_eq_sum_single A).symm
    have h2 : ∑ p, ∑ q, Matrix.single q p (A q p) = A := by
      rw [Finset.sum_comm]
      exact h1
    have h3 : ∑ p : S, ∑ q : S, (if p = q then (2 : ℝ) • Matrix.single p p (A p p) else 0)
        = (2 : ℝ) • D := by
      rw [hD, Finset.smul_sum]
      exact Finset.sum_congr rfl fun p _ => by rw [Finset.sum_ite_eq]; simp
    rw [hOff]
    simp only [Finset.sum_sub_distrib, Finset.sum_add_distrib, h1, h2, h3]
    rw [← two_smul ℝ A]
  have hDeq : D = ∑ p, A p p • popDiff p i₀ := by
    have htr : ∑ p, A p p = 0 := hA.2
    rw [hD]
    simp only [popDiff, smul_sub, Finset.sum_sub_distrib]
    rw [← Finset.sum_smul, htr, zero_smul, sub_zero]
    simp only [single_smul_one]
  have hAeq : A = (1 / 2 : ℝ) • Off + D := by
    rw [hOffEq, smul_sub, smul_smul, smul_smul, show (1 / 2 : ℝ) * 2 = 1 by norm_num, one_smul,
      one_smul, sub_add_cancel]
  rw [hAeq]
  refine L.add_mem (L.smul_mem _ ?_) ?_
  · rw [hOff, ← LieSubalgebra.mem_toSubmodule]
    refine Submodule.sum_mem _ fun p _ => Submodule.sum_mem _ fun q _ => ?_
    rw [LieSubalgebra.mem_toSubmodule]
    by_cases hpq : p = q
    · subst hpq
      rw [if_pos rfl, two_smul, sub_self]
      exact L.zero_mem
    · rw [if_neg hpq, sub_zero]
      exact hpair p q hpq
  · rw [hDeq, ← LieSubalgebra.mem_toSubmodule]
    refine Submodule.sum_mem _ fun p _ => ?_
    rw [LieSubalgebra.mem_toSubmodule]
    exact hdiag p

end Derivation

/-! ### Section F — the primitive, the derivation of Lie-rank richness, and the compressed set -/

section Principle

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **ELEMENTARY TRANSITION RICHNESS**: at every level, every real transition between two
distinguishable states is continuously drivable, every exchange of two states is available,
and a quarter phase on every state is available. -/
def ElementaryTransitionRichness (T : FiniteOperationalTheory A) : Prop :=
  ∀ n : ℕ,
    (∀ a b : A × Fin n, a ≠ b →
      ∀ t : ℝ, T.availExt n Unit (fun _ => conjChannel (flow (transition a b) t)))
    ∧ (∀ a b : A × Fin n, T.availExt n Unit (fun _ => conjChannel (permMatrix (Equiv.swap a b))))
    ∧ (∀ a : A × Fin n, T.availExt n Unit (fun _ => conjChannel (phaseGate a)))

/-- Products of available conjugations are available. -/
theorem avail_mul (T : FiniteOperationalTheory A) (n : ℕ) {V W : Matrix (A × Fin n) (A × Fin n) ℂ}
    (hV : T.availExt n Unit (fun _ => conjChannel V))
    (hW : T.availExt n Unit (fun _ => conjChannel W)) :
    T.availExt n Unit (fun _ => conjChannel (V * W)) := by
  rw [← OIHierarchyGeneral.conjChannel_mul_general]
  exact availExt_comp_unit T n _ _ hW hV

/-- Every permutation is available when every exchange is, on a nonempty carrier. -/
theorem avail_perm (T : FiniteOperationalTheory A) (n : ℕ) [Nonempty (A × Fin n)]
    (hswap : ∀ a b : A × Fin n, T.availExt n Unit (fun _ => conjChannel (permMatrix (Equiv.swap a b))))
    (σ : Equiv.Perm (A × Fin n)) : T.availExt n Unit (fun _ => conjChannel (permMatrix σ)) := by
  refine Equiv.Perm.swap_induction_on σ ?_ ?_
  · obtain ⟨a⟩ := (inferInstance : Nonempty (A × Fin n))
    have := hswap a a
    rwa [Equiv.swap_self] at this
  · intro f x y _ hf
    rw [permMatrix_mul']
    exact avail_mul T n (hswap x y) hf

theorem avail_ctrl (T : FiniteOperationalTheory A) (n : ℕ) [Nonempty (A × Fin n)]
    (hswap : ∀ a b : A × Fin n, T.availExt n Unit (fun _ => conjChannel (permMatrix (Equiv.swap a b))))
    (hphase : ∀ a : A × Fin n, T.availExt n Unit (fun _ => conjChannel (phaseGate a)))
    (i₀ : A × Fin n) (g : Equiv.Perm (A × Fin n) × Bool) :
    T.availExt n Unit (fun _ => conjChannel (ctrl i₀ g)) := by
  obtain ⟨σ, b⟩ := g
  cases b
  · simp only [ctrl, Bool.false_eq_true, if_false, Matrix.mul_one]
    exact avail_perm T n hswap σ
  · simp only [ctrl, if_true]
    exact avail_mul T n (avail_perm T n hswap σ) (hphase i₀)

/-- **LIE-RANK RICHNESS FROM ELEMENTARY TRANSITIONS.** -/
theorem lieRank_of_elementary [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ElementaryTransitionRichness T) : LieRankRichness T := by
  intro n
  rcases n with _ | k
  · refine ⟨Unit, 0, fun _ => 1, by simp, fun _ => by simp, fun B _ => ?_,
      fun t => availExt_zero T _, fun _ => availExt_zero T _⟩
    have hB0 : B = 0 := by
      ext i _
      exact isEmptyElim i
    rw [hB0]
    exact (controlLie (0 : Matrix (A × Fin 0) (A × Fin 0) ℂ)
      (fun _ : Unit => (1 : Matrix (A × Fin 0) (A × Fin 0) ℂ))).zero_mem
  obtain ⟨hflow, hswap, hphase⟩ := h (k + 1)
  let i₀ : A × Fin (k + 1) := (Classical.arbitrary A, ⟨0, k.succ_pos⟩)
  haveI : Nonempty (A × Fin (k + 1)) := ⟨i₀⟩
  by_cases hex : ∃ j : A × Fin (k + 1), j ≠ i₀
  · obtain ⟨j₁, hj⟩ := hex
    exact ⟨Equiv.Perm (A × Fin (k + 1)) × Bool, transition i₀ j₁, ctrl i₀,
      transition_hermitian i₀ j₁, ctrl_unitary i₀, hControl_star i₀ j₁ (Ne.symm hj),
      fun t => hflow i₀ j₁ (Ne.symm hj) t, avail_ctrl T (k + 1) hswap hphase i₀⟩
  · push_neg at hex
    have hone : T.availExt (k + 1) Unit (fun _ => conjChannel 1) := by
      have := hswap i₀ i₀
      rwa [Equiv.swap_self, show (Equiv.refl _ : Equiv.Perm (A × Fin (k + 1))) = 1 from rfl,
        permMatrix_one'] at this
    refine ⟨Unit, 0, fun _ => 1, by simp, fun _ => by simp, fun B hB => ?_, fun t => ?_, fun _ => hone⟩
    · have hB0 : B = 0 := by
        ext p q
        rw [hex p, hex q, Matrix.zero_apply]
        have htr : B.trace = 0 := hB.2
        rw [Matrix.trace, Fintype.sum_eq_single i₀ (fun x hx => absurd (hex x) hx)] at htr
        exact htr
      rw [hB0]
      exact (controlLie (0 : Matrix (A × Fin (k + 1)) (A × Fin (k + 1)) ℂ)
        (fun _ : Unit => (1 : Matrix (A × Fin (k + 1)) (A × Fin (k + 1)) ℂ))).zero_mem
    · have hf : flow (0 : Matrix (A × Fin (k + 1)) (A × Fin (k + 1)) ℂ) t = 1 := by
        simp [flow, NormedSpace.exp_zero]
      rw [hf]
      exact hone

/-- **FULL CONTROL SUPPLIES EVERY ELEMENTARY TRANSITION.** -/
theorem elementary_of_control (T : FiniteOperationalTheory A) (hctrl : HasCompositeUnitaryControl T) :
    ElementaryTransitionRichness T := fun n =>
  ⟨fun a b _ t => hctrl n _ (flow_isometry _ (transition_hermitian a b) t),
    fun a b => hctrl n _ (permMatrix_isometry _),
    fun a => hctrl n _ (phaseGate_unitary a)⟩

variable (T : FiniteOperationalTheory A)

/-- **THE COMPRESSED SET**: reversible implementation locality, elementary transition richness,
embedded observation. -/
def OIPlusElem : Prop :=
  ReversibleImplementationLocality T ∧ ElementaryTransitionRichness T ∧ EmbeddedObservation T

variable [Nonempty A]

theorem oiPlusMicro_of_oiPlusElem (h : OIPlusElem T) : OIPlusMicro T :=
  ⟨h.1, lieRank_of_elementary T h.2.1, h.2.2⟩

theorem qm_of_oiPlusElem (h : OIPlusElem T) : ExactAllFiniteEndomorphicQuantumOps T :=
  qm_of_oiPlusMicro T (oiPlusMicro_of_oiPlusElem T h)

theorem oiPlusElem_of_qm (h : ExactAllFiniteEndomorphicQuantumOps T) : OIPlusElem T :=
  have hp := oiPlusMicro_of_qm T h
  ⟨hp.1, elementary_of_control T (physical_of_exactAll T h).2.2.1, hp.2.2⟩

/-- **THE COMPRESSED SET ⟺ FINITE OPERATIONAL QM**, on any nonempty finite carrier. -/
theorem oiPlusElem_iff_qm : OIPlusElem T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  ⟨qm_of_oiPlusElem T, oiPlusElem_of_qm T⟩

theorem oiPlusElem_iff_oiPlusMicro : OIPlusElem T ↔ OIPlusMicro T := by
  rw [oiPlusElem_iff_qm, oiPlusMicro_iff_qm]

end Principle

/-- **THE CARRIER-GENERAL STATEMENT**, quantified over the carrier. -/
theorem carrier_general_oiPlusElem :
    ∀ (A : Type) [Fintype A] [DecidableEq A] [Nonempty A] (T : FiniteOperationalTheory A),
      OIPlusElem T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  fun _ _ _ _ T => oiPlusElem_iff_qm T

/-- The diagonal countermodel also lacks elementary transitions: the primitive is not supplied
by reversible implementation locality and embedded observation either. -/
theorem elementary_not_redundant :
    ∃ T : FiniteOperationalTheory (Fin 2), ReversibleImplementationLocality T
      ∧ EmbeddedObservation T ∧ ¬ ElementaryTransitionRichness T := by
  obtain ⟨T, h1, h2, h3⟩ := lieRank_not_redundant
  exact ⟨T, h1, h2, fun h => h3 (lieRank_of_elementary T h)⟩

#print axioms realized_conj
#print axioms realized_zero
#print axioms realized_add
#print axioms realized_sum
#print axioms sum_comp'
#print axioms comp_sum'
#print axioms realized_comp
#print axioms realized_smul_nonneg
#print axioms realized_transport
#print axioms realized_id
#print axioms realized_localLuders
#print axioms realized_discard
#print axioms genFamily_regrouping
#print axioms genFamily_relabelling
#print axioms genTheory_ambient
#print axioms genTheory_embeddedObservation
#print axioms genTheory_generated
#print axioms genTheory_reversibleImplementationLocality
#print axioms diagClass_arch
#print axioms diagClass_contextStable
#print axioms diagClass_labelInvariant
#print axioms diagClass_daggerStable
#print axioms preservesDiag_conj_of_diag
#print axioms diagGen_not_control
#print axioms lieRank_not_redundant
#print axioms single_apply'
#print axioms single_conjTranspose'
#print axioms single_smul_one
#print axioms transition_hermitian
#print axioms phaseGate_conjTranspose
#print axioms phaseGate_unitary
#print axioms permMatrix_one'
#print axioms permMatrix_mul'
#print axioms perm_conj_transition
#print axioms perm_conj_transitionY
#print axioms phase_conj_transition
#print axioms bracket_XY
#print axioms ctrl_unitary
#print axioms gen_X
#print axioms gen_Y
#print axioms exists_perm_pair
#print axioms re_diag_zero
#print axioms skew_offdiag
#print axioms pair_decomp
#print axioms hControl_star
#print axioms avail_mul
#print axioms avail_perm
#print axioms avail_ctrl
#print axioms lieRank_of_elementary
#print axioms elementary_of_control
#print axioms oiPlusMicro_of_oiPlusElem
#print axioms qm_of_oiPlusElem
#print axioms oiPlusElem_of_qm
#print axioms oiPlusElem_iff_qm
#print axioms oiPlusElem_iff_oiPlusMicro
#print axioms carrier_general_oiPlusElem
#print axioms elementary_not_redundant

end LieRankSource
end OIBridge
