import OIBridge.ManuscriptAxioms
import OIBridge.SecondOrderDrive

/-!
# The lift audit — executable layer flows

The preregistered pass of `LIFT-AUDIT.md`. The substratum update factors as layers of commuting
local involutions (CT2), and each gate `g` is reached at time one by the exact one-parameter
unitary group `unit g t` of `SecondOrderCircuit`. Three questions, in order, each with its own
outcome:

* **Q1, finite-region realization**: for an involution `σ` of a finite configuration space `S`
  and every level `n`, `gateFlow (levelPerm σ n) t = unit (permMat (σ × id)) t` is a unitary
  one-parameter group starting at `1` and reaching the permutation matrix at `t = 1`, its
  conjugation is trace-preserving, and on a region it is the stage image of the quasilocal gate
  unitary of CT2.
* **Q2, derived executability**: `LayerFlowExecutable T σ` says the conjugation by the gate flow
  is available in `T` at every level and time. It holds in every theory with composite unitary
  control, and it fails in the theory generated by any configuration-level class, in particular
  in `substratumTheory S`, as soon as `σ` moves one configuration: at `t = 1/2` the gate flow does
  not preserve the diagonal.
* **Q3, richness bridge**: see Section C.

Nothing here reads availability off the CT2 path; `unit g t` enters a theory's availability only
through the predicate `LayerFlowExecutable`, and the audit records where that predicate holds.
-/

namespace OIBridge
namespace LiftAudit

open Complex Matrix CoherentLift SpectatorBridge OperationalAssembly AncillaClosure
open MonoidalCompletion InterventionLocality MicroReversibility PrimitiveSource LieRankSource
open DiagonalTheory SubstratumInterface StructuralClosure MinimalRepertoire LevelOneSeam
open PhysicalCharacterization RouteB ManuscriptAxioms
open OIBridge.SecondOrderCircuit (unit proj permMat permMat_involutive unit_mul_unit unit_zero
  unit_one star_unit_mul_unit unit_mul_star_unit)

/-! ### Section A — Q1: the finite-region gate flow as a channel candidate -/

section Realization

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **THE GATE FLOW OF AN INVOLUTION**, as a matrix on a finite configuration space. -/
noncomputable def gateFlow (σ : Equiv.Perm S) (t : ℝ) : Matrix S S ℂ :=
  unit (permMat σ) t

/-- The layer involution read at level `n`: the ancilla is a spectator. -/
def levelPerm (σ : Equiv.Perm S) (n : ℕ) : Equiv.Perm (S × Fin n) :=
  σ.prodCongr (Equiv.refl (Fin n))

omit [Fintype S] [DecidableEq S] in
theorem levelPerm_apply (σ : Equiv.Perm S) (n : ℕ) (p : S × Fin n) :
    levelPerm σ n p = (σ p.1, p.2) := rfl

omit [Fintype S] [DecidableEq S] in
theorem levelPerm_involutive {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) (n : ℕ) (p : S × Fin n) :
    levelPerm σ n (levelPerm σ n p) = p := by
  rw [levelPerm_apply, levelPerm_apply, hσ]

theorem permMat_star {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) :
    star (permMat σ) = permMat σ := by
  rw [Matrix.star_eq_conjTranspose]
  exact (permMat_involutive hσ).2

/-- **Q1 — THE GATE FLOW IS UNITARY** at every time. -/
theorem gateFlow_unitary {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) (t : ℝ) :
    (gateFlow σ t)ᴴ * gateFlow σ t = 1 := by
  rw [gateFlow, ← Matrix.star_eq_conjTranspose]
  exact star_unit_mul_unit (permMat_involutive hσ).1 (permMat_star hσ) t

/-- **Q1 — THE ONE-PARAMETER GROUP LAW.** -/
theorem gateFlow_group {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) (t s : ℝ) :
    gateFlow σ t * gateFlow σ s = gateFlow σ (t + s) :=
  unit_mul_unit (permMat_involutive hσ).1 t s

/-- **Q1 — THE FLOW STARTS AT THE IDENTITY.** -/
theorem gateFlow_zero (σ : Equiv.Perm S) : gateFlow σ 0 = 1 :=
  unit_zero _

/-- **Q1 — AT TIME ONE THE FLOW IS THE GATE.** -/
theorem gateFlow_one {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) : gateFlow σ 1 = permMat σ :=
  unit_one (permMat_involutive hσ).1

/-- **Q1 — THE CANDIDATE CHANNEL PRESERVES THE TRACE**: the conjugation by the gate flow has the
shape of a one-outcome channel. -/
theorem gateFlow_trace {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) (t : ℝ) (X : Matrix S S ℂ) :
    (conjChannel (gateFlow σ t) X).trace = X.trace :=
  DimensionalCountermodel.conjChannel_trace _ (gateFlow_unitary hσ t) X

/-- **Q1 — ON A REGION THE FINITE UNITARY IS THE STAGE IMAGE OF THE QUASILOCAL GATE UNITARY**
of CT2: the candidate is exactly the object the drive theorem runs, read on one region. -/
theorem gateFlow_stage {ι : Type} [DecidableEq ι] {Q : Type} [Fintype Q] [DecidableEq Q]
    [Nonempty Q] (Λ : Finset ι) (σ : RegionTower.Conf Λ Q ≃ RegionTower.Conf Λ Q) (t : ℝ) :
    QuasilocalAlgebra.stage Λ (gateFlow σ t) = unit (SecondOrderCircuit.localGate Λ σ) t := by
  rw [SecondOrderCircuit.unit_localGate_mem_stage]
  rfl

end Realization

/-! ### Section B — Q2: executability is not derived from configuration-level generation -/

section Executability

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **EXECUTABILITY OF THE LAYER FLOW**: at every level and every time, the conjugation by the
gate flow of the layer involution (the ancilla a spectator) is an available one-outcome
operation. This is the only way `unit g t` enters a theory's availability in this file. -/
def LayerFlowExecutable (T : FiniteOperationalTheory S) (σ : Equiv.Perm S) : Prop :=
  ∀ (n : ℕ) (t : ℝ), T.availExt n Unit (fun _ => conjChannel (gateFlow (levelPerm σ n) t))

/-- **EXECUTABILITY IS CONSISTENT**: it holds in every theory with composite unitary control, so
in quantum mechanics. -/
theorem layerFlowExecutable_of_control (T : FiniteOperationalTheory S)
    (hctrl : HasCompositeUnitaryControl T) {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) :
    LayerFlowExecutable T σ :=
  fun n t => hctrl n _ (gateFlow_unitary (levelPerm_involutive hσ n) t)

theorem exp_pi_I_half : Complex.exp ((Real.pi : ℂ) * Complex.I * ((1 / 2 : ℝ) : ℂ)) = Complex.I := by
  have h : (Real.pi : ℂ) * Complex.I * ((1 / 2 : ℝ) : ℂ) = ((Real.pi / 2 : ℝ) : ℂ) * Complex.I := by
    push_cast
    ring
  rw [h, Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin, Real.cos_pi_div_two,
    Real.sin_pi_div_two]
  simp

theorem permMat_apply_self {σ : Equiv.Perm S} {a : S} (ha : σ a ≠ a) : permMat σ a a = 0 := by
  rw [SecondOrderCircuit.permMat_apply, if_neg ha]

theorem permMat_apply_moved (σ : Equiv.Perm S) (a : S) : permMat σ (σ a) a = 1 := by
  rw [SecondOrderCircuit.permMat_apply, if_pos rfl]

/-- The gate flow at time one half, entrywise on a moved configuration: the diagonal entry is
`(1 + i)/2` and the entry towards its image is `(1 − i)/2`. -/
theorem gateFlow_half_entries {σ : Equiv.Perm S} {a : S} (ha : σ a ≠ a) :
    gateFlow σ (1 / 2 : ℝ) a a = (1 + Complex.I) / 2
      ∧ gateFlow σ (1 / 2 : ℝ) (σ a) a = (1 - Complex.I) / 2 := by
  have hI := exp_pi_I_half
  simp only [gateFlow, unit, proj, hI]
  constructor
  · rw [Matrix.add_apply, Matrix.one_apply_eq, Matrix.smul_apply, Matrix.smul_apply,
      Matrix.sub_apply, Matrix.one_apply_eq, permMat_apply_self ha, smul_eq_mul, smul_eq_mul]
    ring
  · rw [Matrix.add_apply, Matrix.one_apply_ne (Ne.symm ha).symm, Matrix.smul_apply,
      Matrix.smul_apply, Matrix.sub_apply, Matrix.one_apply_ne ha, permMat_apply_moved,
      smul_eq_mul, smul_eq_mul]
    ring

/-- **THE GATE FLOW AT TIME ONE HALF DOES NOT PRESERVE THE DIAGONAL** when the involution moves
a configuration: it takes the classical state at `a` to a matrix with a nonzero entry between `a`
and its image. -/
theorem gateFlow_half_not_preservesDiag {σ : Equiv.Perm S} {a : S} (ha : σ a ≠ a) :
    ¬ PreservesDiag (conjChannel (gateFlow σ (1 / 2 : ℝ))) := by
  intro h
  obtain ⟨w', hw'⟩ := h (fun p => if p = a then 1 else 0)
  rw [conjChannel_apply] at hw'
  have hent := congrFun (congrFun hw' a) (σ a)
  rw [Matrix.diagonal_apply_ne _ (Ne.symm ha), Matrix.mul_apply] at hent
  obtain ⟨h1, h2⟩ := gateFlow_half_entries ha
  have hsum : ∑ j, (gateFlow σ (1 / 2 : ℝ) * Matrix.diagonal (fun p => if p = a then (1 : ℂ) else 0)) a j
      * (gateFlow σ (1 / 2 : ℝ))ᴴ j (σ a) = (1 + Complex.I) / 2 * star ((1 - Complex.I) / 2) := by
    rw [Finset.sum_eq_single a]
    · rw [Matrix.mul_diagonal, if_pos rfl, mul_one, Matrix.conjTranspose_apply, h1, h2]
    · intro j _ hj
      rw [Matrix.mul_diagonal, if_neg hj, mul_zero, zero_mul]
    · intro h
      exact absurd (Finset.mem_univ a) h
  rw [hsum] at hent
  have : (1 + Complex.I) / 2 * star ((1 - Complex.I) / 2) = Complex.I / 2 := by
    simp only [Complex.star_def, map_div₀, map_sub, map_one, Complex.conj_I, map_ofNat]
    ring_nf
    simp [Complex.I_sq]
  rw [this] at hent
  have hI : Complex.I / 2 ≠ 0 := by simp
  exact hI hent

/-- **Q2 — NO CONFIGURATION-LEVEL CLASS DERIVES EXECUTABILITY**: in the theory any architecture
of monomial operators generates, the gate flow of an involution that moves a configuration is
unavailable at time one half, already at level one. -/
theorem configurationLevel_not_layerFlowExecutable {𝓘 : ImplementationClass}
    (arch : Architecture 𝓘) (h : ConfigurationLevel 𝓘) {σ : Equiv.Perm S} {x : S}
    (hx : σ x ≠ x) : ¬ LayerFlowExecutable (genTheory 𝓘 arch S) σ := by
  intro hex
  have hav := hex 1 (1 / 2 : ℝ)
  obtain ⟨ι, _, K, hK, hadm⟩ := hav.1 ()
  have hK' : conjChannel (gateFlow (levelPerm σ 1) (1 / 2 : ℝ)) = ∑ i, conjChannel (K i) := hK
  have hx' : levelPerm σ 1 (x, 0) ≠ (x, 0) := by
    rw [levelPerm_apply]
    intro hc
    exact hx (Prod.mk.inj hc).1
  apply gateFlow_half_not_preservesDiag hx'
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_monomial (h _ _ (hadm i))

/-- **Q2 — THE SUBSTRATUM THEORY DOES NOT DERIVE EXECUTABILITY** of any layer involution that
moves a configuration. -/
theorem substratumTheory_not_layerFlowExecutable {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) :
    ¬ LayerFlowExecutable (substratumTheory S) σ :=
  configurationLevel_not_layerFlowExecutable substratumClass_arch substratumClass_configurationLevel hx

end Executability

/-! ### Section C — Q3: the richness bridge

The closed form of the transition flow, the orbit calculus on an involution, the isolation of one
transition flow from the gate flow by two sign conjugations and a phase, and the assembly into
`PhaseFreeRichness`. -/

section ClosedForm

open scoped Matrix.Norms.L2Operator

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **THE EXPONENTIAL OF A SCALED IDEMPOTENT** is a polynomial in it. -/
theorem exp_smul_idempotent {P : Matrix S S ℂ} (hP : P * P = P) (c : ℂ) :
    NormedSpace.exp (c • P) = 1 + (Complex.exp c - 1) • P := by
  have hpow : ∀ n : ℕ, (c • P) ^ n = c ^ n • (if n = 0 then (1 : Matrix S S ℂ) else P) := by
    intro n
    induction n with
    | zero => simp
    | succ k ih =>
      rw [pow_succ, ih, if_neg (Nat.succ_ne_zero k), Matrix.smul_mul, Matrix.mul_smul, smul_smul,
        ← pow_succ]
      by_cases hk : k = 0
      · subst hk; simp
      · rw [if_neg hk, hP]
  have hsum := NormedSpace.exp_series_hasSum_exp' (𝕂 := ℂ) (c • P)
  have hsc : HasSum (fun n : ℕ => (n.factorial⁻¹ : ℂ) * c ^ n) (Complex.exp c) := by
    have h := NormedSpace.exp_series_hasSum_exp' (𝕂 := ℂ) c
    rw [Complex.exp_eq_exp_ℂ]
    simpa [smul_eq_mul] using h
  have h1 : HasSum (fun n : ℕ => ((n.factorial⁻¹ : ℂ) * c ^ n) • P) (Complex.exp c • P) :=
    hsc.smul_const P
  have h2 : HasSum (fun n : ℕ => if n = 0 then (1 - P) else (0 : Matrix S S ℂ)) (1 - P) :=
    hasSum_ite_eq 0 (1 - P)
  have heq : (fun n : ℕ => (n.factorial⁻¹ : ℂ) • (c • P) ^ n)
      = fun n => ((n.factorial⁻¹ : ℂ) * c ^ n) • P + if n = 0 then 1 - P else 0 := by
    funext n
    rw [hpow]
    by_cases hn : n = 0
    · subst hn; simp
    · rw [if_neg hn, if_neg hn, add_zero, smul_smul]
  rw [heq] at hsum
  rw [hsum.unique (h1.add h2), sub_smul, one_smul]
  abel

/-- The projector onto a pair of states. -/
def pairProj (a b : S) : Matrix S S ℂ := Matrix.single a a 1 + Matrix.single b b 1

theorem transition_mul_transition {a b : S} (hab : a ≠ b) :
    transition a b * transition a b = pairProj a b := by
  simp only [transition, pairProj, Matrix.add_mul, Matrix.mul_add]
  simp [hab, hab.symm, add_comm]

theorem pairProj_mul_transition {a b : S} (hab : a ≠ b) :
    pairProj a b * transition a b = transition a b := by
  simp only [transition, pairProj, Matrix.add_mul, Matrix.mul_add]
  simp [hab, hab.symm, add_comm]

theorem transition_mul_pairProj {a b : S} (hab : a ≠ b) :
    transition a b * pairProj a b = transition a b := by
  simp only [transition, pairProj, Matrix.add_mul, Matrix.mul_add]
  simp [hab, hab.symm, add_comm]

theorem pairProj_mul_pairProj {a b : S} (hab : a ≠ b) :
    pairProj a b * pairProj a b = pairProj a b := by
  simp only [pairProj, Matrix.add_mul, Matrix.mul_add]
  simp [hab, hab.symm, add_comm]

/-- **THE CLOSED FORM OF THE TRANSITION FLOW**: `e^{-is X_{ab}} = 1 + (cos s − 1) Π_{ab} − i sin s X_{ab}`,
through the two orthogonal idempotents `(Π ± X)/2`. -/
theorem flow_transition_closedForm {a b : S} (hab : a ≠ b) (s : ℝ) :
    ReachabilitySeam.flow (transition a b) s
      = 1 + ((Real.cos s : ℂ) - 1) • pairProj a b
          - ((Real.sin s : ℂ) * Complex.I) • transition a b := by
  set X := transition a b with hXdef
  set Pab := pairProj a b with hPabdef
  have hXX : X * X = Pab := transition_mul_transition hab
  have hPX : Pab * X = X := pairProj_mul_transition hab
  have hXP : X * Pab = X := transition_mul_pairProj hab
  have hPP : Pab * Pab = Pab := pairProj_mul_pairProj hab
  set Pp : Matrix S S ℂ := (2 : ℂ)⁻¹ • (Pab + X) with hPp
  set Pm : Matrix S S ℂ := (2 : ℂ)⁻¹ • (Pab - X) with hPm
  have hsq : ∀ (M N : Matrix S S ℂ) (c d : ℂ), (c • M) * (d • N) = (c * d) • (M * N) := by
    intro M N c d
    rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
  have hPp2 : Pp * Pp = Pp := by
    rw [hPp, hsq, Matrix.add_mul, Matrix.mul_add, Matrix.mul_add, hPP, hPX, hXP, hXX]
    rw [show Pab + X + (X + Pab) = (2 : ℂ) • (Pab + X) by rw [two_smul]; abel, smul_smul]
    norm_num
  have hPm2 : Pm * Pm = Pm := by
    rw [hPm, hsq, Matrix.sub_mul, Matrix.mul_sub, Matrix.mul_sub, hPP, hPX, hXP, hXX]
    rw [show Pab - X - (X - Pab) = (2 : ℂ) • (Pab - X) by rw [two_smul]; abel, smul_smul]
    norm_num
  have hPpm : Pp * Pm = 0 := by
    have h0 : (Pab + X) * (Pab - X) = 0 := by
      rw [Matrix.add_mul, Matrix.mul_sub, Matrix.mul_sub, hPP, hPX, hXP, hXX]
      abel
    rw [hPp, hPm, hsq, h0, smul_zero]
  have hPmp : Pm * Pp = 0 := by
    have h0 : (Pab - X) * (Pab + X) = 0 := by
      rw [Matrix.sub_mul, Matrix.mul_add, Matrix.mul_add, hPP, hPX, hXP, hXX]
      abel
    rw [hPp, hPm, hsq, h0, smul_zero]
  have hX : (-(s : ℂ) * Complex.I) • X = (-(s : ℂ) * Complex.I) • Pp + ((s : ℂ) * Complex.I) • Pm := by
    rw [hPp, hPm, smul_smul, smul_smul, smul_add, smul_sub]
    module
  have hcomm : Commute ((-(s : ℂ) * Complex.I) • Pp) (((s : ℂ) * Complex.I) • Pm) := by
    show _ * _ = _ * _
    rw [hsq Pp Pm, hsq Pm Pp, hPpm, hPmp, smul_zero, smul_zero]
  have he : Complex.exp (-(s : ℂ) * Complex.I) = (Real.cos s : ℂ) - (Real.sin s : ℂ) * Complex.I := by
    rw [show -(s : ℂ) * Complex.I = ((-s : ℝ) : ℂ) * Complex.I by push_cast; ring, Complex.exp_mul_I,
      ← Complex.ofReal_cos, ← Complex.ofReal_sin, Real.cos_neg, Real.sin_neg]
    push_cast
    ring
  have he' : Complex.exp ((s : ℂ) * Complex.I) = (Real.cos s : ℂ) + (Real.sin s : ℂ) * Complex.I := by
    rw [Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin]
  rw [ReachabilitySeam.flow, hX, Matrix.exp_add_of_commute _ _ hcomm, exp_smul_idempotent hPp2,
    exp_smul_idempotent hPm2, he, he', Matrix.add_mul, Matrix.mul_add, Matrix.mul_add]
  simp only [Matrix.one_mul, Matrix.mul_one]
  rw [hsq Pp Pm, hPpm, smul_zero, add_zero, hPp, hPm, smul_smul, smul_smul, smul_add, smul_sub]
  module

end ClosedForm

section Orbit

variable {S : Type} [Fintype S] [DecidableEq S] (τ : Equiv.Perm S)

/-- **AN ORBIT MATRIX** of an involution: `A z` on the diagonal, `B z` at `(τ z, z)` when `z` is
moved, and nothing else. Permutation matrices of the involution, diagonal matrices, the gate flows
and the transition flows on a moved pair are all of this form, and the form is closed under
products. -/
def orb (A B : S → ℂ) : Matrix S S ℂ :=
  Matrix.of fun y z => (if y = z then A z else 0) + (if τ z ≠ z ∧ y = τ z then B z else 0)

omit [Fintype S] in
theorem orb_apply (A B : S → ℂ) (y z : S) :
    orb τ A B y z = (if y = z then A z else 0) + (if τ z ≠ z ∧ y = τ z then B z else 0) := rfl

omit [Fintype S] in
theorem orb_ext {A A' B B' : S → ℂ} (hA : ∀ z, A z = A' z) (hB : ∀ z, τ z ≠ z → B z = B' z) :
    orb τ A B = orb τ A' B' := by
  ext y z
  rw [orb_apply, orb_apply, hA]
  by_cases hz : τ z ≠ z ∧ y = τ z
  · rw [if_pos hz, if_pos hz, hB z hz.1]
  · rw [if_neg hz, if_neg hz]

theorem sum_mul_ite_eq (f : S → ℂ) (z : S) (c : ℂ) :
    ∑ w, f w * (if w = z then c else 0) = f z * c := by
  rw [Finset.sum_eq_single z]
  · rw [if_pos rfl]
  · intro w _ hw
    rw [if_neg hw, mul_zero]
  · intro h
    exact absurd (Finset.mem_univ z) h

theorem sum_mul_ite_and_eq (f : S → ℂ) (p : Prop) [Decidable p] (z : S) (c : ℂ) :
    ∑ w, f w * (if p ∧ w = z then c else 0) = if p then f z * c else 0 := by
  by_cases hp : p
  · rw [if_pos hp]
    rw [← sum_mul_ite_eq f z c]
    refine Finset.sum_congr rfl fun w _ => ?_
    by_cases hw : w = z
    · rw [if_pos ⟨hp, hw⟩, if_pos hw]
    · rw [if_neg (fun h => hw h.2), if_neg hw]
  · rw [if_neg hp]
    refine Finset.sum_eq_zero fun w _ => ?_
    rw [if_neg (fun h => hp h.1), mul_zero]

/-- **THE ORBIT CALCULUS**: the product of two orbit matrices is an orbit matrix, with the
diagonal and antidiagonal coefficients composed along the orbit. -/
theorem orb_mul (hτ : ∀ z, τ (τ z) = z) (A₁ B₁ A₂ B₂ : S → ℂ) :
    orb τ A₁ B₁ * orb τ A₂ B₂
      = orb τ (fun z => A₁ z * A₂ z + if τ z ≠ z then B₁ (τ z) * B₂ z else 0)
          (fun z => B₁ z * A₂ z + A₁ (τ z) * B₂ z) := by
  ext y z
  rw [Matrix.mul_apply]
  simp_rw [orb_apply]
  have hsplit : ∑ w, ((if y = w then A₁ w else 0) + if τ w ≠ w ∧ y = τ w then B₁ w else 0)
      * ((if w = z then A₂ z else 0) + if τ z ≠ z ∧ w = τ z then B₂ z else 0)
      = ((if y = z then A₁ z else 0) + if τ z ≠ z ∧ y = τ z then B₁ z else 0) * A₂ z
        + if τ z ≠ z then
            ((if y = τ z then A₁ (τ z) else 0) + if τ (τ z) ≠ τ z ∧ y = τ (τ z) then B₁ (τ z) else 0)
              * B₂ z
          else 0 := by
    simp_rw [mul_add, Finset.sum_add_distrib, sum_mul_ite_eq, sum_mul_ite_and_eq]
  rw [hsplit]
  by_cases hz : τ z = z
  · have hz' : ¬ (τ z ≠ z) := not_not.mpr hz
    simp only [hz', false_and, if_false, add_zero]
    by_cases hy : y = z
    · simp [hy]
    · simp [hy]
  · rw [hτ z]
    have hzτ : ¬ z = τ z := fun h => hz h.symm
    by_cases hy : y = z
    · simp only [hy, hz, hzτ, ne_eq, not_false_eq_true, true_and, and_false, if_true, if_false,
        zero_add, add_zero, zero_mul, mul_zero]
    · by_cases hyτ : y = τ z
      · simp only [hy, hyτ, hz, hzτ, ne_eq, not_false_eq_true, true_and, and_false, if_true,
          if_false, zero_add, add_zero, zero_mul, mul_zero]
      · simp only [hy, hyτ, hz, hzτ, ne_eq, not_false_eq_true, true_and, and_false, if_true,
          if_false, zero_add, add_zero, zero_mul, mul_zero]

omit [Fintype S] in
theorem one_eq_orb : (1 : Matrix S S ℂ) = orb τ (fun _ => 1) (fun _ => 0) := by
  ext y z
  rw [orb_apply, Matrix.one_apply]
  by_cases h : τ z ≠ z ∧ y = τ z
  · rw [if_pos h, add_zero]
  · rw [if_neg h, add_zero]

omit [Fintype S] in
theorem diagonal_eq_orb (d : S → ℂ) : Matrix.diagonal d = orb τ d (fun _ => 0) := by
  ext y z
  rw [orb_apply, Matrix.diagonal_apply, ite_self, add_zero]
  by_cases hy : y = z
  · subst hy; rfl
  · rw [if_neg hy, if_neg hy]

theorem permMat_eq_orb : permMat τ = orb τ (fun z => if τ z = z then 1 else 0) (fun _ => 1) := by
  ext y z
  rw [orb_apply, SecondOrderCircuit.permMat_apply]
  by_cases hz : τ z = z
  · have h' : ¬ (τ z ≠ z ∧ y = τ z) := fun h => h.1 hz
    rw [if_neg h', add_zero, if_pos hz]
    by_cases hy : y = z
    · rw [if_pos (hz.trans hy.symm : τ z = y), if_pos hy]
    · rw [if_neg (fun h : τ z = y => hy (h.symm.trans hz)), if_neg hy]
  · rw [if_neg hz, ite_self, zero_add]
    by_cases hy : y = τ z
    · rw [if_pos (hy.symm : τ z = y), if_pos (⟨hz, hy⟩ : τ z ≠ z ∧ y = τ z)]
    · rw [if_neg (fun h : τ z = y => hy h.symm), if_neg (fun h : τ z ≠ z ∧ y = τ z => hy h.2)]

omit [Fintype S] in
theorem orb_add (A B A' B' : S → ℂ) :
    orb τ A B + orb τ A' B' = orb τ (fun z => A z + A' z) (fun z => B z + B' z) := by
  ext y z
  simp only [Matrix.add_apply, orb_apply]
  split_ifs <;> ring

omit [Fintype S] in
theorem orb_sub (A B A' B' : S → ℂ) :
    orb τ A B - orb τ A' B' = orb τ (fun z => A z - A' z) (fun z => B z - B' z) := by
  ext y z
  simp only [Matrix.sub_apply, orb_apply]
  split_ifs <;> ring

omit [Fintype S] in
theorem orb_smul (c : ℂ) (A B : S → ℂ) :
    c • orb τ A B = orb τ (fun z => c * A z) (fun z => c * B z) := by
  ext y z
  simp only [Matrix.smul_apply, orb_apply, smul_eq_mul]
  split_ifs <;> ring

/-- **THE GATE FLOW IS AN ORBIT MATRIX**: `1 + α/2` on the diagonal of a moved configuration, `1`
on a fixed one, `−α/2` towards the image, with `α = e^{iπt} − 1`. -/
theorem gateFlow_eq_orb (t : ℝ) :
    gateFlow τ t
      = orb τ (fun z => if τ z = z then 1
            else 1 + (Complex.exp ((Real.pi : ℂ) * Complex.I * (t : ℂ)) - 1) * (2 : ℂ)⁻¹)
          (fun _ => -((Complex.exp ((Real.pi : ℂ) * Complex.I * (t : ℂ)) - 1) * (2 : ℂ)⁻¹)) := by
  rw [gateFlow, unit, proj, permMat_eq_orb τ, one_eq_orb τ, orb_sub, orb_smul, orb_smul, orb_add]
  refine orb_ext τ (fun z => ?_) (fun z _ => ?_)
  · by_cases hz : τ z = z
    · rw [if_pos hz, if_pos hz]; ring
    · rw [if_neg hz, if_neg hz]; ring
  · ring

/-- **CONJUGATING AN ORBIT MATRIX BY A DIAGONAL** rescales the diagonal by `d z²` and the
antidiagonal by `d (τ z) d z`. -/
theorem diagonal_mul_orb_mul_diagonal (d A B : S → ℂ) :
    Matrix.diagonal d * orb τ A B * Matrix.diagonal d
      = orb τ (fun z => d z * A z * d z) (fun z => d (τ z) * B z * d z) := by
  ext y z
  rw [Matrix.mul_diagonal, Matrix.diagonal_mul, orb_apply, orb_apply]
  by_cases hy : y = z
  · have h : ¬ (τ z ≠ z ∧ y = τ z) := fun h => h.1 (h.2.symm.trans hy)
    rw [if_pos hy, if_pos hy, if_neg h, if_neg h, hy]; ring
  · rw [if_neg hy, if_neg hy]
    by_cases h : τ z ≠ z ∧ y = τ z
    · rw [if_pos h, if_pos h, h.2]; ring
    · rw [if_neg h, if_neg h]; ring

theorem diagonal_mul_orb (d A B : S → ℂ) :
    Matrix.diagonal d * orb τ A B = orb τ (fun z => d z * A z) (fun z => d (τ z) * B z) := by
  ext y z
  rw [Matrix.diagonal_mul, orb_apply, orb_apply]
  by_cases hy : y = z
  · have h : ¬ (τ z ≠ z ∧ y = τ z) := fun h => h.1 (h.2.symm.trans hy)
    rw [if_pos hy, if_pos hy, if_neg h, if_neg h, hy]; ring
  · rw [if_neg hy, if_neg hy]
    by_cases h : τ z ≠ z ∧ y = τ z
    · rw [if_pos h, if_pos h, h.2]; ring
    · rw [if_neg h, if_neg h]; ring

omit [Fintype S] in
theorem pairProj_eq_orb {a b : S} (hab : a ≠ b) :
    pairProj a b = orb τ (fun z => if z = a ∨ z = b then 1 else 0) (fun _ => 0) := by
  ext y z
  rw [pairProj, Matrix.add_apply, Matrix.single_apply, Matrix.single_apply, orb_apply, ite_self,
    add_zero]
  by_cases hy : y = z
  · by_cases hza : y = a
    · rw [if_pos (⟨hza.symm, hza.symm.trans hy⟩ : a = y ∧ a = z),
        if_neg (fun h : b = y ∧ b = z => hab (hza.symm.trans h.1.symm)), if_pos hy,
        if_pos (Or.inl (hy.symm.trans hza) : z = a ∨ z = b), add_zero]
    · by_cases hzb : y = b
      · rw [if_neg (fun h : a = y ∧ a = z => hza h.1.symm),
          if_pos (⟨hzb.symm, hzb.symm.trans hy⟩ : b = y ∧ b = z), if_pos hy,
          if_pos (Or.inr (hy.symm.trans hzb) : z = a ∨ z = b), zero_add]
      · rw [if_neg (fun h : a = y ∧ a = z => hza h.1.symm),
          if_neg (fun h : b = y ∧ b = z => hzb h.1.symm), if_pos hy,
          if_neg (fun h : z = a ∨ z = b => h.elim (fun h' => hza (hy.trans h'))
            (fun h' => hzb (hy.trans h'))), add_zero]
  · rw [if_neg (fun h : a = y ∧ a = z => hy (h.1.symm.trans h.2)),
      if_neg (fun h : b = y ∧ b = z => hy (h.1.symm.trans h.2)), if_neg hy, add_zero]

omit [Fintype S] in
theorem transition_eq_orb {a : S} (ha : τ a ≠ a) (hτ : ∀ z, τ (τ z) = z) :
    transition a (τ a) = orb τ (fun _ => 0) (fun z => if z = a ∨ z = τ a then 1 else 0) := by
  have hab : a ≠ τ a := Ne.symm ha
  ext y z
  rw [transition, Matrix.add_apply, Matrix.single_apply, Matrix.single_apply, orb_apply, ite_self,
    zero_add]
  by_cases hza : z = a
  · have hz : τ z ≠ z := by rw [hza]; exact ha
    by_cases hy : y = τ a
    · rw [if_neg (fun h : a = y ∧ τ a = z => ha (h.2.trans hza)),
        if_pos (⟨hy.symm, hza.symm⟩ : τ a = y ∧ a = z),
        if_pos (⟨hz, hy.trans (congrArg τ hza.symm)⟩ : τ z ≠ z ∧ y = τ z),
        if_pos (Or.inl hza : z = a ∨ z = τ a), zero_add]
    · rw [if_neg (fun h : a = y ∧ τ a = z => ha (h.2.trans hza)),
        if_neg (fun h : τ a = y ∧ a = z => hy h.1.symm),
        if_neg (fun h : τ z ≠ z ∧ y = τ z => hy (h.2.trans (congrArg τ hza))), add_zero]
  · by_cases hzb : z = τ a
    · have hz : τ z ≠ z := by rw [hzb, hτ]; exact hab
      have hτz : τ z = a := by rw [hzb, hτ]
      by_cases hy : y = a
      · rw [if_pos (⟨hy.symm, hzb.symm⟩ : a = y ∧ τ a = z),
          if_neg (fun h : τ a = y ∧ a = z => hza h.2.symm),
          if_pos (⟨hz, hy.trans hτz.symm⟩ : τ z ≠ z ∧ y = τ z),
          if_pos (Or.inr hzb : z = a ∨ z = τ a), add_zero]
      · rw [if_neg (fun h : a = y ∧ τ a = z => hy h.1.symm),
          if_neg (fun h : τ a = y ∧ a = z => hza h.2.symm),
          if_neg (fun h : τ z ≠ z ∧ y = τ z => hy (h.2.trans hτz)), add_zero]
    · rw [if_neg (fun h : a = y ∧ τ a = z => hzb h.2.symm),
        if_neg (fun h : τ a = y ∧ a = z => hza h.2.symm),
        if_neg (fun h : z = a ∨ z = τ a => h.elim hza hzb), ite_self, add_zero]

/-- **THE TRANSITION FLOW ON A MOVED PAIR IS AN ORBIT MATRIX**: `cos s` on the pair's diagonal,
`−i sin s` between the two, the identity elsewhere. -/
theorem flow_transition_eq_orb {a : S} (ha : τ a ≠ a) (hτ : ∀ z, τ (τ z) = z) (s : ℝ) :
    ReachabilitySeam.flow (transition a (τ a)) s
      = orb τ (fun z => if z = a ∨ z = τ a then (Real.cos s : ℂ) else 1)
          (fun z => if z = a ∨ z = τ a then -((Real.sin s : ℂ) * Complex.I) else 0) := by
  have hab : a ≠ τ a := Ne.symm ha
  rw [flow_transition_closedForm hab, one_eq_orb τ, pairProj_eq_orb τ hab, transition_eq_orb τ ha hτ,
    orb_smul, orb_smul, orb_add, orb_sub]
  refine orb_ext τ (fun z => ?_) (fun z _ => ?_)
  · by_cases hz : z = a ∨ z = τ a
    · simp only [hz, if_true]; ring
    · simp only [hz, if_false]; ring
  · by_cases hz : z = a ∨ z = τ a
    · simp only [hz, if_true]; ring
    · simp only [hz, if_false]; ring

end Orbit

section Isolation

variable {S : Type} [Fintype S] [DecidableEq S]

/-- The lower representative of a moved orbit outside the chosen pair `{a, τ a}`: below its image
in a fixed enumeration `e` of the configurations. -/
noncomputable def signFun (τ : Equiv.Perm S) (e : S ≃ Fin (Fintype.card S)) (a z : S) : ℂ :=
  if τ z ≠ z ∧ ¬ (z = a ∨ z = τ a) ∧ e z < e (τ z) then -1 else 1

/-- The phase `e^{-iπt}` on the moved configurations, `1` on the fixed ones. -/
noncomputable def phaseFun (τ : Equiv.Perm S) (t : ℝ) (z : S) : ℂ :=
  if τ z = z then 1 else Complex.exp (-((Real.pi : ℂ) * Complex.I * (t : ℂ)))

variable {τ : Equiv.Perm S}

theorem signFun_sq (e : S ≃ Fin (Fintype.card S)) (a z : S) :
    signFun τ e a z * signFun τ e a z = 1 := by
  unfold signFun
  split_ifs <;> norm_num

theorem signFun_star (e : S ≃ Fin (Fintype.card S)) (a z : S) :
    star (signFun τ e a z) * signFun τ e a z = 1 := by
  unfold signFun
  split_ifs <;> simp

/-- **THE SIGN PRODUCT ALONG AN ORBIT**: `−1` on a moved orbit outside the chosen pair, `1` on the
chosen pair and on the fixed configurations. -/
theorem signFun_mul (hτ : ∀ z, τ (τ z) = z) (e : S ≃ Fin (Fintype.card S)) {a : S} (_ha : τ a ≠ a)
    (z : S) :
    signFun τ e a (τ z) * signFun τ e a z
      = if τ z ≠ z ∧ ¬ (z = a ∨ z = τ a) then -1 else 1 := by
  by_cases hz : τ z = z
  · have h1 : ¬ (τ z ≠ z ∧ ¬ (z = a ∨ z = τ a)) := fun h => h.1 hz
    rw [if_neg h1, hz, signFun_sq]
  · by_cases hc : z = a ∨ z = τ a
    · have h1 : ¬ (τ z ≠ z ∧ ¬ (z = a ∨ z = τ a)) := fun h => h.2 hc
      rw [if_neg h1]
      have hz1 : signFun τ e a z = 1 := by
        unfold signFun
        rw [if_neg (fun h => h.2.1 hc)]
      have hz2 : signFun τ e a (τ z) = 1 := by
        unfold signFun
        rw [if_neg (fun h => h.2.1 (hc.elim (fun h' => Or.inr (by rw [h']))
          (fun h' => Or.inl (by rw [h', hτ]))))]
      rw [hz1, hz2, mul_one]
    · rw [if_pos (⟨hz, hc⟩ : τ z ≠ z ∧ ¬ (z = a ∨ z = τ a))]
      have hτz : τ z ≠ z := hz
      have hcτ : ¬ (τ z = a ∨ τ z = τ a) := by
        rintro (h | h)
        · exact hc (Or.inr (by rw [← h, hτ]))
        · exact hc (Or.inl (by rw [← hτ z, h, hτ]))
      have hne : e z ≠ e (τ z) := fun h => hz (e.injective h).symm
      have hττ : τ (τ z) ≠ τ z := by rw [hτ]; exact fun h => hz h.symm
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · have hz1 : signFun τ e a z = -1 := by
          unfold signFun; rw [if_pos ⟨hτz, hc, hlt⟩]
        have hz2 : signFun τ e a (τ z) = 1 := by
          unfold signFun
          rw [if_neg (fun h => ?_)]
          rw [hτ] at h
          exact lt_asymm hlt h.2.2
        rw [hz1, hz2]; norm_num
      · have hz1 : signFun τ e a z = 1 := by
          unfold signFun; rw [if_neg (fun h => lt_asymm hgt h.2.2)]
        have hz2 : signFun τ e a (τ z) = -1 := by
          unfold signFun
          rw [if_pos ⟨hττ, hcτ, by rw [hτ]; exact hgt⟩]
        rw [hz1, hz2]; norm_num

omit [Fintype S] in
theorem phaseFun_star (t : ℝ) (z : S) : star (phaseFun τ t z) * phaseFun τ t z = 1 := by
  unfold phaseFun
  split_ifs
  · simp
  · rw [Complex.star_def, ← Complex.exp_conj, ← Complex.exp_add]
    have : (starRingEnd ℂ) (-((Real.pi : ℂ) * Complex.I * (t : ℂ))) + -((Real.pi : ℂ) * Complex.I * (t : ℂ)) = 0 := by
      simp only [map_neg, map_mul, Complex.conj_ofReal, Complex.conj_I]
      ring
    rw [this, Complex.exp_zero]

/-- **THE ISOLATION IDENTITY.** The phase, the gate flow, and the gate flow conjugated by the
sign of the non-chosen orbits multiply to the transition flow on the chosen pair at angle `πt`:
on every other moved orbit the two rotations cancel, on the fixed configurations nothing moves,
and the phase removes the scalar the cancellation leaves. -/
theorem gateFlow_isolation (hτ : ∀ z, τ (τ z) = z) {a : S} (ha : τ a ≠ a)
    (e : S ≃ Fin (Fintype.card S)) (t : ℝ) :
    Matrix.diagonal (phaseFun τ t) * gateFlow τ t
        * (Matrix.diagonal (signFun τ e a) * gateFlow τ t * Matrix.diagonal (signFun τ e a))
      = ReachabilitySeam.flow (transition a (τ a)) (Real.pi * t) := by
  rw [gateFlow_eq_orb τ t, diagonal_mul_orb_mul_diagonal, diagonal_mul_orb, orb_mul τ hτ,
    flow_transition_eq_orb τ ha hτ]
  set e₁ := Complex.exp ((Real.pi : ℂ) * Complex.I * (t : ℂ)) with he₁
  set e₂ := Complex.exp (-((Real.pi : ℂ) * Complex.I * (t : ℂ))) with he₂
  have he : e₁ * e₂ = 1 := by
    rw [he₁, he₂, ← Complex.exp_add, add_neg_cancel, Complex.exp_zero]
  have h1 : e₁ = (Real.cos (Real.pi * t) : ℂ) + (Real.sin (Real.pi * t) : ℂ) * Complex.I := by
    rw [he₁, show (Real.pi : ℂ) * Complex.I * (t : ℂ) = ((Real.pi * t : ℝ) : ℂ) * Complex.I by
      push_cast; ring, Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin]
  have h2 : e₂ = (Real.cos (Real.pi * t) : ℂ) - (Real.sin (Real.pi * t) : ℂ) * Complex.I := by
    rw [he₂, show -((Real.pi : ℂ) * Complex.I * (t : ℂ)) = ((-(Real.pi * t) : ℝ) : ℂ) * Complex.I by
      push_cast; ring, Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin, Real.cos_neg,
      Real.sin_neg]
    push_cast
    ring
  have hcos : (Real.cos (Real.pi * t) : ℂ) = (e₁ + e₂) * (2 : ℂ)⁻¹ := by rw [h1, h2]; ring
  have hsin : (Real.sin (Real.pi * t) : ℂ) * Complex.I = (e₁ - e₂) * (2 : ℂ)⁻¹ := by
    rw [h1, h2]; ring
  refine orb_ext τ (fun z => ?_) (fun z hz => ?_)
  · -- the diagonal coefficient
    by_cases hz : τ z = z
    · have hc : ¬ (z = a ∨ z = τ a) := by
        rintro (h | h)
        · exact ha (by rw [← h]; exact hz)
        · have h' := hz
          rw [h, hτ] at h'
          exact ha h'.symm
      have hs2 := signFun_sq (τ := τ) e a z
      simp only [phaseFun, hz, hc, if_true, if_false, ne_eq, not_true_eq_false, false_and, and_false,
        add_zero, one_mul, mul_one]
      linear_combination hs2
    · have hz' : τ z ≠ z := hz
      have hz2 : ¬ z = τ z := fun h => hz h.symm
      have hs := signFun_mul hτ e ha z
      have hs2 := signFun_sq (τ := τ) e a z
      have hτz : τ (τ z) ≠ τ z := by rw [hτ]; exact fun h => hz h.symm
      by_cases hc : z = a ∨ z = τ a
      · rw [if_pos hc]
        have h1' : ¬ (τ z ≠ z ∧ ¬ (z = a ∨ z = τ a)) := fun h => h.2 hc
        rw [if_neg h1'] at hs
        simp only [phaseFun, hz, hz', hz2, hτz, if_true, if_false, hτ, ne_eq, not_false_eq_true]
        rw [hcos, ← he₂]
        linear_combination (e₂ * (1 + (e₁ - 1) * 2⁻¹) ^ 2) * hs2
          + (e₂ * ((e₁ - 1) * 2⁻¹) ^ 2) * hs + (e₁ * 2⁻¹) * he
      · rw [if_neg hc]
        rw [if_pos (⟨hz', hc⟩ : τ z ≠ z ∧ ¬ (z = a ∨ z = τ a))] at hs
        simp only [phaseFun, hz, hz', hz2, hτz, if_true, if_false, hτ, ne_eq, not_false_eq_true]
        rw [← he₂]
        linear_combination (e₂ * (1 + (e₁ - 1) * 2⁻¹) ^ 2) * hs2
          + (e₂ * ((e₁ - 1) * 2⁻¹) ^ 2) * hs + he
  · -- the antidiagonal coefficient, on a moved configuration
    have hs := signFun_mul hτ e ha z
    have hs2 := signFun_sq (τ := τ) e a z
    have hτz : τ (τ z) ≠ τ z := by rw [hτ]; exact fun h => hz h.symm
    have hzz : ¬ (τ z = z) := hz
    have hz2 : ¬ z = τ z := fun h => hz h.symm
    by_cases hc : z = a ∨ z = τ a
    · rw [if_pos hc]
      have h1' : ¬ (τ z ≠ z ∧ ¬ (z = a ∨ z = τ a)) := fun h => h.2 hc
      rw [if_neg h1'] at hs
      simp only [phaseFun, hzz, hz, hz2, hτz, if_true, if_false, hτ, ne_eq, not_false_eq_true]
      rw [hsin, ← he₂]
      linear_combination (-(e₂ * ((e₁ - 1) * 2⁻¹) * (1 + (e₁ - 1) * 2⁻¹))) * hs2
        + (-(e₂ * ((e₁ - 1) * 2⁻¹) * (1 + (e₁ - 1) * 2⁻¹))) * hs + (-(e₁ * 2⁻¹)) * he
    · rw [if_neg hc]
      rw [if_pos (⟨hz, hc⟩ : τ z ≠ z ∧ ¬ (z = a ∨ z = τ a))] at hs
      simp only [phaseFun, hzz, hz, hz2, hτz, if_true, if_false, hτ, ne_eq, not_false_eq_true]
      rw [← he₂]
      linear_combination (-(e₂ * ((e₁ - 1) * 2⁻¹) * (1 + (e₁ - 1) * 2⁻¹))) * hs2
        + (-(e₂ * ((e₁ - 1) * 2⁻¹) * (1 + (e₁ - 1) * 2⁻¹))) * hs

end Isolation

/-! ### Section D — Q3 and Q4: from executability to phase-free richness, and the endpoint -/

section Bridge

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **WHAT THE SUBSTRATUM SUPPLIES**: a theory carries the substratum theory's availability. -/
def SubstratumAvail (T : FiniteOperationalTheory S) : Prop :=
  ∀ (n : ℕ) (O : Type) [Fintype O] [DecidableEq O]
    (F : O → Matrix (S × Fin n) (S × Fin n) ℂ →ₗ[ℂ] Matrix (S × Fin n) (S × Fin n) ℂ),
    (substratumTheory S).availExt n O F → T.availExt n O F

theorem substratumTheory_substratumAvail : SubstratumAvail (substratumTheory S) :=
  fun _ _ _ _ _ h => h

/-- A diagonal unitary is available wherever the substratum's phases are. -/
theorem diagonal_avail (T : FiniteOperationalTheory S) (hsub : SubstratumAvail T) (n : ℕ)
    (d : S × Fin n → ℂ) (hd : ∀ p, star (d p) * d p = 1) :
    T.availExt n Unit (fun _ => conjChannel (Matrix.diagonal d)) := by
  refine hsub n Unit _ (substratumTheory_avail_conj (monomial_diagonal d) ?_)
  rw [Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
  congr 1
  funext p
  exact hd p

theorem conjChannel_comp_conjChannel {l : Type} [Fintype l] [DecidableEq l] (V W : Matrix l l ℂ) :
    (conjChannel V).comp (conjChannel W) = conjChannel (V * W) := by
  refine LinearMap.ext fun X => ?_
  show V * (W * X * Wᴴ) * Vᴴ = V * W * X * (V * W)ᴴ
  rw [Matrix.conjTranspose_mul]
  simp only [Matrix.mul_assoc]

theorem avail_conj_mul (T : FiniteOperationalTheory S) (n : ℕ)
    {V W : Matrix (S × Fin n) (S × Fin n) ℂ}
    (hV : T.availExt n Unit (fun _ => conjChannel V)) (hW : T.availExt n Unit (fun _ => conjChannel W)) :
    T.availExt n Unit (fun _ => conjChannel (V * W)) := by
  have h := availExt_comp_unit T n (conjChannel W) (conjChannel V) hW hV
  rwa [conjChannel_comp_conjChannel] at h

/-- **Q3 — EXECUTABLE LAYER FLOWS GIVE PHASE-FREE RICHNESS.** In a theory that carries the
substratum's availability, executability of the layer flow of an involution with a moved
configuration supplies, at every level, every transition flow between a moved configuration and
its image: the isolation identity writes that flow as a product of the phase, the gate flow, and
the sign-conjugated gate flow, each available. -/
theorem phaseFree_of_layerFlowExecutable (T : FiniteOperationalTheory S) (hsub : SubstratumAvail T)
    {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x) {x : S} (hx : σ x ≠ x)
    (hex : LayerFlowExecutable T σ) : PhaseFreeRichness T := by
  intro n hn
  have hn0 : 0 < n := by
    rcases Nat.eq_zero_or_pos n with h | h
    · subst h
      simp at hn
    · exact h
  set τ := levelPerm σ n with hτdef
  have hτ : ∀ p, τ (τ p) = p := levelPerm_involutive hσ n
  have ha : τ (x, ⟨0, hn0⟩) ≠ (x, ⟨0, hn0⟩) := by
    rw [hτdef, levelPerm_apply]
    intro h
    exact hx (Prod.mk.inj h).1
  refine ⟨⟨(x, ⟨0, hn0⟩), τ (x, ⟨0, hn0⟩), ha.symm, fun t => ?_⟩, fun a b _ => ?_⟩
  swap
  · exact hsub n Unit _ (substratumTheory_avail_conj (exchange_monomial a b) (permMatrix_isometry _))
  have hπ : Real.pi * (t / Real.pi) = t := mul_div_cancel₀ _ Real.pi_ne_zero
  rw [← hπ, ← gateFlow_isolation hτ ha (Fintype.equivFin _) (t / Real.pi)]
  have hu := hex n (t / Real.pi)
  have hD := diagonal_avail T hsub n (signFun τ (Fintype.equivFin _) (x, ⟨0, hn0⟩))
    (signFun_star _ _)
  have hP := diagonal_avail T hsub n (phaseFun τ (t / Real.pi)) (phaseFun_star _)
  exact avail_conj_mul T n (avail_conj_mul T n hP hu) (avail_conj_mul T n (avail_conj_mul T n hD hu) hD)

/-- **Q4 — THE ENDPOINT**: under the closure and the substratum's availability, exact quantum
mechanics is exactly the executability of one layer flow that moves a configuration. -/
theorem derivedOI_qm_iff_layerFlowExecutable [Nonempty S] (T : FiniteOperationalTheory S)
    (hd : DerivedOI T) (hsub : SubstratumAvail T) {σ : Equiv.Perm S} (hσ : ∀ x, σ (σ x) = x)
    {x : S} (hx : σ x ≠ x) :
    ExactAllFiniteEndomorphicQuantumOps T ↔ LayerFlowExecutable T σ :=
  ⟨fun hqm => layerFlowExecutable_of_control T (physical_of_exactAll T hqm).2.2.1 hσ,
    fun hex => (derivedOI_qm_iff_phaseFree hd).mpr (phaseFree_of_layerFlowExecutable T hsub hσ hx hex)⟩

end Bridge

/-! ### Section E — the swap layer of the second-order form, on a region -/

section SwapLayer

open OIBridge.SecondOrderDrive OIBridge.RegionTower

variable {ι : Type} [DecidableEq ι] {V : Type} [Fintype V] [DecidableEq V] [Nonempty V]
  [AddCommGroup V]

theorem regionSwap_involutive' (Λ : Finset ι) (f : Conf Λ (V × V)) :
    regionSwap V Λ (regionSwap V Λ f) = f :=
  regionSwap_involutive Λ f

omit [DecidableEq ι] in
/-- The swap layer moves a configuration as soon as the region is nonempty and the alphabet is
nontrivial. -/
theorem regionSwap_moves (Λ : Finset ι) (hΛ : Λ.Nonempty) [Nontrivial V] :
    ∃ f : Conf Λ (V × V), regionSwap V Λ f ≠ f := by
  obtain ⟨v, hv⟩ := exists_ne (0 : V)
  obtain ⟨u, hu⟩ := hΛ
  refine ⟨fun _ => (0, v), fun h => ?_⟩
  have h' := congrFun h ⟨u, hu⟩
  have h'' : ((v, 0) : V × V) = (0, v) := h'
  exact hv (Prod.mk.inj h'').1

/-- **Q2 FOR THE SWAP LAYER**: the substratum theory on a nonempty region with a nontrivial
alphabet does not derive the executability of its own swap layer. -/
theorem substratumTheory_not_layerFlowExecutable_swap (Λ : Finset ι) (hΛ : Λ.Nonempty)
    [Nontrivial V] :
    ¬ LayerFlowExecutable (substratumTheory (Conf Λ (V × V))) (regionSwap V Λ) := by
  obtain ⟨f, hf⟩ := regionSwap_moves Λ hΛ (V := V)
  exact substratumTheory_not_layerFlowExecutable hf

/-- **Q3 FOR THE SWAP LAYER.** -/
theorem phaseFree_of_layerFlowExecutable_swap (Λ : Finset ι) (hΛ : Λ.Nonempty) [Nontrivial V]
    (T : FiniteOperationalTheory (Conf Λ (V × V))) (hsub : SubstratumAvail T)
    (hex : LayerFlowExecutable T (regionSwap V Λ)) : PhaseFreeRichness T := by
  obtain ⟨f, hf⟩ := regionSwap_moves Λ hΛ (V := V)
  exact phaseFree_of_layerFlowExecutable T hsub (regionSwap_involutive' Λ) hf hex

/-- **Q4 FOR THE SWAP LAYER.** -/
theorem derivedOI_qm_iff_layerFlowExecutable_swap (Λ : Finset ι) (hΛ : Λ.Nonempty) [Nontrivial V]
    (T : FiniteOperationalTheory (Conf Λ (V × V))) (hd : DerivedOI T) (hsub : SubstratumAvail T) :
    ExactAllFiniteEndomorphicQuantumOps T ↔ LayerFlowExecutable T (regionSwap V Λ) := by
  obtain ⟨f, hf⟩ := regionSwap_moves Λ hΛ (V := V)
  exact derivedOI_qm_iff_layerFlowExecutable T hd hsub (regionSwap_involutive' Λ) hf

end SwapLayer

#print axioms levelPerm_apply
#print axioms levelPerm_involutive
#print axioms permMat_star
#print axioms gateFlow_unitary
#print axioms gateFlow_group
#print axioms gateFlow_zero
#print axioms gateFlow_one
#print axioms gateFlow_trace
#print axioms gateFlow_stage
#print axioms layerFlowExecutable_of_control
#print axioms exp_pi_I_half
#print axioms permMat_apply_self
#print axioms permMat_apply_moved
#print axioms gateFlow_half_entries
#print axioms gateFlow_half_not_preservesDiag
#print axioms configurationLevel_not_layerFlowExecutable
#print axioms substratumTheory_not_layerFlowExecutable
#print axioms exp_smul_idempotent
#print axioms transition_mul_transition
#print axioms pairProj_mul_transition
#print axioms transition_mul_pairProj
#print axioms pairProj_mul_pairProj
#print axioms flow_transition_closedForm
#print axioms orb_apply
#print axioms orb_ext
#print axioms sum_mul_ite_eq
#print axioms sum_mul_ite_and_eq
#print axioms orb_mul
#print axioms one_eq_orb
#print axioms diagonal_eq_orb
#print axioms permMat_eq_orb
#print axioms orb_add
#print axioms orb_sub
#print axioms orb_smul
#print axioms gateFlow_eq_orb
#print axioms diagonal_mul_orb_mul_diagonal
#print axioms diagonal_mul_orb
#print axioms pairProj_eq_orb
#print axioms transition_eq_orb
#print axioms flow_transition_eq_orb
#print axioms signFun_sq
#print axioms signFun_star
#print axioms signFun_mul
#print axioms phaseFun_star
#print axioms gateFlow_isolation
#print axioms substratumTheory_substratumAvail
#print axioms diagonal_avail
#print axioms conjChannel_comp_conjChannel
#print axioms avail_conj_mul
#print axioms phaseFree_of_layerFlowExecutable
#print axioms derivedOI_qm_iff_layerFlowExecutable
#print axioms regionSwap_involutive'
#print axioms regionSwap_moves
#print axioms substratumTheory_not_layerFlowExecutable_swap
#print axioms phaseFree_of_layerFlowExecutable_swap
#print axioms derivedOI_qm_iff_layerFlowExecutable_swap

end LiftAudit
end OIBridge
