import OIBridge.ExecSource
import OIBridge.CoherentExtension

/-!
# The lift-source audit — can the observer-level lift be formulated so that it supplies an
admissible intervention?

The preregistered pass of `LIFT-SOURCE-AUDIT.md`. The census of the corpus's formulations of the
lift is in the note; the kernel content is the tests of the formulations that land in the
operational interface, and the countermodel to the generator reading.

* T1, the diagonal criterion: a theory every one of whose available families preserves diagonal
  states executes no layer flow of an involution with a moved configuration
  (`not_layerFlowExecutable_of_preservesDiag`).
* T2, the coherent completion: the reversible coherent lift of a permutation with unimodular
  phases is monomial (`coherentLift_isMonomial`); the reversible coherent extension of a
  permutation is conjugation by a monomial isometry (`reversibleExtension_conj_monomial`); every
  member of the correlation family, reversible or not, preserves diagonal states
  (`correlationExtension_preservesDiag`); the class of the substratum's operators together with
  every reversible coherent lift of every permutation is configuration-level, is the substratum
  class, has the substratum's architecture and generates the substratum theory
  (`coherentLiftClass_contains_lift`, `coherentLiftClass_configurationLevel`,
  `coherentLiftClass_eq_substratumClass`, `coherentLiftClass_arch`,
  `coherentLiftTheory_eq_substratumTheory`), so it executes no layer flow of an involution with a
  moved configuration (`coherentLiftClass_not_layerFlowExecutable`); the observer theory of every
  substratum lies inside it (`obs_availExt_le_coherentLift`), and the wave substratum's
  lift-extended theory does not execute its own swap-layer flow
  (`waveSubstratum_coherentLift_not_layerFlowExecutable_swap`).
* T3, the projected observer operator: a scaled matrix unit is monomial (`single_isMonomial`);
  the explicit Kraus form of a classical stochastic map has monomial Kraus operators and the channel
  preserves diagonal states (`stochasticChannel_kraus_monomial`, `stochasticChannel_preservesDiag`); a theory
  generated by a class of monomials and scaled matrix units executes no layer flow of an
  involution with a moved configuration (`stochastic_not_layerFlowExecutable`).
* T4, the generator reading: the substratum theory has the gate of every involution available at
  time one at every level and executes its flow at no level when the involution moves a
  configuration (`avail_one_not_layerFlowExecutable`); the observer theory of every substratum
  has its swap layer available at time one and executes its flow at no level when the swap layer
  moves a configuration (`obs_swap_avail_one_not_layerFlowExecutable`).

Not claimed: that the wave-operator lift on the amplitude space is or is not derivable, or that a
map from it to the configuration carrier exists or does not; that every implementation of a
nonreversible coherent completion, or every Kraus realization of the stochastic channel, is
configuration-level, the reversible members being proved monomial and one monomial realization of
the channel exhibited; that any non-monomial admissible
operator yields the gate flow of a layer; anything about the phase; anything about a richer
observer architecture than the stated one; anything about a manuscript.
-/

namespace OIBridge
namespace LiftSource

open Complex Matrix CoherentLift SpectatorBridge OperationalAssembly AncillaClosure
open MonoidalCompletion InterventionLocality MicroReversibility PrimitiveSource LieRankSource
open DiagonalTheory SubstratumInterface StructuralClosure MinimalRepertoire LevelOneSeam
open PhysicalCharacterization RouteB ManuscriptAxioms LiftAudit SubstratumInterfaceAudit
open InstrumentRealization SecondOrderCircuit CoherentExtension ExecSource
open scoped ComplexOrder

local notation "conj'" => (starRingEnd ℂ)

/-! ### Section A — T1: the diagonal criterion -/

section Criterion

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T1 — DIAGONAL PRESERVATION EXCLUDES EXECUTABILITY**: a theory every one of whose available
families preserves diagonal states at every level executes no layer flow of an involution with
a moved configuration, the flow at time one half not preserving them. -/
theorem not_layerFlowExecutable_of_preservesDiag (T : FiniteOperationalTheory S)
    (h : ∀ (n : ℕ) (O : Type) [Fintype O] [DecidableEq O]
      (F : O → Matrix (S × Fin n) (S × Fin n) ℂ →ₗ[ℂ] Matrix (S × Fin n) (S × Fin n) ℂ),
      T.availExt n O F → ∀ o, PreservesDiag (F o))
    {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) : ¬ LayerFlowExecutable T σ := by
  intro hex
  have hx' : levelPerm σ 1 (x, 0) ≠ (x, 0) := by
    rw [levelPerm_apply]
    intro hc
    exact hx (Prod.mk.inj hc).1
  exact gateFlow_half_not_preservesDiag hx' (h 1 Unit _ (hex 1 (1 / 2 : ℝ)) ())

end Criterion

/-! ### Section B — T2: the coherent completion -/

section Coherent

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T2(a) — THE REVERSIBLE COHERENT LIFT IS MONOMIAL**: `D · P_g = P_g · D'`. -/
theorem coherentLift_isMonomial (g : Equiv.Perm S) (d : S → ℂ) :
    IsMonomial (Matrix.diagonal (fun a => d (g.symm a)) * permMatrix g) := by
  refine ⟨g, d, ?_⟩
  ext i j
  rw [monomial_entry]
  simp only [Matrix.diagonal_mul, permMatrix]
  by_cases h : g j = i
  · rw [if_pos h, if_pos h, ← h, Equiv.symm_apply_apply, mul_one]
  · rw [if_neg h, if_neg h, mul_zero]

/-- **T2(b) — THE REVERSIBLE COHERENT EXTENSION IS A MONOMIAL CONJUGATION**: a member of the
correlation family with a CPTP left inverse is conjugation by a monomial isometry. -/
theorem reversibleExtension_conj_monomial [Nonempty S] (g : Equiv.Perm S)
    (C : Matrix S S ℂ) (hpsd : C.PosSemidef) (hdiag : ∀ s, C s s = 1)
    (hrev : ∃ Ψ : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ, IsCPTP Ψ
        ∧ Ψ.comp (correlationExtension g C) = LinearMap.id) :
    ∃ K : Matrix S S ℂ, IsMonomial K ∧ Kᴴ * K = 1
      ∧ correlationExtension g C = conjChannel K := by
  obtain ⟨d, hd, hC⟩ := (reversibleExtension_iff_rankOne g C hpsd hdiag).1 hrev
  refine ⟨Matrix.diagonal (fun a => d (g.symm a)) * permMatrix g,
    coherentLift_isMonomial g d, ?_, ?_⟩
  · have hdd : (Matrix.diagonal (fun a => d (g.symm a)))ᴴ
        * Matrix.diagonal (fun a => d (g.symm a)) = 1 := by
      rw [Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
      congr 1
      funext i
      simp only [Pi.star_apply]
      rw [mul_comm, ← starRingEnd_apply]
      exact hd _
    rw [Matrix.conjTranspose_mul, Matrix.mul_assoc, ← Matrix.mul_assoc (Matrix.diagonal _)ᴴ,
      hdd, Matrix.one_mul, permMatrix_isometry]
  · have hC' : C = Matrix.of fun s t => d s * conj' (d t) := by
      ext s t
      rw [hC, Matrix.of_apply]
    apply LinearMap.ext
    intro X
    rw [conjChannel_apply, hC']
    exact rankOne_extension_monomial g d X

omit [Fintype S] in
/-- **T2(c) — EVERY COHERENT COMPLETION PRESERVES DIAGONAL STATES**, reversible or not: on
diagonal preparations the correlation matrix drops out (`correlationExtension_diagonal`). -/
theorem correlationExtension_preservesDiag (g : Equiv.Perm S) (C : Matrix S S ℂ)
    (hdiag : ∀ s, C s s = 1) : PreservesDiag (correlationExtension g C) :=
  fun w => ⟨fun a => w (g.symm a), correlationExtension_diagonal g C hdiag w⟩

end Coherent

section LiftClass

/-- **THE LIFT-EXTENDED CLASS**: the substratum's operators together with every reversible
coherent lift of every permutation, `D · P_g` with unimodular phases. -/
def coherentLiftClass : ImplementationClass := fun S _ _ K =>
  IsMonomial K ∨ ∃ (g : Equiv.Perm S) (d : S → ℂ), (∀ s, d s * conj' (d s) = 1)
    ∧ K = Matrix.diagonal (fun a => d (g.symm a)) * permMatrix g

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T7(c) — THE CLASS CONTAINS THE LIFTS IT IS NAMED FOR.** -/
theorem coherentLiftClass_contains_lift (g : Equiv.Perm S) (d : S → ℂ)
    (hd : ∀ s, d s * conj' (d s) = 1) :
    coherentLiftClass S (Matrix.diagonal (fun a => d (g.symm a)) * permMatrix g) :=
  Or.inr ⟨g, d, hd, rfl⟩

/-- **T2(d) — THE LIFT-EXTENDED CLASS IS CONFIGURATION-LEVEL.** -/
theorem coherentLiftClass_configurationLevel : ConfigurationLevel coherentLiftClass := by
  intro T _ _ K hK
  rcases hK with h | ⟨g, d, -, rfl⟩
  · exact h
  · exact coherentLift_isMonomial g d

/-- **T2(d) — ADJOINING THE COHERENT LIFTS ADDS NOTHING**: the lift-extended class is the
substratum class. -/
theorem coherentLiftClass_eq_substratumClass : coherentLiftClass = substratumClass := by
  funext T _ _ K
  exact propext ⟨fun h => coherentLiftClass_configurationLevel T K h, fun h => Or.inl h⟩

/-- The lift-extended class is an architecture. -/
theorem coherentLiftClass_arch : Architecture coherentLiftClass := by
  rw [coherentLiftClass_eq_substratumClass]
  exact substratumClass_arch

/-- **THE LIFT-EXTENDED THEORY**: what the substratum's operators and the coherent lifts
generate through the observer architecture. -/
noncomputable def coherentLiftTheory (S : Type) [Fintype S] [DecidableEq S] :
    FiniteOperationalTheory S :=
  genTheory coherentLiftClass coherentLiftClass_arch S

/-- **T2(d) — THE LIFT-EXTENDED THEORY IS THE SUBSTRATUM THEORY.** -/
theorem coherentLiftTheory_eq_substratumTheory : coherentLiftTheory S = substratumTheory S := by
  unfold coherentLiftTheory substratumTheory
  congr 1
  exact coherentLiftClass_eq_substratumClass

/-- **T2(d) — THE LIFT-EXTENDED THEORY EXECUTES NO LAYER FLOW** of an involution with a moved
configuration. -/
theorem coherentLiftClass_not_layerFlowExecutable {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) :
    ¬ LayerFlowExecutable (coherentLiftTheory S) σ :=
  configurationLevel_not_layerFlowExecutable coherentLiftClass_arch
    coherentLiftClass_configurationLevel hx

end LiftClass

section Observer

variable (𝒮 : Substratum) [Fintype 𝒮.ι] [Fintype 𝒮.V] [DecidableEq 𝒮.V]

/-- **THE OBSERVER THEORY LIES INSIDE THE LIFT-EXTENDED THEORY**: the stated access together
with the coherent lifts is what the lift-extended theory carries. -/
theorem obs_availExt_le_coherentLift {n : ℕ} {O : Type} [Fintype O] [DecidableEq O]
    (F : O → Matrix (𝒮.Conf × Fin n) (𝒮.Conf × Fin n) ℂ →ₗ[ℂ]
      Matrix (𝒮.Conf × Fin n) (𝒮.Conf × Fin n) ℂ)
    (hF : (obsTheory 𝒮).availExt n O F) : (coherentLiftTheory 𝒮.Conf).availExt n O F := by
  rw [coherentLiftTheory_eq_substratumTheory]
  exact obs_availExt_le_substratum 𝒮 F hF

end Observer

section Wave

variable (d L q : ℕ)

/-- **T2(e) — THE WAVE SUBSTRATUM'S LIFT-EXTENDED THEORY DOES NOT EXECUTE ITS OWN SWAP-LAYER
FLOW**, for every nontrivial alphabet. -/
theorem waveSubstratum_coherentLift_not_layerFlowExecutable_swap [NeZero L] [NeZero q]
    [Fact (1 < q)] (α : ZMod q) :
    ¬ LayerFlowExecutable (coherentLiftTheory (waveSubstratum d L q α).Conf)
      (swapEquiv : (waveSubstratum d L q α).Conf ≃ (waveSubstratum d L q α).Conf) := by
  obtain ⟨x, hx⟩ := waveSubstratum_swap_moves d L q α
  exact coherentLiftClass_not_layerFlowExecutable hx

end Wave

/-! ### Section C — T3: the projected observer operator -/

section Stochastic

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T3(a) — A SCALED MATRIX UNIT IS MONOMIAL**: `c · E_{ik} = P_{(i k)} · diag(c · 1_k)`. -/
theorem single_isMonomial (c : ℂ) (i k : S) : IsMonomial (c • Matrix.single i k 1) := by
  refine ⟨Equiv.swap i k, fun j => if j = k then c else 0, ?_⟩
  ext a b
  rw [monomial_entry, Matrix.smul_apply, Matrix.single_apply, smul_eq_mul]
  by_cases hb : b = k
  · subst hb
    rw [Equiv.swap_apply_right]
    by_cases ha : i = a
    · subst ha
      simp
    · simp [ha]
  · have hkb : k ≠ b := fun h => hb h.symm
    simp [hb, hkb]

/-- **THE KRAUS FORM OF A CLASSICAL STOCHASTIC MAP**: `X ↦ Σ_{i,k} A_{ik} E_{ik} X E_{ki}`, the
operation the projected observer evolution `p ↦ A p` names on states. -/
noncomputable def stochasticChannel (A : S → S → ℝ) : Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ :=
  ∑ p : S × S, conjChannel (((Real.sqrt (A p.1 p.2) : ℝ) : ℂ) • Matrix.single p.1 p.2 1)

/-- **T3(b) — ITS KRAUS OPERATORS ARE MONOMIAL.** -/
theorem stochasticChannel_kraus_monomial (A : S → S → ℝ) (p : S × S) :
    IsMonomial (((Real.sqrt (A p.1 p.2) : ℝ) : ℂ) • Matrix.single p.1 p.2 1) :=
  single_isMonomial _ _ _

/-- **T3(b) — IT PRESERVES DIAGONAL STATES.** -/
theorem stochasticChannel_preservesDiag (A : S → S → ℝ) : PreservesDiag (stochasticChannel A) :=
  preservesDiag_sum _ _ fun p _ =>
    preservesDiag_conj_of_monomial (stochasticChannel_kraus_monomial A p)

/-- **T3(c) — A THEORY OF CLASSICAL MAPS OVER THE STATED ACCESS EXECUTES NO LAYER FLOW**: a
class of monomials and scaled matrix units is configuration-level. -/
theorem stochastic_not_layerFlowExecutable {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
    (h : ∀ (T : Type) [Fintype T] [DecidableEq T] (K : Matrix T T ℂ), 𝓘 T K →
      IsMonomial K ∨ ∃ (c : ℂ) (i k : T), K = c • Matrix.single i k 1)
    {σ : Equiv.Perm S} {x : S} (hx : σ x ≠ x) : ¬ LayerFlowExecutable (genTheory 𝓘 arch S) σ := by
  refine configurationLevel_not_layerFlowExecutable arch ?_ hx
  intro T _ _ K hK
  rcases h T K hK with hm | ⟨c, i, k, rfl⟩
  · exact hm
  · exact single_isMonomial c i k

end Stochastic

/-! ### Section D — T4: the generator reading -/

section Generator

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **T4 — A GENERATOR WITH ITS TIME-ONE EXPONENTIAL AVAILABLE DOES NOT MAKE THE FLOW
EXECUTABLE**: for every involution with a moved configuration, the substratum theory has the gate
at time one available at every level and executes the flow at no level. -/
theorem avail_one_not_layerFlowExecutable {σ : Equiv.Perm S} (hσ : ∀ y, σ (σ y) = y) {x : S}
    (hx : σ x ≠ x) :
    (∀ n, (substratumTheory S).availExt n Unit
        (fun _ => conjChannel (gateFlow (levelPerm σ n) 1)))
      ∧ ¬ LayerFlowExecutable (substratumTheory S) σ := by
  refine ⟨fun n => ?_, substratumTheory_not_layerFlowExecutable hx⟩
  rw [gateFlow_one (levelPerm_involutive hσ n)]
  exact substratumTheory_avail_conj (monomial_permMatrix _) (permMatrix_isometry _)

end Generator

section ObserverGenerator

variable (𝒮 : Substratum) [Fintype 𝒮.ι] [Fintype 𝒮.V] [DecidableEq 𝒮.V]

/-- **T4 — THE SAME FOR THE OBSERVER THEORY AT ITS OWN SWAP LAYER**: available at time one at
every level, its flow executed at no level when the layer moves a configuration. -/
theorem obs_swap_avail_one_not_layerFlowExecutable {x : 𝒮.Conf}
    (hx : (swapEquiv : 𝒮.Conf ≃ 𝒮.Conf) x ≠ x) :
    (∀ n, (obsTheory 𝒮).availExt n Unit
        (fun _ => conjChannel (gateFlow (levelPerm (swapEquiv : 𝒮.Conf ≃ 𝒮.Conf) n) 1)))
      ∧ ¬ LayerFlowExecutable (obsTheory 𝒮) (swapEquiv : 𝒮.Conf ≃ 𝒮.Conf) := by
  refine ⟨fun n => ?_, obs_not_layerFlowExecutable_swap 𝒮 hx⟩
  rw [gateFlow_one (levelPerm_involutive (fun _ => rfl) n)]
  exact obs_swap_avail 𝒮 n

end ObserverGenerator

/-! ### Axiom check -/

#print axioms not_layerFlowExecutable_of_preservesDiag
#print axioms coherentLift_isMonomial
#print axioms reversibleExtension_conj_monomial
#print axioms correlationExtension_preservesDiag
#print axioms coherentLiftClass_contains_lift
#print axioms coherentLiftClass_configurationLevel
#print axioms coherentLiftClass_eq_substratumClass
#print axioms coherentLiftClass_arch
#print axioms coherentLiftTheory_eq_substratumTheory
#print axioms coherentLiftClass_not_layerFlowExecutable
#print axioms obs_availExt_le_coherentLift
#print axioms waveSubstratum_coherentLift_not_layerFlowExecutable_swap
#print axioms single_isMonomial
#print axioms stochasticChannel_kraus_monomial
#print axioms stochasticChannel_preservesDiag
#print axioms stochastic_not_layerFlowExecutable
#print axioms avail_one_not_layerFlowExecutable
#print axioms obs_swap_avail_one_not_layerFlowExecutable

end LiftSource
end OIBridge
