import OIBridge.RouteB

/-!
# The manuscript-axiom audit — A1–A6 against the substratum witness

Route B1 (`RouteB.routeB_target`) exhibits `substratumTheory (Fin 2)`, the theory generated by the
monomial class, as a two-state theory satisfying `DerivedOICore` and failing phase-free richness.
`DerivedOI` is the kernel's closure; the manuscripts' own structural assumptions are A1–A6 of
`[Substratum §3.1]`: finiteness of the configuration space, bijectivity of the dynamics, bounded
coupling degree, center independence, linearity of the wave equation, background independence.
This file is the preregistered pass of `MANUSCRIPT-AXIOM-AUDIT.md`: each axiom is tested against
the witness through its realized-core image where one exists, and recorded as a formalization
gap where none does.

## What the theorems are images of

Every one of A1–A6 is a condition on a substratum `(S, φ)`. A `FiniteOperationalTheory (Fin 2)`
has no distinguished underlying substratum. What it carries is the sealed OI core, `Core` with the
dynamics `sigmaPerm`, embedded at level four by `coreIdx` and realized by the theory, and nothing
in the interface identifies that core with a manuscript substratum's `S` and `φ`. So no
manuscript-level conjunct of A1–A6 is presently a faithful predicate of the bare theory. A1 and
A2 have exact **realized-core images**: the core is finite (`A1Realized`), and its dynamics and
inverse are one-outcome transported permutation channels (`A2Realized`). Both images hold for the
witness (`substratumTheory_A1`, `substratumTheory_A2`); A1's holds for every theory by the
interface's types (`a1_every_theory`), and A2's for every theory with composite unitary control
(`a2_of_control`). They are images, not the axioms: at the substratum level A1 and A2 are
formalization gaps like the rest, absent a sourcing or identification map from `(S, φ)` into the
theory. A3–A6 additionally need a site type, a coupling graph with a uniform degree bound,
lattice translations, an additive alphabet with an additive update rule, and internal indices
with a coupling matrix; the interface has none of these, and no weakened predicate is defined for
them. The conjunction of the two images is `A1A2Realized`; it is not the manuscript OI and is not
named so.

## The configuration-level sourcing bound

The kernel's only sourcing of operations from a substratum is configuration-level: the
interface assigns the substratum's direct interventions, bijections of its configurations and
phases, monomial operators. For any implementation architecture all of whose admissible
operators are monomial (`ConfigurationLevel`), the generated theory's availability is contained
in the substratum theory's (`configurationLevel_availExt_le`), the falsifier `rot` is unavailable
on the two-state carrier (`configurationLevel_falsifierUnavailable`), and, when the class is
label-invariant (configuration relabelling is gauge), the generated theory fails phase-free
richness and is not exact finite operational quantum mechanics
(`configurationLevel_not_phaseFree`, `configurationLevel_not_qm`). The substratum class is the
largest configuration-level architecture (`substratumClass_configurationLevel`,
`configurationLevel_iff_le_substratum`).

These are theorems about the theories generated by implementation classes. The kernel has no map
from a substratum to an implementation class, so they bound every sourcing that factors through
a configuration-level class, and say nothing about sourcings that do not. The reading, fixed in
the audit note before the proof and narrowed at review: phase-free richness requires some
sourcing that is not configuration-level; the observer-level lift `φ → L_obs`, whose derivation
the manuscripts record as open, is their specifically named candidate for one, and nothing here
says whether it is derivable or whether it is the only such route.
-/

namespace OIBridge
namespace ManuscriptAxioms

open Complex Matrix CoherentLift CoherentExtension SpectatorBridge OperationalAssembly
open AncillaClosure MonoidalCompletion InterventionLocality MicroReversibility PrimitiveSource
open LieRankSource DiagonalTheory SubstratumInterface StructuralClosure MinimalRepertoire
open LevelOneSeam PhysicalCharacterization OIRealization IndependenceCensus RouteB

/-! ### Section A — the realized-core images of A1 and A2 -/

section Representable

/-- **THE REALIZED-CORE IMAGE OF A1**: the configuration space of the realized core is finite.
The core has eight states, and every level of the theory is a finite type of `2 n` states. The
predicate does not depend on the theory: it is carried by the interface's types. It is an image
of A1, not A1: nothing identifies the core with a manuscript substratum's `S`. -/
def A1Realized (_T : FiniteOperationalTheory (Fin 2)) : Prop :=
  Fintype.card Core = 8 ∧ ∀ n : ℕ, Fintype.card (Fin 2 × Fin n) = 2 * n

/-- **THE REALIZED-CORE IMAGE OF A2**: the realized dynamics `sigmaPerm` is a bijection of the
core, realized as a one-outcome (deterministic) transported permutation channel at level four,
and its inverse is realized likewise (reversible). An image of A2, not A2: nothing identifies the
core's dynamics with a manuscript substratum's `φ`. -/
def A2Realized (T : FiniteOperationalTheory (Fin 2)) : Prop :=
  T.availExt 4 Unit (fun _ => transport coreIdx (correlationExtension sigmaPerm (onesCorr Core)))
    ∧ T.availExt 4 Unit
        (fun _ => transport coreIdx (correlationExtension sigmaPerm.symm (onesCorr Core)))

/-- The conjunction of the two realized-core images. Not the manuscript OI: no manuscript-level
conjunct of A1–A6 has a faithful form in this interface. -/
def A1A2Realized (T : FiniteOperationalTheory (Fin 2)) : Prop :=
  A1Realized T ∧ A2Realized T

/-- **THE A1 IMAGE HOLDS FOR EVERY THEORY**, by the interface's types. -/
theorem a1_every_theory (T : FiniteOperationalTheory (Fin 2)) : A1Realized T :=
  ⟨sealedCore_is_finiteOI.1, fun n => by simp⟩

/-- **THE A1 IMAGE HOLDS FOR THE WITNESS.** -/
theorem substratumTheory_A1 : A1Realized (substratumTheory (Fin 2)) :=
  a1_every_theory _

/-- **THE A2 IMAGE HOLDS FOR THE WITNESS**: both transported permutation channels come from
monomial generation alone (`substratumTheory_relabel`). -/
theorem substratumTheory_A2 : A2Realized (substratumTheory (Fin 2)) :=
  ⟨substratumTheory_relabel sigmaPerm, substratumTheory_relabel sigmaPerm.symm⟩

/-- **BOTH IMAGES HOLD FOR THE WITNESS.** -/
theorem substratumTheory_A1A2 : A1A2Realized (substratumTheory (Fin 2)) :=
  ⟨substratumTheory_A1, substratumTheory_A2⟩

/-- **THE A2 IMAGE HOLDS FOR EVERY THEORY WITH COMPOSITE UNITARY CONTROL**, so for quantum
mechanics: the image does not separate the witness from quantum mechanics. -/
theorem a2_of_control (T : FiniteOperationalTheory (Fin 2)) (hctrl : HasCompositeUnitaryControl T) :
    A2Realized T :=
  ⟨relabel_available T hctrl sigmaPerm, relabel_available T hctrl sigmaPerm.symm⟩

end Representable

/-! ### Section B — the configuration-level sourcing bound -/

section Sourcing

/-- **A CONFIGURATION-LEVEL ARCHITECTURE**: every admissible implementation operator is monomial,
a permutation of the configurations composed with a phase — the operator shape the interface
assigns to a substratum's direct interventions. -/
def ConfigurationLevel (𝓘 : ImplementationClass) : Prop :=
  ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → IsMonomial K

/-- The substratum class is configuration-level. -/
theorem substratumClass_configurationLevel : ConfigurationLevel substratumClass :=
  fun _ _ _ _ h => h

/-- **THE SUBSTRATUM CLASS IS THE LARGEST CONFIGURATION-LEVEL ARCHITECTURE**: a class is
configuration-level exactly when it is contained in the substratum class. -/
theorem configurationLevel_iff_le_substratum (𝓘 : ImplementationClass) :
    ConfigurationLevel 𝓘
      ↔ ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → substratumClass S K :=
  Iff.rfl

variable {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
variable {A : Type} [Fintype A] [DecidableEq A]

/-- **A CONFIGURATION-LEVEL CLASS GENERATES INSIDE THE SUBSTRATUM THEORY**: every instrument
family available in the theory a configuration-level architecture generates is available in the
theory the monomial class generates, on every carrier and at every level. A statement about
generated theories of implementation classes; it bounds a sourcing of a substratum only when
that sourcing factors through such a class. -/
theorem configurationLevel_availExt_le (h : ConfigurationLevel 𝓘) {n : ℕ} {O : Type} [Fintype O]
    [DecidableEq O] (F : O → Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ] Matrix (A × Fin n) (A × Fin n) ℂ)
    (hF : (genTheory 𝓘 arch A).availExt n O F) : (substratumTheory A).availExt n O F := by
  obtain ⟨hreal, htr⟩ := hF
  refine ⟨fun a => ?_, htr⟩
  obtain ⟨ι, _, K, hK, hadm⟩ := hreal a
  exact ⟨ι, inferInstance, K, hK, fun i => h _ _ (hadm i)⟩

/-- **THE FALSIFIER IS UNAVAILABLE IN THE THEORY OF EVERY CONFIGURATION-LEVEL CLASS**: an
available conjugation is a sum of monomial conjugations, each preserving the diagonal, which
`rot` does not. -/
theorem configurationLevel_falsifierUnavailable (h : ConfigurationLevel 𝓘) :
    FalsifierUnavailable (genTheory 𝓘 arch (Fin 2)) := by
  intro hav
  obtain ⟨ι, _, K, hK, hadm⟩ := hav.1 ()
  have hK' : conjChannel rot = ∑ i, conjChannel (K i) := hK
  apply rot_not_preservesDiag
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_monomial (h _ _ (hadm i))

/-- **NO CONFIGURATION-LEVEL CLASS GENERATES PHASE-FREE RICHNESS** on the two-state carrier,
when configuration relabelling is gauge (the class is label-invariant, so the generated theory
has embedded observation and the falsifier reduction applies). Hence any class supplying
phase-free richness is not configuration-level: necessity of a non-configuration-level source,
with no claim about which one. -/
theorem configurationLevel_not_phaseFree (h : ConfigurationLevel 𝓘) (hl : LabelInvariant 𝓘) :
    ¬ PhaseFreeRichness (genTheory 𝓘 arch (Fin 2)) :=
  not_phaseFree_of_falsifier_unavailable _ (genTheory_embeddedObservation 𝓘 arch hl)
    (configurationLevel_falsifierUnavailable arch h)

/-- **NO CONFIGURATION-LEVEL CLASS GENERATES QUANTUM MECHANICS** on the two-state carrier. -/
theorem configurationLevel_not_qm (h : ConfigurationLevel 𝓘) :
    ¬ ExactAllFiniteEndomorphicQuantumOps (genTheory 𝓘 arch (Fin 2)) :=
  fun hqm => qm_not_falsifierUnavailable _ hqm (configurationLevel_falsifierUnavailable arch h)

end Sourcing

#print axioms a1_every_theory
#print axioms substratumTheory_A1
#print axioms substratumTheory_A2
#print axioms substratumTheory_A1A2
#print axioms a2_of_control
#print axioms substratumClass_configurationLevel
#print axioms configurationLevel_iff_le_substratum
#print axioms configurationLevel_availExt_le
#print axioms configurationLevel_falsifierUnavailable
#print axioms configurationLevel_not_phaseFree
#print axioms configurationLevel_not_qm

end ManuscriptAxioms
end OIBridge
