/-
  OIBridge/MicroscopicReversibility.lean — the primitive-source audit, third target: the
  inverse clause of reversible richness, derived from dagger-stable implementations.

  ROUND FIFTY-EIGHT. After round fifty-seven the carrier-general quantum-complete package is
  implementation locality, reversible richness and embedded observation. Reversible richness
  is a conjunction of two different things, and the audit treats them separately:

      · INVERSE ACCESSIBILITY (`InverseAccessibility`) — every available conjugation channel
        has its adjoint channel available;
      · LIE-RANK RICHNESS (`LieRankRichness`) — at every level, a self-adjoint drift with
        finitely many unitary controls whose control Lie algebra contains `su(D)`, with the
        flows and the controls available.

  `reversibleRichness_iff` records that reversible richness is exactly their conjunction.

  THE REDUNDANCY TEST. Implementation locality, embedded observation and Lie-rank richness
  force inverse accessibility: Lie-rank richness alone gives full composite unitary control
  (`control_of_lieRank`, from the positive-reachability theorem
  `universalReachability_of_lieRank_positive`, which consumes no inverse of a control), and on
  a well-formed theory full control yields the inverse clause
  (`inverseAccessibility_of_lieRank`). The round-50 reachability theorem with the `hstar`
  hypothesis (`control_of_lieRank_inverse`) is kept as the place where the clause was consumed.
  The file also derives the clause from a primitive below availability.

  THE PRIMITIVE, BELOW AVAILABILITY. An implementation class is DAGGER-STABLE when the
  adjoint of an admissible operator is admissible: `𝓘 S K → 𝓘 S Kᴴ` (`DaggerStable`).
  This is closure of elementary implementation amplitudes under reversal; it mentions no
  availability. `ReversibleImplementationLocality` is implementation locality with a
  dagger-stable class.

  THE DERIVATION. If a conjugation channel `conj V` is available and the theory is
  implementation-generated by an architecture, then `conj V = ∑ conj (K i)` with admissible
  `K i` (`realized_of_instAvail`), and the aggregate trace makes `V` an isometry. The Choi
  matrix of `conj V` is the dyad of the vectorized `V`, so the dyads of the `K i` sum to a
  rank-one dyad and every `K i` lies on the ray of `V` (`dyad_sum_span_single`,
  `kraus_of_conj_unitary`): `K i = c i • V`, and some `c i` is nonzero
  (`exists_scaled_mem_of_instAvail_unitary`). The adjoint of a protocol is not a protocol, so
  the unitary itself has to be admissible: UNITARY-RAY SATURATION (`UnitaryRaySaturated`), a
  class containing a nonzero scalar multiple of a unitary contains the unitary, lifts `c i • V`
  to `V`, dagger stability supplies `Vᴴ`, and one step realizes `conj Vᴴ`. Hence
  `inverseAccessibility_of_generated_daggerStable`, for an architecture that is dagger-stable
  and unitary-ray saturated. Saturation is a statement about admissible operators, not about
  the phase resource of a theory; it enters at this one place and in no package. No
  Kraus-uniqueness theorem is invoked; the rank-one specialization is an elementary span lemma
  in the style of `dyad_sum_span`.

  NECESSITY. Exact finite operational QM is generated by the full class, which is
  dagger-stable (`reversibleImplementationLocality_of_qm`).

  THE COMPRESSED SET. `OIPlusMicro` is reversible implementation locality, Lie-rank richness
  and embedded observation; `carrier_general_oiPlusMicro` proves it equivalent to exact
  finite endomorphic operational QM on every nonempty finite carrier, the inverse clause
  taken from Lie-rank control on the well-formed theory, so that neither dagger stability nor
  saturation is consumed by the equivalence. The Lie-rank clause is the one substantive
  selector whose source is not audited here.

  WHAT IS NOT CLAIMED. The converse from inverse accessibility to dagger stability. That
  inverse accessibility follows from dagger stability without saturation. Any source for the
  Lie-rank clause.
-/

import OIBridge.ImplementationLocality
import OIBridge.PositiveReachability

namespace OIBridge
namespace MicroReversibility

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource InterventionLocality
open OIHierarchyGeneral PositiveReachability

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — the split -/

section Split

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **INVERSE ACCESSIBILITY**: every available conjugation channel has its adjoint channel
available. -/
def InverseAccessibility : Prop :=
  ∀ (n : ℕ) (V : Matrix (A × Fin n) (A × Fin n) ℂ),
    T.availExt n Unit (fun _ => conjChannel V) → T.availExt n Unit (fun _ => conjChannel Vᴴ)

/-- **LIE-RANK RICHNESS**: the drift/control certificate at every level. -/
def LieRankRichness : Prop :=
  ∀ n : ℕ, ∃ (G : Type) (H : Matrix (A × Fin n) (A × Fin n) ℂ)
    (U : G → Matrix (A × Fin n) (A × Fin n) ℂ),
    Hᴴ = H ∧ (∀ g, (U g)ᴴ * U g = 1) ∧ HControl H U
      ∧ (∀ t : ℝ, T.availExt n Unit (fun _ => conjChannel (flow H t)))
      ∧ (∀ g, T.availExt n Unit (fun _ => conjChannel (U g)))

/-- Reversible richness is exactly the conjunction of the two clauses. -/
theorem reversibleRichness_iff :
    OIHierarchyGeneral.ReversibleRichness T ↔ InverseAccessibility T ∧ LieRankRichness T :=
  Iff.rfl

/-- **WHERE THE INVERSE CLAUSE IS CONSUMED**: with it, Lie-rank richness gives full composite
unitary control through the round-50 reachability theorem. -/
theorem control_of_lieRank_inverse (hinv : InverseAccessibility T) (hlie : LieRankRichness T) :
    HasCompositeUnitaryControl T :=
  OIHierarchyGeneral.control_of_reversibleRichness T ⟨hinv, hlie⟩

/-- **LIE-RANK RICHNESS ALONE GIVES FULL COMPOSITE UNITARY CONTROL**: the inverse clause of
reversible richness is not consumed. Every unitary is a positive word in the flows, the controls
and the phases (`universalReachability_of_lieRank_positive`). -/
theorem control_of_lieRank (h : LieRankRichness T) : HasCompositeUnitaryControl T := by
  intro n V hV
  obtain ⟨G, H, U, hH, hU, hLie, hflow, hctrl⟩ := h n
  let avail : ∀ m : ℕ, (Fin m → Matrix (A × Fin n) (A × Fin n) ℂ →ₗ[ℂ]
      Matrix (A × Fin n) (A × Fin n) ℂ) → Prop :=
    fun m F => ∀ i : Fin m, T.availExt n Unit (fun _ => F i)
  have hreach : UniversalUnitaryReachability avail :=
    universalReachability_of_lieRank_positive H U hH hU hLie avail
      (fun V W hV hW i => by
        have := availExt_comp_unit T n _ _ (hW i) (hV i)
        rwa [conjChannel_mul_general] at this)
      (fun _ => by
        have := hflow 0
        rwa [OIHierarchy.flow_zero] at this)
      (fun t _ => hflow t) (fun g _ => hctrl g)
  exact hreach V hV 0

/-- **INVERSE ACCESSIBILITY IS DERIVED** from Lie-rank richness on a well-formed theory. -/
theorem inverseAccessibility_of_lieRank [Nonempty A] (hwf : WellFormed T) (h : LieRankRichness T) :
    InverseAccessibility T :=
  (reversibleRichness_of_control T hwf (control_of_lieRank T h)).1

end Split

/-! ### Section B — the rank-one span lemma -/

section Span

variable {C : Type*} [Fintype C] [DecidableEq C]

/-- **A SUM OF DYADS EQUAL TO A RANK-ONE DYAD HAS EVERY DYAD ON THE RAY.** -/
theorem dyad_sum_span_single {ι : Type*} (s : Finset ι) (v : ι → C → ℂ) (w : C → ℂ)
    (hw : w ≠ 0)
    (h : ∑ i ∈ s, Matrix.vecMulVec (v i) (star (v i)) = Matrix.vecMulVec w (star w))
    (i : ι) (hi : i ∈ s) : ∃ a : ℂ, v i = a • w := by
  have hn : star w ⬝ᵥ w ≠ 0 := fun h0 => hw (dotProduct_star_self_eq_zero.mp h0)
  set a := (star w ⬝ᵥ v i) / (star w ⬝ᵥ w) with ha
  set y := v i - a • w with hy
  have hy₀ : star w ⬝ᵥ y = 0 := by
    rw [hy, dotProduct_sub, dotProduct_smul, ha, smul_eq_mul, div_mul_cancel₀ _ hn]
    ring
  have hform : ∑ j ∈ s, ((Complex.normSq (star (v j) ⬝ᵥ y) : ℝ) : ℂ) = 0 := by
    have hl : star y ⬝ᵥ ((∑ j ∈ s, Matrix.vecMulVec (v j) (star (v j))) *ᵥ y)
        = ∑ j ∈ s, ((Complex.normSq (star (v j) ⬝ᵥ y) : ℝ) : ℂ) := by
      rw [Matrix.sum_mulVec, dotProduct_sum]
      exact Finset.sum_congr rfl fun j _ => form_vecMulVec (v j) y
    rw [← hl, h, vecMulVec_mulVec', hy₀, zero_smul, dotProduct_zero]
  have hreal : ∑ j ∈ s, Complex.normSq (star (v j) ⬝ᵥ y) = 0 := by
    have := hform
    rw [← Complex.ofReal_sum] at this
    exact_mod_cast this
  have hzero : star (v i) ⬝ᵥ y = 0 :=
    Complex.normSq_eq_zero.mp
      ((Finset.sum_eq_zero_iff_of_nonneg fun j _ => Complex.normSq_nonneg _).mp hreal i hi)
  have hyy : star y ⬝ᵥ y = 0 := by
    have : star y ⬝ᵥ y = star (v i) ⬝ᵥ y - star a * (star w ⬝ᵥ y) := by
      conv_lhs => rw [hy]
      rw [star_sub, star_smul, sub_dotProduct, smul_dotProduct, smul_eq_mul]
    rw [this, hzero, hy₀]
    ring
  refine ⟨a, ?_⟩
  have := dotProduct_star_self_eq_zero.mp hyy
  rw [hy] at this
  exact sub_eq_zero.mp this

end Span

/-! ### Section C — every Kraus operator of a conjugation channel lies on its ray -/

section Ray

variable {S : Type} [Fintype S] [DecidableEq S]

/-- **THE RAY LEMMA**: if a finite sum of conjugations is the conjugation by a nonzero `V`,
every operator in the sum is a scalar multiple of `V`. -/
theorem kraus_of_conj_unitary {ι : Type} [Fintype ι] (K : ι → Matrix S S ℂ)
    (V : Matrix S S ℂ) (hV : V ≠ 0)
    (h : ∑ i, conjChannel (K i) = conjChannel V) : ∀ i, ∃ a : ℂ, K i = a • V := by
  intro i
  have hchoi := congrArg choiMatrix h
  rw [choiMatrix_finsum] at hchoi
  simp only [choiMatrix_conjChannel] at hchoi
  have hw : (fun p : S × S => V p.2 p.1) ≠ 0 := by
    intro h0
    apply hV
    ext p q
    have := congrFun h0 (q, p)
    simpa using this
  obtain ⟨a, ha⟩ := dyad_sum_span_single Finset.univ (fun i => fun p : S × S => K i p.2 p.1) _ hw
    hchoi i (Finset.mem_univ i)
  refine ⟨a, ?_⟩
  ext p q
  have := congrFun ha (q, p)
  simpa using this

end Ray

/-! ### Section D — dagger-stable classes and the derivation -/

section Dagger

/-- **DAGGER STABILITY**: elementary implementation amplitudes are closed under reversal. -/
def DaggerStable (𝓘 : ImplementationClass) : Prop :=
  ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S Kᴴ

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **REVERSIBLE IMPLEMENTATION LOCALITY**: implementation locality with a dagger-stable
class. -/
def ReversibleImplementationLocality (T : FiniteOperationalTheory A) : Prop :=
  ∃ 𝓘 : ImplementationClass, ImplementationGenerated T 𝓘 ∧ ContextStable 𝓘
    ∧ LabelInvariant 𝓘 ∧ DaggerStable 𝓘

theorem implementationLocality_of_reversible {T : FiniteOperationalTheory A}
    (h : ReversibleImplementationLocality T) : ImplementationLocality T := by
  obtain ⟨𝓘, hg, hc, hl, -⟩ := h
  exact ⟨𝓘, hg, hc, hl⟩

/-- **UNITARY-RAY SATURATION**: a class that contains a nonzero scalar multiple of a unitary
contains the unitary. It is a statement about admissible operators, not about the phase
resource of a theory; the four classes of the kernel have it, the closed-form class of the
countercontrol (`InstrumentRealization`) does not. It enters at exactly one place, the
derivation of inverse accessibility from dagger stability, and no equivalence package
carries it. -/
def UnitaryRaySaturated (𝓘 : ImplementationClass) : Prop :=
  ∀ (S : Type) [Fintype S] [DecidableEq S] (c : ℂ) (V : Matrix S S ℂ), c ≠ 0 → Vᴴ * V = 1 →
    𝓘 S (c • V) → 𝓘 S V

theorem conjChannel_zero' {S : Type} [Fintype S] [DecidableEq S] :
    conjChannel (0 : Matrix S S ℂ) = 0 := by
  refine LinearMap.ext fun X => ?_
  show (0 : Matrix S S ℂ) * X * (0 : Matrix S S ℂ)ᴴ = 0
  simp

/-- **AN AVAILABLE UNITARY CONJUGATION HAS ITS UNITARY ADMISSIBLE** up to a nonzero scalar:
every branch of its branch-wise realization is proportional to the unitary, and some branch is
nonzero. -/
theorem exists_scaled_mem_of_instAvail_unitary (arch : Architecture 𝓘) {S : Type} [Fintype S]
    [DecidableEq S] [Nonempty S] {V : Matrix S S ℂ}
    (h : InstAvail 𝓘 S Unit (fun _ => conjChannel V)) : ∃ c : ℂ, c ≠ 0 ∧ 𝓘 S (c • V) := by
  obtain ⟨ι, _, K, hK, hadm⟩ := realized_of_instAvail arch h ()
  have hiso : Vᴴ * V = 1 := (conjChannel_trace_iff V).mp fun X => by
    have := instAvail_trace h X
    rwa [Fintype.sum_unique] at this
  have hV0 : V ≠ 0 := by
    intro h0
    rw [h0, Matrix.mul_zero] at hiso
    exact zero_ne_one hiso
  have hK' := kraus_of_conj_unitary K V hV0 hK.symm
  choose c hc using hK'
  by_contra hall
  have hall' : ∀ c' : ℂ, c' ≠ 0 → ¬ 𝓘 S (c' • V) := fun c' hc' hm => hall ⟨c', hc', hm⟩
  have hzero : ∀ i, K i = 0 := fun i => by
    by_cases hci : c i = 0
    · rw [hc i, hci, zero_smul]
    · exact absurd (hc i ▸ hadm i) (hall' (c i) hci)
  have h0 : conjChannel V = 0 := by
    rw [hK]
    exact Finset.sum_eq_zero fun i _ => by rw [hzero i, conjChannel_zero']
  have h1 := congrFun (congrFun (congrArg (fun Φ => Φ (1 : Matrix S S ℂ)) h0)
    (Classical.arbitrary S)) (Classical.arbitrary S)
  simp only [conjChannel_apply, Matrix.mul_one, mul_eq_one_comm.mp hiso, LinearMap.zero_apply,
    Matrix.one_apply_eq, Matrix.zero_apply] at h1
  exact one_ne_zero h1

/-- **INVERSE ACCESSIBILITY FROM DAGGER-STABLE GENERATION, UNDER UNITARY-RAY SATURATION.**
The adjoint of a protocol is not a protocol, so the unitary itself has to be admissible:
saturation supplies it from the nonzero branch, dagger stability supplies the adjoint, and one
step realizes it. -/
theorem inverseAccessibility_of_generated_daggerStable [Nonempty A]
    {T : FiniteOperationalTheory A} {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
    (hg : ImplementationGenerated T 𝓘) (hd : DaggerStable 𝓘) (hs : UnitaryRaySaturated 𝓘) :
    InverseAccessibility T := by
  intro n V hV
  rcases n with _ | k
  · exact availExt_zero T _
  have hI := (hg (k + 1) k.succ_pos Unit _).mp hV
  have hiso : Vᴴ * V = 1 := (conjChannel_trace_iff V).mp fun X => by
    have := instAvail_trace hI X
    rwa [Fintype.sum_unique] at this
  have : Nonempty (A × Fin (k + 1)) := ⟨(Classical.arbitrary A, ⟨0, k.succ_pos⟩)⟩
  obtain ⟨c, hc0, hcV⟩ := exists_scaled_mem_of_instAvail_unitary arch hI
  have hVmem : 𝓘 _ V := hs _ c V hc0 hiso hcV
  refine (hg (k + 1) k.succ_pos Unit _).mpr (InstAvail.op Vᴴ (hd _ _ hVmem) ?_)
  rw [Matrix.conjTranspose_conjTranspose]
  exact mul_eq_one_comm.mp hiso

theorem inverseAccessibility_of_reversibleImplementationLocality [Nonempty A]
    {T : FiniteOperationalTheory A} (h : ReversibleImplementationLocality T)
    (harch : ∀ 𝓘, ImplementationGenerated T 𝓘 → Architecture 𝓘 ∧ UnitaryRaySaturated 𝓘) :
    InverseAccessibility T := by
  obtain ⟨𝓘, hg, -, -, hd⟩ := h
  exact inverseAccessibility_of_generated_daggerStable (harch 𝓘 hg).1 hg hd (harch 𝓘 hg).2

/-- **GENERATED THEORIES ARE REVERSIBLY IMPLEMENTATION-LOCAL** when the class is
context-stable, label-invariant and dagger-stable. -/
theorem genTheory_reversibleImplementationLocality (𝓘 : ImplementationClass)
    (arch : Architecture 𝓘) (hc : ContextStable 𝓘) (hl : LabelInvariant 𝓘)
    (hd : DaggerStable 𝓘) : ReversibleImplementationLocality (genTheory 𝓘 arch A) :=
  ⟨𝓘, genTheory_generated 𝓘 arch, hc, hl, hd⟩

end Dagger

/-! ### Section E — necessity and the compressed set -/

section Compressed

theorem fullClass_daggerStable : DaggerStable fullClass := fun _ _ _ _ _ => trivial

theorem fullClass_unitaryRaySaturated : UnitaryRaySaturated fullClass :=
  fun _ _ _ _ _ _ _ _ => trivial

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **EXACT FINITE OPERATIONAL QM IS REVERSIBLY IMPLEMENTATION-LOCAL.** -/
theorem reversibleImplementationLocality_of_qm [Nonempty A]
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ReversibleImplementationLocality T :=
  ⟨fullClass, generated_of_qm T h, fullClass_contextStable, fullClass_labelInvariant,
    fullClass_daggerStable⟩

/-- **THE COMPRESSED SET**: reversible implementation locality, Lie-rank richness, embedded
observation. -/
def OIPlusMicro : Prop :=
  ReversibleImplementationLocality T ∧ LieRankRichness T ∧ EmbeddedObservation T

variable [Nonempty A]

/-- The inverse clause of the compressed set is supplied by Lie-rank richness through positive
reachability; dagger stability is not consumed here. -/
theorem oiPlusLocal_of_oiPlusMicro (h : OIPlusMicro T) : OIPlusLocal T :=
  ⟨implementationLocality_of_reversible h.1,
    ⟨inverseAccessibility_of_lieRank T
      ⟨validity_of_implementationLocality (implementationLocality_of_reversible h.1),
        systemToLevelOne_of_embeddedObservation h.2.2⟩ h.2.1, h.2.1⟩, h.2.2⟩

theorem qm_of_oiPlusMicro (h : OIPlusMicro T) : ExactAllFiniteEndomorphicQuantumOps T :=
  qm_of_oiPlusLocal T (oiPlusLocal_of_oiPlusMicro T h)

theorem oiPlusMicro_of_qm (h : ExactAllFiniteEndomorphicQuantumOps T) : OIPlusMicro T :=
  have hp := oiPlusLocal_of_qm T h
  ⟨reversibleImplementationLocality_of_qm T h, hp.2.1.2, hp.2.2⟩

/-- **THE COMPRESSED SET ⟺ FINITE OPERATIONAL QM**, on any nonempty finite carrier. -/
theorem oiPlusMicro_iff_qm : OIPlusMicro T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  ⟨qm_of_oiPlusMicro T, oiPlusMicro_of_qm T⟩

theorem oiPlusMicro_iff_oiPlusLocal : OIPlusMicro T ↔ OIPlusLocal T := by
  rw [oiPlusMicro_iff_qm, oiPlusLocal_iff_qm]

end Compressed

/-- **THE CARRIER-GENERAL STATEMENT**, quantified over the carrier. -/
theorem carrier_general_oiPlusMicro :
    ∀ (A : Type) [Fintype A] [DecidableEq A] [Nonempty A] (T : FiniteOperationalTheory A),
      OIPlusMicro T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  fun _ _ _ _ T => oiPlusMicro_iff_qm T

#print axioms reversibleRichness_iff
#print axioms control_of_lieRank_inverse
#print axioms control_of_lieRank
#print axioms inverseAccessibility_of_lieRank
#print axioms dyad_sum_span_single
#print axioms kraus_of_conj_unitary
#print axioms implementationLocality_of_reversible
#print axioms conjChannel_zero'
#print axioms exists_scaled_mem_of_instAvail_unitary
#print axioms inverseAccessibility_of_generated_daggerStable
#print axioms inverseAccessibility_of_reversibleImplementationLocality
#print axioms genTheory_reversibleImplementationLocality
#print axioms fullClass_daggerStable
#print axioms fullClass_unitaryRaySaturated
#print axioms reversibleImplementationLocality_of_qm
#print axioms oiPlusLocal_of_oiPlusMicro
#print axioms qm_of_oiPlusMicro
#print axioms oiPlusMicro_of_qm
#print axioms oiPlusMicro_iff_qm
#print axioms oiPlusMicro_iff_oiPlusLocal
#print axioms carrier_general_oiPlusMicro

end MicroReversibility
end OIBridge
