/-
  OIBridge/MicroscopicReversibility.lean — the primitive-source audit, third target: the
  inverse clause of reversible richness, derived from dagger-stable implementations.

  ROUND FIFTY-EIGHT. After round fifty-seven the carrier-general quantum-complete package is
  implementation locality, reversible richness and embedded observation. Reversible richness
  is a conjunction of two different things, and the audit treats them separately:

      · INVERSE ACCESSIBILITY (`InverseAccessibility`) — every available conjugation channel
        has its adjoint channel available;
      · LIE-RANK RICHNESS (`LieRankRichness`) — at every level, a self-adjoint drift with
        finitely many unitary controls whose control Lie algebra contains `su(D)`, with the
        flows and the controls available.

  `reversibleRichness_iff` records that reversible richness is exactly their conjunction.

  THE REDUNDANCY TEST, HONESTLY. Whether implementation locality, embedded observation and
  Lie-rank richness already force inverse accessibility is NOT settled here, in either
  direction. The kernel consumes the inverse clause at exactly one place: the `hstar`
  hypothesis of the round-50 reachability theorem
  (`universalReachability_of_lieRank_unconditional`), which needs the available conjugations
  to be closed under the adjoint in order to conjugate the drift by the controls. Without it
  the available unitaries at a level form a semigroup containing the flows in both time
  directions and the controls; in a compact group a subsemigroup with nonempty interior is a
  group, and the flows plausibly give that interior, so the clause may well be redundant —
  but that argument needs machinery (closure groups, interior of reachable sets) that is not
  in the kernel, and no countermodel is built either. The file says so, and derives the
  clause from a primitive instead.

  THE PRIMITIVE, BELOW AVAILABILITY. An implementation class is DAGGER-STABLE when the
  adjoint of an admissible operator is admissible: `𝓘 S K → 𝓘 S Kᴴ` (`DaggerStable`).
  This is closure of elementary implementation amplitudes under reversal; it mentions no
  availability. `ReversibleImplementationLocality` is implementation locality with a
  dagger-stable class.

  THE DERIVATION. If a conjugation channel `conj V` is available and the theory is
  implementation-generated, then `conj V = ∑ conj (K i)` with admissible `K i`, and the
  aggregate trace clause makes `V` an isometry. The Choi matrix of `conj V` is the dyad of
  the vectorized `V`, so the dyads of the `K i` sum to a rank-one dyad and every `K i` lies
  on the ray of `V` (`dyad_sum_span_single`, `kraus_of_conj_unitary`): `K i = c i • V`.
  Then `conj (K i)ᴴ = |c i|² • conj Vᴴ`, the `|c i|²` sum to one because `conj V ≠ 0`, and
  `conj Vᴴ = ∑ conj (K i)ᴴ` is realized by the dagger-stable class and trace preserving.
  Hence `inverseAccessibility_of_generated_daggerStable`. No Kraus-uniqueness theorem is
  invoked; the rank-one specialization is an elementary span lemma in the style of
  `dyad_sum_span`.

  NECESSITY. Exact finite operational QM is generated by the full class, which is
  dagger-stable (`reversibleImplementationLocality_of_qm`).

  THE COMPRESSED SET. `OIPlusMicro` is reversible implementation locality, Lie-rank richness
  and embedded observation; `carrier_general_oiPlusMicro` proves it equivalent to exact
  finite endomorphic operational QM on every nonempty finite carrier. The Lie-rank clause is
  the one substantive selector whose source is not audited.

  WHAT IS NOT CLAIMED. The redundancy of inverse accessibility given the other principles,
  in either direction. The converse from inverse accessibility to dagger stability. Any
  source for the Lie-rank clause.
-/

import OIBridge.ImplementationLocality

namespace OIBridge
namespace MicroReversibility

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource InterventionLocality

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — the split -/

section Split

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **INVERSE ACCESSIBILITY**: every available conjugation channel has its adjoint channel
available. -/
def InverseAccessibility : Prop :=
  ∀ (n : ℕ) (V : Matrix (A × Fin n) (A × Fin n) ℂ),
    T.availExt n Unit (fun _ => conjChannel V) → T.availExt n Unit (fun _ => conjChannel Vᴴ)

/-- **LIE-RANK RICHNESS**: the drift/control certificate at every level. -/
def LieRankRichness : Prop :=
  ∀ n : ℕ, ∃ (G : Type) (H : Matrix (A × Fin n) (A × Fin n) ℂ)
    (U : G → Matrix (A × Fin n) (A × Fin n) ℂ),
    Hᴴ = H ∧ (∀ g, (U g)ᴴ * U g = 1) ∧ HControl H U
      ∧ (∀ t : ℝ, T.availExt n Unit (fun _ => conjChannel (flow H t)))
      ∧ (∀ g, T.availExt n Unit (fun _ => conjChannel (U g)))

/-- Reversible richness is exactly the conjunction of the two clauses. -/
theorem reversibleRichness_iff :
    OIHierarchyGeneral.ReversibleRichness T ↔ InverseAccessibility T ∧ LieRankRichness T :=
  Iff.rfl

/-- **WHERE THE INVERSE CLAUSE IS CONSUMED**: with it, Lie-rank richness gives full composite
unitary control through the round-50 reachability theorem. -/
theorem control_of_lieRank_inverse (hinv : InverseAccessibility T) (hlie : LieRankRichness T) :
    HasCompositeUnitaryControl T :=
  OIHierarchyGeneral.control_of_reversibleRichness T ⟨hinv, hlie⟩

end Split

/-! ### Section B — the rank-one span lemma -/

section Span

variable {C : Type*} [Fintype C] [DecidableEq C]

/-- **A SUM OF DYADS EQUAL TO A RANK-ONE DYAD HAS EVERY DYAD ON THE RAY.** -/
theorem dyad_sum_span_single {ι : Type*} (s : Finset ι) (v : ι → C → ℂ) (w : C → ℂ)
    (hw : w ≠ 0)
    (h : ∑ i ∈ s, Matrix.vecMulVec (v i) (star (v i)) = Matrix.vecMulVec w (star w))
    (i : ι) (hi : i ∈ s) : ∃ a : ℂ, v i = a • w := by
  have hn : star w ⬝ᵥ w ≠ 0 := fun h0 => hw (dotProduct_star_self_eq_zero.mp h0)
  set a := (star w ⬝ᵥ v i) / (star w ⬝ᵥ w) with ha
  set y := v i - a • w with hy
  have hy₀ : star w ⬝ᵥ y = 0 := by
    rw [hy, dotProduct_sub, dotProduct_smul, ha, smul_eq_mul, div_mul_cancel₀ _ hn]
    ring
  have hform : ∑ j ∈ s, ((Complex.normSq (star (v j) ⬝ᵥ y) : ℝ) : ℂ) = 0 := by
    have hl : star y ⬝ᵥ ((∑ j ∈ s, Matrix.vecMulVec (v j) (star (v j))) *ᵥ y)
        = ∑ j ∈ s, ((Complex.normSq (star (v j) ⬝ᵥ y) : ℝ) : ℂ) := by
      rw [Matrix.sum_mulVec, dotProduct_sum]
      exact Finset.sum_congr rfl fun j _ => form_vecMulVec (v j) y
    rw [← hl, h, vecMulVec_mulVec', hy₀, zero_smul, dotProduct_zero]
  have hreal : ∑ j ∈ s, Complex.normSq (star (v j) ⬝ᵥ y) = 0 := by
    have := hform
    rw [← Complex.ofReal_sum] at this
    exact_mod_cast this
  have hzero : star (v i) ⬝ᵥ y = 0 :=
    Complex.normSq_eq_zero.mp
      ((Finset.sum_eq_zero_iff_of_nonneg fun j _ => Complex.normSq_nonneg _).mp hreal i hi)
  have hyy : star y ⬝ᵥ y = 0 := by
    have : star y ⬝ᵥ y = star (v i) ⬝ᵥ y - star a * (star w ⬝ᵥ y) := by
      conv_lhs => rw [hy]
      rw [star_sub, star_smul, sub_dotProduct, smul_dotProduct, smul_eq_mul]
    rw [this, hzero, hy₀]
    ring
  refine ⟨a, ?_⟩
  have := dotProduct_star_self_eq_zero.mp hyy
  rw [hy] at this
  exact sub_eq_zero.mp this

end Span

/-! ### Section C — every Kraus operator of a conjugation channel lies on its ray -/

section Ray

variable {S : Type} [Fintype S] [DecidableEq S]

omit [DecidableEq S] in
theorem conjChannel_smul (a : ℂ) (V : Matrix S S ℂ) :
    conjChannel (a • V) = (a * star a) • conjChannel V := by
  refine LinearMap.ext fun X => ?_
  show a • V * X * (a • V)ᴴ = (a * star a) • (V * X * Vᴴ)
  rw [Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.mul_smul, Matrix.smul_mul, smul_smul,
    mul_comm (star a) a]

/-- **THE RAY LEMMA**: if a finite sum of conjugations is the conjugation by a nonzero `V`,
every operator in the sum is a scalar multiple of `V`. -/
theorem kraus_of_conj_unitary {r : ℕ} (K : Fin r → Matrix S S ℂ) (s : Finset (Fin r))
    (V : Matrix S S ℂ) (hV : V ≠ 0)
    (h : ∑ i ∈ s, conjChannel (K i) = conjChannel V) : ∀ i ∈ s, ∃ a : ℂ, K i = a • V := by
  intro i hi
  have hchoi := congrArg choiMatrix h
  rw [choiMatrix_finsum] at hchoi
  simp only [choiMatrix_conjChannel] at hchoi
  have hw : (fun p : S × S => V p.2 p.1) ≠ 0 := by
    intro h0
    apply hV
    ext p q
    have := congrFun h0 (q, p)
    simpa using this
  obtain ⟨a, ha⟩ := dyad_sum_span_single s (fun i => fun p : S × S => K i p.2 p.1) _ hw hchoi i hi
  refine ⟨a, ?_⟩
  ext p q
  have := congrFun ha (q, p)
  simpa using this

end Ray

/-! ### Section D — dagger-stable classes and the derivation -/

section Dagger

/-- **DAGGER STABILITY**: elementary implementation amplitudes are closed under reversal. -/
def DaggerStable (𝓘 : ImplementationClass) : Prop :=
  ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), 𝓘 S K → 𝓘 S Kᴴ

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **REVERSIBLE IMPLEMENTATION LOCALITY**: implementation locality with a dagger-stable
class. -/
def ReversibleImplementationLocality (T : FiniteOperationalTheory A) : Prop :=
  ∃ 𝓘 : ImplementationClass, ImplementationGenerated T 𝓘 ∧ ContextStable 𝓘
    ∧ LabelInvariant 𝓘 ∧ DaggerStable 𝓘

theorem implementationLocality_of_reversible {T : FiniteOperationalTheory A}
    (h : ReversibleImplementationLocality T) : ImplementationLocality T := by
  obtain ⟨𝓘, hg, hc, hl, -⟩ := h
  exact ⟨𝓘, hg, hc, hl⟩

/-- **INVERSE ACCESSIBILITY FROM DAGGER-STABLE GENERATION.** -/
theorem inverseAccessibility_of_generated_daggerStable [Nonempty A]
    {T : FiniteOperationalTheory A} {𝓘 : ImplementationClass}
    (hg : ImplementationGenerated T 𝓘) (hd : DaggerStable 𝓘) : InverseAccessibility T := by
  intro n V hV
  rcases n with _ | k
  · exact availExt_zero T _
  obtain ⟨hreal, htr⟩ := (hg (k + 1) k.succ_pos Unit _).mp hV
  obtain ⟨r, K, s, hK, hadm⟩ := hreal ()
  have hiso : Vᴴ * V = 1 := by
    have h := sum_conjTranspose_mul_eq_one_of_trace (fun _ : Unit => V) htr
    rwa [Fintype.sum_unique] at h
  have hV0 : V ≠ 0 := by
    intro h0
    rw [h0, Matrix.mul_zero] at hiso
    exact zero_ne_one hiso
  have hVV : V * Vᴴ = 1 := mul_eq_one_comm.mp hiso
  have hK' : ∀ i ∈ s, ∃ a : ℂ, K i = a • V := kraus_of_conj_unitary K s V hV0 hK.symm
  choose! c hc using hK'
  have hsum : ∑ i ∈ s, conjChannel (K i) = (∑ i ∈ s, c i * star (c i)) • conjChannel V := by
    rw [Finset.sum_smul]
    exact Finset.sum_congr rfl fun i hi => by rw [hc i hi, conjChannel_smul]
  have hone : (∑ i ∈ s, c i * star (c i)) = 1 := by
    have h1 : conjChannel V 1 = ((∑ i ∈ s, c i * star (c i)) • conjChannel V) 1 := by
      rw [← hsum, ← hK]
    rw [LinearMap.smul_apply, conjChannel_apply, Matrix.mul_one, hVV] at h1
    let i : A × Fin (k + 1) := (Classical.arbitrary A, ⟨0, k.succ_pos⟩)
    have h2 := congrFun (congrFun h1 i) i
    rw [Matrix.smul_apply, Matrix.one_apply_eq, smul_eq_mul, mul_one] at h2
    exact h2.symm
  have hVd : (Vᴴ)ᴴ * Vᴴ = 1 := by rw [Matrix.conjTranspose_conjTranspose]; exact hVV
  refine (hg (k + 1) k.succ_pos Unit _).mpr
    ⟨fun _ => ⟨r, fun i => (K i)ᴴ, s, ?_, fun i => hd _ _ (hadm i)⟩, fun X => ?_⟩
  · have hterm : ∀ i ∈ s, conjChannel ((K i)ᴴ) = (c i * star (c i)) • conjChannel Vᴴ := by
      intro i hi
      rw [hc i hi, Matrix.conjTranspose_smul, conjChannel_smul, star_star, mul_comm (star (c i))]
    rw [Finset.sum_congr rfl hterm, ← Finset.sum_smul, hone, one_smul]
  · rw [Fintype.sum_unique]
    exact conjChannel_trace _ hVd X

theorem inverseAccessibility_of_reversibleImplementationLocality [Nonempty A]
    {T : FiniteOperationalTheory A} (h : ReversibleImplementationLocality T) :
    InverseAccessibility T := by
  obtain ⟨𝓘, hg, -, -, hd⟩ := h
  exact inverseAccessibility_of_generated_daggerStable hg hd

end Dagger

/-! ### Section E — necessity and the compressed set -/

section Compressed

theorem fullClass_daggerStable : DaggerStable fullClass := fun _ _ _ _ _ => trivial

variable {A : Type} [Fintype A] [DecidableEq A] (T : FiniteOperationalTheory A)

/-- **EXACT FINITE OPERATIONAL QM IS REVERSIBLY IMPLEMENTATION-LOCAL.** -/
theorem reversibleImplementationLocality_of_qm [Nonempty A]
    (h : ExactAllFiniteEndomorphicQuantumOps T) : ReversibleImplementationLocality T :=
  ⟨fullClass, generated_of_qm T h, fullClass_contextStable, fullClass_labelInvariant,
    fullClass_daggerStable⟩

/-- **THE COMPRESSED SET**: reversible implementation locality, Lie-rank richness, embedded
observation. -/
def OIPlusMicro : Prop :=
  ReversibleImplementationLocality T ∧ LieRankRichness T ∧ EmbeddedObservation T

variable [Nonempty A]

theorem oiPlusLocal_of_oiPlusMicro (h : OIPlusMicro T) : OIPlusLocal T :=
  ⟨implementationLocality_of_reversible h.1,
    ⟨inverseAccessibility_of_reversibleImplementationLocality h.1, h.2.1⟩, h.2.2⟩

theorem qm_of_oiPlusMicro (h : OIPlusMicro T) : ExactAllFiniteEndomorphicQuantumOps T :=
  qm_of_oiPlusLocal T (oiPlusLocal_of_oiPlusMicro T h)

theorem oiPlusMicro_of_qm (h : ExactAllFiniteEndomorphicQuantumOps T) : OIPlusMicro T :=
  have hp := oiPlusLocal_of_qm T h
  ⟨reversibleImplementationLocality_of_qm T h, hp.2.1.2, hp.2.2⟩

/-- **THE COMPRESSED SET ⟺ FINITE OPERATIONAL QM**, on any nonempty finite carrier. -/
theorem oiPlusMicro_iff_qm : OIPlusMicro T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  ⟨qm_of_oiPlusMicro T, oiPlusMicro_of_qm T⟩

theorem oiPlusMicro_iff_oiPlusLocal : OIPlusMicro T ↔ OIPlusLocal T := by
  rw [oiPlusMicro_iff_qm, oiPlusLocal_iff_qm]

end Compressed

/-- **THE CARRIER-GENERAL STATEMENT**, quantified over the carrier. -/
theorem carrier_general_oiPlusMicro :
    ∀ (A : Type) [Fintype A] [DecidableEq A] [Nonempty A] (T : FiniteOperationalTheory A),
      OIPlusMicro T ↔ ExactAllFiniteEndomorphicQuantumOps T :=
  fun _ _ _ _ T => oiPlusMicro_iff_qm T

#print axioms reversibleRichness_iff
#print axioms control_of_lieRank_inverse
#print axioms dyad_sum_span_single
#print axioms conjChannel_smul
#print axioms kraus_of_conj_unitary
#print axioms implementationLocality_of_reversible
#print axioms inverseAccessibility_of_generated_daggerStable
#print axioms inverseAccessibility_of_reversibleImplementationLocality
#print axioms fullClass_daggerStable
#print axioms reversibleImplementationLocality_of_qm
#print axioms oiPlusLocal_of_oiPlusMicro
#print axioms qm_of_oiPlusMicro
#print axioms oiPlusMicro_of_qm
#print axioms oiPlusMicro_iff_qm
#print axioms oiPlusMicro_iff_oiPlusLocal
#print axioms carrier_general_oiPlusMicro

end MicroReversibility
end OIBridge
