/-
  OIBridge/OrbitReachability.lean — the specialized proof of the last external item:
  `LocalReachabilityOfLieRank`, by orbit directions, one derivative, and the inverse-function
  theorem, in the one compact matrix-group setting the project consumes.

  ROUND FIFTY. Round forty-nine isolated the boundary as one predicate: if the dynamical
  control Lie algebra contains `su(D)`, the subgroup generated by the passive flows, the
  controls and the phases is a neighbourhood of `1` in the unitary group. This file proves it
  without Lie–Trotter, without the closed-subgroup theorem, without Yamabe, and without the
  general orbit theorem, along the route the owner laid out:

      1. ORBIT DIRECTIONS. `Ad(r)(-iH) = r(-iH)r†` for `r` reachable, together with the phase
         direction `i·1`. Each one-parameter group `e^{tX}` of an orbit direction lies in the
         reachable subgroup exactly (`exp_orbitDirs_mem_reachable`: `r e^{-itH} r†`, or a
         phase), and every round-nineteen generator `-i U_g H U_g†` is one.
      2. THE SPAN IS A LIE SUBALGEBRA, by one derivative. For an orbit direction `X` and any
         `Y` in the span `V`, the curve `t ↦ e^{tX} Y e^{-tX}` stays in `V` (conjugation by a
         reachable unitary permutes orbit directions and fixes the phase direction), `V` is
         closed (finite-dimensional), and the derivative at `0` is `[X, Y]`; a limit of
         difference quotients in a closed subspace lies in it (`bracket_mem_orbitSpan`).
         Hence `controlLie H U ≤ V` (`controlLie_le_orbitLie`), and with `𝔏 ⊇ su(D)` plus the
         phase direction, `V` contains every skew-Hermitian matrix (`skew_mem_orbitSpan`).
      3. A FINITE SPANNING FAMILY OF ACTUAL ORBIT DIRECTIONS `X_1, …, X_n` of `V`
         (`exists_spanning_family`: a linearly independent subset of the orbit directions
         spanning `V`, finite by Noetherianity, enumerated).
      4. THE PRODUCT MAP `F(t) = e^{t_1 X_1} ⋯ e^{t_n X_n}`, exactly reachable for every `t`
         (`prodMap_mem_reachable`), with strict derivative `h ↦ Σ h_j X_j` at `0`
         (`prodMap_hasStrictFDerivAt`), paired with the Hermitian complement
         `K(s) = Σ s_j (i X_j)` into `Ψ(t, s) = F(t) e^{K(s)}`, whose strict derivative at
         `0` is `(h, k) ↦ Σ h_j X_j + Σ k_j (i X_j)` (`psi_hasStrictFDerivAt`), surjective
         onto the matrix space because every `M = A + iB` with `A = (M − M†)/2` and
         `B = −i(M + M†)/2` skew, and skew matrices lie in `V` (`psiDeriv_surjective`).
      5. THE INVERSE-FUNCTION THEOREM (`HasStrictFDerivAt.map_nhds_eq_of_surj`): `Ψ` maps a
         neighbourhood of `0` onto a neighbourhood of `1`. A unitary `u = F(t) e^{K}` in it
         forces `e^{K}` unitary and Hermitian, so `e^{2K} = 1 = e^{0}` with `2K` inside the
         local injectivity neighbourhood of `exp` at `0` (`exists_exp_injOn_nhds`, from
         `hasStrictFDerivAt_exp_zero` and `eventually_left_inverse`), so `K = 0` and
         `u = F(t)` is reachable. That is `LocalReachability`
         (`localReachability_of_hcontrol`); the empty carrier is trivial.

      ┌──────────────────────────────────────────────────────────────────────────────┐
      │  `localReachabilityOfLieRank : LocalReachabilityOfLieRank S`                    │
      │      for every finite carrier (empty or not).                                  │
      │  `exactReachability_of_hcontrol`: `𝔏 ⊇ su(D) ⟹ ExactReachability` — every        │
      │      unitary is a finite word in the flows, the controls and the phases.       │
      │  `universalReachability_of_lieRank_unconditional`: the round-nineteen           │
      │      criterion `𝔏 ⊇ su(D) ⟹ universal unitary reachability`, unconditional.     │
      │  THE EXTERNAL BOUNDARY: ZERO ITEMS.                                            │
      └──────────────────────────────────────────────────────────────────────────────┘

  THE BOUNDARY AUDIT. The one item of rounds forty-eight and forty-nine (compact Lie
  integration / reachability, pinned to `LocalReachabilityOfLieRank`) is discharged here;
  `BoundaryAudit.lean`, `ReachabilitySeam.lean`, `IsometryExtension.lean` and
  `UhlmannUniqueness.lean` carry the discharge labels in place, provenance preserved. THE
  CURRENT UNRESOLVED EXTERNAL BOUNDARY: ZERO ITEMS. DISCHARGED INTERNALLY: PSD square-root /
  factorization (round thirty-four); finite isometry extension (round forty-five); finite
  right-unitary uniqueness (round forty-eight); compact Lie integration / reachability
  (round fifty). The round-forty-nine definition `LocalReachabilityOfLieRank` and its
  conditional consumer `universalReachability_of_lieRank` are unchanged and consumed.

  WHAT IS AND IS NOT CLAIMED. Proved: everything above, with the usual axiom footprint, for
  the compact matrix-group setting only. NOT claimed: the general orbit theorem, the
  closed-subgroup theorem, the Lie-Trotter formula, or any statement about non-compact or
  infinite-dimensional groups — none is used; that `HControl` is necessary for exact
  reachability. The completion classification (`GeneralCarrier.main_result`) is unaffected
  in either direction. No structure field is added.

  Kernel check:  cd verification/lean-mathlib && lake exe cache get && lake build
-/
import OIBridge.ReachabilitySeam
import Mathlib.Analysis.Calculus.InverseFunctionTheorem.FDeriv
import Mathlib.Analysis.Calculus.FDeriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Comp
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

namespace OIBridge
namespace OrbitReachability

open Complex Matrix ControlLie MonoidalCompletion ReachabilitySeam
open scoped ComplexOrder Matrix.Norms.L2Operator

attribute [local instance 100] LieRing.ofAssociativeRing

variable {S : Type} [Fintype S] [DecidableEq S] {G : Type}

/-! ### Section A — orbit directions -/

/-- The orbit direction `Ad(r)(-iH) = r (-iH) r†`. -/
def orbitDir (H : Matrix S S ℂ) (r : unitary (Matrix S S ℂ)) : Matrix S S ℂ :=
  (r : Matrix S S ℂ) * ((-Complex.I) • H) * (r : Matrix S S ℂ)ᴴ

/-- The orbit directions of the reachable subgroup, with the phase direction `i·1`. -/
def orbitDirs (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) : Set (Matrix S S ℂ) :=
  {X | ∃ r : unitary (Matrix S S ℂ), r ∈ reachable H U ∧ X = orbitDir H r}
    ∪ {Complex.I • (1 : Matrix S S ℂ)}

theorem coe_conjTranspose_mul_self (r : unitary (Matrix S S ℂ)) :
    (r : Matrix S S ℂ)ᴴ * (r : Matrix S S ℂ) = 1 := by
  have := r.2
  rw [Unitary.mem_iff, Matrix.star_eq_conjTranspose] at this
  exact this.1

theorem coe_mul_self_conjTranspose (r : unitary (Matrix S S ℂ)) :
    (r : Matrix S S ℂ) * (r : Matrix S S ℂ)ᴴ = 1 := by
  have := r.2
  rw [Unitary.mem_iff, Matrix.star_eq_conjTranspose] at this
  exact this.2

theorem orbitDir_skew {H : Matrix S S ℂ} (hH : Hᴴ = H) (r : unitary (Matrix S S ℂ)) :
    (orbitDir H r)ᴴ = -(orbitDir H r) := by
  simp only [orbitDir, Matrix.conjTranspose_mul, Matrix.conjTranspose_conjTranspose,
    Matrix.conjTranspose_neg, Matrix.conjTranspose_smul, hH, Complex.star_def, Complex.conj_I,
    neg_smul, neg_neg, Matrix.mul_assoc, Matrix.mul_neg, Matrix.neg_mul]

omit [Fintype S] in
theorem phaseDir_skew : (Complex.I • (1 : Matrix S S ℂ))ᴴ = -(Complex.I • (1 : Matrix S S ℂ)) := by
  rw [Matrix.conjTranspose_smul, Matrix.conjTranspose_one, Complex.star_def, Complex.conj_I,
    neg_smul]

theorem orbitDirs_skew {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H) {X : Matrix S S ℂ}
    (hX : X ∈ orbitDirs H U) : Xᴴ = -X := by
  rcases hX with ⟨r, _, rfl⟩ | hX
  · exact orbitDir_skew hH r
  · rw [Set.mem_singleton_iff] at hX
    rw [hX]
    exact phaseDir_skew

omit [Fintype S] [DecidableEq S] in
theorem real_smul_skew {X : Matrix S S ℂ} (hX : Xᴴ = -X) (t : ℝ) : (t • X)ᴴ = -(t • X) := by
  rw [Matrix.conjTranspose_smul, star_trivial, hX, smul_neg]

/-- The exponential of a real multiple of a skew-Hermitian matrix is unitary. -/
theorem exp_smul_mem_unitary {X : Matrix S S ℂ} (hX : Xᴴ = -X) (t : ℝ) :
    NormedSpace.exp (t • X) ∈ unitary (Matrix S S ℂ) := by
  refine mem_unitary_of_conjTranspose_mul ?_
  have hc : Commute (-(t • X)) (t • X) := (Commute.refl (t • X)).neg_left
  rw [← Matrix.exp_conjTranspose, real_smul_skew hX, ← Matrix.exp_add_of_commute _ _ hc,
    neg_add_cancel, NormedSpace.exp_zero]

omit [Fintype S] [DecidableEq S] in
theorem real_smul_neg_I_smul (H : Matrix S S ℂ) (t : ℝ) :
    t • ((-Complex.I) • H) = (-(t : ℂ) * Complex.I) • H := by
  rw [← smul_assoc, Complex.real_smul]
  congr 1
  ring

/-- **THE ONE-PARAMETER GROUP OF AN ORBIT DIRECTION IS REACHABLE**: `e^{t Ad(r)(-iH)} = r e^{-itH} r†`. -/
theorem exp_orbitDir_mem_reachable {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    (r : unitary (Matrix S S ℂ)) (hr : r ∈ reachable H U) (t : ℝ) :
    (⟨NormedSpace.exp (t • orbitDir H r), exp_smul_mem_unitary (orbitDir_skew hH r) t⟩ :
      unitary (Matrix S S ℂ)) ∈ reachable H U := by
  have hmem := mul_mem (mul_mem hr (flow_mem_reachable H U hH t)) (inv_mem hr)
  convert hmem using 1
  apply Subtype.ext
  simp only [Submonoid.coe_mul, ← Unitary.star_eq_inv, Unitary.coe_star,
    Matrix.star_eq_conjTranspose]
  rw [orbitDir, ← Matrix.smul_mul, ← Matrix.mul_smul, real_smul_neg_I_smul,
    unitary_exp_conj _ _ (coe_mul_self_conjTranspose r)]
  rfl

/-- A unitary scalar has unit modulus. -/
theorem norm_eq_one_of_smul_one_mem_unitary [Nonempty S] {c : ℂ}
    (h : c • (1 : Matrix S S ℂ) ∈ unitary (Matrix S S ℂ)) : ‖c‖ = 1 := by
  have h1 : (c • (1 : Matrix S S ℂ))ᴴ * (c • (1 : Matrix S S ℂ)) = 1 := coe_conjTranspose_mul_self ⟨_, h⟩
  rw [Matrix.conjTranspose_smul, Matrix.conjTranspose_one, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.one_mul, smul_smul] at h1
  obtain ⟨a⟩ := ‹Nonempty S›
  have h2 : star c * c = 1 := by
    have := congrFun (congrFun h1 a) a
    simpa [Matrix.smul_apply, Matrix.one_apply_eq] using this
  rw [Complex.star_def, ← Complex.normSq_eq_conj_mul_self, Complex.normSq_eq_norm_sq] at h2
  have h3 : ‖c‖ ^ 2 = 1 := by exact_mod_cast h2
  exact (pow_left_inj₀ (norm_nonneg _) zero_le_one two_ne_zero).mp (by simpa using h3)

/-- The exponential of the phase direction is a scalar. -/
theorem exp_phaseDir_eq (t : ℝ) :
    NormedSpace.exp (t • (Complex.I • (1 : Matrix S S ℂ)))
      = NormedSpace.exp ((t : ℂ) * Complex.I) • (1 : Matrix S S ℂ) := by
  rw [← smul_assoc, Complex.real_smul, ← Algebra.algebraMap_eq_smul_one,
    ← NormedSpace.algebraMap_exp_comm, Algebra.algebraMap_eq_smul_one]

/-- **THE ONE-PARAMETER GROUP OF THE PHASE DIRECTION IS REACHABLE.** -/
theorem exp_phaseDir_mem_reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (t : ℝ) :
    (⟨NormedSpace.exp (t • (Complex.I • (1 : Matrix S S ℂ))), exp_smul_mem_unitary phaseDir_skew t⟩ :
      unitary (Matrix S S ℂ)) ∈ reachable H U := by
  rcases isEmpty_or_nonempty S with hS | hS
  · -- the empty carrier: every unitary is `1`
    have : (⟨NormedSpace.exp (t • (Complex.I • (1 : Matrix S S ℂ))),
        exp_smul_mem_unitary phaseDir_skew t⟩ : unitary (Matrix S S ℂ)) = 1 := by
      ext i j
      exact (IsEmpty.false i).elim
    rw [this]
    exact one_mem _
  · have hu := exp_smul_mem_unitary (S := S) phaseDir_skew t
    rw [exp_phaseDir_eq] at hu
    have hn := norm_eq_one_of_smul_one_mem_unitary hu
    have := phase_mem_reachable H U hn
    convert this using 1
    ext
    simp only [exp_phaseDir_eq]

theorem exp_orbitDirs_mem_reachable {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    {X : Matrix S S ℂ} (hX : X ∈ orbitDirs H U) (t : ℝ) :
    (⟨NormedSpace.exp (t • X), exp_smul_mem_unitary (orbitDirs_skew hH hX) t⟩ :
      unitary (Matrix S S ℂ)) ∈ reachable H U := by
  rcases hX with ⟨r, hr, rfl⟩ | hX
  · exact exp_orbitDir_mem_reachable hH r hr t
  · rw [Set.mem_singleton_iff] at hX
    subst hX
    exact exp_phaseDir_mem_reachable H U t

/-- Conjugation by a reachable unitary permutes the orbit directions. -/
theorem ad_orbitDirs {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (r : unitary (Matrix S S ℂ))
    (hr : r ∈ reachable H U) {X : Matrix S S ℂ} (hX : X ∈ orbitDirs H U) :
    (r : Matrix S S ℂ) * X * (r : Matrix S S ℂ)ᴴ ∈ orbitDirs H U := by
  rcases hX with ⟨r', hr', rfl⟩ | hX
  · refine Or.inl ⟨r * r', mul_mem hr hr', ?_⟩
    simp only [orbitDir, Submonoid.coe_mul, Matrix.conjTranspose_mul, Matrix.mul_assoc]
  · rw [Set.mem_singleton_iff] at hX
    subst hX
    refine Or.inr ?_
    rw [Set.mem_singleton_iff, Matrix.mul_smul, Matrix.mul_one, Matrix.smul_mul,
      coe_mul_self_conjTranspose]

/-! ### Section B — the span of the orbit directions is a Lie subalgebra -/

/-- The real span of the orbit directions. -/
noncomputable def orbitSpan (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    Submodule ℝ (Matrix S S ℂ) :=
  Submodule.span ℝ (orbitDirs H U)

theorem ad_mem_orbitSpan {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (r : unitary (Matrix S S ℂ))
    (hr : r ∈ reachable H U) {Y : Matrix S S ℂ} (hY : Y ∈ orbitSpan H U) :
    (r : Matrix S S ℂ) * Y * (r : Matrix S S ℂ)ᴴ ∈ orbitSpan H U := by
  induction hY using Submodule.span_induction with
  | mem X hX => exact Submodule.subset_span (ad_orbitDirs r hr hX)
  | zero => simp
  | add X Y _ _ hX hY =>
    rw [Matrix.mul_add, Matrix.add_mul]
    exact Submodule.add_mem _ hX hY
  | smul a X _ hX =>
    rw [Matrix.mul_smul, Matrix.smul_mul]
    exact Submodule.smul_mem _ a hX

theorem orbitSpan_closed (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    IsClosed ((orbitSpan H U : Submodule ℝ (Matrix S S ℂ)) : Set (Matrix S S ℂ)) :=
  Submodule.closed_of_finiteDimensional _

theorem exp_neg_smul_eq_conjTranspose {X : Matrix S S ℂ} (hX : Xᴴ = -X) (t : ℝ) :
    NormedSpace.exp ((-t) • X) = (NormedSpace.exp (t • X))ᴴ := by
  rw [← Matrix.exp_conjTranspose, real_smul_skew hX, neg_smul]

/-- **THE DERIVATIVE STEP**: for an orbit direction `X` and `Y` in the span, `[X, Y]` lies in
the span — the curve `e^{tX} Y e^{-tX}` stays in the closed span and its derivative at `0`
is the bracket. -/
theorem bracket_mem_orbitSpan {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    {X : Matrix S S ℂ} (hX : X ∈ orbitDirs H U) {Y : Matrix S S ℂ} (hY : Y ∈ orbitSpan H U) :
    X * Y - Y * X ∈ orbitSpan H U := by
  have hXs : Xᴴ = -X := orbitDirs_skew hH hX
  set γ : ℝ → Matrix S S ℂ :=
    fun t => NormedSpace.exp (t • X) * Y * NormedSpace.exp ((-t) • X) with hγdef
  have hγ : ∀ t, γ t ∈ orbitSpan H U := by
    intro t
    have := ad_mem_orbitSpan _ (exp_orbitDirs_mem_reachable hH hX t) hY
    simp only [hγdef, exp_neg_smul_eq_conjTranspose hXs]
    exact this
  have hd : HasDerivAt γ (X * Y - Y * X) 0 := by
    have h1 : HasDerivAt (fun t : ℝ => NormedSpace.exp (t • X))
        (NormedSpace.exp ((0 : ℝ) • X) * X) 0 := hasDerivAt_exp_smul_const X 0
    have h2 : HasDerivAt (fun t : ℝ => NormedSpace.exp ((-t) • X))
        ((-1 : ℝ) • (NormedSpace.exp ((-(0 : ℝ)) • X) * X)) 0 :=
      (hasDerivAt_exp_smul_const X (-(0 : ℝ))).scomp 0 (hasDerivAt_neg 0)
    have h12 := (h1.mul (hasDerivAt_const (0 : ℝ) Y)).mul h2
    refine h12.congr_deriv ?_
    simp [zero_smul, NormedSpace.exp_zero, sub_eq_add_neg]
  have hslope := hasDerivAt_iff_tendsto_slope.mp hd
  refine (orbitSpan_closed H U).mem_of_tendsto hslope (Filter.Eventually.of_forall fun t => ?_)
  rw [slope_def_module]
  exact Submodule.smul_mem _ _ (Submodule.sub_mem _ (hγ t) (hγ 0))

/-- **THE ORBIT SPAN AS A LIE SUBALGEBRA.** -/
noncomputable def orbitLie (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (hH : Hᴴ = H) :
    LieSubalgebra ℝ (Matrix S S ℂ) :=
  { orbitSpan H U with
    lie_mem' := fun {X Y} hX hY => by
      show X * Y - Y * X ∈ orbitSpan H U
      induction hX using Submodule.span_induction with
      | mem X hX => exact bracket_mem_orbitSpan hH hX hY
      | zero => simp
      | add X₁ X₂ _ _ h1 h2 =>
        have := Submodule.add_mem _ h1 h2
        convert this using 1
        noncomm_ring
      | smul a X _ h =>
        have := Submodule.smul_mem _ a h
        convert this using 1
        rw [Matrix.smul_mul, Matrix.mul_smul, smul_sub] }

theorem mem_orbitLie_iff {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    (X : Matrix S S ℂ) : X ∈ orbitLie H U hH ↔ X ∈ orbitSpan H U := Iff.rfl

/-- Every round-nineteen generator is an orbit direction. -/
theorem controlGenerators_subset_orbitDirs {H : Matrix S S ℂ} {U : G → Matrix S S ℂ}
    (hU : ∀ g, (U g)ᴴ * U g = 1) : controlGenerators H U ⊆ orbitDirs H U := by
  rintro A ⟨g, rfl⟩
  refine Or.inl ⟨⟨U g, mem_unitary_of_conjTranspose_mul (hU g)⟩,
    control_mem_reachable H U g _, ?_⟩
  simp only [orbitDir, Matrix.mul_smul, Matrix.smul_mul]

/-- **THE CONTROL LIE ALGEBRA LIES IN THE ORBIT SPAN.** -/
theorem controlLie_le_orbitLie {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    (hU : ∀ g, (U g)ᴴ * U g = 1) : controlLie H U ≤ orbitLie H U hH :=
  LieSubalgebra.lieSpan_le.mpr fun _ hA =>
    Submodule.subset_span (controlGenerators_subset_orbitDirs hU hA)

/-- **EVERY SKEW-HERMITIAN MATRIX IS IN THE ORBIT SPAN** when `𝔏 ⊇ su(D)`: split off the
trace along the phase direction. -/
theorem skew_mem_orbitSpan [Nonempty S] {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    (hU : ∀ g, (U g)ᴴ * U g = 1) (hLie : HControl H U) {A : Matrix S S ℂ} (hA : Aᴴ = -A) :
    A ∈ orbitSpan H U := by
  have hD : (Fintype.card S : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  set c : ℂ := A.trace / Fintype.card S with hc
  have htr : star A.trace = -A.trace := by
    rw [← Matrix.trace_conjTranspose, hA, Matrix.trace_neg]
  have hcs : star c = -c := by
    rw [hc, star_div₀, htr, Complex.star_def, map_natCast, neg_div]
  have hA0 : (A - c • (1 : Matrix S S ℂ))ᴴ = -(A - c • (1 : Matrix S S ℂ)) := by
    rw [Matrix.conjTranspose_sub, hA, Matrix.conjTranspose_smul, Matrix.conjTranspose_one, hcs,
      neg_smul, neg_sub_neg, neg_sub]
  have htr0 : (A - c • (1 : Matrix S S ℂ)).trace = 0 := by
    rw [Matrix.trace_sub, Matrix.trace_smul, Matrix.trace_one, smul_eq_mul, hc,
      div_mul_cancel₀ _ hD, sub_self]
  have h1 : A - c • (1 : Matrix S S ℂ) ∈ orbitSpan H U :=
    (mem_orbitLie_iff hH _).mp (controlLie_le_orbitLie hH hU (hLie _ ⟨hA0, htr0⟩))
  have h2 : c • (1 : Matrix S S ℂ) ∈ orbitSpan H U := by
    have hre : c.re = 0 := by
      have := congrArg Complex.re hcs
      rw [Complex.star_def, Complex.conj_re, Complex.neg_re] at this
      linarith
    have hci : c • (1 : Matrix S S ℂ) = (c.im : ℝ) • (Complex.I • (1 : Matrix S S ℂ)) := by
      rw [← smul_assoc, Complex.real_smul]
      congr 1
      apply Complex.ext <;> simp [hre]
    rw [hci]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inr rfl))
  have := Submodule.add_mem _ h1 h2
  simpa using this

/-! ### Section C — a finite spanning family of orbit directions -/

/-- **A FINITE SPANNING FAMILY OF ACTUAL ORBIT DIRECTIONS**: a linearly independent subset of
the orbit directions spanning `V` is finite (`V` is finite-dimensional); enumerate it. -/
theorem exists_spanning_family (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    ∃ (n : ℕ) (X : Fin n → Matrix S S ℂ), (∀ j, X j ∈ orbitDirs H U) ∧
      Submodule.span ℝ (Set.range X) = orbitSpan H U := by
  obtain ⟨b, hb, hspan, hli⟩ := exists_linearIndependent ℝ (orbitDirs H U)
  have hfin : b.Finite := hli.set_finite_of_isNoetherian
  have : Finite b := hfin.to_subtype
  obtain ⟨n, ⟨e⟩⟩ := Finite.exists_equiv_fin b
  refine ⟨n, fun j => ((e.symm j : b) : Matrix S S ℂ), fun j => hb (e.symm j).2, ?_⟩
  rw [orbitSpan, ← hspan]
  congr 1
  ext x
  constructor
  · rintro ⟨j, rfl⟩
    exact (e.symm j).2
  · intro hx
    exact ⟨e ⟨x, hx⟩, by simp⟩

/-! ### Section D — the product map and its strict derivative at `0` -/

/-- The product map `F(t) = e^{t_0 X_0} ⋯ e^{t_{n-1} X_{n-1}}`. -/
noncomputable def prodMap : (n : ℕ) → (Fin n → Matrix S S ℂ) → (Fin n → ℝ) → Matrix S S ℂ
  | 0, _, _ => 1
  | n + 1, X, t =>
    NormedSpace.exp (t 0 • X 0) * prodMap n (fun j => X j.succ) (fun j => t j.succ)

theorem prodMap_zero (n : ℕ) (X : Fin n → Matrix S S ℂ) : prodMap n X 0 = 1 := by
  induction n with
  | zero => rfl
  | succ n ih =>
    show NormedSpace.exp ((0 : Fin (n + 1) → ℝ) 0 • X 0)
      * prodMap n (fun j => X j.succ) (fun j => (0 : Fin (n + 1) → ℝ) j.succ) = 1
    have h : (fun j : Fin n => (0 : Fin (n + 1) → ℝ) j.succ) = 0 := rfl
    rw [h, ih, Pi.zero_apply, zero_smul, NormedSpace.exp_zero, Matrix.one_mul]

theorem prodMap_zero_fun (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    prodMap n X (fun _ => (0 : ℝ)) = 1 := prodMap_zero n X

/-- **THE PRODUCT MAP IS EXACTLY REACHABLE** for every parameter. -/
theorem prodMap_mem_reachable {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H) (n : ℕ)
    (X : Fin n → Matrix S S ℂ) (hX : ∀ j, X j ∈ orbitDirs H U) (t : Fin n → ℝ) :
    ∃ P ∈ reachable H U, (P : Matrix S S ℂ) = prodMap n X t := by
  induction n with
  | zero => exact ⟨1, one_mem _, rfl⟩
  | succ n ih =>
    obtain ⟨P', hP', hPe⟩ := ih (fun j => X j.succ) (fun j => hX j.succ) (fun j => t j.succ)
    refine ⟨⟨_, exp_smul_mem_unitary (orbitDirs_skew hH (hX 0)) (t 0)⟩ * P',
      mul_mem (exp_orbitDirs_mem_reachable hH (hX 0) (t 0)) hP', ?_⟩
    rw [Submonoid.coe_mul, hPe]
    rfl

/-- The linear map `h ↦ Σ_j h_j • X_j`. -/
noncomputable def dirMap (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    (Fin n → ℝ) →L[ℝ] Matrix S S ℂ :=
  ∑ j, (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin n => ℝ) j).smulRight (X j)

omit [Fintype S] [DecidableEq S] in
theorem dirMap_apply (n : ℕ) (X : Fin n → Matrix S S ℂ) (h : Fin n → ℝ) :
    dirMap n X h = ∑ j, h j • X j := by
  simp [dirMap]

/-- **THE STRICT DERIVATIVE OF THE PRODUCT MAP AT `0`** is `h ↦ Σ_j h_j X_j`. -/
theorem prodMap_hasStrictFDerivAt (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    HasStrictFDerivAt (prodMap n X) (dirMap n X) 0 := by
  induction n with
  | zero =>
    have h : dirMap 0 X = 0 := by
      apply ContinuousLinearMap.ext
      intro v
      simp [dirMap_apply]
    rw [h]
    show HasStrictFDerivAt (fun _ : Fin 0 → ℝ => (1 : Matrix S S ℂ)) 0 0
    exact hasStrictFDerivAt_const 1 0
  | succ n ih =>
    let tail : (Fin (n + 1) → ℝ) →L[ℝ] (Fin n → ℝ) :=
      ContinuousLinearMap.pi fun j => ContinuousLinearMap.proj (R := ℝ) (φ := fun _ => ℝ) j.succ
    have ha : HasStrictFDerivAt (fun t : Fin (n + 1) → ℝ => NormedSpace.exp (t 0 • X 0))
        ((ContinuousLinearMap.smulRight (1 : ℝ →L[ℝ] ℝ)
          (NormedSpace.exp (((0 : Fin (n + 1) → ℝ) 0) • X 0) * X 0)).comp
          (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n + 1) => ℝ) 0)) 0 := by
      have h1 := (hasStrictDerivAt_exp_smul_const (X 0) ((0 : Fin (n + 1) → ℝ) 0)).hasStrictFDerivAt
      exact h1.comp (0 : Fin (n + 1) → ℝ)
        (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin (n + 1) => ℝ) 0).hasStrictFDerivAt
    have hb : HasStrictFDerivAt
        (fun t : Fin (n + 1) → ℝ => prodMap n (fun j => X j.succ) (fun j => t j.succ))
        ((dirMap n (fun j => X j.succ)).comp tail) 0 := by
      exact HasStrictFDerivAt.comp (0 : Fin (n + 1) → ℝ) (ih (fun j => X j.succ))
        tail.hasStrictFDerivAt
    have h := ha.mul' hb
    show HasStrictFDerivAt
      (fun t : Fin (n + 1) → ℝ =>
        NormedSpace.exp (t 0 • X 0) * prodMap n (fun j => X j.succ) (fun j => t j.succ))
      (dirMap (n + 1) X) 0
    refine h.congr_fderiv ?_
    apply ContinuousLinearMap.ext
    intro v
    have hb0 : prodMap n (fun j => X j.succ) (fun _ => (0 : ℝ)) = 1 := prodMap_zero_fun _ _
    simp [tail, dirMap_apply, hb0, Fin.sum_univ_succ]
    abel

/-! ### Section E — the map `Ψ`, its surjective derivative, and the inverse-function step -/

/-- The Hermitian complement `K(s) = Σ_j s_j (i X_j)`, as a linear map. -/
noncomputable def hermMap (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    (Fin n → ℝ) →L[ℝ] Matrix S S ℂ :=
  dirMap n fun j => Complex.I • X j

omit [Fintype S] [DecidableEq S] in
theorem hermMap_apply (n : ℕ) (X : Fin n → Matrix S S ℂ) (s : Fin n → ℝ) :
    hermMap n X s = ∑ j, s j • (Complex.I • X j) := dirMap_apply _ _ _

omit [Fintype S] [DecidableEq S] in
theorem hermMap_conjTranspose {n : ℕ} {X : Fin n → Matrix S S ℂ} (hX : ∀ j, (X j)ᴴ = -(X j))
    (s : Fin n → ℝ) : (hermMap n X s)ᴴ = hermMap n X s := by
  rw [hermMap_apply, Matrix.conjTranspose_sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [Matrix.conjTranspose_smul, star_trivial, Matrix.conjTranspose_smul, hX j, Complex.star_def,
    Complex.conj_I, neg_smul, smul_neg, smul_neg, smul_neg, neg_neg]

/-- `Ψ(t, s) = F(t) e^{K(s)}`. -/
noncomputable def psi (n : ℕ) (X : Fin n → Matrix S S ℂ)
    (p : (Fin n → ℝ) × (Fin n → ℝ)) : Matrix S S ℂ :=
  prodMap n X p.1 * NormedSpace.exp (hermMap n X p.2)

theorem psi_zero (n : ℕ) (X : Fin n → Matrix S S ℂ) : psi n X 0 = 1 := by
  simp [psi, prodMap_zero, NormedSpace.exp_zero]

/-- The candidate derivative of `Ψ` at `0`: `(h, k) ↦ Σ h_j X_j + Σ k_j (i X_j)`. -/
noncomputable def psiDeriv (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    ((Fin n → ℝ) × (Fin n → ℝ)) →L[ℝ] Matrix S S ℂ :=
  (dirMap n X).comp (ContinuousLinearMap.fst ℝ _ _)
    + (hermMap n X).comp (ContinuousLinearMap.snd ℝ _ _)

/-- **THE STRICT DERIVATIVE OF `Ψ` AT `0`.** -/
theorem psi_hasStrictFDerivAt (n : ℕ) (X : Fin n → Matrix S S ℂ) :
    HasStrictFDerivAt (psi n X) (psiDeriv n X) 0 := by
  have ha : HasStrictFDerivAt (fun p : (Fin n → ℝ) × (Fin n → ℝ) => prodMap n X p.1)
      ((dirMap n X).comp (ContinuousLinearMap.fst ℝ _ _)) 0 :=
    (prodMap_hasStrictFDerivAt n X).comp (0 : (Fin n → ℝ) × (Fin n → ℝ)) hasStrictFDerivAt_fst
  have hb : HasStrictFDerivAt
      (fun p : (Fin n → ℝ) × (Fin n → ℝ) => NormedSpace.exp (hermMap n X p.2))
      ((1 : Matrix S S ℂ →L[ℝ] Matrix S S ℂ).comp
        ((hermMap n X).comp (ContinuousLinearMap.snd ℝ _ _))) 0 := by
    have he : HasStrictFDerivAt NormedSpace.exp (1 : Matrix S S ℂ →L[ℝ] Matrix S S ℂ)
        (hermMap n X (ContinuousLinearMap.snd ℝ (Fin n → ℝ) (Fin n → ℝ) 0)) := by
      rw [map_zero, map_zero]
      exact hasStrictFDerivAt_exp_zero (𝕂 := ℝ)
    exact he.comp (0 : (Fin n → ℝ) × (Fin n → ℝ))
      ((hermMap n X).hasStrictFDerivAt.comp (0 : (Fin n → ℝ) × (Fin n → ℝ))
        hasStrictFDerivAt_snd)
  have h := ha.mul' hb
  show HasStrictFDerivAt
    (fun p : (Fin n → ℝ) × (Fin n → ℝ) => prodMap n X p.1 * NormedSpace.exp (hermMap n X p.2))
    (psiDeriv n X) 0
  refine h.congr_fderiv ?_
  apply ContinuousLinearMap.ext
  intro p
  simp [psiDeriv, prodMap_zero, NormedSpace.exp_zero]
  abel

/-- **THE DERIVATIVE OF `Ψ` IS SURJECTIVE** when the orbit directions span every skew-Hermitian
matrix: `M₀ = A + i B` with `A = (M₀ − M₀†)/2` and `B = −i (M₀ + M₀†)/2` both skew. -/
theorem psiDeriv_surjective [Nonempty S] {H : Matrix S S ℂ} {U : G → Matrix S S ℂ}
    (hH : Hᴴ = H) (hU : ∀ g, (U g)ᴴ * U g = 1) (hLie : HControl H U) (n : ℕ)
    (X : Fin n → Matrix S S ℂ) (hXspan : Submodule.span ℝ (Set.range X) = orbitSpan H U) :
    LinearMap.range (psiDeriv n X : ((Fin n → ℝ) × (Fin n → ℝ)) →ₗ[ℝ] Matrix S S ℂ) = ⊤ := by
  rw [LinearMap.range_eq_top]
  intro M₀
  set A : Matrix S S ℂ := (1 / 2 : ℝ) • (M₀ - M₀ᴴ) with hAdef
  set B : Matrix S S ℂ := (-Complex.I) • ((1 / 2 : ℝ) • (M₀ + M₀ᴴ)) with hBdef
  have hA : Aᴴ = -A := by
    rw [hAdef, Matrix.conjTranspose_smul, star_trivial, Matrix.conjTranspose_sub,
      Matrix.conjTranspose_conjTranspose, ← smul_neg, neg_sub]
  have hB : Bᴴ = -B := by
    rw [hBdef, Matrix.conjTranspose_smul, Matrix.conjTranspose_smul, star_neg, Complex.star_def,
      Complex.conj_I, star_trivial, Matrix.conjTranspose_add, Matrix.conjTranspose_conjTranspose,
      neg_neg, neg_smul, neg_neg, add_comm]
  have hAB : A + Complex.I • B = M₀ := by
    rw [hBdef, hAdef, smul_smul, mul_neg, Complex.I_mul_I, neg_neg, one_smul, ← smul_add,
      sub_add_add_cancel, ← two_smul ℝ M₀, smul_smul]
    norm_num
  have hA' : A ∈ Submodule.span ℝ (Set.range X) := hXspan ▸ skew_mem_orbitSpan hH hU hLie hA
  have hB' : B ∈ Submodule.span ℝ (Set.range X) := hXspan ▸ skew_mem_orbitSpan hH hU hLie hB
  obtain ⟨h, hh⟩ := (Submodule.mem_span_range_iff_exists_fun ℝ).mp hA'
  obtain ⟨k, hk⟩ := (Submodule.mem_span_range_iff_exists_fun ℝ).mp hB'
  refine ⟨(h, k), ?_⟩
  show dirMap n X h + hermMap n X k = M₀
  rw [dirMap_apply, hermMap_apply, hh, ← hAB]
  congr 1
  rw [← hk, Finset.smul_sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [smul_comm]

/-- **LOCAL INJECTIVITY OF `exp` AT `0`**, from its strict derivative `1` there. -/
theorem exists_exp_injOn_nhds :
    ∃ W ∈ nhds (0 : Matrix S S ℂ), Set.InjOn NormedSpace.exp W := by
  have hf : HasStrictFDerivAt NormedSpace.exp
      ((ContinuousLinearEquiv.refl ℝ (Matrix S S ℂ) : Matrix S S ℂ ≃L[ℝ] Matrix S S ℂ) :
        Matrix S S ℂ →L[ℝ] Matrix S S ℂ) (0 : Matrix S S ℂ) :=
    hasStrictFDerivAt_exp_zero (𝕂 := ℝ)
  obtain ⟨W, hW, hleft⟩ := hf.eventually_left_inverse.exists_mem
  refine ⟨W, hW, fun x hx y hy hxy => ?_⟩
  exact (hleft x hx).symm.trans ((congrArg _ hxy).trans (hleft y hy))

/-- **THE INVERSE-FUNCTION STEP**: on a nonempty carrier, `𝔏 ⊇ su(D)` gives local
reachability. `Ψ` maps a neighbourhood of `0` onto a neighbourhood of `1`; a unitary
`u = F(t) e^{K}` in it forces `e^{K}` unitary and Hermitian, so `e^{2K} = 1 = e^{0}` with
`2K` in the injectivity neighbourhood of `exp`, so `K = 0` and `u = F(t)`. -/
theorem localReachability_of_hcontrol [Nonempty S] {H : Matrix S S ℂ} {U : G → Matrix S S ℂ}
    (hH : Hᴴ = H) (hU : ∀ g, (U g)ᴴ * U g = 1) (hLie : HControl H U) :
    LocalReachability H U := by
  obtain ⟨n, X, hX, hXspan⟩ := exists_spanning_family H U
  have hXs : ∀ j, (X j)ᴴ = -(X j) := fun j => orbitDirs_skew hH (hX j)
  obtain ⟨W, hW, hWinj⟩ := exists_exp_injOn_nhds (S := S)
  have h0W : (0 : Matrix S S ℂ) ∈ W := mem_of_mem_nhds hW
  let f : (Fin n → ℝ) × (Fin n → ℝ) → Matrix S S ℂ := fun p => (2 : ℝ) • hermMap n X p.2
  have hf : Continuous f := ((hermMap n X).continuous.comp continuous_snd).const_smul (2 : ℝ)
  have hf0 : f 0 = 0 := by simp [f]
  have hB : f ⁻¹' W ∈ nhds (0 : (Fin n → ℝ) × (Fin n → ℝ)) :=
    hf.continuousAt.preimage_mem_nhds (by rw [hf0]; exact hW)
  have hmap := (psi_hasStrictFDerivAt n X).map_nhds_eq_of_surj
    (psiDeriv_surjective hH hU hLie n X hXspan)
  have himg : psi n X '' (f ⁻¹' W) ∈ nhds (1 : Matrix S S ℂ) := by
    rw [← psi_zero n X, ← hmap]
    exact Filter.image_mem_map hB
  have hpre : (Subtype.val ⁻¹' (psi n X '' (f ⁻¹' W)) : Set (unitary (Matrix S S ℂ)))
      ∈ nhds (1 : unitary (Matrix S S ℂ)) :=
    continuous_subtype_val.continuousAt.preimage_mem_nhds (by simpa using himg)
  refine Filter.mem_of_superset hpre ?_
  rintro u ⟨p, hp, hpu⟩
  obtain ⟨P, hP, hPe⟩ := prodMap_mem_reachable hH n X hX p.1
  have hK : (hermMap n X p.2)ᴴ = hermMap n X p.2 := hermMap_conjTranspose hXs p.2
  have hEeq : NormedSpace.exp (hermMap n X p.2) = ((star P * u : unitary (Matrix S S ℂ)) :
      Matrix S S ℂ) := by
    rw [Submonoid.coe_mul, Unitary.coe_star, Matrix.star_eq_conjTranspose, ← hpu]
    show _ = (P : Matrix S S ℂ)ᴴ * (prodMap n X p.1 * _)
    rw [← hPe, ← Matrix.mul_assoc, coe_conjTranspose_mul_self, Matrix.one_mul]
  have h1 : (NormedSpace.exp (hermMap n X p.2))ᴴ * NormedSpace.exp (hermMap n X p.2) = 1 := by
    rw [hEeq]
    exact coe_conjTranspose_mul_self _
  rw [← Matrix.exp_conjTranspose, hK, ← Matrix.exp_add_of_commute _ _ (Commute.refl _),
    ← two_smul ℝ (hermMap n X p.2)] at h1
  have hfp : f p = 0 := hWinj hp h0W (by rw [NormedSpace.exp_zero]; exact h1)
  have hK0 : hermMap n X p.2 = 0 := by
    have := hfp
    simp only [f] at this
    exact (smul_eq_zero.mp this).resolve_left two_ne_zero
  have hu : (u : Matrix S S ℂ) = (P : Matrix S S ℂ) := by
    rw [← hpu, psi, hK0, NormedSpace.exp_zero, Matrix.mul_one, hPe]
  rw [show u = P from Subtype.ext hu]
  exact hP

/-! ### Section F — the endpoint -/

/-- **THE LAST EXTERNAL ITEM, PROVED**: for every finite carrier, `𝔏 ⊇ su(D)` gives local
reachability. The empty carrier is trivial (its unitary group is a point). -/
theorem localReachabilityOfLieRank : LocalReachabilityOfLieRank S := by
  intro G H U hH hU hLie
  rcases isEmpty_or_nonempty S with hS | hS
  · unfold LocalReachability
    have huniv : ((reachable H U : Subgroup _) : Set (unitary (Matrix S S ℂ))) = Set.univ := by
      refine Set.eq_univ_of_forall fun u => ?_
      have hu1 : u = 1 := by
        ext i j
        exact (IsEmpty.false i).elim
      rw [hu1]
      exact one_mem _
    rw [huniv]
    exact Filter.univ_mem
  · exact localReachability_of_hcontrol hH hU hLie

/-- **EXACT REACHABILITY FROM THE LIE-RANK CONDITION**, unconditional. -/
theorem exactReachability_of_hcontrol {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hH : Hᴴ = H)
    (hU : ∀ g, (U g)ᴴ * U g = 1) (hLie : HControl H U) : ExactReachability H U :=
  exact_of_local (localReachabilityOfLieRank G H U hH hU hLie)

/-- **THE ROUND-NINETEEN CRITERION, UNCONDITIONAL**: `𝔏 ⊇ su(D)` gives universal unitary
reachability, with no external premise. -/
theorem universalReachability_of_lieRank_unconditional (H : Matrix S S ℂ)
    (U : G → Matrix S S ℂ) (hH : Hᴴ = H) (hU : ∀ g, (U g)ᴴ * U g = 1) (hLie : HControl H U)
    (avail : ∀ m : ℕ, (Fin m → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) → Prop)
    (hmul : ∀ V W : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel W) → avail 1 (fun _ => conjChannel (V * W)))
    (hstar : ∀ V : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel Vᴴ))
    (hone : avail 1 (fun _ => conjChannel (1 : Matrix S S ℂ)))
    (hflow : ∀ t : ℝ, avail 1 (fun _ => conjChannel (flow H t)))
    (hctrl : ∀ g : G, avail 1 (fun _ => conjChannel (U g))) :
    UniversalUnitaryReachability avail :=
  universalReachability_of_lieRank localReachabilityOfLieRank H U hH hU hLie avail hmul hstar
    hone hflow hctrl

#print axioms coe_conjTranspose_mul_self
#print axioms coe_mul_self_conjTranspose
#print axioms orbitDir_skew
#print axioms phaseDir_skew
#print axioms orbitDirs_skew
#print axioms real_smul_skew
#print axioms exp_smul_mem_unitary
#print axioms real_smul_neg_I_smul
#print axioms exp_orbitDir_mem_reachable
#print axioms norm_eq_one_of_smul_one_mem_unitary
#print axioms exp_phaseDir_eq
#print axioms exp_phaseDir_mem_reachable
#print axioms exp_orbitDirs_mem_reachable
#print axioms ad_orbitDirs
#print axioms ad_mem_orbitSpan
#print axioms orbitSpan_closed
#print axioms exp_neg_smul_eq_conjTranspose
#print axioms bracket_mem_orbitSpan
#print axioms mem_orbitLie_iff
#print axioms controlGenerators_subset_orbitDirs
#print axioms controlLie_le_orbitLie
#print axioms skew_mem_orbitSpan
#print axioms exists_spanning_family
#print axioms prodMap_zero
#print axioms prodMap_zero_fun
#print axioms prodMap_mem_reachable
#print axioms dirMap_apply
#print axioms prodMap_hasStrictFDerivAt
#print axioms hermMap_apply
#print axioms hermMap_conjTranspose
#print axioms psi_zero
#print axioms psi_hasStrictFDerivAt
#print axioms psiDeriv_surjective
#print axioms exists_exp_injOn_nhds
#print axioms localReachability_of_hcontrol
#print axioms localReachabilityOfLieRank
#print axioms exactReachability_of_hcontrol
#print axioms universalReachability_of_lieRank_unconditional

end OrbitReachability
end OIBridge
