/-
  OIBridge/OrbitNormalization.lean — round OG-1: the premise-free infrastructure around the
  reduced orbit-generation theorem of `OrbitGeneration`.

  Nothing here is a hypothesis about OI. Every theorem either moves the named hypotheses of
  `OrbitGeneration` (P1 `SharpSeed`, V4′ `SeedOrbitAvailable`, K∞-R `BoundaryTransitive`, and the body
  premise `PreservesBody`) along a construction that needs no further premise, or is a control.

  Proved here.
    §A  the words of a set of automorphisms; `PreservesBody` for the generators extends to every
        word they generate (`preservesBody_words`), in particular to the words of an elementary
        drive (`preservesBody_driveWords`);
    §B  two premise-free facts about elementary drives: `flow 0` is forced by `flow_add`
        (`flow_zero_of_add`), and a body all of whose automorphism orbits are finite admits no
        drive (`isEmpty_drivability_of_finite_orbits`);
    §C  transport along an affine coordinate change `T : V ≃ᵃ[ℝ] W`: bodies, effects, proper
        effects, boundary states, sharp seeds, `PreservesBody`, boundary transitivity, seed orbits
        and V4′ move together (`hypotheses_tr`); for a body carried onto `ball3` — an ellipsoid in
        any coordinates — the seed orbit is the directional family read in the original
        coordinates (`seedOrbit_eq_of_normalization`), and the Lorentz bridge holds for the
        transported effects (`lorentz_of_normalization`);
    §D  restriction to an affine chart `w ↦ L w + p0` with `L` injective and the body inside the
        chart's range: boundary states, effects and sharp seeds restrict; an automorphism of the
        body preserves the body's affine span (`affineSpan_preserved`); an automorphism preserving
        the chart's range restricts to an automorphism of the chart that intertwines it
        (`restrictEquiv`, `chart_restrictEquiv`); the named hypotheses restrict
        (`hypotheses_restrict`);
    §E  the words of the landed control drive `ball3Drive` act transitively on the boundary of
        `ball3` (`boundaryTransitive_ball3Drive`), so the reduced theorem applies to it;
    §F  the countercontrol: the closed unit ball of `EuclideanSpace ℝ (Fin 4)`, a body of
        dimension four, is boundary-transitive under its isometries
        (`boundaryTransitive_ball4`); boundary transitivity does not fix dimension three.

  Kernel check:  cd verification/lean-mathlib && lake exe cache get && lake build
-/
import OIBridge.OrbitGeneration
import Mathlib.Analysis.InnerProductSpace.Projection.Reflection
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Inverse
import Mathlib.LinearAlgebra.Basis.VectorSpace

namespace OIBridge
namespace OrbitNormalization

open Set KInfFoundations OrbitGeneration

variable {V : Type} [NormedAddCommGroup V] [NormedSpace ℝ V]
variable {W : Type} [NormedAddCommGroup W] [NormedSpace ℝ W]

/-! ### §A — words, and `PreservesBody` under words -/

/-- The words generated by a set of affine automorphisms: the subgroup it generates. -/
def words (S : Set (V ≃ᵃ[ℝ] V)) : Set (V ≃ᵃ[ℝ] V) := (Subgroup.closure S : Set (V ≃ᵃ[ℝ] V))

theorem subset_words (S : Set (V ≃ᵃ[ℝ] V)) : S ⊆ words S := Subgroup.subset_closure

theorem mul_mem_words {S : Set (V ≃ᵃ[ℝ] V)} {g k : V ≃ᵃ[ℝ] V} (hg : g ∈ words S)
    (hk : k ∈ words S) : g * k ∈ words S :=
  Subgroup.mul_mem _ hg hk

theorem inv_mem_words {S : Set (V ≃ᵃ[ℝ] V)} {g : V ≃ᵃ[ℝ] V} (hg : g ∈ words S) :
    g⁻¹ ∈ words S :=
  Subgroup.inv_mem _ hg

theorem one_apply' (x : V) : (1 : V ≃ᵃ[ℝ] V) x = x := by
  rw [AffineEquiv.coe_one]
  rfl

theorem mul_apply' (g k : V ≃ᵃ[ℝ] V) (x : V) : (g * k) x = g (k x) := by
  rw [AffineEquiv.coe_mul]
  rfl

theorem symm_eq_inv (g : V ≃ᵃ[ℝ] V) : g.symm = g⁻¹ := (AffineEquiv.inv_def g).symm

theorem inv_apply' (g : V ≃ᵃ[ℝ] V) (x : V) : g⁻¹ x = g.symm x := by rw [symm_eq_inv]

/-- **G-AUT under words.** If every generator and its inverse map `Ω` into `Ω`, so does every word
the generators generate. -/
theorem preservesBody_words {Ω : Set V} {S : Set (V ≃ᵃ[ℝ] V)} (h : PreservesBody Ω S) :
    PreservesBody Ω (words S) := by
  intro g hg
  have hg' : g ∈ Subgroup.closure S := hg
  clear hg
  induction hg' using Subgroup.closure_induction with
  | mem g hgS => exact h g hgS
  | one =>
      intro x hx
      refine ⟨by rw [one_apply']; exact hx, ?_⟩
      rw [symm_eq_inv, inv_one, one_apply']
      exact hx
  | mul g k _ _ ihg ihk =>
      intro x hx
      refine ⟨?_, ?_⟩
      · rw [mul_apply']
        exact (ihg _ (ihk x hx).1).1
      · rw [symm_eq_inv, mul_inv_rev, mul_apply', inv_apply', inv_apply']
        exact (ihk _ (ihg x hx).2).2
  | inv g _ ih =>
      intro x hx
      refine ⟨?_, ?_⟩
      · rw [inv_apply']
        exact (ih x hx).2
      · rw [symm_eq_inv, inv_inv]
        exact (ih x hx).1

/-- The words of an elementary drive's flow and `J` are automorphisms of the body. -/
theorem preservesBody_driveWords {Ω : Set V} (D : ElementaryDrivability Ω) :
    PreservesBody Ω (words (Set.range D.flow ∪ {D.J})) :=
  preservesBody_words (preservesBody_drive D)

/-! ### §B — two premise-free facts about elementary drives -/

/-- **B1.** The group law of a flow forces `flow 0` to be the identity. -/
theorem flow_zero_of_add (flow : ℝ → V ≃ᵃ[ℝ] V)
    (h : ∀ s t, flow (s + t) = (flow t).trans (flow s)) : flow 0 = AffineEquiv.refl ℝ V := by
  refine AffineEquiv.ext fun x => ?_
  have h1 := congrArg (fun f : V ≃ᵃ[ℝ] V => f ((flow 0).symm x)) (h 0 0)
  simp only [add_zero, AffineEquiv.trans_apply, AffineEquiv.apply_symm_apply] at h1
  rw [AffineEquiv.refl_apply]
  exact h1.symm

/-- **B5.** A body every point of which has a finite orbit under the automorphisms of the body
admits no elementary drive: a continuous flow cannot move a point inside a finite set. -/
theorem isEmpty_drivability_of_finite_orbits {Ω : Set V}
    (hfin : ∀ x ∈ Ω,
      {y | ∃ g : V ≃ᵃ[ℝ] V, (∀ z ∈ Ω, g z ∈ Ω ∧ g.symm z ∈ Ω) ∧ g x = y}.Finite) :
    IsEmpty (ElementaryDrivability Ω) := by
  refine ⟨fun D => ?_⟩
  obtain ⟨x, hx, hmove⟩ := D.N_moves
  have hS := hfin x hx
  set S := {y | ∃ g : V ≃ᵃ[ℝ] V, (∀ z ∈ Ω, g z ∈ Ω ∧ g.symm z ∈ Ω) ∧ g x = y} with hSdef
  have hmem : ∀ t, D.flow t x ∈ S := fun t =>
    ⟨D.flow t, fun z hz => ⟨D.flow_preserves t z hz,
      by rw [drive_flow_symm_apply]; exact D.flow_preserves (-t) z hz⟩, rfl⟩
  have hc : Continuous fun t : ℝ => D.flow t x :=
    D.flow_continuous.comp (by fun_prop : Continuous fun t : ℝ => (t, x))
  let A : Set ℝ := {t | D.flow t x = x}
  have hclosed : IsClosed A := isClosed_eq hc continuous_const
  have hT : IsClosed (S \ {x}) := (hS.subset Set.diff_subset).isClosed
  have hA : A = (fun t => D.flow t x) ⁻¹' (S \ {x})ᶜ := by
    ext t
    simp only [A, Set.mem_setOf_eq, Set.mem_preimage, Set.mem_compl_iff, Set.mem_diff,
      Set.mem_singleton_iff, not_and, not_not]
    exact ⟨fun h _ => h, fun h => h (hmem t)⟩
  have hopen : IsOpen A := by
    rw [hA]
    exact hT.isOpen_compl.preimage hc
  have h0 : (0 : ℝ) ∈ A := by
    show D.flow 0 x = x
    rw [D.flow_zero]
    rfl
  have huniv : A = Set.univ := IsClopen.eq_univ ⟨hclosed, hopen⟩ ⟨0, h0⟩
  have ht : D.t₀ ∈ A := by rw [huniv]; exact Set.mem_univ _
  exact hmove ht

/-! ### §C — transport along an affine coordinate change -/

/-- An effect read in the new coordinates. -/
noncomputable def effTr (T : V ≃ᵃ[ℝ] W) (e : V →ᵃ[ℝ] ℝ) : W →ᵃ[ℝ] ℝ :=
  e.comp T.symm.toAffineMap

theorem effTr_apply (T : V ≃ᵃ[ℝ] W) (e : V →ᵃ[ℝ] ℝ) (w : W) : effTr T e w = e (T.symm w) := rfl

theorem effTr_apply_apply (T : V ≃ᵃ[ℝ] W) (e : V →ᵃ[ℝ] ℝ) (x : V) : effTr T e (T x) = e x := by
  rw [effTr_apply, AffineEquiv.symm_apply_apply]

/-- An effect is recovered from its reading in the new coordinates. -/
theorem effTr_comp (T : V ≃ᵃ[ℝ] W) (e : V →ᵃ[ℝ] ℝ) : (effTr T e).comp T.toAffineMap = e := by
  ext x
  show effTr T e (T x) = e x
  exact effTr_apply_apply T e x

theorem effTr_injective (T : V ≃ᵃ[ℝ] W) : Function.Injective (effTr T) := fun e f h => by
  rw [← effTr_comp T e, ← effTr_comp T f, h]

/-- An automorphism read in the new coordinates: `T ∘ g ∘ T⁻¹`. -/
def conjTr (T : V ≃ᵃ[ℝ] W) (g : V ≃ᵃ[ℝ] V) : W ≃ᵃ[ℝ] W := (T.symm.trans g).trans T

theorem conjTr_apply (T : V ≃ᵃ[ℝ] W) (g : V ≃ᵃ[ℝ] V) (w : W) :
    conjTr T g w = T (g (T.symm w)) := rfl

theorem conjTr_apply_apply (T : V ≃ᵃ[ℝ] W) (g : V ≃ᵃ[ℝ] V) (x : V) :
    conjTr T g (T x) = T (g x) := by
  rw [conjTr_apply, AffineEquiv.symm_apply_apply]

theorem conjTr_symm_apply (T : V ≃ᵃ[ℝ] W) (g : V ≃ᵃ[ℝ] V) (w : W) :
    (conjTr T g).symm w = T (g.symm (T.symm w)) := by
  apply (conjTr T g).injective
  rw [AffineEquiv.apply_symm_apply, conjTr_apply, AffineEquiv.symm_apply_apply,
    AffineEquiv.apply_symm_apply, AffineEquiv.apply_symm_apply]

theorem mem_image_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {w : W} : w ∈ T '' Ω ↔ T.symm w ∈ Ω := by
  constructor
  · rintro ⟨x, hx, rfl⟩
    rw [AffineEquiv.symm_apply_apply]
    exact hx
  · intro h
    exact ⟨T.symm w, h, AffineEquiv.apply_symm_apply T w⟩

theorem apply_mem_image_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {x : V} : T x ∈ T '' Ω ↔ x ∈ Ω := by
  rw [mem_image_tr, AffineEquiv.symm_apply_apply]

/-- An affine map carries the extension of a segment to the extension of the image segment. -/
theorem tr_extension (T : V ≃ᵃ[ℝ] W) (x y : V) (ε : ℝ) :
    T (x + ε • (x - y)) = T x + ε • (T x - T y) := by
  have h1 : T.toAffineMap (ε • (x - y) +ᵥ x) =
      T.toAffineMap.linear (ε • (x - y)) +ᵥ T.toAffineMap x :=
    T.toAffineMap.map_vadd x (ε • (x - y))
  have h2 : T.toAffineMap.linear (x -ᵥ y) = T.toAffineMap x -ᵥ T.toAffineMap y :=
    T.toAffineMap.linearMap_vsub x y
  rw [vadd_eq_add, vadd_eq_add, map_smul] at h1
  rw [vsub_eq_sub, vsub_eq_sub] at h2
  rw [h2] at h1
  rw [add_comm x, add_comm (T x)]
  exact h1

theorem isEffectOn_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {e : V →ᵃ[ℝ] ℝ} (he : IsEffectOn Ω e) :
    IsEffectOn (T '' Ω) (effTr T e) := by
  rintro _ ⟨x, hx, rfl⟩
  rw [effTr_apply_apply]
  exact he x hx

theorem isProperOn_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {e : V →ᵃ[ℝ] ℝ} (he : IsProperOn Ω e) :
    IsProperOn (T '' Ω) (effTr T e) := by
  obtain ⟨y, hy, hlt⟩ := he
  exact ⟨T y, ⟨y, hy, rfl⟩, by rw [effTr_apply_apply]; exact hlt⟩

/-- Boundary states are read in the body alone, so a coordinate change carries them exactly. -/
theorem isBoundaryState_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {x : V} :
    IsBoundaryState Ω x ↔ IsBoundaryState (T '' Ω) (T x) := by
  constructor
  · rintro ⟨hx, y, hy, hout⟩
    refine ⟨⟨x, hx, rfl⟩, T y, ⟨y, hy, rfl⟩, fun ε hε hmem => hout ε hε ?_⟩
    rw [← tr_extension] at hmem
    exact (apply_mem_image_tr T).1 hmem
  · rintro ⟨hx, y', hy', hout⟩
    obtain ⟨y, hy, rfl⟩ := hy'
    refine ⟨(apply_mem_image_tr T).1 hx, y, hy, fun ε hε hmem => hout ε hε ?_⟩
    rw [← tr_extension]
    exact ⟨_, hmem, rfl⟩

theorem sharpSeed_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {r : V →ᵃ[ℝ] ℝ} (hr : SharpSeed Ω r) :
    SharpSeed (T '' Ω) (effTr T r) := by
  obtain ⟨he, ⟨x, hx, h1⟩, ⟨y, hy, h0⟩⟩ := hr
  exact ⟨isEffectOn_tr T he, ⟨T x, ⟨x, hx, rfl⟩, by rw [effTr_apply_apply, h1]⟩,
    ⟨T y, ⟨y, hy, rfl⟩, by rw [effTr_apply_apply, h0]⟩⟩

theorem preservesBody_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {G : Set (V ≃ᵃ[ℝ] V)}
    (hG : PreservesBody Ω G) : PreservesBody (T '' Ω) (conjTr T '' G) := by
  rintro _ ⟨g, hg, rfl⟩ _ ⟨x, hx, rfl⟩
  refine ⟨?_, ?_⟩
  · rw [conjTr_apply_apply]
    exact ⟨_, (hG g hg x hx).1, rfl⟩
  · rw [conjTr_symm_apply, AffineEquiv.symm_apply_apply]
    exact ⟨_, (hG g hg x hx).2, rfl⟩

theorem boundaryTransitive_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {G : Set (V ≃ᵃ[ℝ] V)}
    (hK : BoundaryTransitive Ω G) : BoundaryTransitive (T '' Ω) (conjTr T '' G) := by
  intro u v hu hv
  have hu' : IsBoundaryState Ω (T.symm u) := by
    rw [isBoundaryState_tr T, AffineEquiv.apply_symm_apply]
    exact hu
  have hv' : IsBoundaryState Ω (T.symm v) := by
    rw [isBoundaryState_tr T, AffineEquiv.apply_symm_apply]
    exact hv
  obtain ⟨g, hg, hgx⟩ := hK _ _ hu' hv'
  refine ⟨conjTr T g, ⟨g, hg, rfl⟩, ?_⟩
  rw [conjTr_apply, hgx, AffineEquiv.apply_symm_apply]

theorem seedTransport_tr (T : V ≃ᵃ[ℝ] W) (r : V →ᵃ[ℝ] ℝ) (g : V ≃ᵃ[ℝ] V) :
    seedTransport (effTr T r) (conjTr T g) = effTr T (seedTransport r g) := by
  ext w
  rw [seedTransport_apply, conjTr_symm_apply, effTr_apply, effTr_apply,
    AffineEquiv.symm_apply_apply, seedTransport_apply]

theorem seedOrbit_tr (T : V ≃ᵃ[ℝ] W) (G : Set (V ≃ᵃ[ℝ] V)) (r : V →ᵃ[ℝ] ℝ) :
    seedOrbit (conjTr T '' G) (effTr T r) = effTr T '' seedOrbit G r := by
  ext f
  constructor
  · rintro ⟨_, ⟨g, hg, rfl⟩, rfl⟩
    exact ⟨seedTransport r g, ⟨g, hg, rfl⟩, (seedTransport_tr T r g).symm⟩
  · rintro ⟨_, ⟨g, hg, rfl⟩, rfl⟩
    exact ⟨conjTr T g, ⟨g, hg, rfl⟩, (seedTransport_tr T r g).symm⟩

theorem seedOrbitAvailable_tr (T : V ≃ᵃ[ℝ] W) {G : Set (V ≃ᵃ[ℝ] V)} {r : V →ᵃ[ℝ] ℝ}
    {avail : Set (V →ᵃ[ℝ] ℝ)} (hV4 : SeedOrbitAvailable G r avail) :
    SeedOrbitAvailable (conjTr T '' G) (effTr T r) (effTr T '' avail) := by
  rintro _ ⟨g, hg, rfl⟩
  rw [seedTransport_tr]
  exact ⟨_, hV4 g hg, rfl⟩

/-- **The coordinate change is premise-free.** The four named hypotheses move together along any
affine coordinate change, with the body, the seed, the automorphisms and the available effects
read in the new coordinates. -/
theorem hypotheses_tr (T : V ≃ᵃ[ℝ] W) {Ω : Set V} {G : Set (V ≃ᵃ[ℝ] V)} {r : V →ᵃ[ℝ] ℝ}
    {avail : Set (V →ᵃ[ℝ] ℝ)} (hG : PreservesBody Ω G) (hP1 : SharpSeed Ω r)
    (hK : BoundaryTransitive Ω G) (hV4 : SeedOrbitAvailable G r avail) :
    PreservesBody (T '' Ω) (conjTr T '' G) ∧ SharpSeed (T '' Ω) (effTr T r) ∧
      BoundaryTransitive (T '' Ω) (conjTr T '' G) ∧
      SeedOrbitAvailable (conjTr T '' G) (effTr T r) (effTr T '' avail) :=
  ⟨preservesBody_tr T hG, sharpSeed_tr T hP1, boundaryTransitive_tr T hK,
    seedOrbitAvailable_tr T hV4⟩

/-- **The reduced theorem in any coordinates.** For a body carried onto `ball3` by a coordinate
change `T` — an ellipsoid, read in its own coordinates — the transports of a sharp seed under a
boundary-transitive set of automorphisms are exactly the directional effects `(1 + b · T x)/2`. -/
theorem seedOrbit_eq_of_normalization {Ω : Set V} (T : V ≃ᵃ[ℝ] (Fin 3 → ℝ)) (hT : T '' Ω = ball3)
    {G : Set (V ≃ᵃ[ℝ] V)} {r : V →ᵃ[ℝ] ℝ} (hG : PreservesBody Ω G) (hP1 : SharpSeed Ω r)
    (hK : BoundaryTransitive Ω G) :
    seedOrbit G r =
      {f | ∃ b : Fin 3 → ℝ, b 0 ^ 2 + b 1 ^ 2 + b 2 ^ 2 = 1 ∧
        f = (ballEffect b).comp T.toAffineMap} := by
  have hG' := preservesBody_tr T hG
  have hP1' := sharpSeed_tr T hP1
  have hK' := boundaryTransitive_tr T hK
  rw [hT] at hG' hP1' hK'
  have horb := seedOrbit_ball3_eq hG' hP1' hK'
  rw [seedOrbit_tr] at horb
  ext f
  constructor
  · intro hf
    have hmem : effTr T f ∈ directionalFamily := by
      rw [← horb]
      exact ⟨f, hf, rfl⟩
    obtain ⟨b, hb, hbf⟩ := hmem
    refine ⟨b, hb, ?_⟩
    rw [← effTr_comp T f, hbf]
  · rintro ⟨b, hb, rfl⟩
    have hmem : ballEffect b ∈ effTr T '' seedOrbit G r := by
      rw [horb]
      exact ⟨b, hb, rfl⟩
    obtain ⟨f, hf, hfb⟩ := hmem
    have : f = (ballEffect b).comp T.toAffineMap := by
      rw [← hfb, effTr_comp]
    rw [← this]
    exact hf

/-- **The Lorentz bridge in any coordinates.** A homogeneous vector on which every transported
seed, read in the coordinates of `ball3`, pairs nonnegatively lies in the Lorentz cone. -/
theorem lorentz_of_normalization {Ω : Set V} (T : V ≃ᵃ[ℝ] (Fin 3 → ℝ)) (hT : T '' Ω = ball3)
    {G : Set (V ≃ᵃ[ℝ] V)} {r : V →ᵃ[ℝ] ℝ} (hG : PreservesBody Ω G) (hP1 : SharpSeed Ω r)
    (hK : BoundaryTransitive Ω G) (x0 : ℝ) (v : Fin 3 → ℝ)
    (h : ∀ e ∈ seedOrbit G r, 0 ≤ conePair (effTr T e) x0 v) :
    0 ≤ x0 ∧ (∑ j, v j ^ 2) ≤ x0 ^ 2 := by
  have hG' := preservesBody_tr T hG
  have hP1' := sharpSeed_tr T hP1
  have hK' := boundaryTransitive_tr T hK
  rw [hT] at hG' hP1' hK'
  refine lorentz_of_seedOrbit hG' hP1' hK' x0 v (fun e he => ?_)
  rw [seedOrbit_tr] at he
  obtain ⟨f, hf, rfl⟩ := he
  exact h f hf

/-! ### §D — restriction to an affine chart of the body's affine span -/

/-- The chart `w ↦ L w + p0`. -/
noncomputable def chart (L : W →ₗ[ℝ] V) (p0 : V) : W →ᵃ[ℝ] V :=
  L.toAffineMap + AffineMap.const ℝ W p0

theorem chart_apply (L : W →ₗ[ℝ] V) (p0 : V) (w : W) : chart L p0 w = L w + p0 := rfl

theorem chart_injective {L : W →ₗ[ℝ] V} (hL : LinearMap.ker L = ⊥) (p0 : V) :
    Function.Injective (chart L p0) := by
  intro w u h
  rw [chart_apply, chart_apply, add_left_inj] at h
  exact LinearMap.ker_eq_bot.mp hL h

theorem chart_extension (L : W →ₗ[ℝ] V) (p0 : V) (w u : W) (ε : ℝ) :
    chart L p0 (w + ε • (w - u)) =
      chart L p0 w + ε • (chart L p0 w - chart L p0 u) := by
  rw [chart_apply, chart_apply, chart_apply, map_add, map_smul, map_sub]
  module

/-- A left inverse of the chart's linear part exists. -/
theorem exists_chart_leftInverse {L : W →ₗ[ℝ] V} (hL : LinearMap.ker L = ⊥) :
    ∃ Lg : V →ₗ[ℝ] W, ∀ w, Lg (L w) = w := by
  obtain ⟨Lg, hLg⟩ := L.exists_leftInverse_of_injective hL
  exact ⟨Lg, fun w => by rw [← LinearMap.comp_apply, hLg, LinearMap.id_apply]⟩

/-- The retraction onto the chart: `x ↦ Lg (x - p0)`. -/
noncomputable def chartRetract (Lg : V →ₗ[ℝ] W) (p0 : V) : V →ᵃ[ℝ] W :=
  Lg.toAffineMap + AffineMap.const ℝ V (-(Lg p0))

theorem chartRetract_apply (Lg : V →ₗ[ℝ] W) (p0 x : V) :
    chartRetract Lg p0 x = Lg x + -(Lg p0) := rfl

theorem chartRetract_chart {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w) (p0 : V)
    (w : W) : chartRetract Lg p0 (chart L p0 w) = w := by
  rw [chartRetract_apply, chart_apply, map_add, hLg, add_neg_cancel_right]

theorem chart_chartRetract {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w) {p0 x : V}
    (hx : x ∈ Set.range (chart L p0)) : chart L p0 (chartRetract Lg p0 x) = x := by
  obtain ⟨w, rfl⟩ := hx
  rw [chartRetract_chart hLg]

/-- The body read in the chart. -/
def bodyR (L : W →ₗ[ℝ] V) (p0 : V) (Ω : Set V) : Set W := chart L p0 ⁻¹' Ω

/-- An effect read in the chart. -/
noncomputable def effR (L : W →ₗ[ℝ] V) (p0 : V) (e : V →ᵃ[ℝ] ℝ) : W →ᵃ[ℝ] ℝ :=
  e.comp (chart L p0)

theorem effR_apply (L : W →ₗ[ℝ] V) (p0 : V) (e : V →ᵃ[ℝ] ℝ) (w : W) :
    effR L p0 e w = e (chart L p0 w) := rfl

/-- Boundary states are read in the body alone, so the chart carries them exactly. -/
theorem isBoundaryState_restrict {L : W →ₗ[ℝ] V} (hL : LinearMap.ker L = ⊥) {p0 : V}
    {Ω : Set V} (hΩ : Ω ⊆ Set.range (chart L p0)) {w : W} :
    IsBoundaryState (bodyR L p0 Ω) w ↔ IsBoundaryState Ω (chart L p0 w) := by
  constructor
  · rintro ⟨hw, u, hu, hout⟩
    refine ⟨hw, chart L p0 u, hu, fun ε hε hmem => hout ε hε ?_⟩
    show chart L p0 (w + ε • (w - u)) ∈ Ω
    rw [chart_extension]
    exact hmem
  · rintro ⟨hw, y, hy, hout⟩
    obtain ⟨u, rfl⟩ := hΩ hy
    refine ⟨hw, u, hy, fun ε hε hmem => hout ε hε ?_⟩
    have hmem' : chart L p0 (w + ε • (w - u)) ∈ Ω := hmem
    rw [chart_extension] at hmem'
    exact hmem'

theorem isEffectOn_restrict (L : W →ₗ[ℝ] V) (p0 : V) {Ω : Set V} {e : V →ᵃ[ℝ] ℝ}
    (he : IsEffectOn Ω e) : IsEffectOn (bodyR L p0 Ω) (effR L p0 e) :=
  fun w hw => he _ hw

theorem sharpSeed_restrict (L : W →ₗ[ℝ] V) {p0 : V} {Ω : Set V}
    (hΩ : Ω ⊆ Set.range (chart L p0)) {r : V →ᵃ[ℝ] ℝ} (hr : SharpSeed Ω r) :
    SharpSeed (bodyR L p0 Ω) (effR L p0 r) := by
  obtain ⟨he, ⟨x, hx, h1⟩, ⟨y, hy, h0⟩⟩ := hr
  obtain ⟨u, rfl⟩ := hΩ hx
  obtain ⟨v, rfl⟩ := hΩ hy
  exact ⟨isEffectOn_restrict L p0 he, ⟨u, hx, h1⟩, ⟨v, hy, h0⟩⟩

/-- An automorphism of the body maps the body's affine span into itself. -/
theorem affineSpan_preserved {Ω : Set V} {g : V ≃ᵃ[ℝ] V} (hg : ∀ x ∈ Ω, g x ∈ Ω) {x : V}
    (hx : x ∈ affineSpan ℝ Ω) : g x ∈ affineSpan ℝ Ω := by
  have hmap : g.toAffineMap x ∈ (affineSpan ℝ Ω).map g.toAffineMap :=
    AffineSubspace.mem_map_of_mem _ hx
  rw [AffineSubspace.map_span] at hmap
  refine affineSpan_mono ℝ ?_ hmap
  rintro _ ⟨z, hz, rfl⟩
  exact hg z hz

/-- An automorphism of the body maps a chart onto the body's affine span into itself, and so does
its inverse. -/
theorem range_preserved {L : W →ₗ[ℝ] V} {p0 : V} {Ω : Set V}
    (hspan : ∀ x, x ∈ affineSpan ℝ Ω ↔ x ∈ Set.range (chart L p0)) {G : Set (V ≃ᵃ[ℝ] V)}
    (hG : PreservesBody Ω G) {g : V ≃ᵃ[ℝ] V} (hg : g ∈ G) {x : V}
    (hx : x ∈ Set.range (chart L p0)) :
    g x ∈ Set.range (chart L p0) ∧ g.symm x ∈ Set.range (chart L p0) := by
  rw [← hspan] at hx
  rw [← hspan, ← hspan]
  exact ⟨affineSpan_preserved (fun z hz => (hG g hg z hz).1) hx,
    affineSpan_preserved (g := g.symm) (fun z hz => (hG g hg z hz).2) hx⟩

/-- The restriction of an automorphism to the chart, as an affine map. -/
noncomputable def restrictMap (L : W →ₗ[ℝ] V) (Lg : V →ₗ[ℝ] W) (p0 : V) (g : V ≃ᵃ[ℝ] V) :
    W →ᵃ[ℝ] W :=
  (chartRetract Lg p0).comp (g.toAffineMap.comp (chart L p0))

theorem restrictMap_apply (L : W →ₗ[ℝ] V) (Lg : V →ₗ[ℝ] W) (p0 : V) (g : V ≃ᵃ[ℝ] V) (w : W) :
    restrictMap L Lg p0 g w = chartRetract Lg p0 (g (chart L p0 w)) := rfl

theorem chart_restrictMap {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w) {p0 : V}
    {g : V ≃ᵃ[ℝ] V} (hg : ∀ w, g (chart L p0 w) ∈ Set.range (chart L p0)) (w : W) :
    chart L p0 (restrictMap L Lg p0 g w) = g (chart L p0 w) := by
  rw [restrictMap_apply, chart_chartRetract hLg (hg w)]

theorem restrictMap_bijective {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w)
    {p0 : V} {g : V ≃ᵃ[ℝ] V}
    (hg : ∀ x ∈ Set.range (chart L p0),
      g x ∈ Set.range (chart L p0) ∧ g.symm x ∈ Set.range (chart L p0)) :
    Function.Bijective (restrictMap L Lg p0 g) := by
  have h1 : ∀ w, g (chart L p0 w) ∈ Set.range (chart L p0) :=
    fun w => (hg _ ⟨w, rfl⟩).1
  have h2 : ∀ w, g.symm (chart L p0 w) ∈ Set.range (chart L p0) :=
    fun w => (hg _ ⟨w, rfl⟩).2
  refine (Function.bijective_iff_has_inverse).2
    ⟨fun w => chartRetract Lg p0 (g.symm (chart L p0 w)), fun w => ?_, fun w => ?_⟩
  · show chartRetract Lg p0 (g.symm (chart L p0 (restrictMap L Lg p0 g w))) = w
    rw [chart_restrictMap hLg h1, AffineEquiv.symm_apply_apply, chartRetract_chart hLg]
  · show restrictMap L Lg p0 g (chartRetract Lg p0 (g.symm (chart L p0 w))) = w
    rw [restrictMap_apply, chart_chartRetract hLg (h2 w), AffineEquiv.apply_symm_apply,
      chartRetract_chart hLg]

/-- The restriction of an automorphism preserving the chart's range, as an automorphism of the
chart. -/
noncomputable def restrictEquiv {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w)
    {p0 : V} {g : V ≃ᵃ[ℝ] V}
    (hg : ∀ x ∈ Set.range (chart L p0),
      g x ∈ Set.range (chart L p0) ∧ g.symm x ∈ Set.range (chart L p0)) : W ≃ᵃ[ℝ] W :=
  AffineEquiv.ofBijective (restrictMap_bijective hLg hg)

/-- **Intertwining.** The restricted automorphism is the original one, read in the chart. -/
theorem chart_restrictEquiv {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w)
    {p0 : V} {g : V ≃ᵃ[ℝ] V}
    (hg : ∀ x ∈ Set.range (chart L p0),
      g x ∈ Set.range (chart L p0) ∧ g.symm x ∈ Set.range (chart L p0)) (w : W) :
    chart L p0 (restrictEquiv hLg hg w) = g (chart L p0 w) :=
  chart_restrictMap hLg (fun w => (hg _ ⟨w, rfl⟩).1) w

theorem chart_restrictEquiv_symm {L : W →ₗ[ℝ] V} {Lg : V →ₗ[ℝ] W} (hLg : ∀ w, Lg (L w) = w)
    {p0 : V} {g : V ≃ᵃ[ℝ] V}
    (hg : ∀ x ∈ Set.range (chart L p0),
      g x ∈ Set.range (chart L p0) ∧ g.symm x ∈ Set.range (chart L p0)) (w : W) :
    chart L p0 ((restrictEquiv hLg hg).symm w) = g.symm (chart L p0 w) := by
  have h := chart_restrictEquiv hLg hg ((restrictEquiv hLg hg).symm w)
  rw [AffineEquiv.apply_symm_apply] at h
  rw [h, AffineEquiv.symm_apply_apply]

/-- The automorphisms of the body that preserve the chart's range, restricted to the chart. -/
def autR (L : W →ₗ[ℝ] V) (p0 : V) (G : Set (V ≃ᵃ[ℝ] V)) : Set (W ≃ᵃ[ℝ] W) :=
  {g' | ∃ g ∈ G, ∀ w, chart L p0 (g' w) = g (chart L p0 w)}

theorem seedTransport_restrict {L : W →ₗ[ℝ] V} (p0 : V) (r : V →ᵃ[ℝ] ℝ) {g : V ≃ᵃ[ℝ] V}
    {g' : W ≃ᵃ[ℝ] W} (hgg : ∀ w, chart L p0 (g' w) = g (chart L p0 w)) :
    seedTransport (effR L p0 r) g' = effR L p0 (seedTransport r g) := by
  have hsymm : ∀ w, chart L p0 (g'.symm w) = g.symm (chart L p0 w) := fun w => by
    have h := hgg (g'.symm w)
    rw [AffineEquiv.apply_symm_apply] at h
    rw [h, AffineEquiv.symm_apply_apply]
  ext w
  rw [seedTransport_apply, effR_apply, effR_apply, hsymm, seedTransport_apply]

/-- **The restriction is premise-free.** For a body inside a chart of its affine span, the named
hypotheses restrict to the chart, with every automorphism of `G` restricted to an intertwining
automorphism of the chart. -/
theorem hypotheses_restrict {L : W →ₗ[ℝ] V} (hL : LinearMap.ker L = ⊥) {p0 : V} {Ω : Set V}
    (hspan : ∀ x, x ∈ affineSpan ℝ Ω ↔ x ∈ Set.range (chart L p0)) {G : Set (V ≃ᵃ[ℝ] V)}
    {r : V →ᵃ[ℝ] ℝ} {avail : Set (V →ᵃ[ℝ] ℝ)} (hG : PreservesBody Ω G) (hP1 : SharpSeed Ω r)
    (hK : BoundaryTransitive Ω G) (hV4 : SeedOrbitAvailable G r avail) :
    (∀ g ∈ G, ∃ g' ∈ autR L p0 G, ∀ w, chart L p0 (g' w) = g (chart L p0 w)) ∧
      PreservesBody (bodyR L p0 Ω) (autR L p0 G) ∧ SharpSeed (bodyR L p0 Ω) (effR L p0 r) ∧
      BoundaryTransitive (bodyR L p0 Ω) (autR L p0 G) ∧
      SeedOrbitAvailable (autR L p0 G) (effR L p0 r) (effR L p0 '' avail) := by
  have hΩ : Ω ⊆ Set.range (chart L p0) := fun x hx =>
    (hspan x).1 (subset_affineSpan ℝ Ω hx)
  obtain ⟨Lg, hLg⟩ := exists_chart_leftInverse hL
  have hinj := chart_injective hL p0
  refine ⟨fun g hg => ?_, ?_, sharpSeed_restrict L hΩ hP1, ?_, ?_⟩
  · have hr := fun x hx => range_preserved hspan hG hg (x := x) hx
    exact ⟨restrictEquiv hLg hr, ⟨g, hg, chart_restrictEquiv hLg hr⟩,
      chart_restrictEquiv hLg hr⟩
  · rintro g' ⟨g, hg, hgg⟩ w hw
    have hsymm : chart L p0 (g'.symm w) = g.symm (chart L p0 w) := by
      have h := hgg (g'.symm w)
      rw [AffineEquiv.apply_symm_apply] at h
      rw [h, AffineEquiv.symm_apply_apply]
    refine ⟨?_, ?_⟩
    · show chart L p0 (g' w) ∈ Ω
      rw [hgg]
      exact (hG g hg _ hw).1
    · show chart L p0 (g'.symm w) ∈ Ω
      rw [hsymm]
      exact (hG g hg _ hw).2
  · intro u v hu hv
    rw [isBoundaryState_restrict hL hΩ] at hu hv
    obtain ⟨g, hg, hgu⟩ := hK _ _ hu hv
    have hr := fun x hx => range_preserved hspan hG hg (x := x) hx
    refine ⟨restrictEquiv hLg hr, ⟨g, hg, chart_restrictEquiv hLg hr⟩, hinj ?_⟩
    rw [chart_restrictEquiv, hgu]
  · rintro g' ⟨g, hg, hgg⟩
    rw [seedTransport_restrict p0 r hgg]
    exact ⟨_, hV4 g hg, rfl⟩

/-! ### §E — the words of `ball3Drive` are boundary-transitive on `ball3` -/

/-- The words of the landed control drive: rotations about the third axis and the cyclic
permutation of the axes. -/
def driveWords3 : Set ((Fin 3 → ℝ) ≃ᵃ[ℝ] (Fin 3 → ℝ)) :=
  words (Set.range ball3Drive.flow ∪ {ball3Drive.J})

theorem rot3_mem_driveWords3 (t : ℝ) : rot3 t ∈ driveWords3 :=
  subset_words _ (Or.inl ⟨t, rfl⟩)

theorem cyc3_mem_driveWords3 : cyc3 ∈ driveWords3 :=
  subset_words _ (Or.inr rfl)

/-- The rotation by `θ` about the first axis, as a word: `cyc3 · rot3 θ · cyc3⁻¹`. -/
noncomputable def rotX (θ : ℝ) : (Fin 3 → ℝ) ≃ᵃ[ℝ] (Fin 3 → ℝ) := cyc3 * rot3 θ * cyc3⁻¹

theorem rotX_mem_driveWords3 (θ : ℝ) : rotX θ ∈ driveWords3 :=
  mul_mem_words (mul_mem_words cyc3_mem_driveWords3 (rot3_mem_driveWords3 θ))
    (inv_mem_words cyc3_mem_driveWords3)

/-- The word `rot3 ψ · rotX θ` carries the pole `(0, 0, 1)` to
`(sin ψ sin θ, - cos ψ sin θ, cos θ)`. -/
theorem euler_apply_pole (ψ θ : ℝ) :
    (rot3 ψ * rotX θ) ![0, 0, 1] =
      ![Real.sin ψ * Real.sin θ, -(Real.cos ψ * Real.sin θ), Real.cos θ] := by
  have e0 : (![0, 0, 1] : Fin 3 → ℝ) 0 = 0 := rfl
  have e1 : (![0, 0, 1] : Fin 3 → ℝ) 1 = 0 := rfl
  have e2 : (![0, 0, 1] : Fin 3 → ℝ) 2 = 1 := rfl
  rw [mul_apply', rotX, mul_apply', mul_apply', inv_apply']
  obtain ⟨c0, c1, c2⟩ := cyc3_symm_apply ![0, 0, 1]
  obtain ⟨a0, a1, a2⟩ := rotFun_apply θ (cyc3.symm ![0, 0, 1])
  obtain ⟨d0, d1, d2⟩ := cyc3_apply (rotFun θ (cyc3.symm ![0, 0, 1]))
  obtain ⟨b0, b1, b2⟩ := rotFun_apply ψ (cyc3 (rotFun θ (cyc3.symm ![0, 0, 1])))
  simp only [rot3_apply]
  apply vec3_ext
  · rw [b0, d0, d1, a2, a0, c0, c1, c2, e0, e1, e2]
    show _ = Real.sin ψ * Real.sin θ
    ring
  · rw [b1, d0, d1, a2, a0, c0, c1, c2, e0, e1, e2]
    show _ = -(Real.cos ψ * Real.sin θ)
    ring
  · rw [b2, d2, a1, c0, c1, e1, e2]
    show _ = Real.cos θ
    ring

/-- Polar angle for a unit vector: every point of the unit sphere is `(sin ψ sin θ,
-cos ψ sin θ, cos θ)` for some angles. -/
theorem exists_euler_angles {b : Fin 3 → ℝ} (hb : b 0 ^ 2 + b 1 ^ 2 + b 2 ^ 2 = 1) :
    ∃ ψ θ : ℝ, Real.sin ψ * Real.sin θ = b 0 ∧ -(Real.cos ψ * Real.sin θ) = b 1 ∧
      Real.cos θ = b 2 := by
  have hb2 : b 2 ^ 2 ≤ 1 := by nlinarith [sq_nonneg (b 0), sq_nonneg (b 1)]
  have hb2abs := (abs_le.mp ((sq_le_one_iff_abs_le_one (b 2)).mp hb2))
  set s := Real.sqrt (1 - b 2 ^ 2) with hs
  have hs0 : 0 ≤ s := Real.sqrt_nonneg _
  have hss : s ^ 2 = b 0 ^ 2 + b 1 ^ 2 := by
    rw [hs, Real.sq_sqrt (by linarith)]
    linarith
  have hθs : Real.sin (Real.arccos (b 2)) = s := Real.sin_arccos _
  have hθc : Real.cos (Real.arccos (b 2)) = b 2 := Real.cos_arccos hb2abs.1 hb2abs.2
  rcases eq_or_lt_of_le hs0 with hs00 | hspos
  · have hsum : b 0 ^ 2 + b 1 ^ 2 = 0 := by rw [← hss, ← hs00]; ring
    have hq0 : b 0 ^ 2 = 0 := by nlinarith [sq_nonneg (b 0), sq_nonneg (b 1)]
    have hq1 : b 1 ^ 2 = 0 := by nlinarith [sq_nonneg (b 0), sq_nonneg (b 1)]
    have h0 : b 0 = 0 := (pow_eq_zero_iff two_ne_zero).mp hq0
    have h1 : b 1 = 0 := (pow_eq_zero_iff two_ne_zero).mp hq1
    refine ⟨0, Real.arccos (b 2), ?_, ?_, hθc⟩
    · rw [hθs, ← hs00, h0]; ring
    · rw [hθs, ← hs00, h1]; ring
  · set c := -(b 1) / s with hc
    have hs2 : s ^ 2 ≠ 0 := (pow_pos hspos 2).ne'
    have hunit : (b 0 / s) ^ 2 + c ^ 2 = 1 := by
      rw [hc, div_pow, div_pow, neg_sq, ← add_div, div_eq_one_iff_eq hs2]
      linarith
    have hc2 : c ^ 2 ≤ 1 := by nlinarith [sq_nonneg (b 0 / s)]
    have hcabs := (abs_le.mp ((sq_le_one_iff_abs_le_one c).mp hc2))
    have hsq : 1 - c ^ 2 = (b 0 / s) ^ 2 := by linarith
    have hsinα : Real.sin (Real.arccos c) = |b 0 / s| := by
      rw [Real.sin_arccos, hsq, Real.sqrt_sq_eq_abs]
    have hcosα : Real.cos (Real.arccos c) = c := Real.cos_arccos hcabs.1 hcabs.2
    rcases le_or_gt 0 (b 0) with hb0 | hb0
    · refine ⟨Real.arccos c, Real.arccos (b 2), ?_, ?_, hθc⟩
      · rw [hsinα, hθs, abs_of_nonneg (div_nonneg hb0 hs0), div_mul_cancel₀ _ hspos.ne']
      · rw [hcosα, hθs, hc, div_mul_cancel₀ _ hspos.ne']
        ring
    · refine ⟨-Real.arccos c, Real.arccos (b 2), ?_, ?_, hθc⟩
      · rw [Real.sin_neg, hsinα, hθs, abs_of_neg (div_neg_of_neg_of_pos hb0 hspos),
          neg_neg, div_mul_cancel₀ _ hspos.ne']
      · rw [Real.cos_neg, hcosα, hθs, hc, div_mul_cancel₀ _ hspos.ne']
        ring

/-- Every point of the unit sphere is reached from the pole by a word of `ball3Drive`. -/
theorem exists_word_pole {b : Fin 3 → ℝ} (hb : b 0 ^ 2 + b 1 ^ 2 + b 2 ^ 2 = 1) :
    ∃ g ∈ driveWords3, g ![0, 0, 1] = b := by
  obtain ⟨ψ, θ, h0, h1, h2⟩ := exists_euler_angles hb
  refine ⟨rot3 ψ * rotX θ, mul_mem_words (rot3_mem_driveWords3 ψ) (rotX_mem_driveWords3 θ), ?_⟩
  rw [euler_apply_pole]
  exact vec3_ext h0 h1 h2

/-- **`ball3Drive` is boundary-transitive.** The words of the landed control drive carry any
boundary state of `ball3` to any other. -/
theorem boundaryTransitive_ball3Drive : BoundaryTransitive ball3 driveWords3 := by
  intro u w hu hw
  obtain ⟨gu, hgu, hgu1⟩ := exists_word_pole (sphere_of_isBoundaryState_ball3 hu)
  obtain ⟨gw, hgw, hgw1⟩ := exists_word_pole (sphere_of_isBoundaryState_ball3 hw)
  refine ⟨gw * gu⁻¹, mul_mem_words hgw (inv_mem_words hgu), ?_⟩
  rw [mul_apply', inv_apply', ← hgu1, AffineEquiv.symm_apply_apply, hgw1]

theorem preservesBody_driveWords3 : PreservesBody ball3 driveWords3 :=
  preservesBody_driveWords ball3Drive

/-- **The reduced theorem applies to the control drive.** For any sharp seed on `ball3`, the
transports along the words of `ball3Drive` are exactly the directional effects. -/
theorem seedOrbit_ball3Drive {r : (Fin 3 → ℝ) →ᵃ[ℝ] ℝ} (hP1 : SharpSeed ball3 r) :
    seedOrbit driveWords3 r = directionalFamily :=
  seedOrbit_ball3_eq preservesBody_driveWords3 hP1 boundaryTransitive_ball3Drive

/-! ### §F — the countercontrol: boundary transitivity in dimension four -/

/-- In any real normed space, the boundary states of the closed unit ball are its unit vectors. -/
theorem isBoundaryState_closedBall_iff {x : V} :
    IsBoundaryState (Metric.closedBall (0 : V) 1) x ↔ ‖x‖ = 1 := by
  constructor
  · rintro ⟨hx, y, hy, hout⟩
    rw [Metric.mem_closedBall, dist_zero_right] at hx hy
    by_contra hne
    have hlt : ‖x‖ < 1 := lt_of_le_of_ne hx hne
    apply hout ((1 - ‖x‖) / 4) (by linarith)
    rw [Metric.mem_closedBall, dist_zero_right]
    have hxy : ‖x - y‖ ≤ 2 := (norm_sub_le x y).trans (by linarith)
    calc ‖x + ((1 - ‖x‖) / 4) • (x - y)‖ ≤ ‖x‖ + ‖((1 - ‖x‖) / 4) • (x - y)‖ := norm_add_le _ _
      _ = ‖x‖ + (1 - ‖x‖) / 4 * ‖x - y‖ := by
          rw [norm_smul, Real.norm_of_nonneg (by linarith)]
      _ ≤ ‖x‖ + (1 - ‖x‖) / 4 * 2 := by
          have := mul_le_mul_of_nonneg_left hxy (by linarith : (0 : ℝ) ≤ (1 - ‖x‖) / 4)
          linarith
      _ ≤ 1 := by linarith
  · intro hx
    refine ⟨by rw [Metric.mem_closedBall, dist_zero_right]; exact hx.le, -x,
      by rw [Metric.mem_closedBall, dist_zero_right, norm_neg]; exact hx.le, fun ε hε hmem => ?_⟩
    rw [Metric.mem_closedBall, dist_zero_right] at hmem
    have : x + ε • (x - -x) = (1 + 2 * ε) • x := by module
    rw [this, norm_smul, hx, mul_one, Real.norm_of_nonneg (by linarith)] at hmem
    linarith

/-- The four-dimensional Euclidean space. -/
abbrev E4 := EuclideanSpace ℝ (Fin 4)

/-- The closed unit ball of `E4`. -/
def ball4 : Set E4 := Metric.closedBall 0 1

/-- The isometries of `E4`, as affine automorphisms. -/
def isom4 : Set (E4 ≃ᵃ[ℝ] E4) :=
  {g | ∃ R : E4 ≃ₗᵢ[ℝ] E4, ∀ x, g x = R x}

theorem preservesBody_isom4 : PreservesBody ball4 isom4 := by
  rintro g ⟨R, hR⟩ x hx
  rw [ball4, Metric.mem_closedBall, dist_zero_right] at hx
  have hRs : ∀ y, g.symm y = R.symm y := fun y => by
    apply g.injective
    rw [AffineEquiv.apply_symm_apply, hR, LinearIsometryEquiv.apply_symm_apply]
  refine ⟨?_, ?_⟩
  · rw [ball4, Metric.mem_closedBall, dist_zero_right, hR, LinearIsometryEquiv.norm_map]
    exact hx
  · rw [ball4, Metric.mem_closedBall, dist_zero_right, hRs, LinearIsometryEquiv.norm_map]
    exact hx

/-- **The countercontrol.** The isometries of `E4` act transitively on the boundary of its unit
ball: boundary transitivity holds in dimension four. -/
theorem boundaryTransitive_ball4 : BoundaryTransitive ball4 isom4 := by
  intro u w hu hw
  rw [ball4, isBoundaryState_closedBall_iff] at hu hw
  set R : E4 ≃ₗᵢ[ℝ] E4 := Submodule.reflection (ℝ ∙ (u - w))ᗮ with hRdef
  refine ⟨R.toLinearEquiv.toAffineEquiv, ⟨R, fun x => rfl⟩, ?_⟩
  show R u = w
  exact Submodule.reflection_sub (hu.trans hw.symm)

/-- The body of the countercontrol has dimension four. -/
theorem finrank_E4 : Module.finrank ℝ E4 = 4 := finrank_euclideanSpace_fin

theorem zero_mem_interior_ball4 : (0 : E4) ∈ interior ball4 := by
  rw [ball4]
  exact mem_interior.2 ⟨Metric.ball 0 1, Metric.ball_subset_closedBall, Metric.isOpen_ball,
    Metric.mem_ball_self one_pos⟩

/-! ### §G — the verdict -/

theorem og1_infrastructure_core :
    (∀ (Ω : Set V) (S : Set (V ≃ᵃ[ℝ] V)), PreservesBody Ω S → PreservesBody Ω (words S)) ∧
    (∀ flow : ℝ → V ≃ᵃ[ℝ] V, (∀ s t, flow (s + t) = (flow t).trans (flow s)) →
      flow 0 = AffineEquiv.refl ℝ V) ∧
    (∀ (Ω : Set V) (T : V ≃ᵃ[ℝ] (Fin 3 → ℝ)) (G : Set (V ≃ᵃ[ℝ] V)) (r : V →ᵃ[ℝ] ℝ),
      T '' Ω = ball3 → PreservesBody Ω G → SharpSeed Ω r → BoundaryTransitive Ω G →
      seedOrbit G r = {f | ∃ b : Fin 3 → ℝ, b 0 ^ 2 + b 1 ^ 2 + b 2 ^ 2 = 1 ∧
        f = (ballEffect b).comp T.toAffineMap}) ∧
    BoundaryTransitive ball3 driveWords3 ∧
    PreservesBody ball3 driveWords3 ∧
    BoundaryTransitive ball4 isom4 ∧
    PreservesBody ball4 isom4 ∧
    Module.finrank ℝ E4 = 4 := by
  refine ⟨fun Ω S h => preservesBody_words h, fun flow h => flow_zero_of_add flow h,
    fun Ω T G r hT hG hP1 hK => seedOrbit_eq_of_normalization T hT hG hP1 hK,
    boundaryTransitive_ball3Drive, preservesBody_driveWords3, boundaryTransitive_ball4,
    preservesBody_isom4, finrank_E4⟩

end OrbitNormalization
end OIBridge

#print axioms OIBridge.OrbitNormalization.preservesBody_words
#print axioms OIBridge.OrbitNormalization.preservesBody_driveWords
#print axioms OIBridge.OrbitNormalization.flow_zero_of_add
#print axioms OIBridge.OrbitNormalization.isEmpty_drivability_of_finite_orbits
#print axioms OIBridge.OrbitNormalization.isBoundaryState_tr
#print axioms OIBridge.OrbitNormalization.hypotheses_tr
#print axioms OIBridge.OrbitNormalization.seedOrbit_eq_of_normalization
#print axioms OIBridge.OrbitNormalization.lorentz_of_normalization
#print axioms OIBridge.OrbitNormalization.isBoundaryState_restrict
#print axioms OIBridge.OrbitNormalization.affineSpan_preserved
#print axioms OIBridge.OrbitNormalization.chart_restrictEquiv
#print axioms OIBridge.OrbitNormalization.hypotheses_restrict
#print axioms OIBridge.OrbitNormalization.euler_apply_pole
#print axioms OIBridge.OrbitNormalization.exists_euler_angles
#print axioms OIBridge.OrbitNormalization.boundaryTransitive_ball3Drive
#print axioms OIBridge.OrbitNormalization.seedOrbit_ball3Drive
#print axioms OIBridge.OrbitNormalization.isBoundaryState_closedBall_iff
#print axioms OIBridge.OrbitNormalization.boundaryTransitive_ball4
#print axioms OIBridge.OrbitNormalization.finrank_E4
#print axioms OIBridge.OrbitNormalization.og1_infrastructure_core
