/-
  OIBridge/ReachabilitySeam.lean — the compact-Lie interface audit: the last external boundary
  item pinned to one sharply formulated analytic lemma, with everything around it internal.

  ROUND FORTY-NINE. `ControlLie.lean` (round nineteen) records, and does not claim, "the
  Lie-closure equality for the closure of the generated subgroup (the closed-subgroup /
  analytic-subgroup step), and the criterion 𝔏₀ = su(D) ⟹ universal unitary control up to
  phase"; `MonoidalCompletion.lean` consumes the criterion as `UniversalUnitaryReachability`,
  and `HasCompositeUnitaryControl` is its composite form. Neither is a dependency of the
  completion classification (`GeneralCarrier.main_result`), which assumes full control
  outright. This file audits the seam before proving anything, in the distinctions the owner
  named:

      · the Lie algebra of the CLOSURE of the generated subgroup versus the COMPUTED
        dynamical Lie algebra `controlLie H U` — the closed-subgroup step, not needed by
        any consumer and not formalized here;
      · connected-component reachability — supplied internally: the matrix unitary group
        is connected (every unitary is a global phase times a unitary at distance `< 2`
        from `1`, by finiteness of the spectrum; `exists_phase_joined`);
      · EXACT reachability versus DENSITY — the consumers need exact availability of every
        unitary conjugation channel, so density cannot discharge them
        (`dense_of_exact` is the only implication that holds without work);
      · `SU(D)` versus `U(D)` and the global-phase direction — invisible to conjugation
        channels (`conjChannel_smul`), and every unitary is a unit phase times a special
        unitary (`exists_special_phase`), so the traceless target `su(D)` of `HControl` is
        the right one.

  THE REACHABLE SUBGROUP. `reachable H U` is the subgroup of the topological group
  `unitary (Matrix S S ℂ)` generated by the passive flows `e^{-itH}` (all real `t`), the
  controls `U_g`, and the global phases. It contains every conjugated flow
  (`conjugatedFlow_mem_reachable`, the round-nineteen identity), so the generators of
  `controlLie H U` are reachable directions.

  THE REDUCTION, kernel-internal:

      LocalReachability H U   :=  reachable H U is a neighbourhood of 1
        ⟹  ExactReachability H U  (open subgroup ⟹ clopen ⟹ contains the identity
                                    component; connectedness of the unitary group)
        ⟹  UniversalUnitaryReachability avail  (words of available channels are available).

  THE ANALYTIC LEMMA, isolated (`LocalReachabilityOfLieRank`): if `controlLie H U ⊇ su(D)`
  then `reachable H U` is a neighbourhood of `1`. This is the orbit theorem of geometric
  control (Chow–Rashevskii / Sussmann) at the identity of a compact matrix group; the pinned
  Mathlib carries the matrix exponential, its derivative, the inverse-function theorem, and
  the local homeomorphism `exp`/`arg` near `1` in the unitary group, but not the theorem
  itself. It is recorded as the single remaining external item, named, and consumed exactly
  where it is used (`universalReachability_of_lieRank`). Nothing else in the seam is
  external.

      ┌──────────────────────────────────────────────────────────────────────────────┐
      │  `exact_of_local`: LocalReachability ⟹ ExactReachability.                      │
      │  `universalReachability_of_exact`: ExactReachability ⟹ every unitary channel   │
      │      available, given the word closure of availability.                        │
      │  `universalReachability_of_lieRank (hstep : LocalReachabilityOfLieRank S)`:    │
      │      𝔏 ⊇ su(D) ⟹ universal unitary reachability — the round-nineteen           │
      │      criterion, conditional on the one named lemma only.                       │
      │  `noControls_central_not_exact`: with no controls and a central drift, the      │
      │      reachable group is the phases alone — the seam is not vacuous.            │
      └──────────────────────────────────────────────────────────────────────────────┘

  THE BOUNDARY AUDIT: unchanged in count (ONE ITEM), sharpened in statement — the item is
  `LocalReachabilityOfLieRank`, and the completion classification does not depend on it.

  WHAT IS AND IS NOT CLAIMED. Proved: everything above except the named lemma, with the usual
  axiom footprint. NOT claimed: `LocalReachabilityOfLieRank`; the closed-subgroup Lie-closure
  equality; that `HControl` is necessary for exact reachability (controls are group elements
  and can generate independently of `H`); anything about non-compact or infinite-dimensional
  settings. No structure field is added.

  Kernel check:  cd verification/lean-mathlib && lake exe cache get && lake build
-/
import OIBridge.UhlmannUniqueness
import Mathlib.Analysis.CStarAlgebra.Unitary.Connected
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.Topology.Algebra.OpenSubgroup

namespace OIBridge
namespace ReachabilitySeam

open Complex Matrix ControlLie MonoidalCompletion
open scoped ComplexOrder Matrix.Norms.L2Operator

variable {S : Type} [Fintype S] [DecidableEq S] {G : Type}

/-! ### Section A — the passive flow is unitary -/

/-- The passive flow `e^{-itH}`. -/
noncomputable def flow (H : Matrix S S ℂ) (t : ℝ) : Matrix S S ℂ :=
  NormedSpace.exp ((-(t : ℂ) * Complex.I) • H)

omit [Fintype S] [DecidableEq S] in
theorem flow_skewAdjoint_gen (H : Matrix S S ℂ) (hH : Hᴴ = H) (t : ℝ) :
    (-(t : ℂ) * Complex.I) • H ∈ skewAdjoint (Matrix S S ℂ) := by
  rw [skewAdjoint.mem_iff, Matrix.star_eq_conjTranspose, Matrix.conjTranspose_smul, hH,
    ← neg_smul]
  congr 1
  simp only [star_mul', star_neg, Complex.star_def, Complex.conj_ofReal, Complex.conj_I]
  ring

theorem mem_unitary_of_conjTranspose_mul {V : Matrix S S ℂ} (hV : Vᴴ * V = 1) :
    V ∈ unitary (Matrix S S ℂ) := by
  rw [Unitary.mem_iff, Matrix.star_eq_conjTranspose]
  exact ⟨hV, mul_eq_one_comm.mp hV⟩

theorem flow_mem_unitary (H : Matrix S S ℂ) (hH : Hᴴ = H) (t : ℝ) :
    flow H t ∈ unitary (Matrix S S ℂ) := by
  refine mem_unitary_of_conjTranspose_mul ?_
  have hA : ((-(t : ℂ) * Complex.I) • H)ᴴ = -((-(t : ℂ) * Complex.I) • H) := by
    have := skewAdjoint.mem_iff.mp (flow_skewAdjoint_gen H hH t)
    rwa [Matrix.star_eq_conjTranspose] at this
  have hc : Commute (-((-(t : ℂ) * Complex.I) • H)) ((-(t : ℂ) * Complex.I) • H) :=
    (Commute.refl ((-(t : ℂ) * Complex.I) • H)).neg_left
  rw [flow, ← Matrix.exp_conjTranspose, hA, ← Matrix.exp_add_of_commute _ _ hc, neg_add_cancel,
    NormedSpace.exp_zero]

/-! ### Section B — the reachable subgroup -/

/-- The global phases `λ · 1`, `|λ| = 1`, as unitaries. -/
def phaseSet : Set (unitary (Matrix S S ℂ)) :=
  {u | ∃ lam : ℂ, ‖lam‖ = 1 ∧ (u : Matrix S S ℂ) = lam • (1 : Matrix S S ℂ)}

/-- The generators: the passive flows, the controls, and the phases. -/
def generators (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) : Set (unitary (Matrix S S ℂ)) :=
  {u | ∃ t : ℝ, (u : Matrix S S ℂ) = flow H t} ∪ {u | ∃ g : G, (u : Matrix S S ℂ) = U g}
    ∪ phaseSet

/-- **THE REACHABLE SUBGROUP**: all finite words in the flows, the controls, their inverses,
and the phases. -/
noncomputable def reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) :
    Subgroup (unitary (Matrix S S ℂ)) :=
  Subgroup.closure (generators H U)

theorem flow_mem_reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (hH : Hᴴ = H) (t : ℝ) :
    (⟨flow H t, flow_mem_unitary H hH t⟩ : unitary (Matrix S S ℂ)) ∈ reachable H U :=
  Subgroup.subset_closure (Or.inl (Or.inl ⟨t, rfl⟩))

theorem control_mem_reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (g : G)
    (hg : U g ∈ unitary (Matrix S S ℂ)) :
    (⟨U g, hg⟩ : unitary (Matrix S S ℂ)) ∈ reachable H U :=
  Subgroup.subset_closure (Or.inl (Or.inr ⟨g, rfl⟩))

theorem smul_one_mem_unitary {lam : ℂ} (h : ‖lam‖ = 1) :
    lam • (1 : Matrix S S ℂ) ∈ unitary (Matrix S S ℂ) := by
  have hl : star lam * lam = 1 := by
    rw [Complex.star_def, ← Complex.normSq_eq_conj_mul_self, Complex.normSq_eq_norm_sq, h]
    norm_num
  refine mem_unitary_of_conjTranspose_mul ?_
  rw [Matrix.conjTranspose_smul, Matrix.conjTranspose_one, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.one_mul, smul_smul, hl, one_smul]

theorem phase_mem_reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) {lam : ℂ}
    (h : ‖lam‖ = 1) :
    (⟨lam • (1 : Matrix S S ℂ), smul_one_mem_unitary h⟩ : unitary (Matrix S S ℂ))
      ∈ reachable H U :=
  Subgroup.subset_closure (Or.inr ⟨lam, h, rfl⟩)

theorem conj_mem_unitary {V W : Matrix S S ℂ} (hV : V ∈ unitary (Matrix S S ℂ))
    (hW : W ∈ unitary (Matrix S S ℂ)) : V * W * Vᴴ ∈ unitary (Matrix S S ℂ) := by
  rw [← Matrix.star_eq_conjTranspose]
  exact mul_mem (mul_mem hV hW) (Unitary.star_mem hV)

/-- **THE CONJUGATED FLOWS ARE REACHABLE**: `U_g e^{-itH} U_g† ∈ reachable`, so every
generator `-i U_g H U_g†` of the control Lie algebra is a reachable direction. -/
theorem conjugatedFlow_mem_reachable (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (hH : Hᴴ = H)
    (g : G) (hg : U g ∈ unitary (Matrix S S ℂ)) (t : ℝ) :
    (⟨U g * flow H t * (U g)ᴴ, conj_mem_unitary hg (flow_mem_unitary H hH t)⟩ :
      unitary (Matrix S S ℂ)) ∈ reachable H U := by
  have h := mul_mem (mul_mem (control_mem_reachable H U g hg) (flow_mem_reachable H U hH t))
    (inv_mem (control_mem_reachable H U g hg))
  convert h using 1
  ext
  simp [Matrix.star_eq_conjTranspose]

/-! ### Section C — the distinctions, as named predicates -/

/-- **LOCAL REACHABILITY**: the reachable subgroup is a neighbourhood of the identity. -/
def LocalReachability (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) : Prop :=
  ((reachable H U : Subgroup (unitary (Matrix S S ℂ))) : Set (unitary (Matrix S S ℂ)))
    ∈ nhds (1 : unitary (Matrix S S ℂ))

/-- **EXACT REACHABILITY**: every unitary is a finite word. -/
def ExactReachability (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) : Prop :=
  ∀ u : unitary (Matrix S S ℂ), u ∈ reachable H U

/-- **DENSE REACHABILITY**: every unitary is a limit of finite words. -/
def DenseReachability (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) : Prop :=
  ∀ u : unitary (Matrix S S ℂ),
    u ∈ closure ((reachable H U : Subgroup (unitary (Matrix S S ℂ))) : Set (unitary (Matrix S S ℂ)))

theorem dense_of_exact {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (h : ExactReachability H U) :
    DenseReachability H U :=
  fun u => subset_closure (h u)

/-! ### Section D — the matrix unitary group is connected -/

/-- A unit-modulus complex number outside any finite set. -/
theorem exists_unit_notMem_finite {F : Set ℂ} (hF : F.Finite) : ∃ μ : ℂ, ‖μ‖ = 1 ∧ μ ∉ F := by
  have hinf : ({μ : ℂ | ‖μ‖ = 1}).Infinite := by
    refine Set.infinite_of_injOn_mapsTo (f := fun θ : ℝ => ((Circle.exp θ : Circle) : ℂ))
      (s := Set.Ico 0 (2 * Real.pi)) ?_ ?_ (Set.Ico_infinite (by positivity))
    · intro x hx y hy hxy
      exact Circle.exp_injOn_Ico (by simp) hx hy (Circle.coe_injective hxy)
    · intro θ _
      exact Circle.norm_coe _
  obtain ⟨μ, hμ, hμF⟩ := (hinf.sdiff hF).nonempty
  exact ⟨μ, hμ, hμF⟩

theorem inv_smul_mem_unitary {lam : ℂ} (h : ‖lam‖ = 1) (u : unitary (Matrix S S ℂ)) :
    lam⁻¹ • (u : Matrix S S ℂ) ∈ unitary (Matrix S S ℂ) := by
  have h' : ‖lam⁻¹‖ = 1 := by rw [norm_inv, h, inv_one]
  have := mul_mem (smul_one_mem_unitary (S := S) h') u.2
  simpa [Matrix.smul_mul, Matrix.one_mul] using this

/-- **EVERY UNITARY IS A PHASE TIMES A UNITARY JOINED TO `1`**: the spectrum is finite, so a
unit phase moves `-1` out of it, and Mathlib's `Unitary.joined` supplies the path. -/
theorem exists_phase_joined (u : unitary (Matrix S S ℂ)) :
    ∃ (lam : ℂ) (w : unitary (Matrix S S ℂ)), ‖lam‖ = 1 ∧ Joined (1 : unitary (Matrix S S ℂ)) w
      ∧ (u : Matrix S S ℂ) = lam • (w : Matrix S S ℂ) := by
  obtain ⟨ν, hν, hνF⟩ := exists_unit_notMem_finite (Matrix.finite_spectrum (u : Matrix S S ℂ))
  set lam : ℂ := -ν with hlam
  have hlam1 : ‖lam‖ = 1 := by rw [hlam, norm_neg, hν]
  have hlam0 : lam ≠ 0 := by
    intro h0
    rw [h0, norm_zero] at hlam1
    exact zero_ne_one hlam1
  let w : unitary (Matrix S S ℂ) := ⟨lam⁻¹ • (u : Matrix S S ℂ), inv_smul_mem_unitary hlam1 u⟩
  refine ⟨lam, w, hlam1, ?_, ?_⟩
  · -- `-1` is not in the spectrum of `w`, so `‖w - 1‖ < 2`
    have hspec : (-1 : ℂ) ∉ spectrum ℂ (w : Matrix S S ℂ) := by
      intro hmem
      have hw : (w : Matrix S S ℂ) = (Units.mk0 lam⁻¹ (inv_ne_zero hlam0)) • (u : Matrix S S ℂ) := rfl
      rw [hw, spectrum.unit_smul_eq_smul, Set.mem_smul_set_iff_inv_smul_mem] at hmem
      apply hνF
      convert hmem using 1
      simp [hlam, Units.smul_def]
    have hlt : ‖((w : unitary (Matrix S S ℂ)) : Matrix S S ℂ) - 1‖ < 2 :=
      (Unitary.norm_sub_one_lt_two_iff w.2).mpr hspec
    exact Unitary.joined 1 w (by simpa using hlt)
  · show (u : Matrix S S ℂ) = lam • (lam⁻¹ • (u : Matrix S S ℂ))
    rw [smul_smul, mul_inv_cancel₀ hlam0, one_smul]

/-- **LOCAL ⟹ EXACT**: an open subgroup is clopen, hence contains the identity component;
every unitary is a phase times an element of that component. -/
theorem exact_of_local {H : Matrix S S ℂ} {U : G → Matrix S S ℂ} (hloc : LocalReachability H U) :
    ExactReachability H U := by
  intro u
  have hopen : IsOpen ((reachable H U : Subgroup _) : Set (unitary (Matrix S S ℂ))) :=
    Subgroup.isOpen_of_mem_nhds _ hloc
  have hclopen : IsClopen ((reachable H U : Subgroup _) : Set (unitary (Matrix S S ℂ))) :=
    ⟨Subgroup.isClosed_of_isOpen _ hopen, hopen⟩
  obtain ⟨lam, w, hlam, hj, hu⟩ := exists_phase_joined u
  have hw : w ∈ reachable H U :=
    IsClopen.connectedComponent_subset hclopen (one_mem _) (pathComponent_subset_component _ hj)
  have hp := phase_mem_reachable H U (S := S) hlam
  have hu' : u = ⟨lam • (1 : Matrix S S ℂ), smul_one_mem_unitary hlam⟩ * w := by
    ext
    simp [hu]
  rw [hu']
  exact mul_mem hp hw

/-! ### Section E — the global phase is invisible; `SU(D)` suffices -/

omit [DecidableEq S] in
/-- Conjugation channels do not see global phases. -/
theorem conjChannel_smul {lam : ℂ} (h : ‖lam‖ = 1) (V : Matrix S S ℂ) :
    conjChannel (lam • V) = conjChannel V := by
  have hl : lam * star lam = 1 := by
    rw [Complex.star_def, Complex.mul_conj, Complex.normSq_eq_norm_sq, h]
    norm_num
  refine LinearMap.ext fun X => ?_
  show (lam • V) * X * (lam • V)ᴴ = V * X * Vᴴ
  rw [Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.smul_mul, Matrix.mul_smul, smul_smul,
    hl, one_smul]

/-- The determinant of a unitary has unit modulus. -/
theorem norm_det_unitary {V : Matrix S S ℂ} (hV : Vᴴ * V = 1) : ‖V.det‖ = 1 := by
  have h := congrArg Matrix.det hV
  rw [Matrix.det_mul, Matrix.det_conjTranspose, Matrix.det_one, Complex.star_def,
    ← Complex.normSq_eq_conj_mul_self, Complex.normSq_eq_norm_sq] at h
  have h' : ‖V.det‖ ^ 2 = 1 := by exact_mod_cast h
  exact (pow_left_inj₀ (norm_nonneg _) zero_le_one two_ne_zero).mp (by simpa using h')

/-- **EVERY UNITARY IS A UNIT PHASE TIMES A SPECIAL UNITARY**: the traceless target `su(D)`
of `HControl` is the right one, since the phase direction is invisible to channels. -/
theorem exists_special_phase [Nonempty S] {V : Matrix S S ℂ} (hV : Vᴴ * V = 1) :
    ∃ (lam : ℂ) (V₀ : Matrix S S ℂ), ‖lam‖ = 1 ∧ V₀ᴴ * V₀ = 1 ∧ V₀.det = 1 ∧ V = lam • V₀ := by
  have hd1 := norm_det_unitary hV
  have hd0 : V.det ≠ 0 := by
    intro h0; rw [h0, norm_zero] at hd1; exact zero_ne_one hd1
  have hD : (Fintype.card S : ℂ) ≠ 0 := by exact_mod_cast Fintype.card_ne_zero
  set lam : ℂ := Complex.exp (Complex.log V.det / Fintype.card S) with hlam
  have hlamD : lam ^ Fintype.card S = V.det := by
    rw [hlam, ← Complex.exp_nat_mul, mul_div_cancel₀ _ hD, Complex.exp_log hd0]
  have hlam1 : ‖lam‖ = 1 := by
    have hre : (Complex.log V.det / (Fintype.card S : ℂ)).re = 0 := by
      rw [Complex.div_natCast_re, Complex.log_re, hd1, Real.log_one, zero_div]
    rw [hlam, Complex.norm_exp, hre, Real.exp_zero]
  have hlam0 : lam ≠ 0 := Complex.exp_ne_zero _
  have hl : star lam⁻¹ * lam⁻¹ = 1 := by
    rw [Complex.star_def, ← Complex.normSq_eq_conj_mul_self, Complex.normSq_eq_norm_sq,
      norm_inv, hlam1]
    norm_num
  refine ⟨lam, lam⁻¹ • V, hlam1, ?_, ?_, ?_⟩
  · rw [Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.mul_smul, smul_smul, hl, one_smul, hV]
  · rw [Matrix.det_smul, ← hlamD, inv_pow, inv_mul_cancel₀ (pow_ne_zero _ hlam0)]
  · rw [smul_smul, mul_inv_cancel₀ hlam0, one_smul]

/-! ### Section F — exact reachability delivers the consumers' universal reachability -/

set_option maxHeartbeats 800000 in
/-- Words in the generators are available as channels, given the closure hypotheses. -/
theorem avail_of_mem_closure (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (avail : ∀ m : ℕ, (Fin m → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) → Prop)
    (hmul : ∀ V W : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel W) → avail 1 (fun _ => conjChannel (V * W)))
    (hstar : ∀ V : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel Vᴴ))
    (hone : avail 1 (fun _ => conjChannel (1 : Matrix S S ℂ)))
    (hflow : ∀ t : ℝ, avail 1 (fun _ => conjChannel (flow H t)))
    (hctrl : ∀ g : G, avail 1 (fun _ => conjChannel (U g)))
    (x : unitary (Matrix S S ℂ)) (hx : x ∈ Subgroup.closure (generators H U)) :
    avail 1 (fun _ => conjChannel (x : Matrix S S ℂ)) := by
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with (⟨t, hx⟩ | ⟨g, hx⟩) | ⟨lam, hlam, hx⟩
    · rw [hx]; exact hflow t
    · rw [hx]; exact hctrl g
    · rw [hx, conjChannel_smul hlam]; exact hone
  | one => rw [OneMemClass.coe_one]; exact hone
  | mul x y _ _ hx hy => rw [Submonoid.coe_mul]; exact hmul _ _ hx hy
  | inv x _ hx =>
    rw [← Unitary.star_eq_inv, Unitary.coe_star, Matrix.star_eq_conjTranspose]
    exact hstar _ hx

/-- **EXACT ⟹ UNIVERSAL**: if the flows and controls are available as channels and
availability is closed under composition and reversal, then exact reachability makes every
unitary channel available. -/
theorem universalReachability_of_exact (H : Matrix S S ℂ) (U : G → Matrix S S ℂ)
    (avail : ∀ m : ℕ, (Fin m → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) → Prop)
    (hmul : ∀ V W : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel W) → avail 1 (fun _ => conjChannel (V * W)))
    (hstar : ∀ V : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel Vᴴ))
    (hone : avail 1 (fun _ => conjChannel (1 : Matrix S S ℂ)))
    (hflow : ∀ t : ℝ, avail 1 (fun _ => conjChannel (flow H t)))
    (hctrl : ∀ g : G, avail 1 (fun _ => conjChannel (U g)))
    (hex : ExactReachability H U) : UniversalUnitaryReachability avail :=
  fun V hV => avail_of_mem_closure H U avail hmul hstar hone hflow hctrl
    ⟨V, mem_unitary_of_conjTranspose_mul hV⟩ (hex _)

/-! ### Section G — the analytic lemma, isolated, and the criterion -/

/-- **THE ANALYTIC-SUBGROUP STEP, ISOLATED.** If the dynamical Lie algebra contains `su(D)`,
the reachable subgroup is a neighbourhood of the identity. This is the orbit theorem of
geometric control at the identity of a compact matrix group; it is the single remaining
external boundary item, consumed only by `universalReachability_of_lieRank`. -/
def LocalReachabilityOfLieRank (S : Type) [Fintype S] [DecidableEq S] : Prop :=
  ∀ (G : Type) (H : Matrix S S ℂ) (U : G → Matrix S S ℂ), Hᴴ = H →
    (∀ g, (U g)ᴴ * U g = 1) → HControl H U → LocalReachability H U

/-- **THE ROUND-NINETEEN CRITERION**, conditional on the one named lemma only:
`𝔏 ⊇ su(D)` gives universal unitary reachability. -/
theorem universalReachability_of_lieRank (hstep : LocalReachabilityOfLieRank S)
    (H : Matrix S S ℂ) (U : G → Matrix S S ℂ) (hH : Hᴴ = H) (hU : ∀ g, (U g)ᴴ * U g = 1)
    (hLie : HControl H U)
    (avail : ∀ m : ℕ, (Fin m → Matrix S S ℂ →ₗ[ℂ] Matrix S S ℂ) → Prop)
    (hmul : ∀ V W : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel W) → avail 1 (fun _ => conjChannel (V * W)))
    (hstar : ∀ V : Matrix S S ℂ, avail 1 (fun _ => conjChannel V)
      → avail 1 (fun _ => conjChannel Vᴴ))
    (hone : avail 1 (fun _ => conjChannel (1 : Matrix S S ℂ)))
    (hflow : ∀ t : ℝ, avail 1 (fun _ => conjChannel (flow H t)))
    (hctrl : ∀ g : G, avail 1 (fun _ => conjChannel (U g))) :
    UniversalUnitaryReachability avail :=
  universalReachability_of_exact H U avail hmul hstar hone hflow hctrl
    (exact_of_local (hstep G H U hH hU hLie))

/-! ### Section H — the seam is not vacuous -/

set_option maxHeartbeats 800000 in
/-- With no controls and a central drift, every word in the generators is a scalar. -/
theorem noControls_central_scalar_of_mem_closure (c : ℝ) (x : unitary (Matrix S S ℂ))
    (hx : x ∈ Subgroup.closure (generators ((c : ℂ) • (1 : Matrix S S ℂ))
      (fun g : Empty => g.elim))) :
    ∃ lam : ℂ, (x : Matrix S S ℂ) = lam • (1 : Matrix S S ℂ) := by
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with (⟨t, hx⟩ | ⟨g, _⟩) | ⟨lam, _, hx⟩
    · refine ⟨NormedSpace.exp (-(t : ℂ) * Complex.I * c), ?_⟩
      rw [hx, flow, smul_smul, ← Algebra.algebraMap_eq_smul_one, ← NormedSpace.algebraMap_exp_comm,
        Algebra.algebraMap_eq_smul_one]
    · exact g.elim
    · exact ⟨lam, hx⟩
  | one => exact ⟨1, by simp⟩
  | mul x y _ _ hx hy =>
    obtain ⟨a, ha⟩ := hx
    obtain ⟨b, hb⟩ := hy
    exact ⟨a * b, by rw [Submonoid.coe_mul, ha, hb, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.one_mul, smul_smul]⟩
  | inv x _ hx =>
    obtain ⟨a, ha⟩ := hx
    refine ⟨star a, ?_⟩
    rw [← Unitary.star_eq_inv, Unitary.coe_star, ha, Matrix.star_eq_conjTranspose,
      Matrix.conjTranspose_smul, Matrix.conjTranspose_one]

/-- With no controls and a central drift, every reachable unitary is a scalar. -/
theorem noControls_central_reachable_scalar (c : ℝ) {u : unitary (Matrix S S ℂ)}
    (hu : u ∈ reachable ((c : ℂ) • (1 : Matrix S S ℂ)) (fun g : Empty => g.elim)) :
    ∃ lam : ℂ, (u : Matrix S S ℂ) = lam • (1 : Matrix S S ℂ) :=
  noControls_central_scalar_of_mem_closure c u hu

/-- The swap on a two-level system, a unitary that is not a scalar. -/
def swap2 : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]

theorem swap2_unitary : swap2ᴴ * swap2 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [swap2, Matrix.mul_apply, Fin.sum_univ_two]

theorem swap2_not_scalar (lam : ℂ) : swap2 ≠ lam • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  intro h
  have := congrFun (congrFun h 0) 1
  simp [swap2] at this

/-- **THE SEAM IS NOT VACUOUS**: with no controls and a central drift, exact reachability
fails on a qubit — the reachable group is the phases alone. -/
theorem noControls_central_not_exact (c : ℝ) :
    ¬ ExactReachability ((c : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)) (fun g : Empty => g.elim) := by
  intro h
  obtain ⟨lam, hlam⟩ := noControls_central_reachable_scalar c
    (h ⟨swap2, mem_unitary_of_conjTranspose_mul swap2_unitary⟩)
  exact swap2_not_scalar lam hlam

#print axioms flow_skewAdjoint_gen
#print axioms flow_mem_unitary
#print axioms mem_unitary_of_conjTranspose_mul
#print axioms flow_mem_reachable
#print axioms control_mem_reachable
#print axioms smul_one_mem_unitary
#print axioms phase_mem_reachable
#print axioms conj_mem_unitary
#print axioms conjugatedFlow_mem_reachable
#print axioms dense_of_exact
#print axioms exists_unit_notMem_finite
#print axioms inv_smul_mem_unitary
#print axioms exists_phase_joined
#print axioms exact_of_local
#print axioms conjChannel_smul
#print axioms norm_det_unitary
#print axioms exists_special_phase
#print axioms avail_of_mem_closure
#print axioms universalReachability_of_exact
#print axioms universalReachability_of_lieRank
#print axioms noControls_central_scalar_of_mem_closure
#print axioms noControls_central_reachable_scalar
#print axioms swap2_unitary
#print axioms swap2_not_scalar
#print axioms noControls_central_not_exact

end ReachabilitySeam
end OIBridge
