/-
  OIBridge/StructuralClosure.lean — the substratum-source audit, fourth entry: structural
  closure of the substratum architecture.

  ROUND SIXTY-FOUR. Round 61 reduced the primitive-source question to one object — a quantum
  architecture: an implementation class closed under the theory operations, context-stable,
  label-invariant, dagger-stable, and driving the elementary transitions. Rounds 62 and 63
  settled the decisive fifth ingredient for the current axioms: the substratum supplies only
  monomial operators, and read-write coupling does not supply the off-diagonal generator. This
  file audits the FOUR STRUCTURAL ingredients for the class the substratum actually supplies,
  and returns the honest answer for each: all four close, and nothing is completed by
  definition.

  THE CLASS IS THE SUPPLIED CLASS, NOT A HULL. The round-62 interface records that the
  substratum's direct interventions — bijective dynamics (A2) and phase — and the round-63
  read-write couplings have monomial observable operators: `permMatrix σ * diagonal d`, a
  permutation of a diagonal, the weights permitted to vanish (as the readout projectors
  require). The substratum class of this file (`substratumClass`) is exactly that predicate,
  `IsMonomial`, so every operator in it is supplied by an intervention followed by a diagonal
  weighting, and no operator is added to obtain closure.

  THE ELEMENTWISE FORM. A matrix is monomial if and only if it has at most one nonzero entry in
  every row and in every column (`IsSubmonomial`, `monomial_iff_submonomial`). The direction
  monomial ⇒ submonomial is a reading of the entries; the converse extends the partial injection
  "column ↦ row of its nonzero entry" to a permutation of the finite carrier by matching the
  complements, which have equal cardinality. The elementwise form is what makes the closure
  audit a computation on entries rather than on permutations.

  THE FOUR CLOSURES.
    (1) ARCHITECTURE CLOSURE — the identity is monomial, a product of monomials is monomial (a
        nonzero entry of `K * L` picks one nonzero entry of `K` and one of `L`, and the row and
        column conditions of each transfer), scalar multiples are monomial, the readout
        projectors are diagonal, and every ancilla block of a monomial is monomial
        (`substratumClass_arch`).
    (2) CONTEXT STABILITY — `1_R ⊗ K` has a nonzero entry only where the spectator indices
        agree and `K` is nonzero (`substratumClass_contextStable`).
    (3) LABEL INVARIANCE — relabelling a carrier permutes rows and columns together
        (`substratumClass_labelInvariant`).
    (4) DAGGER STABILITY — the adjoint exchanges the row and column conditions
        (`substratumClass_daggerStable`); physically, the reversal of a bijective intervention
        is the inverse bijection (`bijectiveOperator_conjTranspose`) and the reversal of a phase
        is its conjugate (`phaseOperator_conjTranspose`), both of which A2 and the phase
        structure supply.

  THE RESIDUAL. For a structurally closed class, being a quantum architecture is exactly
  driving the elementary transitions (`quantumArchitecture_iff_drives_of_closed`). The
  substratum class is structurally closed but generates no composite unitary control — every
  monomial conjugation preserves the diagonal and the rotation `rot` does not — so its
  generated theory is not quantum mechanics (`substratumGen_not_qm`), it does not drive the
  elementary transitions (`substratumClass_not_drivesElementary`), and it is not a quantum
  architecture (`substratumClass_not_quantumArchitecture`). The closure audit therefore returns
  `substratum_residual`: four closures, one residual, and the residual is exactly the
  off-diagonal controllability that rounds 62 and 63 showed the current axioms do not supply.

  THE ENDPOINT. Any structurally closed extension of the substratum class is a quantum
  architecture exactly when it drives the elementary transitions
  (`substratum_extension_quantum_iff_drives`); such an extension generates finite operational
  quantum mechanics on every nonempty carrier (`substratum_plus_control_qm`); and finite
  operational quantum mechanics is generated by a quantum architecture extending the substratum
  class (`qm_generated_by_substratum_extension`). In one line:

      ┌──────────────────────────────────────────────────────────────────────────────┐
      │  current OI substratum + continuous off-diagonal controllability             │
      │      ⟺  finite operational quantum mechanics.                                 │
      └──────────────────────────────────────────────────────────────────────────────┘

  WHAT IS NOT CLAIMED. No operation is supplied by fiat: the class is the round-62 predicate
  and every closure is a theorem about it. The controllability side of the endpoint is a
  hypothesis on an extension, not a property of the current substratum — the current substratum
  does not have it (`substratumClass_not_drivesElementary`), and no control law is postulated to
  obtain it. Nothing here modifies the frozen OI⁺ statements. The compact-semigroup redundancy of
  the inverse clause and the minimal elementary repertoire remain open.
-/

import OIBridge.ReadWriteControl

namespace OIBridge
namespace StructuralClosure

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource InterventionLocality
open MicroReversibility LieRankSource SubstratumSource SubstratumInterface ReadWriteControl

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — the elementwise form of the supplied class -/

section Elementwise

variable {S : Type}

/-- **THE ELEMENTWISE FORM**: at most one nonzero entry in every row and in every column. -/
def IsSubmonomial (K : Matrix S S ℂ) : Prop :=
  (∀ i j j', K i j ≠ 0 → K i j' ≠ 0 → j = j') ∧ (∀ i i' j, K i j ≠ 0 → K i' j ≠ 0 → i = i')

/-- A nonzero conditional entry forces its condition. -/
theorem of_ite_ne_zero {p : Prop} [Decidable p] {x : ℂ} (h : (if p then x else 0) ≠ 0) : p := by
  by_contra hp
  rw [if_neg hp] at h
  exact h rfl

variable [Fintype S] [DecidableEq S]

omit [DecidableEq S] in
/-- A nonzero entry of a product picks a nonzero entry of each factor. -/
theorem mul_entry_ne_zero {K L : Matrix S S ℂ} {i j : S} (h : (K * L) i j ≠ 0) :
    ∃ k, K i k ≠ 0 ∧ L k j ≠ 0 := by
  rw [Matrix.mul_apply] at h
  obtain ⟨k, -, hk⟩ := Finset.exists_ne_zero_of_sum_ne_zero h
  exact ⟨k, mul_ne_zero_iff.mp hk⟩

/-- **MONOMIAL ⇒ SUBMONOMIAL**: a permutation of a diagonal has at most one nonzero entry per
row and per column. -/
theorem monomial_submonomial {K : Matrix S S ℂ} (h : IsMonomial K) : IsSubmonomial K := by
  obtain ⟨σ, d, rfl⟩ := h
  refine ⟨fun i j j' h1 h2 => ?_, fun i i' j h1 h2 => ?_⟩
  · rw [monomial_entry] at h1 h2
    exact σ.injective ((of_ite_ne_zero h1).trans (of_ite_ne_zero h2).symm)
  · rw [monomial_entry] at h1 h2
    exact (of_ite_ne_zero h1).symm.trans (of_ite_ne_zero h2)

/-- **SUBMONOMIAL ⇒ MONOMIAL**: the partial injection "column ↦ row of its nonzero entry"
extends to a permutation of the finite carrier by matching the complements, which have equal
cardinality; the diagonal weight is the entry the permutation selects. -/
theorem submonomial_monomial {K : Matrix S S ℂ} (h : IsSubmonomial K) : IsMonomial K := by
  classical
  let p : S → Prop := fun t => ∃ s, K s t ≠ 0
  let q : S → Prop := fun s => ∃ t, K s t ≠ 0
  let f : {t // p t} → {s // q s} :=
    fun t => ⟨Classical.choose t.2, ⟨t.1, Classical.choose_spec t.2⟩⟩
  have hf : ∀ t : {t // p t}, K (f t).1 t.1 ≠ 0 := fun t => Classical.choose_spec t.2
  have finj : Function.Injective f := by
    intro t t' ht
    have h1 := hf t
    have h2 := hf t'
    rw [ht] at h1
    exact Subtype.ext (h.1 _ _ _ h1 h2)
  have fsurj : Function.Surjective f := by
    rintro ⟨s, t, hst⟩
    refine ⟨⟨t, s, hst⟩, Subtype.ext ?_⟩
    exact h.2 _ _ _ (hf ⟨t, s, hst⟩) hst
  let e₁ : {t // p t} ≃ {s // q s} := Equiv.ofBijective f ⟨finj, fsurj⟩
  have hcard : Fintype.card {t // ¬ p t} = Fintype.card {s // ¬ q s} := by
    rw [Fintype.card_subtype_compl, Fintype.card_subtype_compl, Fintype.card_congr e₁]
  let e₂ : {t // ¬ p t} ≃ {s // ¬ q s} := Fintype.equivOfCardEq hcard
  let σ : Equiv.Perm S :=
    (Equiv.sumCompl p).symm.trans ((e₁.sumCongr e₂).trans (Equiv.sumCompl q))
  have hσ : ∀ (t : S) (ht : p t), σ t = (e₁ ⟨t, ht⟩).1 := by
    intro t ht
    simp only [σ, Equiv.trans_apply, Equiv.sumCompl_symm_apply_of_pos ht]
    rfl
  refine ⟨σ, fun t => K (σ t) t, ?_⟩
  ext i j
  rw [monomial_entry]
  by_cases hij : σ j = i
  · rw [if_pos hij, hij]
  · rw [if_neg hij]
    by_contra hne
    have hj : p j := ⟨i, hne⟩
    have hsel : K (σ j) j ≠ 0 := by rw [hσ j hj]; exact hf ⟨j, hj⟩
    exact hij (h.2 _ _ _ hsel hne)

/-- **THE TWO FORMS AGREE.** -/
theorem monomial_iff_submonomial (K : Matrix S S ℂ) : IsMonomial K ↔ IsSubmonomial K :=
  ⟨monomial_submonomial, submonomial_monomial⟩

end Elementwise

/-! ### Section B — the substratum class and its four closures -/

section Closure

/-- **THE SUBSTRATUM CLASS**: exactly the operators the round-62 interface records as supplied
by the substratum's interventions — the monomials. Nothing is added to obtain closure. -/
def substratumClass : ImplementationClass := fun _ _ _ K => IsMonomial K

/-- **STRUCTURAL CLOSURE**: the four structural ingredients of a quantum architecture. -/
structure StructurallyClosed (𝓘 : ImplementationClass) : Prop where
  arch : Architecture 𝓘
  context : ContextStable 𝓘
  label : LabelInvariant 𝓘
  dagger : DaggerStable 𝓘

variable {S : Type} [Fintype S] [DecidableEq S]

theorem submonomial_one : IsSubmonomial (1 : Matrix S S ℂ) := by
  have h := monomial_submonomial (monomial_permMatrix (1 : Equiv.Perm S))
  rwa [permMatrix_one'] at h

omit [DecidableEq S] in
/-- **PRODUCTS**: a nonzero entry of `K * L` selects one nonzero entry of `K` and one of `L`. -/
theorem submonomial_mul {K L : Matrix S S ℂ} (hK : IsSubmonomial K) (hL : IsSubmonomial L) :
    IsSubmonomial (K * L) := by
  refine ⟨fun i j j' h1 h2 => ?_, fun i i' j h1 h2 => ?_⟩
  · obtain ⟨k, hk1, hk2⟩ := mul_entry_ne_zero h1
    obtain ⟨k', hk1', hk2'⟩ := mul_entry_ne_zero h2
    have hkk : k = k' := hK.1 _ _ _ hk1 hk1'
    subst hkk
    exact hL.1 _ _ _ hk2 hk2'
  · obtain ⟨k, hk1, hk2⟩ := mul_entry_ne_zero h1
    obtain ⟨k', hk1', hk2'⟩ := mul_entry_ne_zero h2
    have hkk : k = k' := hL.2 _ _ _ hk2 hk2'
    subst hkk
    exact hK.2 _ _ _ hk1 hk1'

omit [Fintype S] [DecidableEq S] in
theorem submonomial_smul (a : ℂ) {K : Matrix S S ℂ} (hK : IsSubmonomial K) :
    IsSubmonomial (a • K) := by
  have key : ∀ i j, (a • K) i j ≠ 0 → K i j ≠ 0 := fun i j h => by
    rw [Matrix.smul_apply, smul_eq_mul] at h
    exact (mul_ne_zero_iff.mp h).2
  exact ⟨fun i j j' h1 h2 => hK.1 i j j' (key _ _ h1) (key _ _ h2),
    fun i i' j h1 h2 => hK.2 i i' j (key _ _ h1) (key _ _ h2)⟩

theorem submonomial_diagonal (d : S → ℂ) : IsSubmonomial (Matrix.diagonal d) :=
  monomial_submonomial (monomial_diagonal d)

omit [Fintype S] [DecidableEq S] in
/-- **ANCILLA BLOCKS**: a block of a submonomial is submonomial. -/
theorem submonomial_block {m : ℕ} {K : Matrix (S × Fin m) (S × Fin m) ℂ}
    (hK : IsSubmonomial K) (f e : Fin m) : IsSubmonomial (ancBlock K f e) :=
  ⟨fun s t t' h1 h2 => congrArg Prod.fst (hK.1 (s, f) (t, e) (t', e) h1 h2),
   fun s s' t h1 h2 => congrArg Prod.fst (hK.2 (s, f) (s', f) (t, e) h1 h2)⟩

/-- **(1) ARCHITECTURE CLOSURE**: the substratum class is closed under the theory operations. -/
theorem substratumClass_arch : Architecture substratumClass where
  one := fun _ _ _ => submonomial_monomial submonomial_one
  mul := fun _ _ _ _ _ hK hL =>
    submonomial_monomial (submonomial_mul (monomial_submonomial hK) (monomial_submonomial hL))
  smul := fun _ _ _ a _ hK => submonomial_monomial (submonomial_smul a (monomial_submonomial hK))
  proj := fun _ _ _ _ _ => monomial_diagonal _
  block := fun _ _ _ _ _ f e hK =>
    submonomial_monomial (submonomial_block (monomial_submonomial hK) f e)

omit [Fintype S] [DecidableEq S] in
/-- A nonzero entry of `1_R ⊗ K` has agreeing spectator indices and a nonzero entry of `K`. -/
theorem tensor_one_entry_ne_zero {R : Type} [Fintype R] [DecidableEq R] {K : Matrix S S ℂ}
    {p q : R × S} (h : tensorOf (1 : Matrix R R ℂ) K p q ≠ 0) : p.1 = q.1 ∧ K p.2 q.2 ≠ 0 := by
  rw [tensorOf_apply] at h
  obtain ⟨h1, h2⟩ := mul_ne_zero_iff.mp h
  refine ⟨?_, h2⟩
  by_contra hne
  exact h1 (Matrix.one_apply_ne hne)

theorem submonomial_tensor_one {R : Type} [Fintype R] [DecidableEq R] {K : Matrix S S ℂ}
    (hK : IsSubmonomial K) : IsSubmonomial (tensorOf (1 : Matrix R R ℂ) K) := by
  refine ⟨fun p q q' h1 h2 => ?_, fun p p' q h1 h2 => ?_⟩
  · obtain ⟨e1, k1⟩ := tensor_one_entry_ne_zero h1
    obtain ⟨e2, k2⟩ := tensor_one_entry_ne_zero h2
    exact Prod.ext (e1.symm.trans e2) (hK.1 _ _ _ k1 k2)
  · obtain ⟨e1, k1⟩ := tensor_one_entry_ne_zero h1
    obtain ⟨e2, k2⟩ := tensor_one_entry_ne_zero h2
    exact Prod.ext (e1.trans e2.symm) (hK.2 _ _ _ k1 k2)

/-- **(2) CONTEXT STABILITY**: an uncoupled spectator leaves the class. -/
theorem substratumClass_contextStable : ContextStable substratumClass := by
  intro _ _ _ _ _ _ _ hK
  exact submonomial_monomial (submonomial_tensor_one (monomial_submonomial hK))

omit [Fintype S] [DecidableEq S] in
theorem submonomial_reindex {S' : Type} [Fintype S'] [DecidableEq S'] (e : S ≃ S')
    {K : Matrix S S ℂ} (hK : IsSubmonomial K) : IsSubmonomial (Matrix.reindex e e K) := by
  refine ⟨fun p q q' h1 h2 => ?_, fun p p' q h1 h2 => ?_⟩
  · rw [Matrix.reindex_apply, Matrix.submatrix_apply] at h1 h2
    exact e.symm.injective (hK.1 _ _ _ h1 h2)
  · rw [Matrix.reindex_apply, Matrix.submatrix_apply] at h1 h2
    exact e.symm.injective (hK.2 _ _ _ h1 h2)

/-- **(3) LABEL INVARIANCE**: admissibility is transported along carrier bijections. -/
theorem substratumClass_labelInvariant : LabelInvariant substratumClass := by
  intro _ _ _ _ _ _ e _ hK
  exact submonomial_monomial (submonomial_reindex e (monomial_submonomial hK))

omit [Fintype S] [DecidableEq S] in
theorem submonomial_conjTranspose {K : Matrix S S ℂ} (hK : IsSubmonomial K) :
    IsSubmonomial Kᴴ := by
  have key : ∀ i j, Kᴴ i j ≠ 0 → K j i ≠ 0 := fun i j h => by
    rw [Matrix.conjTranspose_apply] at h
    exact star_ne_zero.mp h
  exact ⟨fun i j j' h1 h2 => hK.2 j j' i (key _ _ h1) (key _ _ h2),
    fun i i' j h1 h2 => hK.1 j i i' (key _ _ h1) (key _ _ h2)⟩

/-- **(4) DAGGER STABILITY**: the adjoint exchanges the row and column conditions. -/
theorem substratumClass_daggerStable : DaggerStable substratumClass := by
  intro _ _ _ _ hK
  exact submonomial_monomial (submonomial_conjTranspose (monomial_submonomial hK))

omit [Fintype S] in
/-- **A2 SUPPLIES THE REVERSAL OF A BIJECTIVE INTERVENTION**: its adjoint is the inverse
bijection. -/
theorem bijectiveOperator_conjTranspose (σ : Equiv.Perm S) :
    (bijectiveOperator σ)ᴴ = bijectiveOperator σ⁻¹ :=
  permMatrix_conjTranspose σ

omit [Fintype S] in
/-- **THE PHASE STRUCTURE SUPPLIES THE REVERSAL OF A PHASE**: its adjoint is the conjugate
phase. -/
theorem phaseOperator_conjTranspose (d : S → ℂ) : (phaseOperator d)ᴴ = phaseOperator (star d) :=
  Matrix.diagonal_conjTranspose d

/-- **THE SUBSTRATUM CLASS IS STRUCTURALLY CLOSED**: all four closures hold. -/
theorem substratumClass_structurallyClosed : StructurallyClosed substratumClass where
  arch := substratumClass_arch
  context := substratumClass_contextStable
  label := substratumClass_labelInvariant
  dagger := substratumClass_daggerStable

end Closure

/-! ### Section C — what the interface supplies lies in the class -/

section Supplied

variable {S : Type} [Fintype S] [DecidableEq S]

theorem bijectiveOperator_supplied (σ : Equiv.Perm S) : substratumClass S (bijectiveOperator σ) :=
  bijectiveOperator_monomial σ

theorem phaseOperator_supplied (d : S → ℂ) : substratumClass S (phaseOperator d) :=
  phaseOperator_monomial d

theorem readWriteOperator_supplied {a b : S} (F : ReadWriteFamily a b) (l : ℝ) :
    substratumClass S (readWriteOperator F l) :=
  readWriteOperator_monomial F l

end Supplied

/-! ### Section D — the residual: closed, but not quantum -/

section Residual

/-- **THE SUBSTRATUM THEORY HAS NO COMPOSITE UNITARY CONTROL**: every monomial conjugation
preserves the diagonal and the rotation `rot` does not. -/
theorem substratumGen_not_control :
    ¬ HasCompositeUnitaryControl (genTheory substratumClass substratumClass_arch (Fin 2)) := by
  intro h
  obtain ⟨ι, _, K, hK, hadm⟩ := (h 1 rot rot_isometry).1 ()
  have hK' : conjChannel rot = ∑ i, conjChannel (K i) := hK
  apply rot_not_preservesDiag
  rw [hK']
  exact preservesDiag_sum _ _ fun i _ => preservesDiag_conj_of_monomial (hadm i)

/-- **THE SUBSTRATUM THEORY IS NOT FINITE OPERATIONAL QM.** -/
theorem substratumGen_not_qm :
    ¬ ExactAllFiniteEndomorphicQuantumOps (genTheory substratumClass substratumClass_arch (Fin 2)) :=
  fun h => substratumGen_not_control (physical_of_exactAll _ h).2.2.1

/-- **FOR A STRUCTURALLY CLOSED CLASS, QUANTUM IS EXACTLY DRIVING.** -/
theorem quantumArchitecture_iff_drives_of_closed {𝓘 : ImplementationClass}
    (hc : StructurallyClosed 𝓘) : QuantumArchitecture 𝓘 ↔ DrivesElementary 𝓘 :=
  ⟨fun hq => hq.drives, fun hd => ⟨hc.arch, hc.context, hc.label, hc.dagger, hd⟩⟩

/-- **THE SUBSTRATUM CLASS DOES NOT DRIVE THE ELEMENTARY TRANSITIONS**: if it did, it would be
a quantum architecture and its generated theory would be quantum mechanics. -/
theorem substratumClass_not_drivesElementary : ¬ DrivesElementary substratumClass := by
  intro hd
  have hq : QuantumArchitecture substratumClass :=
    (quantumArchitecture_iff_drives_of_closed substratumClass_structurallyClosed).mpr hd
  exact substratumGen_not_qm (genTheory_qm_of_quantumArchitecture (A := Fin 2) hq)

theorem substratumClass_not_quantumArchitecture : ¬ QuantumArchitecture substratumClass :=
  fun hq => substratumClass_not_drivesElementary hq.drives

/-- **THE CLOSURE AUDIT**: four closures, one residual. The substratum class is an
architecture, context-stable, label-invariant and dagger-stable; it does not drive the
elementary transitions, is not a quantum architecture, and its generated theory is not finite
operational quantum mechanics. -/
theorem substratum_residual :
    Architecture substratumClass ∧ ContextStable substratumClass
      ∧ LabelInvariant substratumClass ∧ DaggerStable substratumClass
      ∧ ¬ DrivesElementary substratumClass
      ∧ ¬ QuantumArchitecture substratumClass
      ∧ ¬ ExactAllFiniteEndomorphicQuantumOps
          (genTheory substratumClass substratumClass_arch (Fin 2)) :=
  ⟨substratumClass_arch, substratumClass_contextStable, substratumClass_labelInvariant,
    substratumClass_daggerStable, substratumClass_not_drivesElementary,
    substratumClass_not_quantumArchitecture, substratumGen_not_qm⟩

end Residual

/-! ### Section E — the endpoint: substratum plus controllability is quantum mechanics -/

section Endpoint

/-- An implementation class extends the substratum class. -/
def ExtendsSubstratum (𝓘 : ImplementationClass) : Prop :=
  ∀ (S : Type) [Fintype S] [DecidableEq S] (K : Matrix S S ℂ), substratumClass S K → 𝓘 S K

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **A STRUCTURALLY CLOSED EXTENSION OF THE SUBSTRATUM IS QUANTUM EXACTLY WHEN IT DRIVES**
the elementary transitions. -/
theorem substratum_extension_quantum_iff_drives {𝓘 : ImplementationClass}
    (_ : ExtendsSubstratum 𝓘) (hc : StructurallyClosed 𝓘) :
    QuantumArchitecture 𝓘 ↔ DrivesElementary 𝓘 :=
  quantumArchitecture_iff_drives_of_closed hc

/-- **SUBSTRATUM PLUS CONTROLLABILITY GENERATES QUANTUM MECHANICS** on every nonempty carrier. -/
theorem substratum_plus_control_qm [Nonempty A] {𝓘 : ImplementationClass}
    (_ : ExtendsSubstratum 𝓘) (hc : StructurallyClosed 𝓘) (hd : DrivesElementary 𝓘) :
    ExactAllFiniteEndomorphicQuantumOps (genTheory 𝓘 hc.arch A) :=
  genTheory_qm_of_quantumArchitecture ⟨hc.arch, hc.context, hc.label, hc.dagger, hd⟩

theorem fullClass_extendsSubstratum : ExtendsSubstratum fullClass :=
  fun _ _ _ _ _ => trivial

/-- **QUANTUM MECHANICS IS GENERATED BY A QUANTUM ARCHITECTURE EXTENDING THE SUBSTRATUM.** -/
theorem qm_generated_by_substratum_extension [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) :
    ∃ 𝓘 : ImplementationClass, ExtendsSubstratum 𝓘 ∧ StructurallyClosed 𝓘
      ∧ DrivesElementary 𝓘 ∧ ImplementationGenerated T 𝓘 :=
  ⟨fullClass, fullClass_extendsSubstratum,
    ⟨fullClass_arch, fullClass_contextStable, fullClass_labelInvariant, fullClass_daggerStable⟩,
    fullClass_drivesElementary, generated_of_qm T h⟩

end Endpoint

#print axioms of_ite_ne_zero
#print axioms mul_entry_ne_zero
#print axioms monomial_submonomial
#print axioms submonomial_monomial
#print axioms monomial_iff_submonomial
#print axioms submonomial_one
#print axioms submonomial_mul
#print axioms submonomial_smul
#print axioms submonomial_diagonal
#print axioms submonomial_block
#print axioms substratumClass_arch
#print axioms tensor_one_entry_ne_zero
#print axioms submonomial_tensor_one
#print axioms substratumClass_contextStable
#print axioms submonomial_reindex
#print axioms substratumClass_labelInvariant
#print axioms submonomial_conjTranspose
#print axioms substratumClass_daggerStable
#print axioms bijectiveOperator_conjTranspose
#print axioms phaseOperator_conjTranspose
#print axioms substratumClass_structurallyClosed
#print axioms bijectiveOperator_supplied
#print axioms phaseOperator_supplied
#print axioms readWriteOperator_supplied
#print axioms substratumGen_not_control
#print axioms substratumGen_not_qm
#print axioms quantumArchitecture_iff_drives_of_closed
#print axioms substratumClass_not_drivesElementary
#print axioms substratumClass_not_quantumArchitecture
#print axioms substratum_residual
#print axioms substratum_extension_quantum_iff_drives
#print axioms substratum_plus_control_qm
#print axioms fullClass_extendsSubstratum
#print axioms qm_generated_by_substratum_extension

end StructuralClosure
end OIBridge
