/-
  OIBridge/SubstratumSource.lean — the substratum-source audit, first target: the three
  primitive-source principles collapsed onto one substratum object.

  ROUND SIXTY-ONE. The primitive-source audit (rounds 56-59) settled which structure selects
  quantum mechanics one level below the five operational conditions: reversible implementation
  locality, elementary transition richness, and embedded observation. The next question is
  whether that structure follows from the concrete physical realization of observation
  incompleteness, rather than from bare observation incompleteness as an abstract principle.
  This file takes the first step: it shows the three primitive-source principles are jointly
  supplied by ONE substratum object — an implementation architecture with four stability
  properties and one drivability property — and it isolates the single property that carries
  the physical content.

  THE OBJECT. An IMPLEMENTATION ARCHITECTURE (`Architecture`, round 59) is a class of
  admissible implementation operators closed under the operations every finite operational
  theory performs. A QUANTUM ARCHITECTURE (`QuantumArchitecture`) is one that is, in addition,

      · CONTEXT-STABLE — `𝓘 S K → 𝓘 (R × S) (1_R ⊗ K)` (round 57);
      · LABEL-INVARIANT — admissibility transported along carrier bijections (round 57);
      · DAGGER-STABLE — `𝓘 S K → 𝓘 S Kᴴ` (round 58);
      · ELEMENTARY-DRIVING (`DrivesElementary`) — at every carrier the transition flows, the
        state exchanges, and the quarter phases are admissible.

  THE COLLAPSE. A theory generated by a quantum architecture carries all three primitive-source
  principles at once: reversible implementation locality from the four stabilities
  (`genTheory_reversibleImplementationLocality`), elementary transition richness from
  drivability (`genTheory_elementary`), and embedded observation from label invariance
  (`genTheory_embeddedObservation`). Hence, on every nonempty finite carrier, a theory
  generated by a quantum architecture is exactly finite endomorphic operational quantum
  mechanics (`genTheory_qm_of_quantumArchitecture`), and finite operational QM is generated by
  one — the full class (`fullClass_quantumArchitecture`,
  `qm_generated_by_quantumArchitecture`). The physical question "which conditions select QM"
  becomes the single question "does the substratum supply one implementation architecture that
  is context-, label-, and dagger-stable and drives the elementary transitions".

  THE DECISIVE PROPERTY. Elementary drivability carries the content that the three stabilities
  do not. The DIAGONAL class is an architecture that is context-, label-, and dagger-stable
  (round 59) but NOT elementary-driving: the exchange of two distinguishable states is an
  off-diagonal operator, not admissible (`diagClass_not_drivesElementary`). Its generated
  theory is not quantum mechanics — it has no composite unitary control
  (`diagGen_not_quantumArchitectureGenerated`). So a substratum could supply a fully stable
  implementation architecture and still fail to be quantum; what it must additionally provide
  is a continuously drivable off-diagonal reversible transition between distinguishable states,
  the state exchanges, and a phase — the concrete controllability the abstract stabilities do
  not entail.

  WHAT IS NOT CLAIMED. This does not derive a quantum architecture from A1-A6 or from the
  read-write substratum dynamics; it reduces the three primitive-source principles to one
  object and names its decisive property, so that the remaining audit is whether the concrete
  OI physics supplies that object. The minimal drivability repertoire is that of round 59 and
  is not reduced further here. Nothing here bears on the open redundancy of the inverse clause.
-/

import OIBridge.LieRankSource

namespace OIBridge
namespace SubstratumSource

open Complex Matrix CoherentExtension MonoidalCompletion CoherentLift IndependenceCensus
open OperationalAssembly StinespringAssembly KrausSoundness CompositeSoundness
open DimensionalObstruction DimensionalCountermodel ReferenceExtension ReferenceSufficiency
open BoundaryAudit SpectatorBridge AncillaClosure ClosureObstruction CompositionalIndependence
open OIRealization OperationalValidity LevelOneSeam PhysicalCharacterization DiagonalTheory
open HiddenCoherence RankGapTheory GeneralCarrier ControlLie ReachabilitySeam OrbitReachability
open SubstantiveCensus OperationalRigidity OIHierarchy PrimitiveSource InterventionLocality
open MicroReversibility LieRankSource

open scoped ComplexOrder Kronecker Matrix.Norms.L2Operator

/-! ### Section A — elementary drivability and quantum architectures -/

section Architecture

/-- **ELEMENTARY DRIVABILITY**: at every carrier the transition flows, the state exchanges,
and the quarter phases are admissible implementations. -/
def DrivesElementary (𝓘 : ImplementationClass) : Prop :=
  (∀ (S : Type) [Fintype S] [DecidableEq S] (a b : S) (t : ℝ),
    𝓘 S (flow (transition a b) t))
  ∧ (∀ (S : Type) [Fintype S] [DecidableEq S] (a b : S),
    𝓘 S (permMatrix (Equiv.swap a b)))
  ∧ (∀ (S : Type) [Fintype S] [DecidableEq S] (a : S), 𝓘 S (phaseGate a))

/-- **A QUANTUM ARCHITECTURE**: an implementation architecture that is context-, label- and
dagger-stable and drives the elementary transitions. -/
structure QuantumArchitecture (𝓘 : ImplementationClass) : Prop where
  arch : Architecture 𝓘
  context : ContextStable 𝓘
  label : LabelInvariant 𝓘
  dagger : DaggerStable 𝓘
  drives : DrivesElementary 𝓘

end Architecture

/-! ### Section B — the generated theory drives the elementary transitions -/

section Elementary

variable {𝓘 : ImplementationClass} (arch : Architecture 𝓘)
variable {A : Type} [Fintype A] [DecidableEq A]

/-- A one-outcome conjugation by an admissible isometry is available in the generated theory. -/
theorem genTheory_avail_conj {n : ℕ} {V : Matrix (A × Fin n) (A × Fin n) ℂ}
    (hV : 𝓘 (A × Fin n) V) (hiso : Vᴴ * V = 1) :
    (genTheory 𝓘 arch A).availExt n Unit (fun _ => conjChannel V) :=
  ⟨fun _ => realized_conj hV, fun X => by rw [Fintype.sum_unique]; exact conjChannel_trace V hiso X⟩

/-- **THE GENERATED THEORY DRIVES THE ELEMENTARY TRANSITIONS** when the class does. -/
theorem genTheory_elementary (hd : DrivesElementary 𝓘) :
    ElementaryTransitionRichness (genTheory 𝓘 arch A) := by
  intro n
  refine ⟨fun a b _ t => ?_, fun a b => ?_, fun a => ?_⟩
  · exact genTheory_avail_conj arch (hd.1 _ a b t)
      (flow_isometry _ (transition_hermitian a b) t)
  · exact genTheory_avail_conj arch (hd.2.1 _ a b) (permMatrix_isometry _)
  · exact genTheory_avail_conj arch (hd.2.2 _ a) (phaseGate_unitary a)

end Elementary

/-! ### Section C — the collapse: one object supplies all three principles -/

section Collapse

variable {𝓘 : ImplementationClass} {A : Type} [Fintype A] [DecidableEq A]

/-- **ONE SUBSTRATUM OBJECT SUPPLIES ALL THREE PRIMITIVE-SOURCE PRINCIPLES.** -/
theorem quantumArchitecture_supplies_all (hq : QuantumArchitecture 𝓘) :
    ReversibleImplementationLocality (genTheory 𝓘 hq.arch A)
      ∧ ElementaryTransitionRichness (genTheory 𝓘 hq.arch A)
      ∧ EmbeddedObservation (genTheory 𝓘 hq.arch A) :=
  ⟨genTheory_reversibleImplementationLocality 𝓘 hq.arch hq.context hq.label hq.dagger,
    genTheory_elementary hq.arch hq.drives,
    genTheory_embeddedObservation 𝓘 hq.arch hq.label⟩

/-- **A THEORY GENERATED BY A QUANTUM ARCHITECTURE IS FINITE OPERATIONAL QM.** -/
theorem genTheory_qm_of_quantumArchitecture [Nonempty A] (hq : QuantumArchitecture 𝓘) :
    ExactAllFiniteEndomorphicQuantumOps (genTheory 𝓘 hq.arch A) := by
  obtain ⟨hril, hetr, heo⟩ := quantumArchitecture_supplies_all (A := A) hq
  exact qm_of_oiPlusElem _ ⟨hril, hetr, heo⟩

end Collapse

/-! ### Section D — the full class is a quantum architecture; QM is generated -/

section Full

/-- The full class is an architecture. -/
theorem fullClass_arch : Architecture fullClass where
  one := fun _ _ _ => trivial
  mul := fun _ _ _ _ _ _ _ => trivial
  smul := fun _ _ _ _ _ _ => trivial
  proj := fun _ _ _ _ _ => trivial
  block := fun _ _ _ _ _ _ _ _ => trivial

theorem fullClass_drivesElementary : DrivesElementary fullClass :=
  ⟨fun _ _ _ _ _ _ => trivial, fun _ _ _ _ _ => trivial, fun _ _ _ _ => trivial⟩

/-- **THE FULL CLASS IS A QUANTUM ARCHITECTURE.** -/
theorem fullClass_quantumArchitecture : QuantumArchitecture fullClass where
  arch := fullClass_arch
  context := fullClass_contextStable
  label := fullClass_labelInvariant
  dagger := fullClass_daggerStable
  drives := fullClass_drivesElementary

variable {A : Type} [Fintype A] [DecidableEq A]

/-- **FINITE OPERATIONAL QM IS GENERATED BY A QUANTUM ARCHITECTURE.** -/
theorem qm_generated_by_quantumArchitecture [Nonempty A] (T : FiniteOperationalTheory A)
    (h : ExactAllFiniteEndomorphicQuantumOps T) :
    ∃ 𝓘 : ImplementationClass, QuantumArchitecture 𝓘 ∧ ImplementationGenerated T 𝓘 :=
  ⟨fullClass, fullClass_quantumArchitecture, generated_of_qm T h⟩

end Full

/-! ### Section E — the decisive property: the diagonal architecture is stable but not driving -/

section Decisive

/-- **THE DIAGONAL CLASS DOES NOT DRIVE THE ELEMENTARY TRANSITIONS**: the exchange of two
distinguishable states is off-diagonal. -/
theorem diagClass_not_drivesElementary : ¬ DrivesElementary diagClass := by
  intro h
  have hswap := h.2.1 (Fin 2) 0 1
  have h01 : permMatrix (Equiv.swap (0 : Fin 2) 1) 0 1 = 1 := by
    simp [permMatrix, Equiv.swap_apply_right]
  have := hswap 0 1 (by decide)
  rw [h01] at this
  exact one_ne_zero this

/-- **THE DIAGONAL ARCHITECTURE IS STABLE BUT NOT QUANTUM.** It is context-, label- and
dagger-stable, yet its generated theory is not finite operational QM — so elementary
drivability carries content the three stabilities do not. -/
theorem diagGen_not_quantumArchitectureGenerated :
    ContextStable diagClass ∧ LabelInvariant diagClass ∧ DaggerStable diagClass
      ∧ ¬ DrivesElementary diagClass
      ∧ ¬ ExactAllFiniteEndomorphicQuantumOps (genTheory diagClass diagClass_arch (Fin 2)) :=
  ⟨diagClass_contextStable, diagClass_labelInvariant, diagClass_daggerStable,
    diagClass_not_drivesElementary,
    fun h => diagGen_not_control (physical_of_exactAll _ h).2.2.1⟩

end Decisive

#print axioms genTheory_avail_conj
#print axioms genTheory_elementary
#print axioms quantumArchitecture_supplies_all
#print axioms genTheory_qm_of_quantumArchitecture
#print axioms fullClass_arch
#print axioms fullClass_drivesElementary
#print axioms fullClass_quantumArchitecture
#print axioms qm_generated_by_quantumArchitecture
#print axioms diagClass_not_drivesElementary
#print axioms diagGen_not_quantumArchitectureGenerated

end SubstratumSource
end OIBridge
