import OIBridge.CoherentLiftGauge

/-!
# Act 12 — the two-sided invisible gauge and the fibre-Gram classification

Executed under the frozen control plane
`verification/programmes/oi-qm/track-b/act-12-two-sided-gauge/preregistration.md`, blob
`5850238f290f0424ff677ff6d5cc2c039b1f58c2`, from `main` at
`b821d69ae86f7d76020383735b3161e77c064ccc` — the merge commit of that control plane, which the
freeze fixes as this round's mandated base.

## What this round is

A **classification round**, not a fork. Act 11 classified the maximal uniform *right*
visibility-preserving action `U ↦ U·K` and left one target open: a pair of coherent lifts of one
visible family outside `𝒢ʷ_{a₀}` **and** different in relative evolution. The control plane records
that this target is positive by a two-line construction on `GI2`'s own pair, and that the reason is
structural: act 11's gauge is one-sided. This module supplies the **left** factor, classifies the
quotient by the two-sided action the two factors generate, and determines exactly which data the
visible law leaves free — per time slice.

## The five targets

* **`LG1`** — `LeftFibreGroup` is invisible universally (`left_preserves_admissible`), maximal
  among uniform left actions considered alone (`left_of_preserves_every_admissible`, which needs
  **no** `|V| ≥ 2` hypothesis: the test dilations are the anchor-swapping transpositions
  `swap((j,a₀),(j,a))`, admissible for the identity slice by act 7's `admissible_permMatrix`), and
  escapes the right orbit on `V = Fin 2`, `A = Fin 2` (`lg1_escape_right_orbit`).
* **`RO1`** — act 11's open target closed positively: `ro1_right_only_insufficient`, on the `GI2`
  orbit-switching pair, with the relating element exhibited as a **left** move. The `|V| ≥ 2`
  hypothesis is a conjunct of the statement. **The reading is fixed exactly**: quotienting by the
  maximal uniform right weak gauge is insufficient to determine the relative evolution. It is not a
  statement about every gauge or connection description.
* **`TG2`** — the fibre-Gram orbit theorem, both directions (`twoSided_slice_iff`), the
  Gram-isometry lemma `exists_unitary_of_gram_eq` (stated for arbitrary families, linearly
  dependent ones included), and the lifted slice-wise corollary `twoSidedRelated_iff`.
* **`TG3`** — the Hadamard witness at `|A| = 1`, `|V| = 4`: `hadamard_slices_not_twoSided`,
  `hadamard_lifts_not_twoSided`, with the cross-ratio computed in the kernel
  (`hadamard_cross_ratio`) and its Gram-level invariance (`gramPhaseEquiv_cross_invariant`).
  `GI2`'s and `GL2`'s pairs are recorded as **controls inside single two-sided orbits**
  (`gi2_pair_twoSidedRelated`, `twoSidedRelated_of_gaugeRelated_strong`).
* **`SH1`** — the shape theorem: `sh1_necessity` and `sh1_sufficiency`, with the corollaries
  **`SH1-C1`** (`sh1_c1`, zero-diagonal support, one-way) and **`SH1-C2`**
  (`sh1_c2_at_most_one`, deterministic slices have at most one Gram tuple; `sh1_c2_unique_orbit`
  is its orbit consequence, which rides on the `TG2` converse).

## What none of this licenses

Nothing here says OI and QM are inequivalent. The fibre-Gram data is a **coordinate on the lift
space, not a physical quantity**. Nothing here is a cross-time statement: `TG2` and `SH1` are per
slice, `CoherentLift` stays `ℕ`-indexed with the cocycle vacuous, and no regularity, homogeneity or
source-level coherence is introduced. No selection principle is named, endorsed or excluded, and
nothing is said about connections or gauge fixings in either direction. **Joint maximality is
neither asserted nor excluded**: `𝒢_L × 𝒢ʷ_{a₀}` is the two-sided uniform gauge *generated by the
separately maximal factors*, never "the maximal uniform two-sided action". **Overlap is not
memory.** `P0` is not closed; it moves to the cross-time selection of the Gram trajectory, which is
the next frontier and not this round's.
-/

namespace OIBridge
namespace TwoSidedGauge

open Finset Matrix CausalReadback RootedClassification TransposeBridge BarandesTupleRound
  ContinuousExtension DilationChoice ReadbackRobustness AnchorRobustness CoherentLiftGauge

open scoped ComplexOrder

variable {V A : Type} [Fintype V] [DecidableEq V] [Fintype A] [DecidableEq A]

/-! ### Section A — the budget slots -/

/-- **THE LEFT FIBRE GROUP `𝒢_L`** (act 12's budget slot 1) — unitaries block-diagonal across the
visible fibres, i.e. commuting with every fibre projection `P_i`. Equivalently `𝒢_L ≅ Π_{i ∈ V} U(A)`:
an output-side unitary relabelling of the ancilla *within* each visible fibre.

**Anchor-independent**, unlike `WeakAnchorStabilizer`: no `a₀` appears. -/
def LeftFibreGroup (L : Matrix (V × A) (V × A) ℂ) : Prop :=
  L ∈ Matrix.unitaryGroup (V × A) ℂ ∧ ∀ p q : V × A, p.1 ≠ q.1 → L p q = 0

/-- **TWO-SIDED RELATEDNESS `∼₂`** (slot 2) — over `ℕ`-indexed lifts, time-dependent on both sides,
matching `GaugeRelated`'s convention. `GaugeRelated (WeakAnchorStabilizer a₀)` is the special case
`L ≡ 1` (`twoSidedRelated_of_gaugeRelated_weak`). -/
def TwoSidedRelated (a₀ : A) (U U' : ℕ → Matrix (V × A) (V × A) ℂ) : Prop :=
  ∃ L K : ℕ → Matrix (V × A) (V × A) ℂ,
    (∀ t, LeftFibreGroup (L t)) ∧ (∀ t, WeakAnchorStabilizer a₀ (K t))
      ∧ ∀ t, U' t = L t * U t * K t

/-- **THE FIBRE-GRAM DATA** (slot 3) — for each visible fibre `i`, the `V × V` Gram matrix of the
anchored columns projected into that fibre:
`G^{(i)}(U)_{jk} = ⟨P_i U e_{(j,a₀)}, P_i U e_{(k,a₀)}⟩ = ∑_a conj(U_{(i,a),(j,a₀)}) U_{(i,a),(k,a₀)}`
(`fibreGram_apply`). Written as `Xᴴ X` for the fibre block `X = U.submatrix (i,·) (·,a₀)` so that
positivity, rank and the gauge transformation laws are matrix identities. Its diagonal is the
anchored readback (`fibreGram_diag`). **Carries the anchor**; `LeftFibreGroup` does not. -/
def FibreGram (a₀ : A) (U : Matrix (V × A) (V × A) ℂ) (i : V) : Matrix V V ℂ :=
  (U.submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀)))ᴴ
    * U.submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀))

/-- **PHASE EQUIVALENCE OF GRAM DATA `∼_D`** (slot 4) — `G' = Dᴴ G D` for one diagonal unitary
`D = diag(c)`, entrywise `G'_{jk} = conj(c_j) G_{jk} c_k`, the same `D` for every fibre. This is the
action of the anchored phases of `𝒢ʷ_{a₀}` (`fibreGram_mul_weak_apply`). -/
def GramPhaseEquiv (G G' : V → Matrix V V ℂ) : Prop :=
  ∃ c : V → ℂ, (∀ j, ‖c j‖ = 1) ∧ ∀ i j k, G' i j k = star (c j) * G i j k * c k

/-- **REALIZABLE GRAM TUPLES** (slot 5, conditional — fired) — the four conditions of `SH1`:
positive semidefinite, rank at most `|A|`, summing to the identity, diagonal equal to the visible
slice. **The rank constraint is load-bearing** (hazard 9): dropping it makes sufficiency false. -/
def RealizableGram (A : Type) [Fintype A] (Γ : Matrix V V ℝ) (G : V → Matrix V V ℂ) : Prop :=
  (∀ i, (G i).PosSemidef) ∧ (∀ i, (G i).rank ≤ Fintype.card A)
    ∧ (∑ i, G i = 1) ∧ ∀ i j, G i j j = (Γ i j : ℂ)

/-! ### Section B — the fibre-Gram data: entries, diagonal, and `SH1` necessity -/

omit [Fintype V] [DecidableEq V] [DecidableEq A] in
theorem fibreGram_apply (a₀ : A) (U : Matrix (V × A) (V × A) ℂ) (i j k : V) :
    FibreGram a₀ U i j k = ∑ a : A, star (U (i, a) (j, a₀)) * U (i, a) (k, a₀) := by
  simp [FibreGram, Matrix.mul_apply, Matrix.conjTranspose_apply, Matrix.submatrix_apply]

/-- `star z * z` is the squared norm, cast. The shape every diagonal computation needs. -/
theorem star_mul_self_eq_norm_sq (z : ℂ) : star z * z = ((‖z‖ ^ 2 : ℝ) : ℂ) := by
  rw [mul_comm, RCLike.star_def, Complex.mul_conj]
  norm_cast
  exact Complex.normSq_eq_norm_sq _

omit [Fintype V] [DecidableEq V] [DecidableEq A] in
/-- **THE DIAGONAL OF THE FIBRE-GRAM DATA IS THE ANCHORED READBACK.** -/
theorem fibreGram_diag (a₀ : A) (U : Matrix (V × A) (V × A) ℂ) (i j : V) :
    FibreGram a₀ U i j j = ((∑ a : A, ‖U (i, a) (j, a₀)‖ ^ 2 : ℝ) : ℂ) := by
  rw [fibreGram_apply, Complex.ofReal_sum]
  exact Finset.sum_congr rfl fun a _ => star_mul_self_eq_norm_sq _

/-- So for an admissible dilation the diagonal is the visible slice: **the visible law is exactly
the diagonal of the fibre-Gram data.** -/
theorem fibreGram_diag_of_admissible {Γ : Matrix V V ℝ} {a₀ : A}
    {U : Matrix (V × A) (V × A) ℂ} (h : AdmissibleDilationAt Γ a₀ U) (i j : V) :
    FibreGram a₀ U i j j = (Γ i j : ℂ) := by
  rw [fibreGram_diag, h.2 i j]

omit [DecidableEq V] [DecidableEq A] in
theorem fibreGram_posSemidef (a₀ : A) (U : Matrix (V × A) (V × A) ℂ) (i : V) :
    (FibreGram a₀ U i).PosSemidef :=
  Matrix.posSemidef_conjTranspose_mul_self _

omit [DecidableEq V] [DecidableEq A] in
/-- A fibre has dimension `|A|`, so each fibre-Gram matrix has rank at most `|A|`. -/
theorem fibreGram_rank_le (a₀ : A) (U : Matrix (V × A) (V × A) ℂ) (i : V) :
    (FibreGram a₀ U i).rank ≤ Fintype.card A := by
  unfold FibreGram
  rw [Matrix.rank_conjTranspose_mul_self]
  exact Matrix.rank_le_card_height _

/-- The anchored columns of a unitary are orthonormal, so the fibre-Grams sum to the identity. -/
theorem sum_fibreGram {a₀ : A} {U : Matrix (V × A) (V × A) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (V × A) ℂ) : ∑ i, FibreGram a₀ U i = 1 := by
  have h1 : Uᴴ * U = 1 := by
    have h := Matrix.mem_unitaryGroup_iff'.1 hU
    rwa [Matrix.star_eq_conjTranspose] at h
  ext j k
  have hjk := congrFun (congrFun h1 (j, a₀)) (k, a₀)
  rw [Matrix.mul_apply, Fintype.sum_prod_type] at hjk
  simp only [Matrix.conjTranspose_apply] at hjk
  rw [Matrix.sum_apply]
  simp only [fibreGram_apply]
  rw [hjk, Matrix.one_apply, Matrix.one_apply]
  simp [Prod.ext_iff]

/-- **`SH1`, NECESSITY** — the fibre-Gram data of an admissible dilation is a realizable tuple. -/
theorem sh1_necessity {Γ : Matrix V V ℝ} {a₀ : A} {U : Matrix (V × A) (V × A) ℂ}
    (h : AdmissibleDilationAt Γ a₀ U) : RealizableGram A Γ (FibreGram a₀ U) :=
  ⟨fun i => fibreGram_posSemidef a₀ U i, fun i => fibreGram_rank_le a₀ U i,
    sum_fibreGram h.1, fun i j => fibreGram_diag_of_admissible h i j⟩

/-! ### Section C — the left action: `LG1` (1) invisibility and the Gram invariance -/

/-- Left multiplication by a fibre-block unitary acts on each fibre block of the anchored columns
by the corresponding `|A| × |A|` block. -/
theorem left_mul_submatrix {L : Matrix (V × A) (V × A) ℂ} (hL : LeftFibreGroup L)
    (U : Matrix (V × A) (V × A) ℂ) (a₀ : A) (i : V) :
    (L * U).submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀))
      = L.submatrix (fun a : A => (i, a)) (fun a : A => (i, a))
          * U.submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀)) := by
  ext a j
  simp only [Matrix.submatrix_apply, Matrix.mul_apply, Fintype.sum_prod_type]
  rw [Finset.sum_eq_single i (fun k _ hk => ?_) (fun h => absurd (Finset.mem_univ _) h)]
  exact Finset.sum_eq_zero fun c _ => by rw [hL.2 (i, a) (k, c) (Ne.symm hk), zero_mul]

/-- Each fibre block of a fibre-block unitary is itself unitary. -/
theorem left_block_unitary {L : Matrix (V × A) (V × A) ℂ} (hL : LeftFibreGroup L) (i : V) :
    (L.submatrix (fun a : A => (i, a)) (fun a : A => (i, a)))ᴴ
      * L.submatrix (fun a : A => (i, a)) (fun a : A => (i, a)) = 1 := by
  have h1 : Lᴴ * L = 1 := by
    have h := Matrix.mem_unitaryGroup_iff'.1 hL.1
    rwa [Matrix.star_eq_conjTranspose] at h
  ext a b
  have hab := congrFun (congrFun h1 (i, a)) (i, b)
  rw [Matrix.mul_apply, Fintype.sum_prod_type] at hab
  simp only [Matrix.conjTranspose_apply] at hab
  rw [Finset.sum_eq_single i (fun k _ hk => Finset.sum_eq_zero fun c _ => by
      rw [hL.2 (k, c) (i, a) hk, star_zero, zero_mul])
    (fun h => absurd (Finset.mem_univ _) h)] at hab
  rw [Matrix.mul_apply]
  simp only [Matrix.conjTranspose_apply, Matrix.submatrix_apply]
  rw [hab, Matrix.one_apply, Matrix.one_apply]
  simp [Prod.ext_iff]

/-- **THE LEFT ACTION LEAVES EVERY FIBRE-GRAM MATRIX INVARIANT** — `(L_i X)ᴴ (L_i X) = Xᴴ X`. -/
theorem fibreGram_left_mul {L : Matrix (V × A) (V × A) ℂ} (hL : LeftFibreGroup L) (a₀ : A)
    (U : Matrix (V × A) (V × A) ℂ) (i : V) : FibreGram a₀ (L * U) i = FibreGram a₀ U i := by
  unfold FibreGram
  rw [left_mul_submatrix hL, Matrix.conjTranspose_mul, Matrix.mul_assoc,
    ← Matrix.mul_assoc (L.submatrix (fun a : A => (i, a)) (fun a : A => (i, a)))ᴴ,
    left_block_unitary hL, Matrix.one_mul]

/-- **`LG1` (1) — THE LEFT FIBRE GROUP IS INVISIBLE, UNIVERSALLY.** For every `L ∈ 𝒢_L`, every
family, every anchor and every admissible `U`, `L·U` is admissible: the anchored readback sums over
exactly the index `L` mixes. -/
theorem left_preserves_admissible {Γ : Matrix V V ℝ} {a₀ : A}
    {L U : Matrix (V × A) (V × A) ℂ} (hL : LeftFibreGroup L)
    (hU : AdmissibleDilationAt Γ a₀ U) : AdmissibleDilationAt Γ a₀ (L * U) := by
  refine ⟨mul_mem hL.1 hU.1, fun i j => ?_⟩
  have h1 := congrFun (congrFun (fibreGram_left_mul hL a₀ U i) j) j
  rw [fibreGram_diag, fibreGram_diag] at h1
  rw [hU.2 i j]
  exact_mod_cast h1.symm

theorem one_leftFibreGroup : LeftFibreGroup (1 : Matrix (V × A) (V × A) ℂ) :=
  ⟨one_mem _, fun p q h => Matrix.one_apply_ne (fun hpq => h (by rw [hpq]))⟩

/-! ### Section D — the right action, the phase transformation law, and `TG2` forward -/

/-- The anchored column of `U * K` for weak `K` is the anchored column of `U` times the phase. -/
theorem mul_weak_anchor_col {a₀ : A} {K : Matrix (V × A) (V × A) ℂ} {c : V → ℂ}
    (hc : ∀ p j, K p (j, a₀) = if p = (j, a₀) then c j else 0)
    (U : Matrix (V × A) (V × A) ℂ) (p : V × A) (j : V) :
    (U * K) p (j, a₀) = c j * U p (j, a₀) := by
  rw [Matrix.mul_apply, Finset.sum_eq_single (j, a₀)
    (fun b _ hb => by rw [hc b j, if_neg hb, mul_zero])
    (fun hcon => absurd (Finset.mem_univ _) hcon), hc (j, a₀) j, if_pos rfl, mul_comm]

/-- **THE RIGHT WEAK ACTION CONJUGATES THE GRAM DATA BY THE ANCHORED PHASES**:
`G^{(i)}(U K) = Dᴴ G^{(i)}(U) D`, entrywise. -/
theorem fibreGram_mul_weak_apply {a₀ : A} {K : Matrix (V × A) (V × A) ℂ} {c : V → ℂ}
    (hc : ∀ p j, K p (j, a₀) = if p = (j, a₀) then c j else 0)
    (U : Matrix (V × A) (V × A) ℂ) (i j k : V) :
    FibreGram a₀ (U * K) i j k = star (c j) * FibreGram a₀ U i j k * c k := by
  rw [fibreGram_apply, fibreGram_apply, Finset.mul_sum, Finset.sum_mul]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [mul_weak_anchor_col hc, mul_weak_anchor_col hc, star_mul']
  ring

/-- The weak class is closed under products, coefficientwise. -/
theorem weak_mul {a₀ : A} {K₁ K₂ : Matrix (V × A) (V × A) ℂ}
    (h₁ : WeakAnchorStabilizer a₀ K₁) (h₂ : WeakAnchorStabilizer a₀ K₂) :
    WeakAnchorStabilizer a₀ (K₁ * K₂) := by
  obtain ⟨hm₁, c₁, hc₁⟩ := h₁
  obtain ⟨hm₂, c₂, hc₂⟩ := h₂
  refine ⟨mul_mem hm₁ hm₂, fun j => c₁ j * c₂ j, fun p j => ?_⟩
  rw [mul_weak_anchor_col hc₂, hc₁ p j]
  split_ifs <;> ring

/-- **`TG2`, FORWARD** — two-sided related dilations have `∼_D`-equivalent fibre-Gram data. The
left factor is invisible to the Gram data and the right factor acts by the anchored phases. -/
theorem gramPhaseEquiv_of_twoSided {a₀ : A} {L U K : Matrix (V × A) (V × A) ℂ}
    (hL : LeftFibreGroup L) (hK : WeakAnchorStabilizer a₀ K) :
    GramPhaseEquiv (FibreGram a₀ U) (FibreGram a₀ (L * U * K)) := by
  obtain ⟨hKmem, c, hc⟩ := hK
  exact ⟨c, fun j => weak_anchor_coeff_norm_one hKmem hc j,
    fun i j k => by rw [fibreGram_mul_weak_apply hc, fibreGram_left_mul hL]⟩

/-- Right weak relatedness is the `L ≡ 1` case of two-sided relatedness. -/
theorem twoSidedRelated_of_gaugeRelated_weak {a₀ : A} {U U' : ℕ → Matrix (V × A) (V × A) ℂ}
    (h : GaugeRelated (WeakAnchorStabilizer a₀) U U') : TwoSidedRelated a₀ U U' := by
  obtain ⟨K, hK, hfac⟩ := h
  exact ⟨fun _ => 1, K, fun _ => one_leftFibreGroup, hK,
    fun t => by rw [hfac t, Matrix.one_mul]⟩

/-- **`GL2`'s PAIR IS A CONTROL INSIDE ONE TWO-SIDED ORBIT.** Act 11's `GL2` pair is related by a
time-dependent element of the strong class, so it is two-sided related with `L ≡ 1`. Every
strong-related pair is; this is the general statement `GL2`'s conjunct instantiates. -/
theorem twoSidedRelated_of_gaugeRelated_strong {a₀ : A} {U U' : ℕ → Matrix (V × A) (V × A) ℂ}
    (h : GaugeRelated (StrongAnchorStabilizer a₀) U U') : TwoSidedRelated a₀ U U' :=
  twoSidedRelated_of_gaugeRelated_weak
    ⟨h.choose, fun t => strong_mem_weak (h.choose_spec.1 t), h.choose_spec.2⟩

/-! ### Section E — `LG1` (2): maximality among uniform left actions, considered alone -/

/-- **`LG1` (2) — MAXIMALITY, WITH NO `|V| ≥ 2` HYPOTHESIS.** If a unitary `L` preserves the
visible marginal of **every** admissible dilation of **every** family at one anchor `a₀`, then `L`
is block-diagonal across the visible fibres.

**One family of test dilations does all the work**, and no search over unitaries is needed: for
each target column `(j, b)`, the transposition `swap((j,a₀), (j,b))` — the identity when `b = a₀` —
is admissible for the identity slice by act 7's merged `admissible_permMatrix`, and `L` times it has
`L`'s column `(j, b)` in the anchored slot `(j, a₀)`. Preservation of the identity slice then forces
that column to vanish outside fibre `j`.

**This is maximality among uniform LEFT actions considered alone** (bounded reading, hazard 5): it
does not say the two-sided action is jointly maximal, and it does not exclude non-uniform,
family-specific invisible freedoms. At `|V| = 1` there is one fibre and `𝒢_L` is everything, so no
exception arises. -/
theorem left_of_preserves_every_admissible {a₀ : A} {L : Matrix (V × A) (V × A) ℂ}
    (hL : L ∈ Matrix.unitaryGroup (V × A) ℂ)
    (hpres : ∀ (G : Matrix V V ℝ) (U : Matrix (V × A) (V × A) ℂ),
      AdmissibleDilationAt G a₀ U → AdmissibleDilationAt G a₀ (L * U)) :
    LeftFibreGroup L := by
  classical
  refine ⟨hL, fun p q hpq => ?_⟩
  obtain ⟨i, a⟩ := p
  obtain ⟨j, b⟩ := q
  change i ≠ j at hpq
  set τ : Equiv.Perm (V × A) := Equiv.swap ((j, a₀) : V × A) ((j, b) : V × A) with hτ
  have hτfst : ∀ m : V, (τ.symm (m, a₀)).1 = m := by
    intro m
    rw [hτ, Equiv.symm_swap, Equiv.swap_apply_def]
    split_ifs with h1 h2
    · exact ((Prod.ext_iff.1 h1).1).symm
    · exact ((Prod.ext_iff.1 h2).1).symm
    · rfl
  have hadm : AdmissibleDilationAt (1 : Matrix V V ℝ) a₀ (τ.permMatrix ℂ) := by
    refine admissible_permMatrix a₀ τ fun i' m => ?_
    rw [hτfst m, Matrix.one_apply]
    exact if_congr eq_comm rfl rfl
  have h := (hpres _ _ hadm).2 i j
  rw [Matrix.one_apply, if_neg hpq] at h
  have hcol : ∀ c : A, (L * τ.permMatrix ℂ) (i, c) (j, a₀) = L (i, c) (j, b) := by
    intro c
    rw [mul_permMatrix_apply, hτ, Equiv.symm_swap, Equiv.swap_apply_left]
  rw [Finset.sum_congr rfl fun c _ => by rw [hcol c]] at h
  have hz : ‖L (i, a) (j, b)‖ ^ 2 = 0 :=
    le_antisymm
      (by
        rw [h]
        exact Finset.single_le_sum (f := fun c => ‖L (i, c) (j, b)‖ ^ 2)
          (fun c _ => by positivity) (Finset.mem_univ a))
      (by positivity)
  simpa using (pow_eq_zero_iff (n := 2) (by norm_num)).1 hz

/-! ### Section F — `SH1-C1` and `SH1-C2` -/

/-- A vanishing visible entry forces the whole anchored column to vanish in that fibre. -/
theorem anchored_entry_eq_zero_of_visible_zero {Γ : Matrix V V ℝ} {a₀ : A}
    {U : Matrix (V × A) (V × A) ℂ} (hU : AdmissibleDilationAt Γ a₀ U) {i j : V}
    (h : Γ i j = 0) (a : A) : U (i, a) (j, a₀) = 0 := by
  have hs := hU.2 i j
  rw [h] at hs
  have hz : ‖U (i, a) (j, a₀)‖ ^ 2 = 0 :=
    le_antisymm
      (by
        rw [hs]
        exact Finset.single_le_sum (f := fun b => ‖U (i, b) (j, a₀)‖ ^ 2)
          (fun b _ => by positivity) (Finset.mem_univ a))
      (by positivity)
  simpa using (pow_eq_zero_iff (n := 2) (by norm_num)).1 hz

/-- **`SH1-C1` ON DILATIONS** — `Γ_{ij} = 0 ⇒ G^{(i)}_{jk} = G^{(i)}_{kj} = 0`. -/
theorem sh1_c1_fibreGram {Γ : Matrix V V ℝ} {a₀ : A} {U : Matrix (V × A) (V × A) ℂ}
    (hU : AdmissibleDilationAt Γ a₀ U) {i j : V} (h : Γ i j = 0) (k : V) :
    FibreGram a₀ U i j k = 0 ∧ FibreGram a₀ U i k j = 0 := by
  constructor
  · rw [fibreGram_apply]
    exact Finset.sum_eq_zero fun a _ => by
      rw [anchored_entry_eq_zero_of_visible_zero hU h a, star_zero, zero_mul]
  · rw [fibreGram_apply]
    exact Finset.sum_eq_zero fun a _ => by
      rw [anchored_entry_eq_zero_of_visible_zero hU h a, mul_zero]

/-- **A POSITIVE SEMIDEFINITE MATRIX WITH A ZERO DIAGONAL ENTRY HAS THAT ROW AND COLUMN ZERO.**
This needs only positivity: with `x = e_k − t·conj(G_{kj})·e_j` the form `xᴴ G x` equals
`G_{kk} − 2t|G_{kj}|²`, which cannot stay nonnegative for large `t` unless `G_{kj} = 0`. -/
theorem posSemidef_apply_eq_zero_of_diag_eq_zero {G : Matrix V V ℂ} (hG : G.PosSemidef) {j : V}
    (hjj : G j j = 0) (k : V) : G j k = 0 ∧ G k j = 0 := by
  obtain ⟨hH, hpos⟩ := Matrix.posSemidef_iff_dotProduct_mulVec.1 hG
  have hjk : G j k = star (G k j) := (hH.apply j k).symm
  suffices hkj : G k j = 0 by
    exact ⟨by rw [hjk, hkj, star_zero], hkj⟩
  by_contra hne
  have hnorm : 0 < ‖G k j‖ ^ 2 := by positivity
  -- the quadratic form along `e_k + s e_j`
  have hform : ∀ s : ℂ, star (Pi.single k 1 + s • Pi.single j (1 : ℂ))
      ⬝ᵥ (G *ᵥ (Pi.single k 1 + s • Pi.single j (1 : ℂ)))
        = G k k + s * G k j + star s * G j k := by
    intro s
    rw [Matrix.mulVec_add, Matrix.mulVec_smul, Matrix.mulVec_single_one, Matrix.mulVec_single_one,
      star_add, star_smul, ← Pi.single_star, ← Pi.single_star, star_one, add_dotProduct,
      smul_dotProduct, single_dotProduct, single_dotProduct]
    simp only [Pi.add_apply, Pi.smul_apply, Matrix.col_apply, smul_eq_mul, one_mul, hjj,
      mul_zero, add_zero]
  have hre : ∀ t : ℝ, 0 ≤ (G k k).re - 2 * t * ‖G k j‖ ^ 2 := by
    intro t
    have h0 := hpos (Pi.single k 1 + (-(t : ℂ) * star (G k j)) • Pi.single j (1 : ℂ))
    rw [hform] at h0
    have ht : star ((t : ℝ) : ℂ) = (t : ℂ) := by rw [RCLike.star_def, Complex.conj_ofReal]
    have h1 : (-(t : ℂ) * star (G k j)) * G k j + star (-(t : ℂ) * star (G k j)) * G j k
        = -((2 * t * ‖G k j‖ ^ 2 : ℝ) : ℂ) := by
      rw [hjk, star_mul', star_neg, star_star, ht]
      simp only [mul_assoc]
      rw [mul_comm (G k j) (star (G k j)), star_mul_self_eq_norm_sq]
      push_cast
      ring
    rw [add_assoc, h1] at h0
    have := (Complex.le_def.1 h0).1
    simp only [Complex.zero_re, Complex.add_re, Complex.neg_re, Complex.ofReal_re] at this
    linarith
  have := hre (((G k k).re + 1) / (2 * ‖G k j‖ ^ 2))
  rw [show 2 * (((G k k).re + 1) / (2 * ‖G k j‖ ^ 2)) * ‖G k j‖ ^ 2 = (G k k).re + 1 by
    field_simp] at this
  linarith

omit [DecidableEq A] in
/-- **`SH1-C1` — ZERO-DIAGONAL SUPPORT.** For every realizable fibre-Gram tuple,
`Γ_{ij} = 0 ⇒ G^{(i)}_{jk} = G^{(i)}_{kj} = 0`. Needs only that each `G^{(i)}` is positive
semidefinite, not `SH1` sufficiency.

**Bounded reading**: off-diagonal Gram freedom can occur *only* between visible inputs that both
have positive support into the same output fibre. **No converse is claimed** — rank and
`∑_i G^{(i)} = I` can force an overlap entry to zero — and **no memory claim is made**: a memoryless
Markov slice can have overlap. -/
theorem sh1_c1 {Γ : Matrix V V ℝ} {G : V → Matrix V V ℂ} (hG : RealizableGram A Γ G) {i j : V}
    (h : Γ i j = 0) (k : V) : G i j k = 0 ∧ G i k j = 0 :=
  posSemidef_apply_eq_zero_of_diag_eq_zero (hG.1 i) (by rw [hG.2.2.2 i j, h]; simp) k

/-- **`SH1-C2`, THE CLOSED FORM** — for a deterministic slice (every column has a single nonzero
entry) every admissible dilation has diagonal fibre-Gram data fixed by `Γ`. Off the diagonal: two
inputs landing in different fibres have a vanishing cross-term by `SH1-C1`; two landing in the same
fibre have a cross-term equal to the full column inner product `⟨U e_j, U e_k⟩ = 0`, by unitarity. -/
theorem fibreGram_of_deterministic {Γ : Matrix V V ℝ} {a₀ : A} {U : Matrix (V × A) (V × A) ℂ}
    (hU : AdmissibleDilationAt Γ a₀ U)
    (hdet : ∀ j : V, ∃ i₀ : V, ∀ i, i ≠ i₀ → Γ i j = 0) (i j k : V) :
    FibreGram a₀ U i j k = if j = k then (Γ i j : ℂ) else 0 := by
  by_cases hjk : j = k
  · subst hjk
    rw [if_pos rfl]
    exact fibreGram_diag_of_admissible hU i j
  rw [if_neg hjk]
  obtain ⟨ij, hij⟩ := hdet j
  obtain ⟨ik, hik⟩ := hdet k
  by_cases hi : i = ij
  · by_cases hi' : i = ik
    · have h1 : Uᴴ * U = 1 := by
        have h := Matrix.mem_unitaryGroup_iff'.1 hU.1
        rwa [Matrix.star_eq_conjTranspose] at h
      have hjk' := congrFun (congrFun h1 (j, a₀)) (k, a₀)
      rw [Matrix.mul_apply, Fintype.sum_prod_type, Matrix.one_apply,
        if_neg (fun h => hjk (Prod.ext_iff.1 h).1)] at hjk'
      simp only [Matrix.conjTranspose_apply] at hjk'
      rw [Finset.sum_eq_single i (fun i' _ hi'' => Finset.sum_eq_zero fun a _ => by
          rw [anchored_entry_eq_zero_of_visible_zero hU (hij i' (fun h => hi'' (h.trans hi.symm))) a,
            star_zero, zero_mul])
        (fun h => absurd (Finset.mem_univ _) h)] at hjk'
      rw [fibreGram_apply, hjk']
    · exact (sh1_c1_fibreGram hU (hik i hi') j).2
  · exact (sh1_c1_fibreGram hU (hij i hi) k).1

/-- **`SH1-C2` — DETERMINISTIC SLICES HAVE AT MOST ONE GRAM TUPLE.** Whenever admissible dilations
of a deterministic slice exist, all of them have identical fibre-Gram data. **Stated as "at most
one", never as existence** (hazard 13): several inputs may collapse deterministically onto one
visible output, and the rank bound can then obstruct realization at small `|A|`. -/
theorem sh1_c2_at_most_one {Γ : Matrix V V ℝ} {a₀ : A} {U U' : Matrix (V × A) (V × A) ℂ}
    (hdet : ∀ j : V, ∃ i₀ : V, ∀ i, i ≠ i₀ → Γ i j = 0)
    (hU : AdmissibleDilationAt Γ a₀ U) (hU' : AdmissibleDilationAt Γ a₀ U') :
    FibreGram a₀ U = FibreGram a₀ U' := by
  funext i
  ext j k
  rw [fibreGram_of_deterministic hU hdet, fibreGram_of_deterministic hU' hdet]

/-! ### Section G — `RO1` and the `LG1` (3) escape witness, on `V = Fin 2`, `A = Fin 2` -/

/-- The in-fibre anchor swap `swap((0,0),(0,1))` lies in the left fibre group. -/
theorem inFibreSwap_leftFibreGroup :
    LeftFibreGroup ((Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (1 : Fin 2))
      : Equiv.Perm (Fin 2 × Fin 2)).permMatrix ℂ) := by
  refine ⟨permMatrix_mem_unitaryGroup _, fun p q hpq => ?_⟩
  obtain ⟨x, y⟩ := p
  obtain ⟨u, v⟩ := q
  fin_cases x <;> fin_cases y <;> fin_cases u <;> fin_cases v <;> simp +decide at hpq ⊢

/-- **`LG1` (3) — THE LEFT GROUP ESCAPES THE RIGHT ORBIT**, on a carrier with `|V| = 2` so that act
11's maximality of `𝒢ʷ_{a₀}` applies and "the right orbit" means the maximal uniform one. The
in-fibre anchor swap on the identity dilation of the identity slice is admissible, is a left move,
and is **not** weak-gauge-related to the identity: its forced element moves the anchored basis
vector `e_{(0,0)}` off its own line. This is the identity-family instance of `RO1`. -/
theorem lg1_escape_right_orbit :
    ∃ L U : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ,
      (∀ j : Fin 2, ∃ j' : Fin 2, j' ≠ j)
        ∧ LeftFibreGroup L
        ∧ AdmissibleDilationAt (1 : Matrix (Fin 2) (Fin 2) ℝ) (0 : Fin 2) U
        ∧ AdmissibleDilationAt (1 : Matrix (Fin 2) (Fin 2) ℝ) (0 : Fin 2) (L * U)
        ∧ ¬ GaugeRelated (WeakAnchorStabilizer (0 : Fin 2)) (fun _ => U) (fun _ => L * U) := by
  classical
  refine ⟨_, 1, ?_, inFibreSwap_leftFibreGroup, one_admissible_at_every_anchor _,
    left_preserves_admissible inFibreSwap_leftFibreGroup (one_admissible_at_every_anchor _), ?_⟩
  · intro j
    fin_cases j
    · exact ⟨1, by decide⟩
    · exact ⟨0, by decide⟩
  · rintro ⟨K, hKmem, hfac⟩
    have h2 := hfac 0
    simp only [Matrix.mul_one, Matrix.one_mul] at h2
    obtain ⟨c, hc⟩ := (hKmem 0).2
    have hbad := hc ((0 : Fin 2), (1 : Fin 2)) (0 : Fin 2)
    rw [← h2, permMatrix_apply_eq] at hbad
    simp +decide at hbad

/-- **`RO1` — RIGHT-ONLY INSUFFICIENCY: act 11's open target, closed positively and bounded.**

Two coherent lifts of one visible family on a carrier with `|V| = 2` — the hypothesis is the first
conjunct, in the form act 11's `GL1w` maximality takes, so that "the maximal uniform right weak
gauge" is what is being quotiented by — that are **not** weak-gauge-related and **differ in relative
evolution**, and whose relating element is exhibited as a **left** move.

The pair is `GI2`'s orbit-switching pair: `U_t = P(σ)` for every `t`, `U'_0 = P(ρ·σ)`, `U'_t = P(σ)`
for `t ≥ 1`, each slice one of the two dilations `GI2` already proved admissible for `Aᵀ`. The forced
right element `K_0 = P(ρ)` is outside the weak class, exactly as in `GI2`; `GL3` cancelled `GI2`'s
relative difference only because `GI2` held its orbit choice constant in time, and here the choice
varies. The relating element is `L_0 = P(swap((0,0),(0,1)))`, an in-fibre swap, with `L_t = 1` after.

**The reading is fixed exactly**: quotienting by the maximal uniform **right** weak gauge is
insufficient to determine the relative evolution. **It is not** a statement about every gauge or
connection description, and the relating element being a left move is why `RO1` is closed and why
`LG1` is the right next object. -/
theorem ro1_right_only_insufficient :
    ∃ (Γ : ℕ → Matrix (Fin 2) (Fin 2) ℝ)
      (U U' L : ℕ → Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ),
      (∀ j : Fin 2, ∃ j' : Fin 2, j' ≠ j)
        ∧ CoherentLift (0 : Fin 2) Γ U ∧ CoherentLift (0 : Fin 2) Γ U'
        ∧ ¬ GaugeRelated (WeakAnchorStabilizer (0 : Fin 2)) U U'
        ∧ (∃ t s : ℕ, U' t * (U' s)ᴴ ≠ U t * (U s)ᴴ)
        ∧ (∀ t, LeftFibreGroup (L t)) ∧ (∀ t, U' t = L t * U t) := by
  classical
  obtain ⟨σ, hσ⟩ : ∃ σ : Equiv.Perm (Fin 2 × Fin 2), σ = Equiv.prodComm (Fin 2) (Fin 2) := ⟨_, rfl⟩
  obtain ⟨ρ, hρ⟩ : ∃ ρ : Equiv.Perm (Fin 2 × Fin 2),
      ρ = Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (0 : Fin 2)) := ⟨_, rfl⟩
  obtain ⟨τ, hτ⟩ : ∃ τ : Equiv.Perm (Fin 2 × Fin 2),
      τ = Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (1 : Fin 2)) := ⟨_, rfl⟩
  have hστ : σ * τ = ρ * σ := by
    refine Equiv.ext fun p => ?_
    fin_cases p <;> simp +decide [hσ, hρ, hτ, Equiv.swap_apply_def]
  have hAT : ∀ σ' : Equiv.Perm (Fin 2 × Fin 2),
      (∀ i j : Fin 2,
        (((Matrix.of fun _ j => if j = 0 then (1 : ℝ) else 0) : Matrix (Fin 2) (Fin 2) ℝ)ᵀ) i j
          = if (σ'.symm (j, (0 : Fin 2))).1 = i then (1 : ℝ) else 0) →
      AdmissibleDilationAt
        (((Matrix.of fun _ j => if j = 0 then (1 : ℝ) else 0) : Matrix (Fin 2) (Fin 2) ℝ)ᵀ)
        (0 : Fin 2) (σ'.permMatrix ℂ) := fun σ' h => admissible_permMatrix _ σ' h
  have hadmσ := hAT σ (fun i j => by
    fin_cases i <;> fin_cases j <;> simp +decide [hσ, Matrix.transpose_apply])
  have hadmρσ := hAT (ρ * σ) (fun i j => by
    fin_cases i <;> fin_cases j <;> simp +decide [hσ, hρ, Matrix.transpose_apply])
  have hτleft : LeftFibreGroup (τ.permMatrix ℂ) := by
    rw [hτ]; exact inFibreSwap_leftFibreGroup
  refine ⟨fun _ =>
      (((Matrix.of fun _ j => if j = 0 then (1 : ℝ) else 0) : Matrix (Fin 2) (Fin 2) ℝ)ᵀ),
    fun _ => σ.permMatrix ℂ,
    fun t => if t = 0 then (ρ * σ).permMatrix ℂ else σ.permMatrix ℂ,
    fun t => if t = 0 then τ.permMatrix ℂ else 1, ?_, fun _ => hadmσ, ?_, ?_, ?_, ?_, ?_⟩
  · intro j
    fin_cases j
    · exact ⟨1, by decide⟩
    · exact ⟨0, by decide⟩
  · intro t
    by_cases ht : t = 0
    · simp only [if_pos ht]; exact hadmρσ
    · simp only [if_neg ht]; exact hadmσ
  · rintro ⟨K, hKmem, hfac⟩
    -- the forced element at `t = 0` is `P(ρ)`, which moves an anchored basis vector
    have hforced : K 0 = ρ.permMatrix ℂ := by
      have h1 : ((σ.permMatrix ℂ))ᴴ * (σ.permMatrix ℂ) = 1 := by
        have h := Matrix.mem_unitaryGroup_iff'.1 (permMatrix_mem_unitaryGroup σ)
        rwa [Matrix.star_eq_conjTranspose] at h
      have h2 : (ρ * σ).permMatrix ℂ = σ.permMatrix ℂ * K 0 := by simpa using hfac 0
      have h3 : ((σ.permMatrix ℂ))ᴴ * ((ρ * σ).permMatrix ℂ)
          = ((σ.permMatrix ℂ))ᴴ * ((σ.permMatrix ℂ) * K 0) := by rw [← h2]
      rw [← mul_assoc, h1, one_mul] at h3
      rw [← h3, Matrix.conjTranspose_permMatrix]
      ext p q
      rw [Matrix.mul_apply]
      simp only [permMatrix_apply_eq, Equiv.Perm.mul_apply]
      rw [Finset.sum_eq_single (σ⁻¹ p) (fun r _ hr => by rw [if_neg hr, zero_mul])
        (fun hc => absurd (Finset.mem_univ _) hc), if_pos rfl, one_mul]
      refine if_congr ?_ rfl rfl
      constructor
      · intro h; rw [h, hσ]; simp
      · intro h; rw [h, hσ]; simp
    obtain ⟨c, hc⟩ := (hKmem 0).2
    have hbad := hc ((1 : Fin 2), (0 : Fin 2)) (0 : Fin 2)
    rw [hforced] at hbad
    rw [if_neg (by decide : ((1 : Fin 2), (0 : Fin 2)) ≠ ((0 : Fin 2), (0 : Fin 2)))] at hbad
    rw [permMatrix_apply_eq, hρ] at hbad
    simp +decide at hbad
  · refine ⟨1, 0, ?_⟩
    simp only [if_neg one_ne_zero]
    intro hcon
    have h00 := congrFun (congrFun hcon ((0 : Fin 2), (0 : Fin 2))) ((0 : Fin 2), (1 : Fin 2))
    simp +decide [Matrix.mul_apply, Fintype.sum_prod_type, Fin.sum_univ_two, hσ, hρ,
      Equiv.swap_apply_def] at h00
  · intro t
    by_cases ht : t = 0
    · simp only [if_pos ht]; exact hτleft
    · simp only [if_neg ht]; exact one_leftFibreGroup
  · intro t
    by_cases ht : t = 0
    · simp only [if_pos ht]
      rw [← hστ, Matrix.permMatrix_mul]
    · simp only [if_neg ht, Matrix.one_mul]

/-- **`GI2`'s PAIR IS A CONTROL INSIDE ONE TWO-SIDED ORBIT** (`TG3`'s control table, hazard 7).
Act 11's constant pair `U_t = P(σ)`, `U'_t = P(ρ·σ)` is related by the **constant left** move
`L = P(swap((0,0),(0,1)))` with `K = 1`. That is why its relative objects coincided and why, by
`TG2`, its fibre-Gram data are identical: `GI2` is a left in-fibre move, not revised but explained. -/
theorem gi2_pair_twoSidedRelated :
    TwoSidedRelated (0 : Fin 2)
      (fun _ => Equiv.Perm.permMatrix ℂ (Equiv.prodComm (Fin 2) (Fin 2)))
      (fun _ => Equiv.Perm.permMatrix ℂ
        (Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (0 : Fin 2))
          * Equiv.prodComm (Fin 2) (Fin 2))) := by
  classical
  have hστ : (Equiv.prodComm (Fin 2) (Fin 2) : Equiv.Perm (Fin 2 × Fin 2))
      * Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (1 : Fin 2))
      = Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (0 : Fin 2))
        * Equiv.prodComm (Fin 2) (Fin 2) := by
    refine Equiv.ext fun p => ?_
    fin_cases p <;> simp +decide
  refine ⟨fun _ => (Equiv.swap ((0 : Fin 2), (0 : Fin 2)) ((0 : Fin 2), (1 : Fin 2))
      : Equiv.Perm (Fin 2 × Fin 2)).permMatrix ℂ, fun _ => 1,
    fun _ => inFibreSwap_leftFibreGroup, fun _ => ⟨one_mem _, fun _ => 1, fun p j => by
      simp only [Matrix.one_apply]⟩, fun _ => ?_⟩
  rw [Matrix.mul_one, ← hστ, Matrix.permMatrix_mul]

/-! ### Section H — the Gram-isometry lemma and `TG2` converse -/

/-- **THE GRAM-ISOMETRY LEMMA** — the round's load-bearing technical step. Two families of vectors
in `ℂ^A`, the columns of `X` and of `Y`, with the same Gram matrix `Xᴴ X = Yᴴ Y` are related by a
unitary: `M X = Y`.

**Stated for arbitrary families** (hazard 10): the anchored components in a fibre are linearly
dependent whenever some `Γ_{ij} = 0`, so nothing here assumes the columns span or are independent.
The map `X c ↦ Y c` is well defined on `range X` and isometric there because
`‖X c‖² = cᴴ Xᴴ X c = cᴴ Yᴴ Y c = ‖Y c‖²` for every `c`, and Mathlib's `LinearIsometry.extend`
extends it to all of `ℂ^A`; `M` is that extension's matrix. -/
theorem exists_unitary_of_gram_eq (X Y : Matrix A V ℂ) (h : Xᴴ * X = Yᴴ * Y) :
    ∃ M : Matrix A A ℂ, M ∈ Matrix.unitaryGroup A ℂ ∧ M * X = Y := by
  classical
  set T : EuclideanSpace ℂ V →ₗ[ℂ] EuclideanSpace ℂ A := Matrix.toEuclideanLin X with hT
  set T' : EuclideanSpace ℂ V →ₗ[ℂ] EuclideanSpace ℂ A := Matrix.toEuclideanLin Y with hT'
  have hTapp : ∀ v, T v = WithLp.toLp 2 (X *ᵥ WithLp.ofLp v) := fun v => rfl
  have hT'app : ∀ v, T' v = WithLp.toLp 2 (Y *ᵥ WithLp.ofLp v) := fun v => rfl
  -- the inner products agree, because both are `cᴴ (Xᴴ X) d`
  have hkey : ∀ (Z : Matrix A V ℂ) (v w : V → ℂ),
      (Z *ᵥ w) ⬝ᵥ star (Z *ᵥ v) = star v ⬝ᵥ ((Zᴴ * Z) *ᵥ w) := by
    intro Z v w
    rw [Matrix.star_mulVec, dotProduct_comm, ← Matrix.dotProduct_mulVec, Matrix.mulVec_mulVec]
  have hinner : ∀ v w, inner ℂ (T v) (T w) = inner ℂ (T' v) (T' w) := by
    intro v w
    rw [hTapp, hTapp, hT'app, hT'app, EuclideanSpace.inner_toLp_toLp,
      EuclideanSpace.inner_toLp_toLp, hkey, hkey, h]
  have hnorm : ∀ v, ‖T v‖ = ‖T' v‖ := fun v => by
    rw [norm_eq_sqrt_re_inner (𝕜 := ℂ), norm_eq_sqrt_re_inner (𝕜 := ℂ), hinner]
  have hker : LinearMap.ker T ≤ LinearMap.ker T' := by
    intro v hv
    rw [LinearMap.mem_ker] at hv ⊢
    rw [← norm_eq_zero, ← hnorm, norm_eq_zero]
    exact hv
  -- the isometry `X c ↦ Y c` on `range X`
  let g₀ : LinearMap.range T →ₗ[ℂ] EuclideanSpace ℂ A :=
    ((LinearMap.ker T).liftQ T' hker).comp T.quotKerEquivRange.symm.toLinearMap
  have hg₀ : ∀ v, g₀ ⟨T v, LinearMap.mem_range_self T v⟩ = T' v := by
    intro v
    show ((LinearMap.ker T).liftQ T' hker) (T.quotKerEquivRange.symm ⟨T v, _⟩) = T' v
    rw [LinearMap.quotKerEquivRange_symm_apply_image, Submodule.mkQ_apply, Submodule.liftQ_apply]
  have hgnorm : ∀ s : LinearMap.range T, ‖g₀ s‖ = ‖s‖ := by
    rintro ⟨s, hs⟩
    obtain ⟨v, rfl⟩ := LinearMap.mem_range.1 hs
    show ‖g₀ ⟨T v, LinearMap.mem_range_self T v⟩‖ = ‖T v‖
    rw [hg₀, hnorm]
  let g : LinearMap.range T →ₗᵢ[ℂ] EuclideanSpace ℂ A := ⟨g₀, hgnorm⟩
  -- its extension to all of `ℂ^A`, and the extension's matrix
  let b := EuclideanSpace.basisFun A ℂ
  let M : Matrix A A ℂ := LinearMap.toMatrix b.toBasis b.toBasis g.extend.toLinearMap
  have hrepr : ∀ y : EuclideanSpace ℂ A, (⇑(b.toBasis.repr y) : A → ℂ) = WithLp.ofLp y := by
    intro y
    funext a
    simp [b, OrthonormalBasis.coe_toBasis_repr_apply, EuclideanSpace.basisFun_repr]
  have hM : ∀ x : EuclideanSpace ℂ A, M *ᵥ WithLp.ofLp x = WithLp.ofLp (g.extend x) := by
    intro x
    have := LinearMap.toMatrix_mulVec_repr b.toBasis b.toBasis g.extend.toLinearMap x
    rwa [hrepr, hrepr] at this
  have hMapply : ∀ c a, M c a = WithLp.ofLp (g.extend (EuclideanSpace.single a (1 : ℂ))) c := by
    intro c a
    simp [M, LinearMap.toMatrix_apply, b, OrthonormalBasis.coe_toBasis_repr_apply,
      EuclideanSpace.basisFun_repr, OrthonormalBasis.coe_toBasis, EuclideanSpace.basisFun_apply]
  have hMunit : M ∈ Matrix.unitaryGroup A ℂ := by
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose]
    ext a c
    rw [Matrix.mul_apply, Matrix.one_apply]
    simp only [Matrix.conjTranspose_apply, hMapply]
    have hsum : ∀ x y : EuclideanSpace ℂ A,
        inner ℂ x y = ∑ i, star (WithLp.ofLp x i) * WithLp.ofLp y i := by
      intro x y
      rw [PiLp.inner_apply]
      exact Finset.sum_congr rfl fun i _ => by rw [RCLike.inner_apply, RCLike.star_def, mul_comm]
    have := g.extend.inner_map_map (EuclideanSpace.single a (1 : ℂ)) (EuclideanSpace.single c 1)
    rw [EuclideanSpace.inner_single_left, hsum] at this
    simp only [map_one, one_mul, PiLp.single_apply] at this
    exact this
  have hMX : M * X = Y := by
    ext c j
    have h1 := hM (WithLp.toLp 2 (X *ᵥ Pi.single j 1))
    have h2 : WithLp.toLp 2 (X *ᵥ Pi.single j 1) = T (WithLp.toLp 2 (Pi.single j (1 : ℂ))) := by
      rw [hTapp]
    rw [WithLp.ofLp_toLp, Matrix.mulVec_mulVec, h2] at h1
    have h3 : g.extend (T (WithLp.toLp 2 (Pi.single j (1 : ℂ))))
        = T' (WithLp.toLp 2 (Pi.single j 1)) := by
      rw [← hg₀ (WithLp.toLp 2 (Pi.single j 1))]
      exact LinearIsometry.extend_apply g ⟨T _, LinearMap.mem_range_self T _⟩
    rw [h3, hT'app, WithLp.ofLp_toLp, WithLp.ofLp_toLp] at h1
    have := congrFun h1 c
    rwa [Matrix.mulVec_single_one, Matrix.mulVec_single_one, Matrix.col_apply,
      Matrix.col_apply] at this
  exact ⟨M, hMunit, hMX⟩

/-- The anchored phase element of the weak class built from unit-modulus coefficients: the diagonal
unitary that is `c_j` on the anchored slot `(j, a₀)` and `1` elsewhere. -/
theorem weak_diagonal_phase {a₀ : A} (c : V → ℂ) (hc : ∀ j, ‖c j‖ = 1) :
    WeakAnchorStabilizer a₀
        (Matrix.diagonal fun p : V × A => if p.2 = a₀ then c p.1 else 1)
      ∧ ∀ p j, (Matrix.diagonal fun p : V × A => if p.2 = a₀ then c p.1 else 1) p (j, a₀)
          = if p = (j, a₀) then c j else 0 := by
  have hd : ∀ p j, (Matrix.diagonal fun p : V × A => if p.2 = a₀ then c p.1 else 1) p (j, a₀)
      = if p = (j, a₀) then c j else 0 := by
    intro p j
    rw [Matrix.diagonal_apply]
    by_cases hp : p = (j, a₀)
    · subst hp; simp
    · rw [if_neg hp, if_neg hp]
  refine ⟨⟨?_, c, hd⟩, hd⟩
  rw [Matrix.mem_unitaryGroup_iff, Matrix.star_eq_conjTranspose, Matrix.diagonal_conjTranspose,
    Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
  congr 1
  funext p
  simp only [Pi.star_apply]
  split_ifs with hp
  · rw [mul_comm, star_mul_self_eq_norm_sq, hc, one_pow, Complex.ofReal_one]
  · simp

/-- **`TG2`, CONVERSE** — `∼_D`-equivalent fibre-Gram data give two-sided related dilations.

The phase `D` is absorbed into a weak element (`weak_diagonal_phase`), after which the fibre-Gram
families are **equal**; the Gram-isometry lemma then supplies one fibre-block unitary per fibre,
assembled into `L ∈ 𝒢_L`; and `L·U·D` agrees with `U'` on the anchored columns, so act 11's
`gaugeRelated_strong_iff_agree_on_anchor` absorbs the off-anchor freedom into a strong — hence
weak — element. The converse therefore rides on act 11's orbit theorem and one lemma. -/
theorem twoSided_of_gramPhaseEquiv {a₀ : A} {U U' : Matrix (V × A) (V × A) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (V × A) ℂ) (hU' : U' ∈ Matrix.unitaryGroup (V × A) ℂ)
    (h : GramPhaseEquiv (FibreGram a₀ U) (FibreGram a₀ U')) :
    ∃ L K : Matrix (V × A) (V × A) ℂ,
      LeftFibreGroup L ∧ WeakAnchorStabilizer a₀ K ∧ U' = L * U * K := by
  classical
  obtain ⟨c, hc1, hcG⟩ := h
  obtain ⟨hD, hDcol⟩ := weak_diagonal_phase (a₀ := a₀) c hc1
  set D : Matrix (V × A) (V × A) ℂ :=
    Matrix.diagonal fun p : V × A => if p.2 = a₀ then c p.1 else 1 with hDdef
  have hGeq : ∀ i, FibreGram a₀ (U * D) i = FibreGram a₀ U' i := by
    intro i
    ext j k
    rw [fibreGram_mul_weak_apply hDcol, hcG]
  have hblock : ∀ i, ∃ M : Matrix A A ℂ, M ∈ Matrix.unitaryGroup A ℂ
      ∧ M * (U * D).submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀))
        = U'.submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀)) :=
    fun i => exists_unitary_of_gram_eq _ _ (hGeq i)
  choose M hMunit hMX using hblock
  set L : Matrix (V × A) (V × A) ℂ :=
    Matrix.of fun p q => if p.1 = q.1 then M p.1 p.2 q.2 else 0 with hLdef
  have hLblock : ∀ i, L.submatrix (fun a : A => (i, a)) (fun a : A => (i, a)) = M i := by
    intro i
    ext a b
    simp [hLdef]
  have hLzero : ∀ p q : V × A, p.1 ≠ q.1 → L p q = 0 := by
    intro p q hpq
    simp [hLdef, hpq]
  have hL : LeftFibreGroup L := by
    refine ⟨?_, hLzero⟩
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose]
    ext p q
    rw [Matrix.mul_apply, Fintype.sum_prod_type]
    obtain ⟨i, a⟩ := p
    obtain ⟨k, b⟩ := q
    by_cases hik : i = k
    · subst hik
      rw [Finset.sum_eq_single i (fun i' _ hi' => Finset.sum_eq_zero fun c' _ => by
          rw [Matrix.conjTranspose_apply, hLzero (i', c') (i, a) hi', star_zero, zero_mul])
        (fun hcon => absurd (Finset.mem_univ _) hcon)]
      have hMi : (M i)ᴴ * M i = 1 := by
        have hh := Matrix.mem_unitaryGroup_iff'.1 (hMunit i)
        rwa [Matrix.star_eq_conjTranspose] at hh
      have := congrFun (congrFun hMi a) b
      rw [Matrix.mul_apply] at this
      simp only [Matrix.conjTranspose_apply] at this ⊢
      simp only [hLdef, Matrix.of_apply, if_true]
      rw [this, Matrix.one_apply, Matrix.one_apply]
      simp [Prod.ext_iff]
    · rw [Matrix.one_apply_ne (fun hcon => hik (Prod.ext_iff.1 hcon).1)]
      refine Finset.sum_eq_zero fun i' _ => Finset.sum_eq_zero fun c' _ => ?_
      by_cases hi' : i' = i
      · rw [hLzero (i', c') (k, b) (by rw [hi']; exact hik), mul_zero]
      · rw [Matrix.conjTranspose_apply, hLzero (i', c') (i, a) hi', star_zero, zero_mul]
  have hagree : ∀ p j, (L * (U * D)) p (j, a₀) = U' p (j, a₀) := by
    intro p j
    obtain ⟨i, a⟩ := p
    have := congrFun (congrFun (left_mul_submatrix hL (U * D) a₀ i) a) j
    rw [hLblock, hMX] at this
    simpa [Matrix.submatrix_apply] using this
  have hLUD : L * (U * D) ∈ Matrix.unitaryGroup (V × A) ℂ := mul_mem hL.1 (mul_mem hU hD.1)
  obtain ⟨K, hKstrong, hfac⟩ := (gaugeRelated_strong_iff_agree_on_anchor (a₀ := a₀)
    (U := fun _ => L * (U * D)) (U' := fun _ => U') (fun _ => hLUD) (fun _ => hU')).2
    (fun _ p j => (hagree p j).symm)
  refine ⟨L, D * K 0, hL, weak_mul hD (strong_mem_weak (hKstrong 0)), ?_⟩
  have := hfac 0
  simp only at this
  rw [this]
  simp only [Matrix.mul_assoc]

/-- **`TG2` — THE FIBRE-GRAM ORBIT THEOREM**, single slice, both directions: two unitaries on the
dilated carrier are related by the two-sided uniform gauge exactly when their fibre-Gram data are
`∼_D`-equivalent. Admissible dilations of one `Γ` at one anchor are the intended instance; nothing
beyond unitarity is needed for the statement. -/
theorem twoSided_slice_iff {a₀ : A} {U U' : Matrix (V × A) (V × A) ℂ}
    (hU : U ∈ Matrix.unitaryGroup (V × A) ℂ) (hU' : U' ∈ Matrix.unitaryGroup (V × A) ℂ) :
    (∃ L K : Matrix (V × A) (V × A) ℂ,
        LeftFibreGroup L ∧ WeakAnchorStabilizer a₀ K ∧ U' = L * U * K)
      ↔ GramPhaseEquiv (FibreGram a₀ U) (FibreGram a₀ U') := by
  constructor
  · rintro ⟨L, K, hL, hK, rfl⟩
    exact gramPhaseEquiv_of_twoSided hL hK
  · exact twoSided_of_gramPhaseEquiv hU hU'

/-- **THE LIFTED FORM, SLICE-WISE** — two `ℕ`-indexed lifts are two-sided related exactly when their
fibre-Gram data are `∼_D`-equivalent at every time. A corollary of `twoSided_slice_iff`, and **per
slice only**: nothing couples the Gram data across time (hazard 3). -/
theorem twoSidedRelated_iff {a₀ : A} {U U' : ℕ → Matrix (V × A) (V × A) ℂ}
    (hU : ∀ t, U t ∈ Matrix.unitaryGroup (V × A) ℂ)
    (hU' : ∀ t, U' t ∈ Matrix.unitaryGroup (V × A) ℂ) :
    TwoSidedRelated a₀ U U'
      ↔ ∀ t, GramPhaseEquiv (FibreGram a₀ (U t)) (FibreGram a₀ (U' t)) := by
  constructor
  · rintro ⟨L, K, hL, hK, hfac⟩ t
    rw [hfac t]
    exact gramPhaseEquiv_of_twoSided (hL t) (hK t)
  · intro h
    choose L K hLK using fun t => (twoSided_slice_iff (hU t) (hU' t)).2 (h t)
    exact ⟨L, K, fun t => (hLK t).1, fun t => (hLK t).2.1, fun t => (hLK t).2.2⟩

/-- **`SH1-C2`'s ORBIT CONSEQUENCE, which rides on the `TG2` converse**: a realizable deterministic
slice has a unique two-sided orbit — any two admissible dilations are two-sided related. Reported
only together with `twoSided_of_gramPhaseEquiv`, exactly as the freeze requires. -/
theorem sh1_c2_unique_orbit {Γ : Matrix V V ℝ} {a₀ : A} {U U' : Matrix (V × A) (V × A) ℂ}
    (hdet : ∀ j : V, ∃ i₀ : V, ∀ i, i ≠ i₀ → Γ i j = 0)
    (hU : AdmissibleDilationAt Γ a₀ U) (hU' : AdmissibleDilationAt Γ a₀ U') :
    ∃ L K : Matrix (V × A) (V × A) ℂ,
      LeftFibreGroup L ∧ WeakAnchorStabilizer a₀ K ∧ U' = L * U * K :=
  twoSided_of_gramPhaseEquiv hU.1 hU'.1 ⟨fun _ => 1, fun _ => by simp, fun i j k => by
    rw [sh1_c2_at_most_one hdet hU hU']; simp⟩

/-! ### Section I — `TG3`: the Hadamard witness at `|A| = 1`, `|V| = 4` -/

omit [Fintype V] [DecidableEq V] [Fintype A] [DecidableEq A] in
/-- **A `∼_D`-INVARIANT OF THE GRAM DATA.** `G^{(i₀)}_{i₁ i₀} · G^{(i₁)}_{i₀ i₁}` is unchanged by
the anchored phases: the two factors pick up `conj(c_{i₁}) c_{i₀}` and `conj(c_{i₀}) c_{i₁}`. At
`|A| = 1` this is the cross-ratio `C(U) = U_{i₀i₀}U_{i₁i₁}/(U_{i₀i₁}U_{i₁i₀})` times
`|U_{i₀ i₁}|² |U_{i₁ i₀}|²`, the moduli being `∼_D`-invariant diagonal entries themselves. -/
theorem gramPhaseEquiv_cross_invariant {G G' : V → Matrix V V ℂ} (h : GramPhaseEquiv G G')
    (i₀ i₁ : V) : G' i₀ i₁ i₀ * G' i₁ i₀ i₁ = G i₀ i₁ i₀ * G i₁ i₀ i₁ := by
  obtain ⟨c, hc, hG⟩ := h
  have h0 : c i₀ * star (c i₀) = 1 := by
    rw [mul_comm, star_mul_self_eq_norm_sq, hc, one_pow, Complex.ofReal_one]
  have h1 : c i₁ * star (c i₁) = 1 := by
    rw [mul_comm, star_mul_self_eq_norm_sq, hc, one_pow, Complex.ofReal_one]
  rw [hG, hG]
  calc star (c i₁) * G i₀ i₁ i₀ * c i₀ * (star (c i₀) * G i₁ i₀ i₁ * c i₁)
      = (G i₀ i₁ i₀ * G i₁ i₀ i₁) * ((c i₀ * star (c i₀)) * (c i₁ * star (c i₁))) := by ring
    _ = G i₀ i₁ i₀ * G i₁ i₀ i₁ := by rw [h0, h1, one_mul, mul_one]

/-- **THE CROSS-RATIO, COMPUTED IN THE KERNEL**: `C(H(1)) = 1` and `C(H(i)) = i`, for
`C(U) = U_{00}U_{11} / (U_{01}U_{10})` on the frozen family
`H(z) = ½ · [[1,1,1,1],[1,z,−1,−z],[1,−1,1,−1],[1,−z,−1,z]]`. -/
theorem hadamard_cross_ratio :
    ∀ H₁ Hᵢ : Matrix (Fin 4 × Fin 1) (Fin 4 × Fin 1) ℂ,
      H₁ = Matrix.of (fun p q : Fin 4 × Fin 1 =>
          (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1) →
      Hᵢ = Matrix.of (fun p q : Fin 4 × Fin 1 =>
          (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, Complex.I, -1, -Complex.I; 1, -1, 1, -1;
            1, -Complex.I, -1, Complex.I] p.1 q.1) →
      H₁ (0, 0) (0, 0) * H₁ (1, 0) (1, 0) / (H₁ (0, 0) (1, 0) * H₁ (1, 0) (0, 0)) = 1
        ∧ Hᵢ (0, 0) (0, 0) * Hᵢ (1, 0) (1, 0) / (Hᵢ (0, 0) (1, 0) * Hᵢ (1, 0) (0, 0))
            = Complex.I := by
  rintro _ _ rfl rfl
  refine ⟨by simp, ?_⟩
  simp
  ring

/-- **`TG3`, THE SLICES** — on the single visible law `Γ_{ij} = ¼` at `|A| = 1`, `|V| = 4`, the two
exact Hadamard dilations `H(1)` and `H(i)` are both admissible, have **inequivalent** fibre-Gram
data (the `∼_D`-invariant `G^{(0)}_{10} G^{(1)}_{01}` is `1/16` for one and `i/16` for the other),
and are therefore — by `TG2` — in **different two-sided orbits**.

`|A| = 1` is the *strongest* case, not a degenerate one (hazard 8): the two-sided gauge is row
phases times column phases there, the smallest it can be. -/
theorem hadamard_slices_not_twoSided :
    ∃ (Γ : Matrix (Fin 4) (Fin 4) ℝ) (H₁ Hᵢ : Matrix (Fin 4 × Fin 1) (Fin 4 × Fin 1) ℂ),
      Γ = Matrix.of (fun _ _ => (1 / 4 : ℝ))
        ∧ H₁ = Matrix.of (fun p q : Fin 4 × Fin 1 =>
            (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1)
        ∧ Hᵢ = Matrix.of (fun p q : Fin 4 × Fin 1 =>
            (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, Complex.I, -1, -Complex.I; 1, -1, 1, -1;
              1, -Complex.I, -1, Complex.I] p.1 q.1)
        ∧ AdmissibleDilationAt Γ (0 : Fin 1) H₁ ∧ AdmissibleDilationAt Γ (0 : Fin 1) Hᵢ
        ∧ ¬ GramPhaseEquiv (FibreGram (0 : Fin 1) H₁) (FibreGram (0 : Fin 1) Hᵢ)
        ∧ ¬ ∃ L K : Matrix (Fin 4 × Fin 1) (Fin 4 × Fin 1) ℂ,
            LeftFibreGroup L ∧ WeakAnchorStabilizer (0 : Fin 1) K ∧ Hᵢ = L * H₁ * K := by
  classical
  have hunit₁ : (Matrix.of (fun p q : Fin 4 × Fin 1 =>
      (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1))
      ∈ Matrix.unitaryGroup (Fin 4 × Fin 1) ℂ := by
    rw [Matrix.mem_unitaryGroup_iff, Matrix.star_eq_conjTranspose]
    ext p q
    obtain ⟨x, y⟩ := p
    obtain ⟨u, v⟩ := q
    fin_cases x <;> fin_cases y <;> fin_cases u <;> fin_cases v <;>
      simp [Matrix.mul_apply, Fintype.sum_prod_type, Fin.sum_univ_four,
        Matrix.conjTranspose_apply] <;> norm_num [Complex.ext_iff]
  have hunitᵢ : (Matrix.of (fun p q : Fin 4 × Fin 1 =>
      (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, Complex.I, -1, -Complex.I; 1, -1, 1, -1;
        1, -Complex.I, -1, Complex.I] p.1 q.1))
      ∈ Matrix.unitaryGroup (Fin 4 × Fin 1) ℂ := by
    rw [Matrix.mem_unitaryGroup_iff, Matrix.star_eq_conjTranspose]
    ext p q
    obtain ⟨x, y⟩ := p
    obtain ⟨u, v⟩ := q
    fin_cases x <;> fin_cases y <;> fin_cases u <;> fin_cases v <;>
      simp [Matrix.mul_apply, Fintype.sum_prod_type, Fin.sum_univ_four,
        Matrix.conjTranspose_apply] <;> norm_num [Complex.ext_iff]
  have hnotG : ¬ GramPhaseEquiv
      (FibreGram (0 : Fin 1) (Matrix.of (fun p q : Fin 4 × Fin 1 =>
        (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1)))
      (FibreGram (0 : Fin 1) (Matrix.of (fun p q : Fin 4 × Fin 1 =>
        (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, Complex.I, -1, -Complex.I; 1, -1, 1, -1;
          1, -Complex.I, -1, Complex.I] p.1 q.1))) := by
    intro hG
    have := gramPhaseEquiv_cross_invariant hG 0 1
    simp [fibreGram_apply] at this
    norm_num [Complex.ext_iff] at this
  refine ⟨_, _, _, rfl, rfl, rfl, ⟨hunit₁, fun i j => ?_⟩, ⟨hunitᵢ, fun i j => ?_⟩, hnotG, ?_⟩
  · fin_cases i <;> fin_cases j <;> simp <;> norm_num
  · fin_cases i <;> fin_cases j <;> simp <;> norm_num
  · rintro ⟨L, K, hL, hK, hfac⟩
    have := gramPhaseEquiv_of_twoSided (U := Matrix.of (fun p q : Fin 4 × Fin 1 =>
      (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1)) hL hK
    rw [← hfac] at this
    exact hnotG this

/-- **`TG3`, THE LIFTS** — two coherent lifts of one constant visible family, `U_t = H(1)` and
`U'_0 = H(1)`, `U'_t = H(i)` for `t ≥ 1`, that are **not** two-sided related and whose relative
objects **differ**: `U'_1 U'_0ᴴ = H(i)H(1)ᴴ ≠ 1 = U_1 U_0ᴴ`.

This is the two-sided existence statement, closed independently of `GI2`. **It is not an
inequivalence** (hazard 1): two lifts differing is not two theories differing. -/
theorem hadamard_lifts_not_twoSided :
    ∃ (Γ : ℕ → Matrix (Fin 4) (Fin 4) ℝ) (U U' : ℕ → Matrix (Fin 4 × Fin 1) (Fin 4 × Fin 1) ℂ),
      (∀ t, U t = Matrix.of (fun p q : Fin 4 × Fin 1 =>
          (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, 1, -1, -1; 1, -1, 1, -1; 1, -1, -1, 1] p.1 q.1))
        ∧ U' 0 = U 0
        ∧ (∀ t, t ≠ 0 → U' t = Matrix.of (fun p q : Fin 4 × Fin 1 =>
            (1 / 2 : ℂ) * !![1, 1, 1, 1; 1, Complex.I, -1, -Complex.I; 1, -1, 1, -1;
              1, -Complex.I, -1, Complex.I] p.1 q.1))
        ∧ CoherentLift (0 : Fin 1) Γ U ∧ CoherentLift (0 : Fin 1) Γ U'
        ∧ ¬ TwoSidedRelated (0 : Fin 1) U U'
        ∧ U' 1 * (U' 0)ᴴ ≠ U 1 * (U 0)ᴴ := by
  classical
  obtain ⟨Γ, H₁, Hᵢ, hΓ, hH₁, hHᵢ, hadm₁, hadmᵢ, hnotG, hnot2⟩ := hadamard_slices_not_twoSided
  refine ⟨fun _ => Γ, fun _ => H₁, fun t => if t = 0 then H₁ else Hᵢ, fun _ => hH₁, by simp,
    fun t ht => by simp [ht, hHᵢ], fun _ => hadm₁, ?_, ?_, ?_⟩
  · intro t
    by_cases ht : t = 0
    · simp only [if_pos ht]; exact hadm₁
    · simp only [if_neg ht]; exact hadmᵢ
  · rintro ⟨L, K, hL, hK, hfac⟩
    exact hnot2 ⟨L 1, K 1, hL 1, hK 1, by simpa using hfac 1⟩
  · simp only [if_neg one_ne_zero]
    intro hcon
    have h13 := congrFun (congrFun hcon ((1 : Fin 4), (0 : Fin 1))) ((3 : Fin 4), (0 : Fin 1))
    rw [hH₁, hHᵢ] at h13
    simp [Matrix.mul_apply, Fintype.sum_prod_type, Fin.sum_univ_four,
      Matrix.conjTranspose_apply] at h13
    norm_num [Complex.ext_iff] at h13

/-! ### Section J — `SH1` sufficiency: every realizable tuple is realized -/

/-- **A POSITIVE SEMIDEFINITE MATRIX OF RANK AT MOST `|A|` FACTORS THROUGH `ℂ^A`**: `G = Wᴴ W`
with `W` having `|A|` rows. Spectral decomposition `G = E Λ Eᴴ` with `Λ ≥ 0` and — by the rank
hypothesis — at most `|A|` nonzero eigenvalues; the rows of `W` are `√λ_v · (row v of Eᴴ)` placed at
an injective choice of slots in `A`, zero elsewhere. **This is where the rank constraint is
consumed** (hazard 9): without it there is no room for the nonzero eigenvalues. -/
theorem posSemidef_factor_of_rank_le {G : Matrix V V ℂ} (hG : G.PosSemidef)
    (hr : G.rank ≤ Fintype.card A) : ∃ W : Matrix A V ℂ, Wᴴ * W = G := by
  classical
  have hH : G.IsHermitian := hG.1
  set E : Matrix V V ℂ := (hH.eigenvectorUnitary : Matrix V V ℂ) with hE
  set lam : V → ℝ := hH.eigenvalues with hlam
  have hspec : G = E * Matrix.diagonal (RCLike.ofReal ∘ lam) * Eᴴ := by
    have := hH.spectral_theorem
    rw [Unitary.conjStarAlgAut_apply, Matrix.star_eq_conjTranspose] at this
    exact this
  have hnn : ∀ v, 0 ≤ lam v := fun v => hG.eigenvalues_nonneg v
  have hrank : Fintype.card {v // lam v ≠ 0} ≤ Fintype.card A := by
    rw [← hH.rank_eq_card_non_zero_eigs]
    exact hr
  obtain ⟨f⟩ := Function.Embedding.nonempty_of_card_le hrank
  set W : Matrix A V ℂ := Matrix.of fun a j =>
    if h : ∃ v : {v // lam v ≠ 0}, f v = a
    then ((Real.sqrt (lam h.choose.1) : ℝ) : ℂ) * star (E j h.choose.1) else 0 with hW
  refine ⟨W, ?_⟩
  ext j k
  have hGjk : G j k = ∑ v, E j v * (lam v : ℂ) * star (E k v) := by
    conv_lhs => rw [hspec]
    rw [Matrix.mul_apply]
    refine Finset.sum_congr rfl fun v _ => ?_
    rw [Matrix.mul_diagonal, Matrix.conjTranspose_apply]
    simp [Function.comp]
  have hWoff : ∀ a, (¬ ∃ v : {v // lam v ≠ 0}, f v = a) → ∀ j, W a j = 0 := by
    intro a ha j
    rw [hW, Matrix.of_apply, dif_neg ha]
  have hWon : ∀ v : {v // lam v ≠ 0}, ∀ j,
      W (f v) j = ((Real.sqrt (lam v.1) : ℝ) : ℂ) * star (E j v.1) := by
    intro v j
    have hex : ∃ v' : {v // lam v ≠ 0}, f v' = f v := ⟨v, rfl⟩
    have hch : hex.choose = v := f.injective hex.choose_spec
    simp only [hW, Matrix.of_apply, dif_pos hex, hch]
  have hcompl : ∑ a ∈ (Finset.univ.map f)ᶜ, star (W a j) * W a k = 0 := by
    refine Finset.sum_eq_zero fun a ha => ?_
    have hna : ¬ ∃ v : {v // lam v ≠ 0}, f v = a := by
      rintro ⟨v, rfl⟩
      exact (Finset.mem_compl.1 ha) (Finset.mem_map_of_mem f (Finset.mem_univ v))
    rw [hWoff a hna, hWoff a hna, star_zero, zero_mul]
  rw [Matrix.mul_apply]
  simp only [Matrix.conjTranspose_apply]
  rw [← Finset.sum_add_sum_compl (Finset.univ.map f), hcompl, add_zero, Finset.sum_map]
  simp only [hWon]
  rw [hGjk, ← Finset.sum_filter_of_ne (p := fun v => lam v ≠ 0)
    (fun v _ hv hl => hv (by rw [hl]; simp)),
    Finset.sum_subtype (p := fun v => lam v ≠ 0) (Finset.univ.filter fun v => lam v ≠ 0)
      (fun v => by simp)]
  refine Finset.sum_congr rfl fun v _ => ?_
  have hsr : star ((Real.sqrt (lam v.1) : ℝ) : ℂ) = ((Real.sqrt (lam v.1) : ℝ) : ℂ) := by
    rw [RCLike.star_def, Complex.conj_ofReal]
  have hs : ((Real.sqrt (lam v.1) : ℝ) : ℂ) * ((Real.sqrt (lam v.1) : ℝ) : ℂ) = (lam v.1 : ℂ) := by
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt (hnn v.1)]
  rw [star_mul', star_star, hsr]
  calc ((Real.sqrt (lam v.1) : ℝ) : ℂ) * E j v.1
        * (((Real.sqrt (lam v.1) : ℝ) : ℂ) * star (E k v.1))
      = (((Real.sqrt (lam v.1) : ℝ) : ℂ) * ((Real.sqrt (lam v.1) : ℝ) : ℂ))
          * (E j v.1 * star (E k v.1)) := by ring
    _ = E j v.1 * (lam v.1 : ℂ) * star (E k v.1) := by rw [hs]; ring

/-- **`SH1`, SUFFICIENCY** — every realizable Gram tuple is the fibre-Gram data of an admissible
dilation. Each `G^{(i)}` factors as `W_iᴴ W_i` with `|A|` rows (`posSemidef_factor_of_rank_le`);
the `W_i` stack into `|V|` columns indexed by `V × A`, orthonormal because `∑_i G^{(i)} = I`; and
Mathlib's `Orthonormal.exists_orthonormalBasis_extension_of_card_eq` extends them to an orthonormal
basis whose matrix is the unitary, with the stacked columns in the anchored slots. The diagonal
condition then gives admissibility. **Reached at kernel level**: the frozen level-3 fallback is not
used. -/
theorem sh1_sufficiency {Γ : Matrix V V ℝ} (a₀ : A) {G : V → Matrix V V ℂ}
    (hG : RealizableGram A Γ G) :
    ∃ U : Matrix (V × A) (V × A) ℂ, AdmissibleDilationAt Γ a₀ U ∧ FibreGram a₀ U = G := by
  classical
  obtain ⟨hpsd, hrank, hsum, hdiag⟩ := hG
  choose W hW using fun i => posSemidef_factor_of_rank_le (hpsd i) (hrank i)
  set X : Matrix (V × A) V ℂ := Matrix.of fun p j => W p.1 p.2 j with hX
  have hXX : Xᴴ * X = 1 := by
    ext j k
    have h1 := congrFun (congrFun hsum j) k
    rw [Matrix.sum_apply] at h1
    rw [Matrix.mul_apply, Fintype.sum_prod_type, ← h1]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← hW i, Matrix.mul_apply]
    simp [hX, Matrix.conjTranspose_apply]
  set v : V × A → EuclideanSpace ℂ (V × A) := fun q => WithLp.toLp 2 (fun p => X p q.1) with hv
  have hon : Orthonormal ℂ ({q : V × A | q.2 = a₀}.domRestrict v) := by
    rw [orthonormal_iff_ite]
    rintro ⟨⟨j, a⟩, ha⟩ ⟨⟨k, b⟩, hb⟩
    have ha' : a = a₀ := ha
    have hb' : b = a₀ := hb
    subst a
    subst b
    have h1 := congrFun (congrFun hXX j) k
    rw [Matrix.mul_apply, Matrix.one_apply] at h1
    simp only [Matrix.conjTranspose_apply] at h1
    have hiff : ((⟨(j, a₀), rfl⟩ : {q : V × A // q.2 = a₀}) = ⟨(k, a₀), rfl⟩) ↔ j = k := by
      simp
    show inner ℂ (v (j, a₀)) (v (k, a₀))
      = if (⟨(j, a₀), rfl⟩ : {q : V × A // q.2 = a₀}) = ⟨(k, a₀), rfl⟩ then 1 else 0
    rw [if_congr hiff rfl rfl, hv]
    simp only [EuclideanSpace.inner_toLp_toLp]
    rw [dotProduct_comm]
    simp only [dotProduct, Pi.star_apply]
    exact h1
  obtain ⟨bb, hbb⟩ := hon.exists_orthonormalBasis_extension_of_card_eq
    (finrank_euclideanSpace (𝕜 := ℂ) (ι := V × A))
  set U : Matrix (V × A) (V × A) ℂ :=
    (EuclideanSpace.basisFun (V × A) ℂ).toBasis.toMatrix bb.toBasis with hU
  have hUunit : U ∈ Matrix.unitaryGroup (V × A) ℂ :=
    (EuclideanSpace.basisFun (V × A) ℂ).toMatrix_orthonormalBasis_mem_unitary bb
  have hUapply : ∀ p q, U p q = WithLp.ofLp (bb q) p := by
    intro p q
    simp [hU, Module.Basis.toMatrix_apply, OrthonormalBasis.coe_toBasis_repr_apply,
      EuclideanSpace.basisFun_repr, OrthonormalBasis.coe_toBasis]
  have hUanch : ∀ (i : V) (a : A) (j : V), U (i, a) (j, a₀) = W i a j := by
    intro i a j
    rw [hUapply, hbb (j, a₀) rfl]
    simp [hv, hX]
  have hsub : ∀ i, U.submatrix (fun a : A => (i, a)) (fun j : V => (j, a₀)) = W i := by
    intro i
    ext a j
    rw [Matrix.submatrix_apply, hUanch]
  have hGram : FibreGram a₀ U = G := by
    funext i
    rw [FibreGram, hsub, hW]
  refine ⟨U, ⟨hUunit, fun i j => ?_⟩, hGram⟩
  have h1 := congrFun (congrFun (congrFun hGram i) j) j
  rw [fibreGram_diag, hdiag] at h1
  exact_mod_cast h1.symm

/-- **`SH1` — THE SHAPE THEOREM**, both directions: a family `{G^{(i)}}` is the fibre-Gram data of
some admissible dilation of `Γ` at `a₀` **iff** it is a realizable Gram tuple. Together with `TG2`:
the visible law is exactly the diagonal of the fibre-Gram data, and the residual lift freedom after
the two-sided uniform gauge `𝒢_L × 𝒢ʷ_{a₀}` is exactly the off-diagonal fibre-Gram data modulo the
anchored phases — **per time slice**. -/
theorem sh1_shape {Γ : Matrix V V ℝ} (a₀ : A) (G : V → Matrix V V ℂ) :
    (∃ U : Matrix (V × A) (V × A) ℂ, AdmissibleDilationAt Γ a₀ U ∧ FibreGram a₀ U = G)
      ↔ RealizableGram A Γ G :=
  ⟨fun ⟨_, hU, hG⟩ => hG ▸ sh1_necessity hU, fun hG => sh1_sufficiency a₀ hG⟩

end TwoSidedGauge
end OIBridge

/-! ### Axiom report — one line per named result -/

#print axioms OIBridge.TwoSidedGauge.fibreGram_apply
#print axioms OIBridge.TwoSidedGauge.star_mul_self_eq_norm_sq
#print axioms OIBridge.TwoSidedGauge.fibreGram_diag
#print axioms OIBridge.TwoSidedGauge.fibreGram_diag_of_admissible
#print axioms OIBridge.TwoSidedGauge.fibreGram_posSemidef
#print axioms OIBridge.TwoSidedGauge.fibreGram_rank_le
#print axioms OIBridge.TwoSidedGauge.sum_fibreGram
#print axioms OIBridge.TwoSidedGauge.sh1_necessity
#print axioms OIBridge.TwoSidedGauge.left_mul_submatrix
#print axioms OIBridge.TwoSidedGauge.left_block_unitary
#print axioms OIBridge.TwoSidedGauge.fibreGram_left_mul
#print axioms OIBridge.TwoSidedGauge.left_preserves_admissible
#print axioms OIBridge.TwoSidedGauge.one_leftFibreGroup
#print axioms OIBridge.TwoSidedGauge.mul_weak_anchor_col
#print axioms OIBridge.TwoSidedGauge.fibreGram_mul_weak_apply
#print axioms OIBridge.TwoSidedGauge.weak_mul
#print axioms OIBridge.TwoSidedGauge.gramPhaseEquiv_of_twoSided
#print axioms OIBridge.TwoSidedGauge.twoSidedRelated_of_gaugeRelated_weak
#print axioms OIBridge.TwoSidedGauge.twoSidedRelated_of_gaugeRelated_strong
#print axioms OIBridge.TwoSidedGauge.left_of_preserves_every_admissible
#print axioms OIBridge.TwoSidedGauge.anchored_entry_eq_zero_of_visible_zero
#print axioms OIBridge.TwoSidedGauge.sh1_c1_fibreGram
#print axioms OIBridge.TwoSidedGauge.posSemidef_apply_eq_zero_of_diag_eq_zero
#print axioms OIBridge.TwoSidedGauge.sh1_c1
#print axioms OIBridge.TwoSidedGauge.fibreGram_of_deterministic
#print axioms OIBridge.TwoSidedGauge.sh1_c2_at_most_one
#print axioms OIBridge.TwoSidedGauge.inFibreSwap_leftFibreGroup
#print axioms OIBridge.TwoSidedGauge.lg1_escape_right_orbit
#print axioms OIBridge.TwoSidedGauge.ro1_right_only_insufficient
#print axioms OIBridge.TwoSidedGauge.gi2_pair_twoSidedRelated
#print axioms OIBridge.TwoSidedGauge.exists_unitary_of_gram_eq
#print axioms OIBridge.TwoSidedGauge.weak_diagonal_phase
#print axioms OIBridge.TwoSidedGauge.twoSided_of_gramPhaseEquiv
#print axioms OIBridge.TwoSidedGauge.twoSided_slice_iff
#print axioms OIBridge.TwoSidedGauge.twoSidedRelated_iff
#print axioms OIBridge.TwoSidedGauge.sh1_c2_unique_orbit
#print axioms OIBridge.TwoSidedGauge.gramPhaseEquiv_cross_invariant
#print axioms OIBridge.TwoSidedGauge.hadamard_cross_ratio
#print axioms OIBridge.TwoSidedGauge.hadamard_slices_not_twoSided
#print axioms OIBridge.TwoSidedGauge.hadamard_lifts_not_twoSided
#print axioms OIBridge.TwoSidedGauge.posSemidef_factor_of_rank_le
#print axioms OIBridge.TwoSidedGauge.sh1_sufficiency
#print axioms OIBridge.TwoSidedGauge.sh1_shape
