"""Thread K — exact checks for boundary transitivity of the elementary dynamics.

Exact arithmetic only: sympy symbolic trigonometry (no floats), rationals, exact radicals.
Run: PYTHONDONTWRITEBYTECODE=1 python3 k_groups.py
Every check is counted; written steps are printed as NOTE and are not counted.
"""
import itertools
from fractions import Fraction as Fr
import sympy as sp

CHECKS = 0
NOTES = 0


def check(name, cond):
    global CHECKS
    if not cond:
        raise SystemExit(f"FAIL {name}")
    CHECKS += 1
    print(f"ok    {name}")


def note(text):
    global NOTES
    NOTES += 1
    print(f"NOTE  {text}")


def zero(M):
    """Exact symbolic zero test for a matrix or scalar."""
    M = sp.Matrix(M) if not isinstance(M, sp.Basic) or hasattr(M, 'shape') else M
    if hasattr(M, 'shape'):
        return all(sp.simplify(sp.expand_trig(sp.expand(e.rewrite(sp.cos)))) == 0 for e in M)
    return sp.simplify(sp.expand_trig(sp.expand(M.rewrite(sp.cos)))) == 0


t, s, th, ph, al, be, ga = sp.symbols('t s theta phi alpha beta gamma', real=True)
pi = sp.pi


def Rz(a):
    # KF:351 rotFun t v = (cos t v0 - sin t v1, sin t v0 + cos t v1, v2)
    return sp.Matrix([[sp.cos(a), -sp.sin(a), 0], [sp.sin(a), sp.cos(a), 0], [0, 0, 1]])


def Rx(a):
    return sp.Matrix([[1, 0, 0], [0, sp.cos(a), -sp.sin(a)], [0, sp.sin(a), sp.cos(a)]])


def Ry(a):
    return sp.Matrix([[sp.cos(a), 0, sp.sin(a)], [0, 1, 0], [-sp.sin(a), 0, sp.cos(a)]])


# KF:416 cycEquiv v = ![v 2, v 0, v 1]
C = sp.Matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
ex, ey, ez = sp.Matrix([1, 0, 0]), sp.Matrix([0, 1, 0]), sp.Matrix([0, 0, 1])


def lie_dim(gens):
    """Dimension over Q of the Lie algebra generated by rational/algebraic matrices (bracket closure)."""
    n = gens[0].shape[0]
    basis = []

    def rank_of(mats):
        if not mats:
            return 0
        return sp.Matrix([list(m.reshape(1, n * n)) for m in mats]).rank(simplify=True)

    for g in gens:
        if rank_of(basis + [g]) > rank_of(basis):
            basis.append(g)
    changed = True
    while changed:
        changed = False
        for a, b in itertools.product(list(basis), list(basis)):
            c = (a * b - b * a).applyfunc(sp.nsimplify)
            if rank_of(basis + [c]) > rank_of(basis):
                basis.append(c)
                changed = True
    return len(basis)


Lz = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])  # d/dt Rz(t) at 0

print("=== §1  ball3Drive (KF:449): the generated group is SO(3), transitive on the sphere")
check("1.01 cyc3 matrix has det +1 (cyc3 ∈ SO(3))", C.det() == 1 and C * C.T == sp.eye(3))
check("1.02 cyc3 e_z = e_x", C * ez == ex)
check("1.03 cyc3 Rz(t) cyc3^-1 = Rx(t) for symbolic t (conjugate flow = rotation about e_x)",
      zero(C * Rz(t) * C.T - Rx(t)))
check("1.04 rot3 group law Rz(s)Rz(t) = Rz(s+t) (KF:366 restated)", zero(Rz(s) * Rz(t) - Rz(s + t)))
check("1.05 N = Rz(pi) is involutive and moves e_x", Rz(pi) * Rz(pi) == sp.eye(3) and Rz(pi) * ex == -ex)
check("1.06 D9 witness: cyc3 Rz(pi) cyc3^-1 e_z = -e_z while Rz(s) e_z = e_z for every s",
      C * Rz(pi) * C.T * ez == -ez and zero(Rz(s) * ez - ez))
# transitivity word
target = sp.Matrix([sp.sin(th) * sp.cos(ph), sp.sin(th) * sp.sin(ph), sp.cos(th)])
check("1.07 Euler word: Rz(phi+pi/2) Rx(theta) e_z = (sinθcosφ, sinθsinφ, cosθ) for symbolic θ, φ",
      zero(Rz(ph + pi / 2) * Rx(th) * ez - target))
check("1.08 Rx(theta) = cyc3 Rz(theta) cyc3^-1, so the word lies in <rot3(R), cyc3>",
      zero(C * Rz(th) * C.T - Rx(th)))
check("1.09 stabilizer of e_z in SO(3) is {Rz}: Rz(γ) fixes e_z (symbolic)", zero(Rz(ga) * ez - ez))


def cayley(K):
    I3 = sp.eye(3)
    return (I3 - K).inv() * (I3 + K)


def skew(a, b, c):
    return sp.Matrix([[0, -c, b], [c, 0, -a], [-b, a, 0]])


samples = [(1, 2, 3), (Fr(1, 2), -3, 5), (-2, 0, 1), (0, 0, 7), (3, -1, Fr(2, 3)), (1, 1, 0)]
for k, (a, b, c) in enumerate(samples):
    R = cayley(skew(sp.Rational(a), sp.Rational(b), sp.Rational(c)))
    assert R * R.T == sp.eye(3) and R.det() == 1
    cb = R[2, 2]
    sb = sp.sqrt(R[0, 2] ** 2 + R[1, 2] ** 2)
    if sb == 0:
        # R fixes the z-axis: R = Rz(angle) (det 1, R e_z = e_z) or a half-turn about a horizontal axis
        if R[2, 2] == 1:
            ok = R[:2, :2].det() == 1 and R[0, 0] == R[1, 1] and R[0, 1] == -R[1, 0]
            check(f"1.10.{k} rational rotation {R.tolist()} is a flow member Rz", ok)
            continue
    sa, ca = R[0, 2] / sb, -R[1, 2] / sb
    sg, cg = R[2, 0] / sb, R[2, 1] / sb

    def RzCS(c_, s_):
        return sp.Matrix([[c_, -s_, 0], [s_, c_, 0], [0, 0, 1]])

    def RxCS(c_, s_):
        return C * RzCS(c_, s_) * C.T

    W = RzCS(ca, sa) * RxCS(cb, sb) * RzCS(cg, sg)
    check(f"1.10.{k} exact zxz Euler word in flow and cyc3-conjugate flow reproduces Cayley rotation "
          f"from skew({a},{b},{c})",
          (W - R).applyfunc(sp.simplify) == sp.zeros(3, 3) and sp.simplify(ca**2 + sa**2) == 1
          and sp.simplify(cg**2 + sg**2) == 1)
check("1.11 Lie algebra generated by Lz and cyc3 Lz cyc3^-1 has dimension 3 = dim so(3)",
      lie_dim([Lz, C * Lz * C.T]) == 3)
# mutations: axis-preserving J
Jm1 = Rz(pi / 2)
Jm2 = sp.diag(1, -1, -1)
check("1.12 mutation J = Rz(pi/2): J Rz(t) J^-1 = Rz(t) — D9 fails, Lie dim 1, orbit of e_z is {e_z}",
      zero(Jm1 * Rz(t) * Jm1.T - Rz(t)) and lie_dim([Lz, Jm1 * Lz * Jm1.T]) == 1 and Jm1 * ez == ez)
check("1.13 mutation J = diag(1,-1,-1): J Rz(t) J^-1 = Rz(-t) — D9 fails, J e_z = -e_z, Lie dim 1",
      zero(Jm2 * Rz(t) * Jm2.T - Rz(-t)) and Jm2 * ez == -ez and lie_dim([Lz, Jm2 * Lz * Jm2.T]) == 1)
note("1.N1 G = <rot3(R), cyc3> ⊇ {Rz(α)Rx(β)Rz(γ)} = SO(3) as an abstract group (1.03, 1.10, zxz Euler); "
     "cyc3 ∈ SO(3) (1.01), so G = SO(3) exactly. No closure is taken; D3 is not used because rot3 is "
     "surjective onto the circle by construction. Boundary states of ball3 = unit sphere "
     "(⇒: proof of supportingEffectComplete_ball3 KF:1056–1062; ⇐: y = −x). G is transitive on it (1.07).")

print("\n=== §2  every drive on ball3: transitive given D3; D3 load-bearing")
# off-axis with general rational J: Lie closure of two non-parallel axes
for k, (a, b, c) in enumerate([(1, 2, 3), (Fr(1, 3), 0, 0), (0, Fr(1, 5), 1)]):
    J = cayley(skew(sp.Rational(a), sp.Rational(b), sp.Rational(c)))
    axis2 = J * ez
    nonpar = axis2 != ez and axis2 != -ez
    check(f"2.01.{k} rational J (Cayley {a},{b},{c}): J e_z ∉ {{±e_z}} and Lie<Lz, J Lz J^-1> has dim 3",
          nonpar and lie_dim([Lz, J * Lz * J.T]) == 3)
# reflection J with axis off: still generates
Jr = sp.eye(3) - 2 * sp.Matrix([1, 0, 1]) * sp.Matrix([[1, 0, 1]]) / 2  # reflection in plane ⟂ (1,0,1)
check("2.02 improper J (reflection ⟂ (1,0,1)) preserves ball3, J e_z = -e_x ∉ {±e_z}, Lie dim 3",
      Jr * Jr.T == sp.eye(3) and Jr.det() == -1 and Jr * ez == -ex and lie_dim([Lz, Jr * Lz * Jr.T]) == 3)
note("2.N1 Written: an affine bijection f of R^3 with f(ball3) ⊆ ball3 and f^-1(ball3) ⊆ ball3 maps the ball onto "
     "itself, fixes its unique centre of symmetry 0, and its linear part A and A^-1 are norm-contractions, so A ∈ O(3). "
     "D2+D3+D6: t ↦ flow t is a nontrivial continuous homomorphism R → SO(3) (flow t = (flow t/2)^2 has det +1), "
     "image = full circle {R_a(ωt)}. D9 with D7/D8: J ∈ O(3); if J a = ±a then J R_a(θ) J^-1 = R_a(±θ) is a flow member, "
     "so D9 forces J a ∉ {±a}.")
note("2.N2 Written (cap argument, no Lie theory): G ⊇ circles about a and b = Ja, γ = ∠(a,b) ∈ (0, π/2] after b ↦ −b. "
     "As β runs over [0, π], ∠(a, R_b(β)a) runs continuously over [0, 2γ]; R_a(α) is transitive on each circle of fixed "
     "angle about a; so G·a ⊇ cap(a, 2γ). G acts by isometries, so g·cap(a,2γ) = cap(ga,2γ): G·a is a union of closed caps "
     "of radius 2γ about its own points, hence open, and closed (a limit v of points u ∈ G·a lies in cap(u,2γ) for u close "
     "to v). S² connected ⇒ G·a = S². The stabilizer of a in SO(3) is R_a(R) ⊆ G, so G ⊇ SO(3). Citation-level "
     "alternative: Lowenthal, Rocky Mountain J. Math. 1 (1971) 575–586 (finite generation of SO(3) by two circle subgroups).")
note("2.N3 D3 is load-bearing (countermodel, written, uses a Hamel basis): choose an additive φ: R → R with φ(1) = π and "
     "φ(R) = Qπ (Hamel basis B ∋ 1, φ(1) = π, φ(b) = 0 for b ≠ 1). flow t := Rz(φ(t)), t0 := 1, J := cyc3. D1, D2 "
     "(φ additive), D4, D5 (Rz(π)^2 = 1), D6, D7, D8 and D9 (witness of 1.06 at t = 1) hold; only D3 fails. The generated "
     "group is countable, so the orbit of e_z is countable and not S^2.")

print("\n=== §3  abstract drivable bodies: transitivity that does not follow")


def R2(a):
    return sp.Matrix([[sp.cos(a), -sp.sin(a)], [sp.sin(a), sp.cos(a)]])


Z2 = sp.zeros(2, 2)
# bidisk D×D ⊂ R^4
F = lambda a: sp.diag(R2(a), sp.eye(2))
Jb = sp.Matrix(sp.BlockMatrix([[Z2, sp.eye(2)], [sp.eye(2), Z2]]))
x1, x2, y1, y2 = sp.symbols('x1 x2 y1 y2', real=True)
v = sp.Matrix([x1, x2, y1, y2])


def inv_pair(w):
    return sp.expand(w[0] ** 2 + w[1] ** 2), sp.expand(w[2] ** 2 + w[3] ** 2)


p0 = inv_pair(v)
pf = inv_pair(F(t) * v)
pj = inv_pair(Jb * v)
check("3.01 bidisk drive: F(t) = R(t)⊕I preserves (|x|²,|y|²); J = block swap exchanges them",
      sp.simplify(pf[0] - p0[0]) == 0 and pf[1] == p0[1] and pj == (p0[1], p0[0]))
check("3.02 bidisk: F group law, N = F(pi) involutive, moves (e1,0)",
      zero(F(s) * F(t) - F(s + t)) and F(pi) * F(pi) == sp.eye(4) and F(pi) * sp.Matrix([1, 0, 0, 0]) != sp.Matrix([1, 0, 0, 0]))
w = sp.Matrix([0, 0, 1, 0])
check("3.03 bidisk D9: J F(pi) J^-1 (0,e1) = (0,-e1) while F(s)(0,e1) = (0,e1) for all s",
      Jb * F(pi) * Jb.T * w == -w and zero(F(s) * w - w))
eps = sp.symbols('epsilon', positive=True)
P, Q = sp.Matrix([1, 0, 1, 0]), sp.Matrix([1, 0, 0, 0])
extP = P + eps * (P - (-P))
extQ = Q + eps * (Q - (-Q))
check("3.04 (e1,e1) and (e1,0) are boundary states (KF:130 witness y = −x: first block norm² (1+2ε)² > 1 ∀ε>0)",
      sp.simplify(inv_pair(extP)[0] - (1 + 2 * eps) ** 2) == 0 and sp.simplify(inv_pair(extQ)[0] - (1 + 2 * eps) ** 2) == 0)
check("3.05 G_D-invariant unordered pair {|x|²,|y|²}: {1,1} at (e1,e1) vs {1,0} at (e1,0) — not one G_D-orbit",
      sorted(inv_pair(P)) != sorted(inv_pair(Q)))
check("3.06 midpoint identity (e1,0) = ((e1,e1)+(e1,-e1))/2, so (e1,0) is not extreme [(e1,e1) is extreme: written, "
      "product of extreme points]; affine automorphisms preserve extremality",
      (sp.Matrix([1, 0, 1, 0]) + sp.Matrix([1, 0, -1, 0])) / 2 == Q)
note("3.N1 Bidisk: drivable (3.01–3.03; D3 by continuity of cos, sin), compact, convex, boundary states (e1,e1), (e1,0) in "
     "different orbits of Aut(Ω) ⊇ G_D. G_D ⊇ SO(2)×SO(2) is transitive on ext Ω = S¹×S¹ but not on the boundary.")
# cone over B^3 in R^4: Ω = {(x,h): 0 ≤ h ≤ 1, |x| ≤ 1 − h}
Fc = lambda a: sp.diag(Rz(a), 1)
Jc = sp.diag(C, 1)
apex = sp.Matrix([0, 0, 0, 1])
base = sp.Matrix([1, 0, 0, 0])
h = sp.symbols('h', real=True)
z1, z2, z3 = sp.symbols('z1 z2 z3', real=True)
u = sp.Matrix([z1, z2, z3, h])
nrm = lambda w: sp.expand(w[0] ** 2 + w[1] ** 2 + w[2] ** 2)
check("3.07 cone over B³: Rz(t)⊕1 and cyc3⊕1 preserve |x|² and h (so preserve Ω = {0≤h≤1, |x|≤1−h})",
      sp.simplify(nrm(Fc(t) * u) - nrm(u)) == 0 and (Fc(t) * u)[3] == h and nrm(Jc * u) == nrm(u) and (Jc * u)[3] == h)
check("3.08 cone: D9 witness transported (cyc3⊕1)(Rz(pi)⊕1)(cyc3⊕1)^-1 maps (0,0,1,0) to (0,0,-1,0)",
      Jc * Fc(pi) * Jc.T * sp.Matrix([0, 0, 1, 0]) == sp.Matrix([0, 0, -1, 0]))
check("3.09 cone: every generator fixes the apex, so the G_D-orbit of the apex is {apex} while (e1,0) is moved",
      Fc(t) * apex == apex and Jc * apex == apex and Fc(pi) * base != base)
check("3.10 cone: the apex is isolated in ext Ω = S²×{0} ∪ {apex} (squared distance to S²×{0} is exactly 2)",
      sp.simplify(nrm(sp.Matrix([sp.cos(ph) * sp.sin(th), sp.sin(ph) * sp.sin(th), sp.cos(th)]) ) + 1) == 2)
note("3.N2 Cone: affine automorphisms are homeomorphisms of Ω preserving ext Ω, hence its isolated points; the apex is the "
     "only isolated extreme point, so Aut(Ω) fixes it. Drivable compact convex body on which even Aut(Ω) is not transitive "
     "on extreme points.")
# B^4 with SO(3)⊕1 drive
check("3.11 B⁴ with flow Rz(t)⊕1, J = cyc3⊕1: x4 is G_D-invariant, so e4 and e1 (both on S³) are in different G_D-orbits",
      (Fc(t) * sp.Matrix([z1, z2, z3, h]))[3] == h and (Jc * sp.Matrix([z1, z2, z3, h]))[3] == h)
note("3.N3 B⁴: Ω is a ball and drivable, but G_D (≅ SO(3)) is not transitive on its boundary S³. Drivability does not give "
     "boundary transitivity of the drive group even when the body is a ball (dim ≥ 4).")
# planar exclusion re-check (Thread F B6)
c_, s_ = sp.symbols('c s', real=True)
Ref = sp.Matrix([[c_, s_], [s_, -c_]])
check("3.12 planar control: a reflection conjugates R(t) to R(-t) (given c²+s²=1); a rotation commutes with R(t)",
      ((Ref * R2(t) * Ref.T) - R2(-t)).applyfunc(lambda e: sp.simplify(sp.expand(e).subs(s_**2, 1 - c_**2))) == sp.zeros(2, 2)
      and zero(R2(ph) * R2(t) * R2(-ph) - R2(t)))
note("3.N4 What does follow from the fields alone (written): (i) G_D|Ω is non-abelian (D9 says J flow(t) J^-1 ≠ flow(t) on Ω); "
     "(ii) for compact Ω in finite dimension, the flow moves some extreme point (an affine map fixing ext Ω fixes Ω), and by "
     "D3 its flow orbit is a non-constant continuous curve in ext Ω, so ext Ω is uncountable; (iii) the closure of G_D|Ω "
     "is a compact group, orthogonal for an averaged inner product about the centroid. Nothing more about orbits follows: "
     "3.05 (boundary), 3.09 (extreme points), 3.11 (ball, dim 4).")

print("\n=== §4  sourcing: what the landed matrix objects generate on the qubit Bloch ball (imported C)")
X = sp.Matrix([[0, 1], [1, 0]])
Y = sp.Matrix([[0, -sp.I], [sp.I, 0]])
Zp = sp.Matrix([[1, 0], [0, -1]])
paulis = [X, Y, Zp]


def bloch(U):
    Ud = U.H
    return sp.Matrix(3, 3, lambda i, j: sp.simplify(sp.expand((paulis[i] * U * paulis[j] * Ud).trace() / 2)))


def cs(M):
    return M.applyfunc(lambda e: sp.simplify(sp.expand_complex(sp.expand(e.rewrite(sp.cos)))))


a1, a2 = sp.symbols('a1 a2', real=True)
Dph = sp.diag(sp.exp(sp.I * a1), sp.exp(sp.I * a2))  # phaseOperator d, |d| = 1 (SI:83)
BD = cs(bloch(Dph))
check("4.01 diagonal phase diag(e^{ia1}, e^{ia2}) acts on the Bloch ball as Rz(a2 - a1): fixes e_z",
      zero(BD - Rz(a2 - a1)))
BX = cs(bloch(X))
check("4.02 permMatrix swap acts as diag(1,-1,-1) = Rx(pi): sends e_z to -e_z", BX == sp.diag(1, -1, -1))
BXD = cs(bloch(X * Dph))
check("4.03 every monomial unitary perm·diag on Fin 2 sends e_z to ±e_z (both families, symbolic phases)",
      zero(BD * ez - ez) and zero(BXD * ez + ez))
note("4.N1 Hence the monomial (substratum, SC:180) unitary group of Fin 2 acts on S² through O(2)_z = rotations "
     "preserving the line Re_z: the orbit of a pole is {±e_z}; not transitive. A continuous flow inside it is diagonal "
     "(identity component), i.e. Rz; a monomial J then sends e_z to ±e_z, so D9 fails. Group-level form of "
     "substratum_residual (SC:383) on the Bloch ball; matches Thread G key result 5.")
S0 = sp.diag(sp.I, 1)  # phaseGate 0 on Fin 2 (LRS:209)
BS = cs(bloch(S0))
check("4.04 phaseGate 0 = diag(i,1) acts as Rz(-pi/2) (a monomial, supplied by phaseOperator_supplied SC:333)",
      zero(BS - Rz(-pi / 2)))


def unit(g, tt):  # SOC:356
    return sp.eye(2) + (sp.exp(pi * sp.I * tt) - 1) * (sp.eye(2) - g) / 2


GF = unit(X, t)  # gateFlow (permMat swap) t, LA:47
BG = cs(bloch(GF))
check("4.05 gateFlow(swap, t) acts on the Bloch ball as Rx(pi·t) for symbolic t", zero(BG - Rx(pi * t)))
check("4.06 gateFlow(swap, 1) = permMat swap (LA:84 restated) and gateFlow(1/2) has two nonzero entries per column",
      cs(unit(X, 1)) == X and all(sp.simplify(e) != 0 for e in cs(unit(X, sp.Rational(1, 2)))))
flowX = sp.cos(t) * sp.eye(2) - sp.I * sp.sin(t) * X  # e^{-itX} (RS:95 with H = transition 0 1)
check("4.07 e^{-itX} = e^{-it}·gateFlow(swap, 2t/pi): transition flow = gate flow up to a global (monomial) phase",
      zero(cs(sp.exp(-sp.I * t) * unit(X, 2 * t / pi) - flowX)))
check("4.08 with J = phaseGate 0: J·Rx(pi t)·J^-1 = Ry(-pi t) — the off-axis clause D9 holds (axis e_x ↦ -e_y)",
      zero(BS * Rx(pi * t) * BS.T - Ry(-pi * t)) and BS * ex == -ey)
check("4.09 Bloch drive (flow Rx(pi t), t0 = 1 so N = Rx(pi) = image of the swap, J = image of phaseGate 0): "
      "N involutive and moves e_z; Lie<Lx, J Lx J^-1> has dim 3",
      BX * BX == sp.eye(3) and BX * ez == -ez and lie_dim([C * Lz * C.T, BS * (C * Lz * C.T) * BS.T]) == 3)
note("4.N2 So ⟨gateFlow(swap, R), monomial unitaries of Fin 2⟩ acts on the Bloch sphere as SO(3) (Rx(R) and its "
     "J-conjugate Ry(R) generate SO(3) by §1's Euler argument with the axes relabelled) and is transitive on it. "
     "The only generator outside the substratum class is the gate flow at non-integer times (4.06; LA:138). "
     "Matrix-level kernel counterpart: exactReachability_of_hcontrol (OR:625) applied to transition_hermitian "
     "(LRS:211), ctrl_unitary (LRS:293), hControl_star (LRS:352) gives ExactReachability (transition i₀ j₁) (ctrl i₀): "
     "every unitary is a finite word — a one-line composition, not a landed identifier.")
# real one-parameter groups cannot pass through an odd permutation
check("4.10 det(permMat swap) = -1 [written: det A(1) = det(A(1/2))² > 0 for any real one-parameter group A, D2 only]",
      X.det() == -1)
for n in (1, 2, 3):
    moved = 4 ** n - 2 ** n  # binary alphabet: configurations (p,c)^n moved by the region swap
    print(f"      region swap, |V| = 2, {n} site(s): transpositions = {moved // 2}, parity = {'odd' if (moved // 2) % 2 else 'even'}")
check("4.11 single-site binary swap layer is odd (no real-linear flow through it); regions of 2, 3 sites are even",
      ((4 - 2) // 2) % 2 == 1 and ((16 - 4) // 2) % 2 == 0 and ((64 - 8) // 2) % 2 == 0)
note("4.N3 The CT2 interpolation unit g t (SOC:356) uses e^{iπt}; on the real permutation representation the single-site "
     "binary swap gate lies on no one-parameter group (4.10–4.11, continuity-free). The branch is a choice: unit' g t = "
     "1 + (e^{iπ(2k+1)t} − 1)(1−g)/2 also reaches g at t = 1 for every integer k (4.12).")
check("4.12 every odd branch e^{iπ(2k+1)t} reaches the gate at t = 1 (k = 0, 1, -1, 2 exact)",
      all(sp.simplify(sp.exp(sp.I * pi * (2 * kk + 1))) == -1 for kk in (0, 1, -1, 2)))

note("4.N4 Region level: swapQ (SwapLayer:372) with swapQ_add_time (SwapLayer:494) is the landed strongly continuous "
     "one-parameter group of the swap layer, built from the same unit g t; on the two configurations (0,1), (1,0) of one "
     "binary site exchanged by the swap gate it acts as 4.05. The read-write family (ReadWriteControl:87, couple : R → Perm S) "
     "is a family of permutations: a continuous map from R to a finite discrete group is constant, so it carries no "
     "nontrivial continuous flow (D3 + D6 fail), whatever its parameter law.")

print("\n=== §5  qutrit control: boundary transitivity is a rank-2 property even in the imported kinematics")
r1 = sp.diag(1, 0, 0)
r2 = sp.diag(sp.Rational(1, 2), sp.Rational(1, 2), 0)
check("5.01 diag(1,0,0) and diag(1/2,1/2,0) are singular (boundary) qutrit states with different spectra",
      r1.det() == 0 and r2.det() == 0 and r1.eigenvals() != r2.eigenvals())
note("5.N1 Written: the minimal face of the qutrit body containing diag(1/2,1/2,0) is a 3-dimensional Bloch ball, that "
     "of diag(1,0,0) is a point; affine automorphisms preserve minimal-face dimension. So no affine automorphism of the "
     "d = 3 quantum body is transitive on its boundary; boundary transitivity can only be asked of the two-level body.")

print(f"\nOK -- {CHECKS} checks, {NOTES} written notes")
