# y3_s3_axes.py -- thread Y (stage 4, Q-EX): node S3 and its record refinement by axis; S5; combinations.
#
# DECISION RULE (fixed before the first run; rules, not expected numbers):
#  * For each (token, axis n) in the fixed list below, the real Lie algebra generated by i n.s on that token
#    and its conjugates is computed exactly (rank over Q, iterated commutators until closed):
#      level (i):  conjugates by CNOT only;
#      level (ii): conjugates by the generators of G16 = <cnot, Ad(Z(x)I), Ad(I(x)Z), T>, T acting on a
#                  generator A as A -> conj(A), iterated together with commutators until closed.
#  * A node is labelled REACHABLE iff the closure contains i s_k (x) P (k = 1,2,3) for one block projector P
#    (P+ or P- of the target X-basis for control-side nodes; P0 or P1 of the control Z-basis for target-side
#    nodes); NOT-REACHABLE-ABELIAN iff the closure is abelian (all commutators zero). Anything else prints
#    OTHER (no label). The written argument (RESULT Y3) supplies what the labels mean.
#  * Countercontrols, for every REACHABLE node: among the five fixed rotation angles about n
#    ((cos,sin)(theta/2) in {(3/5,4/5),(4/5,3/5),(5/13,12/13),(12/13,5/13),(0,1)}), some member g of the
#    one-parameter group carries E0 out of K(E0) and some member carries a defect of Z_F out of K(Z_F),
#    each certified by an exact negative pairing with an exact member of the cone. Q3 retention for
#    these maps is automatic (unitary conjugation) and is checked on one instance.
#  * Each line prints PASS/FAIL. "VERDICT Y3-AXES-EXACT" iff every line passes (labels are reported, not
#    judged); otherwise "VERDICT Y3-AXES-FAILED" and the failing ids.
import sympy as sp

I = sp.I
S = [sp.Matrix([[1, 0], [0, 1]]), sp.Matrix([[0, 1], [1, 0]]),
     sp.Matrix([[0, -I], [I, 0]]), sp.Matrix([[1, 0], [0, -1]])]
E2 = S[0]


def kron(A, B):
    return sp.Matrix(4, 4, lambda r, c: A[r // 2, c // 2] * B[r % 2, c % 2])


SS = [[kron(S[m], S[n]) for n in range(4)] for m in range(4)]
pauliW = lambda w: sum((w[m][n] * SS[m][n] for m in range(4) for n in range(4)), sp.zeros(4, 4)) / 4
table = lambda R: [[sp.expand((R * SS[m][n]).trace()) for n in range(4)] for m in range(4)]
ipW = lambda a, b: sp.expand(sum(a[m][n] * b[m][n] for m in range(4) for n in range(4)))
CNOT = sp.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
ZI, IZ = kron(S[3], E2), kron(E2, S[3])
Pp, Pm, P0, P1 = (E2 + S[1]) / 2, (E2 - S[1]) / 2, (E2 + S[3]) / 2, (E2 - S[3]) / 2
fails = []


def report(cid, ok, text):
    print(("PASS " if ok else "FAIL ") + cid + " " + text)
    if not ok:
        fails.append(cid)


def vec(A):
    out = []
    for m in range(4):
        for n in range(4):
            x = sp.expand((SS[m][n] * A).trace() / (4 * I))
            assert sp.im(x) == 0
            out.append(sp.re(x))
    return out


def closure(gens, level2):
    B, V = [], []
    def add(A):
        v = vec(A)
        if sp.Matrix(V + [v]).rank() > len(V):
            V.append(v); B.append(A); return True
        return False
    for g in gens:
        add(g)
    grown = True
    while grown:
        grown = False
        k = len(B)
        for i in range(k):
            imgs = [CNOT * B[i] * CNOT]
            if level2:
                imgs += [ZI * B[i] * ZI, IZ * B[i] * IZ, B[i].conjugate()]
            for A in imgs:
                grown = add(A) or grown
        for i in range(len(B)):
            for j in range(i + 1, len(B)):
                grown = add(B[i] * B[j] - B[j] * B[i]) or grown
    return B, V


def contains(V, mats):
    return sp.Matrix(V + [vec(A) for A in mats]).rank() == sp.Matrix(V).rank()


def label(B, V, side):
    blocks = [(Pp, Pm), (P0, P1)][side == 'T']
    for P in blocks:
        mats = [I * (kron(S[k], P) if side == 'C' else kron(P, S[k])) for k in (1, 2, 3)]
        if contains(V, mats):
            return 'REACHABLE'
    if all(all(x == 0 for x in (B[i] * B[j] - B[j] * B[i])) for i in range(len(B)) for j in range(len(B))):
        return 'NOT-REACHABLE-ABELIAN'
    return 'OTHER'


def ns(n):
    return n[0] * S[1] + n[1] * S[2] + n[2] * S[3]


R_ = sp.Rational
AXES = {'x': (1, 0, 0), 'y': (0, 1, 0), 'z': (0, 0, 1), '(3,4,0)/5': (R_(3, 5), R_(4, 5), 0),
        '(0,3,4)/5': (0, R_(3, 5), R_(4, 5)), '(3,0,4)/5': (R_(3, 5), 0, R_(4, 5)),
        '(1,2,2)/3': (R_(1, 3), R_(2, 3), R_(2, 3)), '(2,1,2)/3': (R_(2, 3), R_(1, 3), R_(2, 3)),
        '(2,2,1)/3': (R_(2, 3), R_(2, 3), R_(1, 3))}
ANG = [(R_(3, 5), R_(4, 5)), (R_(4, 5), R_(3, 5)), (R_(5, 13), R_(12, 13)), (R_(12, 13), R_(5, 13)), (0, 1)]
E0 = [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, -1, 0], [0, 0, 0, 0]]
ZF = [[[R_(1, 4), 0, 0, 0], [0, 0, 0, R_(s1, 4)], [0, 0, R_(s2, 4), 0], [0, -R_(s1 * s2, 4), 0, 0]]
      for s1 in (1, -1) for s2 in (1, -1)]
gE0 = sp.Matrix([1, -1, -1, -1]) / 2                          # negative eigenvector of pauliW(E0)
assert pauliW(E0) * gE0 == -gE0 / 4
capF = [[vv for (val, mu, vs) in pauliW(z).eigenvects() if val < 0 for vv in vs][0] for z in ZF]


def exits(G):
    """exact certificates that Ad(G) moves E0 out of K(E0) and some z in Z_F out of K(Z_F)."""
    tE0 = table(G * pauliW(E0) * G.H)
    okE = ipW(tE0, E0) < 0
    if not okE:
        P = table(G * gE0 * gE0.H * G.H)                     # <g E0, P> = -1; P in K(E0) iff <P, E0> >= 0
        okE = ipW(P, E0) >= 0 and ipW(tE0, P) < 0
    okZ = False
    for z, f in zip(ZF, capF):
        gf = G * f
        P = table(gf * gf.H / sp.expand((f.H * f)[0]))
        if all(ipW(P, zz) >= 0 for zz in ZF) and ipW(table(G * pauliW(z) * G.H), P) < 0:
            okZ = True
    return okE, okZ


for side in ('C', 'T'):
    for name, n in AXES.items():
        gen = I * (kron(ns(n), E2) if side == 'C' else kron(E2, ns(n)))
        res = []
        for lev in (False, True):
            B, V = closure([gen], lev)
            res.append((len(V), label(B, V, side)))
        cid = "A-%s-%s" % (side, name)
        line = "level(i): dim %d %s; level(ii): dim %d %s" % (res[0] + res[1])
        ok = True
        if res[1][1] == 'REACHABLE':
            found = None
            for (cc, ss) in ANG:
                U = cc * E2 - I * ss * ns(n)
                G = kron(U, E2) if side == 'C' else kron(E2, U)
                okE, okZ = exits(G)
                if okE and okZ:
                    found = (cc, ss); break
            ok = found is not None
            line += "; exits K(E0), K(Z_F) at (cos,sin)(theta/2) = %s" % (found,)
        report(cid, ok and res[0][1] != 'OTHER' and res[1][1] != 'OTHER', line)

COMBOS = {'drive-both (X(x)I, I(x)X)': [I * kron(S[1], E2), I * kron(E2, S[1])],
          'S2 torus (Z(x)I, I(x)X)': [I * kron(S[3], E2), I * kron(E2, S[1])],
          'S5 (su(2)(x)I + I(x)su(2))': [I * kron(S[k], E2) for k in (1, 2, 3)] + [I * kron(E2, S[k]) for k in (1, 2, 3)]}
for name, gens in COMBOS.items():
    B, V = closure(gens, True)
    labC = label(B, V, 'C'); labT = label(B, V, 'T')
    lab = 'REACHABLE' if 'REACHABLE' in (labC, labT) else labC
    report("B-" + name.split()[0], lab != 'OTHER', "%s: level(ii) dim %d %s" % (name, len(V), lab))
U = R_(3, 5) * E2 - I * R_(4, 5) * ns(AXES['(1,2,2)/3'])
psi = sp.Matrix([1, 2, 3 * I, -1 + I]); G = kron(U, E2)
report("Q1", all(ev >= 0 for ev in (G * psi * psi.H * G.H).eigenvals().keys()),
       "retention instance: Ad(U(x)I), U about (1,2,2)/3, maps a pure state to a PSD table")
if fails:
    print("VERDICT Y3-AXES-FAILED " + " ".join(fails))
else:
    print("VERDICT Y3-AXES-EXACT")
