"""Exact flats of T^3 for the A39 Dita-locus measurement.

A character equation is u^k = c with k in Z^3 and c in G = <i, z, w>, written additively as (p mod 4, q, r); z and w are
multiplicatively independent modulo roots of unity, so G = Z/4 x Z^2 faithfully inside the circle. The solution set of a
finite system {u^{k_i} = c_i} is empty or a flat F = (L, chi): L the sublattice of Z^3 generated by the k_i and chi: L -> G
the homomorphism with chi(k_i) = c_i. F = {u : u^l = chi(l) for all l in L}; it is nonempty whenever chi is well defined,
since the circle is divisible. A character (k, c) is identically satisfied on F iff k in L and chi(k) = c (the annihilator of
the subgroup cut out by L is L itself). F has dimension 3 - rank L and [sat(L) : L] connected components.

Representation: rows (k | v) in Hermite normal form (row style, positive pivots, entries above pivots reduced), v the value of
chi on the row. Two flats are equal iff their canonical forms are equal."""
from math import gcd

def vadd(a, b): return ((a[0] + b[0]) % 4, a[1] + b[1], a[2] + b[2])
def vsub(a, b): return ((a[0] - b[0]) % 4, a[1] - b[1], a[2] - b[2])
def vmul(n, a): return ((n * a[0]) % 4, n * a[1], n * a[2])
V0 = (0, 0, 0)

class Empty(Exception):
    pass

def _hnf(rows):
    """rows: list of (k tuple of 3 ints, v). Returns the canonical HNF basis as a tuple of (k, v); raises Empty if the system
    is inconsistent (a zero-k row with a nonzero value)."""
    R = [[list(k), v] for k, v in rows]
    basis = []
    for col in range(3):
        while True:
            idx = [t for t in range(len(R)) if R[t][0][col] != 0]
            if len(idx) <= 1: break
            idx.sort(key=lambda t: abs(R[t][0][col]))
            pk, pv = R[idx[0]]
            for t in idx[1:]:
                f = R[t][0][col] // pk[col]
                R[t] = [[a - f * b for a, b in zip(R[t][0], pk)], vsub(R[t][1], vmul(f, pv))]
        idx = [t for t in range(len(R)) if R[t][0][col] != 0]
        if idx:
            k, v = R.pop(idx[0])
            if k[col] < 0: k = [-a for a in k]; v = vmul(-1, v)
            basis.append([k, v])
    for k, v in R:
        if any(k): raise AssertionError('reduction incomplete')
        if v != V0: raise Empty()
    piv_cols = [next(c for c in range(3) if k[c] != 0) for k, v in basis]
    for a in range(len(basis)):
        pc = piv_cols[a]; h = basis[a][0][pc]
        for b in range(a):
            f = basis[b][0][pc] // h
            if f:
                basis[b] = [[x - f * y for x, y in zip(basis[b][0], basis[a][0])], vsub(basis[b][1], vmul(f, basis[a][1]))]
    return tuple((tuple(k), v) for k, v in basis)

class Flat:
    __slots__ = ('B',)
    def __init__(self, rows=()):
        self.B = _hnf(list(rows))
    @staticmethod
    def of(B):
        f = Flat.__new__(Flat); f.B = B; return f
    def key(self): return self.B
    def __eq__(self, o): return self.B == o.B
    def __hash__(self): return hash(self.B)
    def rank(self): return len(self.B)
    def dim(self): return 3 - len(self.B)
    def meet(self, other):
        """intersection; raises Empty"""
        return Flat.of(_hnf(list(self.B) + list(other.B)))
    def add(self, k, v):
        return Flat.of(_hnf(list(self.B) + [(tuple(k), v)]))
    def reduce(self, k, v):
        """canonical representative of the character (k, v) modulo the flat: characters equal on F have equal reductions"""
        k = list(k)
        for bk, bv in self.B:
            pc = next(c for c in range(3) if bk[c] != 0)
            f = k[pc] // bk[pc]
            if f:
                k = [a - f * b for a, b in zip(k, bk)]; v = vsub(v, vmul(f, bv))
        return (tuple(k), v)
    def holds(self, k, v):
        """is u^k = v identically on F"""
        rk, rv = self.reduce(k, v)
        return not any(rk) and rv == V0
    def contains(self, other):
        """F_self contains F_other: every equation of self holds on other"""
        return all(other.holds(k, v) for k, v in self.B)
    def components(self):
        """[sat(L) : L]: the product of the elementary divisors (gcd of maximal minors of the basis)"""
        r = len(self.B)
        if r == 0: return 1
        import itertools
        M = [list(k) for k, v in self.B]
        g = 0
        for cols in itertools.combinations(range(3), r):
            sub = [[row[c] for c in cols] for row in M]
            d = _det(sub)
            g = gcd(g, abs(d))
        return g
    def describe(self):
        return 'dim %d, %d component(s), equations %s' % (self.dim(), self.components(), ['u^%s = %s' % (k, _show(v)) for k, v in self.B])

def _det(M):
    n = len(M)
    if n == 1: return M[0][0]
    if n == 2: return M[0][0] * M[1][1] - M[0][1] * M[1][0]
    return sum((-1) ** c * M[0][c] * _det([row[:c] + row[c + 1:] for row in M[1:]]) for c in range(n))

def _show(v):
    p, q, r = v
    parts = []
    if p: parts.append('i^%d' % p)
    if q: parts.append('z^%d' % q)
    if r: parts.append('w^%d' % r)
    return ' '.join(parts) or '1'

TORUS = Flat()

def self_test():
    import itertools
    # u1 = 1 and u1^2 = 1: consistent, one-dimensional gcd; u1^2 = -1 and u1^2 = 1: empty
    f = Flat([((1, 0, 0), V0)]); assert f.dim() == 2 and f.components() == 1
    g = Flat([((2, 0, 0), V0)]); assert g.components() == 2 and g.contains(f) and not f.contains(g)
    try: Flat([((2, 0, 0), V0), ((2, 0, 0), (2, 0, 0))]); raise AssertionError
    except Empty: pass
    # u^2 = z, u^4 = z^2 consistent; u^4 = z^3 not
    Flat([((2, 0, 0), (0, 1, 0)), ((4, 0, 0), (0, 2, 0))])
    try: Flat([((2, 0, 0), (0, 1, 0)), ((4, 0, 0), (0, 3, 0))]); raise AssertionError
    except Empty: pass
    # canonical: generators given in different orders and combinations give the same flat
    a = Flat([((1, 1, 0), (1, 0, 0)), ((0, 1, -1), (0, 0, 1))])
    b = Flat([((1, 0, 1), (1, 0, -1)), ((1, 1, 0), (1, 0, 0))])
    assert a == b, (a.B, b.B)
    assert a != Flat([((1, 0, 1), (1, 0, 1)), ((1, 1, 0), (1, 0, 0))])
    # holds / reduce: u1 u3 = (u1 u2) / (u2 / u3) = i w^-1
    assert a.holds((1, 0, 1), (1, 0, -1)) and not a.holds((1, 0, 1), (1, 0, 1)) and not a.holds((1, 0, 0), V0)
    # a point: u = (i, z, w)
    p = Flat([((1, 0, 0), (1, 0, 0)), ((0, 1, 0), (0, 1, 0)), ((0, 0, 1), (0, 0, 1))])
    assert p.dim() == 0 and p.components() == 1 and p.holds((1, 1, 1), (1, 1, 1)) and p.holds((4, 0, 0), V0)
    assert a.contains(p) is False or True
    # meet associativity on random small systems
    import random
    random.seed(3)
    for _ in range(300):
        eqs = [(tuple(random.randint(-2, 2) for _ in range(3)), (random.randint(0, 3), random.randint(-2, 2), random.randint(-2, 2))) for _ in range(random.randint(1, 4))]
        try:
            F = Flat(eqs)
        except Empty:
            continue
        for k, v in eqs: assert F.holds(k, v)
        G = TORUS
        for k, v in eqs: G = G.add(k, v)
        assert G == F
    return 'flats: self-test OK'

if __name__ == '__main__':
    print(self_test())
