"""Controls C1-C3 (object-level part), C7 (group closure), C8 (generators permute the relaxed subspaces).
Exact integer / Gaussian-rational arithmetic throughout. Writes ctrl_objects.json."""
import json, random, sympy
from lib41 import *
res = {}; bad = []
def chk(name, got, want):
    ok = got == want; print('  %s  %-60s %s' % ('PASS' if ok else 'FAIL', name, got if ok else '%s (expected %s)' % (got, want)))
    res[name] = {'ok': ok, 'got': str(got)}
    if not ok: bad.append(name)
M = lambda f: [[f(i, j) for j in range(16)] for i in range(16)]
A, B, C = M(EA), M(EB), M(EC)
add = lambda *Xs: [[sum(X[i][j] for X in Xs) for j in range(16)] for i in range(16)]
objs = {'A': A, 'B': B, 'C': C, 'A+B': add(A, B), 'A+C': add(A, C), 'B+C': add(B, C), 'A+B+C': add(A, B, C), 'zero': M(lambda i, j: 0)}
chk('A+B+C equals the landed EE', objs['A+B+C'], EE)
want = {'A': {('k2', 'row'), ('k4', 'row'), ('e2', 'row'), ('t1', 'column'), ('t1', 'row'), ('t2', 'row'), ('t3', 'row')},
        'B': {('k1', 'row'), ('k4', 'column'), ('t1', 'row'), ('t2', 'column')},
        'C': {('k2', 'column'), ('t1', 'column'), ('t2', 'column'), ('t3', 'column'), ('t3', 'row')},
        'A+B': {('t1', 'row')}, 'A+C': {('t1', 'column'), ('t3', 'row')}, 'B+C': {('t2', 'column')}, 'A+B+C': set(),
        'zero': set((nm, f) for nm, f, s, tr in STRUCTS18)}
for k, E in objs.items():
    chk('%s in the domain ({0,1}, row 0 = 0)' % k, all(x in (0, 1) for r in E for x in r) and not any(E[0]), True)
    chk('%s straight line (direct exact Laurent identity)' % k, straight_line_direct(E), True)
    chk('%s strict memberships (discovery-note table)' % k, set(members(E, False)), want[k])
    chk('%s relaxed memberships = strict (discovery-note table)' % k, set(members(E, True)), want[k])
chk('support of A+B+C', sum(map(sum, EE)), 48)
imgs = images_gn(EE); distinct = len(set(map(bytes, imgs.astype(np.int8))))
chk('A+B+C: distinct gauge-normal images under the 2048 elements', distinct, 512)
chk('A+B+C: minimum gauge-normal support over the orbit', int((imgs != 0).sum(axis=1).min()), 48)
# gauge-trivial matrix: relaxed in all 18, strict in none
Gt = [[(i % 3) + (j % 5) for j in range(16)] for i in range(16)]
chk('gauge-trivial matrix: relaxed members', len(members(Gt, True)), 18)
chk('gauge-trivial matrix: strict members', len(members(Gt, False)), 0)
# ---- C7: the 2048 elements form a group -----------------------------------------------------------------------
P = PERM_ARR; S = SIGN_ARR
elem_index = {(bytes(P[g].astype(np.uint16)), int(S[g])): g for g in range(len(P))}
chk('2048 distinct elements', len(elem_index), 2048)
def compose(g, h):   # (g o h).E = g.(h.E): perm = P[g][P[h]], sign = S[g] S[h]
    return (bytes(P[g][P[h]].astype(np.uint16)), int(S[g] * S[h]))
random.seed(41)
gens = []; group = {elem_index[(bytes(np.arange(256, dtype=np.uint16)), 1)]} if (bytes(np.arange(256, dtype=np.uint16)), 1) in elem_index else None
chk('identity in the set', group is not None, True)
while True:
    # BFS closure of the current generator set
    seen = set(group); frontier = list(seen)
    while frontier:
        nf = []
        for x in frontier:
            for g in gens:
                y = compose(g, x)
                if y not in elem_index: chk('closure: product outside the set', True, False); raise SystemExit(1)
                yi = elem_index[y]
                if yi not in seen: seen.add(yi); nf.append(yi)
        frontier = nf
    if len(seen) == 2048: break
    gens.append(random.choice([g for g in range(2048) if g not in seen]))
chk('group generated by %d elements has order' % len(gens), len(seen), 2048)
# ---- C8: each generator maps every relaxed subspace L_S onto some L_S' (equal dimensions + inclusion) ----------
def nullspace_int(eqs):
    Mx = sympy.Matrix(eqs); out = []
    for v in Mx.nullspace():
        den = 1
        for x in v: den = sympy.ilcm(den, sympy.Rational(x).q)
        out.append([int(x * den) for x in v])
    return np.array(out, dtype=np.int64)
EQA = {k: np.array(v, dtype=np.int64) for k, v in EQS.items()}
NUL = {}
for nm, form, s, tr in STRUCTS18:
    NUL[(nm, form)] = nullspace_int(EQS[(nm, form, True)])
dims = {k: len(v) for k, v in NUL.items()}
print('  relaxed subspace dimensions', dims)
perm_ok = True
for g in gens + [int(x) for x in random.sample(range(2048), 6)]:
    for k, basis in NUL.items():
        img = np.zeros_like(basis); img[:, P[g]] = S[g] * basis      # (g.E)[perm[t]] = s E[t]
        tgt = [k2 for k2 in NUL if dims[k2] == dims[k] and not (EQA[(k2[0], k2[1], True)] @ img.T).any()]
        if not tgt: perm_ok = False; print('   no target for', g, k)
chk('generators (and 6 random elements) map each relaxed subspace onto a relaxed subspace', perm_ok, True)
json.dump({'controls': res, 'failed': bad, 'generators': gens, 'relaxed_dims': {'%s-%s' % k: v for k, v in dims.items()}}, open('ctrl_objects.json', 'w'), indent=1)
print('FAILED' if bad else 'ALL GREEN', bad)
