#!/usr/bin/env python3
"""
b23 — EXACTNESS CONTROL on v3 route (b): does the single-quark corner-resolved
pole carry ANY taste-breaking signal, or is it degenerate at all couplings by
exact symmetry?

Claim under test (derived analytically this session, controlled here per A.21):
  (T1) Config-wise shift identity: for the K=6 staggered action with
       S_mu: chi(x) -> zeta_mu(x) chi(x+mu),  U_nu(x) -> U_nu(x+mu),
       zeta_mu(x) = (-1)^{sum_{nu>mu} x_nu},
       the quark propagator obeys, exactly per configuration,
         S[U^shift]_{B+z(mu), B'+z(mu)}(p) = ph * S[U]_{B,B'}(p) * ph'^*
       with |ph|=|ph'|=1 and z(mu) = sum_{nu>mu} e_nu (mod 2);
       in particular corner-DIAGONAL entries are equal along the orbit.
  (T2) The group generated by {z(mu)} translations together with S3 axis
       permutations acts TRANSITIVELY on the 8 corners.
  (T3) Ensemble translation invariance makes <S> corner-diagonal.
  (T1)+(T2)+(T3) => the ensemble-averaged corner-diagonal quark propagator is
  the SAME function of reduced momentum for all 8 corners AT EVERY COUPLING:
  route (b)'s observable is exactly zero-signal (must-be-silent everywhere).

Controls:
  C-A (must-hold): free field (U=1): all 8 corner masses equal m to machine
      precision (the doubling degeneracy — sanity of the corner projection).
  C-B (must-hold): random INTERACTING config U: the shift identity holds
      elementwise to machine precision, for each mu, on the corner-projected
      propagator at several reduced momenta.  Random links (not equilibrated)
      suffice: the identity is config-wise and coupling-independent.
  C-C (must-FIRE): a deliberately WRONG zeta phase (zeta -> 1) must break the
      identity at O(1).  If C-C does not fire, the instrument cannot detect a
      broken identity and C-B is meaningless.
  C-D (transitivity): explicit orbit computation on {0,1}^3.

Lattice: L=4 (VOL*NK = 384 -> dense inverse trivially exact), K=6 = 3+2+1
blocks with independent random SU(3), SU(2), U(1) links, staggered phases
eta_mu(x) = (-1)^{sum_{nu<mu} x_nu} exactly as in k6_hmc.c.
"""
import numpy as np, itertools, sys

rng = np.random.default_rng(230805)
L = 4; DIM = 3; NK = 6; VOL = L**3

def site(c):  return ((c[0]%L)*L + (c[1]%L))*L + (c[2]%L)
def coords(s): return np.array([s//(L*L), (s//L)%L, s%L])

def eta(s, mu):
    c = coords(s); return 1.0 if (c[:mu].sum() % 2 == 0) else -1.0

def zeta(s, mu):
    c = coords(s); return 1.0 if (c[mu+1:].sum() % 2 == 0) else -1.0

def rand_su(n):
    z = (rng.standard_normal((n, n)) + 1j*rng.standard_normal((n, n)))/np.sqrt(2)
    q, r = np.linalg.qr(z); q = q @ np.diag(np.exp(-1j*np.angle(np.diag(r))))
    return q / np.linalg.det(q)**(1.0/n)

def random_links():
    U = np.zeros((VOL, DIM, NK, NK), dtype=complex)
    for s in range(VOL):
        for mu in range(DIM):
            U[s, mu, 0:3, 0:3] = rand_su(3)
            U[s, mu, 3:5, 3:5] = rand_su(2)
            U[s, mu, 5, 5] = np.exp(1j*rng.uniform(0, 2*np.pi))
    return U

def unit_links():
    U = np.zeros((VOL, DIM, NK, NK), dtype=complex)
    U[:, :] = np.eye(NK)
    return U

def build_D(U, mass):
    """Dense K=6 staggered D, conventions of k6_hmc.c apply_D."""
    N = VOL*NK
    D = np.zeros((N, N), dtype=complex)
    for s in range(VOL):
        D[s*NK:(s+1)*NK, s*NK:(s+1)*NK] += mass*np.eye(NK)
        c = coords(s)
        for mu in range(DIM):
            ph = eta(s, mu)*0.5
            cp = c.copy(); cp[mu] += 1; sp = site(cp)
            cm = c.copy(); cm[mu] -= 1; sm = site(cm)
            D[s*NK:(s+1)*NK, sp*NK:(sp+1)*NK] += ph*U[s, mu]
            D[s*NK:(s+1)*NK, sm*NK:(sm+1)*NK] -= ph*U[sm, mu].conj().T
    return D

def shift_links(U, mu):
    """U'_nu(x) = U_nu(x - mu): the link shift that pairs with
    (M chi)(x) = zeta_mu(x) chi(x+mu) in D[U'] = M^{-1} D[U] M, equivalently
    M D[U'] M^{-1} = D[U].  (Direction pinned empirically 2026-08-05: the
    +mu pairing fails at O(1); zeta_mu(x) = zeta_mu(x+mu) since zeta depends
    only on coordinates nu > mu.)"""
    Up = np.empty_like(U)
    for s in range(VOL):
        c = coords(s); c[mu] -= 1
        Up[s] = U[site(c)]
    return Up

def shift_op(mu):
    """Matrix of (S_mu chi)(x) = zeta_mu(x) chi(x+mu) on the VOL*NK space."""
    N = VOL*NK
    M = np.zeros((N, N))
    for s in range(VOL):
        c = coords(s); c[mu] += 1; sp = site(c)
        M[s*NK:(s+1)*NK, sp*NK:(sp+1)*NK] = zeta(s, mu)*np.eye(NK)
    return M

# corner projection: for reduced momentum p in (-pi/2,pi/2]^3 and corner
# B in {0,1}^3, plane wave e^{i(p+pi B).x}
corners = list(itertools.product([0, 1], repeat=3))
def plane_waves(p):
    W = np.zeros((8, VOL), dtype=complex)
    X = np.array([coords(s) for s in range(VOL)])
    for bi, B in enumerate(corners):
        q = p + np.pi*np.array(B)
        W[bi] = np.exp(1j*(X @ q))/np.sqrt(VOL)
    return W

def corner_block(Sfull, p):
    """8x8 corner matrix of the color-traced propagator at reduced momentum p:
       C_{BB'} = (1/NK) sum_k <B,k| S |B',k>."""
    W = plane_waves(p)
    C = np.zeros((8, 8), dtype=complex)
    Sr = Sfull.reshape(VOL, NK, VOL, NK)
    # T[b,x,y] etc: contract plane waves on both sides, trace color
    T1 = np.einsum('bx,xkyl->bkyl', W.conj(), Sr)
    T2 = np.einsum('bkyl,cy->bkcl', T1, W)
    C = np.einsum('bkck->bc', T2)/NK
    return C

def report(name, val, tol, mode="must_hold"):
    ok = (val < tol) if mode == "must_hold" else (val > tol)
    tag = "PASS" if ok else "FAIL"
    print(f"  [{tag}] {name}: {val:.3e} ({'<' if mode=='must_hold' else '>'} {tol:.0e})")
    return ok

print("=== b23 exactness control on route (b), L=%d, K=%d ===" % (L, NK))
mass = 0.10
allok = True

# ---- C-D transitivity of <z(mu) translations, S3> on corners --------------
zvecs = []
for mu in range(DIM):
    z = np.zeros(3, dtype=int); z[mu+1:] = 1
    zvecs.append(tuple(z % 2))
print("shift corner-translations z(mu):", zvecs)
orbit = {(0, 0, 0)}
frontier = [(0, 0, 0)]
perms = list(itertools.permutations(range(3)))
while frontier:
    b = frontier.pop()
    nxt = []
    for z in zvecs:
        nxt.append(tuple((np.array(b)+np.array(z)) % 2))
    for pm in perms:
        nxt.append(tuple(np.array(b)[list(pm)]))
    for n in nxt:
        if n not in orbit:
            orbit.add(n); frontier.append(n)
print("  orbit of (0,0,0) under <shifts, S3>: size %d of 8" % len(orbit))
allok &= report("C-D transitivity (8 - orbit size)", 8-len(orbit), 0.5)

# ---- C-A free-field corner degeneracy -------------------------------------
Ufree = unit_links()
Df = build_D(Ufree, mass)
Sf = np.linalg.inv(Df)
p0 = np.array([0.0, 0.0, 0.0])
C0 = corner_block(Sf, p0)
diag = np.real(np.diag(C0))
offd = np.abs(C0 - np.diag(np.diag(C0))).max()
# at p=0, free S corner-diagonal entries all = 1/mass
allok &= report("C-A free diag spread max|d_i - d_j|", np.ptp(diag), 1e-10)
allok &= report("C-A free diag vs 1/m", abs(diag.mean() - 1.0/mass), 1e-10)
allok &= report("C-A free off-diagonal", offd, 1e-10)

# ---- C-B config-wise shift identity on random interacting links -----------
U = random_links()
D = build_D(U, mass)
S = np.linalg.inv(D)
ps = [np.array([0.0, 0.0, 0.0]),
      np.array([2*np.pi/L, 0.0, 0.0]),          # on-lattice reduced momenta
      np.array([0.0, 2*np.pi/L, 2*np.pi/L])]
for mu in range(DIM):
    Us = shift_links(U, mu)
    Ds = build_D(Us, mass)
    Ss = np.linalg.inv(Ds)
    # operator identity: S_mu D[U^shift] S_mu^{-1} = D[U]  =>  Ss = M^{-1} S M
    M = shift_op(mu)
    lhs = M @ Ss @ np.linalg.inv(M)
    err_op = np.abs(lhs - S).max()
    allok &= report(f"C-B operator identity mu={mu} max|M Ss M^-1 - S|", err_op, 1e-10)
    # corner-level consequence: diagonal entries transported to B+z(mu)
    z = np.array(zvecs[mu])
    for p in ps:
        Cb  = corner_block(S,  p)
        Cbs = corner_block(Ss, p)
        errs = []
        for bi, B in enumerate(corners):
            Bt = tuple((np.array(B)+z) % 2); bj = corners.index(Bt)
            errs.append(abs(Cbs[bj, bj] - Cb[bi, bi]))
        allok &= report(f"C-B corner-diag transport mu={mu} p={np.round(p,3)}",
                        max(errs), 1e-10)

# ---- C-C must-FIRE: wrong phase (zeta -> 1) must break the identity -------
mu = 0
Us = shift_links(U, mu)
Ds = build_D(Us, mass)
Ss = np.linalg.inv(Ds)
Mwrong = np.zeros((VOL*NK, VOL*NK))
for s in range(VOL):
    c = coords(s); c[mu] += 1; sp = site(c)
    Mwrong[s*NK:(s+1)*NK, sp*NK:(sp+1)*NK] = np.eye(NK)   # zeta stripped
lhs = Mwrong @ Ss @ np.linalg.inv(Mwrong)
err_wrong = np.abs(lhs - S).max()
allok &= report("C-C must-FIRE wrong-phase residual", err_wrong, 1e-3, mode="must_fire")

# ---- consequence statement -------------------------------------------------
print()
if allok:
    print("ALL CONTROLS GREEN.")
    print("T1 (config-wise shift identity) + T2 (transitivity) verified exactly;")
    print("with T3 (ensemble translation invariance => <S> corner-diagonal),")
    print("the ensemble corner-diagonal quark propagator is the SAME function")
    print("for all 8 corners at every coupling. ROUTE (b) IS ZERO-SIGNAL:")
    print("its free-degeneracy gate would pass and its production would")
    print("measure an exact symmetry zero. Route (b) CLOSED before build.")
else:
    print("CONTROL FAILURE — the analytic claim is NOT certified; do not act on it.")
sys.exit(0 if allok else 1)
