"""Independent exact audit of EQ3-P's four-copy results (coordinator; research only, base bcbc516f).

Imports nothing from scratchpad/eq3/P.  Conventions are typed in by hand (the kernel cnot tables as in review_eq2b.py)
and re-parsed from the base text as a transcription control.  The four-copy contractions are computed in OPERATOR form
(16 x 16 matrices on four qubits, explicit assembly and partial trace), not in the thread's table calculus; the table
formulas are then checked against the operator computation.
Usage:  python3 -I -B audit_eq3_n1.py <base>/verification/lean-mathlib/OIBridge

Conventions.  Pauli dictionary s0 = 1, s1 = X, s2 = Y, s3 = Z.  State table of a two-qubit operator rho:
coords(rho)[m][n] = tr(rho (s_m (x) s_n)); pauli(T) = (1/4) sum T[m][n] s_m (x) s_n.  Effect table of an effect
operator E: coords(E)/4, paired with state tables by the Euclidean pairing <e, X> = sum e[m][n] X[m][n].  First table
index = first token (control).  Four qubits ordered (0, 1, 2, 3).  Instance KT(4; 01|23, 02|13).

DECISION RULES (fixed before the first run; rules, not expected numbers):
  K  transcription and kernel controls: parsed sgn/pc/pt (CompositeDimension:741-781), phiW (CD:1220), idW and chainW
     (K2Guard:101-107), reflY (K2G:46) and sharpVec (EffectSpace:57) equal the hand transcriptions; landed
     cnot(prodState xplus z3) = phiW and cnot(idW) = chainW reproduce; the kernel cnot equals Ad(CNOT) in my
     dictionary (symbolic table); it is orthogonal and symmetric as a 16 x 16 matrix; pairVal(sharpVec x, sharpVec y)
     is the pairing with the effect table of the product of the two sharp effect operators (symbolic).
  O  operator four-copy calculus: (O1) my index-sum conditional equals the explicit partial trace (symbolic L, L', F);
     (O2) its state table is L.f.L'^T with f the effect table of F (symbolic); (O3) the family (i) value
     tr[(E02 (x) F13)(X01 (x) Y23)] equals <X, e.Y.f^T> (symbolic).
  I  inclusion (I): with the Bell link |Omega> = |00> + |11> on (0,2) and (1,3) the conditional of F on (2,3) is
     F^T (symbolic F); in tables Delta.f.Delta = T f with T the transpose map.  Inclusion (II): with Bell effects on
     (0,2), (1,3) the value is tr(X Y^T) (symbolic X, Y).  Both are linear identities in the cone elements.
  L  links from the gate: (L1) CNOT(|a>|c>) has coefficient diag(a).Circ(c) (symbolic); (L2) general rank-one links
     with coefficients C, C' give the conditional (C (x) C') F^T (C (x) C')^dag (symbolic C, C', F); (L3) every 2 x 2
     coefficient with four nonzero entries is diag(1,u).Circ(c).diag(1,u') (symbolic); (L4) the filtered conditional
     of the gate effect CNOT(|+><+| (x) |b><b|)CNOT is the pure state with coefficient diag(1,u).conj(Circ(b))/sqrt2.
     diag(1,u') (symbolic); (L5) maximally entangled gate links (1 - t^2) 1 + 2it X and diag(1, z), |z| = 1, induce
     on copy 0 the maps homMap(R) with R in SO(3) a rotation about x (resp. z), R != 1 (exact rational t, z).
  G  general charts (exact rational O(3) locals, proper and improper, pre- and post-locals independent):
     (G1) N = l1 . cnot . l2 is orthogonal, so (N^-1)^T = N; (G2) the Bell STATE N(l2^-1(prodState xplus z3)) is
     H_R with R = A reflY B^T; (G3) the Bell EFFECT through the dual action of N^-1 on the product effect
     l2^-1(sharp xplus (x) sharp z3) (itself a product of sharp effects) is H_R/4, the same Theta; (G4) with these,
     (I) gives Theta(K23*) <= K01 and (II) gives K01 <= Theta(K23*) for one Theta (symbolic f, X, Y); (G5) NOTE, not
     a pass condition: through N's own dual the Bell effect is H_R'/4 with R' = A2^T reflY B2 from the pre-locals,
     and an exact gate with det R' != det R is exhibited; (G6) a maximally entangled link in general charts on (0,2)
     with the Bell link on (1,3) maps Theta^-1(X) to c . H_{A R_C A^T} X (symbolic X): rotations of copy 0.
  P  twisted configurations, independent: pair cones K^t = PT_second^t(PSD); for all 16 assignments on (01, 23, 02, 13)
     the minimum of both family values over the Bell-basis candidates (states and effects in the cones) is negative
     iff t01 + t13 + t23 + t02 is odd; for every S in the 16 subsets of tokens, K4 = PT_S(PSD16) contains the
     products of both groupings exactly when the pair twists are t_ij = [i in S] + [j in S] mod 2 (exact identity).
  F  K_F foil, independent: the group generated by local H, S (both tokens) and CNOT acting on tables by my
     dictionary; its order is reported; over the orbit of psi psi^dag (psi = (1,1,1,2)/sqrt7) the largest marginal
     Bloch norm^2 is < (24/25)^2 (so w = (49/50) 1 - psi psi^dag lies in K_F*); countercontrol: a product state's orbit
     reaches norm^2 1; the four-copy value tr[(W01 (x) F23)(Phi+02 (x) Phi+13)] with F = psi psi^dag is negative.
  Q  converse control: PSD16 satisfies both families on exact random PSD instances.
VERDICT `AUDIT-EQ3-N1-EXACT` iff every check passes; otherwise VERDICT NOT RENDERED.  Exact arithmetic only.
Run log: run 1 (kept as audit_eq3_n1.run1.*) 28/29, G3 FAIL from a harness error: sharpVec divided Python ints, so
floats entered G3/G5 (residues ~1e-16; the G5 NOTE printed -1.00000000000000).  Fixed by exact division and an
explicit no-Float guard in K4, G3 and G5; decision rules unchanged.
"""
import itertools
import random
import re
import sys
from functools import reduce

import sympy as sp
from sympy import I, Matrix, Rational as R, eye, zeros

BASE = sys.argv[1]
checks = []


def check(name, cond):
    checks.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name)
    sys.stdout.flush()


def note(text):
    print("NOTE " + text)
    sys.stdout.flush()


def Z(M):
    return M.applyfunc(sp.expand).is_zero_matrix


def kron(*Ms):
    return reduce(sp.kronecker_product, Ms)


# ------------------------------------------------------------------ K transcription (hand) and parse (base text)
def sgn_hand(m, n):
    return -1 if (m == 1 and n == 3) or (m == 2 and n == 2) else 1


PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]

cd = open(BASE + "/CompositeDimension.lean", encoding="utf-8").read()
k2 = open(BASE + "/K2Guard.lean", encoding="utf-8").read()
es = open(BASE + "/EffectSpace.lean", encoding="utf-8").read()


def parse_table(name):
    i = cd.index("def " + name + " : Fin 4 → Fin 4 → Fin 4")
    block = cd[i:i + 400]
    tab = [[None] * 4 for _ in range(4)]
    for m, n, v in re.findall(r"\|\s*(\d),\s*(\d)\s*=>\s*(\d)", block)[:16]:
        tab[int(m)][int(n)] = int(v)
    return tab


i_s = cd.index("def sgn (μ ν : Fin 4) : ℝ :=")
sgn_line = cd[i_s:cd.index("\n", i_s)]
neg_pairs = {(int(a), int(b)) for a, b in re.findall(r"μ = (\d) ∧ ν = (\d)", sgn_line)}
ok_sgn = "then -1 else 1" in sgn_line and all(
    (sgn_hand(m, n) == -1) == ((m, n) in neg_pairs) for m in range(4) for n in range(4))
i_p = cd.index("def phiW : W 3 :=")
phi_line = cd[i_p:cd.index("\n", i_p)]
ok_phi = phi_line.strip() == "def phiW : W 3 := fun μ ν => if μ = ν then (if μ = 2 then -1 else 1) else 0"


def parse_matrix(src, name):
    i = src.index("def " + name + " : W 3 := ")
    line = src[i:src.index("\n", i)]
    rows = re.findall(r"!\[([-\d, ]+)\]", line)
    return Matrix([[int(v) for v in r.split(",")] for r in rows])


idW_p, chainW_p = parse_matrix(k2, "idW"), parse_matrix(k2, "chainW")
ok_refl = "toFun x := fun i => (![1, -1, 1] : Fin 3 → ℝ) i * x i" in k2
ok_sharp = "def sharpVec (b : Fin d → ℝ) : HVec d := Matrix.vecCons (1 / 2) fun j => b j / 2" in es
check("K0 parsed pc, pt, sgn equal the hand transcription; phiW, idW, chainW, reflY, sharpVec as transcribed",
      parse_table("pc") == PC and parse_table("pt") == PT and ok_sgn and ok_phi and ok_refl and ok_sharp
      and idW_p == eye(4) and chainW_p == Matrix([[1, 0, 0, 1], [1, 0, 0, -1], [0, 0, 0, 0], [0, 0, 0, 0]]))

DEL = sp.diag(1, 1, -1, 1)                    # phiW
REFLY = sp.diag(1, -1, 1)


def cnot_tab(T):
    return Matrix(4, 4, lambda m, n: sgn_hand(m, n) * T[PC[m][n], PT[m][n]])


def hom(x):
    return Matrix([1] + list(x))


def prodState(x, y):
    return hom(x) * hom(y).T


def H(A):                                     # homMap A on HVec 3
    M = eye(4)
    M[1:, 1:] = A
    return M


XPLUS, Z3 = [1, 0, 0], [0, 0, 1]
check("K1 landed controls reproduce: cnot(prodState xplus z3) = phiW (CD:1222) and cnot(idW) = chainW (K2G:110)",
      cnot_tab(prodState(XPLUS, Z3)) == DEL and cnot_tab(eye(4)) == chainW_p)

# ------------------------------------------------------------------ my Pauli dictionary
s0 = eye(2)
sx = Matrix([[0, 1], [1, 0]])
sy = Matrix([[0, -I], [I, 0]])
sz = Matrix([[1, 0], [0, -1]])
SIG = [s0, sx, sy, sz]
SS = [[kron(SIG[m], SIG[n]) for n in range(4)] for m in range(4)]


def coords(rho):
    return Matrix(4, 4, lambda m, n: sp.expand((rho * SS[m][n]).trace()))


def coords1(rho):
    return Matrix([sp.expand((rho * SIG[m]).trace()) for m in range(4)])


def pauli(T):
    out = zeros(4, 4)
    for m in range(4):
        for n in range(4):
            out += T[m, n] * SS[m][n]
    return out / 4


CNOT = Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])


def symtab(p):
    return Matrix(4, 4, lambda m, n: sp.Symbol("%s%d%d" % (p, m, n), real=True))


def herm(p):
    a = sp.symbols(p + "0:16", real=True)
    M = zeros(4, 4)
    k = 0
    for r in range(4):
        M[r, r] = a[k]
        k += 1
    for r in range(4):
        for c in range(r + 1, 4):
            M[r, c] = a[k] + I * a[k + 1]
            M[c, r] = a[k] - I * a[k + 1]
            k += 2
    return M


Ts = symtab("t")
check("K2 the kernel cnot is Ad(CNOT) in my dictionary: cnot(T) = coords(CNOT pauli(T) CNOT) (symbolic T)",
      Z(cnot_tab(Ts) - coords(CNOT * pauli(Ts) * CNOT)))


def tab_matrix(f):                            # 16 x 16 matrix of a linear table map, vec index 4m + n
    M = zeros(16, 16)
    for k in range(16):
        E = zeros(4, 4)
        E[k // 4, k % 4] = 1
        img = f(E)
        for j in range(16):
            M[j, k] = img[j // 4, j % 4]
    return M


CN16 = tab_matrix(cnot_tab)
check("K3 the kernel cnot is orthogonal and symmetric as a 16 x 16 matrix (so its Euclidean dual is itself)",
      CN16.T * CN16 == eye(16) and CN16.T == CN16)
x1, x2, x3, y1, y2, y3 = sp.symbols("x1 x2 x3 y1 y2 y3", real=True)
xs, ys = [x1, x2, x3], [y1, y2, y3]


def sharp_op(v):
    return (s0 + v[0] * sx + v[1] * sy + v[2] * sz) / 2


def sharpVec(v):
    return Matrix([R(1, 2)] + [sp.S(c) / 2 for c in v])


def exact(*Ms):                               # no floating-point atom anywhere (run 1 harness error: int / 2)
    return all(not sp.Matrix(M).atoms(sp.Float) for M in Ms)


pv = (sharpVec(xs).T * Ts * sharpVec(ys))[0, 0]
eff_tab = coords(kron(sharp_op(xs), sharp_op(ys))) / 4
check("K4 pairVal(sharpVec x, sharpVec y, T) = <effect table of sharp(x) (x) sharp(y), T>, and that effect table is "
      "prodState(x, y)/4 (symbolic x, y, T)",
      exact(sharpVec(XPLUS), sharpVec(Z3)) and sp.expand(pv - sum(eff_tab[m, n] * Ts[m, n] for m in range(4) for n in range(4))) == 0
      and Z(eff_tab - prodState(xs, ys) / 4))
PHIP = Matrix([1, 0, 0, 1]) / sp.sqrt(2)
PHI = (PHIP * PHIP.T).applyfunc(sp.nsimplify)
check("K5 phiW = coords(Phi+) and idW = coords(SWAP/2) = coords(PT_2 Phi+)",
      coords(PHI) == DEL and coords(Matrix([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]]) / 2) == eye(4))


# ------------------------------------------------------------------ O four-copy operator calculus
def idx4(i0, i1, i2, i3):
    return 8 * i0 + 4 * i1 + 2 * i2 + i3


B4 = list(itertools.product(range(2), repeat=4))


def pair_on(Lab, Lcd, a, b):
    """16 x 16 operator Lab (x) Lcd where Lab acts on qubits a < b, Lcd on the other two (in increasing order)."""
    rest = [q for q in range(4) if q not in (a, b)]
    M = zeros(16, 16)
    for ii in B4:
        for jj in B4:
            M[idx4(*ii), idx4(*jj)] = (Lab[2 * ii[a] + ii[b], 2 * jj[a] + jj[b]]
                                       * Lcd[2 * ii[rest[0]] + ii[rest[1]], 2 * jj[rest[0]] + jj[rest[1]]])
    return M


def ptrace23(P):
    return Matrix(4, 4, lambda r, c: sum(P[idx4(r // 2, r % 2, k2_, k3), idx4(c // 2, c % 2, k2_, k3)]
                                         for k2_ in range(2) for k3 in range(2)))


def cond_explicit(L02, L13, F23):
    return ptrace23(kron(eye(4), F23) * pair_on(L02, L13, 0, 2)).applyfunc(sp.expand)


def cond_sum(L02, L13, F23):
    out = zeros(4, 4)
    for i0, i1, j0, j1 in itertools.product(range(2), repeat=4):
        s = 0
        for i2, i3, j2, j3 in itertools.product(range(2), repeat=4):
            s += L02[2 * i0 + i2, 2 * j0 + j2] * L13[2 * i1 + i3, 2 * j1 + j3] * F23[2 * j2 + j3, 2 * i2 + i3]
        out[2 * i0 + i1, 2 * j0 + j1] = s
    return out.applyfunc(sp.expand)


def trace_prod(A, B):
    return sp.expand(sum(A[r, c] * B[c, r] for r in range(A.rows) for c in range(A.cols)))


def val_i(X01, Y23, E02, F13):
    return trace_prod(pair_on(E02, F13, 0, 2), kron(X01, Y23))


Ls, Lps, Fs = herm("l"), herm("m"), herm("f")
c_exp = cond_explicit(Ls, Lps, Fs)
check("O1 the index-sum conditional equals the explicit partial trace tr_23[(1 (x) F)(L02 (x) L'13)] (symbolic)",
      Z(c_exp - cond_sum(Ls, Lps, Fs)))
check("O2 table form of family (ii): coords(conditional) = coords(L) . (coords(F)/4) . coords(L')^T (symbolic)",
      Z(coords(c_exp) - coords(Ls) * (coords(Fs) / 4) * coords(Lps).T))
Xs_, Ys_, Es_, F2s_ = herm("x"), herm("y"), herm("e"), herm("g")
v1 = val_i(Xs_, Ys_, Es_, F2s_)
e_t, f_t, X_t, Y_t = coords(Es_) / 4, coords(F2s_) / 4, coords(Xs_), coords(Ys_)
check("O3 table form of family (i): tr[(E02 (x) F13)(X01 (x) Y23)] = <X, e.Y.f^T> (symbolic)",
      sp.expand(v1 - sum((X_t[m, n] * (e_t * Y_t * f_t.T)[m, n]) for m in range(4) for n in range(4))) == 0)

# ------------------------------------------------------------------ I the two inclusions
OM = Matrix([1, 0, 0, 1])
OMP = OM * OM.T


def Ttab(T):
    return coords(pauli(T).T)


check("I1 inclusion (I): the Bell-link conditional of F is F^T (symbolic F), and in tables Delta.f.Delta = T f with "
      "T the transpose map coords(pauli(.)^T) (symbolic f)",
      Z(cond_sum(OMP, OMP, Fs) - Fs.T) and Z(DEL * Ts * DEL - Ttab(Ts)))
check("I2 inclusion (II): with Bell effects |Omega><Omega| on (0,2), (1,3) the value is tr(X Y^T) (symbolic X, Y)",
      sp.expand(val_i(Xs_, Ys_, OMP, OMP) - (Xs_ * Ys_.T).trace()) == 0)

# ------------------------------------------------------------------ L links from the gate
a0, a1, c0, c1 = sp.symbols("a0 a1 c0 c1")
coef = CNOT * kron(Matrix([a0, a1]), Matrix([c0, c1]))
check("L1 CNOT(|a>|c>) has coefficient matrix diag(a).Circ(c), Circ(c) = [[c0, c1], [c1, c0]] (symbolic)",
      Z(Matrix(2, 2, lambda i, k: coef[2 * i + k]) - sp.diag(a0, a1) * Matrix([[c0, c1], [c1, c0]])))


def csym(p):
    r = sp.symbols(p + "r0:4", real=True)
    i = sp.symbols(p + "i0:4", real=True)
    return Matrix(2, 2, lambda a, b: r[2 * a + b] + I * i[2 * a + b])


def vec(C):
    return Matrix([C[0, 0], C[0, 1], C[1, 0], C[1, 1]])


def proj(v):
    return (v * v.H).applyfunc(sp.expand)


Cs, Cps = csym("c"), csym("d")
Kc = kron(Cs, Cps)
check("L2 general rank-one links: links with coefficients C on (0,2), C' on (1,3) give the conditional "
      "(C (x) C') F^T (C (x) C')^dag (symbolic C, C', F)",
      Z(cond_sum(proj(vec(Cs)), proj(vec(Cps)), Fs) - Kc * Fs.T * Kc.H))
p_, q_, r_, w_ = sp.symbols("p q r w", nonzero=True)
u_cov, up_cov = r_ / w_, q_ / w_
lhs_cov = sp.diag(1, u_cov) * Matrix([[p_, w_], [w_, p_]]) * sp.diag(1, up_cov)
check("L3 coverage: diag(1, r/w).Circ(p, w).diag(1, q/w) = [[p, q], [r, p q r / w^2]] (symbolic): every coefficient "
      "[[p, q], [r, s]] with pqrs != 0 arises, w a square root of pqr/s",
      Z(lhs_cov - Matrix([[p_, q_], [r_, p_ * q_ * r_ / w_ ** 2]])))
ur, ui, vr, vi, br0, bi0, br1, bi1 = sp.symbols("ur ui vr vi br0 bi0 br1 bi1", real=True)
u, up = ur + I * ui, vr + I * vi
bv = Matrix([br0 + I * bi0, br1 + I * bi1])
plus = Matrix([1, 1]) / sp.sqrt(2)
g_op = (CNOT * proj(kron(plus, bv)) * CNOT).applyfunc(sp.expand)
Xb = Matrix([[bv[0], bv[1]], [bv[1], bv[0]]]) / sp.sqrt(2)
phi_cov = vec(sp.diag(1, u) * Xb.applyfunc(sp.conjugate) * sp.diag(1, up))
check("L4 the filtered conditional of the gate effect CNOT(|+><+| (x) |b><b|)CNOT through links |00> + u|11>, "
      "|00> + u'|11> is the pure state with coefficient diag(1,u).conj(Circ(b))/sqrt2.diag(1,u') (symbolic u, u', b)",
      Z(cond_sum(proj(vec(sp.diag(1, u))), proj(vec(sp.diag(1, up))), g_op) - proj(phi_cov)))


def one_copy_map(C):
    """coords map of rho -> C rho C^dag / |det C| on one qubit, as a 4 x 4 matrix on hom vectors."""
    d = sp.sqrt(sp.expand(C.det() * sp.conjugate(C.det())))
    M = zeros(4, 4)
    for k in range(4):
        img = C * SIG[k] * C.H / d
        for j in range(4):
            M[j, k] = sp.nsimplify(sp.expand((img * SIG[j]).trace() / 2))
    return M


ok_rot = True
for t in (R(1, 2), R(2, 3)):
    CX = (1 - t ** 2) * eye(2) + 2 * I * t * sx
    cf = CNOT * kron(Matrix([1, 1]), Matrix([1 - t ** 2, 2 * I * t]))
    MX = one_copy_map(CX)
    RX = MX[1:, 1:]
    ok_rot &= Z(Matrix(2, 2, lambda i, k: cf[2 * i + k]) - CX) and Z(MX - H(RX)) and Z(RX.T * RX - eye(3)) \
        and RX.det() == 1 and RX * Matrix([1, 0, 0]) == Matrix([1, 0, 0]) and RX != eye(3)
for s in (R(1, 3), R(3, 2)):
    zz = (1 - s ** 2 + 2 * I * s) / (1 + s ** 2)
    CZ = sp.diag(1, zz)
    cf = CNOT * kron(Matrix([1, zz]), Matrix([1, 0]))
    MZ = one_copy_map(CZ)
    RZ = MZ[1:, 1:]
    ok_rot &= Z(Matrix(2, 2, lambda i, k: cf[2 * i + k]) - CZ) and Z(MZ - H(RZ)) and Z(RZ.T * RZ - eye(3)) \
        and RZ.det() == 1 and RZ * Matrix([0, 0, 1]) == Matrix([0, 0, 1]) and RZ != eye(3)
check("L5 the gate's maximally entangled links (1 - t^2) 1 + 2it X = CNOT(|+>|c>) and diag(1, z) = CNOT(|a>|0>) "
      "induce on copy 0 homMap(R), R in SO(3) a nontrivial rotation about x (resp. z) (exact t = 1/2, 2/3; "
      "z from s = 1/3, 3/2)", ok_rot)

# ------------------------------------------------------------------ G general charts
rng = random.Random(20261008)


def rat_rot():
    a, b, c = (R(rng.randint(-5, 5), rng.randint(1, 4)) for _ in range(3))
    S = Matrix([[0, -a, -b], [a, 0, -c], [b, c, 0]])
    return ((eye(3) - S) * (eye(3) + S).inv()).applyfunc(sp.expand)


def local16(A, B):
    return kron(H(A), H(B))


def apply16(M, T):
    v = M * Matrix([T[k // 4, k % 4] for k in range(16)])
    return Matrix(4, 4, lambda m, n: v[4 * m + n])


def gate(A, B, A2, B2):
    return local16(A, B) * CN16 * local16(A2, B2)


A_, B_, A2_, B2_ = rat_rot(), rat_rot() * REFLY, rat_rot() * REFLY, rat_rot()
Ap_, Bp_, A2p_, B2p_ = rat_rot() * REFLY, rat_rot(), rat_rot(), rat_rot() * REFLY
N02, N13 = gate(A_, B_, A2_, B2_), gate(Ap_, Bp_, A2p_, B2p_)
ok_o = all(Z(M.T * M - eye(3)) for M in (A_, B_, A2_, B2_, Ap_, Bp_, A2p_, B2p_))
check("G1 general gates N = l1 . cnot . l2 (exact rational O(3) locals, proper and improper, pre- and post-locals "
      "independent) are orthogonal, so the dual of N^-1 acts on effect tables as N",
      ok_o and Z(N02.T * N02 - eye(16)) and Z(N13.T * N13 - eye(16)) and Z(N02.inv().T - N02))
R02, R13 = A_ * REFLY * B_.T, Ap_ * REFLY * Bp_.T
pin = apply16(local16(A2_, B2_).inv(), prodState(XPLUS, Z3))
pin13 = apply16(local16(A2p_, B2p_).inv(), prodState(XPLUS, Z3))
st02, st13 = apply16(N02, pin), apply16(N13, pin13)
check("G2 the Bell STATE N(l2^-1(prodState xplus z3)) is homMap(R), R = A reflY B^T (both link pairs), and the input "
      "l2^-1(prodState xplus z3) is a product state",
      Z(st02 - H(R02)) and Z(st13 - H(R13)) and Z(pin - prodState(list(A2_.T * Matrix(XPLUS)), list(B2_.T * Matrix(Z3)))))
eff_in = apply16(local16(A2_, B2_).inv(), sharpVec(XPLUS) * sharpVec(Z3).T)
eff02 = apply16(N02.inv().T, eff_in)
check("G3 the Bell EFFECT through the dual action of N^-1 on the product effect l2^-1(sharp xplus (x) sharp z3) "
      "(a product of two sharp effects) is homMap(R)/4: the same Theta as the Bell state",
      exact(eff02, eff_in, st02) and Z(eff02 - H(R02) / 4)
      and Z(eff_in - sharpVec(list(A2_.T * Matrix(XPLUS))) * sharpVec(list(B2_.T * Matrix(Z3))).T))
fs_ = symtab("f")
Xg, Yg = symtab("x"), symtab("y")
lhs_I = st02 * fs_ * st13.T
val_II = sum(Xg[m, n] * ((H(R02) / 4) * Yg * (H(R13) / 4).T)[m, n] for m in range(4) for n in range(4))
check("G4 with one Theta(g) = H_R02 g H_R13^T: the Bell-state conditional of f is Theta(f) (so Theta(K23*) <= K01) "
      "and the Bell-effect value is <X, Theta(Y)>/16 (so K01 <= Theta(K23)* = Theta(K23*), Theta orthogonal)",
      Z(lhs_I - H(R02) * fs_ * H(R13).T) and sp.expand(val_II - sum(
          Xg[m, n] * (H(R02) * Yg * H(R13).T)[m, n] for m in range(4) for n in range(4)) / 16) == 0
      and Z(local16(R02, R13).T * local16(R02, R13) - eye(16)))
Nbad = gate(REFLY, eye(3), eye(3), eye(3))
st_bad = apply16(Nbad, prodState(XPLUS, Z3))
eff_bad = apply16(Nbad.T, apply16(local16(REFLY, eye(3)), sharpVec(XPLUS) * sharpVec(Z3).T))
note("G5 through N's OWN dual the Bell effect is l2^T(Delta)/4 (pre-locals): for N = (reflY (x) 1) . cnot the Bell "
     "state is homMap(R) with det R = %s and the N^T Bell effect is homMap(R')/4 with det R' = %s; the inverse's dual "
     "(G3) is what makes (II) use the same Theta as (I)"
     % ((st_bad[1:, 1:]).det(), (4 * eff_bad[1:, 1:]).det()))
check("G5 control: the two Bell effects of that gate differ (so the choice in G3 is substantive)",
      exact(eff_bad, st_bad) and not Z(4 * eff_bad - st_bad)
      and Z(apply16(Nbad.inv().T, sharpVec(XPLUS) * sharpVec(Z3).T) - st_bad / 4))
t_ = R(1, 2)
CX = (1 - t_ ** 2) * eye(2) + 2 * I * t_ * sx
rot_in = coords1(proj(Matrix([1, 1]))) * coords1(proj(Matrix([1 - t_ ** 2, 2 * I * t_]))).T
link_rot = apply16(N02, apply16(local16(A2_, B2_).inv(), rot_in))
MC = one_copy_map(CX)
Xsym = symtab("z")
cond_rot = link_rot * (H(R02).T * Xsym * H(R13)) * st13.T
scale = sp.nsimplify(sp.sqrt(sp.expand(CX.det() * sp.conjugate(CX.det()))))
check("G6 general charts, maximally entangled link on (0,2) and Bell link on (1,3): the conditional of "
      "Theta^-1(X) is c . homMap(A R_C A^T) X with R_C in SO(3) (symbolic X; c = 2|det C|)",
      Z(cond_rot - 2 * scale * H(A_ * MC[1:, 1:] * A_.T) * Xsym) and (A_ * MC[1:, 1:] * A_.T).det() == 1)

# ------------------------------------------------------------------ P twisted configurations
def PT2(M):                                   # partial transpose on the second qubit of a pair
    out = zeros(4, 4)
    for i0, i1, j0, j1 in itertools.product(range(2), repeat=4):
        out[2 * i0 + i1, 2 * j0 + j1] = M[2 * i0 + j1, 2 * j0 + i1]
    return out


BELLV = [Matrix([1, 0, 0, 1]), Matrix([1, 0, 0, -1]), Matrix([0, 1, 1, 0]), Matrix([0, 1, -1, 0])]
BELLP = [proj(v) for v in BELLV]
PAIRS4 = ["01", "23", "02", "13"]


def ilist(M):
    return [[int(M[r, c]) for c in range(4)] for r in range(4)]


IDX8 = list(itertools.product(range(2), repeat=8))


def val_i_int(X, Y, E, F):                    # tr[(E02 (x) F13)(X01 (x) Y23)], explicit index sum
    s_ = 0
    for i0, i1, i2, i3, j0, j1, j2, j3 in IDX8:
        s_ += (E[2 * i0 + i2][2 * j0 + j2] * F[2 * i1 + i3][2 * j1 + j3]
               * X[2 * j0 + j1][2 * i0 + i1] * Y[2 * j2 + j3][2 * i2 + i3])
    return s_


def val_ii_int(e, f, L, Lp):                   # tr[(e01 (x) f23)(L02 (x) L'13)], explicit index sum
    s_ = 0
    for i0, i1, i2, i3, j0, j1, j2, j3 in IDX8:
        s_ += (e[2 * i0 + i1][2 * j0 + j1] * f[2 * i2 + i3][2 * j2 + j3]
               * L[2 * j0 + j2][2 * i0 + i2] * Lp[2 * j1 + j3][2 * i1 + i3])
    return s_


Xq, Yq, Eq, Fq = herm("xq"), herm("yq"), herm("eq"), herm("fq")
xq_sub = {sym: rng.randint(-3, 3) for M in (Xq, Yq, Eq, Fq) for sym in M.free_symbols}
Xn, Yn, En, Fn = (M.subs(xq_sub) for M in (Xq, Yq, Eq, Fq))
check("P0 control: the integer index sums agree with the sympy operator values on an exact Gaussian-integer instance "
      "(family (i) by val_i; family (ii) by the trace of the assembled operators)",
      sp.expand(val_i(Xn, Yn, En, Fn) - sum(
          En[2 * i0 + i2, 2 * j0 + j2] * Fn[2 * i1 + i3, 2 * j1 + j3] * Xn[2 * j0 + j1, 2 * i0 + i1]
          * Yn[2 * j2 + j3, 2 * i2 + i3] for i0, i1, i2, i3, j0, j1, j2, j3 in IDX8)) == 0
      and sp.expand(trace_prod(pair_on(Xn, Yn, 0, 1), pair_on(En, Fn, 0, 2)) - sum(
          Xn[2 * i0 + i1, 2 * j0 + j1] * Yn[2 * i2 + i3, 2 * j2 + j3] * En[2 * j0 + j2, 2 * i0 + i2]
          * Fn[2 * j1 + j3, 2 * i1 + i3] for i0, i1, i2, i3, j0, j1, j2, j3 in IDX8)) == 0)
ok_par, mins = True, []
for tau in itertools.product(range(2), repeat=4):
    t = dict(zip(PAIRS4, tau))
    cands = {p: [ilist(PT2(B) if t[p] else B) for B in BELLP] for p in PAIRS4}
    m1 = min(val_i_int(X, Y, E, F) for X in cands["01"] for Y in cands["23"] for E in cands["02"]
             for F in cands["13"])
    m2 = min(val_ii_int(e, f, L, Lp) for e in cands["01"] for f in cands["23"] for L in cands["02"]
             for Lp in cands["13"])
    odd = (t["01"] + t["13"] + t["23"] + t["02"]) % 2 == 1
    mins.append("%s:%s/%s" % ("".join(map(str, tau)), m1, m2))
    ok_par &= ((min(m1, m2) < 0) == odd)
check("P1 for all 16 twist assignments on (01, 23, 02, 13): a negative family value exists over the Bell-basis "
      "candidates iff the 4-cycle parity is odd  [" + " ".join(mins) + "]", ok_par)


def PTset(M, S, n=4):
    N = 2 ** n
    out = zeros(N, N)
    for a in range(N):
        for b in range(N):
            ba = [(a >> (n - 1 - q)) & 1 for q in range(n)]
            bb = [(b >> (n - 1 - q)) & 1 for q in range(n)]
            for q in S:
                ba[q], bb[q] = bb[q], ba[q]
            out[sum(v << (n - 1 - q) for q, v in enumerate(ba)), sum(v << (n - 1 - q) for q, v in enumerate(bb))] \
                = M[a, b]
    return out


def PTpair(M, S2):                             # partial transpose of a pair operator on the subset S2 of {0, 1}
    out = M
    if 1 in S2:
        out = PT2(out)
    if 0 in S2:
        out = PT2(out.T)                       # PT on the first = full transpose followed by PT on the second
    return out


ok_cob = True
Xr = Matrix(4, 4, lambda i, j: R(rng.randint(-3, 3), 2) + I * R(rng.randint(-3, 3), 3))
Yr = Matrix(4, 4, lambda i, j: R(rng.randint(-3, 3), 5) + I * R(rng.randint(-3, 3), 7))
for S in itertools.chain.from_iterable(itertools.combinations(range(4), k) for k in range(5)):
    lhs = PTset(kron(Xr, Yr), S)
    ok_cob &= lhs == kron(PTpair(Xr, [q for q in (0, 1) if q in S]), PTpair(Yr, [q - 2 for q in (2, 3) if q in S]))
    lhs2 = PTset(pair_on(Xr, Yr, 0, 2), S)
    ok_cob &= lhs2 == pair_on(PTpair(Xr, [i for i, q in enumerate((0, 2)) if q in S]),
                              PTpair(Yr, [i for i, q in enumerate((1, 3)) if q in S]), 0, 2)
ok_cob &= all(PTpair(PTpair(Xr, [0]), [1]) == Xr.T for _ in [0])
check("P2 for every S of the 16 token subsets, PT_S(X01 (x) Y23) = PT_{S cap 01}X (x) PT_{S cap 23}Y and likewise "
      "for the 02|13 grouping (exact instance), and PT on both tokens of a pair is the full transpose: K4 = PT_S(PSD16) "
      "realizes exactly the twist t_ij = [i in S] + [j in S] mod 2 on every pair, i.e. every even 4-cycle pattern",
      ok_cob)

# ------------------------------------------------------------------ F the K_F foil
Hd = Matrix([[1, 1], [1, -1]]) / sp.sqrt(2)
Sg = sp.diag(1, I)
GENU = [kron(Hd, s0), kron(s0, Hd), kron(Sg, s0), kron(s0, Sg), CNOT]


def unitary_tab(U):
    return tab_matrix(lambda T: coords(U * pauli(T) * U.H).applyfunc(sp.nsimplify))


GEN = [unitary_tab(U) for U in GENU]
ok_gen = all(all(x in (0, 1, -1) for x in g) and g[0, 0] == 1 for g in GEN) and GEN[4] == CN16


def to_sperm(M):
    out = []
    for k in range(16):
        nz = [(j, int(M[j, k])) for j in range(16) if M[j, k] != 0]
        assert len(nz) == 1 and nz[0][1] in (1, -1)
        out.append(nz[0])
    return tuple(out)


def compose(g, h):                             # (g . h)(e_k) = g(h(e_k))
    return tuple((g[h[k][0]][0], g[h[k][0]][1] * h[k][1]) for k in range(16))


GSP = [to_sperm(g) for g in GEN]
ident = tuple((k, 1) for k in range(16))
seen = {ident}
frontier = [ident]
while frontier:
    nxt = []
    for M in frontier:
        for g in GSP:
            P_ = compose(g, M)
            if P_ not in seen:
                seen.add(P_)
                nxt.append(P_)
    frontier = nxt
order = len(seen)
psi = Matrix([1, 1, 1, 2])
rho_psi = psi * psi.T / 7
t_psi = coords(rho_psi)
vt = Matrix([t_psi[k // 4, k % 4] for k in range(16)])


def bloch_max(vt_):
    best = 0
    for g in seen:
        w = [0] * 16
        for k in range(16):
            w[g[k][0]] = g[k][1] * vt_[k]
        best = max(best, w[4] ** 2 + w[8] ** 2 + w[12] ** 2, w[1] ** 2 + w[2] ** 2 + w[3] ** 2)
    return best


bm = bloch_max(vt)
prod_t = coords(kron(proj(Matrix([1, 0])), proj(Matrix([1, 0]))))
bm_prod = bloch_max(Matrix([prod_t[k // 4, k % 4] for k in range(16)]))
check("F1 the generators (local H, S on both tokens, CNOT) act on tables as signed permutations fixing the unit, "
      "CNOT's as the kernel cnot; group order %d; over the orbit of psi psi^dag the largest marginal Bloch norm^2 is "
      "%s < (24/25)^2, so the largest Schmidt weight on the orbit is < 49/50 and w = (49/50) 1 - psi psi^dag is in "
      "K_F*; countercontrol: a product state's orbit reaches %s" % (order, bm, bm_prod),
      ok_gen and bm < R(24, 25) ** 2 and bm_prod == 1)
W_op = R(49, 50) * eye(4) - rho_psi
val_F = trace_prod(pair_on(W_op, rho_psi, 0, 1), pair_on(PHI, PHI, 0, 2))
check("F2 the four-copy value tr[(W01 (x) F23)(Phi+02 (x) Phi+13)] with F = psi psi^dag (in K_F* as PSD, K_F <= PSD) "
      "and Phi+ = Ad(CNOT)(|+><+| (x) |0><0|) in K_F is %s < 0: K_F admits no K4 for this instance" % val_F,
      val_F < 0 and Z(CNOT * kron(proj(plus), proj(Matrix([1, 0]))) * CNOT - PHI))
check("F3 control: W is not PSD (eigenvalue -1/50 on psi), so the witness is outside Q3* = PSD",
      Z(W_op * psi + R(1, 50) * psi))

# ------------------------------------------------------------------ Q converse control
ok_q = True
for trial in range(3):
    def rpsd(n):
        G = Matrix(n, n, lambda i, j: R(rng.randint(-3, 3), rng.randint(1, 3)) + I * R(rng.randint(-3, 3), 2))
        return (G * G.H).applyfunc(sp.expand)
    ok_q &= val_i(rpsd(4), rpsd(4), rpsd(4), rpsd(4)) >= 0
    ok_q &= trace_prod(pair_on(rpsd(4), rpsd(4), 0, 1), pair_on(rpsd(4), rpsd(4), 0, 2)) >= 0
check("Q converse: PSD pair cones with K4 = PSD16 give nonnegative values in both families (3 exact random instances)",
      ok_q)

npass = sum(1 for _, c in checks if c)
print("--- audit_eq3_n1: %d/%d checks pass" % (npass, len(checks)))
print("VERDICT AUDIT-EQ3-N1-EXACT" if npass == len(checks) else "VERDICT NOT RENDERED")
