"""Exact checks for the integration design note (coordinator; research only, base bcbc516f).

Decision rules, fixed before the run:
  U1  The twin R_B Q3 has NO type-uniform adapter: for each representative phi in {I, R} of O(3)/SO(3)
      (R = reflY = diag(1,-1,1) on the Bloch vector), the image (phi (x) phi)(I (x) R) Phi+ of the Bell state
      has a negative eigenvalue.  Local SO(3) x SO(3) maps preserve the spectrum, so this covers every
      uniform adapter phi = U.{I or R}.  PASS iff both images have min eigenvalue -1/2.
  U2  Control: the per-token adapter (I, R) carries the twin back exactly ((I (x) R)^2 = id), and the global
      transpose R (x) R preserves the spectrum of Phi+ and of a non-symmetric pure state.  PASS iff spectra agree.
  P   Pauli-string closure: the Lie algebra generated by all 2-local Pauli strings on the edges of a PATH on n
      copies is su(2^n) (closure size 4^n - 1) for n = 3, 4, 5.  Countercontrols: two disjoint edges at n = 4
      give 30; one edge plus single-copy strings on the third copy at n = 3 give 18 (EQ-C P6.1b).
"""
import sys
from itertools import product as iproduct
from sympy import Matrix, I, Rational as R, eye, zeros, kronecker_product as kron

checks = []


def check(name, cond):
    checks.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name)
    sys.stdout.flush()


s0 = eye(2)
sx = Matrix([[0, 1], [1, 0]])
sy = Matrix([[0, -I], [I, 0]])
sz = Matrix([[1, 0], [0, -1]])
paulis = [s0, sx, sy, sz]


def coords(rho):
    """omega_{mu nu} = tr(rho sigma_mu (x) sigma_nu)."""
    return Matrix(4, 4, lambda m, n: (rho * kron(paulis[m], paulis[n])).trace())


def density(om):
    out = zeros(4, 4)
    for m in range(4):
        for n in range(4):
            out += om[m, n] * kron(paulis[m], paulis[n])
    return out / 4


def spectrum(rho):
    ev = rho.eigenvals()
    return sorted([k for k, v in ev.items() for _ in range(v)], key=lambda z: complex(z).real)


Rb = Matrix.diag(1, 1, -1, 1)          # reflY on the Bloch vector, as a map of (1, x, y, z)
Id4 = eye(4)
phi_plus = Matrix([1, 0, 0, 1]) / R(1) * 1
rho_bell = phi_plus * phi_plus.T / 2
om_bell = coords(rho_bell)
check("Pauli coordinates round-trip on Phi+", (density(om_bell) - rho_bell).is_zero_matrix)


def act(A, B, om):
    return A * om * B.T


twin_bell = act(Id4, Rb, om_bell)          # Phi+ as a point of the twin R_B Q3 (native coordinates)
for name, phi in (("I", Id4), ("R", Rb)):
    img = act(phi, phi, twin_bell)
    spec = spectrum(density(img))
    check(f"U1 uniform adapter phi = {name}: image of the twin's Bell point has spectrum {spec}, min -1/2",
          spec[0] == R(-1, 2))
back = act(Id4, Rb, twin_bell)
check("U2 per-token adapter (I, R) maps the twin's Bell point back to Phi+ exactly", back == om_bell)
psi = Matrix([3, 1 + 2 * I, -2, I]) / 1
rho_psi = psi * psi.H / (psi.H * psi)[0, 0]
for name, rho in (("Phi+", rho_bell), ("psi", rho_psi)):
    tr_img = density(act(Rb, Rb, coords(rho)))
    check(f"U2 global transpose R(x)R: image of {name} is its transpose and has the same spectrum",
          (tr_img - rho.T).applyfunc(lambda z: z.expand()).is_zero_matrix and spectrum(tr_img) == spectrum(rho))
pt_img = density(act(Id4, Rb, coords(rho_psi)))
pt_det = pt_img.det().expand()
check(f"U2 countercontrol: one-copy reflection (I(x)R) on the entangled psi is not PSD (det {pt_det} < 0)",
      pt_det.is_real and pt_det < 0)

# Pauli-string closure
MUL = {}
lab = "IXYZ"
for a in lab:
    for b in lab:
        if a == "I":
            MUL[(a, b)] = (b, True)
        elif b == "I" or a == b:
            MUL[(a, b)] = ("I" if a == b else a, True)
        else:
            MUL[(a, b)] = ("XYZ".replace(a, "").replace(b, ""), False)   # anticommuting single-site pair


def anticommute_product(p, q):
    out = []
    anti = 0
    for a, b in zip(p, q):
        c, comm = MUL[(a, b)]
        out.append(c)
        anti ^= (0 if comm else 1)
    return ("".join(out), anti == 1)


def closure(gens):
    S = set(gens)
    frontier = list(S)
    while frontier:
        new = []
        cur = list(S)
        for p in frontier:
            for q in cur:
                r, anti = anticommute_product(p, q)
                if anti and r not in S:
                    S.add(r)
                    new.append(r)
        frontier = new
    S.discard("I" * len(next(iter(gens))))
    return S


def local_strings(n, sites):
    out = set()
    for labels in iproduct(lab, repeat=len(sites)):
        s = ["I"] * n
        for site, l in zip(sites, labels):
            s[site] = l
        st = "".join(s)
        if st != "I" * n:
            out.add(st)
    return out


for n in (3, 4, 5):
    gens = set()
    for i in range(n - 1):
        gens |= local_strings(n, (i, i + 1))
    size = len(closure(gens))
    check(f"P path on {n} copies: 2-local strings generate {size} = 4^{n} - 1 (su(2^{n}))", size == 4 ** n - 1)
g4 = local_strings(4, (0, 1)) | local_strings(4, (2, 3))
check(f"P countercontrol: two disjoint edges at n = 4 close at {len(closure(g4))} = 30", len(closure(g4)) == 30)
g3 = local_strings(3, (0, 1)) | local_strings(3, (2,))
check(f"P countercontrol: one edge plus local strings on the third copy close at {len(closure(g3))} = 18",
      len(closure(g3)) == 18)

npass = sum(1 for _, c in checks if c)
print(f"review_integration: {npass}/{len(checks)} checks pass")
sys.exit(0 if npass == len(checks) else 1)
