"""Independent exact check of EQ2-A's three-copy countermodels (coordinator review; research only, base bcbc516f).

Written from the definitions in EQ2-A's probe docstrings, in operator form; imports nothing from EQ2-A.
Three qubit-type copies 0, 1, 2 (copy 0 is the most significant bit and the first tensor factor). Pair cones:
  Q  = two-copy PSD (density operators), Tw = PT_j(Q) (partial transpose on the second copy j of the pair i < j).
Model K_tau, tau = (t01, t02, t12): the convex cone generated by PT_j^{t_ij}(sigma) on the pair (i, j) times rho on the
remaining copy k, sigma a two-copy state, rho a one-copy state, for all three pairs.
  M_odd = K_(0,1,0), M_tw = K_(1,1,1), M_bs = K_(0,0,0).

Decision rules, fixed before the run (rules, not expected numbers):
  C0  controls: the placement routine reproduces the Kronecker product on pair (0, 1); partial transpose is an
      involution, self-adjoint for the trace pairing, and preserves the Hilbert-Schmidt norm (symbolic 8 x 8).
  T   transported premises, symbolic in a generic two-copy matrix sigma and a generic one-copy state rho(r):
      T1 pair marginals of every generator lie in the pair cone of that pair (matching pair: PT^t(sigma); other
         pairs: a product of one-copy marginals); T2 conditioning copy k on an effect gives the same dichotomy;
      T3 COMP-1 (max side) on each pair|single bipartition for mismatched generators: the value of E (x) f
         factorizes as tr(E_rho . sigma_f) with E_rho, sigma_f obtained by contracting one copy (identity checked
         symbolically; positivity is then tr of a product of two PSD operators);
      T4 IE1: a local unitary U (x) V (x) X maps each generator family onto itself (PT_j intertwines U with conj U);
      T5 per-token charts: PT on copy i maps K_tau onto K_tau' with the twist bits of the two pairs containing i
         flipped (on generators, symbolic); T6 a per-token chart presenting all three pairs as Q exists iff
         t01 + t02 + t12 is even (enumeration).
  G   IE2 fails: omega0 = |+><+| (x) Phi+_(1,2) is a generator of every K_tau with t12 = 0; (CNOT_(0,1) (x) 1) omega0
      (CNOT (x) 1)^dag = |GHZ'><GHZ'|, GHZ' = (|000> + |011> + |101> + |110>)/2; W' = 1/2 - |GHZ'><GHZ'| has value
      -1/2 on GHZ'; W' >= 0 on every generator of every K_tau (written proof: lambda_max(PT^t(X_rho)) <=
      ||X_rho||_HS <= tr X_rho = tr(rho psi_k) = 1/2, inputs checked exactly: every one-copy marginal of GHZ' is 1/2,
      X_rho is PSD (it is tr_k[(1 (x) sqrt rho) psi (1 (x) sqrt rho)])); exact spot checks on random generators
      (labelled as spot checks). The same for M_tw through the chart PT_1 (G4).
  B   M_bs: GHZ is PSD, W_GHZ = 1/2 - |GHZ><GHZ| has value -1/2 on it and is >= 0 on every generator of every K_tau
      (same proof, marginals checked) -- so no per-token chart image of M_bs contains GHZ.
  H   the all-twisted hull B_tw (= K_(1,1,1)): EQ2-A's construction (alpha_p, beta_p, delta_p, GHZ-stabilizer twirl)
      gives twirl(M) = W_GHZ / 3 exactly, every ingredient is PT_j of a PSD operator times a state, the 8 stabilizers
      fix GHZ; countercontrol: dropping the beta family does not give a multiple of W_GHZ.
  V   the review verdict prints only if every check passes.
"""
import sys
import itertools
import random
from functools import reduce
import sympy as sp

checks = []


def check(name, cond):
    checks.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name)
    sys.stdout.flush()


I = sp.I
s0 = sp.eye(2)
sx = sp.Matrix([[0, 1], [1, 0]])
sy = sp.Matrix([[0, -I], [I, 0]])
sz = sp.Matrix([[1, 0], [0, -1]])
PAULI = {"I": s0, "X": sx, "Y": sy, "Z": sz}


def kron(*Ms):
    return reduce(sp.kronecker_product, Ms)


def bits(a, n):
    return [(a >> (n - 1 - q)) & 1 for q in range(n)]


def num(bs):
    v = 0
    for b in bs:
        v = 2 * v + b
    return v


def PT(M, q, n):
    """partial transpose on qubit q of an n-qubit operator"""
    N = 2 ** n
    out = sp.zeros(N, N)
    for a in range(N):
        for b in range(N):
            ba, bb = bits(a, n), bits(b, n)
            ba2, bb2 = list(ba), list(bb)
            ba2[q], bb2[q] = bb[q], ba[q]
            out[a, b] = M[num(ba2), num(bb2)]
    return out


def place(sig, pair, rho):
    """sig on the ordered pair (i, j) (first factor i), rho on the remaining copy k; result on copies (0, 1, 2)"""
    i, j = pair
    k = [c for c in range(3) if c not in pair][0]
    out = sp.zeros(8, 8)
    for a in range(8):
        for b in range(8):
            ba, bb = bits(a, 3), bits(b, 3)
            out[a, b] = sig[2 * ba[i] + ba[j], 2 * bb[i] + bb[j]] * rho[ba[k], bb[k]]
    return out


def ptrace_keep(M, keep, n=3):
    """partial trace keeping the qubits in `keep` (in increasing order)"""
    m = len(keep)
    out = sp.zeros(2 ** m, 2 ** m)
    rest = [q for q in range(n) if q not in keep]
    for a in range(2 ** m):
        for b in range(2 ** m):
            s = 0
            for r in range(2 ** len(rest)):
                ba, bb = [0] * n, [0] * n
                for idx, q in enumerate(keep):
                    ba[q] = bits(a, m)[idx]
                    bb[q] = bits(b, m)[idx]
                for idx, q in enumerate(rest):
                    ba[q] = bits(r, len(rest))[idx]
                    bb[q] = bits(r, len(rest))[idx]
                s += M[num(ba), num(bb)]
            out[a, b] = s
    return out


def contract(M, q, f, n=3):
    """tr_q[(1 (x) f_q) M]: contract qubit q of an n-qubit operator with the one-qubit operator f"""
    keep = [c for c in range(n) if c != q]
    out = sp.zeros(2 ** (n - 1), 2 ** (n - 1))
    for a in range(2 ** (n - 1)):
        for b in range(2 ** (n - 1)):
            s = 0
            for x in range(2):
                for y in range(2):
                    ba, bb = [0] * n, [0] * n
                    for idx, c in enumerate(keep):
                        ba[c] = bits(a, n - 1)[idx]
                        bb[c] = bits(b, n - 1)[idx]
                    ba[q], bb[q] = x, y
                    s += f[y, x] * M[num(ba), num(bb)]
            out[a, b] = s
    return out


def rho1(r):
    return (s0 + r[0] * sx + r[1] * sy + r[2] * sz) / 2


def zero(M):
    return M.applyfunc(sp.expand).is_zero_matrix


PAIRS = [(0, 1), (0, 2), (1, 2)]

# ---------- C0 controls ----------
A2 = sp.Matrix(4, 4, lambda i, j: sp.Symbol(f"a{i}{j}"))
B1 = sp.Matrix(2, 2, lambda i, j: sp.Symbol(f"b{i}{j}"))
check("C0 place(sig, (0,1), rho) == sig (x) rho (symbolic)", zero(place(A2, (0, 1), B1) - kron(A2, B1)))
M8 = sp.Matrix(8, 8, lambda i, j: sp.Symbol(f"m{i}_{j}"))
N8 = sp.Matrix(8, 8, lambda i, j: sp.Symbol(f"n{i}_{j}"))
check("C0 PT is an involution on every qubit (symbolic 8 x 8)", all(PT(PT(M8, q, 3), q, 3) == M8 for q in range(3)))
check("C0 PT is self-adjoint for the pairing tr(A B) (symbolic)",
      all(sp.expand((PT(M8, q, 3) * N8).trace() - (M8 * PT(N8, q, 3)).trace()) == 0 for q in range(3)))
check("C0 PT permutes entries, so it preserves the Hilbert-Schmidt norm",
      all(sorted(map(str, PT(M8, q, 3))) == sorted(map(str, M8)) for q in range(3)))

# ---------- T: transported premises ----------
r = sp.symbols("r1:4", real=True)
f_ = sp.symbols("f1:4", real=True)
rho = rho1(r)
eff = (s0 * sp.Symbol("f0", real=True) + f_[0] * sx + f_[1] * sy + f_[2] * sz)
SIG = sp.Matrix(4, 4, lambda i, j: sp.Symbol(f"s{i}{j}"))
ok_t1 = ok_t2 = True
for t in (0, 1):
    for p in PAIRS:
        i, j = p
        k = [c for c in range(3) if c not in p][0]
        g = place(PT(SIG, 1, 2) if t else SIG, p, rho)
        # T1: marginal on the matching pair, and on each other pair
        for q in PAIRS:
            marg = ptrace_keep(g, list(q))
            if q == p:
                want = (PT(SIG, 1, 2) if t else SIG) * rho.trace()
                ok_t1 &= zero(marg - want)
            else:
                m0 = ptrace_keep(marg, [0], 2)
                m1 = ptrace_keep(marg, [1], 2)
                tot = marg.trace()
                ok_t1 &= zero(marg * tot - kron(m0, m1))
        # T2: conditioning copy k on an effect: matching pair -> multiple of PT^t(sigma)
        cond = contract(g, k, eff)
        want = (PT(SIG, 1, 2) if t else SIG) * (eff * rho).trace()
        ok_t2 &= zero(cond - want)
        # conditioning a copy of the pair on an effect -> product (one-copy operator (x) rho)
        for q in p:
            condq = contract(g, q, eff)
            other = [c for c in p if c != q][0]
            # condq lives on the remaining two copies in increasing order; it must be (x)-product
            kept = sorted([other, k])
            m0 = ptrace_keep(condq, [0], 2)
            m1 = ptrace_keep(condq, [1], 2)
            tot = condq.trace()
            ok_t2 &= zero(condq * tot - kron(m0, m1))
check("T1 every generator's pair marginals lie in that pair's cone: PT^t(sigma) on the matching pair, a product of "
      "one-copy marginals on the others (symbolic, both twists, all pairs)", ok_t1)
check("T2 conditioning on an effect: the matching pair gives a multiple of PT^t(sigma), a copy of the pair gives a "
      "product (symbolic)", ok_t2)

# T3 done as a direct factorization identity on pure tensor effects (cleaner than the generic contraction above):
ok_t3 = True
e_a = sp.Matrix(2, 2, lambda u, v: sp.Symbol(f"ea{u}{v}"))
e_b = sp.Matrix(2, 2, lambda u, v: sp.Symbol(f"eb{u}{v}"))
for t in (0, 1):
    for p in PAIRS:
        g = place(PT(SIG, 1, 2) if t else SIG, p, rho)
        k = [c for c in range(3) if c not in p][0]
        for q in PAIRS:
            if q == p:
                continue
            c_ = [c for c in range(3) if c not in q][0]
            Eq = sp.Matrix(4, 4, lambda u, v: sp.Symbol(f"e{u}{v}"))
            val = (place(Eq, q, eff) * g).trace()
            # factorization: val = tr_s[ A . B ] with A = E contracted on its non-shared copy with that copy's state
            # in g, and B = g's pair operator contracted on its non-shared copy with eff (one-copy operators on s)
            s = [c for c in q if c in p][0]
            xq = [c for c in q if c != s][0]          # copy of q not in p  (= k)
            yp = [c for c in p if c != s][0]          # copy of p not in q  (= c_)
            # E as an operator on copies (q[0], q[1]); contract copy xq with rho (the state g carries on k = xq)
            Eop = place(Eq, q, sp.eye(2)) / 2         # Eq (x) 1 on c_, normalized by tr 1 = 2
            Acon = ptrace_keep(contract(Eop, xq, rho), [sorted([c for c in range(3) if c != xq]).index(s)], 2)
            Acon = Acon  # one-copy operator on s
            gp = ptrace_keep(g, list(p))              # PT^t(sigma) on (p[0], p[1])
            Bcon = contract(place(gp, p, sp.eye(2)) / 2, yp, eff)
            Bcon = ptrace_keep(Bcon, [sorted([c for c in range(3) if c != yp]).index(s)], 2)
            ok_t3 &= sp.expand(val - (Acon * Bcon).trace()) == 0
check("T3 COMP-1 on pair|single, mismatched generators: <E (x) f, g> = tr(E_rho . sigma_f) with one-copy operators "
      "E_rho (E contracted with the state g carries) and sigma_f (g's pair operator contracted with f) (symbolic)", ok_t3)


def rat_unitary(seed):
    rnd = random.Random(seed)
    Hm = sp.Matrix(2, 2, lambda u, v: 0)
    a_, b_, c_, d_ = [sp.Rational(rnd.randint(-5, 5), rnd.randint(1, 4)) for _ in range(4)]
    Hm = sp.Matrix([[a_, b_ + I * c_], [b_ - I * c_, d_]])
    return ((sp.eye(2) - I * Hm) * (sp.eye(2) + I * Hm).inv()).applyfunc(sp.simplify)   # Cayley: unitary


U0, U1, U2 = rat_unitary(1), rat_unitary(2), rat_unitary(3)
check("T4 control: the three Cayley transforms are exactly unitary",
      all(zero(U * U.H - sp.eye(2)) for U in (U0, U1, U2)))
Ul = kron(U0, U1, U2)
ok_t4 = True
Us = [U0, U1, U2]
for t in (0, 1):
    for p in PAIRS:
        i, j = p
        k = [c for c in range(3) if c not in p][0]
        g = place(PT(SIG, 1, 2) if t else SIG, p, rho)
        lhs = Ul * g * Ul.H
        Uj = Us[j].conjugate() if t else Us[j]
        sig2 = kron(Us[i], Uj) * SIG * kron(Us[i], Uj).H
        rhs = place(PT(sig2, 1, 2) if t else sig2, p, Us[k] * rho * Us[k].H)
        ok_t4 &= zero(lhs - rhs)
check("T4 IE1: (U (x) V (x) X) maps the generator family of each pair onto itself, PT_j intertwining U_j with conj "
      "U_j (symbolic sigma, rho; exact rational unitaries)", ok_t4)

ok_t5 = True
for t in (0, 1):
    for p in PAIRS:
        g = place(PT(SIG, 1, 2) if t else SIG, p, rho)
        for q in range(3):
            img = PT(g, q, 3)
            k = [c for c in range(3) if c not in p][0]
            if q in p:
                # flip of this pair's twist bit: PT_q(PT_j^t sigma) = PT_j^{1-t}(T_q' sigma) with T_q' a transpose
                # that keeps sigma PSD; check the image is PT_j^{1-t} of (PT_{both} sigma) placed on p
                both = PT(PT(SIG, 0, 2), 1, 2)               # full transpose of the pair operator
                cand = place(PT(both, 1, 2) if (1 - t) else both, p, rho) if q == p[0] else \
                    place(PT(SIG, 1, 2) if (1 - t) else SIG, p, rho)
                ok_t5 &= zero(img - cand)
            else:
                ok_t5 &= zero(img - place(PT(SIG, 1, 2) if t else SIG, p, rho.T))
check("T5 per-token chart: PT on copy q flips the twist bit of each pair containing q (image = PT_j^(1-t) of a "
      "transpose of sigma, still PSD) and transposes the state of a copy outside the pair (symbolic)", ok_t5)
ok_t6 = True
for tau in itertools.product((0, 1), repeat=3):
    tdict = dict(zip(PAIRS, tau))
    solvable = any(all((tdict[(i, j)] + e[i] + e[j]) % 2 == 0 for (i, j) in PAIRS)
                   for e in itertools.product((0, 1), repeat=3))
    ok_t6 &= solvable == (sum(tau) % 2 == 0)
check("T6 a per-token chart presenting all three pairs as Q exists iff t01 + t02 + t12 is even (all 8 tau); "
      "M_odd = K_(0,1,0) and M_tw = K_(1,1,1) have none, M_bs = K_(0,0,0) has the trivial one", ok_t6)

# ---------- G: IE2 fails ----------
def ket(s):
    v = sp.zeros(2 ** len(s), 1)
    v[int(s, 2)] = 1
    return v


plus = (ket("0") + ket("1")) / sp.sqrt(2)
phip = (ket("00") + ket("11")) / sp.sqrt(2)
omega0 = place(phip * phip.T, (1, 2), plus * plus.T)
check("G1 omega0 = |+><+|_0 (x) Phi+_(1,2) is the generator 'Phi+ on (1,2) times |+> on 0' (Kronecker form)",
      zero(omega0 - kron(plus * plus.T, phip * phip.T)))
CNOT = sp.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
C01 = kron(CNOT, s0)
out = C01 * omega0 * C01.H
ghzp = (ket("000") + ket("011") + ket("101") + ket("110")) / 2
check("G2 (CNOT_(0,1) (x) 1) omega0 (CNOT (x) 1)^dag = |GHZ'><GHZ'| exactly", zero(out - ghzp * ghzp.T))
Wp = sp.eye(8) / 2 - ghzp * ghzp.T
check("G3 W' = 1/2 - |GHZ'><GHZ'| has value tr(W' GHZ') = -1/2", sp.simplify((Wp * ghzp * ghzp.T).trace()) == sp.Rational(-1, 2))
check("G3 input of the written bound: every one-copy marginal of GHZ' is 1/2",
      all(zero(ptrace_keep(ghzp * ghzp.T, [q]) - s0 / 2) for q in range(3)))
check("G3 control: CNOT maps the pair cone Q onto itself (unitary conjugation); t01 = 0 in M_odd and M_bs",
      zero(CNOT * CNOT.H - sp.eye(4)))

# exact spot checks on random exact generators of all 8 K_tau (spot checks; the written bound covers all)
rnd = random.Random(11)


def rand_state2():
    v = sp.Matrix([sp.Rational(rnd.randint(-4, 4), 1) + I * sp.Rational(rnd.randint(-4, 4), 1) for _ in range(4)])
    w = sp.Matrix([sp.Rational(rnd.randint(-4, 4), 1) + I * sp.Rational(rnd.randint(-4, 4), 1) for _ in range(4)])
    S = v * v.H + w * w.H
    return S / S.trace()


def rand_state1():
    while True:
        z = [sp.Rational(rnd.randint(-5, 5), 5) for _ in range(3)]
        if sum(c * c for c in z) <= 1:
            return rho1(z)


ok_spot = True
mins = []
for tau in itertools.product((0, 1), repeat=3):
    tdict = dict(zip(PAIRS, tau))
    for p in PAIRS:
        for _ in range(2):
            sig = rand_state2()
            g = place(PT(sig, 1, 2) if tdict[p] else sig, p, rand_state1())
            v1 = sp.nsimplify((Wp * g).trace())
            mins.append(v1)
            ok_spot &= v1 >= 0
check(f"G3 spot check: W' >= 0 on {len(mins)} random exact generators across all 8 K_tau (min {min(mins)})", ok_spot)

# X_rho is PSD and the HS bound holds on the symbolic family: tr_k[(1 (x) rho) GHZ'] has trace 1/2 for every state rho
ok_x = True
for k in range(3):
    Xr = contract(ghzp * ghzp.T, k, rho)
    ok_x &= sp.simplify(Xr.trace() - rho.trace() / 2) == 0
check("G3 tr X_rho = tr(rho psi_k) = 1/2 for every one-copy state rho and every copy k (symbolic)", ok_x)

# G4: M_tw through the chart PT_1 (flips the bits of pairs (0,1) and (1,2): (0,1,0) -> (1,1,1))
Wtw = PT(Wp, 1, 3)
ghz_tw = PT(ghzp * ghzp.T, 1, 3)
check("G4 M_tw: PT_1 maps M_odd onto M_tw (T5) and GHZ' to PT_1(GHZ'), with PT_1(W') of value -1/2 on it",
      sp.simplify((Wtw * ghz_tw).trace()) == sp.Rational(-1, 2))
cnotp = lambda M: PT(kron(CNOT, s0) * PT(M, 1, 3) * kron(CNOT, s0).H, 1, 3)
check("G4 the twisted pair interaction cnot' = PT_1 . Ad CNOT . PT_1 idly extended sends PT_1(omega0) (a generator of "
      "M_tw) to PT_1(GHZ'), outside M_tw", zero(cnotp(PT(omega0, 1, 3)) - ghz_tw))

# ---------- B: M_bs has no chart for the triple ----------
ghz = (ket("000") + ket("111")) / sp.sqrt(2)
Wg = sp.eye(8) / 2 - ghz * ghz.T
check("B1 W_GHZ has value -1/2 on GHZ, GHZ is PSD (rank one), every one-copy marginal of GHZ is 1/2",
      sp.simplify((Wg * ghz * ghz.T).trace()) == sp.Rational(-1, 2)
      and all(zero(ptrace_keep(ghz * ghz.T, [q]) - s0 / 2) for q in range(3)))
ok_spot2 = True
vals2 = []
for tau in itertools.product((0, 1), repeat=3):
    tdict = dict(zip(PAIRS, tau))
    for p in PAIRS:
        sig = rand_state2()
        g = place(PT(sig, 1, 2) if tdict[p] else sig, p, rand_state1())
        v2 = sp.nsimplify((Wg * g).trace())
        vals2.append(v2)
        ok_spot2 &= v2 >= 0
check(f"B1 spot check: W_GHZ >= 0 on {len(vals2)} random exact generators across all 8 K_tau (min {min(vals2)})",
      ok_spot2)

# ---------- H: the all-twisted hull contains W_GHZ (EQ2-A a4b construction, re-implemented) ----------
psim = (ket("01") - ket("10")) / sp.sqrt(2)
psip = (ket("01") + ket("10")) / sp.sqrt(2)
Psim = psim * psim.T
Psip = psip * psip.T
Sg = sp.diag(1, I)
Psim_rot = kron(s0, Sg) * Psim * kron(s0, Sg).H
corr = sp.Matrix(3, 3, lambda u, v: (Psim_rot * kron([sx, sy, sz][u], [sx, sy, sz][v])).trace())
check(f"H0 Psi-_rot = (1 (x) S) Psi- (1 (x) S)^dag has correlation matrix {corr.tolist()}",
      corr == sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, -1]]))
plusi = (ket("0") + I * ket("1")) / sp.sqrt(2)
gens_ok = True
Msum = sp.zeros(8, 8)
for p in PAIRS:
    for sig, st in ((Psim, plus * plus.H), (Psim_rot, plusi * plusi.H), ((Psim + Psip) / 2, s0 / 2)):
        gens_ok &= sp.simplify(sig.trace()) == 1 and all(ev >= 0 for ev in sig.eigenvals())
        Msum += place(PT(sig, 1, 2), p, st)
Mh = Msum / 9
check("H1 the nine ingredients are PT_j(sigma) (x) rho with sigma PSD of trace 1 and rho a state", gens_ok)
stabs = [(1, "III"), (1, "ZZI"), (1, "IZZ"), (1, "ZIZ"), (1, "XXX"), (-1, "YYX"), (-1, "XYY"), (-1, "YXY")]
Smats = [sgn * kron(*[PAULI[c] for c in w]) for sgn, w in stabs]
check("H2 the 8 GHZ stabilizers commute, square to 1 and fix GHZ",
      all(zero(A * B - B * A) for A in Smats for B in Smats) and all(zero(A * A - sp.eye(8)) for A in Smats)
      and all(zero(A * ghz - ghz) for A in Smats))
tw = sum((A * Mh * A.H for A in Smats), sp.zeros(8, 8)) / 8
check("H3 twirl((1/9) sum_p (alpha_p + beta_p + delta_p)) = W_GHZ / 3 exactly, so W_GHZ is in B_tw "
      "(local Pauli conjugations preserve every generator family, T4)", zero(tw - Wg / 3))
Msum2 = sp.zeros(8, 8)
for p in PAIRS:
    for sig, st in ((Psim, plus * plus.H), ((Psim + Psip) / 2, s0 / 2)):
        Msum2 += place(PT(sig, 1, 2), p, st)
tw2 = sum((A * (Msum2 / 6) * A.H for A in Smats), sp.zeros(8, 8)) / 8
lin_dep = sp.Matrix([list(tw2), list(Wg)]).rank() == 1
check("H4 countercontrol: without the beta family the twirl is not a multiple of W_GHZ", not lin_dep)
check("H5 W_GHZ is not PSD (eigenvalue -1/2) and lies in B_tw* by the bound of B1 (B_tw = K_(1,1,1))",
      sp.Rational(-1, 2) in Wg.eigenvals())

npass = sum(1 for _, c in checks if c)
print(f"review_eq2a_cm: {npass}/{len(checks)} checks pass")
if npass == len(checks):
    print("VERDICT COUNTERMODELS-CONFIRMED: K_(0,1,0), K_(1,1,1), K_(0,0,0) satisfy the transported premises checked "
          "here and violate IE2; the odd-parity models have no per-token chart; K_(0,0,0) excludes GHZ; the "
          "all-twisted hull contains W_GHZ")
else:
    print("VERDICT NOT RENDERED")
sys.exit(0 if npass == len(checks) else 1)
