"""EQ4-SIX exploration y1 -- FLOATING POINT, EXPLORATION ONLY.  NOT EVIDENCE.  Never cited as a certificate.

Question (lead only).  Lift(K_A) = closed cone of all local-filter images Ad(A (x) B (x) C) g of the generators g of K_A.
Lift(K_A) is self-positive iff tr(g Ad(k) g') >= 0 for all k in GL(2,C)^3 and all generator pairs.  Pairs with a W3-type
or a pair-sum generator are settled by written arguments (W3 in Z, every generator in Z* and BS*).  The remaining
orbit types are kappa' = 1/2 - P0 + P1 (same fibre) and omega = 1/2 - P0 + P2 (different fibre).
Method: (1) random starts + BFGS on the normalized value; (2) at the tight points (value 0 at an LU), the gradient and
the Hessian of the unnormalized value over the 48 real filter parameters (finite differences): a negative Hessian
eigenvalue in a direction off the scaling orbit would be a lead for a violation.
"""
import itertools
import sys

import numpy as np
from scipy.optimize import minimize

rng = np.random.default_rng(2026100901)


def idx(x, y, z):
    return 4 * x + 2 * y + z


P = []
for b in range(4):
    b1, b2 = b >> 1, b & 1
    for t in range(2):
        v = np.zeros(8)
        v[idx(0, b1, b2)] = 1
        v[idx(1, 1 - b1, 1 - b2)] = 1 if t == 0 else -1
        P.append(np.outer(v, v) / 2)
I8 = np.eye(8)
KAP = 0.5 * I8 - P[0] + P[1]
OME = 0.5 * I8 - P[0] + P[2]
W3 = 0.5 * I8 - P[0]


def gl2(p):
    return (p[0:4] + 1j * p[4:8]).reshape(2, 2)


def kmat(p):
    return np.kron(np.kron(gl2(p[0:8]), gl2(p[8:16])), gl2(p[16:24]))


def raw(p, g, gp):
    k = kmat(p)
    return np.real(np.trace(gp @ k @ g @ k.conj().T))


def val(p, g, gp):
    k = kmat(p)
    Y = k @ g @ k.conj().T
    return np.real(np.trace(gp @ Y)) / max(np.linalg.norm(gp) * np.linalg.norm(Y), 1e-300)


names = [("kappa'", KAP), ("omega", OME)]
for (n1, g1), (n2, g2) in itertools.product(names, names):
    best = np.inf
    for s in range(60):
        r = minimize(val, rng.normal(size=24), args=(g1, g2), method="BFGS",
                     options={"maxiter": 3000, "gtol": 1e-12})
        best = min(best, r.fun)
    print("min normalized tr(%s Ad(k) %s) over 60 starts = %.3e" % (n2, n1, best), flush=True)

# tight points: LU k with tr(g' Ad(k) g) = 0.  Search over the signed-permutation-like LUs generated by X, Z, S, H.
Xm = np.array([[0, 1], [1, 0]], dtype=complex)
Zm = np.array([[1, 0], [0, -1]], dtype=complex)
Sm = np.array([[1, 0], [0, 1j]], dtype=complex)
Hm = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
Id = np.eye(2, dtype=complex)
cliff = [Id]
frontier = [Id]
for _ in range(6):
    nf = []
    for U in frontier:
        for Gm in (Hm, Sm):
            V = Gm @ U
            if not any(np.allclose(V, W * ph) for W in cliff for ph in (1, -1, 1j, -1j)):
                cliff.append(V)
                nf.append(V)
    frontier = nf
print("one-qubit Clifford representatives (mod phase):", len(cliff), flush=True)


def params(A, B, C):
    out = []
    for M in (A, B, C):
        out += list(M.real.reshape(4)) + list(M.imag.reshape(4))
    return np.array(out)


def hessian(f, p0, h=1e-4):
    n = len(p0)
    H = np.zeros((n, n))
    f0 = f(p0)
    for i in range(n):
        for j in range(i, n):
            ei = np.zeros(n)
            ej = np.zeros(n)
            ei[i] = h
            ej[j] = h
            H[i, j] = (f(p0 + ei + ej) - f(p0 + ei - ej) - f(p0 - ei + ej) + f(p0 - ei - ej)) / (4 * h * h)
            H[j, i] = H[i, j]
    return H


for (n1, g1), (n2, g2) in itertools.product(names, names):
    tight = 0
    worst_eig = np.inf
    for A, B, C in itertools.product(cliff, repeat=3):
        p0 = params(A, B, C)
        v0 = raw(p0, g1, g2)
        if abs(v0) < 1e-9:
            tight += 1
            if tight <= 40:
                H = hessian(lambda p: raw(p, g1, g2), p0)
                ev = np.linalg.eigvalsh(H)
                worst_eig = min(worst_eig, ev[0])
    print("pair (%s, %s): Clifford tight points %d; min Hessian eigenvalue at the first <= 40: %.3e"
          % (n1, n2, tight, worst_eig), flush=True)
print("done", file=sys.stderr)
