"""EQ4-SIX exploration y9 -- FLOATING POINT, EXPLORATION ONLY.  NOT EVIDENCE.  Never cited as a certificate.

c = 1 (pairs twin, K3 = K3*, twin links SWAP/2; NOTES N1, s1 G).  K_tw = cone(G.(e0 + e1), G.t, G.kappa') with
t = (1,1,1,1,1,-1,1,-1), kappa' = (-1, 3, 1^6) in GHZ-basis coordinates (EQ4-P p13).
(1) Lift(K_tw) self-positivity: min over filters k of tr(g' Ad(k) g) / (|g'| |Ad(k) g|) for all generator types
    (all G-images enter through LU filters and token permutations; we use every generator as g' and the three
    orbit representatives as g).
(2) twin-link glue network (crossing split): states x, y, effects e, f all in Lift(K_tw) (K3* = K3, no T):
    N = tr[ Glue_e(e, f; SWAP_st/2) Glue_s(x, y; SWAP_pq/2) ].
Controls: PSD nodes give N >= 0? (no: c = 1 has no PSD triple; reported only); the twin theta value of two K_tw
generators is (1/8) tr(x y) >= 0.
"""
import itertools
import sys

import numpy as np
from scipy.optimize import minimize

rng = np.random.default_rng(2026100909)


def idx(x, y, z):
    return 4 * x + 2 * y + z


P = []
for b in range(4):
    b1, b2 = b >> 1, b & 1
    for t in range(2):
        v = np.zeros(8)
        v[idx(0, b1, b2)] = 1
        v[idx(1, 1 - b1, 1 - b2)] = 1 if t == 0 else -1
        P.append(np.outer(v, v) / 2)


def gd(vec):
    return sum(c * Pj for c, Pj in zip(vec, P))


# G as permutations of the 8 positions (generated by the seven generators of EQ4-P p11 H2)
gens = [(1, 0, 3, 2, 5, 4, 7, 6), (6, 7, 4, 5, 2, 3, 0, 1), (4, 5, 6, 7, 0, 1, 2, 3), (2, 3, 0, 1, 6, 7, 4, 5),
        (1, 0, 3, 2, 4, 5, 6, 7), (0, 1, 2, 3, 6, 7, 4, 5), (0, 1, 4, 5, 2, 3, 6, 7)]
group = {tuple(range(8))}
frontier = [tuple(range(8))]
while frontier:
    nf = []
    for g in frontier:
        for h in gens:
            c = tuple(g[h[i]] for i in range(8))
            if c not in group:
                group.add(c)
                nf.append(c)
    frontier = nf
print("|G| =", len(group), flush=True)


def orbit(vec):
    out = set()
    for g in group:
        out.add(tuple(vec[g[i]] for i in range(8)))
    return sorted(out)


p0 = (1, 1, 0, 0, 0, 0, 0, 0)
t0 = (1, 1, 1, 1, 1, -1, 1, -1)
k0 = (-1, 3, 1, 1, 1, 1, 1, 1)
GEN = orbit(p0) + orbit(t0) + orbit(k0)
print("K_tw generators:", len(GEN), flush=True)
REPS = {"pair": gd(p0), "t": gd(t0), "kappa'": gd(k0)}
GOPS = [gd(v) for v in GEN]


def gl2(p):
    return (p[0:4] + 1j * p[4:8]).reshape(2, 2)


def kmat(p):
    return np.kron(np.kron(gl2(p[0:8]), gl2(p[8:16])), gl2(p[16:24]))


def val(p, g, gp):
    k = kmat(p)
    Y = k @ g @ k.conj().T
    return np.real(np.trace(gp @ Y)) / max(np.linalg.norm(gp) * np.linalg.norm(Y), 1e-300)


worst = (np.inf, None)
for (nm, g) in REPS.items():
    for j, gp in enumerate(GOPS):
        best = np.inf
        for _ in range(3):
            r = minimize(val, rng.normal(size=24), args=(g, gp), method="BFGS", options={"maxiter": 3000, "gtol": 1e-11})
            best = min(best, r.fun)
        if best < worst[0]:
            worst = (best, (nm, GEN[j]))
print("(1) Lift(K_tw) self-positivity: worst normalized min tr(g' Ad(k) g) = %.3e at %s" % worst, flush=True)


def t6(M):
    return M.reshape(2, 2, 2, 2, 2, 2)


SW = np.zeros((2, 2, 2, 2))
for a in range(2):
    for b in range(2):
        SW[a, b, b, a] = 0.5   # SWAP/2 [ket p, ket q; bra p, bra q]


def net_twin(x, y, e, f):
    # Glue_s[r1 r2 u1 u2; r1' r2' u1' u2'] = sum SW[p q; p' q'] x[p' r1 r2; p r1' r2'] y[q' u1 u2; q u1' u2']
    gs = np.einsum("pqPQ,PabpAB,QcdqCD->abcdABCD", SW, t6(x), t6(y))      # (r1 r2 u1 u2; ...)
    ge = np.einsum("stST,SacsAC,TbdtBD->acbdACBD", SW, t6(e), t6(f))      # (r1 u1 r2 u2; ...)
    ge = np.transpose(ge, (0, 2, 1, 3, 4, 6, 5, 7))                       # -> (r1 r2 u1 u2; ...)
    return np.real(np.einsum("abcdABCD,ABCDabcd->", ge, gs))


def gval(p, gs):
    nodes = [kmat(p[24 * i:24 * i + 24]) @ gs[i] @ kmat(p[24 * i:24 * i + 24]).conj().T for i in range(4)]
    return net_twin(*nodes) / np.prod([np.linalg.norm(X) for X in nodes])


worst = (np.inf, None)
for trial in range(120):
    ii = rng.integers(len(GOPS), size=4)
    gs = [GOPS[i] for i in ii]
    r = minimize(gval, rng.normal(size=96), args=(gs,), method="L-BFGS-B", options={"maxiter": 400})
    if r.fun < worst[0]:
        worst = (r.fun, tuple(GEN[i] for i in ii))
    if trial % 40 == 39:
        print("(2) after %d trials: worst normalized twin glue network min %.3e" % (trial + 1, worst[0]), flush=True)
print("(2) worst configuration:", worst[1], flush=True)
print("done", file=sys.stderr)
