"""K2C P4 -- the Lie algebra of the closure of the generated group, in DIM-1 coordinates (kernel objects only).

The group G = < cnot, actT R, actC R : R in SO(3) > contains the one-parameter groups actT exp(tL), actC exp(tL)
(L in so(3)) and their cnot-conjugates, so the Lie algebra of its closure contains the Lie algebra generated by the
infinitesimal local generators and is Ad(cnot)-stable.  Infinitesimal generators on vec(w) (index 4 mu + nu):
  X_T(L) = I4 (x) diag(0, L),  X_C(L) = diag(0, L) (x) I4.

Decision rule (fixed before running):
  dimension = LOWER bound from a closure computed over GF(p) (valid: integer generators, rank mod p <= rank over Q)
            + UPPER bound from an exact rational subspace shown closed under brackets and the conjugations used
              (case A, F), or from antisymmetry + annihilation of e00 (all cases: inside so(15), dim 105).
  A case's dimension is RENDERED only when lower = upper.
  Case A (local + cnot) expected by thread E P10: 15.  Countercontrols: B (local only) and C (local + actT nflip): 6.
  Case D (local + cnot + actT reflY), case E (local + T_refl): thread E P11 expects 105.
  Case F (local + cnot'): 15, a different subspace from A.
  Matrix-model identification [M]: A's subspace = span of the transfer generators of ad(iH), H traceless Pauli product.

Usage: python -I p4_group_lie.py <CompositeDimension.lean> <K2Guard.lean>
"""
import os
import sys
from fractions import Fraction
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from k2clib import *  # noqa
import numpy as np

CD, KG = sys.argv[1], sys.argv[2]
tabs = parse_tables(CD)
reflY = parse_diag_map(KG, 'reflY')
nflip = parse_diag_map(CD, 'nflip')
P = 1000003


def to_np(M):
    return np.array([[int(M[i, j]) for j in range(M.shape[1])] for i in range(M.shape[0])], dtype=np.int64)


Kc = to_np(cnot_mat(tabs))
RY = to_np(actT_mat(reflY))
NT = to_np(actT_mat(nflip))
TR = RY @ Kc                      # T_refl = actT reflY . cnot ;  inverse = cnot . actT reflY
TRi = Kc @ RY
CP = RY @ Kc @ RY                 # cnot'
so3 = [sp.Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]]), sp.Matrix([[0, 0, 1], [0, 0, 0], [-1, 0, 0]]),
       sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])]


def d0(L):
    H = sp.zeros(4, 4)
    H[1:, 1:] = L
    return H


I4 = sp.eye(4)
LOCAL = [to_np(kron(I4, d0(L))) for L in so3] + [to_np(kron(d0(L), I4)) for L in so3]


def closure_modp(gens, conj):
    """Lie closure over GF(p) of span(gens), also stable under X -> A X A^{-1} for (A, Ainv) in conj."""
    basis, piv = [], []          # reduced rows (np int64 length 256), pivot indices

    def reduce(v):
        v = v % P
        for b, pi in zip(basis, piv):
            if v[pi]:
                v = (v - v[pi] * b) % P
        return v

    def add(M):
        v = reduce(M.reshape(-1))
        nz = np.nonzero(v)[0]
        if len(nz) == 0:
            return False
        pi = nz[0]
        inv = pow(int(v[pi]), P - 2, P)
        v = (v * inv) % P
        for k in range(len(basis)):
            if basis[k][pi]:
                basis[k] = (basis[k] - basis[k][pi] * v) % P
        basis.append(v)
        piv.append(pi)
        return True

    queue = []
    for g in gens:
        if add(g):
            queue.append(g % P)
    elems = list(queue)
    i = 0
    while i < len(elems):
        X = elems[i]
        new = []
        for (A, Ai) in conj:
            new.append((A @ X @ Ai) % P)
        for Y in elems[:i + 1]:
            new.append((X @ Y - Y @ X) % P)
        for Z in new:
            if add(Z):
                elems.append(Z % P)
        i += 1
    return len(basis)


def antisym_e00(gens, conj):
    ok = all((g == -g.T).all() and not g[0].any() and not g[:, 0].any() for g in gens)
    ok = ok and all((A @ A.T == np.eye(16, dtype=np.int64)).all() and A[0, 0] == 1 and not A[0, 1:].any() for (A, _) in conj)
    return ok


cases = {
    'A local + cnot': ([], [(Kc, Kc)]),
    'B local only': ([], []),
    'C local + actT nflip': ([], [(NT, NT)]),
    'D local + cnot + actT reflY': ([], [(Kc, Kc), (RY, RY)]),
    'E local + T_refl': ([], [(TR, TRi)]),
    "F local + cnot'": ([], [(CP, CP)]),
}
lower = {}
for name, (extra, conj) in cases.items():
    lower[name] = closure_modp(LOCAL + extra, conj)
    check('4.0 %s: generators antisymmetric, kill e00; conjugators orthogonal fixing e00 (so dim <= 105)' % name, antisym_e00(LOCAL, conj))
    print('     GF(p) closure dimension (lower bound) for %s = %d' % (name, lower[name]))


# exact rational upper bounds for A and F: an explicit 15-dim subspace closed under brackets and conjugation
def frac_basis(mats):
    rows, piv = [], []
    for M in mats:
        v = [Fraction(int(t)) if not isinstance(t, Fraction) else t for t in np.asarray(M).reshape(-1)]
        for r, pi in zip(rows, piv):
            if v[pi] != 0:
                c = v[pi]
                v = [a - c * b for a, b in zip(v, r)]
        nz = [k for k, t in enumerate(v) if t != 0]
        if not nz:
            continue
        pi = nz[0]
        c = v[pi]
        v = [t / c for t in v]
        for k in range(len(rows)):
            if rows[k][pi] != 0:
                cc = rows[k][pi]
                rows[k] = [a - cc * b for a, b in zip(rows[k], v)]
        rows.append(v)
        piv.append(pi)
    return rows, piv


def in_span(rows, piv, M):
    v = [Fraction(int(t)) for t in np.asarray(M).reshape(-1)]
    for r, pi in zip(rows, piv):
        if v[pi] != 0:
            c = v[pi]
            v = [a - c * b for a, b in zip(v, r)]
    return all(t == 0 for t in v)


# [M] transfer generators of ad(iH): G_H[(mu nu),(ka la)] = Tr(s_mu nu (-i)[H, s_ka la]) / 4
paulis2 = [(m, v) for m in range(4) for v in range(4) if (m, v) != (0, 0)]
GH = []
for (m, v) in paulis2:
    H = kron(PAULI[m], PAULI[v])
    M = sp.zeros(16, 16)
    for (a, b) in [(i, j) for i in range(4) for j in range(4)]:
        for (k, l) in [(i, j) for i in range(4) for j in range(4)]:
            Sk = kron(PAULI[k], PAULI[l])
            M[4 * a + b, 4 * k + l] = sp.expand((kron(PAULI[a], PAULI[b]) * (-sp.I) * (H * Sk - Sk * H)).trace() / 4)
    GH.append(to_np(M))
rowsA, pivA = frac_basis(GH)
check('4.1a [M] the 15 transfer generators of ad(i su(4)) are linearly independent (exact)', len(rowsA) == 15)
check('4.1b the six local generators lie in that span (exact)', all(in_span(rowsA, pivA, g) for g in LOCAL))
check('4.1c the span is stable under Ad(cnot) (exact)', all(in_span(rowsA, pivA, Kc @ g @ Kc) for g in GH))
check('4.1d the span is closed under brackets (exact, 105 brackets)',
      all(in_span(rowsA, pivA, GH[i] @ GH[j] - GH[j] @ GH[i]) for i in range(15) for j in range(i + 1, 15)))
check('4.1e case A rendered: lower bound 15 = exact upper bound 15', lower['A local + cnot'] == 15)
GHp = [RY @ g @ RY for g in GH]
rowsF, pivF = frac_basis(GHp)
check("4.2a case F: PT_B-conjugate span contains the local generators, is Ad(cnot')-stable and bracket-closed",
      all(in_span(rowsF, pivF, g) for g in LOCAL) and all(in_span(rowsF, pivF, CP @ g @ CP) for g in GHp)
      and all(in_span(rowsF, pivF, GHp[i] @ GHp[j] - GHp[j] @ GHp[i]) for i in range(15) for j in range(i + 1, 15)))
check("4.2b case F rendered: 15, and its span differs from A's (A + F spans more than 15)",
      lower["F local + cnot'"] == 15 and len(frac_basis(GH + GHp)[0]) > 15, len(frac_basis(GH + GHp)[0]))
check('4.3 countercontrols B, C rendered at 6 (local algebra so(3)+so(3); a finite local gate adds nothing)',
      lower['B local only'] == 6 and lower['C local + actT nflip'] == 6)
check('4.4 cases D, E rendered at 105 = so(15) (lower bound meets the antisymmetry bound)',
      lower['D local + cnot + actT reflY'] == 105 and lower['E local + T_refl'] == 105)
# Ad(CNOT) inside Ad(SU(4)): det(e^{i pi/4} CNOT) = 1
CN = sp.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
check('4.5 [M] det CNOT = -1 and det(e^{i pi/4} CNOT) = e^{i pi} (-1) = 1, so Ad(CNOT) is in Ad(SU(4))',
      CN.det() == -1 and sp.simplify(sp.exp(sp.I * sp.pi / 4) ** 4 * CN.det()) == 1)

nf = summary()
print('VERDICT P4:', 'LIE-DIMENSIONS-RENDERED' if nf == 0 else 'NOT RENDERED')
sys.exit(nf)
