"""A33 research: F cap K as a subspace of K = F2^9 (circle subsets), against the cut and cycle
spaces of the incidence graph K33; and a search for a complement of K in G."""
import pickle, itertools
d = pickle.load(open('finite.pkl', 'rb')); pts, lab, G = d['pts'], d['lab'], d['iso']
a = pickle.load(open('analyse.pkl', 'rb')); cp, K, V, ends, circ, single = a['cp'], a['K'], a['V'], a['ends'], a['circ'], a['single']
fam = pickle.load(open('family.pkl', 'rb'))['fam']; F = set(fam)
n = len(pts); N = 9; ident = tuple(range(n))
def mul(p, q): return tuple(p[q[x]] for x in range(n))
def vec(k):   # which circles k conjugates (moves the circle's two non-V points)
    return frozenset(r for r in range(N) if k[min(set(circ[r]) - set(V))] != min(set(circ[r]) - set(V)))
Kv = {vec(k): k for k in K}
FK = {vec(k) for k in K if k in F}
cuts = set()
for m in range(1 << len(V)):
    S = {V[i] for i in range(len(V)) if m >> i & 1}
    cuts.add(frozenset(r for r, (x, y) in enumerate(ends) if (x in S) != (y in S)))
print('|F cap K| =', len(FK), ' |cut space| =', len(cuts), ' F cap K == cut space:', FK == cuts)
# cycle space = orthogonal complement of the cut space in F2^9
def dot(A, B): return len(A & B) % 2
allsets = [frozenset(r for r in range(N) if m >> r & 1) for m in range(1 << N)]
cyc = {A for A in allsets if all(dot(A, C) == 0 for C in cuts)}
print('|cycle space| =', len(cyc))
# A32's witness: conjugation of the Fourier circle alone (circle 0) -- its class mod the cuts
print("A32's one-circle conjugation lies in F:", single[0] in F, ' (a cut would; a single edge is not a cut)')
# complement search: order-3, order-2 generators of G_circle lifted into G
Gc = {}
for p in G: Gc.setdefault(cp[p], []).append(p)
def cyc_order(c):
    o, x = 1, c
    while x != tuple(range(N)):
        x = tuple(c[x[i]] for i in range(N)); o += 1
    return o
def order(p):
    o, x = 1, p
    while x != ident: x = mul(p, x); o += 1
    return o
def generate(gens, cap=100):
    S = {ident}; fr = [ident]
    while fr:
        new = []
        for x in fr:
            for g in gens:
                y = mul(g, x)
                if y not in S:
                    S.add(y); new.append(y)
                    if len(S) > cap: return None
        fr = new
    return S
# pick generators of G_circle: find two circle permutations generating all 72
Cs = list(Gc)
def cgen(gens):
    S = {tuple(range(N))}; fr = list(S)
    while fr:
        new = []
        for x in fr:
            for g in gens:
                y = tuple(g[x[i]] for i in range(N))
                if y not in S: S.add(y); new.append(y)
        fr = new
    return S
gens = None
for c1 in Cs:
    for c2 in Cs:
        if len(cgen([c1, c2])) == 72:
            gens = (c1, c2); break
    if gens: break
o1, o2 = cyc_order(gens[0]), cyc_order(gens[1])
print('G_circle generated by two elements of orders', o1, o2)
L1 = [p for p in Gc[gens[0]] if order(p) == o1]
L2 = [p for p in Gc[gens[1]] if order(p) == o2]
print('order-preserving lifts:', len(L1), len(L2))
found = None
for x in L1:
    for y in L2:
        H = generate([x, y], cap=72)
        if H is not None and len(H) == 72 and not (H & set(K)) - {ident}:
            found = H; break
    if found: break
print('complement of K found (G = K x| H):', bool(found))
if found:
    print('complement inside the family F:', found <= F)
