"""A33 research: act 25's four-shape family (576 relabelling pairs x 4 shapes) acting on P, computed
from tuples through the landed definitions (relabel, entrywise star, FibreGram of the transposed
dilation), then located in derivation B's group."""
import pickle, itertools
from circles import MS, R, IDX, N
d = pickle.load(open('finite.pkl', 'rb')); pts, lab, G = d['pts'], d['lab'], d['iso']
a = pickle.load(open('analyse.pkl', 'rb')); cp, K = a['cp'], a['K']
n = len(pts); Gs = set(G); where = {x: i for i, x in enumerate(pts)}
IP = [(1, 0), (0, 1), (-1, 0), (0, -1)]
def gmul(x, y): return (x[0] * y[0] - x[1] * y[1], x[0] * y[1] + x[1] * y[0])
def gconj(x): return (x[0], -x[1])
def Mw(k):  # M(i^k) as Gaussian integers; times 1/2 gives U
    return [[(s * IP[(k * e) % 4][0], s * IP[(k * e) % 4][1]) for (s, e) in row] for row in MS]
def dilation(r, k):  # U'[i][j] = M[r1 i][r2 j] (times 1/2), FibreGram U' = circle r at w = i^k
    r1, r2 = R[r]; M = Mw(k)
    return [[M[r1[i]][r2[j]] for j in range(4)] for i in range(4)]
def gram_of(U):      # G[i][j][k] = conj(U[i][j]) U[i][k]  (times 1/4)
    return [[[gmul(gconj(U[i][j]), U[i][l]) for l in range(4)] for j in range(4)] for i in range(4)]
def relabel(Gt, pi, tau):
    return [[[Gt[pi[i]][tau[j]][tau[l]] for l in range(4)] for j in range(4)] for i in range(4)]
def star(Gt):
    return [[[gconj(v) for v in row] for row in m] for m in Gt]
def feature(Gt):     # times 64
    out = []
    for (i1, i2, i3), (j1, j2, j3) in IDX:
        v = gmul(gmul(Gt[i1][j1][j2], Gt[i2][j2][j3]), Gt[i3][j3][j1]); out.append(v)
    return tuple(out)
# sanity: feature of the canonical gram is the P point
assert all(feature(gram_of(dilation(r, k))) == pts[lab[r, k]] for r in range(N) for k in range(4))
S4 = list(itertools.permutations(range(4)))
def action(shape, pi, tau):
    img = [None] * n
    for (r, k), x in lab.items():
        U = dilation(r, k)
        if shape in (0, 1):
            Gt = relabel(gram_of(U), pi, tau)
        else:
            UT = [[U[j][i] for j in range(4)] for i in range(4)]
            Gt = relabel(gram_of(UT), pi, tau)
        if shape in (1, 3):
            Gt = star(Gt)
        y = where.get(feature(Gt))
        if y is None:
            return None
        if img[x] is not None and img[x] != y:
            return 'ill-defined'
        img[x] = y
    return tuple(img)
fam = {}
bad = 0
for shape in range(4):
    for pi in S4:
        for tau in S4:
            p = action(shape, pi, tau)
            if not isinstance(p, tuple):
                bad += 1; continue
            fam.setdefault(p, []).append((shape, pi, tau))
print('family members acting on P:', 4 * 576 - bad, ' failures:', bad)
F = set(fam)
print('distinct actions of the family on P:', len(F), ' all in G:', F <= Gs)
ident = tuple(range(n))
def mul(p, q): return tuple(p[q[x]] for x in range(n))
def generate(gens):
    S = {ident}; frontier = [ident]
    while frontier:
        new = []
        for x in frontier:
            for g in gens:
                y = mul(g, x)
                if y not in S: S.add(y); new.append(y)
        frontier = new
    return S
H = generate(list(F))
print('subgroup generated by the family:', len(H), ' family closed (= that subgroup):', H == F)
print('index of the family in G:', len(G) // len(F), '(remainder', len(G) % len(F), ')')
print('family meets K in', len(F & set(K)), 'elements; circle action of the family:', len({cp[p] for p in F}))
pickle.dump({'fam': fam}, open('family.pkl', 'wb'))
