"""Split the green dev module into the stage-1 and stage-2 module texts, with the frozen header.

usage: python3 stage33.py <dev module .lean>   -> writes stage1.lean, stage2.lean beside it,
and prints controls.module_label for both plus the per-theorem audit of landed helpers that are
not on the preregistration's provenance list.
"""
import re, sys, importlib.util, subprocess
S = '/tmp/claude-0/-home-user-incompleteness/727ddb71-72ba-5388-a9a1-1413a0433ac0/scratchpad/a33/'
spec = importlib.util.spec_from_file_location('c33', S + 'controls.py'); C = importlib.util.module_from_spec(spec); spec.loader.exec_module(C)

DOC = '''/-!
# Act 33 — the isometry group of the normalized single-carrier space

At the single-carrier configuration of acts 24–26 (`Γ₀ ≡ ¼`, the ancilla `Fin 1`, act 24's
distance), this module classifies the surjective isometries of act 26's normalized space, the
union of the nine relabelled Fourier circles.

Every such map carries each circle onto a circle, acts on it by `w ↦ λ w` or `w ↦ λ w̄` with
`λ ∈ {1, −1}`, and is determined by the automorphism it induces on the incidence graph `K₃,₃` of
the six shared points together with nine conjugation bits; every such pair is realized. The
automorphisms are generated by three relabellings and the transpose, and the finite parts — the
72 automorphisms, the shape words of act 25's family and the parity patterns of the kernel — are
decided by the kernel.

The module carries no definition. Every theorem prints its axioms.
-/
'''

src = open(sys.argv[1], encoding='utf-8').read()
head_end = src.index('namespace OIBridge\n')
head = src[:head_end]
assert head.startswith(C.IMPORT)
body = src[head_end:]
new_head = C.IMPORT + '\n' + DOC + '\n'

# cut the verdict and the corollary (each: theorem ... #print axioms NAME\n\n)
def cut(text, name):
    m = re.search(r'(?m)^theorem %s :\n' % re.escape(name), text)
    assert m, name
    e = re.search(r'(?m)^#print axioms %s\n\n' % re.escape(name), text[m.start():])
    assert e, name
    piece = text[m.start():m.start() + e.end()]
    return text[:m.start()] + text[m.start() + e.end():], piece

body1, verdict = cut(body, 'a33_classified')
body1, coroll = cut(body1, 'a33_c_exclusive')
tail = 'end OrbitIsometryGroup\nend OIBridge\n'
assert body1.endswith(tail)
stage1 = new_head + body1
stage2 = new_head + body1[:-len(tail)] + verdict + coroll + tail
open(S + 'stage1.lean', 'w', encoding='utf-8').write(stage1)
open(S + 'stage2.lean', 'w', encoding='utf-8').write(stage2)
for nm, txt in (('stage1', stage1), ('stage2', stage2)):
    lab, f = C.module_label(txt)
    print(nm, 'label', lab, 'findings', f, 'theorems', len(C.theorems(C.strip_comments(txt))))
    print(nm, 'blob', subprocess.run(['git', 'hash-object', S + nm + '.lean'], capture_output=True, text=True).stdout.strip())

# ---- audit of landed helpers off the provenance list, per theorem
F = 'd5126a3d61f78ab38e3cca0ee7f744ce645d7196'
files = subprocess.run(['git', 'ls-tree', '-r', '--name-only', F, 'verification/lean-mathlib/OIBridge/'], capture_output=True, text=True, cwd='/home/user/incompleteness').stdout.split()
names = {}
for p in files:
    s = subprocess.run(['git', 'show', F + ':' + p], capture_output=True, text=True, cwd='/home/user/incompleteness').stdout
    for m in re.finditer(r'(?m)^[ \t]*(?:@\[[^\]\n]*\][ \t]*)?(?:private[ \t]+|protected[ \t]+|noncomputable[ \t]+)*(?:theorem|lemma|def|abbrev)[ \t]+(\S+)', s):
        names.setdefault(m.group(1), p.split('/')[-1][:-5])
PROV = set("""FibreGram GramPhaseEquiv RealizableGram AdmissibleDilationAt sh1_necessity gramPhaseEquiv_refl gramPhaseEquiv_symm gramPhaseEquiv_trans realizable_of_gramPhaseEquiv hadamard_z_admissible mixedTriple mixedTriple_gauge mixedTriple_star dist_eq_norm_toLp coord_le_dist fourier_dist_le geo1_class_invariant geo1_equiv_of_zero_single iso1_single_carrier iso2_classes_single mixedTriple_relabel2 mixedTriple_transpose fibreGram_unique relabel2_isometry conj_isometry relabel2_realizable featureVec normalizedSet IsSurjIsometryOn featureVec_gauge gramPhaseEquiv_of_featureVec_eq featureVec_mem_normalizedSet relabelled_fourier_mem_normalizedSet normalizedSet_eq_iUnion bridge_of_tuple_isometry tuple_isometry_of_bridge eqOn_affineSpan_of_agree exists_affineIsometryEquiv_of_isSurjIsometryOn a26_0_affine_extension a26_1_circle_count rigid_motion_of_tuple_isometry a32_shared_fourier_star a32_shared_coord_inj a32_shared_fourier_inj a32_shared_pair a32_shared_classify a32_control_overlap a32_shared_exists a32_shared_isometry a32_shared_separation a32_shared_relabel a32_shared_star_mul_self a32_not_rigid""".split())
ORBIT = {'OrbitGeometryRigidity', 'OrbitGeometryIsometries', 'OrbitGeometrySelector', 'OrbitIsometryClassification', 'OrbitLawGaps', 'OrbitLawRigidityTwisted', 'GramTrajectorySelection', 'TwoSidedGauge'}
code = C.strip_comments(stage2)
blocks = re.split(r'(?m)^(?=theorem )', code)
by_helper = {}
for b in blocks:
    m = re.match(r'theorem (\S+)', b)
    if not m:
        continue
    thm = m.group(1)
    proof = b[b.index(':= by') + 5:] if ':= by' in b else b
    for ident in set(re.findall(r"(?<![A-Za-z0-9_'.])[A-Za-z_][A-Za-z0-9_']*", proof)):
        if ident in names and names[ident] in ORBIT and ident not in PROV and not ident.startswith('a33_'):
            by_helper.setdefault((ident, names[ident]), []).append(thm)
print('\nOFF-LIST HELPERS (module, consumers):')
for (h, f), ts in sorted(by_helper.items()):
    print(' ', h, f, len(ts), ts if len(ts) <= 6 else ts[:6] + ['...'])
