#!/usr/bin/env python3
# architecture_check.py — b107, strengthened at b110 (2026-08-13)
# The analogue of citation_check.py for CLAIMS. Encodes the manuscript's
# load-bearing architectural invariants as mechanical assertions.
#
# b110 lesson, recorded here because it cost a clean-but-false readout: the first
# version forbade the literal string "P-indivisible subclass" while the book wrote
# "*P-indivisible* subclass". Markdown emphasis defeated the regex and the guard
# reported zero violations while the corpus contradicted Main. A guard whose
# failure mode is SILENCE must be tested against the text it guards. Hence:
#   (a) patterns are emphasis- and hyphen-tolerant semantic families, not literals;
#   (b) every invariant carries a known-bad EXEMPLAR, and the guard fails if an
#       invariant does not match its own exemplar — a pattern that matches nothing
#       can no longer pass quietly.
import os, re, sys, glob

root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
targets = sorted(glob.glob(os.path.join(root, "papers", "*.md"))) \
        + sorted(glob.glob(os.path.join(root, "book", "*.md"))) \
        + [os.path.join(root, "README.md")]

E = r"[*_`\s-]*"          # markdown emphasis / hyphen / space tolerance

INVARIANTS = [
    (rf"P{E}indivisib\w*{E}(subclass)",
     "the imported representation applies across the correspondence's class, not to a P-indivisible subclass",
     [r'does not apply only to a "P-indivisible subclass"', r"P-indivisible-subclass representation clause"],
     "the quantum representation attaches to the *P-indivisible* subclass"),
    (rf"P{E}indivisibility[^.\n]{{0,70}}(carries|produces|yields|gives|delivers)[^.\n]{{0,45}}quantum",
     "P-indivisibility governs nontriviality of the representation, not its existence",
     [],
     "P-indivisibility carries the quantum representation"),
    (r"picks out processes in that class",
     "(T) is tuple instantiation, not an identification of the framework's criterion with the source's class",
     [],
     "the criterion picks out processes in that class"),
    (rf"C1{E}[^.\n]{{0,60}}(implies|forces)[^.\n]{{0,45}}permutation"
     rf"|permutation[^.\n]{{0,60}}(follows from|because of|by){E}C1",
     "C1 is non-zero coupling; a non-permutation one-step matrix is a separate witness, not a consequence of C1",
     [],
     "T is not a permutation matrix (this follows from C1)"),
    (r"lack[s]?[^.\n]{0,90}(Stinespring|density-matrix|density matrix|Hilbert[- ]space unitary)",
     "every stochastic T admits the one-step ancilla dilation (Main §3.1); no process lacks a representation at that layer",
     [],
     "the partially-quantum process lacks the structure required for Stinespring dilation"),
    (r"treated in this paper as structural hypotheses",
     "C1-C4 are diagnostics of a realization, not hypotheses of the characterization",
     [],
     "the four conditions are treated in this paper as structural hypotheses"),
    (r"C1, C2, C3, C4, and C4",
     "duplicated condition in an enumeration",
     [],
     "C1, C2, C3, C4, and C4 therefore produce"),
    (r"[Tt]wo independent routes|either alone sufficient|Either route alone suffices",
     "both routes reach only the transition-statistics layer; neither supplies the operational instrument algebra",
     [r"hypercharge assignment", r'so \\?"either alone suf'],
     "the bridge is established by two independent routes"),
    (rf"requires a{E}\*?frozen\*?{E}hidden sector|hidden sector to evolve much more slowly",
     "C2 is memory persistence, not slow evolution (fastbath_probes.py)",
     [],
     "quantum mechanics requires a *frozen* hidden sector"),
    (rf"(?<!P-)(?<!P){E}\bindivisible{E}subclass",
     "the source's class has no distinguished subclass; use 'the source's finite-configuration class'",
     [],
     "representability following for the indivisible subclass"),
    (r"is no Hilbert space on which|lacks?[^.\n]{0,30}Hilbert space|does not have[^.\n]{0,40}density-matrix description|some but not all[^.\n]{0,40}Stinespring",
     "every stochastic T admits the one-step ancilla dilation; representability is not what is partial",
     [],
     "there is no Hilbert space on which the system's dynamics is unitary"),
    (rf"(finiteness|infinite substratum)[^.\n]{{0,80}}(required|necessary|not produce)[^.\n]{{0,45}}(quantum|P{E}indivisib)",
     "finiteness is load-bearing for the recurrence route only; readback has its own finite-horizon route",
     [],
     "finiteness is required for quantum mechanics"),
    (rf"C2[^.\n]{{0,50}}(must|necessary)[^.\n]{{0,50}}slow|C2[^.\n]{{0,40}}timescale[^.\n]{{0,40}}slower[^.\n]{{0,30}}necessary",
     "C2 is memory persistence; slow evolution is one sufficient mechanism, not the condition",
     [],
     "C2 requires that the hidden sector must have slow dynamics"),
    (r"(does not admit|lacks?|has no|is no)[^.\n]{0,45}(density[- ]matrix|Stinespring|Hilbert space)"
     r"|some but not all[^.\n]{0,45}Stinespring",
     "every stochastic T admits the one-step ancilla dilation; representability is not what is partial",
     [r"no probability calculus", r"requires no Hilbert space, no Born rule",
      r"routed through the uniqueness clause", r"is not distinguished by lacking",
      r"Stinespring uniqueness"],
     "a partially-quantum process does not admit a density-matrix description"),
    (r"Markov chains are excluded|memoryless Markov chains are excluded|excludes? (ordinary )?Markov chains",
     "the source's class explicitly includes Markov chains as special cases",
     [],
     "ordinary memoryless Markov chains are excluded"),
    (r"(L\\u00fcders|Luders|Lüders)[^.\n]{0,60}(derived|delivered|follows)"
     r"|instrument algebra[^.\n]{0,40}(derived|delivered)"
     r"|multi-time predictions[^.\n]{0,40}(derived|delivered|are all)",
     "the operational instrument algebra is open; only the transition-statistics layer is delivered",
     # negation-aware: the corrected form states the NEGATIVE and must not self-trigger
     [r"are NOT all delivered", r"remains open"],
     "the Lüders update and multi-time predictions are derived"),
    (rf"(would not produce|cannot produce|no)[^.\n]{{0,45}}quantum[^.\n]{{0,45}}infinite substratum"
     rf"|infinite substratum[^.\n]{{0,60}}(would not produce|no longer produces|cannot produce)[^.\n]{{0,30}}quantum"
     rf"|finiteness[^.\n]{{0,60}}(makes|required for)[^.\n]{{0,40}}(account of )?quantum",
     "finiteness is load-bearing for the recurrence route only",
     [],
     "the framework would not produce quantum mechanics on an infinite substratum"),
    (r"the (four|4) structural conditions|four structural conditions",
     "C1, C3, C4 are the structural conditions; C2 is a physical-regime premise",
     [r"Juno", r"A_1 is fixed by", r"cubic geometric input"],
     "the framework's four structural conditions"),
    (rf"C2 \(slow bath\)|C2[^.\n]{{0,30}}slow bath\)",
     "C2 is memory persistence; slow bath is one realization",
     [],
     "C2 (slow bath) requires timescale separation"),
    (r"T_\{ij\}(\(t\))?[^.\n]{0,12}=[^.\n]{0,12}\|U_\{ij\}(\(t\))?\|\^2"
     r"|\|\\langle j\|e\^\{-i\\hat\{H\}t\}\|i\\rangle\|\^2 = T_\{ij\}",
     "the bare visible-space form is unavailable in general; the representation is the ancilla-dilated one (Main §3.1)",
     [r"undilated equality", r"is itself unistochastic", r"not in general unistochastic",
      r"trivial-ancilla (special )?case", r"discards phase information", r"ancilla-marginal level"],
     "such that $T_{ij}(t) = |U_{ij}(t)|^2$ on the visible space"),
    (r"(follow|derived|delivered)[^.\n]{0,60}without independent postulates"
     r"|L\u00fcders rule[^.\n]{0,60}(quantum transcription|follows|is derived)",
     "the operational instrument algebra is open; the Lüders rule is not delivered by the characterization",
     [],
     "the further structures of operational quantum mechanics follow without independent postulates"),
    (r"exactly one self-consistent algorithm|the unique self-consistent algorithm",
     "the stochastic-to-quantum representation is explicitly non-unique (Main §3.1)",
     [],
     "there is exactly one self-consistent algorithm for making predictions"),
    (rf"frozen bath[^.\n]{{0,40}}(enables|is required|makes)|only[^.\n]{{0,40}}slow bath[^.\n]{{0,40}}(see|observe)[^.\n]{{0,30}}quantum",
     "C2 is record persistence with timely readback; fast conserved dynamics qualify (fastbath_probes.py)",
     [],
     "the frozen bath enables quantum mechanics"),
    (rf"P{E}indivisibility[^.\n]{{0,70}}(produces|yields|gives)[^.\n]{{0,40}}(quantum correlations|Tsirelson|Bell)"
     rf"|Tsirelson[^.\n]{{0,60}}from[^.\n]{{0,30}}P{E}indivisibility",
     "the Tsirelson value is imported for the causally local indivisible construction, not generic P-indivisibility",
     [],
     "P-indivisibility produces quantum correlations up to Tsirelson"),
    (r"(framework|it) (preserves|satisfies) measurement independence",
     "measurement independence is not imposed at the substratum level; it is an operational target",
     [r"does not impose", r"not imposed"],
     "the framework preserves measurement independence"),
    (rf"phase[- ]lock\w*[^.\n]{{0,70}}unique\w*",
     "phase-locking fixes H only up to shift, rephasing and the antiunitary conjugation H -> -H*",
     [r"antiunitary", r"-\\hat\{H\}\^\*", r"twofold ambiguity"],
     "phase-locking determines the Hamiltonian uniquely"),
    (rf"(Input|Scope|input)[^|\n]{{0,25}}\|[^|\n]{{0,20}}P{E}indivisible process"
     rf"|[Aa]ny P{E}indivisible process(?![^.\n]{{0,40}}nontrivial)",
     "membership in the source's class is not gated by P-indivisibility; (T) admits the process",
     [],
     "| Input | P-indivisible process on $\\mathcal{C}_V$ |"),
    (rf"C1{E}[-–]{E}C4[^.\n]{{0,50}}(jointly necessary|jointly sufficient|exactly the joint specification)"
     rf"|combination of the four conditions[^.\n]{{0,40}}(produces|yields)",
     "the equivalence is a dilation theorem; C4 coincides with the non-Markovianity clause and C1/C3 follow from it",
     [],
     "C1–C4 as jointly necessary for accessible non-Markovianity"),
    (r"(Hamiltonian|dynamics) is uniquely (fixed|determined)"
     r"|Up to this freedom, the dynamics is uniquely determined",
     "phase-locking fixes H only up to shift, rephasing and the antiunitary conjugation",
     [r"antiunitary", r"twofold ambiguity", r"full gauge"],
     "The Hamiltonian is uniquely fixed by the observable transition data."),
    (r"independent second route|second independent route"
     r"|rejects? the Barandes[^.\n]{0,60}must also reject Stinespring",
     "Stinespring independently secures the generic dilation layer only; the two routes share that bedrock",
     [],
     "Stinespring dilation is an independent second route"),
    (r"reproduces all quantum[- ]mechanical predictions|reproduces all of quantum mechanics",
     "the operational instrument algebra is open; not all quantum predictions are delivered",
     [],
     "the framework reproduces all quantum-mechanical predictions"),
    (r"measurement[- ]independence preservation|preservation of measurement independence",
     "measurement independence is not imposed at the substratum level; it is an operational target",
     [],
     "the framework's measurement-independence preservation distinguishes it"),
    (rf"P{E}indivisibility required for (QM|quantum)|requires? P{E}indivisibility[^.\n]{{0,30}}for (QM|quantum)",
     "P-indivisibility is not required for a quantum representation (Main §3.4's diagonal-Hamiltonian counterexample)",
     [],
     "contradicting the P-indivisibility required for QM"),
    (rf"C1{E}[-–]{E}C4 imply quantum mechanics|C1{E}[-–]{E}C4[^.\n]{{0,30}}(imply|produce) (quantum mechanics|QM)",
     "C4's readback implies accessible non-Markovianity; the quantum representation is supplied separately under (T)",
     [],
     "C1–C4 imply quantum mechanics"),
    (r"not to be a permutation — equivalent to non-trivial coupling"
     r"|non-permutation[^.\n]{0,40}equivalent to[^.\n]{0,30}coupling",
     "the non-permutation witness is not equivalent to C1",
     [r"not equivalent to C1", r"does not by itself force"],   # negation-aware
     "requires $T$ not to be a permutation — equivalent to non-trivial coupling"),
    (r"non-Markovianity\}?\s*\\iff\s*\\text\{a per-horizon finite reversible deterministic realization exists"
     r"|accessible non-Markovianity[^.\n]{0,40}\\iff[^.\n]{0,60}realization exists(?![^.\n]{0,80}readback)",
     "the realization-exists form is FALSE without readback on the right-hand side: Markov laws have realizations too",
     [r"is \*\*false\*\*", r"does NOT license"],
     "accessible non-Markovianity \\iff \\text{a per-horizon finite reversible deterministic realization exists}"),
    (rf"P{E}indivisibility is mathematically equivalent to quantum mechanics",
     "P-indivisibility governs nontriviality of the representation, not its existence",
     [],
     "P-indivisibility is mathematically equivalent to quantum mechanics"),
    # ---- b119 families: encode the S ⟺ D ⟺ Q_fb architecture, not merely police old errors ----
    (rf"non{E}Markovianity[^.\n]{{0,80}}(finite{E}horizon{E})?reversible( deterministic)?{E}realizability",
     "bare reversible realizability is universal (the process dilation realizes Markov laws too); the licensed universal statement pairs non-Markovianity with unavoidable readout-relevant hidden memory",
     [r"is \*\*false\*\*", r"does NOT license", r"retired as false"],
     "the in-house equivalence between accessible non-Markovianity and finite-horizon reversible realizability"),
    (rf"QM is not merely{E}\*?compatible|[Qq]uantum mechanics is not merely{E}\*?compatible",
     "the equivalence is scoped: finite-horizon fixed-basis observable laws (S ⟺ D ⟺ Q_fb); unscoped QM-⟺-embedded-observation overstates the theorem",
     [r"finite-horizon fixed-basis", r"observable law"],
     "QM is not merely *compatible with* embedded observation — it is *equivalent to* it."),
    (rf"load{E}bearing for one result only|correspondence[^.\n]{{0,50}}load{E}bearing for[^.\n]{{0,50}}necessity|Barandes[^.\n]{{0,60}}load{E}bearing for the necessity",
     "the representation is internal (permutation unitary, §3.4); the import retains the compressed (≤ n³) form and its interpretive apparatus under (T), nothing gating existence or necessity",
     [],
     "The correspondence [11, 12] is load-bearing for one result only: the necessity direction"),
    (rf"P{E}indivisibility biconditional|QM[^.\n]{{0,25}}(\\Leftrightarrow|⇔|\\iff)[^.\n]{{0,25}}P{E}indivisib",
     "there is no QM ⇔ P-indivisibility biconditional in the architecture: membership and representation are P-indivisibility-free, and nontriviality is the M_t > 0 sector",
     [],
     "the QM $\\Leftrightarrow$ P-indivisibility biconditional powers (ii) $\\implies$ (i)"),
    (rf"frozen{E}bath[^.\n]{{0,60}}enables[^.\n]{{0,40}}quantum",
     "the representation is universal (S ⟺ D ⟺ Q_fb); the bath condition governs the accessible memory sector, and persistence — not frozenness — is the requirement (fastbath_probes.py)",
     [],
     "this frozen-bath condition is what enables quantum mechanics"),
    (rf"(failure|violating)[^.\n]{{0,60}}destroys the framework'?s emergent quantum|destroys the framework'?s emergent quantum mechanics",
     "under S ⟺ D ⟺ Q_fb the representation exists regardless; condition failure removes the memory-bearing sector (accessible non-Markovianity), not the representation",
     [],
     "violating the condition destroys the framework's emergent quantum mechanics"),
    (rf"(unitarily evolving |quantum |unitary )representation is imported|representation is supplied by an external theorem|quantum representation for processes in the correspondence'?s class",
     "existence of the representation is internal by the permutation unitary; only the compressed (≤ n³) form and interpretive apparatus are imported, under (T)",
     [r"compressed", r"no longer"],
     "The unitarily evolving representation is imported, applies across the correspondence's class"),
    (rf"C2 condition states that the hidden sector evolves much more slowly|C2[^.\n]{{0,50}}necessary for P{E}indivisibility",
     "(C2) is memory persistence with two named forms (Main §1.3): (C2-slow) is one mechanism, its necessity the conditional physical-memory theorem — not a P-indivisibility precondition",
     [],
     "The C2 condition states that the hidden sector evolves much more slowly than the visible sector"),
    (rf"P{E}indivisible members[^.\n]{{0,80}}admit the quantum representation",
     "the representation attaches to the whole class (S ⟺ D ⟺ Q_fb); P-indivisibility governs recurrence-scale nontriviality, and the discriminating sector is M_t > 0",
     [],
     "the P-indivisible members of that class, the empirically realized ones, admit the quantum representation"),
    (r"four conditions are exactly the joint specification",
     "C4 is primitive with C1/C3 its consequences and C2 a physical-regime premise; 'exactly the joint specification' overstates joint necessity",
     [],
     "The framework's four conditions are exactly the joint specification of \"embedded laboratory observer"),
    (r"only kind of observer whose dynamics is quantum",
     "the representation is universal at the observable-law level; what the observer kind selects is the memory-bearing (M_t > 0) sector",
     [],
     "the only kind of observer whose dynamics is quantum mechanics"),
    (r"\(C2\) as the retention required",
     "cite (C2-structural) for the retention clause; unqualified (C2) conflates structural retention with the τ_S ≪ τ_B form (Main §1.3)",
     [],
     "(C2) as the retention required by (b)"),
    # ---- b120 families: near-miss formulations of the retired dichotomy, found by sweep after b119 ----
    (r"structurally distinct from QM|violating the condition destroys QM",
     "P-divisible/Markovian laws lie inside Q_fb (S ⟺ D ⟺ Q_fb); condition failure removes the memory-bearing sector, not quantum representability",
     [],
     "violating C2 produces Markovian dynamics, which is structurally distinct from QM"),
    (rf"QM requires{E}(slow{E}bath|coupling|capacity|readback)",
     "state the necessity theorems in the memory currency (accessible non-Markovianity / physical memory), not as requirements of QM — the representation is universal",
     [],
     "QM requires slow bath"),
    (rf"P{E}indivisibility licenses",
     "(T) alone licenses the imported compressed representation; P-indivisibility gates neither membership nor representation (Main §3.4)",
     [],
     "P-indivisibility licenses the imported stochastic–quantum representation"),
    (rf"representation{E}(is{E})?supplied across the correspondence|attach\w*{E}to (its|the) correspondence['\u2019]s class",
     "existence of the representation is internal and universal; only the compressed (≤ n³) form is class-scoped under (T) — say 'compressed'",
     [r"compressed"],
     "the quantum representation is supplied across the correspondence's class under (T)"),
    (rf"QM for processes in the correspondence|correspondence['\u2019]s class \u2192{E}quantum representation",
     "the representation is universal (S ⟺ D ⟺ Q_fb); the class-scoped object is the compressed form",
     [],
     "QM for processes in the correspondence's class"),
    (rf"P{E}indivisibility requires[^.\n]{{0,25}}(τ_S|\\tau_S)",
     "the τ_S ≪ τ_B necessity is conditional on the mixing hypothesis (conditional physical-memory theorem); fast non-mixing baths retain records (fastbath_probes.py)",
     [r"mixing class", r"conditional"],
     "Contrapositive: P-indivisibility requires τ_S ≪ τ_B."),
    # ---- b121 families: review-32 error classes ----
    (rf"(Born rule|Schr\W?\w*dinger equation)[^.\n]{{0,60}}structural consequence",
     "the representation ADMITS Schrödinger-form interpolation and Born-rule readout; on permutation unitaries |U|² = |U|^p for every p > 0, so neither is derived by the equivalence",
     [],
     "the Schrödinger equation and Born rule are structural consequences"),
    (r"framework derives the Born rule|derives the Born rule as the equilibrium",
     "the Born rule is admitted by the representation (S ⟺ D ⟺ Q_fb); the equilibrium reading is the cosmological realization's mechanism proposal, and the quadratic-form selection is open",
     [],
     "The framework derives the Born rule."),
    (r"Born rule is the equilibrium( distribution)? of (the|this) (read-write )?cycle",
     "state it as the cycle's readout rule (admitted), with the quadratic form an open selection question — not as a derived equilibrium",
     [],
     "The Born rule is the equilibrium of the cycle."),
    (r"Derived \(read-write equilibrium\)",
     "the Born-rule origin is split status: representation level settled (admitted), quadratic selection open, equilibrium reading a mechanism proposal",
     [],
     "| Born rule origin | Independent postulate | Derived (read-write equilibrium) |"),
    (r"derives quantum mechanics from embedded observation|theorem that derives quantum mechanics",
     "the posture is identification, not derivation (Main abstract): quantum mechanics as the description of a particular kind of incomplete observation",
     [],
     "the theorem that derives quantum mechanics from embedded observation"),
    (rf"QM emergence[^.\n]{{0,80}}requires[^.\n]{{0,15}}\(C2\)|requires \(C2\) as a necessary condition",
     "unqualified (C2) means persistence (§1.3); the slow form's necessity is conditional, and condition failure empties the memory sector rather than removing QM",
     [],
     "Since QM emergence under the framework requires (C2) as a necessary condition"),
    (r"For every finite accessible horizon, \$\\mathcal\{S\}\$ arises from marginalizing",
     "the characterization's (iii) must be witness-anchored: a horizon ending before the first memory witness carries a Markovian law with no C4-gapped realization — every-horizon form is false",
     [],
     "For every finite accessible horizon, $\\mathcal{S}$ arises from marginalizing a deterministic bijection"),
    (r"same mathematical structure\*? as the amplitude phases",
     "negative intermediate entries and complex phases share a role (no positive propagator), not a demonstrated isomorphism — state it as analogy",
     [],
     "are the *same mathematical structure* as the amplitude phases"),
    (r"follows from C1.{0,2}C4 jointly|structural mechanism for emergent quantum",
     "P-indivisibility follows from a non-permutation coupling at the recurrence scale (§2.3), gates neither membership nor representation, and is not an emergence mechanism",
     [],
     "P-indivisibility is the framework's structural mechanism for emergent quantum mechanics, and it follows from C1–C4 jointly"),
    (r"does not extend to general non.Markovian",
     "the representation extends to every finite-configuration process — divisible, Markovian, and non-Markovian alike (S ⟺ D ⟺ Q_fb; the correspondence's class)",
     [],
     "it does not extend to general non-Markovian (divisible) processes at all"),
    # ---- b122 families: review-33 error classes ----
    (r"Born rule[^.\n]{0,60}is derived",
     "the Born rule is admitted by the representation, not derived; the quadratic functional is a named open selection question (Main §3.4)",
     [],
     "The Born rule, often treated as an independent postulate, is derived"),
    (r"Born rule is derived as the equilibrium",
     "the equilibrium reading is the realization's mechanism proposal, not a derivation (Ch 18 §18.2)",
     [],
     "The Born rule is derived as the equilibrium of the read-write cycle"),
    (r"Born rule as the equilibrium distribution",
     "the Born rule enters as the readout dictionary; the equilibrium reading is a mechanism proposal, not the rule's status",
     [],
     "with the Born rule as the equilibrium distribution"),
    (r"Born rule recovery",
     "renamed: Born-form representation of the transition probabilities — the identity exhibits the Born form without selecting the quadratic exponent",
     [],
     "Theorem B.2.3 (Born rule recovery)."),
    (r"rests on the Barandes correspondence",
     "the characterization and hidden-memory theorems are internal; the import retains only the compressed form and interpretation under (T)",
     [],
     "the characterization theorem, which rests on the Barandes correspondence"),
    (r"drives the quantum emergence",
     "(C2) is the persistence condition sustaining the memory-bearing sector; the slow bath is one mechanism (§1.3), and the representation is universal regardless",
     [],
     "the slow-bath condition (C2) that drives the quantum emergence"),
    (rf"framework derives QM|derives QM (from|as the necessary)",
     "the posture is identification: QM identified with the statistics of embedded observation (Main abstract)",
     [r"Adler"],
     "The framework derives QM from read-write cycling"),
    (r"[Dd]erived QM|derived quantum mechanics",
     "say: the framework's emergent quantum mechanics — 'derived QM' as a noun overstates against the identification posture and the Q_fb/Q_operational split",
     [],
     "Band structure is a consequence of derived QM applied to derived crystal geometry."),
    (r"quantum mechanics follows as a theorem",
     "the memory-bearing statistics and their fixed-basis representation follow as theorems; operational quantum theory entire is the stated frontier",
     [],
     "given the foundational commitment plus four conditions, quantum mechanics follows as a theorem"),
    (r"quantum mechanics derives from|quantum mechanics is derived through",
     "say: the emergent quantum description is constructed/obtained — the construction is a representation, not a derivation of QM's operational structure",
     [],
     "The framework's emergent quantum mechanics derives from a deterministic substratum bijection"),
    (r"satisfying all (three|four) is quantum",
     "the conditions govern the memory-bearing sector, not representability, which is universal (S ⟺ D ⟺ Q_fb)",
     [],
     "A system satisfying all three is quantum"),
    (r"no quantum structure to emerge|derivation of quantum mechanics from embedded observation",
     "condition failure empties the memory-bearing sector; the quantum representation survives trivially, and the posture is identification, not derivation",
     [],
     "there is no quantum structure to emerge"),
    (r"statistics (that )?are quantum mechanics",
     "the statistics are what quantum mechanics represents — the memory-bearing sector carries the discriminating content, the representation being universal",
     [],
     "yields the non-Markovian statistics that are quantum mechanics"),
    (r"equilibrium dynamics between (the )?visible and hidden",
     "the read-write cycle is the realization's mechanism picture, not a derived equilibrium dynamics",
     [],
     "The framework's equilibrium dynamics between the visible and hidden sectors"),
    # ---- b123 families: review-34 error classes ----
    (r"(?<!re)produces? quantum mechanics",
     "the conditions produce the memory-bearing dynamics quantum mechanics represents; representability is universal (S ⟺ D ⟺ Q_fb)",
     [],
     "it produces quantum mechanics at the cosmological scale"),
    (r"yields? quantum mechanics|embeddings yield quantum",
     "C1–C4 define which embeddings carry the memory-bearing sector, not which yield quantum representability",
     [],
     "the conditions defining which embeddings yield quantum mechanics"),
    (r"quantum mechanics emerges from C1|QM emerges because|\"QM emerges\"|quantum mechanics emerging at",
     "the memory-bearing sector emerges from C1–C4; its quantum representation is universal",
     [],
     "quantum mechanics emerges from C1–C4 (Main characterization theorem)"),
    (r"quantum mechanics is derivable from",
     "the posture is identification: the representation is universal, the four conditions characterize the memory-bearing sector",
     [],
     "quantum mechanics is derivable from a deterministic substratum under four conditions"),
    (r"quantum.representation clause rests",
     "the compressed-representation clause rests on the import; the fixed-basis representation's existence is internal",
     [],
     "Because the quantum-representation clause rests on this external result"),
    (r"qualifying regime is precisely the indivisible",
     "the Doukas restriction is on the differentiable continuous-time reading, not on tuple-class membership, which includes Markov chains",
     [r"differentiable reading"],
     "the qualifying regime is precisely the indivisible one §2.3 produces, not the generic one"),
    (r"Stone's theorem",
     "the interpolation comes from the Hermitian logarithm of the discrete step U_φ; a finite substratum has no nontrivial continuous permutation family",
     [r"one.parameter"],
     "For continuous-time dynamics $\\varphi_t$, Stone's theorem on $\\mathcal{H}$ yields"),
    (r"quantum mechanics in biology is the framework's prediction",
     "the prediction is structurally non-Markovian (memory-bearing) dynamics in biology — classical instantiation, no quantum coherence invoked (Medicine)",
     [],
     "quantum mechanics in biology is the framework's prediction rather than the anomaly"),
    (r"emergent quantum mechanics as a theorem",
     "the derivation yields the memory-bearing statistics and their fixed-basis representation as theorem-backed structure, not QM entire as a theorem",
     [],
     "produces the framework's emergent quantum mechanics as a theorem"),
    (r"slow.bath memory \(C2\)",
     "unqualified (C2) is memory persistence (§1.3); the slow bath is one mechanism, not the definition",
     [],
     "coupling (C1), slow-bath memory (C2), high capacity (C3)"),
    # ---- b124 families: review-35 operational-overreach classes ----
    (r"full equivalence between[^.\n]{0,90}unitary quantum mechanics",
     "the equivalence is at the fixed-basis transition-statistics level (S ⟺ D ⟺ Q_fb); the noncommuting observable algebra belongs to the open operational bridge",
     [],
     "the Main paper's characterization theorem is a full equivalence between the embedded-observer reduced description and unitary quantum mechanics"),
    (r"framework reproduces quantum mechanics",
     "scope it: the framework reproduces the represented quantum statistics (fixed-basis layer); KS-type inheritance is conditional on the operational bridge",
     [],
     "The framework reproduces quantum mechanics: the Main paper's characterization theorem"),
    (r"must use (quantum mechanics|Born)|experimenter must use|structural conditions must use",
     "the representation is admitted and explicitly non-unique; 'must use' asserts an operational uniqueness the frontier has not delivered",
     [],
     "it is the probability assignment that any embedded experimenter must use given C1–C4"),
    (r"follow from C1.{0,2}C4 without additional assumptions",
     "the operational toolkit enters through the explicit computational model (Computation §4); CPTP/fixed-basis representability supplies none of its hypotheses",
     [],
     "they follow from C1–C4 without additional assumptions"),
    (r"as derived rather than fundamental constructs|evolution as derived structures",
     "use the four-grade hierarchy: representation constructed; Born-form readout admitted; quadratic functional not derived; operational QM not selected",
     [],
     "with the wave function, Born rule, and unitary evolution arising as derived rather than fundamental constructs"),
    (r"maps P.indivisible stochastic processes",
     "the correspondence's class is the broad finite-configuration tuple class (Markov included); P-indivisibility marks the nontrivial sector, not membership",
     [],
     "the correspondence maps P-indivisible stochastic processes on finite configuration spaces to unitary quantum evolutions"),
    (r"is mathematically equivalent to unitary quantum mechanics",
     "every finite-horizon law admits the fixed-basis representation; C1–C4 select the memory-bearing sector, not representability",
     [],
     "the emergent description of any system satisfying C1–C4 is mathematically equivalent to unitary quantum mechanics"),
    (r"BQP as the .?unique.? computational class",
     "the BQP characterization is conditional on the explicit computational model (Computation §4), not unconditional from C1–C4",
     [],
     "The framework derives BQP as the *unique* computational class accessible to embedded observers"),
    (r"emergent quantum mechanics is [^.\n]{0,20}non.Markovian",
     "the embedded-observer dynamics is memory-bearing; the quantum representation is universal, Markov chains included",
     [],
     "the framework's emergent quantum mechanics is *non-Markovian* through *P-indivisibility*"),
    (r"quantum mechanics as the specific cost",
     "the specific cost is the memory-bearing dynamics quantum mechanics represents",
     [],
     "with quantum mechanics as the specific cost"),
    (r"beyond the transition data[^)\n]{0,60}(interference|entanglement)",
     "split the layers: continuous data constrain generator structure under phase-locking hypotheses; operational interference/entanglement need the open instrument structure",
     [],
     "makes predictions beyond the transition data up to that gauge (energy-gap structure, interference, entanglement)"),
    (r"coupled, slow, and vast",
     "the triple names C2 by its slow mechanism; the conditions sustain the memory-bearing sector, and the representation is universal regardless",
     [],
     "Only an environment that is coupled, slow, and vast sustains the persistent non-decomposable correlations"),
    (r"[Aa]ll four cases (below )?are (thus )?developed results|quantum mechanics is derived as a theorem",
     "Bell and FR are developed; KS and PBR are conditional on the operational bridge reconstructing the observable algebra",
     [],
     "All four cases below are developed results, not conjectures."),
    # ---- b125 family: exact finite operational equivalence is closed in the negative ----
    (r"exactly operationally equivalent",
     "no fixed finite realization is exactly operationally equivalent to the full operational theory (classical-dimension obstruction, Main §3.4); use the ε-form",
     [r"[Nn]o fixed finite"],
     "the framework is exactly operationally equivalent to quantum mechanics"),
    # ---- b126 family: the gluing theorem is approximation, not selection or closure ----
    (r"gluing theorem (closes|delivers|selects)[^.\n]{0,40}operational",
     "the gluing theorem is finite-resolution approximation with fixed mechanisms; the exact limit and the selection question remain the frontier (Main §3.4)",
     [],
     "the gluing theorem closes the gap to operational quantum mechanics"),
    # ---- b126b family: the limit is now a theorem ----
    (r"limit statement is not yet a theorem|limit and the selection question remain the frontier",
     "the operational limit is proved in mutual-ε-density form (uniform continuum realization + Corollary, Main §3.4); only selection remains",
     [],
     "the limit statement is not yet a theorem"),
    # ---- b127 family: substratum purification is not yet the operational axiom ----
    (r"derives the purification axiom|purification axiom (is|has been) derived",
     "the substratum-form theorem gives existence and the canonical predictive quotient; full-completion uniqueness is not claimed, and the operational translation remains (Main §3.4 Remark)",
     [],
     "the framework derives the purification axiom of the reconstruction theorems"),
    # ---- b128 families: retired claims must stay retired ----
    (r"operational state space is a polytope",
     "the polytope inference was invalid (b128 correction of record); the obstruction is classical-dimension form (Main §3.4 Proposition + Remark)",
     [],
     "the operational state space is a polytope with at most N extreme points"),
    (r"= ?\\lim_n D",
     "class identity Q_operational = lim D_finite was retracted in b128; the Corollary states finite-test density of the quantum-shadow subclass only",
     [],
     r"in this sense $Q_{\mathrm{operational}} = \lim_n D_{\mathrm{finite}}$ holds"),
    (r"purification with uniqueness, substratum form",
     "renamed in b128: canonical predictive quotient, a purification ingredient; completions are not unique as wholes (fiber freedom certified)",
     [],
     "Theorem (canonical predictive completion, purification with uniqueness, substratum form)"),
    # ---- b129 family: capacity bounds have different scopes, not a matched pair ----
    (r"two-sided (hidden-)?capacity",
     "constructive upper bound for the built realization vs universal lower bound (>= I*) for every realization; different scopes, not a matched pair (Main §3.4 clause (5), b129)",
     [],
     "a two-sided hidden-capacity law"),
    # ---- b130 family: the route-(i) residue list must stay retired ----
    (r"with three residuals",
     "route (i) is discharged at the exact-ring finite-test level; the one named item is the Rounding Lemma (Main §3.4, b130)",
     [],
     "the finite form is now the gluing theorem below — with three residuals: tightening"),
    # ---- b131 families: pre-equivalence "C1-C4 derive QM" language must stay retired ----
    (r"necessarily describes? the visible sector using",
     "the reduced description is necessarily non-Markovian and ADMITS the quantum representation; nothing forces the observer to use it (Main §3.4, b131)",
     [],
     "the observer necessarily describes the visible sector using quantum mechanics"),
    (r"derivable from a deterministic substratum|deriving quantum mechanics as a theorem",
     "the quantum REPRESENTATION is derived; operational quantum theory's unique selection is open (Main §3.4, b131)",
     [],
     "quantum mechanics is derivable from a deterministic substratum through four conditions"),
    (r"(four conditions|C1–C4) (produce|produced|derive|derived) quantum mechanics",
     "the conditions produce the quantum representation and the memory sector; they do not by themselves produce operational quantum theory (Main §3.4, b131)",
     [],
     "the four conditions produced quantum mechanics in Part I"),
    # ---- b132 families: further regression phrasings caught by review 41 ----
    (r"produce(s)? emergent quantum mechanics",
     "conditions select the memory-bearing sector; its finite laws ADMIT the universal Q_fb representation (Main §3.4, b132)",
     [],
     "these conditions produce emergent quantum mechanics"),
    (r"formalism — quantum(,| mechanics)",
     "the memory-bearing formalism ADMITS the quantum representation; it is not identified with quantum mechanics (Main §3.4, b132)",
     [],
     "must use a memory-bearing formalism — quantum mechanics for processes in the class"),
    # ---- b133 families: review-42 corpus regressions must stay retired ----
    (r"not merely sufficient for quantum mechanics",
     "necessity holds in the memory currency, not for quantum mechanics as such (Main §3.4, b133)",
     [],
     "the conditions are not merely sufficient for quantum mechanics to emerge"),
    (r"(C1–C4|the four conditions) imply P-indivisibility|under C1–C4 the marginalized stochastic process is P-indivisible —",
     "C1–C4 give accessible non-Markovianity; P-indivisibility needs the stronger recurrence/non-permutation regimes (Main §3.4, b133)",
     [],
     "under C1–C4 the marginalized stochastic process is P-indivisible — a precise property"),
    (r"any system equivalent to unitarily evolving",
     "the retired converse: memory-free unitary systems need only the trivial realization; the characterization is in the memory currency (Main §3.4, b133)",
     [],
     "and, under (T), any system equivalent to unitarily evolving quantum mechanics arises from"),
    # ---- b134 families: review-43 corpus-lag phrasings ----
    (r"mechanism for emergent quantum mechanics",
     "P-indivisibility marks the nontrivially indivisible sector; the quantum representation is admitted, not mechanically produced (Main §3.4, b134)",
     [],
     "P-indivisibility, the framework's mechanism for emergent quantum mechanics"),
    (r"therefore equivalent to unitary quantum mechanics",
     "the reduced description ADMITS the quantum representation; equivalence-as-identity is the retired reading (Main §3.4, b134)",
     [],
     "the description is P-indivisible and therefore equivalent to unitary quantum mechanics"),
    # ---- b135 families: review-44 completion-pass regressions ----
    (r"Quantum mechanics emerges under",
     "the memory-bearing description emerges; the quantum representation is admitted (Main §3.4, b135)",
     [],
     "Quantum mechanics emerges under three further conditions"),
    (r"governs all visible-sector dynamics",
     "the representation is available for visible-sector dynamics; selection of the operational theory is open (Main §3.4, b135)",
     [],
     "emergent quantum mechanics governs all visible-sector dynamics"),
    (r"yields emergent quantum mechanics",
     "the conditions yield the memory-bearing sector whose laws admit the quantum representation (Main §3.4, b135)",
     [],
     "combined with C1–C4, yields emergent quantum mechanics"),
    (r"load-bearing dependency",
     "the fixed-basis representation is internal; Barandes is retained for compression and interpretation (Main §3.4, b135)",
     [],
     "an external result used as a load-bearing dependency"),
    # ---- b136 families: review-45 editorial-sweep regressions ----
    (r"establishes that any embedded observer satisfying C1–C4 has access to BQP",
     "BQP access is conditional on the explicit computational-control hypotheses of ch14 §14.4 (b136)",
     [],
     "establishes that any embedded observer satisfying C1–C4 has access to BQP computational resources"),
    (r"produce the quantum behavior you want",
     "C1–C4 characterize memory architecture; target processes are realized as finite-test shadows, not selected by the conditions (Main §3.4, b136)",
     [],
     "engineer the C1–C4 architecture to produce the quantum behavior you want"),
    (r"as part of the emergent quantum mechanics",
     "capabilities belong to the stated computational-control model / operational layer, not to emergent QM as such (b136)",
     [],
     "operations the observer has access to as part of the emergent quantum mechanics"),
    # ---- b137 families: review-46 pre-freeze regressions ----
    (r"default\*? wherever",
     "the memory-bearing dynamics is the rule where the conditions hold; quantum mechanics as such is not 'the default' (Main §3.4, b137)",
     [],
     "quantum mechanics is the default wherever C1–C4 hold"),
    (r"all derivable from the framework's structural conditions",
     "computational capabilities come from the stated §14.4 control model, not from C1–C4 alone (b137)",
     [],
     "state preparation, gate application, and measurement all derivable from the framework's structural conditions"),
    (r"identifies quantum mechanics with the statistics",
     "the theorem identifies the representation and the memory sector, not unrestricted operational QM (Main §3.4, b137)",
     [],
     "the theorem that identifies quantum mechanics with the statistics of embedded observation"),
    # ---- b138 families: the freeze-pass semantic classes ----
    (r"quantum mechanics emerges under those conditions",
     "the memory-bearing description emerges; the representation is universally admitted (Main §3.4, b138)",
     [],
     "the central theorem that quantum mechanics emerges under those conditions"),
    (r"forced by its equivalence with quantum mechanics",
     "the KS chain is conditional on the operational bridge reconstructing the observable algebra (Main §3.4, b138)",
     [],
     "contextuality being forced by its equivalence with quantum mechanics"),
    (r"second independent bridge",
     "the routes share dilation bedrock; Q_fb existence is internal, Barandes is compression/interpretation (Main §3.4, b138)",
     [],
     "provided the second independent bridge from deterministic substrata"),
    (r"quantum mechanics under C1–C4 is necessarily non-Markovian",
     "the C1–C4/readback SECTOR is necessarily memory-bearing; representability is universal (Main §3.4, b138)",
     [],
     "emergent quantum mechanics under C1–C4 is necessarily non-Markovian"),
    # ---- b139 families: review-48 final semantic classes (markup-tolerant) ----
    (r"is the emergent description of any embedded observer",
     "the memory-bearing description is what the observer has; QM-as-such is not identified with it (Main §3.4, b139)",
     [],
     "quantum mechanics is the emergent description of any embedded observer satisfying C1–C4"),
    (r"structurally \*?quantum\*? wherever",
     "biology is structurally memory-bearing wherever the conditions hold; representability is universal (Main §3.4, b139)",
     [],
     "biology is *structurally quantum* wherever C1–C4 hold"),
    (r"sees the same emergent quantum mechanics",
     "observers share the memory architecture and representation; further structures need their own derivation chains (b139)",
     [],
     "any embedded observer satisfying C1–C4 sees the same emergent quantum mechanics"),
    (r"rather than emergent quantum mechanics",
     "the contrast is memoryless vs memory-bearing; representability is universal, Markov included (Main §3.4, b139)",
     [],
     "produces classical stochastic dynamics rather than emergent quantum mechanics"),
    (r"produces emergent unitary quantum mechanics|identification of quantum mechanics with embedded observation applies in full",
     "the bijection produces the memory-bearing description; the representation is supplied, operational selection open (Main §3.4, b139)",
     [],
     "the deterministic bijection produces emergent unitary quantum mechanics on the visible sector"),
    # ---- b140 families: the partially-quantum layer must not contradict S<=>D ----
    (r"BEC_Experiment",
     "the file is not packaged; F(r)=2r-r^2 is a proposed model form until a derivation ships (b140)",
     [],
     "developed in detail in BEC_Experiment.md §3.3"),
    (r"classical probability distribution over hidden classical variables",
     "every finite law has a deterministic hidden realization (S<=>D, Main §3.4); non-realizability is never the claim (b140)",
     [],
     "does not admit a classical probability distribution over hidden classical variables"),
    (r"required for the framework's emergent quantum mechanics in its fully-quantum form",
     "C3 is the capacity condition for the memory-bearing sector; representability is universal (Main §3.4, b140)",
     [],
     "C3 is required for the framework's emergent quantum mechanics in its fully-quantum form"),
    (r"fully quantum-decohered in the standard sense",
     "the memoryless-description test is the mechanism proposal's own falsifiable claim (b140)",
     [],
     "the enzyme would be fully quantum-decohered in the standard sense"),
]

# --- self-test: every invariant must match its own known-bad exemplar ---
selftest_failures = [why for pat, why, _, ex in INVARIANTS if not re.search(pat, ex)]
for why in selftest_failures:
    print(f"SELF-TEST FAILURE: an invariant does not match its own exemplar -> {why}")

violations = []
for path in targets:
    if not os.path.exists(path): continue
    text = open(path, encoding="utf-8").read()
    for pattern, why, exceptions, _ in INVARIANTS:
        for m in re.finditer(pattern, text):
            window = text[max(0, m.start()-160):m.start()+160]   # b114: qualifying language often sits a clause away
            if any(re.search(e, window) for e in exceptions): continue
            line = text[:m.start()].count("\n") + 1
            violations.append((os.path.relpath(path, root), line, re.sub(r"\s+", " ", m.group(0))[:60], why))

LIMIT = len(violations) if os.environ.get("OI_ARCH_FULL") else 25
for f, ln, hit, why in violations[:LIMIT]:
    print(f"ARCHITECTURE VIOLATION  {f}:{ln}  '{hit}'\n    -> {why}")
if len(violations) > LIMIT: print(f"    … and {len(violations)-LIMIT} more (set OI_ARCH_FULL=1 for all)")
print(f"architecture_check: {len(INVARIANTS)} invariant(s), {len(violations)} violation(s), "
      f"{len(selftest_failures)} self-test failure(s)")
sys.exit(1 if (violations or selftest_failures) else 0)
