#!/usr/bin/env python3
"""EQ-D, node N4 (QD2): the converse test in finite-dimensional complex QT, and the foils.

Principles tested (statements in RESULT.md):
  FP-S  every face F generated by k jointly perfectly distinguishable pure states, with the restricted effects, is
        affinely the state space (with all effects) of a capacity-k system;
  FP-O  the identification is implemented by transformations: decode D: B -> A, encode E: A -> B, with
        D(Omega_B) = F, E o D = id, D o E = id on F;
  FP-T  every transformation of A mapping F into its cone restricts to a transformation of B, and every
        transformation of B arises so;
  FP-C  the composite of two face systems is the face of the composite generated by product states, and the real
        span of the products is the real span of that face (local tomography of faces).
All checks are exact field arithmetic (sympy DomainMatrix over QQ_I or QQ, helper module gq.py): frames are columns
of Cayley transforms of Gaussian-rational skew-Hermitian matrices, states and effects are Gaussian-rational.
Seeded randomness; no floating point.
"""
import sys

from sympy.polys.domains import QQ
from sympy.polys.matrices import DomainMatrix

from gq import Ctx, real_rank

FAILS = []


def check(name, ok):
    print(('PASS ' if ok else 'FAIL ') + name)
    if not ok:
        FAILS.append(name)


def converse(real):
    C = Ctx(real, 8100 + int(real))
    tag = 'real QT' if real else 'complex QT'
    for n in (2, 3, 4, 5, 6):
        U = C.cayley(C.rand_skew(n))
        if not C.eq(C.H(U) * U, C.eye(n)):
            check(f'[{tag}] Cayley frame unitary n={n}', False)
            continue
        for k in range(1, n + 1):
            iota = C.cols(U, range(k))
            P = iota * C.H(iota)
            ok = C.eq(C.H(iota) * iota, C.eye(k))
            # frame: the k pure states are perfectly distinguishable by their own projectors
            for i in range(k):
                for j in range(k):
                    vi, vj = C.col(U, i), C.col(U, j)
                    val = (C.H(vi) * vj * C.H(vj) * vi)[0, 0].element
                    ok &= val == (C.K.one if i == j else C.K.zero)
            # face map, inverse, exposedness by the sharp effect P
            sig = C.rand_state(k)
            rho = iota * sig * C.H(iota)
            ok &= C.trace(rho) == C.K.one and C.eq(P * rho * P, rho) and C.eq(C.H(iota) * rho * iota, sig)
            ok &= C.trace(P * rho) == C.K.one
            if k < n:
                full = C.rand_state(n)
                ok &= C.re(C.K.one - C.trace(P * full)) > 0
            # restricted effects are all effects of the k-level system
            Ek = C.rand_effect(k)
            En = iota * Ek * C.H(iota)
            ok &= C.trace(En * rho) == C.trace(Ek * sig)
            # FP-O: encode/decode in Kraus form, trace preserving, mutually inverse on the face
            e0 = C.zeros(k, 1)
            e0 = DomainMatrix([[C.K.one] + [C.K.zero] * (k - 1)], (1, k), C.K).transpose()
            enc_kraus = [C.H(iota)] + [e0 * C.H(C.col(U, j)) for j in range(k, n)]
            S = C.zeros(n)
            for K in enc_kraus:
                S = S + C.H(K) * K
            ok &= C.eq(S, C.eye(n))

            def enc(X):
                out = C.zeros(k)
                for K in enc_kraus:
                    out = out + K * X * C.H(K)
                return out
            ok &= C.eq(iota * enc(rho) * C.H(iota), rho) and C.eq(enc(iota * sig * C.H(iota)), sig)
            # FP-T: a CP instrument on the k-level system extends to a face-preserving one and restricts back
            m = 2
            V = C.cols(C.cayley(C.rand_skew(k * m)), range(k))       # isometry C^k -> C^(km)
            Ks = [C.rows(V, range(j * k, (j + 1) * k)) for j in range(m)]
            S = C.zeros(k)
            for K in Ks:
                S = S + C.H(K) * K
            ok &= C.eq(S, C.eye(k))
            Kt = [iota * K * C.H(iota) for K in Ks] + [C.eye(n) - P]
            S = C.zeros(n)
            for K in Kt:
                S = S + C.H(K) * K
            ok &= C.eq(S, C.eye(n))
            out_t, out_k = C.zeros(n), C.zeros(k)
            for K in Kt:
                out_t = out_t + K * rho * C.H(K)
            for K in Ks:
                out_k = out_k + K * sig * C.H(K)
            ok &= C.eq(P * out_t * P, out_t) and C.eq(C.H(iota) * out_t * iota, out_k)
            # the certain face of the sharp effect P is not a point for k >= 2 (the census's K-infinity scope)
            if k >= 2:
                r0 = C.col(U, 0) * C.H(C.col(U, 0))
                r1 = C.col(U, 1) * C.H(C.col(U, 1))
                ok &= C.trace(P * r0) == C.K.one and C.trace(P * r1) == C.K.one and not C.eq(r0, r1)
            check(f'[{tag}] n={n} k={k}: frame; face = D_k (affine iso); exposed by P; restricted effects; '
                  f'FP-O encode/decode; FP-T extend/restrict; certain face not a point (k>=2)', ok)


def herm_basis(C, k):
    out = []
    for i in range(k):
        rows = [[C.K.zero] * k for _ in range(k)]
        rows[i][i] = C.K.one
        out.append(DomainMatrix(rows, (k, k), C.K))
    for i in range(k):
        for j in range(i + 1, k):
            rows = [[C.K.zero] * k for _ in range(k)]
            rows[i][j] = rows[j][i] = C.K.one
            out.append(DomainMatrix(rows, (k, k), C.K))
            if not C.real:
                rows = [[C.K.zero] * k for _ in range(k)]
                rows[i][j], rows[j][i] = C.s(0, -1), C.s(0, 1)
                out.append(DomainMatrix(rows, (k, k), C.K))
    return out


def as_real_vec(C, M):
    n, m = M.shape
    return [C.re(M[i, j].element) for i in range(n) for j in range(m)] + \
           [C.im(M[i, j].element) for i in range(n) for j in range(m)]


def composites(real):
    C = Ctx(real, 77)
    tag = 'real QT' if real else 'complex QT'
    for k, m in ((2, 2), (2, 3), (3, 2), (3, 3)):
        prods = [C.kron(A, B) for A in herm_basis(C, k) for B in herm_basis(C, m)]
        dprod = real_rank([as_real_vec(C, M) for M in prods])
        dfull = (k * m) ** 2 if not real else (k * m) * (k * m + 1) // 2
        if real:
            check(f'[{tag}] FP-C span test k={k}, m={m}: products span {dprod} < dim Sym({k*m}) = {dfull} '
                  f'(local tomography of faces fails)', dprod < dfull)
        else:
            check(f'[{tag}] FP-C span test k={k}, m={m}: products span all of Herm({k*m}), dimension {dfull}',
                  dprod == dfull)


def quaternionic():
    """Quaternionic n x n Hermitian matrices as complex 2n x 2n Hermitian matrices commuting with
    J v = Om conj(v), Om = 1_n (x) [[0,-1],[1,0]]."""
    C = Ctx(False, 5)
    z, o = C.K.zero, C.K.one
    units = [DomainMatrix([[o, z], [z, o]], (2, 2), C.K), DomainMatrix([[C.s(0, 1), z], [z, C.s(0, -1)]], (2, 2), C.K),
             DomainMatrix([[z, o], [-o, z]], (2, 2), C.K), DomainMatrix([[z, C.s(0, 1)], [C.s(0, 1), z]], (2, 2), C.K)]

    def E(n, i, j):
        rows = [[z] * n for _ in range(n)]
        rows[i][j] = o
        return DomainMatrix(rows, (n, n), C.K)

    def qherm_basis(n):
        out = [C.kron(E(n, i, i), units[0]) for i in range(n)]
        for i in range(n):
            for j in range(i + 1, n):
                for u in units:
                    Mh = C.kron(E(n, i, j), u)
                    out.append(Mh + C.H(Mh))
        return out

    def conjm(M):
        r, c = M.shape
        return DomainMatrix([[C.conj(M[i, j].element) for j in range(c)] for i in range(r)], (r, c), C.K)
    ok = True
    for n in (2, 3):
        Om = C.kron(C.eye(n), DomainMatrix([[z, -o], [o, z]], (2, 2), C.K))
        B = qherm_basis(n)
        for M in B:
            ok &= C.eq(M, C.H(M)) and C.eq(Om * conjm(M), M * Om)
        ok &= real_rank([as_real_vec(C, M) for M in B]) == n * (2 * n - 1)
    check('[quaternionic QT] the complex model of Herm_n(H) is Hermitian, J-invariant, of real dimension n(2n-1) (n=2,3)', ok)
    corner = [M for M in qherm_basis(3) if all(M[r, c].element == z for r in range(6) for c in range(6) if r >= 4 or c >= 4)]
    check('[quaternionic QT] the face on the quaternionic span of two orthonormal vectors spans the corner Herm_2(H): '
          'real dimension 6, a 5-dimensional state ball of capacity 2: FP-S holds in HQT',
          real_rank([as_real_vec(C, M) for M in corner]) == 6)


def classical_and_square():
    ok = True
    for n in range(2, 8):
        for k in range(1, n + 1):
            rows = [[QQ(1 if i == j else 0) for i in range(n)] + [QQ(1)] for j in range(k)]
            ok &= DomainMatrix(rows, (k, n + 1), QQ).rank() == k
    check('[classical] the face generated by k vertices of a simplex is a (k-1)-simplex (capacity k): FP-S, FP-O hold', ok)
    half = QQ(1, 2)
    sq = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
    e1 = lambda p: half * (1 + p[0])
    e2 = lambda p: 1 - e1(p)
    edge = [p for p in sq if e2(p) == 0]
    f = lambda p: half * (1 + p[1])
    cap_edge = len(edge) == 2 and sorted([f(edge[0]), f(edge[1])]) == [0, 1]
    dim = lambda pts: DomainMatrix([[QQ(x) for x in p] + [QQ(1)] for p in pts], (len(pts), 3), QQ).rank() - 1
    check('[square gbit] the states with zero last outcome of a complete measurement form an edge of capacity 2 (MM '
          'requires 1); the edge (dim 1) and the square (dim 2) have equal capacity 2 and are not affinely isomorphic: '
          'the subspace axiom (FP-S with FP-E) fails', cap_edge and dim(edge) == 1 and dim(sq) == 2)
    check('[K2-only theory] capacity 3 is not a power of 2: the 3-face of Q_2 is carried by no system, FP-S fails',
          3 not in {2 ** j for j in range(12)})
    check('[real QT] phaseGate 0 = diag(i, 1) has non-real entry i: DrivesElementary at Fin 2 fails in RQT',
          Ctx(False, 0).im(Ctx(False, 0).s(0, 1)) != 0)


if __name__ == '__main__':
    converse(False)
    composites(False)
    converse(True)
    composites(True)
    quaternionic()
    classical_and_square()
    print()
    if FAILS:
        print('VERDICT  VOID — failed:', FAILS)
        sys.exit(1)
    print('VERDICT  complex QT satisfies FP-S, FP-O, FP-T and FP-C on every tested frame (n <= 6); real QT satisfies '
          'FP-S, FP-O, FP-T and fails the span form of FP-C; HQT and classical theory satisfy FP-S; the square gbit '
          'and the K2-only theory fail FP-S/FP-E')
