#!/usr/bin/env python3
"""Thread A (PAIR-COMP), nodes A2/A4: the two closure principles that a native construction supplies
at the instance (gate cnot, identity locals, the same cone at every pair), and what the four-copy
interface FCC says about them. Exact arithmetic only (sympy Rationals and Gaussian rationals; symbolic
identities). Run as:  python3 -I -B a2_native_closures.py

Objects (landed conventions, as in kt4_prem1_probe.py; transcription re-checked against the base):
  SEP     the convex cone generated by prodState x y, x, y in the closed unit ball;
  K_gen   SEP + cnot SEP: the completion of the stage product closed under cnot (node A2(c)); it is the
          smallest convex cone that contains every product state and is cnot-invariant;
  K_E     dualW(K_gen) = {w : ipW(w, g) >= 0 for every generator g of K_gen}: the states that are
          nonnegative on every natively generated effect (product effects and their cnot images);
          it equals maxCone /\ cnot(maxCone), the largest admissible cnot-invariant cone (written, W-A2.2);
  T_psi   actT R_H phiW (landed probe M_cl.6), R_H = [[0,0,1],[0,-1,0],[1,0,0]];
  F       E00/2 - T_psi/4;   E = T_psi/4.
  FCC famI at (X, Y, E, F):  fourVal X Y E F = ipW(E, X F Y^T) >= 0 for X, Y in the pair cones and E, F in
  their duals (landed probe H8 for the identity fourVal X Y E F = ipW E (X F Y^T)).

DECISION RULES (fixed before the first run; rules, not expected numbers):
  R1 DUAL-SOS: a table G is certified in dualW(K_gen) iff, for symbolic x, y in R^3,
     ipW(G, prodState x y) and ipW(G, cnot(prodState x y)) are each identically equal to an explicit
     expression c0 + c1 |x - O y|^2 + c2 (1 - |x|^2) + c3 (1 - |y|^2) with c_i >= 0 rational and O a
     signed permutation matrix (so the value is >= 0 for x, y in the ball); together with the symbolic
     identity ipW(A, cnot B) = ipW(cnot A, B) (cnot is self-adjoint for ipW).
  R2 SEPARATION: T_psi is certified outside K_gen iff F passes R1 and ipW(F, T_psi) < 0.
  R3 IE1(K_gen) FAILS iff phiW = cnot(prodState xplus z3) and T_psi = actT R_H phiW with R_H a rotation
     (R^T R = I, det R = 1), and R2 holds.
  R4 FCC(K_gen) FAILS iff phiW lies in K_gen (R3), E and F pass R1, and fourVal phiW phiW E F < 0.
  R5 K_E: (a) F lies in K_E (R1 again: K_E = dualW K_gen); (b) F is not in Q3: <psi| pauliW F |psi> < 0
     for the unit vector psi of T_psi (pauliW T_psi = psi psi^dagger, exact); (c) IE1(K_E) FAILS iff some
     rotation R and some generator g of K_gen give ipW(actT R F, g) < 0; (d) FCC(K_E) FAILS iff X, Y in K_E
     certified by R1 and generators E', F' of K_gen (which lie in dualW K_E by definition) give
     fourVal X Y E' F' < 0; (e) every product state lies in K_E: ipW(prodState x y, g) >= 0 on both generator
     families, via the identity ipW(prodState x y, cnot(prodState x' y')) = pairVal(hom x, hom y, cnot(prodState x' y'))
     and the landed cnot_prodState_mem_maxCone (source check), and the product identity for SEP.
  COUNTERCONTROLS (each must give the opposite verdict):
     C1 the witness construction aimed at a member of K_gen fails: G' = E00/2 - phiW/4 has ipW(G', phiW) < 0
        with phiW in K_gen, so G' is not in dualW K_gen;
     C2 with F replaced by the Q3-dual effect T_psi/4, the famI value at (phiW, phiW, T_psi/4, .) is >= 0;
     C3 the transcription control: ipW(T_psi, prodState x y) differs from 1 + x.y (the identity permutation)
        as a polynomial, so the permutation O of R1 is load-bearing;
     C4 a rotated member of Q3, actT R phiW, is >= 0 on the same sampled generators as R5(c)
        (rotations do not leave K_E from Q3 at those generators).
  R6 INCLUSIONS (added in run 2, wording of the verdict only; see NOTES): the identities behind
     K_gen <= Q3 <= K_E hold symbolically: pauliW(prodState x y) = rho(x) (x) rho(y), pauliW(cnot w) =
     CNOT pauliW(w) CNOT^dagger, and ipW E X = tr(opW E pauliW X) with opW = 4 pauliW. The remaining step
     (a Kronecker product of positive semidefinite matrices, the conjugate of one by a unitary, and the trace
     of a product of two, are positive semidefinite / nonnegative) is written and standard.
  VERDICT: printed iff every check and every countercontrol passes; otherwise 'VERDICT: not rendered', exit 1.
Deterministic output; no timing.
"""
import re
import sys
from itertools import product
from pathlib import Path

import sympy as sp

Q = sp.Rational
iu = sp.I
R4 = range(4)
CHECKS = []


def chk(cid, name, ok, kind, detail=''):
    ok = bool(ok)
    CHECKS.append((cid, kind, ok))
    print(f"{'PASS' if ok else 'FAIL'} {cid}  [{kind}] {name}" + (f" -- {detail}" if detail else ''), flush=True)


def note(cid, text):
    print(f'NOTE [written] {cid}  -- {text}', flush=True)


PC = [[0, 0, 3, 3], [1, 1, 2, 2], [2, 2, 1, 1], [3, 3, 0, 0]]
PT = [[0, 1, 2, 3], [1, 0, 3, 2], [1, 0, 3, 2], [0, 1, 2, 3]]
NEG = {(1, 3), (2, 2)}
BASE = Path(__file__).resolve().parent.parent / 'base' / 'verification' / 'lean-mathlib' / 'OIBridge'
CD = (BASE / 'CompositeDimension.lean').read_text(encoding='utf-8')
KG = (BASE / 'K2Guard.lean').read_text(encoding='utf-8')

print('== S0 transcription')
msg = re.search(r'^def sgn \(μ ν : Fin 4\) : ℝ := if \(μ = (\d) ∧ ν = (\d)\) ∨ \(μ = (\d) ∧ ν = (\d)\) '
                r'then -1 else 1$', CD, re.M)
neg_src = {(int(msg.group(1)), int(msg.group(2))), (int(msg.group(3)), int(msg.group(4)))} if msg else None


def lean_table(nm):
    mm = re.search(rf'^def {nm} : Fin 4 → Fin 4 → Fin 4\n((?:  \|.*\n){{4}})', CD, re.M)
    if not mm:
        return None
    T = [[None] * 4 for _ in R4]
    for a, b, v in re.findall(r'\|\s*(\d),\s*(\d)\s*=>\s*(\d)', mm.group(1)):
        T[int(a)][int(b)] = int(v)
    return T


chk('S0.tables', 'sgn, pc, pt, phiW transcribed from the base', neg_src == NEG and lean_table('pc') == PC
    and lean_table('pt') == PT
    and 'def phiW : W 3 := fun μ ν => if μ = ν then (if μ = 2 then -1 else 1) else 0' in CD, 'source')
chk('S0.cites', 'landed cnot_prodState_mem_maxCone, cnot_prodState_xplus_z3, prodState_mem_maxCone are present',
    'theorem cnot_prodState_mem_maxCone' in CD and 'theorem cnot_prodState_xplus_z3' in CD
    and 'theorem prodState_mem_maxCone' in KG, 'source')


def sgn(m, n):
    return -1 if (m, n) in NEG else 1


def cnot(w):
    return sp.Matrix(4, 4, lambda m, n: sgn(m, n) * w[PC[m][n], PT[m][n]])


def hom(x):
    return sp.Matrix([1] + list(x))


def homMap(R):
    M = sp.zeros(4, 4)
    M[0, 0] = 1
    M[1:4, 1:4] = R
    return M


def actT(R, w):
    return w * homMap(R).T


def prodState(x, y):
    return hom(x) * hom(y).T


def pairVal(a, b, w):
    return (sp.Matrix(a).T * w * sp.Matrix(b))[0, 0]


def ipW(E, X):
    return sum(E[m, n] * X[m, n] for m in R4 for n in R4)


def fourVal(X, Y, E, F):
    return sum(X[a, b] * Y[c, d] * E[a, c] * F[b, d] for a, b, c, d in product(R4, repeat=4))


S = [sp.eye(2), sp.Matrix([[0, 1], [1, 0]]), sp.Matrix([[0, -iu], [iu, 0]]), sp.Matrix([[1, 0], [0, -1]])]


def pauliW(w):
    out = sp.zeros(4, 4)
    for m in R4:
        for n in R4:
            if w[m, n] != 0:
                out += w[m, n] * sp.kronecker_product(S[m], S[n])
    return out / 4


phiW = sp.diag(1, 1, -1, 1)
E00 = sp.zeros(4, 4)
E00[0, 0] = 1
RH = sp.Matrix([[0, 0, 1], [0, -1, 0], [1, 0, 0]])
I3 = sp.eye(3)
xplus, z3 = [1, 0, 0], [0, 0, 1]
Tpsi = actT(RH, phiW)
Fw = E00 / 2 - Tpsi / 4
Ew = Tpsi / 4
xs = sp.symbols('x1 x2 x3', real=True)
ys = sp.symbols('y1 y2 y3', real=True)
X3, Y3 = sp.Matrix(xs), sp.Matrix(ys)
Wsym = sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'w{i}{j}', real=True))
Asym = sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'a{i}{j}', real=True))


def is_signed_perm(O):
    return all(sum(abs(O[i, j]) for j in range(3)) == 1 and sum(1 for j in range(3) if O[i, j] != 0) == 1
               for i in range(3)) and O.T * O == I3


def sos(c0, c1, c2, c3, O):
    v = X3 - O * Y3
    return c0 + c1 * v.dot(v) + c2 * (1 - X3.dot(X3)) + c3 * (1 - Y3.dot(Y3))


def dual_sos(G, certs):
    """R1: certs = ((c0, c1, c2, c3, O) for the product family, (...) for the cnot family)."""
    ok = True
    for fam, cert in zip(('prod', 'cnot'), certs):
        c0, c1, c2, c3, O = cert
        val = ipW(G, prodState(xs, ys)) if fam == 'prod' else ipW(G, cnot(prodState(xs, ys)))
        ok = ok and min(c0, c1, c2, c3) >= 0 and is_signed_perm(O) and sp.expand(val - sos(c0, c1, c2, c3, O)) == 0
    return ok


print()
print('== S1 the dual memberships (R1)')
chk('A2.1', 'ipW(A, cnot B) = ipW(cnot A, B) for symbolic tables (cnot is self-adjoint for ipW)',
    sp.expand(ipW(Asym, cnot(Wsym)) - ipW(cnot(Asym), Wsym)) == 0, 'identity')
P13 = sp.Matrix([[0, 0, 1], [0, 1, 0], [1, 0, 0]])           # the block of T_psi
blkT = Tpsi[1:4, 1:4]
blkC = cnot(Tpsi)[1:4, 1:4]
chk('A2.2', 'T_psi = diag(1) + P13 and cnot T_psi = diag(1) + O_c with O_c a signed permutation (no unit row/column)',
    blkT == P13 and is_signed_perm(blkC) and Tpsi[0, :] == sp.Matrix([[1, 0, 0, 0]])
    and cnot(Tpsi)[0, :] == sp.Matrix([[1, 0, 0, 0]]) and Tpsi[:, 0] == sp.Matrix([1, 0, 0, 0])
    and cnot(Tpsi)[:, 0] == sp.Matrix([1, 0, 0, 0]), 'witness', f'O_c = {blkC.tolist()}')
# ipW(T_psi, x(x)y) = 1 + x.P13 y = 1/2 |x + P13 y|^2 + 1/2 (1 - |x|^2) + 1/2 (1 - |y|^2):  O = -P13
certE = ((0, Q(1, 8), Q(1, 8), Q(1, 8), -P13), (0, Q(1, 8), Q(1, 8), Q(1, 8), -blkC))
certF = ((0, Q(1, 8), Q(1, 8), Q(1, 8), P13), (0, Q(1, 8), Q(1, 8), Q(1, 8), blkC))
chk('A2.3', 'R1: E = T_psi/4 lies in dualW K_gen (both generator families, exact SOS identity)', dual_sos(Ew, certE),
    'identity')
chk('A2.4', 'R1: F = E00/2 - T_psi/4 lies in dualW K_gen (both generator families, exact SOS identity)',
    dual_sos(Fw, certF), 'identity')
note('A2.W1', 'K_gen is the convex cone generated by the two families prodState x y and cnot(prodState x y), '
     'x, y in the ball, so a table nonnegative on both families is nonnegative on K_gen; by A2.1 '
     'ipW(G, cnot g) = ipW(cnot G, g). Each SOS expression is >= 0 on the ball because |x|, |y| <= 1.')

print()
print('== S2 T_psi is outside K_gen; IE1 fails for K_gen (R2, R3)')
vFT = ipW(Fw, Tpsi)
chk('A2.5', 'R2: ipW(F, T_psi) < 0, so T_psi is not in K_gen', vFT < 0, 'witness', f'value {vFT}')
chk('A2.6', 'R3: phiW = cnot(prodState xplus z3) (phiW in K_gen); R_H is a rotation; T_psi = actT R_H phiW',
    cnot(prodState(xplus, z3)) == phiW and RH.T * RH == I3 and RH.det() == 1
    and Tpsi == sp.Matrix([[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0]]), 'witness')
psi = sp.Matrix([1, 1, 1, -1]) / 2
pTp = pauliW(Tpsi)
chk('A2.7', 'pauliW T_psi = psi psi^dagger, psi = (1, 1, 1, -1)/2 (T_psi is a pure state of Q3, landed M_cl.7)',
    (pTp - psi * psi.H).applyfunc(sp.expand) == sp.zeros(4, 4), 'witness')
note('A2.W2', 'so actT R_H maps phiW in K_gen to T_psi outside K_gen: IE1 fails for K_gen; and K_gen is not Q3. '
     'This is a PSD-free certificate of the landed M_cl.9W conclusion (T_psi is not in SEP + cnot SEP): a linear '
     'witness F with exact SOS certificates in place of pure-state extremality.')

print()
print('== S3 FCC fails for the uniform K_gen (R4)')
vI = fourVal(phiW, phiW, Ew, Fw)
chk('A2.8', 'fourVal X Y E F = ipW E (X F Y^T) for symbolic tables (landed probe H8, re-checked)',
    sp.expand(fourVal(Wsym, Asym, sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'e{i}{j}')),
                      sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'f{i}{j}')))
              - ipW(sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'e{i}{j}')),
                    Wsym * sp.Matrix(4, 4, lambda i, j: sp.Symbol(f'f{i}{j}')) * Asym.T)) == 0, 'identity')
chk('A2.9', 'R4: famI at (X, Y, E, F) = (phiW, phiW, T_psi/4, E00/2 - T_psi/4) is negative', vI < 0, 'witness',
    f'value {vI}')
note('A2.W3', 'phiW lies in K_gen (A2.6) and E, F lie in dualW K_gen (A2.3, A2.4), so FourCopyCoherent fails for '
     'the uniform family (K_gen, K_gen, K_gen, K_gen). K_gen contains the products, lies in maxCone (landed '
     'prodState_mem_maxCone, cnot_prodState_mem_maxCone) and is a convex cone, so by Lemma B1 '
     '(fourCopyCoherent_of_kt4Core, design run, [D]) no carrier carries KT4Core for it: H fails.')
vC2 = fourVal(phiW, phiW, Ew, Ew)
chk('C2', 'countercontrol: with F replaced by the Q3-dual effect T_psi/4 the same famI value is >= 0',
    vC2 >= 0, 'countercontrol', f'value {vC2}')
Gp = E00 / 2 - phiW / 4
vC1 = ipW(Gp, phiW)
chk('C1', 'countercontrol: the witness built on phiW (in K_gen), E00/2 - phiW/4, is negative at phiW, so it is '
    'not in dualW K_gen', vC1 < 0, 'countercontrol', f'value {vC1}')
lhsC3 = sp.expand(ipW(Tpsi, prodState(xs, ys)))
chk('C3', 'countercontrol: ipW(T_psi, prodState x y) is not 1 + x.y (the permutation in R1 is load-bearing)',
    sp.expand(lhsC3 - (1 + X3.dot(Y3))) != 0, 'countercontrol', f'ipW = {lhsC3}')

print()
print('== S4 the maximal closure K_E = dualW(K_gen) (R5)')
chk('A2.10', 'R5(a): F lies in K_E (it is A2.4)', dual_sos(Fw, certF), 'identity')
vq = (psi.H * pauliW(Fw) * psi)[0, 0]
chk('A2.11', 'R5(b): <psi| pauliW F |psi> < 0, so F is not in Q3: K_E is strictly larger than Q3', sp.simplify(vq) < 0,
    'witness', f'value {sp.simplify(vq)}')
R0 = sp.Matrix([[Q(3, 5), Q(-4, 5), 0], [Q(4, 5), Q(3, 5), 0], [0, 0, 1]])
gx, gy = [0, -1, 0], [0, 1, 0]
g0 = cnot(prodState(gx, gy))
vR = ipW(actT(R0, Fw), g0)
chk('A2.12', 'R5(c): R0 is a rotation and ipW(actT R0 F, cnot(prodState (0,-1,0) (0,1,0))) < 0: actT R0 maps F in '
    'K_E out of K_E, so IE1 fails for K_E', R0.T * R0 == I3 and R0.det() == 1 and vR < 0, 'witness', f'value {vR}')
pts = [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1], [Q(3, 5), Q(4, 5), 0],
       [0, Q(3, 5), Q(4, 5)], [Q(2, 3), Q(2, 3), Q(1, 3)], [Q(-2, 3), Q(1, 3), Q(2, 3)]]
gens = [prodState(x, y) for x in pts for y in pts] + [cnot(prodState(x, y)) for x in pts for y in pts]
rot_phi = actT(R0, phiW)
vC4 = min(ipW(rot_phi, g) for g in gens)
chk('C4', 'countercontrol: actT R0 phiW (a member of Q3, inside K_E) is >= 0 on the sampled generators',
    vC4 >= 0, 'countercontrol', f'minimum {vC4} over {len(gens)} generators')
ok_phi_prod = sp.expand(ipW(phiW, prodState(xs, ys)) - sos(0, Q(1, 2), Q(1, 2), Q(1, 2), -sp.diag(1, -1, 1))) == 0
ok_phi_cnot = sp.expand(ipW(phiW, cnot(prodState(xs, ys))) - (1 + xs[0]) * (1 + ys[2])) == 0
chk('A2.13', 'R5(d) membership: phiW lies in K_E: ipW(phiW, prodState x y) = SOS and ipW(phiW, cnot(prodState x y)) '
    '= (1 + x1)(1 + y3) >= 0 on the ball', ok_phi_prod and ok_phi_cnot, 'identity')
Eg = cnot(prodState([0, 1, 0], [0, 0, -1]))
Fg = cnot(prodState([0, 1, 0], [0, 1, 0]))
vKE = fourVal(Fw, phiW, Eg, Fg)
chk('A2.14', 'R5(d): famI for the uniform K_E at X = F, Y = phiW, E\' = cnot(prodState e2 (-e3)), '
    'F\' = cnot(prodState e2 e2) is negative', vKE < 0, 'witness', f'value {vKE}')
note('A2.W4', 'E\' and F\' are generators of K_gen; every generator g of K_gen lies in dualW K_E because '
     'ipW(g, w) >= 0 for w in K_E = dualW K_gen by definition. So FourCopyCoherent fails for the uniform K_E; '
     'K_E contains the products (A2.15), lies in maxCone and is a convex cone, so by Lemma B1 [D] H fails for it.')
xp, yp = sp.symbols('u1 u2 u3', real=True), sp.symbols('v1 v2 v3', real=True)
idA = sp.expand(ipW(prodState(xs, ys), cnot(prodState(xp, yp))) - pairVal(hom(xs), hom(ys), cnot(prodState(xp, yp))))
idB = sp.expand(ipW(prodState(xs, ys), prodState(xp, yp))
                - (1 + X3.dot(sp.Matrix(xp))) * (1 + Y3.dot(sp.Matrix(yp))))
chk('A2.15', 'R5(e): ipW(prodState x y, cnot(prodState u v)) = pairVal(hom x, hom y, cnot(prodState u v)) and '
    'ipW(prodState x y, prodState u v) = (1 + x.u)(1 + y.v), symbolic', idA == 0 and idB == 0, 'identity')
note('A2.W5', 'hom x = 2 ehom(sharp effect (1 + x.z)/2) for |x| <= 1, so pairVal(hom x, hom y, w) = 4 prodEffVal >= 0 '
     'for w in maxCone; cnot(prodState u v) is in maxCone by the landed cnot_prodState_mem_maxCone; and '
     '(1 + x.u)(1 + y.v) >= 0 on the ball. So every product state lies in K_E.')
note('A2.W6', 'the interval: every convex cone K that contains the product states, lies in maxCone and is '
     'cnot-invariant satisfies K_gen <= K (it contains the products and their cnot images) and K <= K_E '
     '(cnot K = K lies in maxCone, so K lies in maxCone /\\ cnot(maxCone); dualW(SEP) = maxCone because the '
     'homogenized effect vectors of the ball are the cone L of hom-points, landed lor_ehom and isEffectOn_affOf; '
     'and dualW(cnot SEP) = cnot(dualW SEP) by A2.1). Q3 and the landed foil K_cl lie in this interval. Both '
     'endpoints are closed (K_gen: the convex hull of two compact sets, cone over a compact base; K_E: a dual '
     'cone), contain the products, are cnot-invariant, and fail IE1 and FCC (A2.6-A2.9, A2.12-A2.14).')

print()
print('== S5 the identities behind K_gen <= Q3 <= K_E (R6)')
CNOTm = sp.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])


def rho1(x):
    return (S[0] + sum((x[i] * S[i + 1] for i in range(3)), sp.zeros(2, 2))) / 2


ok_r6 = (pauliW(prodState(xs, ys)) - sp.kronecker_product(rho1(xs), rho1(ys))).applyfunc(sp.expand) == sp.zeros(4, 4)
ok_r6 = ok_r6 and (pauliW(cnot(Wsym)) - CNOTm * pauliW(Wsym) * CNOTm.H).applyfunc(sp.expand) == sp.zeros(4, 4)


def opW(E):
    return 4 * pauliW(E)


trp = sum((opW(Asym) * pauliW(Wsym))[i, i] for i in range(4))
ok_r6 = ok_r6 and sp.expand(ipW(Asym, Wsym) - trp) == 0
chk('A2.16', 'R6: pauliW(prodState x y) = rho(x) (x) rho(y), pauliW(cnot w) = CNOT pauliW(w) CNOT^dagger and '
    'ipW E X = tr(4 pauliW(E) pauliW(X)), symbolic', ok_r6, 'identity')
note('A2.W7', 'with the standard facts (Kronecker products and unitary conjugates of positive semidefinite '
     'matrices are positive semidefinite; tr(AB) >= 0 for A, B positive semidefinite) and rho(x) >= 0 for |x| <= 1: '
     'every generator of K_gen lies in Q3, so K_gen <= Q3; every member of Q3 pairs nonnegatively with every generator '
     'of K_gen, so Q3 <= dualW(K_gen) = K_E. Both inclusions are strict by A2.5 with A2.7 (T_psi in Q3 \\ K_gen) and by '
     'A2.10 with A2.11 (F in K_E \\ Q3).')

print()
kinds = {}
for _, k, _ in CHECKS:
    kinds[k] = kinds.get(k, 0) + 1
print('kinds: ' + ', '.join(f'{k} {v}' for k, v in sorted(kinds.items())))
failed = [c for c, _, ok in CHECKS if not ok]
if failed:
    print(f'a2_native_closures: FAILED -- {len(failed)} of {len(CHECKS)}: {", ".join(failed)}')
    print('VERDICT: not rendered')
    sys.exit(1)
print(f'a2_native_closures: OK -- {len(CHECKS)} checks')
print('VERDICT A2: at the instance (cnot, identity locals, uniform cones) the minimal native closure K_gen = '
      'SEP + cnot SEP and the maximal one K_E = dualW(K_gen) are admissible cnot-invariant cones; Q3 differs from '
      'both (exact witnesses T_psi in Q3 outside K_gen, F in K_E outside Q3; the inclusions K_gen <= Q3 <= K_E rest '
      'on the exact identities A2.16 and written standard steps); IE1 fails for both, and FCC fails for both '
      f'(famI values {vI} and {vKE}). Closedness of the two endpoints is written (A2.W6).')
