"""AC probe P4 -- which downstream consumers need the closure of a raw countable family.
Exact arithmetic only.

  C1  symmetric bilinear forms invariant under the two raw generators R_x(theta), R_z(theta)
      (cos theta = 3/5): solution space dimension 1 (the round form).  No closure is used: two raw
      generators pin the invariant quadratic form that TRB-1's ball theorem consumes
  C2  countercontrols for C1: under R_z(theta) alone, dimension 2 (a(x^2+y^2) + b z^2); under the
      finite raw group generated by R_x(pi), R_z(pi) (Klein four), dimension 3 (diagonal forms)
  C3  countercontrol for the dense-orbit weakening (density on ALL boundary states is load-bearing):
      the cylinder B^2 x [-1,1] with R_z(theta) and the reflection z -> -z: every invariant form is
      a(x^2+y^2) + b z^2, and the boundary states (1,0,0), (1,0,1) get values a, a + b; with b > 0
      (positive definiteness) the form is not constant on the boundary
  C4  EFF-1 cone separation by raw directions: on K2-GUARD-1's chain vector chainW (outside
      maxCone (eball 3), kernel value -1/2 at (-e1, -e3)), some pair of RAW orbit directions
      b = W e_z, b' = W' e_z gives a strictly negative product-effect value (exact)
  C5  control for C4: on product states the raw-direction values are products of effect values,
      hence nonnegative (checked on a grid of raw pairs)
  C6  exact-existence predicates are not closure-invariant: with avail = the raw seed orbit
      {sharpEff (W e_z)}, no available sharp effect is certain at the boundary state -e_z within the
      enumerated words (written for all words: P1 F9); an effect sharpEff b is certain on the ball
      exactly at b (checked on rational sphere points)
"""
import sys
from fractions import Fraction as Fr
from itertools import product

L = int(sys.argv[1]) if len(sys.argv) > 1 else 6
c, s = Fr(3, 5), Fr(4, 5)
I3 = [[Fr(int(i == j)) for j in range(3)] for i in range(3)]
Rx = [[Fr(1), Fr(0), Fr(0)], [Fr(0), c, -s], [Fr(0), s, c]]
Rz = [[c, -s, Fr(0)], [s, c, Fr(0)], [Fr(0), Fr(0), Fr(1)]]
Rxpi = [[Fr(1), 0, 0], [0, Fr(-1), 0], [0, 0, Fr(-1)]]
Rzpi = [[Fr(-1), 0, 0], [0, Fr(-1), 0], [0, 0, Fr(1)]]
Zref = [[Fr(1), 0, 0], [0, Fr(1), 0], [0, 0, Fr(-1)]]


def T(A):
    return [[A[j][i] for j in range(3)] for i in range(3)]


def mul(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def mv(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) for i in range(3))


results = []


def check(name, cond, detail=''):
    results.append((name, bool(cond)))
    print(('PASS ' if cond else 'FAIL ') + name + (('  ' + detail) if detail else ''))


def nullity(M):
    M = [row[:] for row in M]
    rows, cols = len(M), len(M[0])
    r = 0
    for cc in range(cols):
        piv = next((i for i in range(r, rows) if M[i][cc] != 0), None)
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][cc]
        M[r] = [x / pv for x in M[r]]
        for i in range(rows):
            if i != r and M[i][cc] != 0:
                f = M[i][cc]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
    return cols - r


SYM = [(i, j) for i in range(3) for j in range(i, 3)]  # 6 unknowns


def invariant_form_dim(gens):
    rows = []
    for G in gens:
        # equations: (G^T S G - S)_{ij} = 0 for i <= j, S symmetric with unknowns S_{ij}, i<=j
        for (i, j) in SYM:
            row = [Fr(0)] * len(SYM)
            for k, (a, b) in enumerate(SYM):
                # contribution of S_ab (and S_ba) to (G^T S G)_{ij} = sum_{p,q} G_pi S_pq G_qj
                coef = G[a][i] * G[b][j]
                if a != b:
                    coef += G[b][i] * G[a][j]
                if (a, b) == (i, j):
                    coef -= 1
                row[k] = coef
            rows.append(row)
    return nullity(rows)


d1 = invariant_form_dim([Rx, Rz])
check('C1 invariant symmetric forms under the raw pair {R_x(theta), R_z(theta)}: dimension 1', d1 == 1, f'dim = {d1}')
d2 = invariant_form_dim([Rz])
check('C2 countercontrol: under R_z(theta) alone, dimension 2', d2 == 2, f'dim = {d2}')
d3 = invariant_form_dim([Rxpi, Rzpi])
check('C2 countercontrol: under the finite group <R_x(pi), R_z(pi)>, dimension 3', d3 == 3, f'dim = {d3}')
# C2b: pinning the form is NOT the ball theorem.  The finite octahedral rotation group
# <R_x(pi/2), R_z(pi/2)> also pins the form (irreducible), and it preserves the cube [-1,1]^3,
# which is not a ball: orbit density on the boundary, not form pinning, is what TRB-1 consumes.
Qx = [[Fr(1), 0, 0], [0, Fr(0), Fr(-1)], [0, Fr(1), Fr(0)]]
Qz = [[Fr(0), Fr(-1), 0], [Fr(1), Fr(0), 0], [0, 0, Fr(1)]]
d5 = invariant_form_dim([Qx, Qz])
check('C2b countercontrol: finite octahedral rotations <R_x(pi/2), R_z(pi/2)> also give dimension 1', d5 == 1,
      f'dim = {d5}')
cube_vertices = [(a, b, cc) for a in (1, -1) for b in (1, -1) for cc in (1, -1)]
pres = all(tuple(int(t) for t in mv(G, v)) in cube_vertices for G in (Qx, Qz) for v in cube_vertices)
check('C2b ... and they permute the cube vertices (preserve the cube, not a ball)', pres)
d4 = invariant_form_dim([Rz, Zref])
check('C3 cylinder symmetries R_z(theta), z -> -z: invariant forms have dimension 2', d4 == 2, f'dim = {d4}')
# the two-dimensional space is spanned by diag(1,1,0) and diag(0,0,1); verify both are invariant
for name, Sm in (('diag(1,1,0)', [[Fr(1), 0, 0], [0, Fr(1), 0], [0, 0, Fr(0)]]),
                 ('diag(0,0,1)', [[Fr(0), 0, 0], [0, Fr(0), 0], [0, 0, Fr(1)]])):
    inv = all(mul(mul(T(G), Sm), G) == Sm for G in (Rz, Zref))
    check(f'C3 {name} is invariant', inv)
qa = lambda a, b, v: a * (v[0] ** 2 + v[1] ** 2) + b * v[2] ** 2  # noqa: E731
a_, b_ = Fr(4), Fr(3)  # any positive pair; the difference is b
check('C3 Q(1,0,1) - Q(1,0,0) = b > 0 on two boundary states of the cylinder',
      qa(a_, b_, (1, 0, 1)) - qa(a_, b_, (1, 0, 0)) == b_ and b_ > 0)

# C4 raw orbit directions
GEN = {'x': Rx, 'X': T(Rx), 'z': Rz, 'Z': T(Rz)}
INV = {'x': 'X', 'X': 'x', 'z': 'Z', 'Z': 'z'}
EZ = (Fr(0), Fr(0), Fr(1))


def reduced(n):
    out = ['']
    frontier = ['']
    for _ in range(n):
        nxt = []
        for w in frontier:
            for a in GEN:
                if w and a == INV[w[-1]]:
                    continue
                nxt.append(w + a)
        out += nxt
        frontier = nxt
    return out


orbit = {}
for w in reduced(L):
    if w and w[-1] in 'zZ':
        continue
    v = EZ
    for a in reversed(w):
        v = mv(GEN[a], v)
    orbit.setdefault(v, w)
dirs = list(orbit)


def sharpVec(b):
    return [Fr(1, 2)] + [t / 2 for t in b]


def pairVal(a, b, om):
    return sum(a[m] * om[m][n] * b[n] for m in range(4) for n in range(4))


chainW = [[Fr(1), 0, 0, Fr(1)], [Fr(1), 0, 0, Fr(-1)], [0, 0, 0, 0], [0, 0, 0, 0]]
kern = pairVal(sharpVec((Fr(-1), 0, 0)), sharpVec((0, 0, Fr(-1))), chainW)
check('C4 kernel witness reproduced: value at (-e1, -e3) is -1/2', kern == Fr(-1, 2))
best = None
for b in dirs:
    for b2 in dirs:
        v = pairVal(sharpVec(b), sharpVec(b2), chainW)
        if best is None or v < best[0]:
            best = (v, orbit[b], orbit[b2])
check('C4 some raw pair of orbit directions separates chainW from maxCone (value < 0)', best[0] < 0,
      f'min value {best[0]} (~{float(best[0]):.4f}, display only) at words {best[1]!r}, {best[2]!r}; '
      f'{len(dirs)} directions')

# C5 control: product states


def hom(x):
    return [Fr(1)] + list(x)


def prodState(x, y):
    hx, hy = hom(x), hom(y)
    return [[hx[m] * hy[n] for n in range(4)] for m in range(4)]


sample = dirs[:40]
ok = True
for x_, y_ in [(EZ, (Fr(1), 0, 0)), ((Fr(2, 7), Fr(3, 7), Fr(6, 7)), (0, Fr(-1), 0))]:
    om = prodState(x_, y_)
    for b in sample:
        for b2 in sample:
            v = pairVal(sharpVec(b), sharpVec(b2), om)
            ok &= v >= 0 and v == ((1 + sum(p * q for p, q in zip(b, x_))) / 2) * ((1 + sum(p * q for p, q in zip(b2, y_))) / 2)
check('C5 control: on product states every raw-direction value is a product of effect values (>= 0)', ok,
      f'{2 * len(sample) ** 2} instances')

# C6
negz = (Fr(0), Fr(0), Fr(-1))
check('C6 no raw seed transport sharpEff(W e_z) is certain at -e_z (enumerated words)', negz not in orbit)
cert = True
pts = [(Fr(2, 7), Fr(3, 7), Fr(6, 7)), (Fr(-6, 7), Fr(2, 7), Fr(-3, 7)), EZ, negz]
for b in pts:
    for xx in pts:
        val = (1 + sum(p * q for p, q in zip(b, xx))) / 2
        cert &= ((val == 1) == (b == xx))
check('C6 sharpEff b is certain at a sphere point x iff x = b (rational sphere points)', cert)

nfail = sum(1 for _, ok_ in results if not ok_)
print(f'SUMMARY {len(results) - nfail}/{len(results)} PASS')
print('VERDICT ' + ('consumer-classification-holds' if nfail == 0 else 'NOT RENDERED'))
