"""EQ2-C, C3 target 1: boundary purity (BP) at capacity two from level-uniform premises.

Theorem under test (written proof in RESULT.md, Theorem BP-S):
  Let Omega be a compact convex body with nonempty interior, G a group of affine automorphisms, and F a set of
  ordered pairs (frames) of distinct extreme points, closed under swap, with
    (Spec2) every state lies on a closed segment [x, y] with (x, y) in F, and
    (SS)    G maps F onto F and acts transitively on it (as ordered pairs).
  Then every frame's midpoint is the centroid c, Omega is centrally symmetric about c, every boundary state is a
  frame member (hence extreme): BP; and G is transitive on the extreme points, so BoundaryTransitive holds.
  Operational reading: frames = pairs of perfectly distinguishable pure states (capacity two makes them maximal).

DECISION RULE (fixed before the first run). The verdict line prints only if every check below passes:
  M  (mechanism, positive control) Bloch ball: frames are antipodal pairs; SS has exact rational rotation
     witnesses; Spec2 has exact decompositions on rational samples; BP holds (written; kernel KF:658).
  P5 regular pentagon (exact, Q(sqrt5)): capacity two; SS holds (D5 transitive on the 10 ordered frames);
     Spec2 fails (the centroid lies on no frame segment); BP fails; strongly self-dual; ELEM2 holds.
     -> SS, capacity two and self-duality do not give BP; Spec2 is load-bearing.
  BD bidisk D x D (= conv of the torus S1 x S1): capacity two; Spec2 holds (exact samples of the written
     construction); SS fails (two frames with midpoints = c and != c; affine automorphisms fix c, TB:356);
     BP fails. -> Spec2 and a continuous transitive group on pure states do not give BP; SS is load-bearing.
  ST Stiefel orbitope conv V2(R^3): SS fails by the same mechanism; BP fails; Spec2 exact instance.
  Q3 qutrit: Spec and SS hold with frames = orthonormal TRIPLES (exact instances); BP fails.
     -> "frames are pairs" (capacity two) is load-bearing.
  C2 Caratheodory orbitope: capacity >= 3 (exact triple); BP fails: outside the capacity-two scope.
  Controls on the harness itself: the frame test reproduces the square (all 12 ordered pairs of distinct vertices)
  and the affine-regular hexagon (18 ordered frames, two D6-orbits matching the midpoint criterion); the strong
  self-duality test rejects the square with its D4-invariant forms; a non-frame pair of the pentagon has no
  distinguishing effect.
Exact arithmetic only (Fraction, Q(sqrt5), sympy with sqrt(3) for the Caratheodory curve).
"""
import os
import sys
from fractions import Fraction as Fr
from itertools import permutations, combinations

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from c_common import Checks, Q5, IPHI, vadd, vsub, vscale, dot, cross2, mat_vec  # noqa: E402

C = Checks("c3_bp")


# ----------------------------------------------------------------------------- polygon machinery (2D, exact)

def outward_normals(V):
    """V: vertices in counterclockwise order. normal of edge k = [V[k], V[k+1]] is (dy, -dx)."""
    n = len(V)
    out = []
    for k in range(n):
        d = vsub(V[(k + 1) % n], V[k])
        out.append((d[1], -d[0]))
    return out


def in_cone(x, g1, g2):
    """x in cone(g1, g2) for g1 -> g2 counterclockwise with angle < pi."""
    return cross2(g1, x).sign() >= 0 and cross2(x, g2).sign() >= 0 if hasattr(cross2(g1, x), "sign") else \
        cross2(g1, x) >= 0 and cross2(x, g2) >= 0


def normal_cone(V, i):
    """normal cone of vertex i: generated by the outward normals of edges (i-1, i) and (i, i+1), ccw order."""
    nrm = outward_normals(V)
    n = len(V)
    return nrm[(i - 1) % n], nrm[i]


def cones_meet(A, B):
    a1, a2 = A
    b1, b2 = B
    return in_cone(a1, b1, b2) or in_cone(a2, b1, b2) or in_cone(b1, a1, a2) or in_cone(b2, a1, a2)


def neg(v):
    return tuple(-x for x in v)


def is_frame(V, i, j):
    """exists linear l maximal over V at V[i] and minimal at V[j]: N_i meets -N_j."""
    if i == j:
        return False
    b1, b2 = normal_cone(V, j)
    return cones_meet(normal_cone(V, i), (neg(b1), neg(b2)))


def frame_effect(V, i, j):
    """an explicit distinguishing effect: a common direction l, e = (l - min)/(max - min)."""
    A = normal_cone(V, i)
    b1, b2 = normal_cone(V, j)
    B = (neg(b1), neg(b2))
    for cand in (A[0], A[1], B[0], B[1]):
        if in_cone(cand, *A) and in_cone(cand, *B):
            l = cand
            break
    vals = [dot(l, v) for v in V]
    mx, mn = max(vals), min(vals)
    return [(x - mn) / (mx - mn) for x in vals]


def frames_of(V):
    n = len(V)
    return [(i, j) for i in range(n) for j in range(n) if is_frame(V, i, j)]


def on_segment_line(p, a, b):
    return cross2(vsub(b, a), vsub(p, a)) == 0


def in_polygon_strict(V, p):
    nrm = outward_normals(V)
    return all((dot(nrm[k], vsub(p, V[k]))).sign() < 0 if hasattr(dot(nrm[k], vsub(p, V[k])), "sign")
               else dot(nrm[k], vsub(p, V[k])) < 0 for k in range(len(V)))


def orbit_ordered_pairs(gens_perm, start):
    """orbit of an ordered vertex pair under the group generated by vertex permutations"""
    seen = {start}
    frontier = [start]
    while frontier:
        new = []
        for (i, j) in frontier:
            for g in gens_perm:
                q = (g[i], g[j])
                if q not in seen:
                    seen.add(q)
                    new.append(q)
        frontier = new
    return seen


def perm_of_linear(M, V):
    """the vertex permutation induced by a linear map M (must permute V)"""
    img = [mat_vec(M, v) for v in V]
    perm = []
    for w in img:
        hits = [k for k, v in enumerate(V) if v == w]
        if len(hits) != 1:
            return None
        perm.append(hits[0])
    return perm if sorted(perm) == list(range(len(V))) else None


# ----------------------------------------------------------------------------- P5: the regular pentagon

print("== P5 the affine-regular pentagon in Q(sqrt5): v_{k+1} = (1/phi) v_k - v_{k-1}")
P = [(Q5(1), Q5(0)), (Q5(0), Q5(1))]
for k in range(3):
    P.append(vsub(vscale(IPHI, P[-1]), P[-2]))
C.check("P5.0 recurrence closes: v5 = v0, and the vertices sum to 0 (centroid 0 by D5 symmetry below)",
        vsub(vscale(IPHI, P[4]), P[3]) == P[0] and vadd(vadd(vadd(P[0], P[1]), vadd(P[2], P[3])), P[4]) == (0, 0))
C.check("P5.0b convex, counterclockwise: every consecutive cross product is positive",
        all(cross2(vsub(P[(k + 1) % 5], P[k]), vsub(P[(k + 2) % 5], P[(k + 1) % 5])).sign() > 0 for k in range(5)))
R5 = ((Q5(0), Q5(-1)), (Q5(1), IPHI))      # columns v1, v2
S5 = ((Q5(1), IPHI), (Q5(0), Q5(-1)))      # columns v0, v4
pr = perm_of_linear(R5, P)
ps = perm_of_linear(S5, P)
C.check(f"P5.1 R permutes the vertices as the 5-cycle {pr}; S as the reflection {ps}",
        pr == [1, 2, 3, 4, 0] and ps == [0, 4, 3, 2, 1])
# the group D5 as vertex permutations
grp = {tuple(range(5))}
frontier = [tuple(range(5))]
while frontier:
    new = []
    for g in frontier:
        for h in (pr, ps):
            c = tuple(h[g[k]] for k in range(5))
            if c not in grp:
                grp.add(c)
                new.append(c)
    frontier = new
C.check(f"P5.2 the generated group has order {len(grp)} (D5)", len(grp) == 10)
F5 = frames_of(P)
C.check(f"P5.3 frames (perfectly distinguishable ordered vertex pairs) = the 10 ordered distance-2 pairs: {F5}",
        sorted(F5) == sorted([(i, (i + 2) % 5) for i in range(5)] + [(i, (i - 2) % 5) for i in range(5)]))
eff_ok = True
for (i, j) in F5:
    e = frame_effect(P, i, j)
    eff_ok &= e[i] == 1 and e[j] == 0 and all(Q5(0) <= x <= Q5(1) for x in e)
C.check("P5.4 each frame has an explicit effect: 1 on the first vertex, 0 on the second, in [0,1] on every vertex",
        eff_ok)
C.check("P5.5 countercontrol: the adjacent pair (v0, v1) is not a frame (normal cones of v0 and -v1 do not meet)",
        not is_frame(P, 0, 1) and not is_frame(P, 1, 0))
tri = [t for t in combinations(range(5), 3)
       if all(((a, b) in F5) for a in t for b in t if a != b)]
C.check(f"P5.6 capacity two: no three pairwise-distinguishable vertices (triples: {tri}); capacity >= 2: a frame exists",
        tri == [] and len(F5) > 0)
orb = orbit_ordered_pairs([list(g) for g in grp], (0, 2))
C.check(f"P5.7 SS: the D5-orbit of the ordered frame (v0, v2) has {len(orb)} elements = all ordered frames",
        orb == set(F5))
cen = (Q5(0), Q5(0))
mids_c = [((i, j)) for (i, j) in F5 if vscale(Q5(Fr(1, 2)), vadd(P[i], P[j])) == cen]
C.check("P5.8 the theorem's mechanism: no frame has the centroid as midpoint", mids_c == [])
C.check("P5.9 Spec2 fails: the centroid lies on no frame segment (not even on a frame line)",
        not any(on_segment_line(cen, P[i], P[j]) for (i, j) in F5))
m01 = vscale(Q5(Fr(1, 2)), vadd(P[0], P[1]))
nrm = outward_normals(P)
vals = [dot(nrm[0], v) for v in P]
C.check("P5.10 BP fails: the edge midpoint (v0+v1)/2 attains the max of the edge-0 functional (a proper effect is "
        "certain there, KF:227) and is a proper midpoint, so it is a non-extreme boundary state",
        dot(nrm[0], m01) == max(vals) and min(vals) < max(vals) and P[0] != P[1])
m02 = vscale(Q5(Fr(1, 2)), vadd(P[0], P[2]))
C.check("P5.11 ELEM2: the midpoint of the frame (v0, v2) is an interior point", in_polygon_strict(P, m02))
# strong self-duality: M = diag(alpha, Q), Q the D5-invariant form, alpha from orthogonality
#   Q = [[q11, q12], [q12, q22]]; invariance R^T Q R = Q, S^T Q S = Q is linear in (q11, q12, q22)
def quad(Q, u, v):
    return dot(u, mat_vec(Q, v))


# solve: for the rotation R5: R^T Q R = Q. Parametrize q11 = 1 and solve the 2 remaining unknowns exactly.
# Using S5: S^T Q S = Q gives, with S = [[1, i],[0,-1]] (i = 1/phi): entry (0,1): q11*i - q12 = q12 -> q12 = q11*i/2.
q11 = Q5(1)
q12 = IPHI / 2
# entry (1,1) of R^T Q R = Q, with R = [[0,-1],[1,i]]: (R^T Q R)_{11} = q11 - 2 i q12 + i^2 q22 ... solve for q22
# R^T Q R entry (0,0) = q22 (R e0 = (0,1)) must equal q11 -> q22 = q11
q22 = Q5(1)
Qf = ((q11, q12), (q12, q22))


def RtQR(R, Q):
    RT = tuple(tuple(R[j][i] for j in range(2)) for i in range(2))
    def mm(A, B):
        return tuple(tuple(A[i][0] * B[0][j] + A[i][1] * B[1][j] for j in range(2)) for i in range(2))
    return mm(mm(RT, Q), R)


C.check("P5.12 the form Q = [[1, 1/(2phi)], [1/(2phi), 1]] is D5-invariant (R^T Q R = Q and S^T Q S = Q)",
        RtQR(R5, Qf) == Qf and RtQR(S5, Qf) == Qf)
C.check("P5.13 Q is positive definite (q11 > 0, det > 0)", q11.sign() > 0 and (q11 * q22 - q12 * q12).sign() > 0)
alphas = set()
for k in range(5):
    alphas.add(-quad(Qf, P[k], P[(k + 3) % 5]))
    alphas.add(-quad(Qf, P[(k + 1) % 5], P[(k + 3) % 5]))
alpha = list(alphas)[0]
C.check(f"P5.14 one alpha = {alpha} makes M(1, v_(k+3)) orthogonal to both generators (1, v_k), (1, v_(k+1)) "
        "of facet k, for every k", len(alphas) == 1 and alpha.sign() > 0)


def Mpair(u, v):     # (1,u)^T M (1,v) with M = diag(alpha, Q)
    return alpha + quad(Qf, u, v)


nonneg = all(Mpair(P[j], P[k]).sign() >= 0 for j in range(5) for k in range(5))
C.check("P5.15 strong self-duality: M = diag(alpha, Q) is positive definite and D5-invariant, M(1, v_j) pairs "
        "nonnegatively with every generator and vanishes on exactly the two generators of the opposite facet; "
        "so M maps the 5 extreme rays of K onto the 5 extreme rays of K*, K* = M K",
        nonneg and all(sorted(k for k in range(5) if Mpair(P[j], P[k]) == 0) ==
                       sorted([(j + 2) % 5, (j + 3) % 5]) for j in range(5)))

# ----------------------------------------------------------------------------- harness controls: square, hexagon

print("== harness controls: square and affine-regular hexagon")
Sq = [(Fr(1), Fr(1)), (Fr(-1), Fr(1)), (Fr(-1), Fr(-1)), (Fr(1), Fr(-1))]
Fsq = frames_of(Sq)
C.check(f"H.1 square: every ordered pair of distinct vertices is a frame ({len(Fsq)} = 12)", len(Fsq) == 12)
Hx = [(Fr(1), Fr(0)), (Fr(1), Fr(1)), (Fr(0), Fr(1)), (Fr(-1), Fr(0)), (Fr(-1), Fr(-1)), (Fr(0), Fr(-1))]
Fhx = frames_of(Hx)
C.check(f"H.2 hexagon: 18 ordered frames, each vertex with its two distance-2 and its opposite vertex ({len(Fhx)})",
        sorted(Fhx) == sorted([(i, (i + d) % 6) for i in range(6) for d in (2, 3, 4)]))
# D6 acting on the affine-regular hexagon: rotation x -> (x0 - x1, x0) maps v_k -> v_{k+1}
R6 = ((Fr(1), Fr(-1)), (Fr(1), Fr(0)))
S6 = ((Fr(0), Fr(1)), (Fr(1), Fr(0)))
g6 = [perm_of_linear(R6, Hx), perm_of_linear(S6, Hx)]
C.check(f"H.3 D6 generators act on the hexagon: {g6}", all(g is not None for g in g6))
orbs = []
rest = set(Fhx)
while rest:
    s = min(rest)
    o = orbit_ordered_pairs(g6, s)
    orbs.append(o)
    rest -= o
mid0 = lambda f: vadd(Hx[f[0]], Hx[f[1]]) == (0, 0)  # noqa: E731
C.check(f"H.4 SS fails for the hexagon: {len(orbs)} orbits of sizes {sorted(len(o) for o in orbs)}; each orbit is "
        "uniform in 'midpoint = centroid' (the theorem's invariant separates them)",
        len(orbs) == 2 and all(len({mid0(f) for f in o}) == 1 for o in orbs))
# strong self-duality countercontrol: the square with D4-invariant forms (scalar Q = I) fails
ok_sq = True
for v in Sq:
    # M = diag(alpha, lambda I), alpha, lambda > 0 (the D4-invariant forms): M(1, v) is a facet normal only if it
    # vanishes on two ADJACENT generators w1, w2, i.e. v.w1 = v.w2 = -alpha/lambda < 0
    adj_equal = [(w1, w2) for w1, w2 in zip(Sq, Sq[1:] + Sq[:1]) if dot(v, w1) == dot(v, w2) and dot(v, w1) < 0]
    ok_sq &= adj_equal == []
C.check("H.5 strong self-duality test rejects the square: no D4-invariant diag(alpha, lambda I) maps a generator to "
        "a facet normal (no generator has equal negative pairings with two adjacent generators)", ok_sq)

# ----------------------------------------------------------------------------- BD: the bidisk D x D

print("== BD the bidisk D x D = conv(S1 x S1) in R^4 (the torus orbitope)")


def bd_effect(a1, a2):
    """e(w) = 1/2 + a1.w1 + a2.w2 is an effect on D x D iff |a1| + |a2| <= 1/2 (support function |a1|+|a2|).
    Exact test on rational a's with rational norms is done by the caller."""
    return lambda w: Fr(1, 2) + dot(a1, w[0]) + dot(a2, w[1])


x = ((Fr(1), Fr(0)), (Fr(1), Fr(0)))
f1 = (x, ((Fr(-1), Fr(0)), (Fr(-1), Fr(0))))                 # antipodal frame
f2 = (x, ((Fr(-1), Fr(0)), (Fr(1), Fr(0))))                  # y1 = -x1, y2 = x2
e1 = bd_effect((Fr(1, 4), Fr(0)), (Fr(1, 4), Fr(0)))         # |a1|+|a2| = 1/2
e2 = bd_effect((Fr(1, 2), Fr(0)), (Fr(0), Fr(0)))            # |a1|+|a2| = 1/2
C.check("BD.1 both pairs are frames: explicit effects (|a1|+|a2| = 1/2) give 1 on the first and 0 on the second "
        "member", e1(f1[0]) == 1 and e1(f1[1]) == 0 and e2(f2[0]) == 1 and e2(f2[1]) == 0)


def mid4(f):
    return tuple(tuple((p + q) / 2 for p, q in zip(f[0][k], f[1][k])) for k in range(2))


C.check(f"BD.2 SS fails: midpoint(f1) = {mid4(f1)} is the centroid 0, midpoint(f2) = {mid4(f2)} is not; every affine "
        "automorphism fixes the centroid (TB:356), so none maps f1 to f2",
        mid4(f1) == ((0, 0), (0, 0)) and mid4(f2) != ((0, 0), (0, 0)))
C.check("BD.3 the frame members are extreme points (both components unit vectors); capacity two by central "
        "symmetry about 0 (Lemma D, KF:632, written)",
        all(dot(z[0], z[0]) == 1 and dot(z[1], z[1]) == 1 for f in (f1, f2) for z in f))
# BP fails: the centre ((1,0),(0,0)) of the face {w1 = (1,0)} x D
b = ((Fr(1), Fr(0)), (Fr(0), Fr(0)))
C.check("BD.4 BP fails: ((1,0),(0,0)) is certain for the proper effect e2 (so a boundary state) and is the midpoint "
        "of the distinct states ((1,0),(1,0)) and ((1,0),(-1,0))",
        e2(b) == 1 and e2(((Fr(-1), Fr(0)), (Fr(0), Fr(0)))) == 0 and
        mid4((((Fr(1), Fr(0)), (Fr(1), Fr(0))), ((Fr(1), Fr(0)), (Fr(-1), Fr(0))))) == b)


# Spec2 on exact samples: w = (A*u, B*v) with rational unit u, v and B <= A <= 1; written construction:
#   x2 = v, y2 = -v, p = (1+B)/2; x1, y1 unit with p x1 + (1-p) y1 = A u, <A u, x1> = mu = (A^2 + B)/(1 + B)
def rat_sqrt(q):
    q = Fr(q)
    if q < 0:
        return None
    from math import isqrt
    n, d = q.numerator, q.denominator
    rn, rd = isqrt(n), isqrt(d)
    return Fr(rn, rd) if rn * rn == n and rd * rd == d else None


samples = []
for A in [Fr(a, 20) for a in range(1, 21)]:
    for B in [Fr(c, 20) for c in range(0, 21)]:
        if B > A:
            continue
        mu = (A * A + B) / (1 + B)
        r = rat_sqrt(1 - (mu / A) ** 2) if A != 0 else None
        if r is not None and abs(mu / A) <= 1:
            samples.append((A, B, mu, r))
u, uperp, v = (Fr(3, 5), Fr(4, 5)), (Fr(-4, 5), Fr(3, 5)), (Fr(5, 13), Fr(12, 13))
spec_ok = True
nsamp = 0
for (A, B, mu, r) in samples:
    p = (1 + B) / 2
    w1, w2 = vscale(A, u), vscale(B, v)
    x1 = vadd(vscale(mu / A, u), vscale(r, uperp))
    if p == 1:
        y1 = x1
        spec_ok &= (w1 == x1)
    else:
        y1 = vscale(1 / (1 - p), vsub(w1, vscale(p, x1)))
    x2, y2 = v, vscale(-1, v)
    lhs = (vadd(vscale(p, x1), vscale(1 - p, y1)), vadd(vscale(p, x2), vscale(1 - p, y2)))
    spec_ok &= lhs == (w1, w2) and dot(x1, x1) == 1 and dot(y1, y1) == 1 and dot(x2, x2) == 1 \
        and 0 <= p <= 1
    nsamp += 1
C.check(f"BD.5 Spec2 holds on {nsamp} exact rational samples (B <= A, the written construction: x2 = v, y2 = -v, "
        "p = (1+B)/2, unit x1, y1 solving p x1 + (1-p) y1 = A u); each decomposition is along a frame (y2 = -x2)",
        spec_ok and nsamp >= 5)

# ----------------------------------------------------------------------------- ST: Stiefel orbitope conv V2(R^3)

print("== ST the Stiefel orbitope conv V2(R^3) = {X in R^(3x2) : ||X||_op <= 1}")
Aa = ((1, 0), (0, 1), (0, 0))
Bb = ((-1, 0), (0, 1), (0, 0))
negA = ((-1, 0), (0, -1), (0, 0))


def colorth(X):
    c0 = [X[i][0] for i in range(3)]
    c1 = [X[i][1] for i in range(3)]
    return dot(c0, c0) == 1 and dot(c1, c1) == 1 and dot(c0, c1) == 0


eST = lambda X: Fr(1, 2) + Fr(1, 2) * X[0][0]  # noqa: E731  (|X_11| <= ||X||_op <= 1)
C.check("ST.1 (A, -A) and (A, B) are frames of extreme points (orthonormal columns): the effect (1 + X_11)/2 is 1 on A, "
        "0 on -A and on B", colorth(Aa) and colorth(Bb) and colorth(negA) and eST(Aa) == 1 and eST(negA) == 0
        and eST(Bb) == 0)
midAB = tuple(tuple(Fr(Aa[i][j] + Bb[i][j], 2) for j in range(2)) for i in range(3))
C.check(f"ST.2 SS fails: midpoint(A,-A) = 0 = centroid, midpoint(A,B) = {midAB} != 0",
        midAB != ((0, 0), (0, 0), (0, 0)))
c_face = ((1, 0), (0, 0), (0, 0))
C.check("ST.3 BP fails: [e1, 0] is certain for (1 + X_11)/2 (proper) and is the midpoint of [e1, e2] and [e1, -e2]",
        eST(c_face) == 1 and tuple(tuple(Fr(p + q, 2) for p, q in zip(r1, r2)) for r1, r2 in
                                  zip(((1, 0), (0, 1), (0, 0)), ((1, 0), (0, -1), (0, 0)))) == c_face)
# Spec2 exact instance: X = [[s1, 0], [0, s2], [0, 0]], s2 <= s1: decompose along the smaller singular value
cands = [(A, B) for (A, B, mu_, r_) in samples if 0 < B < A < 1]
s1, s2 = cands[0]
p = (1 + s2) / 2
mu = (s1 * s1 + s2) / (1 + s2)
r = rat_sqrt(1 - mu * mu / (s1 * s1))
ok_st = r is not None
if ok_st:
    a = (mu / s1, Fr(0), r)                 # in u^perp = span(e1, e3), u = e2
    bvec = tuple((s1 * (1 if k == 0 else 0) - p * a[k]) / (1 - p) for k in range(3))
    AX = ((a[0], 0), (a[1], 1), (a[2], 0))  # columns: w-column a, v-column u = e2
    BX = ((bvec[0], 0), (bvec[1], -1), (bvec[2], 0))
    comb = tuple(tuple(p * AX[i][j] + (1 - p) * BX[i][j] for j in range(2)) for i in range(3))
    ok_st = colorth(AX) and colorth(BX) and comb == ((s1, 0), (0, s2), (0, 0))
C.check(f"ST.4 Spec2 exact instance: X = [[{s1}, 0], [0, {s2}], [0, 0]] is p A + (1-p) B with A, B in V2 and A e2 = -B e2 "
        "(a frame)", ok_st)

# ----------------------------------------------------------------------------- Q3: the qutrit

print("== Q3 the qutrit: frames are orthonormal triples")
rho = [[Fr(1, 2), 0, 0], [0, Fr(1, 2), 0], [0, 0, 0]]
Pm = [[1, 0, 0], [0, 1, 0], [0, 0, 0]]
tr = lambda X, Y: sum(X[i][j] * Y[j][i] for i in range(3) for j in range(3))  # noqa: E731
P2 = [[0, 0, 0], [0, 0, 0], [0, 0, 1]]
C.check("Q3.1 BP fails: diag(1/2,1/2,0) is certain for the proper effect diag(1,1,0) and is the midpoint of "
        "|0><0| and |1><1|", tr(Pm, rho) == 1 and tr(Pm, P2) == 0)
# Spec with triples (exact instance): rho = sum_k lambda_k |u_k><u_k| with a rational orthonormal basis
U = [[Fr(1, 3), Fr(2, 3), Fr(2, 3)], [Fr(2, 3), Fr(1, 3), Fr(-2, 3)], [Fr(2, 3), Fr(-2, 3), Fr(1, 3)]]
orth = all(sum(U[i][k] * U[j][k] for k in range(3)) == (1 if i == j else 0) for i in range(3) for j in range(3))
lam = [Fr(1, 2), Fr(1, 3), Fr(1, 6)]
rhoU = [[sum(lam[k] * U[i][k] * U[j][k] for k in range(3)) for j in range(3)] for i in range(3)]
C.check("Q3.2 Spec (triples) instance: a rational orthonormal basis and weights give a state that is a mixture of a "
        "perfectly distinguishable triple; the triple's projectors sum to 1", orth and
        sum(rhoU[i][i] for i in range(3)) == 1)
# SS (triples) instance: the real orthogonal U maps the standard frame to the U-frame, in order
UtU = [[sum(U[k][i] * U[k][j] for k in range(3)) for j in range(3)] for i in range(3)]
C.check("Q3.3 SS (triples) instance: the orthogonal (so unitary) U, U^T U = 1, maps the ordered standard frame "
        "(e0, e1, e2) to the ordered frame of its columns", UtU == [[1, 0, 0], [0, 1, 0], [0, 0, 1]])
proj = [[[1 if (i == k and j == k) else 0 for j in range(3)] for i in range(3)] for k in range(3)]
C.check("Q3.4 capacity three: the diagonal projectors sum to 1 and tr(P_k |j><j|) = delta_kj",
        all(tr(proj[k], proj[j]) == (1 if k == j else 0) for k in range(3) for j in range(3)) and
        [[sum(proj[k][i][j] for k in range(3)) for j in range(3)] for i in range(3)] == [[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# ----------------------------------------------------------------------------- M: the Bloch ball (positive control)

print("== M the Bloch ball (positive control for the mechanism)")
n = (Fr(2, 3), Fr(1, 3), Fr(2, 3))
e3 = (Fr(0), Fr(0), Fr(1))


def householder(w):
    ww = dot(w, w)
    return tuple(tuple((1 if i == j else 0) - 2 * w[i] * w[j] / ww for j in range(3)) for i in range(3))


def mm3(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)) for i in range(3))


def det3(M):
    return (M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1]) - M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0])
            + M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]))


H1 = householder(vsub(e3, n))
wperp = (Fr(1, 3), Fr(-2, 3), Fr(0))
wperp = vsub(wperp, vscale(dot(wperp, n), n))
H2 = householder(wperp)
Rot = mm3(H2, H1)
C.check("M.1 SS witness: a rational rotation (det +1, orthogonal) maps the ordered frame (e3, -e3) to (n, -n), "
        "n = (2/3, 1/3, 2/3)", mat_vec(Rot, e3) == n and mat_vec(Rot, vscale(-1, e3)) == vscale(-1, n)
        and det3(Rot) == 1 and mm3(Rot, tuple(zip(*Rot))) == tuple(tuple(Fr(int(i == j)) for j in range(3))
                                                                  for i in range(3)))
xs = [vscale(Fr(t, 7), n) for t in range(-7, 8)]
C.check("M.2 Spec2 on the ball: each sample x = t n is ((1+t)/2) n + ((1-t)/2)(-n), an antipodal frame",
        all(vadd(vscale((1 + Fr(t, 7)) / 2, n), vscale((1 - Fr(t, 7)) / 2, vscale(-1, n))) == xs[t + 7]
            for t in range(-7, 8)))
C.check("M.3 mechanism: every antipodal frame has midpoint 0 = centroid; BP holds on the ball (strictly convex; "
        "kernel singletonFaces_closedBall KF:658)", vscale(Fr(1, 2), vadd(n, vscale(-1, n))) == (0, 0, 0))

# ----------------------------------------------------------------------------- C2: the Caratheodory orbitope

print("== C2 the Caratheodory orbitope conv{(cos t, sin t, cos 2t, sin 2t)}: capacity three, BP fails")
import sympy as sp  # noqa: E402

t = sp.symbols("t", real=True)
ts = [sp.Integer(0), 2 * sp.pi / 3, 4 * sp.pi / 3]
gam = lambda tt: [sp.cos(tt), sp.sin(tt), sp.cos(2 * tt), sp.sin(2 * tt)]  # noqa: E731


def eff_coeffs(a, bb):
    """(4/9)(1 - cos(t-a))(1 - cos(t-b)) written as c0 + c . (cos t, sin t, cos 2t, sin 2t)"""
    ca, sa, cb, sb = sp.cos(a), sp.sin(a), sp.cos(bb), sp.sin(bb)
    c0 = 1 + sp.cos(bb - a) / 2
    c = [-(ca + cb), -(sa + sb), sp.cos(a + bb) / 2, sp.sin(a + bb) / 2]
    return [sp.radsimp(sp.Rational(4, 9) * c0)] + [sp.radsimp(sp.Rational(4, 9) * ci) for ci in c]


E = [eff_coeffs(ts[1], ts[2]), eff_coeffs(ts[0], ts[2]), eff_coeffs(ts[0], ts[1])]
evalE = lambda co, pt: sp.simplify(co[0] + sum(co[k + 1] * pt[k] for k in range(4)))  # noqa: E731
delta = all(sp.simplify(evalE(E[i], gam(ts[j])) - (1 if i == j else 0)) == 0 for i in range(3) for j in range(3))
sumE = [sp.simplify(sum(E[i][k] for i in range(3))) for k in range(5)]
cs, sn = sp.symbols("c s", real=True)


def on_circle_zero(expr):
    ex = sp.expand(sp.expand_trig(expr)).subs({sp.sin(t): sn, sp.cos(t): cs})
    ex = sp.expand(ex)
    _, rem = sp.reduced(ex, [sn ** 2 + cs ** 2 - 1], sn, cs)
    return sp.simplify(rem) == 0


ident = all(on_circle_zero(evalE(E[i], gam(t)) - sp.Rational(4, 9) *
                           (1 - sp.cos(t - [ts[1], ts[0], ts[0]][i])) *
                           (1 - sp.cos(t - [ts[2], ts[2], ts[1]][i]))) for i in range(3))
C.check("C2.1 capacity >= 3: three affine functionals with E_i(gamma(t_j)) = delta_ij, sum = 1 identically, and "
        "E_i(gamma(t)) = (4/9)(1-cos(t-t_j))(1-cos(t-t_k)) >= 0 on the curve (hence effects on the hull)",
        delta and sumE == [1, 0, 0, 0, 0] and ident)
mid = [sp.simplify((a + bb) / 2) for a, bb in zip(gam(ts[1]), gam(ts[2]))]
C.check("C2.2 BP fails: E_0 vanishes at gamma(t_1) and gamma(t_2), so their midpoint is certain for the effect "
        "E_1 + E_2 = 1 - E_0, which is proper (value 0 at gamma(t_0)); the midpoint of two distinct points is not extreme",
        sp.simplify(evalE(E[0], mid)) == 0 and sp.simplify(evalE(E[1], gam(ts[0])) + evalE(E[2], gam(ts[0]))) == 0)

sys.exit(C.finish("BP-SPEC-SS: the controls hold; Spec2 + SS (+ capacity two) give BP and pure-state transitivity "
                  "(written Theorem BP-S); each premise and the capacity-two scope are load-bearing: pentagon "
                  "(SS, self-dual, cap 2; no Spec2, no BP), bidisk and Stiefel (Spec2, cap 2; no SS, no BP), qutrit "
                  "(Spec, SS with triples; no BP), Caratheodory (cap >= 3; no BP)"))
