"""A33 research: structure of Isom(X) cap Stab(P) from derivation B's permutations alone."""
import pickle, itertools
from collections import Counter
from circles import N
d = pickle.load(open('finite.pkl', 'rb'))
pts, lab, G = d['pts'], d['lab'], d['iso']
n = len(pts)
Gs = set(G)
ident = tuple(range(n))
def mul(p, q):            # (p*q)(x) = p(q(x))
    return tuple(p[q[x]] for x in range(n))
def inv(p):
    out = [0] * n
    for x, y in enumerate(p): out[y] = x
    return tuple(out)

# circles as point sets; V = points on >= 2 circles
circ = [frozenset(lab[r, k] for k in range(4)) for r in range(N)]
V = sorted(x for x in range(n) if sum(x in c for c in circ) >= 2)
print('closure: identity in G', ident in Gs, '| closed under product (sample 2000):',
      all(mul(p, q) in Gs for p, q in itertools.islice(itertools.product(G[:50], G[:40]), 2000)))
print('V (points on several circles):', len(V), 'each on', Counter(sum(x in c for c in circ) for x in V))
# incidence graph: vertices V, edges = circles (each through two points of V)
ends = [tuple(sorted(set(circ[r]) & set(V))) for r in range(N)]
print('each circle through', Counter(len(e) for e in ends), 'points of V')
adj = {v: set() for v in V}
for a, b in ends: adj[a].add(b); adj[b].add(a)
# bipartite with parts of size 3 and complete?
col = {V[0]: 0}; stack = [V[0]]
while stack:
    v = stack.pop()
    for u in adj[v]:
        if u not in col: col[u] = 1 - col[v]; stack.append(u)
bip = all(col[a] != col[b] for a, b in ends)
parts = [[v for v in V if col[v] == c] for c in (0, 1)]
k33 = bip and len(ends) == 9 and len(set(ends)) == 9 and all(len(p) == 3 for p in parts)
print('incidence graph is K33:', k33)
# action on circles
def circle_perm(p):
    return tuple(next(s for s in range(N) if frozenset(p[x] for x in circ[r]) == circ[s]) for r in range(N))
cp = {p: circle_perm(p) for p in G}
Gc = set(cp.values())
K = [p for p in G if cp[p] == tuple(range(N))]
print('|G| =', len(G), ' |G_circle| =', len(Gc), ' |K| =', len(K))
# K elementary abelian 2-group of rank 9, generated by single-circle conjugations?
print('K abelian:', all(mul(a, b) == mul(b, a) for a in K[:64] for b in K[:64]),
      ' exponent 2:', all(mul(a, a) == ident for a in K))
single = []
for r in range(N):
    # the map fixing every point except swapping the two non-V points of circle r
    nv = sorted(set(circ[r]) - set(V))
    p = list(range(n)); p[nv[0]], p[nv[1]] = nv[1], nv[0]; p = tuple(p)
    single.append(p)
print('single-circle conjugations in G:', [p in Gs for p in single])
span = {ident}
for g in single:
    span |= {mul(g, x) for x in span}
print('they generate K:', span == set(K))
# incidence automorphisms of K33 acting on edges vs realized circle permutations
inc = set()
for vp in itertools.permutations(V):
    m = dict(zip(V, vp))
    img = [tuple(sorted((m[a], m[b]))) for a, b in ends]
    if sorted(img) == sorted(ends):
        inc.add(tuple(ends.index(e) for e in img))
print('incidence-graph automorphisms (on edges):', len(inc), ' all realized by isometries:', inc == Gc)
# splitting: is there a subgroup H of order 72 with H cap K = 1 mapping onto G_circle?
# search: choose one lift per generator of G_circle and test closure is order 72
pickle.dump({'cp': cp, 'K': K, 'V': V, 'ends': ends, 'circ': circ, 'single': single}, open('analyse.pkl', 'wb'))
