#!/usr/bin/env python3
"""Read-only provenance check of the owner's confirmation comments on PR #806 (KT4-PREM-1).

Decision rule, fixed before the comments exist. A comment is accepted as the owner's confirmation
of subject X (F or E) iff ALL of:
  A1  it is an issue comment on PR #806 (its issue_url ends in /issues/806);
  A2  user.login == amaybaum and author_association == OWNER;
  A3  performed_via_github_app is null (posted directly, not through any app); any app is reported
      by its slug, and the claude app is a hard reject;
  A4  the body carries no Claude Code footer (no "Generated by [Claude Code]", no "claude.ai/code");
  A5  the body contains X's full SHA and the id of X's record comment, and "KT4-PREM-1";
  A6  the body does not contain the other subject's full SHA (one subject per comment);
  A7  it was created after X's record comment and has not been edited (created_at == updated_at).
Informational only (never decides): whether the body equals the owner's recommended wording.
Also re-checks the stop conditions: PR #806 head == E, main == D, PR open, draft, not merged.

Usage: check_confirmations.py [--ids ID ...]   (default: every comment that is not one of the four
known agent-posted comments). Exit 0 iff exactly one accepted comment per subject and the stop
conditions hold.
"""
import json
import subprocess
import sys

REPO = "amaybaum/incompleteness"
PR = 806
D = "bcbc516fe78eb7aa303a41e7bc9cc106dd63bd58"
SUBJ = {
    "F": {"sha": "7ae032174699190086f1e54b7adb7aeb1a80a726", "record": 6087571713},
    "E": {"sha": "86f26c87c750601583f382ed00baeb8fee32ef26", "record": 6088471219},
}
AGENT_POSTED = {6087395574, 6087571713, 6088326237, 6088471219}
# The owner's final wording (informational comparison only; A1-A7 decide).
RECOMMENDED = {
    "F": "I confirm my earlier in-session designation of F = `7ae032174699190086f1e54b7adb7aeb1a80a726` "
         "for KT4-PREM-1, made before execution.\n\nThis confirms my original designation recorded in "
         "comment 6087571713. It is not a new designation, and F remains unchanged.",
    "E": "I confirm my earlier in-session designation of E = `86f26c87c750601583f382ed00baeb8fee32ef26` "
         "for KT4-PREM-1.\n\nThis confirms my original designation recorded in comment 6088471219. "
         "It is not a new designation, and E remains unchanged.",
}
FOOTER_MARKS = ("Generated by [Claude Code]", "claude.ai/code")


def api(path, paginate=False):
    cmd = ["gh", "api", path] + (["--paginate"] if paginate else [])
    out = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout
    if paginate:
        # --paginate concatenates JSON arrays; merge them
        dec, items, i = json.JSONDecoder(), [], 0
        out = out.strip()
        while i < len(out):
            obj, j = dec.raw_decode(out, i)
            items.extend(obj if isinstance(obj, list) else [obj])
            i = j
            while i < len(out) and out[i].isspace():
                i += 1
        return items
    return json.loads(out)


def norm(s):
    return " ".join(s.split())


def evaluate(c, x, created):
    s = SUBJ[x]
    other = SUBJ["E" if x == "F" else "F"]["sha"]
    body = c.get("body") or ""
    app = (c.get("performed_via_github_app") or {}).get("slug")
    res = [
        ("A1", c["issue_url"].endswith(f"/issues/{PR}"), c["issue_url"].rsplit("/", 2)[-1]),
        ("A2", c["user"]["login"] == "amaybaum" and c["author_association"] == "OWNER",
         f'{c["user"]["login"]}/{c["author_association"]}'),
        ("A3", app is None, f"app={app}"),
        ("A4", not any(m in body for m in FOOTER_MARKS), "footer" if any(m in body for m in FOOTER_MARKS) else "no footer"),
        ("A5", s["sha"] in body and str(s["record"]) in body and "KT4-PREM-1" in body,
         f'sha={s["sha"] in body} ref={str(s["record"]) in body} round={"KT4-PREM-1" in body}'),
        ("A6", other not in body, "other sha present" if other in body else "one subject"),
        ("A7", c["created_at"] > created[s["record"]] and c["created_at"] == c["updated_at"],
         f'created {c["created_at"]} updated {c["updated_at"]}'),
    ]
    return res, norm(body) == norm(RECOMMENDED[x])


def self_test():
    """Offline: a synthetic direct owner comment must be accepted; each single-criterion mutation
    must be rejected on exactly that criterion."""
    created = {SUBJ["F"]["record"]: "2026-10-09T19:13:41Z", SUBJ["E"]["record"]: "2026-10-09T20:11:58Z"}

    def base(x):
        return {"issue_url": f"https://api.github.com/repos/{REPO}/issues/{PR}",
                "user": {"login": "amaybaum"}, "author_association": "OWNER",
                "performed_via_github_app": None, "body": RECOMMENDED[x],
                "created_at": "2026-10-10T12:00:00Z", "updated_at": "2026-10-10T12:00:00Z"}

    other = {"F": "E", "E": "F"}
    muts = {
        "A1": lambda c, x: c.update(issue_url=c["issue_url"][:-3] + "805"),
        "A2": lambda c, x: c.update(author_association="COLLABORATOR"),
        "A3": lambda c, x: c.update(performed_via_github_app={"slug": "claude"}),
        "A4": lambda c, x: c.update(body=c["body"] + "\n---\n_Generated by [Claude Code](https://claude.ai/code)_"),
        "A5": lambda c, x: c.update(body=c["body"].replace(str(SUBJ[x]["record"]), "6000000000")),
        "A6": lambda c, x: c.update(body=c["body"] + " " + SUBJ[other[x]]["sha"]),
        "A7": lambda c, x: c.update(updated_at="2026-10-10T12:05:00Z"),
    }
    n = bad = 0
    for x in ("F", "E"):
        res, verb = evaluate(base(x), x, created)
        n += 1
        if not (all(r[1] for r in res) and verb):
            bad += 1
            print(f"self-test FAIL: positive control {x} not accepted: {res}")
        for name, m in muts.items():
            c = base(x)
            m(c, x)
            res, _ = evaluate(c, x, created)
            failed = [r[0] for r in res if not r[1]]
            n += 1
            if failed != [name]:
                bad += 1
                print(f"self-test FAIL: mutation {name} on {x} failed {failed}")
    print(f"self-test: {n - bad}/{n} {'OK' if not bad else 'FAILED'}")
    return 0 if not bad else 1


def main(argv):
    if "--self-test" in argv:
        return self_test()
    ids = [int(a) for a in argv[argv.index("--ids") + 1:]] if "--ids" in argv else None
    pr = api(f"repos/{REPO}/pulls/{PR}")
    main_sha = api(f"repos/{REPO}/branches/main")["commit"]["sha"]
    stop = [
        ("head == E", pr["head"]["sha"] == SUBJ["E"]["sha"], pr["head"]["sha"]),
        ("main == D", main_sha == D, main_sha),
        ("open, draft, unmerged", pr["state"] == "open" and pr["draft"] and not pr["merged"],
         f'{pr["state"]} draft={pr["draft"]} merged={pr["merged"]}'),
    ]
    for name, ok, val in stop:
        print(f'STOP-CHECK {"ok  " if ok else "FAIL"} {name}: {val}')
    comments = api(f"repos/{REPO}/issues/{PR}/comments", paginate=True)
    created = {c["id"]: c["created_at"] for c in comments}
    if ids is None:
        pool = [c for c in comments if c["id"] not in AGENT_POSTED]
    else:
        pool = [api(f"repos/{REPO}/issues/comments/{i}") for i in ids]
    print(f"comments on #{PR}: {len(comments)}; evaluated: {len(pool)}")
    accepted = {"F": [], "E": []}
    for c in pool:
        for x in ("F", "E"):
            if SUBJ[x]["sha"] not in (c.get("body") or ""):
                continue
            res, verbatim = evaluate(c, x, created)
            ok = all(r[1] for r in res)
            print(f'{c["id"]} as {x}: {"ACCEPT" if ok else "REJECT"}  ' +
                  "  ".join(f'{n}:{"ok" if v else "FAIL"}({d})' for n, v, d in res) +
                  f"  verbatim-recommended={verbatim}")
            if ok:
                accepted[x].append(c["id"])
    for x in ("F", "E"):
        print(f"{x}: accepted {accepted[x] or 'none'}")
    good = all(v for _, v, _ in stop) and all(len(accepted[x]) == 1 for x in ("F", "E"))
    print("RESULT", "PROVENANCE OK" if good else "NOT SATISFIED")
    return 0 if good else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
