"""P2 (node N2, decisive) -- the Lie algebra of every connected group of normalization-preserving
reversible maps of an admissible two-ball cone (min <= K <= maxCone) that contains local SO(3)^2.

Setting: W 3 = R^4 (x) R^4 with DIM-1's coordinates. X ranges over 16x16 real matrices with
u o X = 0 (u = the (0,0) coordinate, normalization) -- 240 unknowns.

First-order (necessary) condition V1: if exp(tX) preserves a cone K with min <= K <= maxCone, then for every
pure product state w = hom x (x) hom y (|x| = |y| = 1) and every product effect E = (1,a) (x) (1,b) with
E(w) = 0 (a = -x or b = -y), t -> E(exp(tX) w) is >= 0 and vanishes at t = 0, so E(X w) = 0.  Since the
(1,b), |b| = 1, span R^4 this is:  (1,-x)^T (X w) = 0  and  (X w)(1,-y) = 0  (8 linear conditions in X).

Decision rule (fixed before the run):
  * upper bound: dim V1 <= 240 - rank(conditions at finitely many rational pairs), exact rational rank;
  * lower bound: an explicit subspace verified to satisfy the conditions for ALL unit x, y (sympy, exact);
  * controls: l = so(3)+so(3) in V1; su(4)-image and its PT_B conjugate in V1 (both cones admissible);
    countercontrol: a generic element of so(15) on the traceless part fails V1, and the element of the
    algebra generated by M1 + M2 outside l + M1 + M2 fails V1;
  * the classification verdict is printed only if lower bound == upper bound and all controls pass.
Usage: python3 -I p2_lie_classification.py
"""
import sys
import os
import time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from eqclib import *  # noqa
import sympy as sp

t0 = time.time()
rep = Report("P2 Lie classification")

# ------------------------------------------------------------------ the candidate pieces
L_ = [ad_herm(SIG2[(i, 0)]) for i in (1, 2, 3)] + [ad_herm(SIG2[(0, j)]) for j in (1, 2, 3)]
M1 = [ad_herm(SIG2[(i, j)]) for i in (1, 2, 3) for j in (1, 2, 3)]
RB = actT_mat(REFLY)
PB = actT_mat(MINUS)
M2 = [matmul(matmul(RB, m), RB) for m in M1]
PHI = [matmul(matmul(PB, m), PB) for m in M1]  # phi(v) = Pi_B v Pi_B, the l-module map M1 -> M2

flatL, flatM1, flatM2 = [flat(m) for m in L_], [flat(m) for m in M1], [flat(m) for m in M2]
rep.check("2.0a dim l = 6, dim M1 = 9, dim M2 = 9, dim(l + M1 + M2) = 24",
          span_rank(flatL) == 6 and span_rank(flatM1) == 9 and span_rank(flatM2) == 9
          and span_rank(flatL + flatM1 + flatM2) == 24)
rep.check("2.0b span(phi(M1)) = M2 (phi = conjugation by Pi_B = actT(-I))",
          span_rank(flatM2 + [flat(m) for m in PHI]) == 9)

# l is the derivative of the kernel lifts actC R, actT R (so(3) generators, homogenized)
def gen(i, j):
    Lm = [[0] * 3 for _ in range(3)]
    Lm[i][j], Lm[j][i] = 1, -1
    return Lm


def hom_gen_T(Lm):  # derivative of actT exp(tL): w -> w * homMap(L)^T  (unit row/col zero)
    H = zeros(4, 4)
    for a in range(3):
        for b in range(3):
            H[a + 1][b + 1] = Fr(Lm[a][b])
    M = zeros(16, 16)
    for (m, n) in IDX:
        for l_ in range(4):
            if H[n][l_] != 0:
                M[4 * m + n][4 * m + l_] = H[n][l_]
    return M


def hom_gen_C(Lm):
    H = zeros(4, 4)
    for a in range(3):
        for b in range(3):
            H[a + 1][b + 1] = Fr(Lm[a][b])
    M = zeros(16, 16)
    for (m, n) in IDX:
        for k in range(4):
            if H[m][k] != 0:
                M[4 * m + n][4 * k + n] = H[m][k]
    return M


kern_l = [flat(hom_gen_C(gen(i, j))) for (i, j) in [(0, 1), (0, 2), (1, 2)]] + \
         [flat(hom_gen_T(gen(i, j))) for (i, j) in [(0, 1), (0, 2), (1, 2)]]
rep.check("2.0c l = span of the generators of the kernel lifts actC R, actT R (R in SO(3))",
          span_rank(kern_l) == 6 and span_rank(kern_l + flatL) == 6)

# ------------------------------------------------------------------ lower bound: symbolic V1 membership
s1, t1, s2, t2 = sp.symbols("s1 t1 s2 t2", real=True)


def sym_unit(s, t):
    d = 1 + s * s + t * t
    return [2 * s / d, 2 * t / d, (s * s + t * t - 1) / d]


xs, ys = sym_unit(s1, t1), sym_unit(s2, t2)
hx = [sp.Integer(1)] + xs
hy = [sp.Integer(1)] + ys
wsym = [hx[m] * hy[n] for (m, n) in IDX]
hmx = [sp.Integer(1)] + [-c for c in xs]
hmy = [sp.Integer(1)] + [-c for c in ys]


def v1_symbolic(X):
    V = [sum(sp.Rational(X[r][c].numerator, X[r][c].denominator) * wsym[c] for c in range(16) if X[r][c] != 0)
         for r in range(16)]
    V = [sp.Integer(0) if v == 0 else v for v in V]
    conds = []
    for n in range(4):
        conds.append(sum(hmx[m] * V[4 * m + n] for m in range(4)))
    for m in range(4):
        conds.append(sum(V[4 * m + n] * hmy[n] for n in range(4)))
    return all(sp.simplify(sp.together(c)) == 0 for c in conds) and all(X[0][c] == 0 for c in range(16))


ok_l = all(v1_symbolic(X) for X in L_)
ok_m1 = all(v1_symbolic(X) for X in M1)
ok_m2 = all(v1_symbolic(X) for X in M2)
rep.check("2.1a control: every element of l satisfies V1 for all unit x, y (symbolic)", ok_l)
rep.check("2.1b control: every element of M1 (su(4)-image complement) satisfies V1 symbolically", ok_m1)
rep.check("2.1c control: every element of M2 = R_B M1 R_B satisfies V1 symbolically", ok_m2)
print(f"  [lower bound done, {time.time() - t0:.1f}s]")

# ------------------------------------------------------------------ upper bound: exact rank of the conditions
NU = 240  # unknowns X[r][c], r = 1..15, c = 0..15


def cond_rows(x, y):
    w = vec(prodState(x, y))
    hmx_ = [Fr(1)] + [-F(c) for c in x]
    hmy_ = [Fr(1)] + [-F(c) for c in y]
    rows = []
    for n in range(4):
        row = [Fr(0)] * NU
        for m in range(4):
            r = 4 * m + n
            if r == 0:
                continue
            for c in range(16):
                if w[c] != 0:
                    row[(r - 1) * 16 + c] += hmx_[m] * w[c]
        rows.append(row)
    for m in range(4):
        row = [Fr(0)] * NU
        for n in range(4):
            r = 4 * m + n
            if r == 0:
                continue
            for c in range(16):
                if w[c] != 0:
                    row[(r - 1) * 16 + c] += hmy_[n] * w[c]
        rows.append(row)
    return rows


pool = [unit_vector(s, t) for (s, t) in [(0, 0), (1, 0), (0, 1), (2, 0), (0, 3), (1, 1), (Fr(1, 2), 2), (3, -1),
                                         (-2, Fr(1, 3)), (Fr(2, 5), Fr(-3, 4)), (5, 7), (-1, -4)]]
pool += [[1, 0, 0], [0, 1, 0], [0, 0, 1], [-1, 0, 0], [0, -1, 0]]
inc = IncRank(NU)
history = []
npairs = 0
for i, x in enumerate(pool):
    for j, y in enumerate(pool):
        for row in cond_rows(x, y):
            inc.add(row)
        npairs += 1
    history.append((npairs, inc.rank))
print("  rank history (pairs used, rank):", history)
up = NU - inc.rank
rep.note(f"upper bound: dim V1 <= {up} (rank {inc.rank} of the conditions from {npairs} rational pairs)")
print(f"  [upper bound done, {time.time() - t0:.1f}s]")


def unk(X):
    return [X[r][c] for r in range(1, 16) for c in range(16)]


basis24 = L_ + M1 + M2
rows_basis = list(inc.basis.values())
rep.check("2.2a each of the 24 basis elements satisfies every finite condition used (exact)",
          all(all(sum(a * b for a, b in zip(row, unk(X))) == 0 for row in rows_basis) for X in basis24))
rep.check("2.2b the explicit lower bound and the exact upper bound meet: dim V1 = 24 = dim(l + M1 + M2)",
          up == 24)

# ------------------------------------------------------------------ countercontrols
import random
rnd = random.Random(7)
A = zeros(16, 16)
for i in range(1, 16):
    for j in range(i + 1, 16):
        v = Fr(rnd.randint(-5, 5))
        A[i][j], A[j][i] = v, -v
sol_ns = inc.nullspace()
rep.check("2.3a countercontrol: a generic so(15) element (traceless block, rational) is NOT in V1",
          not span_rank(sol_ns + [unk(A)]) == span_rank(sol_ns))

# ------------------------------------------------------------------ bracket structure
def in_space(vecs, X):
    return span_rank(vecs + [flat(X)]) == span_rank(vecs)


l_sp, m1_sp, m2_sp = flatL, flatM1, flatM2
rep.check("2.4a [l, M1] in M1 and [l, M2] in M2",
          all(in_space(m1_sp, bracket(a, b)) for a in L_ for b in M1) and
          all(in_space(m2_sp, bracket(a, b)) for a in L_ for b in M2))
rep.check("2.4b [M1, M1] in l and [M2, M2] in l (both l+M1 and l+M2 are Lie algebras: the su(4) image "
          "and its R_B conjugate)",
          all(in_space(l_sp, bracket(a, b)) for a in M1 for b in M1) and
          all(in_space(l_sp, bracket(a, b)) for a in M2 for b in M2))
# phi is an l-module isomorphism M1 -> M2 and an involutive automorphism fixing l
rep.check("2.4c phi = Ad(Pi_B) fixes l pointwise, maps M1 onto M2, and phi^2 = id",
          all(matmul(matmul(PB, a), PB) == a for a in L_) and matmul(PB, PB) == eye(16))
# commutant of l on M1: dimension 1 (absolute irreducibility of (3,3))
# coordinates of ad_l on M1 in the basis M1 (solve exactly)
def coords(basis_flat, X):
    """Exact coordinates of flat(X) in the given basis (asserts membership)."""
    n = len(basis_flat)
    rows = [list(r) + [x] for r, x in zip(zip(*basis_flat), flat(X))]
    piv, R = rref(rows, n + 1)
    assert n not in piv, "not in span"
    c = [Fr(0)] * n
    for k, p in enumerate(piv):
        c[p] = R[k][n]
    return c


adl = []
for a in L_:
    adl.append([coords(flatM1, bracket(a, b)) for b in M1])  # adl[a][b] = coords of [a, M1_b]
# unknown 9x9 matrix C commuting: C . ad_a = ad_a . C for all a  (ad_a as matrix: column b = coords)
NUC = 81
crow = []
for k in range(6):
    Dm = [[adl[k][b][i] for b in range(9)] for i in range(9)]  # matrix of ad_a on M1 (rows i, cols b)
    for i in range(9):
        for j in range(9):
            row = [Fr(0)] * NUC
            # (C D)_{ij} - (D C)_{ij} = sum_t C_{it} D_{tj} - D_{it} C_{tj}
            for t in range(9):
                row[i * 9 + t] += Dm[t][j]
                row[t * 9 + j] -= Dm[i][t]
            crow.append(row)
rk = rank(crow, NUC)
rep.check("2.4d the commutant of ad(l) on M1 is 1-dimensional (M1 is absolutely irreducible: (3,3))",
          NUC - rk == 1, f"dim = {NUC - rk}")
# the mixed bracket C(v,w) = [v, phi w] + [phi v, w]
V1sp = [list(v) for v in sol_ns]  # nullspace basis in unknown coordinates (rows 1..15)
def in_V1(X):
    if any(X[0][c] != 0 for c in range(16)):
        return False
    return span_rank(V1sp + [unk(X)]) == span_rank(V1sp)


bad = None
for a_i, v in enumerate(M1):
    for b_i, w in enumerate(M1):
        Cvw = madd(bracket(v, PHI[b_i]), bracket(PHI[a_i], w))
        if not in_V1(Cvw):
            bad = (a_i, b_i, Cvw)
            break
    if bad:
        break
rep.check("2.5a some mixed bracket C(v,w) = [v, phi w] + [phi v, w] lies outside V1 "
          "(so no graph l + {a v + b phi v} with ab != 0 is a Lie algebra inside V1)", bad is not None,
          f"pair {bad[:2] if bad else None}")
if bad:
    rep.check("2.5b countercontrol: that element C(v,w) is NOT in V1 although it lies in the algebra "
              "generated by M1 + M2", not in_V1(bad[2]))
# the algebra generated by l + M1 + M2 is not inside V1 (so M1 + M2 together is excluded)
mix = None
for v in M1:
    for w in M2:
        Bm = bracket(v, w)
        if not in_V1(Bm):
            mix = Bm
            break
    if mix is not None:
        break
rep.check("2.5c some [M1, M2] bracket lies outside V1 (l + M1 + M2 is not a subalgebra of V1)", mix is not None)
print(f"  [brackets done, {time.time() - t0:.1f}s]")

# dimension of the Lie algebra generated by l + M1 + M2 (identification: expected so(15) = 105)
span_inc = IncRank(256)
for X in basis24:
    span_inc.add(flat(X))
frontier = list(basis24)
allel = list(basis24)
while frontier and span_inc.rank < 256:
    new = []
    for a in basis24:
        for b in frontier:
            Bm = bracket(a, b)
            if span_inc.add(flat(Bm)):
                new.append(Bm)
    allel += new
    frontier = new
rep.note(f"the Lie algebra generated by l + M1 + M2 has dimension {span_inc.rank} (so(15) has 105)")
print(f"  [generated algebra done, {time.time() - t0:.1f}s]")

rep.verdict("V1-CLASSIFIED: dim V1 = 24 = l + M1 + M2; the Lie subalgebras g with l <= g <= V1 are exactly "
            "l, l + M1 (the su(4) image) and l + M2 (its R_B conjugate)")
