"""Stage 1: regroup the 416 collected non-Dita {0,1} straight lines (scratchpad a38/first_wit.pkl, regenerated by a38/first_wit.py)
into orbits under gauge x stabilizer (1024, with transposition) x sign; record per orbit the {0,1} members among the 416 and their
supports; re-verify straightness exactly (direct Laurent identity) and non-membership in every census hull (strict and relaxed)."""
import sys, time, pickle, os
import numpy as np
from lib43 import *
t0 = time.time()
SCR = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
found = pickle.load(open(os.path.join(SCR, 'a38', 'first_wit.pkl'), 'rb'))
Es = [[[int(x) for x in row] for row in E] for E in found]
print('witnesses', len(Es))
PERMS = np.array([np.argsort(np.array(p)) for p, s_ in elems], dtype=np.int64)
SIGNS = np.array([s_ for p, s_ in elems], dtype=np.int64)
def gn(imgs): return imgs - imgs[:, :, :1] - imgs[:, :1, :] + imgs[:, :1, :1]
def canon(E):
    flat = np.array(E, dtype=np.int64).reshape(256); imgs = flat[PERMS] * SIGNS[:, None]
    imgs = np.concatenate([imgs, -imgs], 0).reshape(-1, 16, 16)
    flat2 = gn(imgs).reshape(-1, 256); order = np.lexsort(flat2.T[::-1])
    return tuple(flat2[order[0]].tolist())
# note: act 38's deep_wit canon applied the index permutation without the conjugation sign; the sign is included in the
# explicit x(+-1) factor there. Here both are applied; the orbit partition is the same either way (checked below).
def canon_nosign(E):
    flat = np.array(E, dtype=np.int64).reshape(256); imgs = flat[PERMS]
    imgs = np.concatenate([imgs, -imgs], 0).reshape(-1, 16, 16)
    flat2 = gn(imgs).reshape(-1, 256); order = np.lexsort(flat2.T[::-1])
    return tuple(flat2[order[0]].tolist())
def support(E): return sum(1 for r in E for x in r if x)
orb = {}; orb2 = {}
for idx, E in enumerate(Es):
    orb.setdefault(canon(E), []).append(idx); orb2.setdefault(canon_nosign(E), []).append(idx)
print('orbits', len(orb), '(without the conjugation sign on the permutation: %d; same partition: %s)' % (len(orb2), sorted(map(sorted, orb.values())) == sorted(map(sorted, orb2.values()))))
# exact re-verification
from lib43 import P40
def straight_direct(E):
    for i in range(16):
        for i2 in range(i + 1, 16):
            acc = {}
            for k in range(16):
                d = E[i][k] - E[i2][k]; acc[d] = acc.get(d, ZERO) + SIG[i][k] * SIG[i2][k].conj()
            if any(v != ZERO for v in acc.values()): return False
    return True
recs = []
for key, idxs in sorted(orb.items(), key=lambda kv: (min(support(Es[i]) for i in kv[1]), kv[0])):
    members = sorted(idxs, key=lambda i: (support(Es[i]), Es[i]))
    rep = Es[members[0]]
    st = straight_direct(rep)
    hs = census_hulls([rep]); hr = census_hulls([rep], relaxed=True)
    recs.append({'canon': key, 'members': members, 'supports': sorted(set(support(Es[i]) for i in members)), 'rep': rep,
                 'straight': st, 'hulls_strict': hs, 'hulls_relaxed': hr})
print('orbit  n  supports  straight  hulls(strict/relaxed)')
for t, r in enumerate(recs):
    print('%3d  %3d  %-12s %s  %s %s' % (t, len(r['members']), r['supports'], r['straight'], r['hulls_strict'], r['hulls_relaxed']))
print('all straight and in no hull:', all(r['straight'] and not r['hulls_strict'] and not r['hulls_relaxed'] for r in recs))
print('support histogram of orbit representatives:', {s: sum(1 for r in recs if r['supports'][0] == s) for s in sorted(set(r['supports'][0] for r in recs))})
pickle.dump({'Es': Es, 'recs': recs}, open(os.path.join(HERE, 'orbits.pkl'), 'wb'))
print('%.0fs' % (time.time() - t0))
